import { requireRole } from "../../../../src/auth/session";
import { hasRole, type Role } from "../../../../src/auth/permissions";
import { listClaimsForVerification } from "../../../../src/db/repository.console";
import { listVerificationArtifacts } from "../../../../src/db/repository.research";
import { ARTIFACT_VERIFIERS } from "../../../../src/verification/artifact-adapters";
import { recordExecution, reviewArtifact, submitArtifact } from "./actions";
type Props = { searchParams: Promise<{ claimId?: string; success?: string; error?: string }> };
const commands: Record<string, string> = { LEAN4: "lake build", COQ: "dune build", ISABELLE: "isabelle build -D .", SAT_SOLVER: "drat-trim proof.cnf proof.drat" };
export default async function ArtifactPage({ searchParams }: Props) {
  const session = await requireRole("RESEARCHER");
  const params = await searchParams;
  const [artifacts, claims] = await Promise.all([listVerificationArtifacts(params.claimId), listClaimsForVerification()]);
  const canReview = hasRole(session.user.role as Role, "REVIEWER");
  const canExecute = hasRole(session.user.role as Role, "EDITOR");
  return <><p className="section-kicker">Reproducibility</p><h1>Verification artifacts</h1><p className="lede">Artifacts are private drafts until editorial acceptance. A machine-checked badge is issued only after an accepted artifact has a successful, reproducible verifier execution.</p>
    {(params.success || params.error) && <p className={params.error ? "graph-message graph-error" : "graph-message"} role="status">{params.error ?? params.success}</p>}
    <section><h2>Submit an artifact</h2><form className="artifact-form" action={submitArtifact}><label>Claim<select name="claimId" required defaultValue={params.claimId ?? ""}><option value="" disabled>Choose Claim</option>{claims.map((claim) => <option key={claim.id} value={claim.id}>{claim.claimNumber} — {claim.valueExact} ({claim.status})</option>)}</select></label><label>Verifier<select name="verifier" required>{ARTIFACT_VERIFIERS.map((verifier) => <option key={verifier}>{verifier}</option>)}</select></label><label>HTTPS repository URL<input name="repositoryUrl" type="url" pattern="https://.*" required placeholder="https://github.com/org/proof"/></label><label>Full commit SHA<input name="commitHash" pattern="[0-9a-fA-F]{40}" minLength={40} maxLength={40} required placeholder="40 hexadecimal characters"/></label><label>Reported verifier version<input name="verifierVersion" placeholder="e.g. Lean 4.19.0"/></label><button type="submit">Submit for review</button></form></section>
    <section><div className="artifact-filter"><h2>Artifacts ({artifacts.length})</h2><form method="get"><select name="claimId" defaultValue={params.claimId ?? ""}><option value="">All Claims</option>{claims.map((claim) => <option key={claim.id} value={claim.id}>{claim.claimNumber}</option>)}</select><button type="submit">Filter</button></form></div>{artifacts.length ? artifacts.map((artifact) => <article className="candidate-card artifact-card" key={artifact.id}><header><span>{artifact.claim?.claimNumber ?? artifact.claimId} · {artifact.verifier}</span><span>{artifact.reviewStatus}</span></header><strong>{artifact.verificationLevel}</strong><div>Build: {artifact.buildResult} · Commit: <code>{artifact.commitHash}</code></div><a href={artifact.repositoryUrl} target="_blank" rel="noreferrer">Repository ↗</a>{artifact.reviewRationale ? <p>Review: {artifact.reviewRationale}</p> : null}
      {canReview && artifact.reviewStatus === "DRAFT" ? <form className="candidate-actions artifact-review" action={reviewArtifact}><input type="hidden" name="id" value={artifact.id}/><textarea name="rationale" required placeholder="Review rationale" rows={2}/><div><button name="decision" value="ACCEPTED">Accept</button><button name="decision" value="REJECTED">Reject</button></div></form> : null}
      {canExecute && artifact.reviewStatus === "ACCEPTED" ? <details className="execution-entry"><summary>Record trusted verifier execution</summary><form action={recordExecution}><input type="hidden" name="artifactId" value={artifact.id}/><label>Command<input name="command" required defaultValue={commands[artifact.verifier] ?? ""}/></label><label>Tool version<input name="toolVersion" required defaultValue={artifact.verifierVersion ?? ""}/></label><label>Exit code<input name="exitCode" type="number" step="1" required defaultValue="0"/></label><label>Standard output<textarea name="stdout" rows={3} placeholder={artifact.verifier === "SAT_SOLVER" ? "s VERIFIED" : "Build output"}/></label><label>Standard error<textarea name="stderr" rows={2}/></label><button type="submit">Validate and record</button></form></details> : null}
      {artifact.executions.length ? <div className="execution-history"><h3>Execution history</h3>{artifact.executions.map((execution) => <div key={execution.id}><strong>{execution.status}{execution.reproducible ? " · reproducible" : ""}</strong><span>{execution.toolVersion} · exit {execution.exitCode} · {new Date(execution.completedAt).toLocaleString()}</span><small>SHA-256 output: {execution.outputDigest}</small></div>)}</div> : null}</article>) : <p>No artifacts found.</p>}</section>
  </>;
}
