export type BlogPost = { slug: string; title: string; dek: string; publishedAt: string; tags: string[] };

// Single source of truth for post metadata — the index page, each post's own generateMetadata,
// and sitemap.ts all read from this instead of duplicating title/dek in three places.
export const blogPosts: BlogPost[] = [
  {
    slug: "what-is-the-chromatic-number-of-the-plane",
    title: "What Is the Chromatic Number of the Plane?",
    dek: "A 70-year-old coloring problem, narrowed to 5, 6, or 7 — and still open.",
    publishedAt: "2026-08-28",
    tags: ["Mathematics", "Open problems"],
  },
  {
    slug: "what-is-the-beal-conjecture",
    title: "What Is the Beal Conjecture?",
    dek: "A $1,000,000 prize for a one-line generalization of Fermat's Last Theorem.",
    publishedAt: "2026-08-28",
    tags: ["Mathematics", "Open problems"],
  },
  {
    slug: "millennium-prize-problems-list",
    title: "What Are the Millennium Prize Problems?",
    dek: "Seven $1,000,000 problems named in 2000. One is solved. Six are still open.",
    publishedAt: "2026-08-28",
    tags: ["Mathematics", "Open problems"],
  },
  {
    slug: "why-are-physical-constants-known-so-precisely",
    title: "Why Are Physical Constants Known to So Many Decimal Places?",
    dek: "Inside CODATA 2022, the internationally adjusted reference values behind every precision measurement.",
    publishedAt: "2026-08-28",
    tags: ["Physics", "Constants"],
  },
  {
    slug: "what-is-rsa-factoring",
    title: "What Is RSA Factoring, and Why Is It Hard?",
    dek: "The factoring challenge that underwrites internet cryptography — and the exact number where the record currently stands.",
    publishedAt: "2026-08-28",
    tags: ["Cryptography", "Computing"],
  },
  {
    slug: "what-is-a-mersenne-prime",
    title: "What Is a Mersenne Prime?",
    dek: "Primes of the form 2^p − 1, and the volunteer computing project still finding new ones.",
    publishedAt: "2026-08-28",
    tags: ["Mathematics", "Number theory"],
  },
  {
    slug: "limit-of-lossless-data-compression",
    title: "What Is the Theoretical Limit of Lossless Data Compression?",
    dek: "Shannon's source-coding theorem sets a hard floor on file size — no cleverer algorithm can beat it.",
    publishedAt: "2026-08-28",
    tags: ["Information theory", "Computing"],
  },
  {
    slug: "what-is-a-ramsey-number",
    title: "What Is a Ramsey Number?",
    dek: "Why R(5,5) — a single unknown integer between 43 and 46 — might never be found by brute force.",
    publishedAt: "2026-08-28",
    tags: ["Mathematics", "Combinatorics"],
  },
  {
    slug: "what-is-a-kissing-number",
    title: "What Is a Kissing Number?",
    dek: "The surprising geometry of how many equal spheres can touch one central sphere without overlap.",
    publishedAt: "2026-08-28",
    tags: ["Mathematics", "Geometry"],
  },
  {
    slug: "what-is-the-no-cloning-theorem",
    title: "What Is the No-Cloning Theorem?",
    dek: "Why quantum mechanics forbids a universal machine from making a perfect copy of an unknown quantum state.",
    publishedAt: "2026-08-28",
    tags: ["Quantum information", "Impossibility"],
  },
  {
    slug: "how-do-upper-and-lower-bounds-work",
    title: "How Do Upper and Lower Bounds Work?",
    dek: "The two-sided language researchers use to describe exactly what is known when the final answer is still out of reach.",
    publishedAt: "2026-08-28",
    tags: ["Methodology", "Open problems"],
  },
  {
    slug: "what-is-channel-capacity",
    title: "What Is Channel Capacity?",
    dek: "The hard ceiling on reliable communication through a noisy channel — and why more clever coding cannot erase noise for free.",
    publishedAt: "2026-08-28",
    tags: ["Information theory", "Computing"],
  },
  {
    slug: "what-is-miplib",
    title: "What Is MIPLIB, and Why Do Solvers Compete on It?",
    dek: "The standard benchmark library for mixed-integer programming — and the 382 provably optimal objective values it puts in the Registry.",
    publishedAt: "2026-08-29",
    tags: ["Computing", "Optimization"],
  },
  {
    slug: "real-world-records-in-the-registry",
    title: "The Fastest, Highest, Deepest: Real-World Records in the Registry",
    dek: "From a 9.58-second 100 meters to a 10,934-meter dive — verified real-world records, sourced and dated like everything else here.",
    publishedAt: "2026-08-29",
    tags: ["Records", "Methodology"],
  },
  {
    slug: "what-is-the-p-vs-np-problem",
    title: "What Is the P versus NP Problem?",
    dek: "The $1,000,000 question of whether every easily checked answer is also easy to find — open since 1971.",
    publishedAt: "2026-09-19",
    tags: ["Mathematics", "Computing"],
  },
  {
    slug: "what-is-the-riemann-hypothesis",
    title: "What Is the Riemann Hypothesis?",
    dek: "A 165-year-old claim about where the zeros of one function sit — verified for trillions of cases, proven for none.",
    publishedAt: "2026-09-19",
    tags: ["Mathematics", "Number theory"],
  },
  {
    slug: "what-is-the-navier-stokes-problem",
    title: "What Is the Navier–Stokes Existence and Smoothness Problem?",
    dek: "The equations that fly every airplane and forecast every storm — and the unproven question of whether their solutions can blow up.",
    publishedAt: "2026-09-19",
    tags: ["Physics", "Open problems"],
  },
  {
    slug: "what-is-landauers-principle",
    title: "What Is Landauer's Principle?",
    dek: "Erasing a single bit of information has a minimum energy cost — a thermodynamic floor confirmed in the lab in 2012.",
    publishedAt: "2026-09-19",
    tags: ["Physics", "Information theory"],
  },
  {
    slug: "what-is-the-matrix-multiplication-exponent",
    title: "What Is the Matrix Multiplication Exponent?",
    dek: "The best proven algorithm for multiplying two matrices keeps getting slightly faster — currently ω < 2.371339, with 2 as the unreached floor.",
    publishedAt: "2026-09-19",
    tags: ["Computing", "Algorithms"],
  },
  {
    slug: "how-good-can-a-tsp-approximation-get",
    title: "How Good Can a TSP Approximation Get?",
    dek: "Christofides' 3/2-approximation for the traveling salesman problem stood as the best known bound for 44 years — until it finally moved in 2020.",
    publishedAt: "2026-09-19",
    tags: ["Computing", "Optimization"],
  },
  {
    slug: "what-is-the-vesuvius-challenge",
    title: "What Is the Vesuvius Challenge?",
    dek: "A $1,000,000 prize to read a 2,000-year-old scroll nobody can physically open — using CT scans and machine learning instead.",
    publishedAt: "2026-09-19",
    tags: ["Computing", "Machine learning"],
  },
  {
    slug: "what-is-bremermanns-limit",
    title: "What Is Bremermann's Limit?",
    dek: "A 1962 estimate of the fastest any physical system can compute — later superseded by a more rigorous quantum bound with almost the same number.",
    publishedAt: "2026-09-20",
    tags: ["Physics", "Computing"],
  },
  {
    slug: "why-cant-edit-distance-be-computed-faster",
    title: "Why Can't Edit Distance Be Computed Faster?",
    dek: "A 44-year-old quadratic-time algorithm, and a 2015 proof that beating it would break a foundational assumption of complexity theory.",
    publishedAt: "2026-09-20",
    tags: ["Computing", "Algorithms"],
  },
  {
    slug: "why-is-greedy-optimal-for-set-cover",
    title: "Why Is the Greedy Algorithm Optimal for Set Cover?",
    dek: "A simple, decades-old heuristic turned out to be provably as good as any polynomial-time algorithm can get.",
    publishedAt: "2026-09-20",
    tags: ["Computing", "Algorithms"],
  },
  {
    slug: "can-vertex-cover-be-approximated-better-than-2x",
    title: "Can Vertex Cover Be Approximated Better Than 2×?",
    dek: "A one-line algorithm has stood unbeaten for decades — and beating it would resolve one of complexity theory's biggest open conjectures.",
    publishedAt: "2026-09-20",
    tags: ["Computing", "Algorithms"],
  },
  {
    slug: "how-much-data-can-dna-actually-store",
    title: "How Much Data Can DNA Actually Store?",
    dek: "A theoretical ceiling near 455 exabytes per gram, and a real demonstrated record of 215 petabytes per gram using fountain codes.",
    publishedAt: "2026-09-20",
    tags: ["Biology", "Data storage"],
  },
  {
    slug: "what-sets-the-minimum-age-of-the-universe",
    title: "What Sets the Minimum Age of the Universe?",
    dek: "The universe must be at least as old as its oldest surviving stars — a lower bound independent of any cosmological model.",
    publishedAt: "2026-09-20",
    tags: ["Physics", "Astrophysics"],
  },
];

export function getBlogPost(slug: string) {
  return blogPosts.find((post) => post.slug === slug);
}
