import type { Claim, Evidence, Limit, Review, SpecificationVersion } from "./types";

export type Fixture = { name: string; limit: Limit; specification: SpecificationVersion; claims: Claim[]; evidence: Evidence[]; reviews: Review[]; expected: { status: "OPEN" | "PROVEN"; gap: string } };
const base = (id: string, title: string, category = "Mathematics"): Limit => ({ id, title, category, status: "OPEN", direction: "MAXIMIZE", summary: title });
const spec = (id: string, limitId: string, version = 1, asymptotic = false): SpecificationVersion => ({ id, limitId, version, formalStatement: "A precisely scoped quantity under stated constraints.", constraints: { domain: "fixture" }, asymptotic, probabilistic: false });
const claim = (id: string, specificationVersionId: string, relation: Claim["relation"], value: number | bigint, claimType: Claim["claimType"], status: Claim["status"] = "ACCEPTED", epistemicStatus: Claim["epistemicStatus"] = "PROVEN"): Claim => ({ id, specificationVersionId, relation, value: { kind: "integer", value: BigInt(value) }, claimType, status, epistemicStatus, evidenceIds: [`EVD-${id}`], author: "Fixture author", year: 2025, source: "Fixture evidence" });
const emptyEvidence = (id: string): Evidence => ({ id, type: "PAPER", label: "Fixture paper", location: "Theorem 1" });
const fixtureReview = (claimId: string): Review => ({ id: `REV-${claimId}`, claimId, decision: "ACCEPTED", rationale: "Fixture review confirms the claim is scoped to the fixture specification.", reviewer: "Fixture reviewer" });

const fixtureDefinitions: Fixture[] = [
  { name: "exact proven limit", limit: base("LR-F01", "Exact fixture limit"), specification: spec("SP-F01", "LR-F01"), claims: [claim("CLM-F01A", "SP-F01", ">=", 5, "LOWER_BOUND"), claim("CLM-F01B", "SP-F01", "<=", 5, "UPPER_BOUND")], evidence: [emptyEvidence("EVD-CLM-F01A"), emptyEvidence("EVD-CLM-F01B")], reviews: [fixtureReview("CLM-F01A"), fixtureReview("CLM-F01B")], expected: { status: "PROVEN", gap: "Closed" } },
  { name: "open integer gap", limit: base("LR-F02", "Open integer fixture"), specification: spec("SP-F02", "LR-F02"), claims: [claim("CLM-F02A", "SP-F02", ">=", 5, "LOWER_BOUND"), claim("CLM-F02B", "SP-F02", "<=", 6, "UPPER_BOUND")], evidence: [], reviews: [fixtureReview("CLM-F02A"), fixtureReview("CLM-F02B")], expected: { status: "OPEN", gap: "5 to 6" } },
  { name: "asymptotic bound", limit: base("LR-F03", "Asymptotic fixture"), specification: spec("SP-F03", "LR-F03", 1, true), claims: [{ ...claim("CLM-F03A", "SP-F03", "<=", 1, "ASYMPTOTIC_BOUND"), value: { kind: "text", value: "O(log n)" } }], evidence: [], reviews: [fixtureReview("CLM-F03A")], expected: { status: "OPEN", gap: "Unknown" } },
  { name: "exhaustive computation", limit: base("LR-F04", "Exhaustive search fixture"), specification: spec("SP-F04", "LR-F04"), claims: [claim("CLM-F04A", "SP-F04", "<=", 12, "COMPUTATIONAL_BOUND", "ACCEPTED", "REPRODUCED")], evidence: [{ id: "EVD-CLM-F04A", type: "EXHAUSTIVE_COMPUTATION", label: "Search bundle v3", location: "run hash abc123" }], reviews: [fixtureReview("CLM-F04A")], expected: { status: "OPEN", gap: "Unknown" } },
  { name: "formal machine proof", limit: base("LR-F05", "Formal proof fixture"), specification: spec("SP-F05", "LR-F05"), claims: [claim("CLM-F05A", "SP-F05", "<=", 10, "UPPER_BOUND", "ACCEPTED", "FORMALLY_PROVEN")], evidence: [{ id: "EVD-CLM-F05A", type: "FORMAL_PROOF", label: "Lean proof", location: "theorem main" }], reviews: [fixtureReview("CLM-F05A")], expected: { status: "OPEN", gap: "Unknown" } },
  { name: "invalidated history", limit: base("LR-F06", "Invalidation fixture"), specification: spec("SP-F06", "LR-F06"), claims: [claim("CLM-F06A", "SP-F06", ">=", 5, "LOWER_BOUND", "INVALIDATED", "INVALIDATED"), claim("CLM-F06B", "SP-F06", "<=", 6, "UPPER_BOUND")], evidence: [], reviews: [fixtureReview("CLM-F06A"), fixtureReview("CLM-F06B")], expected: { status: "OPEN", gap: "Unknown" } },
  { name: "incompatible specifications", limit: base("LR-F07", "Specification fixture"), specification: spec("SP-F07", "LR-F07"), claims: [claim("CLM-F07A", "OTHER-SPEC", ">=", 5, "LOWER_BOUND"), claim("CLM-F07B", "SP-F07", "<=", 6, "UPPER_BOUND")], evidence: [], reviews: [fixtureReview("CLM-F07A"), fixtureReview("CLM-F07B")], expected: { status: "OPEN", gap: "Unknown" } },
  { name: "probabilistic bound", limit: base("LR-F08", "Probabilistic fixture"), specification: { ...spec("SP-F08", "LR-F08"), probabilistic: true }, claims: [claim("CLM-F08A", "SP-F08", "<=", 9, "UPPER_BOUND", "ACCEPTED", "EMPIRICALLY_SUPPORTED")], evidence: [], reviews: [fixtureReview("CLM-F08A")], expected: { status: "OPEN", gap: "Unknown" } },
  { name: "construction", limit: base("LR-F09", "Construction fixture"), specification: spec("SP-F09", "LR-F09"), claims: [claim("CLM-F09A", "SP-F09", ">=", 4, "CONSTRUCTION", "ACCEPTED", "SOURCE_CONFIRMED")], evidence: [], reviews: [fixtureReview("CLM-F09A")], expected: { status: "OPEN", gap: "Unknown" } },
  { name: "counterexample", limit: base("LR-F10", "Counterexample fixture"), specification: spec("SP-F10", "LR-F10"), claims: [claim("CLM-F10A", "SP-F10", "<=", 6, "UPPER_BOUND", "INVALIDATED", "INVALIDATED"), claim("CLM-F10B", "SP-F10", ">=", 5, "COUNTEREXAMPLE")], evidence: [], reviews: [fixtureReview("CLM-F10A"), fixtureReview("CLM-F10B")], expected: { status: "OPEN", gap: "Unknown" } },
].map((fixture): Fixture => ({
  ...fixture,
  evidence: (fixture.evidence.length ? fixture.evidence : fixture.claims.map((item) => emptyEvidence(`EVD-${item.id}`))) as Evidence[],
  reviews: fixture.reviews.length ? fixture.reviews : fixture.claims.map((item) => fixtureReview(item.id)),
} as Fixture));

export const fixtures: Fixture[] = fixtureDefinitions;
