import type { ResearchPacket } from "./research-packet";
import type { Claim, Evidence, Direction, SpecificationVersion } from "./types";

const spec: SpecificationVersion = {
  id: "SP-LR-000127-V1", limitId: "LR-000127", version: 1,
  formalStatement: "ex(n, K₃) is the maximum number of edges in a simple n-vertex graph containing no triangle.",
  constraints: { graph: "simple", vertices: "n", forbiddenSubgraph: "K₃" }, asymptotic: false, probabilistic: false,
};
const evidence: Evidence = { id: "EVD-LR127-1", type: "MATHEMATICAL_PROOF", method: "MANTEL_THEOREM", verificationLevel: "SOURCE_CONFIRMED", label: "Mantel's theorem and balanced complete bipartite construction", sourceUrl: "https://ocw.mit.edu/courses/18-225-graph-theory-and-additive-combinatorics-fall-2023/mit18_225_f23_lec_full.pdf" };
const claim = (id: string, relation: Claim["relation"], type: Claim["claimType"], value: string, author: string, year: number): Claim => ({ id, specificationVersionId: spec.id, relation, value: { kind: "text", value }, claimType: type, status: "ACCEPTED", epistemicStatus: "SOURCE_CONFIRMED", scientificStatus: "ACCEPTED", registryReviewStatus: "UNREVIEWED", evidenceIds: [evidence.id], author, year, source: evidence.label });

export const mantelResearchPacket: ResearchPacket = {
  limit: { id: "LR-000127", title: "Maximum edges in a triangle-free graph", category: "Graph Theory", status: "PROVEN", direction: "MAXIMIZE", summary: "The maximum number of edges in a simple n-vertex graph containing no triangle." },
  specification: spec,
  claims: [
    claim("CLM-LR127-LOWER", ">=", "CONSTRUCTION", "floor(n²/4)", "Willem Mantel", 1907),
    claim("CLM-LR127-UPPER", "<=", "UPPER_BOUND", "floor(n²/4)", "Willem Mantel", 1907),
  ],
  evidence: [evidence], registryReviewStatus: "UNREVIEWED",
};


const packetSpec = (id: string, limitId: string, formalStatement: string, constraints: Record<string, string>, asymptotic = true, probabilistic = false): SpecificationVersion => ({ id, limitId, version: 1, formalStatement, constraints, asymptotic, probabilistic });
const textClaim = (id: string, specId: string, relation: Claim["relation"], value: string, claimType: Claim["claimType"], author: string, year: number, source: string, evidenceId: string, scientificStatus: Claim["scientificStatus"] = "ACCEPTED"): Claim => ({ id, specificationVersionId: specId, relation, value: { kind: "text", value }, claimType, status: "ACCEPTED", epistemicStatus: scientificStatus === "UNCERTAIN" ? "LITERATURE_ASSERTED" : "SOURCE_CONFIRMED", scientificStatus, registryReviewStatus: "UNREVIEWED", evidenceIds: [evidenceId], author, year, source });

const cernySpec = packetSpec("SP-LR-000114-V1", "LR-000114", "C(n) is the maximum shortest reset-word length over synchronizing complete deterministic automata with n states.", { automaton: "complete DFA", states: "n", quantity: "reset threshold" }, true);
const cernyEvidence: Evidence = { id: "EVD-LR114-1", type: "MATHEMATICAL_PROOF", method: "AUTOMATON_CONSTRUCTION", verificationLevel: "SOURCE_CONFIRMED", label: "Černý automata attain (n−1)²; general quadratic upper bound remains conjectural", sourceUrl: "https://doi.org/10.1145/3798283" };
export const cernyResearchPacket: ResearchPacket = { limit: { id: "LR-000114", title: "Synchronizing automaton reset threshold", category: "Automata", status: "OPEN", direction: "MINIMIZE", summary: "The maximum shortest reset-word length among synchronizing n-state finite automata." }, specification: cernySpec, claims: [ textClaim("CLM-LR114-LOWER", cernySpec.id, ">=", "(n−1)²", "LOWER_BOUND", "Jan Černý", 1964, "Černý automata construction", cernyEvidence.id), textClaim("CLM-LR114-CONJECTURE", cernySpec.id, "<=", "(n−1)²", "UPPER_BOUND", "Černý conjecture", 1969, "Černý conjecture", cernyEvidence.id, "UNCERTAIN"), textClaim("CLM-LR114-UPPER-CUBIC", cernySpec.id, "<=", "0.1654n³ + O(n²)", "UPPER_BOUND", "Yaroslav Shitov", 2022, "Best known general cubic upper bound", cernyEvidence.id) ], evidence: [cernyEvidence], registryReviewStatus: "UNREVIEWED" };

const capSpec = packetSpec("SP-LR-000098-V1", "LR-000098", "A cap set is a subset of F₃ⁿ with no non-trivial solution to x+y+z=0.", { domain: "F₃ⁿ", forbiddenConfiguration: "non-trivial 3-term arithmetic progression" });
const capEvidence: Evidence = { id: "EVD-LR098-1", type: "MATHEMATICAL_PROOF", method: "POLYNOMIAL_METHOD", verificationLevel: "SOURCE_CONFIRMED", label: "Polynomial-method upper bound for cap sets", sourceUrl: "https://doi.org/10.1016/j.jcta.2019.06.001" };
const capLowerEvidence: Evidence = { id: "EVD-LR098-2", type: "CONSTRUCTION", method: "EXPLICIT_CONSTRUCTION", verificationLevel: "SOURCE_CONFIRMED", label: "Improved exponential lower bound for cap sets", sourceUrl: "https://arxiv.org/abs/2209.10045" };
export const capSetResearchPacket: ResearchPacket = { limit: { id: "LR-000098", title: "Largest cap set in F₃ⁿ", category: "Combinatorics", status: "OPEN", direction: "MAXIMIZE", summary: "The largest subset of F₃ⁿ containing no non-trivial three-term arithmetic progression." }, specification: capSpec, claims: [ textClaim("CLM-LR098-LOWER", capSpec.id, ">=", "2.218ⁿ", "LOWER_BOUND", "Fred Tyrrell", 2022, "New Lower Bounds for Cap Sets", capLowerEvidence.id), textClaim("CLM-LR098-UPPER", capSpec.id, "<=", "O(2.756ⁿ)", "UPPER_BOUND", "Jordan Ellenberg and Dion Gijswijt", 2016, "Bounds on sizes of generalized caps", capEvidence.id) ], evidence: [capLowerEvidence, capEvidence], registryReviewStatus: "UNREVIEWED" };

const bchSpec = packetSpec("SP-LR-000086-V1", "LR-000086", "d(C) is the true minimum Hamming distance of a primitive narrow-sense binary BCH code of length 2ᵐ−1 and designed distance δ.", { field: "F₂", family: "primitive narrow-sense BCH", length: "2ᵐ−1", parameter: "m and δ" }, false);
const bchEvidence: Evidence = { id: "EVD-LR086-1", type: "MATHEMATICAL_PROOF", method: "BCH_BOUND", verificationLevel: "SOURCE_CONFIRMED", label: "BCH designed-distance guarantee", sourceUrl: "https://www.aimsciences.org/article/doi/10.3934/amc.2024047?viewType=HTML" };
export const bchResearchPacket: ResearchPacket = { limit: { id: "LR-000086", title: "Minimum distance of primitive binary BCH codes", category: "Coding theory", status: "OPEN", direction: "MAXIMIZE", summary: "The true minimum Hamming distance of a primitive narrow-sense binary BCH family of length 2ᵐ − 1." }, specification: bchSpec, claims: [ textClaim("CLM-LR086-DESIGNED", bchSpec.id, ">=", "δ", "LOWER_BOUND", "BCH bound", 1959, "The designed distance is a lower bound on true minimum distance", bchEvidence.id) ], evidence: [bchEvidence], registryReviewStatus: "UNREVIEWED" };

export const additionalResearchPackets: ResearchPacket[] = [cernyResearchPacket, capSetResearchPacket, bchResearchPacket];

const sortingSpec = (id: string, limitId: string, inputs: number): SpecificationVersion => ({ id, limitId, version: 1, formalStatement: `S(${inputs}) is the minimum number of comparators in a fixed network that sorts every ${inputs}-input sequence.`, constraints: { inputs: String(inputs), inputDomain: "totally ordered values", verificationDomain: `${2 ** inputs} binary inputs`, network: "fixed/data-oblivious" }, asymptotic: false, probabilistic: false });
const sortingEvidence = (id: string, label: string): Evidence => ({ id, type: "COMPUTATIONAL_PROOF", method: "SAT_SYMMETRY_REDUCTION", verificationLevel: "SOURCE_CONFIRMED", label, sourceUrl: "https://arxiv.org/abs/1405.5754" });
const sortingPacket = (limitId: string, inputs: number, lower: number, upper: number, status: "OPEN" | "PROVEN", lowerSource: string, upperSource: string): ResearchPacket => {
  const specification = sortingSpec(`SP-${limitId}-V1`, limitId, inputs);
  const lowerEvidence = sortingEvidence(`EVD-${limitId}-LOWER`, `Computer-assisted lower-bound verification for S(${inputs})`);
  const upperEvidence: Evidence = { id: `EVD-${limitId}-UPPER`, type: "CONSTRUCTION", method: "COMPARATOR_NETWORK", verificationLevel: "SOURCE_CONFIRMED", label: `Known ${upper}-comparator sorting network for ${inputs} inputs`, sourceUrl: "https://imada.sdu.dk/~petersk/sn/" };
  const makeClaim = (id: string, relation: Claim["relation"], value: number, type: Claim["claimType"], source: string, evidenceId: string): Claim => ({ id, specificationVersionId: specification.id, relation, value: { kind: "integer", value: BigInt(value) }, claimType: type, status: "ACCEPTED", epistemicStatus: "SOURCE_CONFIRMED", scientificStatus: "ACCEPTED", registryReviewStatus: "UNREVIEWED", evidenceIds: [evidenceId], author: "Codish, Cruz-Filipe, Frank, Schneider-Kamp", year: 2014, source });
  return { limit: { id: limitId, title: `Minimum number of comparators for a ${inputs}-input sorting network`, category: "Algorithms / Sorting Networks", status, direction: "MINIMIZE", summary: `The minimum number of fixed compare-exchange operations needed to sort ${inputs} inputs.` }, specification, claims: [makeClaim(`CLM-${limitId}-LOWER`, ">=", lower, "LOWER_BOUND", lowerSource, lowerEvidence.id), makeClaim(`CLM-${limitId}-UPPER`, "<=", upper, "UPPER_BOUND", upperSource, upperEvidence.id)], evidence: [lowerEvidence, upperEvidence], registryReviewStatus: "UNREVIEWED" };
};

export const sortingNetworkResearchPackets: ResearchPacket[] = [
  sortingPacket("LR-SN-009", 9, 25, 25, "PROVEN", "Twenty-Five Comparators is Optimal when Sorting Nine Inputs", "Floyd's 25-comparator construction"),
  sortingPacket("LR-SN-010", 10, 29, 29, "PROVEN", "Twenty-Five Comparators is Optimal when Sorting Nine Inputs (and Twenty-Nine for Ten)", "Waksman's 29-comparator construction"),
  sortingPacket("LR-SN-011", 11, 33, 35, "OPEN", "Maintained sorting-network lower-bound table", "Maintained sorting-network upper-bound table"),
  sortingPacket("LR-SN-012", 12, 37, 39, "OPEN", "Maintained sorting-network lower-bound table", "Maintained sorting-network upper-bound table"),
];

const landauerSpec: SpecificationVersion = { id: "SP-LR-LANDAUER-V1", limitId: "LR-LANDAUER", version: 1, formalStatement: "The minimum work required to irreversibly erase one bit at thermodynamic temperature T is k_B T ln(2).", constraints: { system: "physical information-bearing system", operation: "logically irreversible bit erasure", temperature: "T kelvin", assumptions: "thermal equilibrium" }, asymptotic: false, probabilistic: false };
const landauerEvidence: Evidence = { id: "EVD-LR-LANDAUER-1", type: "MATHEMATICAL_PROOF", method: "STATISTICAL_MECHANICS", verificationLevel: "SOURCE_CONFIRMED", label: "Landauer principle", sourceUrl: "https://doi.org/10.1103/PhysRev.122.1152" };
export const landauerResearchPacket: ResearchPacket = { limit: { id: "LR-LANDAUER", title: "Minimum energy to erase one bit", category: "Physics / Information", status: "PROVEN", direction: "MINIMIZE", limitKind: "THEORETICAL_BOUND", canonicalStatus: "EXACT", summary: "The minimum thermodynamic work required for logically irreversible erasure of one bit at temperature T." }, specification: landauerSpec, claims: [{ id: "CLM-LR-LANDAUER-BOUND", relation: ">=", value: { kind: "text", value: "k_B T ln(2)" }, claimType: "LOWER_BOUND", status: "ACCEPTED", epistemicStatus: "PROVEN", scientificStatus: "ACCEPTED", registryReviewStatus: "UNREVIEWED", evidenceBasis: ["THEORETICAL_DERIVATION"], specificationVersionId: landauerSpec.id, evidenceIds: [landauerEvidence.id], author: "Rolf Landauer", year: 1961, source: "Irreversibility and Heat Generation in the Computing Process" }], evidence: [landauerEvidence], registryReviewStatus: "UNREVIEWED" };

const genomeSpec: SpecificationVersion = { id: "SP-LR-GENOME-V1", limitId: "LR-GENOME", version: 1, formalStatement: "The genome size of a viable, independently growing bacterial cell maintained in pure culture under the stated laboratory conditions.", constraints: { organism: "JCVI-syn3.0", environment: "pure culture", viability: "independently growing", metric: "genes and base pairs" }, asymptotic: false, probabilistic: false };
const genomeEvidence: Evidence = { id: "EVD-LR-GENOME-1", type: "CONSTRUCTION", method: "SYNTHETIC_GENOME_REDUCTION", verificationLevel: "SOURCE_CONFIRMED", label: "JCVI-syn3.0 minimal bacterial cell", sourceUrl: "https://doi.org/10.1038/nature16449" };
export const minimalGenomeResearchPacket: ResearchPacket = { limit: { id: "LR-GENOME", title: "Smallest demonstrated independently growing bacterial genome", category: "Biology / Synthetic Biology", status: "OPEN", direction: "MINIMIZE", limitKind: "OBSERVED_RECORD", summary: "The smallest genome demonstrated in a viable, independently growing bacterial cell under a defined laboratory specification." }, specification: genomeSpec, claims: [{ id: "CLM-LR-GENOME-473", relation: "<=", value: { kind: "integer", value: 473n }, claimType: "CONSTRUCTION", status: "ACCEPTED", epistemicStatus: "SOURCE_CONFIRMED", scientificStatus: "ACCEPTED", registryReviewStatus: "UNREVIEWED", evidenceBasis: ["CONSTRUCTION"], specificationVersionId: genomeSpec.id, evidenceIds: [genomeEvidence.id], author: "Hutchison et al.", year: 2016, source: "Design and synthesis of a minimal bacterial genome" }], evidence: [genomeEvidence], registryReviewStatus: "UNREVIEWED" };

export const crossDomainResearchPackets: ResearchPacket[] = [landauerResearchPacket, minimalGenomeResearchPacket];


const speedSpec: SpecificationVersion = { id: "SP-LR-SPEED-V1", limitId: "LR-SPEED", version: 1, formalStatement: "The vacuum speed of light c is exactly 299792458 metres per second in the SI system.", constraints: { medium: "vacuum", unitSystem: "SI" }, asymptotic: false, probabilistic: false };
const speedEvidence: Evidence = { id: "EVD-LR-SPEED-1", type: "MATHEMATICAL_PROOF", method: "SI_DEFINITION_AND_RELATIVITY", verificationLevel: "SOURCE_CONFIRMED", label: "SI defining value for the speed of light in vacuum", sourceUrl: "https://www.nist.gov/pml/special-publication-330/sp-330-appendix-1" };
export const speedOfLightResearchPacket: ResearchPacket = { limit: { id: "LR-SPEED", title: "Speed of light in vacuum", category: "Physics / Fundamental Constants", status: "PROVEN", direction: "MAXIMIZE", limitKind: "FUNDAMENTAL_CONSTANT", canonicalStatus: "EXACT", summary: "The exact SI-defined speed of electromagnetic radiation in vacuum." }, specification: speedSpec, claims: [{ id: "CLM-LR-SPEED-EXACT", relation: "=", value: { kind: "integer", value: 299792458n }, claimType: "EXACT_VALUE", status: "ACCEPTED", epistemicStatus: "PROVEN", scientificStatus: "ACCEPTED", registryReviewStatus: "UNREVIEWED", evidenceBasis: ["THEORETICAL_DERIVATION"], specificationVersionId: speedSpec.id, evidenceIds: [speedEvidence.id], author: "International System of Units", year: 1983, source: "SI definition of c" }], evidence: [speedEvidence], registryReviewStatus: "UNREVIEWED" };

const genomeSizeSpec: SpecificationVersion = { ...genomeSpec, id: "SP-LR-GENOME-SIZE-V1", limitId: "LR-GENOME-SIZE", constraints: { ...genomeSpec.constraints, metric: "base pairs" } };
export const minimalGenomeSizeResearchPacket: ResearchPacket = { ...minimalGenomeResearchPacket, limit: { ...minimalGenomeResearchPacket.limit, id: "LR-GENOME-SIZE", title: "Smallest demonstrated bacterial genome by base-pair count" }, specification: genomeSizeSpec, claims: [{ ...minimalGenomeResearchPacket.claims[0], id: "CLM-LR-GENOME-531560", specificationVersionId: genomeSizeSpec.id, value: { kind: "integer", value: 531560n }, evidenceIds: ["EVD-LR-GENOME-1"] }] };

export const nextCrossDomainResearchPackets: ResearchPacket[] = [landauerResearchPacket, speedOfLightResearchPacket, minimalGenomeResearchPacket, minimalGenomeSizeResearchPacket];


const exactTextClaim = (id: string, specId: string, relation: Claim["relation"], value: string, claimType: Claim["claimType"], author: string, year: number, source: string, evidenceId: string, basis: NonNullable<Claim["evidenceBasis"]>[number]): Claim => ({ id, specificationVersionId: specId, relation, value: { kind: "text", value }, claimType, status: "ACCEPTED", epistemicStatus: "PROVEN", scientificStatus: "ACCEPTED", registryReviewStatus: "UNREVIEWED", evidenceBasis: [basis], evidenceIds: [evidenceId], author, year, source });

const carnotSpec: SpecificationVersion = { id: "SP-LR-CARNOT-V1", limitId: "LR-CARNOT", version: 1, formalStatement: "The efficiency of a reversible heat engine operating between reservoirs at temperatures T_h and T_c is η = 1 − T_c/T_h.", constraints: { engine: "heat engine", process: "reversible", hotReservoir: "T_h", coldReservoir: "T_c", units: "kelvin" }, asymptotic: false, probabilistic: false };
const carnotEvidence: Evidence = { id: "EVD-LR-CARNOT-1", type: "MATHEMATICAL_PROOF", method: "REVERSIBLE_THERMODYNAMICS", verificationLevel: "SOURCE_CONFIRMED", label: "Carnot efficiency theorem", sourceUrl: "https://openstax.org/books/college-physics/pages/15-4-carnots-perfect-heat-engine-the-second-law-of-thermodynamics-restated" };
export const carnotResearchPacket: ResearchPacket = { limit: { id: "LR-CARNOT", title: "Maximum efficiency of a reversible heat engine", category: "Thermodynamics", status: "PROVEN", direction: "MAXIMIZE", limitKind: "THEORETICAL_BOUND", canonicalStatus: "EXACT", summary: "The maximum efficiency of a reversible heat engine between specified hot and cold reservoirs." }, specification: carnotSpec, claims: [exactTextClaim("CLM-LR-CARNOT", "SP-LR-CARNOT-V1", "<=", "1 − T_c/T_h", "UPPER_BOUND", "Sadi Carnot", 1824, "Carnot efficiency theorem", carnotEvidence.id, "THEORETICAL_DERIVATION")], evidence: [carnotEvidence], registryReviewStatus: "UNREVIEWED" };

const betzSpec: SpecificationVersion = { id: "SP-LR-BETZ-V1", limitId: "LR-BETZ", version: 1, formalStatement: "The power coefficient C_p of an ideal actuator-disk wind turbine in steady, uniform, incompressible flow is at most 16/27.", constraints: { device: "ideal actuator disk", flow: "steady uniform incompressible", metric: "power coefficient C_p" }, asymptotic: false, probabilistic: false };
const betzEvidence: Evidence = { id: "EVD-LR-BETZ-1", type: "MATHEMATICAL_PROOF", method: "ACTUATOR_DISK_MOMENTUM_THEORY", verificationLevel: "SOURCE_CONFIRMED", label: "Betz limit", sourceUrl: "https://www.energy.gov/cmei/systems/windexchange/small-wind-guidebook" };
export const betzResearchPacket: ResearchPacket = { limit: { id: "LR-BETZ", title: "Maximum wind-turbine power coefficient", category: "Energy / Wind", status: "PROVEN", direction: "MAXIMIZE", limitKind: "THEORETICAL_BOUND", canonicalStatus: "EXACT", summary: "The ideal actuator-disk limit on the fraction of wind power extractable by a turbine." }, specification: betzSpec, claims: [exactTextClaim("CLM-LR-BETZ", "SP-LR-BETZ-V1", "<=", "16/27", "UPPER_BOUND", "Albert Betz", 1919, "Betz limit", betzEvidence.id, "THEORETICAL_DERIVATION")], evidence: [betzEvidence], registryReviewStatus: "UNREVIEWED" };

const shannonSpec: SpecificationVersion = { id: "SP-LR-SHANNON-AWGN-V1", limitId: "LR-SHANNON-AWGN", version: 1, formalStatement: "The capacity of a band-limited additive white Gaussian noise channel is C = B log₂(1 + P/N).", constraints: { channel: "band-limited AWGN", bandwidth: "B", signalPower: "P", noisePower: "N", reliability: "arbitrarily low error with sufficiently long codes" }, asymptotic: true, probabilistic: true };
const shannonEvidence: Evidence = { id: "EVD-LR-SHANNON-1", type: "MATHEMATICAL_PROOF", method: "CODING_THEOREM_AND_CONVERSE", verificationLevel: "SOURCE_CONFIRMED", label: "Capacity of the band-limited Gaussian channel", sourceUrl: "https://onlinelibrary.wiley.com/doi/abs/10.1002/j.1538-7305.1966.tb04214.x" };
export const shannonAwgnResearchPacket: ResearchPacket = { limit: { id: "LR-SHANNON-AWGN", title: "Capacity of a band-limited AWGN channel", category: "Information Theory", status: "PROVEN", direction: "MAXIMIZE", limitKind: "THEORETICAL_BOUND", canonicalStatus: "EXACT", summary: "The maximum reliable communication rate for a specified additive white Gaussian noise channel." }, specification: shannonSpec, claims: [exactTextClaim("CLM-LR-SHANNON", "SP-LR-SHANNON-AWGN-V1", "<=", "B log₂(1 + P/N)", "UPPER_BOUND", "Claude Shannon", 1948, "Channel capacity theorem", shannonEvidence.id, "THEORETICAL_DERIVATION")], evidence: [shannonEvidence], registryReviewStatus: "UNREVIEWED" };

const cloningSpec: SpecificationVersion = { id: "SP-LR-NO-CLONING-V1", limitId: "LR-NO-CLONING", version: 1, formalStatement: "No physical quantum operation can produce a perfect copy of every arbitrary unknown input quantum state.", constraints: { input: "arbitrary unknown quantum state", output: "perfect identical copies", operation: "physical quantum operation" }, asymptotic: false, probabilistic: false };
const cloningEvidence: Evidence = { id: "EVD-LR-NO-CLONING-1", type: "MATHEMATICAL_PROOF", method: "LINEARITY_OF_QUANTUM_MECHANICS", verificationLevel: "SOURCE_CONFIRMED", label: "Universal quantum no-cloning theorem", sourceUrl: "https://doi.org/10.1038/299802A0" };
export const noCloningResearchPacket: ResearchPacket = { limit: { id: "LR-NO-CLONING", title: "Perfect cloning of an arbitrary unknown quantum state", category: "Quantum Information", status: "PROVEN", direction: "MAXIMIZE", limitKind: "IMPOSSIBILITY_RESULT", canonicalStatus: "EXACT", summary: "Perfect universal cloning of an arbitrary unknown quantum state is forbidden by quantum mechanics." }, specification: cloningSpec, claims: [exactTextClaim("CLM-LR-NO-CLONING", "SP-LR-NO-CLONING-V1", "=", "impossible", "COUNTEREXAMPLE", "W. K. Wootters and W. H. Zurek", 1982, "A single quantum cannot be cloned", cloningEvidence.id, "MATHEMATICAL_PROOF")], evidence: [cloningEvidence], registryReviewStatus: "UNREVIEWED" };

export const foundationalResearchPackets: ResearchPacket[] = [carnotResearchPacket, betzResearchPacket, shannonAwgnResearchPacket, noCloningResearchPacket];


const foundationalPacket = (limit: ResearchPacket["limit"], specification: SpecificationVersion, claim: Claim, evidence: Evidence): ResearchPacket => ({ limit, specification, claims: [claim], evidence: [evidence], registryReviewStatus: "UNREVIEWED" });
const basisClaim = (id: string, specId: string, relation: Claim["relation"], value: string, type: Claim["claimType"], author: string, year: number, source: string, evidenceId: string): Claim => exactTextClaim(id, specId, relation, value, type, author, year, source, evidenceId, "THEORETICAL_DERIVATION");

const mlSpec = packetSpec("SP-LR-ML-V1", "LR-MARGOLUS-LEVITIN", "For time-independent unitary evolution, the orthogonalization time is bounded below by πℏ/[2(E−E₀)].", { evolution: "unitary time-independent", "state change": "orthogonalization", energy: "mean above ground state E−E₀" }, false);
const mlEvidence: Evidence = { id: "EVD-LR-ML-1", type: "MATHEMATICAL_PROOF", method: "QUANTUM_SPEED_LIMIT", verificationLevel: "SOURCE_CONFIRMED", label: "The maximum speed of dynamical evolution", sourceUrl: "https://doi.org/10.1016/S0167-2789(98)00054-2" };
export const margolusLevitinResearchPacket = foundationalPacket({ id: "LR-MARGOLUS-LEVITIN", title: "Minimum orthogonalization time for a quantum state", category: "Quantum Physics", status: "PROVEN", direction: "MINIMIZE", limitKind: "THEORETICAL_BOUND", canonicalStatus: "EXACT", summary: "The minimum time for a specified isolated quantum system to evolve to an orthogonal state." }, mlSpec, basisClaim("CLM-LR-ML", mlSpec.id, ">=", "πℏ/[2(E−E₀)]", "LOWER_BOUND", "Norman Margolus and Lev B. Levitin", 1998, "The maximum speed of dynamical evolution", mlEvidence.id), mlEvidence);

const copSpec = packetSpec("SP-LR-CARNOT-COP-V1", "LR-CARNOT-COP", "The coefficient of performance of a reversible refrigerator between reservoirs T_c<T_h is at most T_c/(T_h−T_c).", { device: "refrigerator", process: "reversible", coldReservoir: "T_c", hotReservoir: "T_h", units: "kelvin" }, false);
const copEvidence: Evidence = { id: "EVD-LR-CARNOT-COP-1", type: "MATHEMATICAL_PROOF", method: "REVERSIBLE_THERMODYNAMICS", verificationLevel: "SOURCE_CONFIRMED", label: "Carnot refrigerator coefficient of performance", sourceUrl: "https://openstax.org/books/university-physics-volume-2/pages/4-5-the-carnot-cycle" };
export const carnotCopResearchPacket = foundationalPacket({ id: "LR-CARNOT-COP", title: "Maximum coefficient of performance of a reversible refrigerator", category: "Thermodynamics", status: "PROVEN", direction: "MAXIMIZE", limitKind: "THEORETICAL_BOUND", canonicalStatus: "EXACT", summary: "The maximum refrigeration performance between specified cold and hot reservoirs." }, copSpec, basisClaim("CLM-LR-CARNOT-COP", "SP-LR-CARNOT-COP-V1", "<=", "T_c/(T_h−T_c)", "UPPER_BOUND", "Sadi Carnot", 1824, "Carnot refrigerator theorem", copEvidence.id), copEvidence);

const holevoSpec = packetSpec("SP-LR-HOLEVO-V1", "LR-HOLEVO", "For a classical variable X encoded in quantum states and a measurement outcome Y, accessible information I(X:Y) is at most χ = S(ρ)−Σ p_x S(ρ_x).", { channel: "classical-quantum", encoding: "ensemble of quantum states", output: "measurement outcome", metric: "classical mutual information" }, false);
const holevoEvidence: Evidence = { id: "EVD-LR-HOLEVO-1", type: "MATHEMATICAL_PROOF", method: "QUANTUM_INFORMATION_INEQUALITY", verificationLevel: "SOURCE_CONFIRMED", label: "Capacity of a quantum channel with general signal states", sourceUrl: "https://arxiv.org/abs/quant-ph/9611023" };
export const holevoResearchPacket = foundationalPacket({ id: "LR-HOLEVO", title: "Accessible classical information from a quantum ensemble", category: "Quantum Information", status: "PROVEN", direction: "MAXIMIZE", limitKind: "THEORETICAL_BOUND", canonicalStatus: "EXACT", summary: "The maximum accessible classical information under a specified quantum-state ensemble and measurement model." }, holevoSpec, basisClaim("CLM-LR-HOLEVO", holevoSpec.id, "<=", "χ = S(ρ) − Σ p_x S(ρ_x)", "UPPER_BOUND", "Alexander Holevo", 1998, "Quantum channel capacity theorem", holevoEvidence.id), holevoEvidence);

const nyquistSpec = packetSpec("SP-LR-NYQUIST-V1", "LR-NYQUIST", "A signal band-limited to B Hz can be perfectly reconstructed from uniform samples taken at rate at least 2B samples per second.", { signal: "continuous-time", bandwidth: "B Hz", reconstruction: "ideal exact", sampling: "uniform" }, false);
const nyquistEvidence: Evidence = { id: "EVD-LR-NYQUIST-1", type: "MATHEMATICAL_PROOF", method: "BANDLIMITED_SIGNAL_RECONSTRUCTION", verificationLevel: "SOURCE_CONFIRMED", label: "Classical sampling theorem", sourceUrl: "https://www.govinfo.gov/content/pkg/GOVPUB-D101-PURL-gpo2614/pdf/GOVPUB-D101-PURL-gpo2614.pdf" };
export const nyquistResearchPacket = foundationalPacket({ id: "LR-NYQUIST", title: "Minimum sampling rate for exact reconstruction", category: "Signal Processing", status: "PROVEN", direction: "MINIMIZE", limitKind: "THEORETICAL_BOUND", canonicalStatus: "EXACT", summary: "The minimum uniform sampling rate for exact reconstruction of a signal with specified bandwidth." }, nyquistSpec, basisClaim("CLM-LR-NYQUIST", nyquistSpec.id, ">=", "2B", "LOWER_BOUND", "Harry Nyquist and Claude Shannon", 1949, "Sampling theorem", nyquistEvidence.id), nyquistEvidence);

const bekensteinSpec = packetSpec("SP-LR-BEKENSTEIN-V1", "LR-BEKENSTEIN", "For a bounded system with effective radius R and total energy E, entropy-to-energy ratio is bounded by 2πR/(ℏc).", { system: "bounded physical system", radius: "effective R", energy: "total E", quantity: "entropy S" }, false);
const bekensteinEvidence: Evidence = { id: "EVD-LR-BEKENSTEIN-1", type: "THEORETICAL_DERIVATION", method: "BLACK_HOLE_THOUGHT_EXPERIMENT", verificationLevel: "SOURCE_CONFIRMED", label: "Universal upper bound on entropy-to-energy ratio", sourceUrl: "https://doi.org/10.1103/PhysRevD.23.287" };
export const bekensteinResearchPacket = foundationalPacket({ id: "LR-BEKENSTEIN", title: "Maximum entropy-to-energy ratio of a bounded system", category: "Physics / Information", status: "PROVEN", direction: "MAXIMIZE", limitKind: "THEORETICAL_BOUND", canonicalStatus: "EXACT", summary: "A theory-dependent upper bound on the entropy content of a finite physical system." }, bekensteinSpec, basisClaim("CLM-LR-BEKENSTEIN", bekensteinSpec.id, "<=", "2πR/(ℏc)", "UPPER_BOUND", "Jacob Bekenstein", 1981, "Universal upper bound on entropy-to-energy ratio", bekensteinEvidence.id), bekensteinEvidence);

export const moreFoundationalResearchPackets: ResearchPacket[] = [margolusLevitinResearchPacket, carnotCopResearchPacket, holevoResearchPacket, nyquistResearchPacket, bekensteinResearchPacket];

const aiSpec = (id: string, limitId: string, formalStatement: string, constraints: Record<string, string>, asymptotic = true): SpecificationVersion => packetSpec(id, limitId, formalStatement, constraints, asymptotic);
const aiEvidence = (id: string, label: string, url: string, method = "THEORETICAL_ANALYSIS"): Evidence => ({ id, type: "MATHEMATICAL_PROOF", method, verificationLevel: "SOURCE_CONFIRMED", label, sourceUrl: url });
const aiClaim = (id: string, specId: string, relation: Claim["relation"], value: string, type: Claim["claimType"], author: string, year: number, source: string, evidenceId: string): Claim => exactTextClaim(id, specId, relation, value, type, author, year, source, evidenceId, "MATHEMATICAL_PROOF");

const widthSpec = aiSpec("SP-LR-AI-WIDTH-V1", "LR-AI-WIDTH", "For ReLU networks approximating Lᵖ functions from R^{dₓ} to R^{dᵧ}, determine the minimum hidden-layer width enabling universal approximation.", { activation: "ReLU", functionSpace: "Lᵖ", inputDimension: "dₓ", outputDimension: "dᵧ", domain: "specified measurable domain" });
const widthEvidence = aiEvidence("EVD-LR-AI-WIDTH-1", "Minimum width for universal approximation", "https://openreview.net/pdf?id=O-XJwyoIF-k");
export const aiMinimumWidthResearchPacket = foundationalPacket({ id: "LR-AI-WIDTH", title: "Minimum width for ReLU universal approximation", category: "AI / Neural Network Theory", status: "PROVEN", direction: "MINIMIZE", limitKind: "THEORETICAL_BOUND", canonicalStatus: "EXACT", summary: "The minimum hidden-layer width required for universal Lᵖ approximation under a fixed ReLU specification." }, widthSpec, aiClaim("CLM-LR-AI-WIDTH", widthSpec.id, ">=", "max(dₓ + 1, dᵧ)", "LOWER_BOUND", "Park, Yun, Lee, Shin", 2021, "Minimum Width for Universal Approximation", widthEvidence.id), widthEvidence);

const pacSpec = aiSpec("SP-LR-AI-PAC-V1", "LR-AI-PAC", "Determine the minimum number of iid labeled examples needed for realizable PAC learning of a hypothesis class H with error ε and confidence 1−δ.", { regime: "realizable PAC", hypothesisClass: "H", accuracy: "ε", confidence: "1−δ", distribution: "iid" });
const pacEvidence = aiEvidence("EVD-LR-AI-PAC-1", "The optimal sample complexity of PAC learning", "https://jmlr.csail.mit.edu/papers/v17/15-389.html", "PAC_SAMPLE_COMPLEXITY");
export const aiPacSampleResearchPacket = foundationalPacket({ id: "LR-AI-PAC", title: "Minimum samples for PAC learning", category: "AI / Learning Theory", status: "PROVEN", direction: "MINIMIZE", limitKind: "THEORETICAL_BOUND", canonicalStatus: "EXACT", summary: "The minimum labeled sample size required to learn a specified hypothesis class to error ε with confidence 1−δ." }, pacSpec, aiClaim("CLM-LR-AI-PAC", pacSpec.id, ">=", "Θ((VC(H)+log(1/δ))/ε)", "LOWER_BOUND", "Hanneke", 2016, "The Optimal Sample Complexity of PAC Learning", pacEvidence.id), pacEvidence);

const robustnessSpec = aiSpec("SP-LR-AI-ROBUST-V1", "LR-AI-ROBUST", "For a fixed classifier f and input x, determine the largest certified radius r such that f(x+δ)=f(x) for every perturbation with ||δ||₂≤r.", { model: "fixed classifier f", norm: "L2", guarantee: "for all perturbations", evaluation: "certified" }, false);
const robustnessEvidence = aiEvidence("EVD-LR-AI-ROBUST-1", "Certified adversarial robustness under bounded support", "https://proceedings.mlr.press/v162/kou22a.html", "CERTIFIED_ROBUSTNESS");
export const aiRobustnessResearchPacket = foundationalPacket({ id: "LR-AI-ROBUST", title: "Largest certified adversarial radius", category: "AI / Robustness", status: "OPEN", direction: "MAXIMIZE", limitKind: "EMPIRICAL_FRONTIER", summary: "The largest perturbation radius for which a fixed classifier has a formally certified prediction guarantee." }, robustnessSpec, aiClaim("CLM-LR-AI-ROBUST", robustnessSpec.id, ">=", "r", "COMPUTATIONAL_BOUND", "Kou, Zheng, Wang", 2022, "Certified Adversarial Robustness Under the Bounded Support Set", robustnessEvidence.id), robustnessEvidence);

const approximationSpec = aiSpec("SP-LR-AI-APPROX-V1", "LR-AI-APPROX", "For a target function class F, determine the minimum network size N required to achieve approximation error at most ε in a specified norm.", { architecture: "ReLU network", target: "function class F", error: "ε", norm: "specified approximation norm", resource: "width/depth/parameters N" });
const approximationEvidence = aiEvidence("EVD-LR-AI-APPROX-1", "Optimal approximation rate of ReLU networks", "https://doi.org/10.1016/j.jde.2021.07.003", "APPROXIMATION_RATE");
export const aiApproximationRateResearchPacket = foundationalPacket({ id: "LR-AI-APPROX", title: "Minimum ReLU network size for approximation error ε", category: "AI / Approximation Theory", status: "OPEN", direction: "MINIMIZE", limitKind: "THEORETICAL_BOUND", summary: "The minimum architecture resource required to approximate a specified function class within error ε." }, approximationSpec, aiClaim("CLM-LR-AI-APPROX", approximationSpec.id, ">=", "N(F, ε)", "LOWER_BOUND", "Petersen and Voigtlaender", 2021, "Optimal approximation rate of ReLU networks", approximationEvidence.id), approximationEvidence);

const transformerSpec = aiSpec("SP-LR-AI-TRANSFORMER-V1", "LR-AI-TRANSFORMER", "A transformer expressivity Limit requires a fixed depth, precision, attention mechanism, positional encoding, target language, and generalization regime.", { architecture: "transformer", depth: "UNSPECIFIED", precision: "UNSPECIFIED", task: "UNSPECIFIED" }, true);
export const aiTransformerExpressivityResearchPacket: ResearchPacket = { limit: { id: "LR-AI-TRANSFORMER", title: "Transformer expressivity under a fixed formal task", category: "AI / Theory", status: "OPEN", direction: "MAXIMIZE", limitKind: "THEORETICAL_BOUND", summary: "A placeholder for architecture-specific transformer expressivity results; no claim is published until the task and architecture are fixed." }, specification: transformerSpec, claims: [], evidence: [], registryReviewStatus: "UNREVIEWED" };

export const aiResearchPackets: ResearchPacket[] = [aiMinimumWidthResearchPacket, aiPacSampleResearchPacket, aiRobustnessResearchPacket, aiApproximationRateResearchPacket, aiTransformerExpressivityResearchPacket];

const rnnSpec: SpecificationVersion = { id: "SP-LR-AI-RNN-WIDTH-V1", limitId: "LR-AI-RNN-WIDTH", version: 1, formalStatement: "For finite sequence-to-sequence maps from R^{dₓ} to R^{dᵧ}, determine the minimum width of a deep ReLU RNN with arbitrary depth that has universal approximation property.", constraints: { architecture: "deep RNN", activation: "ReLU", inputDimension: "dₓ", outputDimension: "dᵧ", target: "continuous sequence-to-sequence functions" }, asymptotic: false, probabilistic: false };
const rnnEvidence: Evidence = { id: "EVD-LR-AI-RNN-WIDTH-1", type: "MATHEMATICAL_PROOF", method: "RECURRENT_UNIVERSAL_APPROXIMATION", verificationLevel: "SOURCE_CONFIRMED", label: "Minimal width for universal property of deep RNN", sourceUrl: "https://www.jmlr.org/papers/volume24/22-1191.html" };
export const aiRnnWidthResearchPacket = foundationalPacket({ id: "LR-AI-RNN-WIDTH", title: "Minimum width for universal deep RNN approximation", category: "AI / Neural Network Theory", status: "PROVEN", direction: "MINIMIZE", limitKind: "THEORETICAL_BOUND", canonicalStatus: "EXACT", summary: "The minimum recurrent width required for universal approximation of specified sequence-to-sequence functions." }, rnnSpec, aiClaim("CLM-LR-AI-RNN-WIDTH", rnnSpec.id, ">=", "max(dₓ + 1, dᵧ)", "LOWER_BOUND", "Song, Hwang, Lee, Kang", 2023, "Minimal Width for Universal Property of Deep RNN", rnnEvidence.id), rnnEvidence);

const trainingSpec: SpecificationVersion = { id: "SP-LR-AI-TRAINING-HARDNESS-V1", limitId: "LR-AI-TRAINING-HARDNESS", version: 1, formalStatement: "Given labeled examples, decide whether a fixed two-layer three-node linear-threshold neural network has weights and thresholds consistent with all examples.", constraints: { architecture: "two-layer, three-node", activation: "linear threshold", task: "consistent training decision", complexityModel: "polynomial-time reductions" }, asymptotic: false, probabilistic: false };
const trainingEvidence: Evidence = { id: "EVD-LR-AI-TRAINING-HARDNESS-1", type: "MATHEMATICAL_PROOF", method: "NP_COMPLETENESS_REDUCTION", verificationLevel: "SOURCE_CONFIRMED", label: "Training a 3-node neural network is NP-complete", sourceUrl: "https://doi.org/10.1016/S0893-6080(05)80010-3" };
export const aiTrainingHardnessResearchPacket: ResearchPacket = { limit: { id: "LR-AI-TRAINING-HARDNESS", title: "Exact training of a small threshold network", category: "AI / Computational Complexity", status: "PROVEN", direction: "MINIMIZE", limitKind: "IMPOSSIBILITY_RESULT", canonicalStatus: "EXACT", summary: "Finding weights consistent with arbitrary labeled examples is NP-complete even for a fixed small threshold network." }, specification: trainingSpec, claims: [aiClaim("CLM-LR-AI-TRAINING-NP", trainingSpec.id, "=", "NP-complete", "COMPUTATIONAL_BOUND", "Avrim Blum and Ronald Rivest", 1992, "Training a 3-node neural network is NP-complete", trainingEvidence.id)], evidence: [trainingEvidence], registryReviewStatus: "UNREVIEWED" };

export const moreAiResearchPackets: ResearchPacket[] = [aiRnnWidthResearchPacket, aiTrainingHardnessResearchPacket];

const vcSpec: SpecificationVersion = { id: "SP-LR-AI-VC-V1", limitId: "LR-AI-VC", version: 1, formalStatement: "Determine the VC dimension of a piecewise-linear neural-network function class with W parameters and L layers.", constraints: { activation: "piecewise-linear", parameters: "W weights", depth: "L layers", quantity: "VC dimension" }, asymptotic: true, probabilistic: false };
const vcEvidence: Evidence = { id: "EVD-LR-AI-VC-1", type: "MATHEMATICAL_PROOF", method: "VC_DIMENSION_BOUND", verificationLevel: "SOURCE_CONFIRMED", label: "Nearly-tight VC-dimension bounds for piecewise-linear neural networks", sourceUrl: "https://jmlr.csail.mit.edu/papers/v20/17-612.html" };
export const aiVcDimensionResearchPacket = foundationalPacket({ id: "LR-AI-VC", title: "VC dimension of a piecewise-linear neural network", category: "AI / Learning Theory", status: "OPEN", direction: "MAXIMIZE", limitKind: "THEORETICAL_BOUND", summary: "The capacity of a specified piecewise-linear neural-network class as a function of weights and depth." }, vcSpec, aiClaim("CLM-LR-AI-VC-UPPER", vcSpec.id, "<=", "O(WL log W)", "UPPER_BOUND", "Bartlett, Harvey, Liaw, Mehrabian", 2019, "Nearly-tight VC-dimension bounds", vcEvidence.id), vcEvidence);

const depthSpec: SpecificationVersion = { id: "SP-LR-AI-DEPTH-V1", limitId: "LR-AI-DEPTH", version: 1, formalStatement: "For a specified target function class and approximation error ε, compare the minimum size of networks at different fixed depths.", constraints: { activation: "ReLU", target: "specified function class", error: "ε", comparison: "depth 2 versus depth 3", size: "number of units" }, asymptotic: true, probabilistic: false };
const depthEvidence: Evidence = { id: "EVD-LR-AI-DEPTH-1", type: "MATHEMATICAL_PROOF", method: "DEPTH_SEPARATION", verificationLevel: "SOURCE_CONFIRMED", label: "Depth separations in neural networks", sourceUrl: "https://proceedings.mlr.press/v99/safran19a.html" };
export const aiDepthSeparationResearchPacket = foundationalPacket({ id: "LR-AI-DEPTH", title: "Depth required for efficient neural approximation", category: "AI / Approximation Theory", status: "OPEN", direction: "MINIMIZE", limitKind: "THEORETICAL_BOUND", summary: "The minimum network depth needed to approximate a specified function class without exponential size growth." }, depthSpec, aiClaim("CLM-LR-AI-DEPTH-LOWER", depthSpec.id, ">=", "3 for the specified separation family", "LOWER_BOUND", "Safran, Eldan, Shamir", 2019, "Depth Separations in Neural Networks", depthEvidence.id), depthEvidence);

const nflSpec: SpecificationVersion = { id: "SP-LR-AI-NFL-V1", limitId: "LR-AI-NFL", version: 1, formalStatement: "Under a uniform distribution over all target functions or learning problems, compare the expected performance of supervised learners.", constraints: { regime: "supervised learning", taskDistribution: "uniform over target functions", comparison: "expected generalization performance" }, asymptotic: false, probabilistic: true };
const nflEvidence: Evidence = { id: "EVD-LR-AI-NFL-1", type: "MATHEMATICAL_PROOF", method: "NO_FREE_LUNCH_THEOREM", verificationLevel: "SOURCE_CONFIRMED", label: "The no-free-lunch theorems of supervised learning", sourceUrl: "https://link.springer.com/article/10.1007/s11229-021-03233-1" };
export const aiNoFreeLunchResearchPacket: ResearchPacket = { limit: { id: "LR-AI-NFL", title: "Universal superiority of a supervised learner", category: "AI / Learning Theory", status: "PROVEN", direction: "MAXIMIZE", limitKind: "IMPOSSIBILITY_RESULT", canonicalStatus: "EXACT", summary: "No supervised learner is uniformly best across all target-function distributions under the specified no-free-lunch regime." }, specification: nflSpec, claims: [aiClaim("CLM-LR-AI-NFL", nflSpec.id, "=", "no universal best learner", "COUNTEREXAMPLE", "David Wolpert and William Macready", 1997, "No-free-lunch theorem", nflEvidence.id)], evidence: [nflEvidence], registryReviewStatus: "UNREVIEWED" };

const tradeoffSpec: SpecificationVersion = { id: "SP-LR-AI-ROBUST-TRADEOFF-V1", limitId: "LR-AI-ROBUST-TRADEOFF", version: 1, formalStatement: "For a fixed data distribution, classifier family, accuracy metric, and perturbation set, characterize achievable pairs of standard and adversarial accuracy.", constraints: { threatModel: "specified perturbation set", metric: "standard and robust classification error", distribution: "fixed", classifier: "measurable predictors" }, asymptotic: false, probabilistic: true };
const tradeoffEvidence: Evidence = { id: "EVD-LR-AI-ROBUST-TRADEOFF-1", type: "MATHEMATICAL_PROOF", method: "ROBUSTNESS_ACCURACY_TRADEOFF", verificationLevel: "SOURCE_CONFIRMED", label: "Theoretically principled trade-off between robustness and accuracy", sourceUrl: "https://arxiv.org/abs/1901.08573" };
export const aiRobustnessAccuracyResearchPacket: ResearchPacket = { limit: { id: "LR-AI-ROBUST-TRADEOFF", title: "Maximum robustness at a fixed accuracy", category: "AI / Robustness", status: "OPEN", direction: "MAXIMIZE", limitKind: "THEORETICAL_BOUND", summary: "The maximum certified adversarial robustness achievable while maintaining a specified standard accuracy." }, specification: tradeoffSpec, claims: [aiClaim("CLM-LR-AI-ROBUST-TRADEOFF", tradeoffSpec.id, "<=", "R*(A)", "UPPER_BOUND", "Zhang et al.", 2019, "Theoretically Principled Trade-off between Robustness and Accuracy", tradeoffEvidence.id)], evidence: [tradeoffEvidence], registryReviewStatus: "UNREVIEWED" };

export const extendedAiResearchPackets: ResearchPacket[] = [aiRnnWidthResearchPacket, aiTrainingHardnessResearchPacket, aiVcDimensionResearchPacket, aiDepthSeparationResearchPacket, aiNoFreeLunchResearchPacket, aiRobustnessAccuracyResearchPacket];

const infraSpec = (id: string, limitId: string, statement: string, constraints: Record<string, string>, asymptotic = true, probabilistic = false): SpecificationVersion => packetSpec(id, limitId, statement, constraints, asymptotic, probabilistic);
const infraEvidence = (id: string, label: string, url: string, method = "THEORETICAL_DERIVATION"): Evidence => ({ id, type: method === "MEASUREMENT_PROTOCOL" ? "OBSERVATION" : "MATHEMATICAL_PROOF", method, verificationLevel: "SOURCE_CONFIRMED", label, sourceUrl: url });
const infraClaim = (id: string, specId: string, relation: Claim["relation"], value: string, type: Claim["claimType"], author: string, year: number, source: string, evidenceId: string, basis: NonNullable<Claim["evidenceBasis"]>[number] = "THEORETICAL_DERIVATION"): Claim => exactTextClaim(id, specId, relation, value, type, author, year, source, evidenceId, basis);

const timeSpec = infraSpec("SP-LR-TIME-HIERARCHY-V1", "LR-TIME-HIERARCHY", "For time-constructible f and g with f(n)log f(n)=o(g(n)), DTIME(f) is strictly contained in DTIME(g).", { model: "deterministic Turing machine", bounds: "time-constructible f,g", separation: "f log f = o(g)" });
const timeEvidence = infraEvidence("EVD-LR-TIME-HIERARCHY-1", "Time hierarchy theorem", "https://theory.cs.princeton.edu/complexity/book.pdf");
export const timeHierarchyResearchPacket = foundationalPacket({ id: "LR-TIME-HIERARCHY", title: "Computational power gained from additional time", category: "Computation / Complexity", status: "PROVEN", direction: "MAXIMIZE", limitKind: "THEORETICAL_BOUND", canonicalStatus: "EXACT", summary: "A strict separation between deterministic time-bounded computational classes." }, timeSpec, infraClaim("CLM-LR-TIME-HIERARCHY", timeSpec.id, "<", "DTIME(f) ⊊ DTIME(g)", "UPPER_BOUND", "Hartmanis and Stearns", 1965, "Time hierarchy theorem", timeEvidence.id), timeEvidence);

const spaceSpec = infraSpec("SP-LR-SPACE-HIERARCHY-V1", "LR-SPACE-HIERARCHY", "For space-constructible s1=o(s2), DSPACE(s1) is strictly contained in DSPACE(s2).", { model: "deterministic Turing machine", bounds: "space-constructible s1,s2", separation: "s1=o(s2)" });
const spaceEvidence = infraEvidence("EVD-LR-SPACE-HIERARCHY-1", "Space hierarchy theorem", "https://plato.sydney.edu.au/entries/computational-complexity/");
export const spaceHierarchyResearchPacket = foundationalPacket({ id: "LR-SPACE-HIERARCHY", title: "Computational power gained from additional space", category: "Computation / Complexity", status: "PROVEN", direction: "MAXIMIZE", limitKind: "THEORETICAL_BOUND", canonicalStatus: "EXACT", summary: "A strict separation between space-bounded computational classes." }, spaceSpec, infraClaim("CLM-LR-SPACE-HIERARCHY", spaceSpec.id, "<", "DSPACE(s₁) ⊊ DSPACE(s₂)", "UPPER_BOUND", "Hartmanis and Stearns", 1965, "Space hierarchy theorem", spaceEvidence.id), spaceEvidence);

const codingSpec = infraSpec("SP-LR-CODING-BOUNDS-V1", "LR-CODING-BOUNDS", "For a q-ary code with length n, size M, dimension k, and minimum distance d, compare achievable code parameters with universal bounds.", { alphabet: "q-ary", length: "n", size: "M", dimension: "k", distance: "d" }, true);
const codingEvidence = infraEvidence("EVD-LR-CODING-BOUNDS-1", "Singleton, sphere-packing, and Gilbert–Varshamov bounds", "https://www.cambridge.org/core/books/introduction-to-coding-theory/bounds-on-the-parameters-of-codes/39E9DAA5040D4D4DFCC6F84685C59AB");
export const codingBoundsResearchPacket: ResearchPacket = { limit: { id: "LR-CODING-BOUNDS", title: "Achievable code rate at a specified distance", category: "Coding Theory", status: "OPEN", direction: "MAXIMIZE", limitKind: "THEORETICAL_BOUND", summary: "The maximum rate of a q-ary code subject to length, distance, and alphabet constraints." }, specification: codingSpec, claims: [infraClaim("CLM-LR-CODING-SINGLETON", codingSpec.id, "<=", "k ≤ n − d + 1", "UPPER_BOUND", "Richard Singleton", 1964, "Singleton bound", codingEvidence.id), infraClaim("CLM-LR-CODING-HAMMING", codingSpec.id, "<=", "M · Σᵢ₌₀ᵗ C(n,i)(q−1)ⁱ ≤ qⁿ", "UPPER_BOUND", "R. W. Hamming", 1950, "Sphere-packing bound", codingEvidence.id), infraClaim("CLM-LR-CODING-GV", codingSpec.id, ">=", "existence when the Gilbert–Varshamov inequality holds", "LOWER_BOUND", "E. N. Gilbert and R. R. Varshamov", 1952, "Gilbert–Varshamov bound", codingEvidence.id)], evidence: [codingEvidence], registryReviewStatus: "UNREVIEWED" };

const distributedCapSpec = infraSpec("SP-LR-CAP-V1", "LR-CAP", "A distributed read/write object must choose between linearizable consistency and guaranteed availability during an asynchronous network partition.", { system: "distributed storage", consistency: "linearizability", availability: "every request eventually responds", failure: "network partition" }, false, true);
const distributedCapEvidence = infraEvidence("EVD-LR-CAP-1", "CAP theorem and distributed storage consistency", "https://www.eurecom.fr/publication/5172/download/data-publi-5172.pdf");
export const capTheoremResearchPacket: ResearchPacket = { limit: { id: "LR-CAP", title: "Simultaneous consistency and availability during partition", category: "Cloud / Distributed Systems", status: "PROVEN", direction: "MAXIMIZE", limitKind: "IMPOSSIBILITY_RESULT", canonicalStatus: "EXACT", summary: "Whether a partition-tolerant distributed store can guarantee both linearizability and availability." }, specification: distributedCapSpec, claims: [infraClaim("CLM-LR-CAP", distributedCapSpec.id, "=", "impossible under the stated model", "COUNTEREXAMPLE", "Eric Brewer; Gilbert and Lynch", 2002, "CAP theorem", distributedCapEvidence.id, "MATHEMATICAL_PROOF")], evidence: [distributedCapEvidence], registryReviewStatus: "UNREVIEWED" };

const bdpSpec = infraSpec("SP-LR-BDP-V1", "LR-BDP", "For a TCP path, the bandwidth-delay product equals bottleneck bandwidth multiplied by round-trip time and determines the in-flight data needed to fill the path.", { protocol: "TCP", bandwidth: "bottleneck bandwidth", delay: "RTT", path: "specified end-to-end path" }, false);
const bdpEvidence = infraEvidence("EVD-LR-BDP-1", "Framework for TCP throughput testing", "https://www.rfc-editor.org/info/rfc6349", "MEASUREMENT_PROTOCOL");
export const bandwidthDelayProductResearchPacket = foundationalPacket({ id: "LR-BDP", title: "In-flight data required to saturate a TCP path", category: "Networking", status: "PROVEN", direction: "MINIMIZE", limitKind: "THEORETICAL_BOUND", canonicalStatus: "EXACT", summary: "The bandwidth-delay product required for a TCP connection to utilize a specified path capacity." }, bdpSpec, infraClaim("CLM-LR-BDP", bdpSpec.id, "=", "BDP = bandwidth × RTT", "EXACT_VALUE", "IETF", 2011, "RFC 6349", bdpEvidence.id), bdpEvidence);

const storageSpec = infraSpec("SP-LR-STORAGE-DENSITY-V1", "LR-STORAGE-DENSITY", "Measure reproducible information density under a specified storage technology, physical volume or area, retention period, temperature, and bit-error rate.", { medium: "specified storage medium", metric: "bits per area or volume", retention: "specified time", errorRate: "specified BER" }, false);
const storageEvidence = infraEvidence("EVD-LR-STORAGE-DENSITY-1", "High-density magnetic recording measurement context", "https://www.jstage.jst.go.jp/article/jmsjmag/15/S_2_PMRC_91/15_S2_475/_article/-char/en", "MEASUREMENT_PROTOCOL");
export const storageDensityResearchPacket: ResearchPacket = { limit: { id: "LR-STORAGE-DENSITY", title: "Maximum verified information storage density", category: "Data Storage", status: "OPEN", direction: "MAXIMIZE", limitKind: "EMPIRICAL_FRONTIER", summary: "The highest reproducibly measured information density under a fixed medium, retention, temperature, and error-rate specification." }, specification: storageSpec, claims: [], evidence: [storageEvidence], registryReviewStatus: "UNREVIEWED" };

const apiSpec = infraSpec("SP-LR-API-RATE-V1", "LR-API-RATE", "Measure the maximum sustained request rate for a named API endpoint under a specified provider, authentication tier, quota window, payload, and response-success criterion.", { provider: "named provider", endpoint: "named endpoint", tier: "authentication tier", window: "quota window", success: "HTTP success criterion" }, false);
const apiEvidence = infraEvidence("EVD-LR-API-RATE-1", "HTTP rate-limiting semantics", "https://www.ietf.org/rfc/rfc6585.txt.pdf", "MEASUREMENT_PROTOCOL");
export const apiRateResearchPacket: ResearchPacket = { limit: { id: "LR-API-RATE", title: "Maximum sustained request rate for an API endpoint", category: "APIs / Internet Services", status: "OPEN", direction: "MAXIMIZE", limitKind: "EMPIRICAL_FRONTIER", summary: "The highest verified request rate for a specified endpoint and provider configuration without rate-limit responses." }, specification: apiSpec, claims: [], evidence: [apiEvidence], registryReviewStatus: "UNREVIEWED" };

export const computationCodingNetworkResearchPackets: ResearchPacket[] = [timeHierarchyResearchPacket, spaceHierarchyResearchPacket, codingBoundsResearchPacket, capTheoremResearchPacket, bandwidthDelayProductResearchPacket, storageDensityResearchPacket, apiRateResearchPacket];

// Research pass: scoped drafts. These are intentionally not part of the public
// registry or the database seed until an independent editor accepts their claims.
const draftSpec = (id: string, limitId: string, statement: string, constraints: Record<string, string>, asymptotic = false): SpecificationVersion => ({ id, limitId, version: 1, formalStatement: statement, constraints, asymptotic, probabilistic: false });
const draftEvidence = (id: string, label: string, url: string, type: Evidence["type"] = "PAPER"): Evidence => ({ id, type, verificationLevel: "REPORTED", label, sourceUrl: url });
const draftClaim = (id: string, specId: string, relation: Claim["relation"], value: string, claimType: Claim["claimType"], author: string, year: number, source: string, evidenceId: string, basis: NonNullable<Claim["evidenceBasis"]>[number] = "THEORETICAL_DERIVATION"): Claim => ({ id, specificationVersionId: specId, relation, value: { kind: "text", value }, claimType, status: "DRAFT", epistemicStatus: "LITERATURE_ASSERTED", scientificStatus: "ACCEPTED", registryReviewStatus: "UNREVIEWED", evidenceBasis: [basis], evidenceIds: [evidenceId], author, year, source });
const readyDraft = (id: string, title: string, category: string, direction: Direction, description: string, formalQuestion: string, constraints: Record<string, string>, claim: [Claim["relation"], string, Claim["claimType"], string, number, string], url: string, basis: NonNullable<Claim["evidenceBasis"]>[number] = "THEORETICAL_DERIVATION"): ResearchPacket => { const spec = draftSpec(`SP-${id}-V1`, id, formalQuestion, constraints); const evidence = draftEvidence(`EVD-${id}-1`, title, url, basis === "OBSERVATION" ? "OBSERVATION" : basis === "CONSTRUCTION" ? "CONSTRUCTION" : "PAPER"); return { limit: { id, title, category, status: "DRAFT", direction, summary: description, limitKind: basis === "OBSERVATION" ? "OBSERVED_RECORD" : "THEORETICAL_BOUND" }, specification: spec, claims: [draftClaim(`CLM-${id}-1`, spec.id, claim[0], claim[1], claim[2], claim[3], claim[4], claim[5], evidence.id, basis)], evidence: [evidence], registryReviewStatus: "UNREVIEWED", publicationState: "DRAFT", ingestionReadiness: "READY_FOR_EDITORIAL_REVIEW", independentRegistryReviews: 0 }; };

export const researchedDraftPackets: ResearchPacket[] = [
  readyDraft("LR-DRAFT-CARNOT", "Carnot heat-engine efficiency", "Physics / Thermodynamics", "MAXIMIZE", "No heat engine operating between two temperature reservoirs can convert heat to work more efficiently than a reversible one: the Carnot limit η ≤ 1 − T_c/T_h, where T_h and T_c are the hot and cold reservoir temperatures.", "What is the maximum thermodynamic efficiency η achievable by any heat engine operating between a hot reservoir at T_h and a cold reservoir at T_c?", { hotReservoir: "T_h", coldReservoir: "T_c", process: "reversible" }, ["<=", "1 − T_c/T_h", "UPPER_BOUND", "Sadi Carnot", 1824, "Réflexions sur la puissance motrice du feu"], "https://openstax.org/books/college-physics/pages/15-4-carnots-perfect-heat-engine-the-second-law-of-thermodynamics-restated"),
  readyDraft("LR-DRAFT-LANDAUER", "Landauer bit-erasure limit", "Physics / Information", "MINIMIZE", "Erasing one bit of information in a logically irreversible way necessarily dissipates heat into the environment — a fundamental link between information and thermodynamics. The minimum dissipated energy is Q ≥ k_B T ln(2), where T is the system's temperature.", "What is the minimum energy Q that must be dissipated as heat to logically erase one bit of information at temperature T?", { temperature: "T", operation: "logically irreversible bit erasure" }, [">=", "k_B T ln(2)", "LOWER_BOUND", "Rolf Landauer", 1961, "Irreversibility and Heat Generation in the Computing Process"], "https://doi.org/10.1147/RD.53.0183"),
  readyDraft("LR-DRAFT-BEKENSTEIN", "Bekenstein entropy bound", "Physics / Gravitation", "MAXIMIZE", "The entropy — and so the total information content — of any physical system is capped by its energy and physical size: S ≤ 2π k_B E R/(ℏ c) for a system with energy E confined within radius R, setting an absolute upper limit on how much information can fit in a bounded region of space.", "What is the maximum entropy S — and so the maximum information content — of a physical system with energy E confined within a sphere of radius R?", { system: "bounded physical system", energy: "E", radius: "R" }, ["<=", "2π k_B E R/(ℏ c)", "UPPER_BOUND", "Jacob Bekenstein", 1981, "Universal upper bound on the entropy-to-energy ratio for bounded systems"], "https://journals.aps.org/prd/abstract/10.1103/PhysRevD.23.287"),
  readyDraft("LR-DRAFT-ML", "Margolus–Levitin quantum speed limit", "Physics / Quantum", "MINIMIZE", "The Margolus–Levitin theorem sets a fundamental speed limit on how fast any physical process, including computation, can occur: an isolated quantum system needs at least τ ≥ πℏ/[2(E−E₀)] to evolve into a fully distinguishable (orthogonal) state.", "What is the minimum time τ for an isolated quantum system with mean energy E above its ground state E₀ to evolve into an orthogonal state?", { system: "isolated quantum system", energy: "mean energy above ground E−E₀" }, [">=", "πℏ/[2(E−E₀)]", "LOWER_BOUND", "Norman Margolus and Lev Levitin", 1998, "The maximum speed of dynamical evolution"], "https://www.sciencedirect.com/science/article/pii/S0167278998000542"),
  readyDraft("LR-DRAFT-SHANNON", "Shannon channel capacity and source-coding limits", "Information Theory", "MAXIMIZE", "Shannon's noisy-channel coding theorem defines the hard ceiling on reliable communication: no coding scheme can transmit information faster than a channel's capacity without introducing errors, no matter how sophisticated the encoding.", "What is the maximum rate C at which information can be transmitted over a channel with bandwidth B and signal-to-noise ratio P/N with arbitrarily low error probability?", { channel: "specified probabilistic channel", noise: "specified", reliability: "vanishing error" }, ["<=", "B log₂(1 + P/N)", "UPPER_BOUND", "Claude Shannon", 1948, "A Mathematical Theory of Communication"], "https://onlinelibrary.wiley.com/doi/pdf/10.1002/j.1538-7305.1948.tb00917.x"),
  readyDraft("LR-DRAFT-NYQUIST", "Nyquist sampling limit", "Signal Processing", "MAXIMIZE", "The Nyquist–Shannon sampling theorem sets the minimum rate at which a continuous signal must be sampled to be perfectly reconstructed — sample too slowly and distinct frequencies become indistinguishable (aliasing).", "What is the minimum sampling rate needed to perfectly reconstruct a signal band-limited to bandwidth B?", { signal: "band-limited", bandwidth: "B", reconstruction: "ideal" }, [">=", "2B samples/second", "LOWER_BOUND", "Harry Nyquist", 1928, "Certain Topics in Telegraph Transmission Theory"], "https://doi.org/10.1109/T-AIEE.1928.5055024"),
  readyDraft("LR-DRAFT-HOLEVO", "Holevo accessible-information bound", "Quantum Information", "MAXIMIZE", "No measurement strategy, however clever, can extract more classical (readable) information out of a quantum ensemble than its Holevo quantity χ — a hard ceiling on quantum communication capacity that sits below the naive per-qubit rate one might expect.", "What is the maximum amount of classical information χ that any measurement can extract from a quantum ensemble?", { ensemble: "quantum ensemble", measurement: "arbitrary POVM" }, ["<=", "χ(ensemble)", "UPPER_BOUND", "Alexander Holevo", 1973, "Bounds for the Quantity of Information Transmitted by a Quantum Communication Channel"], "https://www.mathnet.ru/eng/ppi/v9/i3/p3"),
  readyDraft("LR-DRAFT-NO-CLONING", "Perfect cloning of an arbitrary unknown quantum state", "Quantum Information", "MAXIMIZE", "The no-cloning theorem is one of quantum mechanics' foundational impossibility results: unlike classical information, an arbitrary unknown quantum state cannot be copied — a direct consequence of the linearity of quantum evolution, and the basis for quantum cryptography's security guarantees.", "Does there exist a physical process that perfectly copies an arbitrary unknown quantum state onto a second system?", { state: "arbitrary unknown quantum state", clone: "perfect universal" }, ["=", "impossible", "COUNTEREXAMPLE", "Wootters and Zurek", 1982, "A single quantum cannot be cloned"], "https://www.nature.com/articles/299802a0", "MATHEMATICAL_PROOF"),
  readyDraft("LR-DRAFT-RAMSEY33", "Ramsey number R(3,3)", "Mathematics / Combinatorics", "MINIMIZE", "Ramsey's theorem guarantees that large enough structures always contain order: however you two-color the edges of a large enough complete graph, a monochromatic triangle becomes unavoidable. R(3,3) is the smallest such threshold.", "What is the least n such that every two-coloring of the edges of the complete graph K_n contains a monochromatic triangle?", { graph: "complete graph K_n", colors: "2" }, ["=", "6", "EXACT_VALUE", "Frank Ramsey", 1930, "On a Problem of Formal Logic"], "https://encyclopediaofmath.org/wiki/Ramsey_number", "MATHEMATICAL_PROOF"),
  readyDraft("LR-DRAFT-KISSING4", "Kissing number in four dimensions", "Mathematics / Geometry", "MAXIMIZE", "The kissing number problem asks how many equal, non-overlapping spheres can simultaneously touch a central sphere of the same size — a question that gets dramatically harder as dimension increases, and is only exactly solved in a handful of dimensions.", "What is the maximum number of non-overlapping unit spheres that can simultaneously touch a central unit sphere in four-dimensional Euclidean space?", { dimension: "4", objects: "equal Euclidean spheres" }, ["=", "24", "EXACT_VALUE", "Oleg Musin", 2008, "The kissing number in four dimensions"], "https://geodesic.mathdoc.fr/articles/10.4007/annals.2008.168.1/", "MATHEMATICAL_PROOF"),
  readyDraft("LR-DRAFT-E8", "Optimal sphere packing in eight dimensions", "Mathematics / Geometry", "MAXIMIZE", "The sphere packing problem asks what fraction of space can be filled by non-overlapping equal spheres. In eight dimensions, the extraordinarily symmetric E8 lattice achieves the provably optimal arrangement — a landmark 2016 result.", "What is the maximum density achievable by any packing of non-overlapping equal spheres in eight-dimensional Euclidean space?", { dimension: "8", packing: "equal spheres" }, ["=", "E8 packing optimum", "EXACT_VALUE", "Maryna Viazovska", 2017, "The sphere packing problem in dimension 8"], "https://annals.math.princeton.edu/2017/185-3/p07", "MATHEMATICAL_PROOF"),
  readyDraft("LR-DRAFT-TSP", "Metric TSP approximation frontier", "Algorithms / Approximation", "MINIMIZE", "The traveling salesman problem — finding the shortest route visiting every city once — is NP-hard to solve exactly, so research focuses on how close a fast algorithm can guarantee to get to the true optimum for realistic (metric) instances.", "What is the best approximation ratio achievable in polynomial time for metric traveling salesman, assuming P ≠ NP?", { problem: "metric TSP", assumption: "P ≠ NP for hardness claim" }, ["<=", "3/2 − ε", "UPPER_BOUND", "Karlin, Klein, Oveis Gharan", 2022, "A (slightly) improved approximation algorithm for metric TSP"], "https://pubsonline.informs.org/doi/10.1287/opre.2022.2338", "COMPUTATIONAL_PROOF"),
  (() => { const packet = readyDraft("LR-DRAFT-OMEGA", "Matrix-multiplication exponent", "Algorithms / Complexity", "MINIMIZE", "Matrix multiplication underlies everything from computer graphics to machine learning. The naive algorithm takes O(n³) operations for n×n matrices, but faster algorithms exist — the matrix multiplication exponent ω tracks the best asymptotic speed anyone has proven achievable.", "The exponent ω is the infimum such that n×n matrix multiplication uses O(n^ω) arithmetic operations.", { model: "arithmetic complexity", matrices: "n×n" }, [">=", "2", "LOWER_BOUND", "Williams, Xu, Xu, Zhou", 2025, "New bounds for matrix multiplication"], "https://epubs.siam.org/doi/pdf/10.1137/1.9781611978322.63", "COMPUTATIONAL_PROOF"); packet.claims.push({ ...packet.claims[0], id: "CLM-LR-DRAFT-OMEGA-2", relation: "<", value: { kind: "text", value: "2.371339" }, claimType: "UPPER_BOUND", methodSummary: "Best published upper bound on the matrix-multiplication exponent." }); return packet; })(),
  readyDraft("LR-DRAFT-C", "Speed of light in vacuum", "Physics / Fundamental Constants", "MAXIMIZE", "The speed of light in vacuum is one of the few physical constants whose value is exact by definition rather than measurement — the 1983 SI redefinition of the metre fixed it precisely, making it the ultimate speed limit for information and matter in relativity.", "What is the SI-defined value of c, the speed of light in vacuum?", { system: "SI", medium: "vacuum" }, ["=", "299792458 m/s", "EXACT_VALUE", "BIPM / SI", 1983, "SI definition of the metre"], "https://physics.nist.gov/cuu/Constants/Value/c.html", "FORMAL_PROOF"),
  readyDraft("LR-DRAFT-GENOME", "Smallest demonstrated autonomously growing bacterial cell", "Biology / Synthetic Biology", "MINIMIZE", "How few genes does a living cell need to independently grow and divide? The JCVI-syn3.0 synthetic bacterium demonstrates the smallest genome shown to support autonomous life in a laboratory setting — not a claim about the theoretical minimum for life itself.", "What is the smallest genome demonstrated to support a viable, independently growing bacterial cell?", { organism: "JCVI-syn3.0", metric: "protein-coding and essential genes", scope: "demonstrated cell, not minimum for life" }, ["<=", "473 genes / 531560 bp", "CONSTRUCTION", "Hutchison et al.", 2016, "Design and synthesis of a minimal bacterial genome"], "https://jcvi.com/media-center/first-minimal-synthetic-bacterial-cell-designed-and-constructed-scientists-venter", "CONSTRUCTION"),
  readyDraft("LR-DRAFT-C3", "C3 photosynthetic efficiency", "Biology / Photosynthesis", "MAXIMIZE", "Photosynthesis converts sunlight into chemical energy, but real-world efficiency falls far short of the theoretical maximum due to biochemical and physical losses. This record cites the observed efficiency ceiling for C3 plants — the majority of crop species — under a specific modeled canopy scenario.", "What is the observed canopy-level photosynthetic efficiency for C3 plants under the Zhu–Long–Ort frozen-conditions model?", { pathway: "C3", conditions: "frozen Zhu–Long–Ort model" }, ["=", "4.6%", "EXACT_VALUE", "Zhu, Long, Ort", 2010, "Improving photosynthetic efficiency for greater yield"], "https://pubmed.ncbi.nlm.nih.gov/18374559/", "OBSERVATION"),
  readyDraft("LR-DRAFT-HAYFLICK", "Historical Hayflick fibroblast record", "Biology / Cell Aging", "MAXIMIZE", "Normal human cells don't divide forever — the Hayflick limit is the historical observation that established cellular senescence as a real biological phenomenon, not the discovery of a single universal number.", "How many population doublings were observed before senescence in Hayflick and Moorhead's studied human diploid fibroblast strains?", { cell: "human diploid fibroblast strains", metric: "subcultivations", scope: "historical observation" }, ["=", "about 50 subcultivations", "CONSTRUCTION", "Hayflick and Moorhead", 1961, "The serial cultivation of human diploid cell strains"], "https://pubmed.ncbi.nlm.nih.gov/13905658/", "OBSERVATION"),
  readyDraft("LR-DRAFT-DNA", "DNA information density", "Data Storage / Molecular", "MAXIMIZE", "DNA can in principle store far more information per gram than any other known medium. This tracks two genuinely different figures that should never be conflated: the theoretical raw nucleotide encoding limit, and the density actually demonstrated by real error-corrected schemes like DNA Fountain — which are orders of magnitude apart.", "What is the theoretical raw information density achievable by DNA-based storage, versus the density actually demonstrated by a real error-corrected encoding scheme?", { medium: "DNA", metrics: "raw theoretical versus demonstrated coded density" }, ["<=", "455 EB/g theoretical; 215 PB/g demonstrated", "UPPER_BOUND", "Erlich and Zielinski", 2017, "DNA Fountain enables a robust and efficient storage architecture"], "https://www.science.org/doi/10.1126/science.aaj2038"),
  readyDraft("LR-DRAFT-GRAPHENE", "Graphene intrinsic strength", "Materials Science", "MAXIMIZE", "Graphene is the strongest material ever measured. This record cites the specific tensile strength observed for defect-free monolayer graphene under controlled nanoindentation testing — a scoped experimental result, not a claim about bulk graphene sheets or composites.", "What tensile strength was measured for defect-free monolayer graphene under controlled nanoindentation testing?", { material: "graphene", metric: "tensile strength", scope: "cited experiment" }, ["=", "130 GPa", "EXACT_VALUE", "Lee et al.", 2008, "Measurement of the elastic properties and intrinsic strength of monolayer graphene"], "https://pubmed.ncbi.nlm.nih.gov/18635798/", "OBSERVATION"),
  readyDraft("LR-DRAFT-OPTICAL", "Optical-fiber capacity-distance demonstration", "Networking / Optical", "MAXIMIZE", "Optical fiber capacity-distance demonstrations track the practical frontier of how much data can be transmitted how far through fiber — a moving target as multi-core fiber and better amplification push the record higher each year.", "What is the highest verified data rate demonstrated over the longest distance in a single optical fiber transmission experiment?", { fiber: "19-core standard cladding", distance: "1808 km", metric: "capacity-distance" }, ["=", "1.02 Pb/s over 1808 km", "CONSTRUCTION", "NICT", 2025, "Ultra-high capacity optical fiber transmission"], "https://www.nict.go.jp/en/press/2025/05/29-1.html", "OBSERVATION"),
  readyDraft("LR-DRAFT-COVERING", "Thinnest covering of the plane by congruent circles", "Mathematics / Geometry", "MINIMIZE", "Covering the plane with congruent circles and leaving no gaps forces the circles to overlap. The thinnest such covering — the arrangement with the least overlap, achieved by centering circles on a hexagonal lattice — has density 2π/√27 ≈ 1.209, meaning the circles' total area exceeds the plane's area by about 21%.", "What is the minimum-density arrangement of congruent circles that covers the entire Euclidean plane with no gaps?", { objects: "congruent circles", domain: "Euclidean plane" }, ["=", "2π/√27", "EXACT_VALUE", "László Fejes Tóth", 1940, "Regular circle coverings"], "https://www.jstor.org/stable/i340747", "MATHEMATICAL_PROOF"),
  readyDraft("LR-DRAFT-NEUTRON", "Rhoades–Ruffini neutron-star mass bound", "Astrophysics", "MAXIMIZE", "Beyond a certain mass, a neutron star's own gravity overwhelms the quantum pressure holding it up, and it collapses into a black hole. The exact maximum mass depends on the poorly-constrained neutron-star equation of state; this record cites an early rigorous bound assuming causality.", "Under the causal equation-of-state assumption, what is the maximum possible mass of a stable neutron star?", { object: "neutron star", assumptions: "causal EOS and stated model" }, ["<=", "3.2 M☉", "UPPER_BOUND", "Rhoades and Ruffini", 1974, "Maximum mass of a neutron star"], "https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.32.324"),
  readyDraft("LR-DRAFT-CHANDRA", "Historical Chandrasekhar white-dwarf mass calculation", "Astrophysics", "MAXIMIZE", "Before neutron stars were even confirmed to exist, Chandrasekhar showed that white dwarf stars have a maximum possible mass — beyond it, electron degeneracy pressure can no longer support the star against gravitational collapse. His original 1931 calculation used an idealized, composition-independent model.", "Under Chandrasekhar's 1931 idealized model, what is the maximum mass a white dwarf star can have before gravitational collapse?", { object: "ideal white dwarf", scope: "Chandrasekhar 1931 historical model" }, ["=", "0.91 M☉", "EXACT_VALUE", "Subrahmanyan Chandrasekhar", 1931, "The maximum mass of ideal white dwarfs"], "https://repository.ias.ac.in/70320/", "THEORETICAL_DERIVATION"),
];

export const researchQueueCandidates = [
  "Bremermann limit", "maximum enzyme catalytic efficiency", "highest superconducting Tc", "maximum hardness", "maximum thermal conductivity", "highest rechargeable battery Wh/kg", "lithium-air theoretical energy", "shortest transistor gate", "maximum transistor density", "maximum storage density", "3D kissing number", "sorting network S(11)", "original Oppenheimer–Volkoff model",
].map((title, index) => ({ id: `RQ-${String(index + 1).padStart(3, "0")}`, title, ingestionReadiness: "RESEARCH_QUEUE" as const, publicationState: "DRAFT" as const, registryReviewStatus: "UNREVIEWED" as const, independentRegistryReviews: 0 }));

// AI scaling extensions. These remain draft-only because model family, data,
// hardware, retrieval corpus, and evaluation protocol materially affect them.
export const aiChinchillaScalingResearchPacket = readyDraft("LR-DRAFT-CHINCHILLA", "Compute-optimal language-model scaling", "AI / Scaling Laws", "MINIMIZE", "Training a fixed compute budget into an ever-larger model isn't always the best use of that compute — the Chinchilla study found that model size and training-token count should scale together, not model size alone, to reach the best loss for a given budget.", "Under a fixed compute budget, what is the jointly compute-optimal model size and training-token count for a specified autoregressive language-model family and data regime?", { objective: "next-token loss", compute: "fixed training FLOPs", variables: "parameter count and training tokens", regime: "specified model/data family" }, ["=", "N and D scale approximately together under the specified compute budget", "ASYMPTOTIC_BOUND", "Hoffmann et al.", 2022, "Training Compute-Optimal Large Language Models"], "https://arxiv.org/abs/2203.15556");
export const aiAttentionMemoryResearchPacket = readyDraft("LR-DRAFT-ATTENTION", "Transformer attention memory and IO scaling", "AI / Systems", "MINIMIZE", "Exact self-attention naively materializes a score matrix that grows quadratically with sequence length, which is what limits how long a context transformer models can practically handle. IO-aware kernels like FlashAttention avoid materializing that full matrix, trading a fixed compute cost for dramatically less memory traffic.", "For sequence length n and hidden width d, what is the peak memory and data movement for exact attention, distinguishing quadratic score-matrix materialization from IO-aware kernels such as FlashAttention?", { operation: "exact self-attention", sequenceLength: "n", hiddenWidth: "d", implementation: "materialized or IO-aware kernel" }, ["<=", "O(n²) score interactions; reduced intermediate memory with IO-aware tiling", "ASYMPTOTIC_BOUND", "Dao et al.", 2022, "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness"], "https://arxiv.org/abs/2205.14135", "COMPUTATIONAL_PROOF");
export const aiRetrievalFloorResearchPacket = readyDraft("LR-DRAFT-RETRIEVAL", "Context-window retrieval reliability floor", "AI / Information Retrieval", "MAXIMIZE", "Long-context language models don't retrieve information from anywhere in their context window with equal reliability — accuracy varies with where the relevant fact sits, how many distractors surround it, and which model and prompt are used, so no single model-independent floor can be asserted.", "For a fixed context length, distractor count, corpus, model, and prompt, what retrieval accuracy is actually achieved under a specified evaluation protocol?", { task: "long-context retrieval", metric: "specified retrieval accuracy", corpus: "fixed benchmark corpus", context: "fixed token window and distractors" }, [">=", "protocol-specific measured retrieval accuracy", "COMPUTATIONAL_BOUND", "Long-context evaluation literature", 2024, "Empirical retrieval frontier under a fixed evaluation protocol"], "https://arxiv.org/abs/2307.03172", "OBSERVATION");

export const aiScalingResearchPackets: ResearchPacket[] = [aiChinchillaScalingResearchPacket, aiAttentionMemoryResearchPacket, aiRetrievalFloorResearchPacket];
