import type { ResearchPacket } from "./research-packet";
import type { Claim, Evidence, SpecificationVersion } from "./types";

const spec: SpecificationVersion = {
  id: "SP-LR-000127-V1", limitId: "LR-000127", version: 1,
  formalStatement: "ex(n, K₃) is the maximum number of edges in a simple n-vertex graph containing no triangle.",
  constraints: { graph: "simple", vertices: "n", forbiddenSubgraph: "K₃" }, asymptotic: false, probabilistic: false,
};
const evidence: Evidence = { id: "EVD-LR127-1", type: "MATHEMATICAL_PROOF", method: "MANTEL_THEOREM", verificationLevel: "SOURCE_CONFIRMED", label: "Mantel's theorem and balanced complete bipartite construction", sourceUrl: "https://ocw.mit.edu/courses/18-225-graph-theory-and-additive-combinatorics-fall-2023/mit18_225_f23_lec_full.pdf" };
const claim = (id: string, relation: Claim["relation"], type: Claim["claimType"], value: string, author: string, year: number): Claim => ({ id, specificationVersionId: spec.id, relation, value: { kind: "text", value }, claimType: type, status: "ACCEPTED", epistemicStatus: "SOURCE_CONFIRMED", scientificStatus: "ACCEPTED", registryReviewStatus: "UNREVIEWED", evidenceIds: [evidence.id], author, year, source: evidence.label });

export const mantelResearchPacket: ResearchPacket = {
  limit: { id: "LR-000127", title: "Maximum edges in a triangle-free graph", category: "Graph Theory", status: "PROVEN", direction: "MAXIMIZE", summary: "The maximum number of edges in a simple n-vertex graph containing no triangle." },
  specification: spec,
  claims: [
    claim("CLM-LR127-LOWER", ">=", "CONSTRUCTION", "floor(n²/4)", "Willem Mantel", 1907),
    claim("CLM-LR127-UPPER", "<=", "UPPER_BOUND", "floor(n²/4)", "Willem Mantel", 1907),
  ],
  evidence: [evidence], registryReviewStatus: "UNREVIEWED",
};


const packetSpec = (id: string, limitId: string, formalStatement: string, constraints: Record<string, string>, asymptotic = true): SpecificationVersion => ({ id, limitId, version: 1, formalStatement, constraints, asymptotic, probabilistic: false });
const textClaim = (id: string, specId: string, relation: Claim["relation"], value: string, claimType: Claim["claimType"], author: string, year: number, source: string, evidenceId: string, scientificStatus: Claim["scientificStatus"] = "ACCEPTED"): Claim => ({ id, specificationVersionId: specId, relation, value: { kind: "text", value }, claimType, status: "ACCEPTED", epistemicStatus: scientificStatus === "UNCERTAIN" ? "LITERATURE_ASSERTED" : "SOURCE_CONFIRMED", scientificStatus, registryReviewStatus: "UNREVIEWED", evidenceIds: [evidenceId], author, year, source });

const cernySpec = packetSpec("SP-LR-000114-V1", "LR-000114", "C(n) is the maximum shortest reset-word length over synchronizing complete deterministic automata with n states.", { automaton: "complete DFA", states: "n", quantity: "reset threshold" }, true);
const cernyEvidence: Evidence = { id: "EVD-LR114-1", type: "MATHEMATICAL_PROOF", method: "AUTOMATON_CONSTRUCTION", verificationLevel: "SOURCE_CONFIRMED", label: "Černý automata attain (n−1)²; general quadratic upper bound remains conjectural", sourceUrl: "https://doi.org/10.1145/3798283" };
export const cernyResearchPacket: ResearchPacket = { limit: { id: "LR-000114", title: "Synchronizing automaton reset threshold", category: "Automata", status: "OPEN", direction: "MINIMIZE", summary: "The maximum shortest reset-word length among synchronizing n-state finite automata." }, specification: cernySpec, claims: [ textClaim("CLM-LR114-LOWER", cernySpec.id, ">=", "(n−1)²", "LOWER_BOUND", "Jan Černý", 1964, "Černý automata construction", cernyEvidence.id), textClaim("CLM-LR114-CONJECTURE", cernySpec.id, "<=", "(n−1)²", "UPPER_BOUND", "Černý conjecture", 1969, "Černý conjecture", cernyEvidence.id, "UNCERTAIN"), textClaim("CLM-LR114-UPPER-CUBIC", cernySpec.id, "<=", "0.1654n³ + O(n²)", "UPPER_BOUND", "Yaroslav Shitov", 2022, "Best known general cubic upper bound", cernyEvidence.id) ], evidence: [cernyEvidence], registryReviewStatus: "UNREVIEWED" };

const capSpec = packetSpec("SP-LR-000098-V1", "LR-000098", "A cap set is a subset of F₃ⁿ with no non-trivial solution to x+y+z=0.", { domain: "F₃ⁿ", forbiddenConfiguration: "non-trivial 3-term arithmetic progression" });
const capEvidence: Evidence = { id: "EVD-LR098-1", type: "MATHEMATICAL_PROOF", method: "POLYNOMIAL_METHOD", verificationLevel: "SOURCE_CONFIRMED", label: "Polynomial-method upper bound for cap sets", sourceUrl: "https://doi.org/10.1016/j.jcta.2019.06.001" };
const capLowerEvidence: Evidence = { id: "EVD-LR098-2", type: "CONSTRUCTION", method: "EXPLICIT_CONSTRUCTION", verificationLevel: "SOURCE_CONFIRMED", label: "Improved exponential lower bound for cap sets", sourceUrl: "https://arxiv.org/abs/2209.10045" };
export const capSetResearchPacket: ResearchPacket = { limit: { id: "LR-000098", title: "Largest cap set in F₃ⁿ", category: "Combinatorics", status: "OPEN", direction: "MAXIMIZE", summary: "The largest subset of F₃ⁿ containing no non-trivial three-term arithmetic progression." }, specification: capSpec, claims: [ textClaim("CLM-LR098-LOWER", capSpec.id, ">=", "2.218ⁿ", "LOWER_BOUND", "Fred Tyrrell", 2022, "New Lower Bounds for Cap Sets", capLowerEvidence.id), textClaim("CLM-LR098-UPPER", capSpec.id, "<=", "O(2.756ⁿ)", "UPPER_BOUND", "Jordan Ellenberg and Dion Gijswijt", 2016, "Bounds on sizes of generalized caps", capEvidence.id) ], evidence: [capLowerEvidence, capEvidence], registryReviewStatus: "UNREVIEWED" };

const bchSpec = packetSpec("SP-LR-000086-V1", "LR-000086", "d(C) is the true minimum Hamming distance of a primitive narrow-sense binary BCH code of length 2ᵐ−1 and designed distance δ.", { field: "F₂", family: "primitive narrow-sense BCH", length: "2ᵐ−1", parameter: "m and δ" }, false);
const bchEvidence: Evidence = { id: "EVD-LR086-1", type: "MATHEMATICAL_PROOF", method: "BCH_BOUND", verificationLevel: "SOURCE_CONFIRMED", label: "BCH designed-distance guarantee", sourceUrl: "https://www.aimsciences.org/article/doi/10.3934/amc.2024047?viewType=HTML" };
export const bchResearchPacket: ResearchPacket = { limit: { id: "LR-000086", title: "Minimum distance of primitive binary BCH codes", category: "Coding theory", status: "OPEN", direction: "MAXIMIZE", summary: "The true minimum Hamming distance of a primitive narrow-sense binary BCH family of length 2ᵐ − 1." }, specification: bchSpec, claims: [ textClaim("CLM-LR086-DESIGNED", bchSpec.id, ">=", "δ", "LOWER_BOUND", "BCH bound", 1959, "The designed distance is a lower bound on true minimum distance", bchEvidence.id) ], evidence: [bchEvidence], registryReviewStatus: "UNREVIEWED" };

export const additionalResearchPackets: ResearchPacket[] = [cernyResearchPacket, capSetResearchPacket, bchResearchPacket];

const sortingSpec = (id: string, limitId: string, inputs: number): SpecificationVersion => ({ id, limitId, version: 1, formalStatement: `S(${inputs}) is the minimum number of comparators in a fixed network that sorts every ${inputs}-input sequence.`, constraints: { inputs: String(inputs), inputDomain: "totally ordered values", verificationDomain: `${2 ** inputs} binary inputs`, network: "fixed/data-oblivious" }, asymptotic: false, probabilistic: false });
const sortingEvidence = (id: string, label: string): Evidence => ({ id, type: "COMPUTATIONAL_PROOF", method: "SAT_SYMMETRY_REDUCTION", verificationLevel: "SOURCE_CONFIRMED", label, sourceUrl: "https://arxiv.org/abs/1405.5754" });
const sortingPacket = (limitId: string, inputs: number, lower: number, upper: number, status: "OPEN" | "PROVEN", lowerSource: string, upperSource: string): ResearchPacket => {
  const specification = sortingSpec(`SP-${limitId}-V1`, limitId, inputs);
  const lowerEvidence = sortingEvidence(`EVD-${limitId}-LOWER`, `Computer-assisted lower-bound verification for S(${inputs})`);
  const upperEvidence: Evidence = { id: `EVD-${limitId}-UPPER`, type: "CONSTRUCTION", method: "COMPARATOR_NETWORK", verificationLevel: "SOURCE_CONFIRMED", label: `Known ${upper}-comparator sorting network for ${inputs} inputs`, sourceUrl: "https://imada.sdu.dk/~petersk/sn/" };
  const makeClaim = (id: string, relation: Claim["relation"], value: number, type: Claim["claimType"], source: string, evidenceId: string): Claim => ({ id, specificationVersionId: specification.id, relation, value: { kind: "integer", value: BigInt(value) }, claimType: type, status: "ACCEPTED", epistemicStatus: "SOURCE_CONFIRMED", scientificStatus: "ACCEPTED", registryReviewStatus: "UNREVIEWED", evidenceIds: [evidenceId], author: "Codish, Cruz-Filipe, Frank, Schneider-Kamp", year: 2014, source });
  return { limit: { id: limitId, title: `Minimum number of comparators for a ${inputs}-input sorting network`, category: "Algorithms / Sorting Networks", status, direction: "MINIMIZE", summary: `The minimum number of fixed compare-exchange operations needed to sort ${inputs} inputs.` }, specification, claims: [makeClaim(`CLM-${limitId}-LOWER`, ">=", lower, "LOWER_BOUND", lowerSource, lowerEvidence.id), makeClaim(`CLM-${limitId}-UPPER`, "<=", upper, "UPPER_BOUND", upperSource, upperEvidence.id)], evidence: [lowerEvidence, upperEvidence], registryReviewStatus: "UNREVIEWED" };
};

export const sortingNetworkResearchPackets: ResearchPacket[] = [
  sortingPacket("LR-SN-009", 9, 25, 25, "PROVEN", "Twenty-Five Comparators is Optimal when Sorting Nine Inputs", "Floyd's 25-comparator construction"),
  sortingPacket("LR-SN-010", 10, 29, 29, "PROVEN", "Twenty-Five Comparators is Optimal when Sorting Nine Inputs (and Twenty-Nine for Ten)", "Waksman's 29-comparator construction"),
  sortingPacket("LR-SN-011", 11, 33, 35, "OPEN", "Maintained sorting-network lower-bound table", "Maintained sorting-network upper-bound table"),
  sortingPacket("LR-SN-012", 12, 37, 39, "OPEN", "Maintained sorting-network lower-bound table", "Maintained sorting-network upper-bound table"),
];

const landauerSpec: SpecificationVersion = { id: "SP-LR-LANDAUER-V1", limitId: "LR-LANDAUER", version: 1, formalStatement: "The minimum work required to irreversibly erase one bit at thermodynamic temperature T is k_B T ln(2).", constraints: { system: "physical information-bearing system", operation: "logically irreversible bit erasure", temperature: "T kelvin", assumptions: "thermal equilibrium" }, asymptotic: false, probabilistic: false };
const landauerEvidence: Evidence = { id: "EVD-LR-LANDAUER-1", type: "MATHEMATICAL_PROOF", method: "STATISTICAL_MECHANICS", verificationLevel: "SOURCE_CONFIRMED", label: "Landauer principle", sourceUrl: "https://doi.org/10.1103/PhysRev.122.1152" };
export const landauerResearchPacket: ResearchPacket = { limit: { id: "LR-LANDAUER", title: "Minimum energy to erase one bit", category: "Physics / Information", status: "PROVEN", direction: "MINIMIZE", limitKind: "THEORETICAL_BOUND", canonicalStatus: "EXACT", summary: "The minimum thermodynamic work required for logically irreversible erasure of one bit at temperature T." }, specification: landauerSpec, claims: [{ id: "CLM-LR-LANDAUER-BOUND", relation: ">=", value: { kind: "text", value: "k_B T ln(2)" }, claimType: "LOWER_BOUND", status: "ACCEPTED", epistemicStatus: "PROVEN", scientificStatus: "ACCEPTED", registryReviewStatus: "UNREVIEWED", evidenceBasis: ["THEORETICAL_DERIVATION"], specificationVersionId: landauerSpec.id, evidenceIds: [landauerEvidence.id], author: "Rolf Landauer", year: 1961, source: "Irreversibility and Heat Generation in the Computing Process" }], evidence: [landauerEvidence], registryReviewStatus: "UNREVIEWED" };

const genomeSpec: SpecificationVersion = { id: "SP-LR-GENOME-V1", limitId: "LR-GENOME", version: 1, formalStatement: "The genome size of a viable, independently growing bacterial cell maintained in pure culture under the stated laboratory conditions.", constraints: { organism: "JCVI-syn3.0", environment: "pure culture", viability: "independently growing", metric: "genes and base pairs" }, asymptotic: false, probabilistic: false };
const genomeEvidence: Evidence = { id: "EVD-LR-GENOME-1", type: "CONSTRUCTION", method: "SYNTHETIC_GENOME_REDUCTION", verificationLevel: "SOURCE_CONFIRMED", label: "JCVI-syn3.0 minimal bacterial cell", sourceUrl: "https://doi.org/10.1038/nature16449" };
export const minimalGenomeResearchPacket: ResearchPacket = { limit: { id: "LR-GENOME", title: "Smallest demonstrated independently growing bacterial genome", category: "Biology / Synthetic Biology", status: "OPEN", direction: "MINIMIZE", limitKind: "OBSERVED_RECORD", summary: "The smallest genome demonstrated in a viable, independently growing bacterial cell under a defined laboratory specification." }, specification: genomeSpec, claims: [{ id: "CLM-LR-GENOME-473", relation: "<=", value: { kind: "integer", value: 473n }, claimType: "CONSTRUCTION", status: "ACCEPTED", epistemicStatus: "SOURCE_CONFIRMED", scientificStatus: "ACCEPTED", registryReviewStatus: "UNREVIEWED", evidenceBasis: ["CONSTRUCTION"], specificationVersionId: genomeSpec.id, evidenceIds: [genomeEvidence.id], author: "Hutchison et al.", year: 2016, source: "Design and synthesis of a minimal bacterial genome" }], evidence: [genomeEvidence], registryReviewStatus: "UNREVIEWED" };

export const crossDomainResearchPackets: ResearchPacket[] = [landauerResearchPacket, minimalGenomeResearchPacket];


const speedSpec: SpecificationVersion = { id: "SP-LR-SPEED-V1", limitId: "LR-SPEED", version: 1, formalStatement: "The vacuum speed of light c is exactly 299792458 metres per second in the SI system.", constraints: { medium: "vacuum", unitSystem: "SI" }, asymptotic: false, probabilistic: false };
const speedEvidence: Evidence = { id: "EVD-LR-SPEED-1", type: "MATHEMATICAL_PROOF", method: "SI_DEFINITION_AND_RELATIVITY", verificationLevel: "SOURCE_CONFIRMED", label: "SI defining value for the speed of light in vacuum", sourceUrl: "https://www.nist.gov/pml/special-publication-330/sp-330-appendix-1" };
export const speedOfLightResearchPacket: ResearchPacket = { limit: { id: "LR-SPEED", title: "Speed of light in vacuum", category: "Physics / Fundamental Constants", status: "PROVEN", direction: "MAXIMIZE", limitKind: "FUNDAMENTAL_CONSTANT", canonicalStatus: "EXACT", summary: "The exact SI-defined speed of electromagnetic radiation in vacuum." }, specification: speedSpec, claims: [{ id: "CLM-LR-SPEED-EXACT", relation: "=", value: { kind: "integer", value: 299792458n }, claimType: "EXACT_VALUE", status: "ACCEPTED", epistemicStatus: "PROVEN", scientificStatus: "ACCEPTED", registryReviewStatus: "UNREVIEWED", evidenceBasis: ["THEORETICAL_DERIVATION"], specificationVersionId: speedSpec.id, evidenceIds: [speedEvidence.id], author: "International System of Units", year: 1983, source: "SI definition of c" }], evidence: [speedEvidence], registryReviewStatus: "UNREVIEWED" };

const genomeSizeSpec: SpecificationVersion = { ...genomeSpec, id: "SP-LR-GENOME-SIZE-V1", limitId: "LR-GENOME-SIZE", constraints: { ...genomeSpec.constraints, metric: "base pairs" } };
export const minimalGenomeSizeResearchPacket: ResearchPacket = { ...minimalGenomeResearchPacket, limit: { ...minimalGenomeResearchPacket.limit, id: "LR-GENOME-SIZE", title: "Smallest demonstrated bacterial genome by base-pair count" }, specification: genomeSizeSpec, claims: [{ ...minimalGenomeResearchPacket.claims[0], id: "CLM-LR-GENOME-531560", specificationVersionId: genomeSizeSpec.id, value: { kind: "integer", value: 531560n }, evidenceIds: ["EVD-LR-GENOME-1"] }] };

export const nextCrossDomainResearchPackets: ResearchPacket[] = [landauerResearchPacket, speedOfLightResearchPacket, minimalGenomeResearchPacket, minimalGenomeSizeResearchPacket];


const exactTextClaim = (id: string, specId: string, relation: Claim["relation"], value: string, claimType: Claim["claimType"], author: string, year: number, source: string, evidenceId: string, basis: NonNullable<Claim["evidenceBasis"]>[number]): Claim => ({ id, specificationVersionId: specId, relation, value: { kind: "text", value }, claimType, status: "ACCEPTED", epistemicStatus: "PROVEN", scientificStatus: "ACCEPTED", registryReviewStatus: "UNREVIEWED", evidenceBasis: [basis], evidenceIds: [evidenceId], author, year, source });

const carnotSpec: SpecificationVersion = { id: "SP-LR-CARNOT-V1", limitId: "LR-CARNOT", version: 1, formalStatement: "The efficiency of a reversible heat engine operating between reservoirs at temperatures T_h and T_c is η = 1 − T_c/T_h.", constraints: { engine: "heat engine", process: "reversible", hotReservoir: "T_h", coldReservoir: "T_c", units: "kelvin" }, asymptotic: false, probabilistic: false };
const carnotEvidence: Evidence = { id: "EVD-LR-CARNOT-1", type: "MATHEMATICAL_PROOF", method: "REVERSIBLE_THERMODYNAMICS", verificationLevel: "SOURCE_CONFIRMED", label: "Carnot efficiency theorem", sourceUrl: "https://openstax.org/books/college-physics/pages/15-4-carnots-perfect-heat-engine-the-second-law-of-thermodynamics-restated" };
export const carnotResearchPacket: ResearchPacket = { limit: { id: "LR-CARNOT", title: "Maximum efficiency of a reversible heat engine", category: "Thermodynamics", status: "PROVEN", direction: "MAXIMIZE", limitKind: "THEORETICAL_BOUND", canonicalStatus: "EXACT", summary: "The maximum efficiency of a reversible heat engine between specified hot and cold reservoirs." }, specification: carnotSpec, claims: [exactTextClaim("CLM-LR-CARNOT", "SP-LR-CARNOT-V1", "<=", "1 − T_c/T_h", "UPPER_BOUND", "Sadi Carnot", 1824, "Carnot efficiency theorem", carnotEvidence.id, "THEORETICAL_DERIVATION")], evidence: [carnotEvidence], registryReviewStatus: "UNREVIEWED" };

const betzSpec: SpecificationVersion = { id: "SP-LR-BETZ-V1", limitId: "LR-BETZ", version: 1, formalStatement: "The power coefficient C_p of an ideal actuator-disk wind turbine in steady, uniform, incompressible flow is at most 16/27.", constraints: { device: "ideal actuator disk", flow: "steady uniform incompressible", metric: "power coefficient C_p" }, asymptotic: false, probabilistic: false };
const betzEvidence: Evidence = { id: "EVD-LR-BETZ-1", type: "MATHEMATICAL_PROOF", method: "ACTUATOR_DISK_MOMENTUM_THEORY", verificationLevel: "SOURCE_CONFIRMED", label: "Betz limit", sourceUrl: "https://www.energy.gov/cmei/systems/windexchange/small-wind-guidebook" };
export const betzResearchPacket: ResearchPacket = { limit: { id: "LR-BETZ", title: "Maximum wind-turbine power coefficient", category: "Energy / Wind", status: "PROVEN", direction: "MAXIMIZE", limitKind: "THEORETICAL_BOUND", canonicalStatus: "EXACT", summary: "The ideal actuator-disk limit on the fraction of wind power extractable by a turbine." }, specification: betzSpec, claims: [exactTextClaim("CLM-LR-BETZ", "SP-LR-BETZ-V1", "<=", "16/27", "UPPER_BOUND", "Albert Betz", 1919, "Betz limit", betzEvidence.id, "THEORETICAL_DERIVATION")], evidence: [betzEvidence], registryReviewStatus: "UNREVIEWED" };

const shannonSpec: SpecificationVersion = { id: "SP-LR-SHANNON-AWGN-V1", limitId: "LR-SHANNON-AWGN", version: 1, formalStatement: "The capacity of a band-limited additive white Gaussian noise channel is C = B log₂(1 + P/N).", constraints: { channel: "band-limited AWGN", bandwidth: "B", signalPower: "P", noisePower: "N", reliability: "arbitrarily low error with sufficiently long codes" }, asymptotic: true, probabilistic: true };
const shannonEvidence: Evidence = { id: "EVD-LR-SHANNON-1", type: "MATHEMATICAL_PROOF", method: "CODING_THEOREM_AND_CONVERSE", verificationLevel: "SOURCE_CONFIRMED", label: "Capacity of the band-limited Gaussian channel", sourceUrl: "https://onlinelibrary.wiley.com/doi/abs/10.1002/j.1538-7305.1966.tb04214.x" };
export const shannonAwgnResearchPacket: ResearchPacket = { limit: { id: "LR-SHANNON-AWGN", title: "Capacity of a band-limited AWGN channel", category: "Information Theory", status: "PROVEN", direction: "MAXIMIZE", limitKind: "THEORETICAL_BOUND", canonicalStatus: "EXACT", summary: "The maximum reliable communication rate for a specified additive white Gaussian noise channel." }, specification: shannonSpec, claims: [exactTextClaim("CLM-LR-SHANNON", "SP-LR-SHANNON-AWGN-V1", "<=", "B log₂(1 + P/N)", "UPPER_BOUND", "Claude Shannon", 1948, "Channel capacity theorem", shannonEvidence.id, "THEORETICAL_DERIVATION")], evidence: [shannonEvidence], registryReviewStatus: "UNREVIEWED" };

const cloningSpec: SpecificationVersion = { id: "SP-LR-NO-CLONING-V1", limitId: "LR-NO-CLONING", version: 1, formalStatement: "No physical quantum operation can produce a perfect copy of every arbitrary unknown input quantum state.", constraints: { input: "arbitrary unknown quantum state", output: "perfect identical copies", operation: "physical quantum operation" }, asymptotic: false, probabilistic: false };
const cloningEvidence: Evidence = { id: "EVD-LR-NO-CLONING-1", type: "MATHEMATICAL_PROOF", method: "LINEARITY_OF_QUANTUM_MECHANICS", verificationLevel: "SOURCE_CONFIRMED", label: "Universal quantum no-cloning theorem", sourceUrl: "https://doi.org/10.1038/299802A0" };
export const noCloningResearchPacket: ResearchPacket = { limit: { id: "LR-NO-CLONING", title: "Perfect cloning of an arbitrary unknown quantum state", category: "Quantum Information", status: "PROVEN", direction: "MAXIMIZE", limitKind: "IMPOSSIBILITY_RESULT", canonicalStatus: "EXACT", summary: "Perfect universal cloning of an arbitrary unknown quantum state is forbidden by quantum mechanics." }, specification: cloningSpec, claims: [exactTextClaim("CLM-LR-NO-CLONING", "SP-LR-NO-CLONING-V1", "=", "impossible", "COUNTEREXAMPLE", "W. K. Wootters and W. H. Zurek", 1982, "A single quantum cannot be cloned", cloningEvidence.id, "MATHEMATICAL_PROOF")], evidence: [cloningEvidence], registryReviewStatus: "UNREVIEWED" };

export const foundationalResearchPackets: ResearchPacket[] = [carnotResearchPacket, betzResearchPacket, shannonAwgnResearchPacket, noCloningResearchPacket];
