type Rel = "=" | "<=" | ">=";
type Status = "PROVEN" | "OPEN";
type Source = { title: string; url: string; date: string; venue: string; location: string; doi?: string };

export type ChemistryRecord = {
  registryNumber: string; slug: string; title: string; summary: string; subcategory: string;
  direction: "MINIMIZE" | "MAXIMIZE"; metricName: string; unit: string; formalStatement: string;
  constraints: Record<string, unknown>; status: Status; relation: Rel; formula: string;
  claimType: "EXACT_VALUE" | "LOWER_BOUND" | "UPPER_BOUND";
  epistemic: "PROVEN" | "SOURCE_CONFIRMED" | "EMPIRICALLY_SUPPORTED"; source: Source; evidenceBasis: string;
};

const slug = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
const source = (title: string, url: string, date: string, venue: string, location: string, doi?: string): Source => ({ title, url, date, venue, location, doi });
const si = source("The International System of Units (SI): Defining constants", "https://www.bipm.org/en/measurement-units/si-defining-constants", "2019-05-20", "BIPM", "Defining constants table");
const iupac = (title: string, url: string, location: string): Source => source(title, url, "2019-01-01", "IUPAC Gold Book", location);

export const chemistryRecords: ChemistryRecord[] = [
  { registryNumber: "LR-004100", slug: slug("Avogadro constant"), title: "Avogadro constant", summary: "The amount-of-substance scale contains exactly 6.02214076 × 10²³ specified elementary entities per mole.", subcategory: "Constants and units", direction: "MAXIMIZE", metricName: "entities per mole", unit: "mol⁻¹", formalStatement: "Fix the numerical value of the Avogadro constant in the SI definition of the mole.", constraints: { system: "SI", entity: "specified elementary entities", uncertainty: "exact", definition: "2019 SI revision" }, status: "PROVEN", relation: "=", formula: "N_A = 6.02214076 × 10²³ mol⁻¹", claimType: "EXACT_VALUE", epistemic: "PROVEN", source: si, evidenceBasis: "DEFINITIONAL_CONSTANT" },
  { registryNumber: "LR-004101", slug: slug("Faraday constant from exact SI constants"), title: "Faraday constant from exact SI constants", summary: "The charge carried by one mole of elementary charges is exactly determined by e and N_A in the revised SI.", subcategory: "Electrochemistry", direction: "MAXIMIZE", metricName: "charge per mole of electrons", unit: "C mol⁻¹", formalStatement: "Combine the exact elementary charge and Avogadro constant to obtain the molar elementary charge.", constraints: { system: "SI", species: "electron", relation: "F = N_A e", uncertainty: "exact" }, status: "PROVEN", relation: "=", formula: "F = 96485.33212 C mol⁻¹", claimType: "EXACT_VALUE", epistemic: "PROVEN", source: si, evidenceBasis: "DERIVED_FROM_EXACT_CONSTANTS" },
  { registryNumber: "LR-004102", slug: slug("Standard hydrogen electrode potential"), title: "Standard hydrogen electrode potential", summary: "The standard potential of the reference hydrogen electrode is fixed at zero by electrochemical convention.", subcategory: "Electrochemistry", direction: "MINIMIZE", metricName: "standard electrode potential", unit: "V", formalStatement: "Set the standard potential of the H⁺/H₂ reference electrode under standard-state conditions.", constraints: { electrode: "Pt | H₂(g) | H⁺(aq)", temperature: "specified measurement temperature", pressure: "standard pressure", activity: "unit hydrogen-ion activity", status: "reference convention" }, status: "PROVEN", relation: "=", formula: "E°(H⁺/H₂) = 0 V", claimType: "EXACT_VALUE", epistemic: "PROVEN", source: iupac("standard electrode potential", "https://goldbook.iupac.org/terms/view/S05912", "Reference-electrode convention"), evidenceBasis: "REFERENCE_CONVENTION" },
  { registryNumber: "LR-004103", slug: slug("Gibbs phase-rule degrees of freedom"), title: "Gibbs phase-rule degrees of freedom", summary: "The maximum independent intensive variables for a nonreacting equilibrium system are F = C − P + 2.", subcategory: "Thermodynamics", direction: "MAXIMIZE", metricName: "degrees of freedom", unit: "dimensionless", formalStatement: "Count independent intensive variables for C components and P coexisting phases at equilibrium.", constraints: { components: "C", phases: "P", reactions: "none", equilibrium: "heterogeneous thermodynamic equilibrium", variables: "intensive" }, status: "PROVEN", relation: "=", formula: "F = C − P + 2", claimType: "EXACT_VALUE", epistemic: "PROVEN", source: iupac("phase rule", "https://goldbook.iupac.org/terms/view/P04533", "Degrees-of-freedom definition"), evidenceBasis: "THERMODYNAMIC_DERIVATION" },
  { registryNumber: "LR-004104", slug: slug("Beer-Lambert absorbance relation"), title: "Beer–Lambert absorbance relation", summary: "For a homogeneous absorbing medium in the linear regime, absorbance scales with path length and concentration.", subcategory: "Spectroscopy", direction: "MAXIMIZE", metricName: "absorbance", unit: "dimensionless", formalStatement: "Relate monochromatic absorbance to molar attenuation coefficient, path length, and concentration.", constraints: { radiation: "monochromatic or narrow-band", sample: "homogeneous", regime: "linear, non-scattering", concentration: "dilute enough for proportionality" }, status: "PROVEN", relation: "=", formula: "A = ε l c", claimType: "EXACT_VALUE", epistemic: "PROVEN", source: iupac("Beer–Lambert law", "https://goldbook.iupac.org/terms/view/B00626", "Definition and scope"), evidenceBasis: "SPECTROSCOPIC_RELATION" },
  { registryNumber: "LR-004105", slug: slug("Nernst equilibrium-potential relation"), title: "Nernst equilibrium-potential relation", summary: "The equilibrium electrode potential depends logarithmically on the activities of the reacting species.", subcategory: "Electrochemistry", direction: "MAXIMIZE", metricName: "equilibrium electrode potential", unit: "V", formalStatement: "Compute equilibrium potential for a specified redox reaction from standard potential, temperature, charge number, and activities.", constraints: { state: "electrochemical equilibrium", activities: "dimensionless and referenced to standard state", temperature: "uniform T", reaction: "stoichiometry νᵢ specified" }, status: "PROVEN", relation: "=", formula: "E_eq = E° − (RT/zF) Σνᵢ ln(aᵢ)", claimType: "EXACT_VALUE", epistemic: "PROVEN", source: iupac("Nernst equation", "https://goldbook.iupac.org/terms/view/09068", "Equation and symbols"), evidenceBasis: "ELECTROCHEMICAL_THERMODYNAMICS" },
  { registryNumber: "LR-004106", slug: slug("Bragg diffraction condition"), title: "Bragg diffraction condition", summary: "Constructive reflection from parallel crystal planes occurs when the path difference is an integer number of wavelengths.", subcategory: "Structure and diffraction", direction: "MAXIMIZE", metricName: "diffracted-order condition", unit: "dimensionless", formalStatement: "Relate wavelength, plane spacing, incidence angle, and integer diffraction order for elastic crystal diffraction.", constraints: { scattering: "elastic", lattice: "periodic crystal planes", geometry: "specular Bragg reflection", order: "integer n" }, status: "PROVEN", relation: "=", formula: "nλ = 2d sin θ", claimType: "EXACT_VALUE", epistemic: "PROVEN", source: source("The diffraction of short electromagnetic waves by a crystal", "https://doi.org/10.1098/rspa.1913.0083", "1913-01-01", "Proceedings of the Royal Society A", "Original X-ray diffraction relation", "10.1098/rspa.1913.0083"), evidenceBasis: "WAVE_INTERFERENCE_DERIVATION" },
  { registryNumber: "LR-004107", slug: slug("Ideal-gas molar volume at 273.15 K and 100 kPa"), title: "Ideal-gas molar volume at 273.15 K and 100 kPa", summary: "An ideal gas occupies 22.71095464 L mol⁻¹ at 273.15 K and 100 kPa.", subcategory: "Gas-phase thermodynamics", direction: "MINIMIZE", metricName: "molar volume", unit: "L mol⁻¹", formalStatement: "Evaluate Vₘ = RT/p for one mole of an ideal gas at the recorded temperature and pressure.", constraints: { model: "ideal gas", amount: "1 mol", temperature: "273.15 K", pressure: "100 kPa", convention: "IUPAC standard ambient pressure" }, status: "PROVEN", relation: "=", formula: "Vₘ = RT/p = 22.71095464 L mol⁻¹", claimType: "EXACT_VALUE", epistemic: "PROVEN", source: source("IUPAC Green Book: Quantities, Units and Symbols in Physical Chemistry", "https://doi.org/10.1351/pac200466091283", "2004-01-01", "IUPAC", "Standard pressure and physical quantities", "10.1351/pac200466091283"), evidenceBasis: "EQUATION_OF_STATE" },
  { registryNumber: "LR-004108", slug: slug("Arrhenius temperature-dependence model"), title: "Arrhenius temperature-dependence model", summary: "In a thermally activated regime, a reaction-rate constant follows an exponential dependence on inverse temperature.", subcategory: "Chemical kinetics", direction: "MINIMIZE", metricName: "rate constant", unit: "s⁻¹ or concentration-dependent", formalStatement: "Fit the rate constant of a specified reaction to the Arrhenius form over a stated temperature interval.", constraints: { regime: "single dominant activated pathway", temperature: "finite fitted interval", activationEnergy: "approximately constant", prefactor: "A may depend on reaction order and units", scope: "model-dependent" }, status: "OPEN", relation: "=", formula: "k(T) = A exp(−Eₐ/RT)", claimType: "EXACT_VALUE", epistemic: "SOURCE_CONFIRMED", source: iupac("Arrhenius equation", "https://goldbook.iupac.org/terms/view/A00446", "Arrhenius equation definition"), evidenceBasis: "MODEL_QUALIFIED_LITERATURE_RELATION" },
  { registryNumber: "LR-004109", slug: slug("Ideal-solution chemical-potential relation"), title: "Ideal-solution chemical-potential relation", summary: "The chemical potential of a component in an ideal solution shifts with the logarithm of its mole fraction.", subcategory: "Solution thermodynamics", direction: "MAXIMIZE", metricName: "chemical potential", unit: "J mol⁻¹", formalStatement: "Compute the chemical potential of component i in an ideal solution from its standard chemical potential and mole fraction.", constraints: { solution: "ideal", composition: "xᵢ > 0", reference: "same temperature and pressure", interactions: "activity coefficient γᵢ = 1", scope: "limiting model" }, status: "PROVEN", relation: "=", formula: "μᵢ = μᵢ° + RT ln xᵢ", claimType: "EXACT_VALUE", epistemic: "PROVEN", source: iupac("chemical potential", "https://goldbook.iupac.org/terms/view/C01062", "Chemical-potential definition and ideal-mixture specialization"), evidenceBasis: "THERMODYNAMIC_DERIVATION" }
];
