type Source={title:string;url:string;date:string;venue:string;location:string;doi?:string};export type StorageRecord={registryNumber:string;slug:string;title:string;summary:string;subcategory:string;direction:"MINIMIZE"|"MAXIMIZE";metricName:string;unit:string;formalStatement:string;constraints:Record<string,unknown>;status:"PROVEN"|"OPEN";relation:"="|"<="|">=";formula:string;claimType:"EXACT_VALUE"|"UPPER_BOUND"|"LOWER_BOUND";epistemic:"PROVEN"|"EMPIRICALLY_SUPPORTED";source:Source;evidenceBasis:string};const s=(title:string,url:string,date:string,venue:string,location:string):Source=>({title,url,date,venue,location});
const S={ext4:s("The Linux kernel ext4 block documentation","https://www.kernel.org/doc/html/latest/filesystems/ext4/blocks.html","2026-08-01","Linux kernel documentation","Block-size limit tables"),win:s("File System Functionality Comparison","https://learn.microsoft.com/en-us/windows/win32/fileio/filesystem-functionality-comparison","2023-04-01","Microsoft Learn","Limits table"),exfat:s("exFAT File System Specification, revision 1.00","https://learn.microsoft.com/en-us/windows/win32/fileio/exfat-specification","2019-08-27","Microsoft","Section 9: File System Limits"),sqlite:s("Implementation Limits For SQLite","https://www.sqlite.org/limits.html","2025-05-31","SQLite project","Maximum pages and database size"),sd:s("SD Association product capacity standards","https://www.sdcard.org/about-sda/faq/","2026-01-01","SD Association","Memory-card capacity classes"),lto:s("LTO-10 Technology","https://www.lto.org/lto-10/","2025-08-13","LTO Program","Generation-10 format capacities and track count"),bd:s("R3 Format Specification (BDXL)","https://blu-raydisc.info/format-spec/r3-spec.php","2010-06-01","Blu-ray Disc Association","BDXL recordable capacities"),dna:s("DNA Fountain enables a robust and efficient storage architecture","https://doi.org/10.1126/science.aaj2038","2017-03-03","Science","Demonstrated density and coding architecture")};
type Row=[string,string,string,string,"PROVEN"|"OPEN",Source,string];const rows:Row[]=[
["ext4 maximum extent file size with 4 KiB blocks","16 TiB","Maximum regular-file size using extents on ext4 with 4 KiB filesystem blocks.","Filesystem formats","PROVEN",S.ext4,"FORMAT_SPECIFICATION"],
["ext4 maximum extent file size with 64 KiB blocks","256 TiB","Maximum regular-file size using extents on ext4 with 64 KiB filesystem blocks.","Filesystem formats","PROVEN",S.ext4,"FORMAT_SPECIFICATION"],
["ext4 32-bit filesystem size with 4 KiB blocks","16 TiB","Filesystem-size ceiling from 2^32 addressable blocks of 4 KiB each.","Filesystem formats","PROVEN",S.ext4,"FORMAT_SPECIFICATION"],
["ext4 64-bit address-space size with 4 KiB blocks","64 ZiB","Arithmetic block-address ceiling from 2^64 blocks of 4 KiB; practical implementation limits may be lower.","Filesystem formats","PROVEN",S.ext4,"FORMAT_SPECIFICATION"],
["FAT32 maximum file size","2^32 - 1 bytes","Largest object size accepted by FAT32's 32-bit file-size field.","Filesystem formats","PROVEN",S.win,"FORMAT_SPECIFICATION"],
["NTFS physical-format maximum file size","2^64 - 1 bytes","Physical-format file-size ceiling; operating-system implementation ceilings are separately versioned.","Filesystem formats","PROVEN",S.win,"FORMAT_SPECIFICATION"],
["exFAT maximum file size","2^64 - 1 bytes","Largest file length representable by exFAT's 64-bit data-length field.","Filesystem formats","PROVEN",S.win,"FORMAT_SPECIFICATION"],
["UDF maximum file size in Windows comparison","2^64 - 1 bytes","Maximum UDF file size listed by the Microsoft filesystem functionality specification.","Filesystem formats","PROVEN",S.win,"FORMAT_SPECIFICATION"],
["exFAT maximum cluster size","32 MiB","Largest allocation cluster permitted by exFAT revision 1.00 sector and cluster shift fields.","Filesystem formats","PROVEN",S.exfat,"FORMAT_SPECIFICATION"],
["exFAT maximum cluster count","2^32 - 11 clusters","Upper Cluster Heap count encoded by the exFAT ClusterCount field.","Filesystem formats","PROVEN",S.exfat,"FORMAT_SPECIFICATION"],
["exFAT volume-length field ceiling","2^64 - 1 sectors","Largest sector count representable by the exFAT VolumeLength field.","Filesystem formats","PROVEN",S.exfat,"FORMAT_SPECIFICATION"],
["exFAT recommended maximum volume size","approximately 512 TB","Recommended upper volume size using the largest cluster and recommended cluster-count ceiling.","Filesystem formats","PROVEN",S.exfat,"FORMAT_SPECIFICATION"],
["exFAT maximum directory stream size","256 MiB","Largest directory DataLength permitted by exFAT revision 1.00.","Filesystem formats","PROVEN",S.exfat,"FORMAT_SPECIFICATION"],
["exFAT maximum files per directory","2,796,202 files","Maximum minimum-sized file directory-entry sets in a 256 MiB directory stream.","Filesystem formats","PROVEN",S.exfat,"FORMAT_SPECIFICATION"],
["SQLite maximum database page size","65,536 bytes","Largest compile-time/runtime database page size supported by SQLite.","Database storage","PROVEN",S.sqlite,"IMPLEMENTATION_SPECIFICATION"],
["SQLite maximum pages per database","2^32 - 2 pages","Largest SQLITE_MAX_PAGE_COUNT accepted by current documented SQLite limits.","Database storage","PROVEN",S.sqlite,"IMPLEMENTATION_SPECIFICATION"],
["SQLite maximum database size","281,474,976,579,584 bytes","Maximum database size from 2^32-2 pages at 65,536 bytes per page.","Database storage","PROVEN",S.sqlite,"IMPLEMENTATION_SPECIFICATION"],
["SDHC standard maximum card capacity","32 GB","Upper capacity of the SD High Capacity class.","Removable media","PROVEN",S.sd,"INDUSTRY_STANDARD"],
["SDXC standard maximum card capacity","2 TB","Upper capacity of the SD Extended Capacity class.","Removable media","PROVEN",S.sd,"INDUSTRY_STANDARD"],
["SDUC standard maximum card capacity","128 TB","Upper capacity of the SD Ultra Capacity class.","Removable media","PROVEN",S.sd,"INDUSTRY_STANDARD"],
["LTO-10 maximum native cartridge capacity","40 TB","Largest native cartridge capacity published for the LTO Ultrium generation-10 format.","Magnetic tape","PROVEN",S.lto,"INDUSTRY_STANDARD"],
["LTO-10 maximum native transfer rate","400 MB/s","Published generation-10 native transfer-rate ceiling.","Magnetic tape","PROVEN",S.lto,"INDUSTRY_STANDARD"],
["LTO-10 data-track count","15,104 tracks","Number of data tracks specified across LTO-10 media.","Magnetic tape","PROVEN",S.lto,"INDUSTRY_STANDARD"],
["BDXL recordable-disc capacity","128 GB","Largest capacity in the BDXL R3 multi-layer recordable format.","Optical storage","PROVEN",S.bd,"INDUSTRY_STANDARD"],
["DNA Fountain demonstrated storage density","215 PB/g","Demonstrated coded DNA storage density reported by the DNA Fountain experiment.","Molecular storage","OPEN",S.dna,"EXPERIMENT"]
];
const slug=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");export const dataStorageRecords:StorageRecord[]=rows.map((r,i)=>{const[title,formula,summary,subcategory,status,source,evidenceBasis]=r;return{registryNumber:`LR-${String(3700+i).padStart(6,"0")}`,slug:slug(title),title,formula,summary,subcategory,direction:"MAXIMIZE",metricName:title.includes("rate")?"transfer rate":title.includes("files")?"file count":"storage capacity",unit:formula.split(" ").slice(1).join(" ")||"value",status,relation:status==="OPEN"?">=":"=",claimType:status==="OPEN"?"LOWER_BOUND":"EXACT_VALUE",epistemic:status==="OPEN"?"EMPIRICALLY_SUPPORTED":"PROVEN",source,evidenceBasis,formalStatement:`Under the recorded ${subcategory.toLowerCase()} version and parameters, establish ${formula}.`,constraints:{technology:subcategory,version:source.title,measurement:"binary and decimal units are preserved exactly as stated",scope:"format, implementation, or experiment named by the source",sourceLocation:source.location,empirical:status==="OPEN"}}});
