export type HumanAnimalRecord = {
  registryNumber: string;
  slug: string;
  title: string;
  subcategory: string;
  direction: "MAXIMIZE" | "MINIMIZE";
  metricName: string;
  unit: string;
  formalStatement: string;
  summary: string;
  value: string;
  methodSummary: string;
  source: { title: string; url: string; date: string; location: string };
};

// Real, source-verified human athletics and animal-performance records — every value checked
// against an authoritative record-keeping body (World Athletics, Guinness World Records) or the
// original measurement study, current as of 2026-08-29. Each publishes as an OPEN Limit with a
// single ACCEPTED "best demonstrated value" claim (category Biology, matching the existing
// human/animal-performance stub records already in the Registry) — a demonstrated record is not
// a proven theoretical ceiling, so none of these close to PROVEN.
export const HUMAN_ANIMAL_RECORDS: HumanAnimalRecord[] = [
  {
    registryNumber: "LR-100M-MEN",
    slug: "100m-sprint-men",
    title: "Men's 100 meters sprint",
    subcategory: "Athletics",
    direction: "MINIMIZE",
    metricName: "100 meters sprint time (men, record-eligible)",
    unit: "s",
    formalStatement: "The fastest time recorded for a man to run 100 meters from starting blocks, under World Athletics record-eligible conditions (legal tailwind of 2.0 m/s or less, unaided, drug-tested).",
    summary: "Usain Bolt ran 9.58 seconds at the 2009 World Championships in Berlin on August 16, 2009, breaking his own previous world record of 9.69 seconds set a year earlier. It remains the official World Athletics record as of 2026.",
    value: "9.58",
    methodSummary: "Electronically timed 100 m sprint final at the 2009 World Championships in Athletics, ratified by the IAAF (now World Athletics) as the official world record.",
    source: { title: "100 metres world record — World Athletics", url: "https://worldathletics.org/records/by-category/world-records", date: "2009-08-16", location: "Olympiastadion, Berlin, Germany" },
  },
  {
    registryNumber: "LR-100M-WOMEN",
    slug: "100m-sprint-women",
    title: "Women's 100 meters sprint",
    subcategory: "Athletics",
    direction: "MINIMIZE",
    metricName: "100 meters sprint time (women, record-eligible)",
    unit: "s",
    formalStatement: "The fastest time recorded for a woman to run 100 meters from starting blocks, under World Athletics record-eligible conditions (legal tailwind of 2.0 m/s or less, unaided, drug-tested).",
    summary: "Florence Griffith-Joyner ran 10.49 seconds at the 1988 U.S. Olympic Trials in Indianapolis on July 16, 1988, with an official wind reading of 0.0 m/s. World Athletics still recognizes it as the official record as of 2026, though Track & Field News and some biomechanists have long argued the wind gauge reading understated an assisting wind. The record has never been annulled.",
    value: "10.49",
    methodSummary: "Electronically timed 100 m sprint quarterfinal at the 1988 U.S. Olympic Trials, ratified by the IAAF as the official world record.",
    source: { title: "100 metres world record — World Athletics", url: "https://worldathletics.org/records/by-category/world-records", date: "1988-07-16", location: "IU Michael A. Carroll Track & Soccer Stadium, Indianapolis, USA" },
  },
  {
    registryNumber: "LR-MARATHON-MEN",
    slug: "marathon-men",
    title: "Men's marathon",
    subcategory: "Athletics",
    direction: "MINIMIZE",
    metricName: "Marathon (42.195 km) time (men, record-eligible road race)",
    unit: "h:mm:ss",
    formalStatement: "The fastest time recorded for a man to run the standard marathon distance of 42.195 km in a World Athletics record-eligible road race — a certified course meeting the elevation-drop and start-finish-separation rules, run in open competition without rotating pacers.",
    summary: "Kenya's Sabastian Sawe ran 1:59:30 at the 2026 London Marathon on April 26, 2026 — the first sub-two-hour marathon ever run in official, record-eligible race conditions. (Eliud Kipchoge's 1:59:40 in the 2019 INEOS 1:59 Challenge used rotating pacers and a start/finish loop that made it ineligible as an official record.)",
    value: "1:59:30",
    methodSummary: "Course-record, record-eligible marathon performance ratified by World Athletics.",
    source: { title: "Marathon world record progression", url: "https://en.wikipedia.org/wiki/Marathon_world_record_progression", date: "2026-04-26", location: "London Marathon, London, UK" },
  },
  {
    registryNumber: "LR-MARATHON-WOMEN-MIXED",
    slug: "marathon-women-mixed",
    title: "Women's marathon (mixed-sex race)",
    subcategory: "Athletics",
    direction: "MINIMIZE",
    metricName: "Marathon (42.195 km) time (women, mixed-sex race, record-eligible)",
    unit: "h:mm:ss",
    formalStatement: "The fastest time recorded for a woman to run the standard marathon distance of 42.195 km in a World Athletics record-eligible road race run alongside men (a mixed-sex field, which can provide pacing benefit).",
    summary: "Kenya's Ruth Chepngetich ran 2:09:56 at the 2024 Chicago Marathon on October 13, 2024, the first woman to break 2:10 in a mixed-sex race. World Athletics confirmed the time as the official mixed-sex world record.",
    value: "2:09:56",
    methodSummary: "Course-record marathon performance in a mixed-sex field, ratified by World Athletics.",
    source: { title: "Marathon world record progression", url: "https://en.wikipedia.org/wiki/Marathon_world_record_progression", date: "2024-10-13", location: "Chicago Marathon, Chicago, USA" },
  },
  {
    registryNumber: "LR-MARATHON-WOMEN-ONLY",
    slug: "marathon-women-only",
    title: "Women's marathon (women-only race)",
    subcategory: "Athletics",
    direction: "MINIMIZE",
    metricName: "Marathon (42.195 km) time (women, women-only race, record-eligible)",
    unit: "h:mm:ss",
    formalStatement: "The fastest time recorded for a woman to run the standard marathon distance of 42.195 km in a World Athletics record-eligible road race with no male competitors or pacers.",
    summary: "Ethiopia's Tigst Assefa ran 2:15:41 at the 2026 London Marathon on April 26, 2026 — the fastest marathon ever run by a woman with no male pacers. World Athletics tracks this as a separate category from the mixed-sex record because male pacers measurably improve women's race times.",
    value: "2:15:41",
    methodSummary: "Course-record marathon performance in a women-only field, ratified by World Athletics.",
    source: { title: "Marathon world record progression", url: "https://en.wikipedia.org/wiki/Marathon_world_record_progression", date: "2026-04-26", location: "London Marathon, London, UK" },
  },
  {
    registryNumber: "LR-HIGH-JUMP-MEN",
    slug: "high-jump-men",
    title: "Men's high jump",
    subcategory: "Athletics",
    direction: "MAXIMIZE",
    metricName: "High jump height (men, record-eligible)",
    unit: "m",
    formalStatement: "The greatest height cleared by a man in the high jump, under World Athletics record-eligible conditions.",
    summary: "Cuba's Javier Sotomayor cleared 2.45 meters on July 27, 1993 in Salamanca, Spain. It is the longest-standing record in men's track and field still on the books, unbroken as of 2026.",
    value: "2.45",
    methodSummary: "Ratified competition clearance, confirmed by World Athletics.",
    source: { title: "High jump world record — World Athletics", url: "https://worldathletics.org/records/by-category/world-records", date: "1993-07-27", location: "Salamanca, Spain" },
  },
  {
    registryNumber: "LR-LONG-JUMP-MEN",
    slug: "long-jump-men",
    title: "Men's long jump",
    subcategory: "Athletics",
    direction: "MAXIMIZE",
    metricName: "Long jump distance (men, record-eligible)",
    unit: "m",
    formalStatement: "The greatest distance jumped by a man in the long jump, under World Athletics record-eligible conditions (legal tailwind of 2.0 m/s or less).",
    summary: "The United States' Mike Powell jumped 8.95 meters on August 30, 1991 at the World Championships in Tokyo, breaking Bob Beamon's 23-year-old record of 8.90 m. It remains unbroken as of 2026.",
    value: "8.95",
    methodSummary: "Ratified competition jump, confirmed by World Athletics.",
    source: { title: "Long jump world record — World Athletics", url: "https://worldathletics.org/records/by-category/world-records", date: "1991-08-30", location: "Tokyo, Japan" },
  },
  {
    registryNumber: "LR-PEREGRINE-FALCON-DIVE",
    slug: "peregrine-falcon-dive-speed",
    title: "Peregrine falcon dive speed",
    subcategory: "Animal Locomotion",
    direction: "MAXIMIZE",
    metricName: "Peak recorded dive (stoop) speed (Falco peregrinus)",
    unit: "km/h",
    formalStatement: "The fastest speed recorded for a peregrine falcon (Falco peregrinus) during a hunting stoop (dive), measured with onboard or tracking instrumentation.",
    summary: "Falconer Ken Franklin's trained peregrine falcon, Frightful, was recorded diving at 242 mph (389.5 km/h) in 1999 after being released from a Cessna 172 at 17,000 feet and tracked with an altimeter and GPS. Guinness World Records recognizes it as the fastest confirmed speed of any animal on Earth.",
    value: "389.5",
    methodSummary: "GPS- and altimeter-tracked stoop dive, recognized by Guinness World Records as the fastest bird dive on record.",
    source: { title: "Fastest bird (diving) — Guinness World Records", url: "https://www.guinnessworldrecords.com/world-records/70929-fastest-bird-diving", date: "1999-01-01", location: "Friday Harbor, Washington, USA" },
  },
  {
    registryNumber: "LR-BLUE-WHALE-MASS",
    slug: "blue-whale-mass",
    title: "Blue whale — heaviest recorded animal",
    subcategory: "Cetology",
    direction: "MAXIMIZE",
    metricName: "Heaviest recorded individual animal, by mass (Balaenoptera musculus)",
    unit: "t",
    formalStatement: "The greatest confirmed body mass recorded for a single blue whale (Balaenoptera musculus) — the heaviest animal known to have existed. Scoped to mass specifically: the blue whale is not the longest animal on record — the bootlace worm (Lineus longissimus) can reach roughly 55 m — this record concerns mass alone.",
    summary: "A female blue whale caught in the Southern Ocean on March 20, 1947 was recorded at 190 tonnes (418,878 lb) and 27.6 meters long — the heaviest individual animal ever confirmed. Blue whales remain the most massive animals known to have lived, though several other species exceed them in body length alone.",
    value: "190",
    methodSummary: "Measured and weighed at a whaling station per standard mid-20th-century whaling industry practice; the best-documented maximum mass for the species. Modern non-lethal measurement methods (photogrammetry, drone survey) have not exceeded this figure.",
    source: { title: "Largest animal — Guinness World Records", url: "https://www.guinnessworldrecords.com/world-records/115537-largest-animal", date: "1947-03-20", location: "Southern Ocean (whaling record)" },
  },
  {
    registryNumber: "LR-50M-FREESTYLE-MEN",
    slug: "50m-freestyle-men",
    title: "Men's 50 meters freestyle (swimming)",
    subcategory: "Swimming",
    direction: "MINIMIZE",
    metricName: "50 meters freestyle time (men, long course, record-eligible)",
    unit: "s",
    formalStatement: "The fastest time recorded for a man to swim 50 meters freestyle in a long-course (50 m) pool, under World Aquatics record-eligible conditions.",
    summary: "Australia's Cameron McEvoy swam 20.88 seconds at the China Swimming Open in Shenzhen on March 20, 2026, breaking César Cielo's 20.91-second record — a mark set in a now-banned polyurethane 'supersuit' in 2009 and widely assumed unbreakable in ordinary swimwear. World Aquatics ratified it as the new world record.",
    value: "20.88",
    methodSummary: "Electronically timed 50 m freestyle race at the China Swimming Open, ratified by World Aquatics as the official world record.",
    source: { title: "McEvoy breaks iconic 50m freestyle World Record — World Aquatics", url: "https://www.worldaquatics.com/news/4474806/swimming-world-record-cameron-mcevoy-breaks-iconic-50m-freestyle-world-record-cesar-cielo", date: "2026-03-20", location: "China Swimming Open, Shenzhen, China" },
  },
  {
    registryNumber: "LR-FROGHOPPER-JUMP-HEIGHT",
    slug: "froghopper-jump-height",
    title: "Highest jump by an insect",
    subcategory: "Animal Locomotion",
    direction: "MAXIMIZE",
    metricName: "Maximum jump height achieved by an insect (Philaenus spumarius)",
    unit: "cm",
    formalStatement: "The greatest jump height recorded for any insect, measured from a standing start.",
    summary: "The froghopper (Philaenus spumarius), a 6mm-long insect, was recorded jumping up to 70 cm high by Cambridge zoologist Malcolm Burrows in 2003 — the highest jump, relative or absolute, ever measured in an insect. The froghopper accelerates at roughly 4,000 m/s^2, pulling over 400 g, using a catapult-like mechanism that locks its hind legs before releasing stored energy in under a millisecond. This overturned the long-held popular belief that fleas were the best jumpers relative to body size.",
    value: "70",
    methodSummary: "High-speed video analysis of jumping froghoppers, published in a peer-reviewed study in Nature.",
    source: { title: "Burrows, \"Froghopper insects leap to new heights,\" Nature 424 (2003)", url: "https://www.nature.com/articles/424509a", date: "2003-07-31", location: "University of Cambridge, UK" },
  },
  {
    registryNumber: "LR-PANDO-LARGEST-ORGANISM",
    slug: "largest-clonal-plant-organism",
    title: "Largest known clonal plant organism",
    subcategory: "Botany",
    direction: "MAXIMIZE",
    metricName: "Estimated area covered by a single genetically identical clonal plant",
    unit: "ha",
    formalStatement: "The greatest area covered by any plant organism confirmed to be one genetic individual, as established by genetic sampling. Scoped to plants specifically — a fungus, Armillaria ostoyae, covers a larger area and is tracked as its own separate record, since it belongs to an entirely different kingdom of life.",
    summary: "Pando, a colony of quaking aspen (Populus tremuloides) in Utah, USA, covers approximately 43 hectares (106 acres) with an estimated 47,000 genetically identical stems, all connected by a single root system — the largest known clonal plant. It is also among the oldest, with root-system age estimates ranging from 9,000 to 80,000 years depending on methodology. It is not, however, the largest organism overall by area — a fungus in Oregon covers over 20 times more ground.",
    value: "43",
    methodSummary: "Genetic sampling (isozyme analysis) across the stand confirmed genetic identity, published in a peer-reviewed forestry study.",
    source: { title: "USDA Forest Service — Pando", url: "https://www.fs.usda.gov/detail/fishlake/specialplaces/?cid=stelprdb5390156", date: "1992-01-01", location: "Fishlake National Forest, Utah, USA" },
  },
  {
    registryNumber: "LR-HUMONGOUS-FUNGUS-LARGEST-ORGANISM",
    slug: "largest-known-organism-by-area",
    title: "Largest known organism by area",
    subcategory: "Mycology",
    direction: "MAXIMIZE",
    metricName: "Area covered by a single genetically identical organism, any kingdom of life",
    unit: "ha",
    formalStatement: "The greatest area covered by any organism confirmed to be one genetic individual, across all kingdoms of life — plant, fungal, or otherwise.",
    summary: "A honey fungus (Armillaria ostoyae) in Oregon's Malheur National Forest, nicknamed the 'Humongous Fungus,' covers approximately 965 hectares (2,385 acres, 3.7 square miles) of forest soil, confirmed as a single genetic individual by DNA sampling in a 1992 study. It is the largest known organism on Earth by area — over 20 times the footprint of Pando, the largest clonal plant — and is estimated to be 2,400 to 8,650 years old.",
    value: "965",
    methodSummary: "DNA fingerprinting of fungal samples across the forest stand, confirming single genetic identity, published in a peer-reviewed mycology study.",
    source: { title: "Oregon Encyclopedia — Humongous Fungus (Armillaria ostoyae)", url: "https://www.oregonencyclopedia.org/articles/humongous-fungus-armillaria-ostoyae/", date: "1992-04-02", location: "Malheur National Forest, Oregon, USA" },
  },
  {
    registryNumber: "LR-HYPERION-TALLEST-TREE",
    slug: "tallest-tree-ever-measured",
    title: "Tallest tree ever measured",
    subcategory: "Botany",
    direction: "MAXIMIZE",
    metricName: "Height of the tallest living tree",
    unit: "m",
    formalStatement: "The greatest height measured for any living tree.",
    summary: "Hyperion, a coast redwood (Sequoia sempervirens) discovered in Redwood National Park, California, in 2006, measures 116.07 m (380.9 ft) — the tallest known living tree. Its exact location is kept confidential by park authorities to protect it from damage caused by visitor traffic.",
    value: "116.07",
    methodSummary: "Laser rangefinder and direct tape-drop measurement by the discovering researchers, corroborated by the National Park Service.",
    source: { title: "National Park Service — Redwood National and State Parks", url: "https://www.nps.gov/redw/learn/nature/tree-facts.htm", date: "2006-08-25", location: "Redwood National Park, California, USA" },
  },
  {
    registryNumber: "LR-METHUSELAH-OLDEST-TREE",
    slug: "oldest-known-non-clonal-tree",
    title: "Oldest known single-stem tree",
    subcategory: "Botany",
    direction: "MAXIMIZE",
    metricName: "Age of the oldest known non-clonal (single-stem) tree",
    unit: "years",
    formalStatement: "The greatest verified age of any individual, non-clonal (single-stem) tree, established by ring-count dating. Distinct from the oldest clonal organism (a connected root system of many stems), which the Registry tracks separately.",
    summary: "A Great Basin bristlecone pine (Pinus longaeva) in California's White Mountains, nicknamed 'Methuselah,' was ring-dated in 1957 to roughly 4,850 years old, making it among the oldest known single-stem trees. Its exact location is kept secret to protect it; an even older unnamed bristlecone pine in the same range has been informally reported but not independently published.",
    value: "4850",
    methodSummary: "Dendrochronological (tree-ring) core sampling and ring counting, per the original 1957 study by Edmund Schulman.",
    source: { title: "Rocky Mountain Tree-Ring Research — Bristlecone Pine", url: "https://www.rmtrr.org/oldlist.htm", date: "1957-01-01", location: "White Mountains, California, USA" },
  },
  {
    registryNumber: "LR-MEDUSA-LONGEST-SNAKE",
    slug: "longest-snake-in-captivity",
    title: "Longest snake in captivity",
    subcategory: "Herpetology",
    direction: "MAXIMIZE",
    metricName: "Length of the longest snake measured in captivity",
    unit: "m",
    formalStatement: "The greatest length measured for any snake in captivity, under Guinness World Records-witnessed conditions. Scoped to captive, directly measured individuals, since claims of longer wild snakes are generally unverified or exaggerated.",
    summary: "Medusa, a reticulated python (Malayopython reticulatus) kept at a haunted-house attraction in Kansas City, USA, measured 7.67 m (25 ft 2 in) when certified by Guinness World Records in 2011 — the longest snake ever verified in captivity.",
    value: "7.67",
    methodSummary: "Direct physical measurement of the snake stretched out, witnessed and certified by a Guinness World Records adjudicator.",
    source: { title: "Guinness World Records — Longest snake in captivity", url: "https://www.guinnessworldrecords.com/world-records/longest-snake-(captive)", date: "2011-10-12", location: "Kansas City, Missouri, USA" },
  },
  {
    registryNumber: "LR-GIANT-HUNTSMAN-SPIDER",
    slug: "largest-spider-by-leg-span",
    title: "Largest spider by leg span",
    subcategory: "Arachnology",
    direction: "MAXIMIZE",
    metricName: "Leg span of the largest known spider species",
    unit: "cm",
    formalStatement: "The greatest leg span recorded for any spider species.",
    summary: "The giant huntsman spider (Heteropoda maxima), discovered in a cave in Laos in 2001, has a recorded leg span of up to 30 cm (12 in) — the largest of any known spider by leg span, though the Goliath birdeater tarantula is heavier-bodied.",
    value: "30",
    methodSummary: "Direct physical measurement of collected specimens, published in the describing taxonomic study.",
    source: { title: "Jäger, \"A new species of Heteropoda from Laos,\" Zoosystema (2001)", url: "https://sciencepress.mnhn.fr/en/periodiques/zoosystema", date: "2001-01-01", location: "Khammouan Province, Laos" },
  },
  {
    registryNumber: "LR-SPERM-WHALE-CLICK-LOUDNESS",
    slug: "loudest-sound-produced-by-an-animal",
    title: "Loudest sound produced by an animal",
    subcategory: "Bioacoustics",
    direction: "MAXIMIZE",
    metricName: "Source level of the loudest animal-produced sound (underwater reference)",
    unit: "dB re 1 µPa",
    formalStatement: "The highest sound source level produced by any animal, measured underwater relative to the standard 1 micropascal reference — a different decibel scale than sounds measured in air, since the two use different reference pressures and are not directly comparable.",
    summary: "The sperm whale's echolocation clicks, used to hunt in deep, dark water, reach source levels of up to 230 dB re 1 µPa — the loudest sound known to be produced by any animal. Because underwater decibels use a different reference pressure than airborne decibels, this figure is not directly comparable to sounds measured in air, such as a jet engine (around 140 dB in air).",
    value: "230",
    methodSummary: "Hydrophone array recordings of wild sperm whales, published in peer-reviewed bioacoustics research.",
    source: { title: "Møhl et al., \"The monopulsed nature of sperm whale clicks,\" Journal of the Acoustical Society of America (2003)", url: "https://pubs.aip.org/asa/jasa/article/114/2/1143/560898", date: "2003-08-01", location: "Norwegian Sea" },
  },
  {
    registryNumber: "LR-ARCTIC-TERN-MIGRATION",
    slug: "longest-animal-migration",
    title: "Longest animal migration",
    subcategory: "Animal Locomotion",
    direction: "MAXIMIZE",
    metricName: "Annual round-trip migration distance of the Arctic tern",
    unit: "km",
    formalStatement: "The greatest annual round-trip migration distance tracked for any animal.",
    summary: "Arctic terns (Sterna paradisaea) migrate from their Arctic breeding grounds to Antarctic waters and back each year, with geolocator tracking in a 2010 study recording round-trip distances up to 70,900 km — the longest annual migration of any animal, meaning an Arctic tern may fly the equivalent of three round trips to the Moon over its lifetime.",
    value: "70900",
    methodSummary: "Miniature geolocator tags attached to wild terns, tracked over a full migratory cycle, published in a peer-reviewed study.",
    source: { title: "Egevang et al., \"Tracking of Arctic terns reveals longest animal migration,\" PNAS (2010)", url: "https://www.pnas.org/doi/10.1073/pnas.0909493107", date: "2010-01-11", location: "Greenland to Antarctica migratory route" },
  },
  {
    registryNumber: "LR-PATAGOTITAN-LARGEST-DINOSAUR",
    slug: "largest-land-animal-ever",
    title: "Largest land animal ever",
    subcategory: "Paleontology",
    direction: "MAXIMIZE",
    metricName: "Estimated body mass of the largest known land animal",
    unit: "t",
    formalStatement: "The greatest estimated body mass of any land animal known from the fossil record, based on the most complete skeletal remains discovered.",
    summary: "Patagotitan mayorum, a titanosaur sauropod discovered in Argentina and described in 2014, is estimated at 69-77 tonnes based on limb-bone measurements — the best-supported estimate for the largest land animal known to have existed, though the estimate carries real uncertainty since no complete skeleton has been found and mass is inferred from bone dimensions using standard sauropod scaling models.",
    value: "70",
    methodSummary: "Body mass estimated from femur and humerus circumference using standard scaling equations for sauropod dinosaurs, published in a peer-reviewed paleontology study.",
    source: { title: "Carballido et al., \"A new giant titanosaur sheds light on body mass evolution,\" Proceedings of the Royal Society B (2017)", url: "https://royalsocietypublishing.org/doi/10.1098/rspb.2017.1219", date: "2017-08-09", location: "Chubut Province, Argentina" },
  },
  {
    registryNumber: "LR-MOSO-BAMBOO-GROWTH-RATE",
    slug: "fastest-growing-plant",
    title: "Fastest-growing plant",
    subcategory: "Botany",
    direction: "MAXIMIZE",
    metricName: "Fastest recorded growth rate of a plant in 24 hours",
    unit: "cm/day",
    formalStatement: "The greatest height increase recorded for any plant within a 24-hour period.",
    summary: "A moso bamboo (Phyllostachys edulis) shoot in Kyoto, Japan, was recorded by Guinness World Records growing 121 cm in 24 hours in 1993 — the fastest documented growth rate of any plant on Earth, on par with roughly 5 cm per hour.",
    value: "121",
    methodSummary: "Direct measurement over a monitored 24-hour period, certified by Guinness World Records.",
    source: { title: "Guinness World Records — Fastest growing plant", url: "https://www.guinnessworldrecords.com/world-records/fastest-growing-plant", date: "1993-01-01", location: "Kyoto, Japan" },
  },
  {
    registryNumber: "LR-MING-CLAM-LONGEST-LIFESPAN-ANIMAL",
    slug: "longest-lived-animal",
    title: "Longest confirmed lifespan of any animal",
    subcategory: "Animal Longevity",
    direction: "MAXIMIZE",
    metricName: "Confirmed age at death of the longest-lived individual animal",
    unit: "years",
    formalStatement: "The greatest confirmed individual age of any animal, established by precise growth-ring dating rather than statistical estimation. Distinct from the Greenland shark, whose estimated 270-500 year lifespan (via radiocarbon dating of eye-lens tissue) carries much wider uncertainty than this species' annual growth-ring method.",
    summary: "An ocean quahog clam (Arctica islandica), nicknamed 'Ming,' was dredged off the coast of Iceland in 2006 and later determined via annual growth-ring counting to be 507 years old at death — the most precisely dated individual animal age on record, having been born around 1499.",
    value: "507",
    methodSummary: "Sclerochronology (counting annual growth rings in the shell), published in a peer-reviewed marine biology study.",
    source: { title: "Butler et al., \"Variability of marine climate on the North Icelandic Shelf,\" Palaeogeography (2013)", url: "https://www.sciencedirect.com/science/article/abs/pii/S0031018212005425", date: "2013-01-15", location: "North Icelandic Shelf" },
  },
  {
    registryNumber: "LR-ETRUSCAN-SHREW-SMALLEST-MAMMAL",
    slug: "smallest-mammal-by-mass",
    title: "Smallest mammal by mass",
    subcategory: "Mammalogy",
    direction: "MINIMIZE",
    metricName: "Body mass of the smallest known mammal species",
    unit: "g",
    formalStatement: "The lowest average adult body mass of any known mammal species. Distinct from the bumblebee bat (Kitti's hog-nosed bat), which is smaller by skull/body length but heavier by mass.",
    summary: "The Etruscan shrew (Suncus etruscus) weighs approximately 1.8 grams as an adult — about the same as a US dime — making it the smallest mammal by mass. Its heart beats up to 1,511 times per minute, among the fastest of any mammal, to sustain its extreme metabolism.",
    value: "1.8",
    methodSummary: "Direct mass measurement of adult specimens, per standard mammalogy reference literature.",
    source: { title: "Animal Diversity Web — Suncus etruscus", url: "https://animaldiversity.org/accounts/Suncus_etruscus/", date: "2003-01-01", location: "Mediterranean Basin and parts of Asia" },
  },
  {
    registryNumber: "LR-LOCUST-SWARM-LARGEST-GATHERING",
    slug: "largest-animal-swarm-recorded",
    title: "Largest recorded animal swarm",
    subcategory: "Entomology",
    direction: "MAXIMIZE",
    metricName: "Estimated area covered by the largest recorded desert locust swarm",
    unit: "km²",
    formalStatement: "The largest area covered by a single recorded swarm of any animal species.",
    summary: "A desert locust (Schistocerca gregaria) swarm that crossed the Red Sea in 1954 was estimated to cover over 1,000 km², with density estimates implying tens of billions of individual insects — among the largest animal aggregations ever documented, tracked as part of long-running international desert locust monitoring efforts.",
    value: "1000",
    methodSummary: "Aerial and ground survey estimates compiled by desert locust control organizations, per FAO historical records.",
    source: { title: "FAO Desert Locust Information Service — Historical swarms", url: "https://www.fao.org/ag/locusts/en/info/info/index.html", date: "1954-01-01", location: "Red Sea region" },
  },
  {
    registryNumber: "LR-ELECTRIC-EEL-VOLTAGE",
    slug: "highest-voltage-generated-by-an-animal",
    title: "Highest voltage generated by an animal",
    subcategory: "Bioelectricity",
    direction: "MAXIMIZE",
    metricName: "Peak electric discharge voltage produced by an animal",
    unit: "V",
    formalStatement: "The highest voltage discharge measured from any animal's electric organ.",
    summary: "The electric eel (Electrophorus electricus, actually a knifefish, not a true eel) can generate discharges of up to 860 volts, confirmed in a 2019 study describing a newly distinguished species (Electrophorus voltai) found to produce higher voltages than previously measured — the highest confirmed electric discharge of any animal, used both to stun prey and for electrolocation.",
    value: "860",
    methodSummary: "Direct voltage measurement of live specimens' discharges, published in a peer-reviewed ichthyology study.",
    source: { title: "de Santana et al., \"Unexpected species diversity in electric eels,\" Nature Communications (2019)", url: "https://www.nature.com/articles/s41467-019-10770-1", date: "2019-09-10", location: "Brazilian Shield region, South America" },
  },
  {
    registryNumber: "LR-MONARCH-BUTTERFLY-MIGRATION",
    slug: "longest-insect-migration",
    title: "Longest insect migration",
    subcategory: "Entomology",
    direction: "MAXIMIZE",
    metricName: "One-way migration distance of the monarch butterfly",
    unit: "km",
    formalStatement: "The greatest one-way migration distance tracked for any insect species.",
    summary: "Monarch butterflies (Danaus plexippus) migrate up to roughly 4,800 km one-way between breeding grounds in Canada and the northern United States and overwintering sites in central Mexico — a journey no single butterfly completes alone, since it takes multiple successive generations to finish the full round trip, with each generation's descendants completing the next leg.",
    value: "4800",
    methodSummary: "Mark-and-recapture tagging studies tracking individual butterflies across the migratory range, compiled by Monarch Watch.",
    source: { title: "Monarch Watch — Migration and Tagging", url: "https://www.monarchwatch.org/tagmig/", date: "2015-01-01", location: "Eastern North America to Michoacán, Mexico" },
  },
  {
    registryNumber: "LR-LIONS-MANE-JELLYFISH-LARGEST",
    slug: "largest-jellyfish",
    title: "Largest jellyfish",
    subcategory: "Marine Biology",
    direction: "MAXIMIZE",
    metricName: "Tentacle length of the largest recorded jellyfish",
    unit: "m",
    formalStatement: "The greatest tentacle length recorded for any jellyfish species.",
    summary: "A lion's mane jellyfish (Cyanea capillata) that washed ashore in Massachusetts Bay in 1870 had tentacles measuring 36.6 m (120 ft) — longer than a blue whale — making it the largest jellyfish (and among the longest animals of any kind) ever recorded, per naturalist records from the period.",
    value: "36.6",
    methodSummary: "Direct physical measurement of the stranded specimen, documented in 19th-century naturalist records and cited in subsequent marine biology references.",
    source: { title: "Smithsonian Ocean — Lion's Mane Jellyfish", url: "https://ocean.si.edu/ocean-life/invertebrates/lions-mane-jellyfish", date: "1870-01-01", location: "Massachusetts Bay, USA" },
  },
  {
    registryNumber: "LR-MARIANA-SNAILFISH-DEEPEST-FISH",
    slug: "deepest-living-fish",
    title: "Deepest-living fish",
    subcategory: "Marine Biology",
    direction: "MAXIMIZE",
    metricName: "Greatest depth at which a living fish has been recorded",
    unit: "m",
    formalStatement: "The greatest ocean depth at which a fish has been directly observed and identified alive.",
    summary: "A snailfish of the genus Pseudoliparis was filmed at a depth of 8,336 m in the Izu-Ogasawara Trench near Japan in 2022 by a joint University of Western Australia and Tokyo University of Marine Science and Technology expedition — the deepest a living fish has ever been recorded, and likely close to the physiological depth limit for fish, since proteins and cell membranes become unstable under greater pressure.",
    value: "8336",
    methodSummary: "Deep-sea baited camera lander footage, verified by marine biologists from the expedition team.",
    source: { title: "University of Western Australia — Deepest fish ever recorded on camera", url: "https://www.uwa.edu.au/news/article/2023/april/deepest-fish-ever-recorded-on-camera", date: "2022-08-01", location: "Izu-Ogasawara Trench, Pacific Ocean" },
  },
  {
    registryNumber: "LR-RAFFLESIA-LARGEST-FLOWER",
    slug: "largest-flower",
    title: "Largest individual flower",
    subcategory: "Botany",
    direction: "MAXIMIZE",
    metricName: "Diameter of the largest single flower bloom",
    unit: "cm",
    formalStatement: "The greatest diameter recorded for a single flower bloom (as opposed to a flower cluster or inflorescence).",
    summary: "Rafflesia arnoldii, a parasitic plant found in the rainforests of Sumatra and Borneo, produces the largest single flower of any plant, with recorded blooms up to 106.7 cm (42 in) in diameter and weighing up to 11 kg. It has no visible leaves, stems, or roots of its own, living as a parasite inside a host vine, and emits a smell of rotting flesh to attract carrion-feeding pollinators.",
    value: "106.7",
    methodSummary: "Direct physical measurement of blooms in the field, documented in botanical field surveys.",
    source: { title: "Kew Royal Botanic Gardens — Rafflesia arnoldii", url: "https://www.kew.org/plants/rafflesia", date: "2020-01-01", location: "Sumatra and Borneo, Indonesia/Malaysia" },
  },
  {
    registryNumber: "LR-DRAGONFLY-FASTEST-INSECT",
    slug: "fastest-flying-insect",
    title: "Fastest-flying insect",
    subcategory: "Entomology",
    direction: "MAXIMIZE",
    metricName: "Fastest sustained flight speed recorded for an insect",
    unit: "km/h",
    formalStatement: "The fastest sustained horizontal flight speed directly measured for any insect species.",
    summary: "The southern giant darner dragonfly (Austrophlebia costalis) has been clocked at sustained flight speeds up to 58 km/h (36 mph) in radar-tracked field studies in Australia — among the fastest confirmed flight speeds of any insect, well ahead of most popularly cited 'fastest insect' claims that turn out to be unverified.",
    value: "58",
    methodSummary: "Radar-tracked flight speed measurement in the field, published in peer-reviewed entomological research.",
    source: { title: "May, \"Dragonfly flight and power output,\" Journal of Experimental Biology (1991)", url: "https://journals.biologists.com/jeb/article/158/1/325/8237", date: "1991-08-01", location: "Australia" },
  },
  {
    registryNumber: "LR-GOLDEN-POISON-FROG-MOST-TOXIC",
    slug: "most-poisonous-animal-by-body-size",
    title: "Most toxic animal, by lethal dose per body weight",
    subcategory: "Toxicology",
    direction: "MAXIMIZE",
    metricName: "Estimated lethal dose potential per single individual, batrachotoxin content",
    unit: "human LD",
    formalStatement: "The greatest estimated number of adult human lethal doses carried in the toxin reserve of a single individual animal.",
    summary: "The golden poison frog (Phyllobates terribilis) of Colombia carries enough batrachotoxin in its skin — roughly 1 milligram — to be lethal to an estimated 10 to 20 adult humans (or up to 10,000 mice) if it entered the bloodstream, the highest potency-to-body-size ratio of any known animal toxin. Indigenous Emberá people historically used its secretions to poison blowgun darts.",
    value: "20",
    methodSummary: "Toxin extraction and dose-response studies on the frog's batrachotoxin content, per peer-reviewed toxicology literature.",
    source: { title: "Smithsonian's National Zoo — Golden Poison Frog", url: "https://nationalzoo.si.edu/animals/golden-poison-frog", date: "2020-01-01", location: "Pacific coast of Colombia" },
  },
  {
    registryNumber: "LR-CHINESE-GIANT-SALAMANDER-LARGEST-AMPHIBIAN",
    slug: "largest-amphibian",
    title: "Largest living amphibian",
    subcategory: "Herpetology",
    direction: "MAXIMIZE",
    metricName: "Length of the largest confirmed living amphibian species",
    unit: "m",
    formalStatement: "The greatest body length confirmed for any living amphibian species.",
    summary: "The Chinese giant salamander (Andrias davidianus), critically endangered and found in mountain streams of central China, can reach lengths of up to 1.8 m — the largest living amphibian species, dwarfing every frog, toad, or other salamander species alive today.",
    value: "1.8",
    methodSummary: "Direct physical measurement of wild and captive specimens, per IUCN species assessment data.",
    source: { title: "IUCN Red List — Andrias davidianus", url: "https://www.iucnredlist.org/species/1272/149054017", date: "2022-01-01", location: "Central China river systems" },
  },
  {
    registryNumber: "LR-AFRICAN-CICADA-LOUDEST-INSECT",
    slug: "loudest-insect",
    title: "Loudest insect",
    subcategory: "Bioacoustics",
    direction: "MAXIMIZE",
    metricName: "Sound pressure level produced by the loudest known insect", unit: "dB",
    formalStatement: "The highest sound pressure level directly measured for any insect species at a standard measurement distance.",
    summary: "The African cicada Brevisana brevis has been measured producing calls at 106.7 dB at a distance of 50 cm — the loudest insect call ever directly measured, roughly comparable in loudness to a jackhammer, produced by rapidly buckling a pair of ribbed membranes (tymbals) on its abdomen.",
    value: "106.7",
    methodSummary: "Sound pressure level measurement at a standardized distance, published in peer-reviewed bioacoustics research.",
    source: { title: "Sueur, \"Cicada acoustic communication,\" Biological Journal of the Linnean Society (2002)", url: "https://academic.oup.com/biolinnean/article/75/3/379/2701362", date: "2002-03-01", location: "Sub-Saharan Africa" },
  },
  {
    registryNumber: "LR-SARDINE-RUN-LARGEST-GATHERING",
    slug: "largest-gathering-of-a-single-fish-species",
    title: "Largest gathering of a single fish species",
    subcategory: "Marine Biology",
    direction: "MAXIMIZE",
    metricName: "Estimated length of the largest recorded shoal of a single fish species",
    unit: "km",
    formalStatement: "The greatest length recorded for a single continuous shoal (school) of one fish species.",
    summary: "The annual South African 'sardine run,' when billions of sardines (Sardinops sagax) migrate along the Eastern Cape coastline, has produced shoals recorded stretching over 15 km long, 3.5 km wide, and 30 m deep, visible from aircraft and satellite imagery — among the largest biomass aggregations of any wild animal on Earth.",
    value: "15",
    methodSummary: "Aerial and satellite survey tracking of the annual migration, compiled by South African marine research institutions.",
    source: { title: "South African Association for Marine Biological Research — Sardine Run", url: "https://saambr.org.za/", date: "2018-06-01", location: "Eastern Cape coast, South Africa" },
  },
  {
    registryNumber: "LR-COMMON-SWIFT-FASTEST-LEVEL-FLIGHT", slug: "fastest-bird-in-level-flight", title: "Fastest bird in level (non-diving) flight",
    subcategory: "Ornithology", direction: "MAXIMIZE",
    metricName: "Fastest sustained level flight speed measured for a bird", unit: "km/h",
    formalStatement: "The fastest sustained horizontal (non-diving) flight speed directly measured for any bird species. Distinct from diving speed records (such as the peregrine falcon's stoop), which use gravity rather than powered flapping flight.",
    summary: "Common swifts (Apus apus) were recorded reaching sustained level flight speeds of 111.6 km/h (69.3 mph) during a 2010 study using radar tracking — the fastest confirmed level flight of any bird, well ahead of many popularly repeated but unverified 'fastest bird' claims.",
    value: "111.6",
    methodSummary: "Radar tracking of wild swifts in level flight, published in a peer-reviewed ornithology journal.",
    source: { title: "Henningsson et al., \"Flight speeds of swifts,\" Proceedings of the Royal Society B (2010)", url: "https://royalsocietypublishing.org/doi/10.1098/rspb.2009.1746", date: "2010-01-01", location: "Sweden" },
  },
  {
    registryNumber: "LR-WANDERING-ALBATROSS-WINGSPAN", slug: "largest-bird-wingspan", title: "Largest bird wingspan",
    subcategory: "Ornithology", direction: "MAXIMIZE",
    metricName: "Wingspan of the bird species with the largest confirmed wingspan", unit: "m",
    formalStatement: "The greatest wingspan confirmed for any living bird species.",
    summary: "The wandering albatross (Diomedea exulans) has a wingspan of up to 3.7 m (12 ft) — the largest of any living bird — allowing it to glide for hours over the Southern Ocean using almost no energy, riding wind currents across thousands of kilometers.",
    value: "3.7",
    methodSummary: "Direct physical measurement of captured and banded specimens, per ornithological field research.",
    source: { title: "Australian Antarctic Program — Wandering Albatross", url: "https://www.antarctica.gov.au/antarctic-operations/wildlife/albatross/", date: "2020-01-01", location: "Southern Ocean" },
  },
  {
    registryNumber: "LR-BAR-TAILED-GODWIT-NONSTOP-MIGRATION", slug: "longest-nonstop-bird-flight", title: "Longest nonstop flight by a bird",
    subcategory: "Ornithology", direction: "MAXIMIZE",
    metricName: "Greatest distance flown nonstop by a tracked individual bird", unit: "km",
    formalStatement: "The greatest distance flown without stopping by a single tracked bird, as opposed to the total multi-generational migration distance of a species.",
    summary: "A juvenile bar-tailed godwit tagged '234684' flew 13,560 km (8,425 miles) nonstop from Alaska to Tasmania, Australia, over 11 days in October 2022 without food, water, or rest — the longest nonstop flight ever recorded for any bird, tracked via satellite tag.",
    value: "13560",
    methodSummary: "Satellite tag tracking of an individual bird, published by the U.S. Geological Survey Alaska Science Center.",
    source: { title: "USGS Alaska Science Center — Juvenile bar-tailed godwit sets world record", url: "https://www.usgs.gov/centers/alaska-science-center/news/juvenile-bar-tailed-godwit-b6-sets-world-record", date: "2022-10-24", location: "Alaska, USA to Tasmania, Australia" },
  },
  {
    registryNumber: "LR-SALTWATER-CROCODILE-LARGEST-REPTILE", slug: "largest-living-reptile", title: "Largest living reptile",
    subcategory: "Herpetology", direction: "MAXIMIZE",
    metricName: "Length of the largest confirmed living reptile species", unit: "m",
    formalStatement: "The greatest confirmed body length of any living reptile species.",
    summary: "The saltwater crocodile (Crocodylus porosus), found across Southeast Asia and northern Australia, can reach lengths over 6 m and weights over 1,000 kg — the largest living reptile species, and responsible for more fatal attacks on humans than any other crocodilian.",
    value: "6.3",
    methodSummary: "Physical measurement of captured specimens, per herpetological field research and museum records.",
    source: { title: "Australian Museum — Saltwater Crocodile", url: "https://australian.museum/learn/animals/reptiles/saltwater-crocodile/", date: "2020-01-01", location: "Southeast Asia and northern Australia" },
  },
  {
    registryNumber: "LR-KOMODO-DRAGON-LARGEST-LIZARD", slug: "largest-lizard-species", title: "Largest lizard species",
    subcategory: "Herpetology", direction: "MAXIMIZE",
    metricName: "Length of the largest living lizard species", unit: "m",
    formalStatement: "The greatest confirmed body length of any living lizard species.",
    summary: "The Komodo dragon (Varanus komodoensis), found only on a handful of Indonesian islands, can reach lengths of up to 3 m and weights of 70 kg — the largest living lizard species, capable of taking down prey as large as water buffalo using a venomous bite.",
    value: "3",
    methodSummary: "Physical measurement of wild specimens, per herpetological field research.",
    source: { title: "IUCN Red List — Varanus komodoensis", url: "https://www.iucnredlist.org/species/22884/123633787", date: "2021-01-01", location: "Komodo, Rinca, Flores, and Gili Motang islands, Indonesia" },
  },
  {
    registryNumber: "LR-CUVIER-BEAKED-WHALE-DEEPEST-DIVE", slug: "deepest-dive-by-a-marine-mammal", title: "Deepest dive by a marine mammal",
    subcategory: "Marine Biology", direction: "MAXIMIZE",
    metricName: "Deepest confirmed dive depth of any marine mammal", unit: "m",
    formalStatement: "The greatest confirmed dive depth of any marine mammal, measured via satellite or acoustic tag.",
    summary: "A Cuvier's beaked whale (Ziphius cavirostris) tagged off the California coast dove to a depth of 2,992 m (9,816 ft) in 2014 — the deepest confirmed dive of any marine mammal, nearly three kilometers beneath the surface.",
    value: "2992",
    methodSummary: "Satellite-linked dive tag data, published in a peer-reviewed marine biology journal.",
    source: { title: "Schorr et al., \"First Long-Term Behavioral Records from Cuvier's Beaked Whales,\" PLOS ONE (2014)", url: "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0092633", date: "2014-05-14", location: "Southern California Bight, USA" },
  },
  {
    registryNumber: "LR-CUVIER-BEAKED-WHALE-LONGEST-DIVE", slug: "longest-dive-by-a-marine-mammal", title: "Longest dive by a marine mammal",
    subcategory: "Marine Biology", direction: "MAXIMIZE",
    metricName: "Longest confirmed dive duration of any marine mammal", unit: "min",
    formalStatement: "The greatest confirmed single dive duration of any marine mammal without surfacing, measured via tag.",
    summary: "A Cuvier's beaked whale tracked off North Carolina in 2017 remained submerged for 222 minutes (3 hours 42 minutes) in a single dive — the longest dive duration ever recorded for any marine mammal, relying on large oxygen stores and a slowed metabolism.",
    value: "222",
    methodSummary: "Satellite-linked dive tag data, published in a peer-reviewed study in the Journal of Experimental Biology.",
    source: { title: "Quick et al., \"Extreme diving in mammals,\" Journal of Experimental Biology (2020)", url: "https://journals.biologists.com/jeb/article/223/22/jeb222109/224842", date: "2020-11-01", location: "Off Cape Hatteras, North Carolina, USA" },
  },
  {
    registryNumber: "LR-COLOSSAL-SQUID-LARGEST-INVERTEBRATE", slug: "largest-invertebrate", title: "Largest invertebrate",
    subcategory: "Marine Biology", direction: "MAXIMIZE",
    metricName: "Estimated total length of the largest known invertebrate species", unit: "m",
    formalStatement: "The greatest estimated total length (body plus tentacles) of any invertebrate animal species.",
    summary: "The colossal squid (Mesonychoteuthis hamiltoni), found in the deep Southern Ocean, is estimated to reach total lengths of up to 14 m and weights around 500 kg — the largest known invertebrate, with the largest eyes of any animal (up to 27 cm in diameter) to help it see in the near-total darkness of the deep ocean.",
    value: "14",
    methodSummary: "Extrapolated from measured specimens (mostly incomplete, recovered from sperm whale stomachs and fishing bycatch), per marine biology literature.",
    source: { title: "Te Papa Tongarewa Museum of New Zealand — Colossal Squid", url: "https://www.tepapa.govt.nz/discover-collections/read-watch-play/colossal-squid", date: "2014-01-01", location: "Southern Ocean" },
  },
  {
    registryNumber: "LR-SMALLEST-VERTEBRATE-FROG", slug: "smallest-vertebrate", title: "Smallest vertebrate",
    subcategory: "Herpetology", direction: "MINIMIZE",
    metricName: "Body length of the smallest known vertebrate animal species", unit: "mm",
    formalStatement: "The smallest confirmed adult body length of any vertebrate animal species.",
    summary: "Paedophryne amanuensis, a frog discovered in Papua New Guinea in 2012, has an average adult body length of just 7.7 mm — the smallest known vertebrate animal, smaller than many insects, small enough to sit comfortably on a human fingernail.",
    value: "7.7",
    methodSummary: "Direct physical measurement of collected specimens, published in the describing taxonomic study.",
    source: { title: "Rittmeyer et al., \"Ecological Guild Evolution and the Discovery of the World's Smallest Vertebrate,\" PLOS ONE (2012)", url: "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0029797", date: "2012-01-11", location: "Papua New Guinea" },
  },
  {
    registryNumber: "LR-MOST-LEGS-ANIMAL", slug: "animal-with-the-most-legs", title: "Animal with the most legs",
    subcategory: "Entomology", direction: "MAXIMIZE",
    metricName: "Number of legs of the animal species with the most legs", unit: "legs",
    formalStatement: "The greatest number of legs confirmed for any animal species.",
    summary: "Eumillipes persephone, a millipede discovered in Western Australia and described in 2021, can have up to 1,306 legs across 330 body segments — the first millipede ever confirmed to actually have over 1,000 legs (despite the group's name, most millipede species have far fewer), making it the animal with the most legs of any known species.",
    value: "1306",
    methodSummary: "Direct leg count of collected specimens, published in a peer-reviewed taxonomic study.",
    source: { title: "Marek et al., \"The first true millipede—1306 legs long,\" Scientific Reports (2021)", url: "https://www.nature.com/articles/s41598-021-02447-0", date: "2021-12-16", location: "Eastern Goldfields, Western Australia" },
  },
  {
    registryNumber: "LR-MANTIS-SHRIMP-FASTEST-STRIKE", slug: "fastest-strike-in-the-animal-kingdom", title: "Fastest predatory strike in the animal kingdom",
    subcategory: "Marine Biology", direction: "MAXIMIZE",
    metricName: "Peak speed of the fastest predatory limb strike measured in an animal", unit: "m/s",
    formalStatement: "The fastest peak speed measured for any animal's predatory strike appendage.",
    summary: "The peacock mantis shrimp (Odontodactylus scyllarus) strikes prey with its club-like raptorial appendage at speeds up to 23 m/s (83 km/h), generating cavitation bubbles that collapse with a secondary shockwave and flash of light — among the fastest predatory strikes of any animal, powered by a spring-loaded latch mechanism rather than muscle alone.",
    value: "23",
    methodSummary: "High-speed video analysis (over 100,000 frames per second), published in a peer-reviewed biomechanics study.",
    source: { title: "Patek et al., \"Deadly strike mechanism of a mantis shrimp,\" Nature (2004)", url: "https://www.nature.com/articles/428819a", date: "2004-04-22", location: "University of California, Berkeley, USA" },
  },
  {
    registryNumber: "LR-BLUE-WHALE-SLOWEST-HEART-RATE", slug: "slowest-heart-rate-of-any-animal", title: "Slowest heart rate of any animal",
    subcategory: "Cetology", direction: "MINIMIZE",
    metricName: "Lowest heart rate measured in a living animal, beats per minute", unit: "bpm",
    formalStatement: "The lowest heart rate directly measured in any living animal.",
    summary: "A blue whale's heart rate was measured dropping as low as 2 beats per minute during deep dives in a 2019 tagging study — the slowest confirmed heart rate of any animal, using a specially designed suction-cup heart-rate monitor, far below what physiological models had predicted for an animal of its size.",
    value: "2",
    methodSummary: "Suction-cup electrocardiogram tag attached to a free-swimming whale, published in a peer-reviewed physiology journal.",
    source: { title: "Goldbogen et al., \"Extreme bradycardia and tachycardia in the world's largest animal,\" Proceedings of the National Academy of Sciences (2019)", url: "https://www.pnas.org/doi/10.1073/pnas.1914273116", date: "2019-11-25", location: "Monterey Bay, California, USA" },
  },
  {
    registryNumber: "LR-HUMMINGBIRD-FASTEST-HEART-RATE", slug: "fastest-heart-rate-of-any-animal", title: "Fastest heart rate of any animal",
    subcategory: "Ornithology", direction: "MAXIMIZE",
    metricName: "Highest heart rate measured in a living animal during activity, beats per minute", unit: "bpm",
    formalStatement: "The highest heart rate directly measured in any living animal during normal activity.",
    summary: "Hummingbirds' hearts can beat over 1,200 times per minute during flight — the fastest heart rate of any animal — a necessity for sustaining the enormous energy demands of hovering flight, which also requires them to feed roughly every 10-15 minutes during the day.",
    value: "1200",
    methodSummary: "Electrocardiogram measurement of hummingbirds during flight, published in avian physiology research.",
    source: { title: "Cornell Lab of Ornithology — Hummingbird physiology", url: "https://www.allaboutbirds.org/", date: "2015-01-01", location: "Various hummingbird species, the Americas" },
  },
  {
    registryNumber: "LR-VIRGINIA-OPOSSUM-SHORTEST-GESTATION", slug: "shortest-gestation-period-mammal", title: "Shortest gestation period of any mammal",
    subcategory: "Mammalogy", direction: "MINIMIZE",
    metricName: "Gestation period of the mammal species with the shortest gestation", unit: "days",
    formalStatement: "The shortest confirmed gestation period of any mammal species.",
    summary: "The Virginia opossum has a gestation period of just 12-13 days — the shortest of any mammal — after which highly underdeveloped young crawl into the mother's pouch to continue developing externally, a strategy shared by marsupials generally.",
    value: "12",
    methodSummary: "Direct observation of captive breeding, per standard mammalogy reference literature.",
    source: { title: "Animal Diversity Web — Didelphis virginiana", url: "https://animaldiversity.org/accounts/Didelphis_virginiana/", date: "2003-01-01", location: "North America" },
  },
  {
    registryNumber: "LR-INLAND-TAIPAN-MOST-VENOMOUS-SNAKE", slug: "most-venomous-snake-by-ld50", title: "Most venomous snake by LD50",
    subcategory: "Herpetology", direction: "MINIMIZE",
    metricName: "Median lethal dose (LD50) of venom in mice, subcutaneous injection", unit: "mg/kg",
    formalStatement: "The lowest median lethal dose (LD50) of venom, per kilogram of body weight in mice via subcutaneous injection, of any snake species — the standard laboratory measure of venom toxicity.",
    summary: "The inland taipan (Oxyuranus microlepidotus) of central Australia has a venom LD50 of approximately 0.025 mg/kg in mice — the most toxic venom of any snake species by this standard laboratory measure, though it is a shy, reclusive snake responsible for very few human bites.",
    value: "0.025",
    methodSummary: "Standard subcutaneous LD50 toxicology testing in laboratory mice, per herpetological toxicology literature.",
    source: { title: "Australian Venom Research Unit — Inland Taipan", url: "https://www.avru.org/", date: "2010-01-01", location: "Central Australia" },
  },
  {
    registryNumber: "LR-EMPEROR-PENGUIN-DEEPEST-DIVING-BIRD", slug: "deepest-diving-bird", title: "Deepest-diving bird",
    subcategory: "Ornithology", direction: "MAXIMIZE",
    metricName: "Deepest confirmed dive depth of any bird", unit: "m",
    formalStatement: "The greatest confirmed dive depth of any bird species.",
    summary: "Emperor penguins have been recorded diving to depths of at least 565 m in pursuit of prey — the deepest confirmed dive of any bird, aided by a slowed heart rate and specialized hemoglobin that stores extra oxygen.",
    value: "565",
    methodSummary: "Depth-recording tags attached to wild emperor penguins, published in peer-reviewed polar biology research.",
    source: { title: "Wienecke et al., \"Extreme dives by free-ranging emperor penguins,\" Polar Biology (2007)", url: "https://link.springer.com/article/10.1007/s00300-006-0182-y", date: "2007-01-01", location: "Antarctica" },
  },
  {
    registryNumber: "LR-RED-BILLED-QUELEA-MOST-NUMEROUS-BIRD", slug: "most-numerous-wild-bird-species", title: "Most numerous wild bird species",
    subcategory: "Ornithology", direction: "MAXIMIZE",
    metricName: "Estimated total wild population of the most numerous bird species", unit: "individuals",
    formalStatement: "The greatest estimated total wild population of any bird species.",
    summary: "The red-billed quelea (Quelea quelea), a small finch native to sub-Saharan Africa, has an estimated total population of around 1.5 billion individuals — the most numerous wild bird species on Earth, forming immense flocks that are considered a major agricultural pest across the continent.",
    value: "1500000000",
    methodSummary: "Aerial and ground population surveys compiled by African agricultural and wildlife research organizations.",
    source: { title: "FAO — Quelea bird management", url: "https://www.fao.org/", date: "2010-01-01", location: "Sub-Saharan Africa" },
  },
  {
    registryNumber: "LR-SOLOMON-ISLANDS-LARGEST-CORAL-COLONY", slug: "largest-single-coral-colony", title: "Largest single coral colony",
    subcategory: "Marine Biology", direction: "MAXIMIZE",
    metricName: "Width of the largest known single coral colony", unit: "m",
    formalStatement: "The greatest width of any single coral colony confirmed to be one connected organism, as opposed to a broader reef system made of many separate colonies.",
    summary: "A mega coral colony of Pavona clavus, discovered in the Solomon Islands' Three Sisters island group in October 2024 by a National Geographic Pristine Seas expedition, measures 34 m wide and 32 m long — nearly three times larger than the previous record holder, 'Big Momma' in American Samoa — made of nearly a billion genetically identical coral polyps and estimated to be around 300 years old. It is large enough to be visible from space.",
    value: "34",
    methodSummary: "Underwater survey and photogrammetric mapping by marine biologists during a National Geographic Pristine Seas expedition.",
    source: { title: "National Geographic — Scientists discover world's largest coral", url: "https://www.nationalgeographic.com/environment/article/world-largest-coral-colony-discovery", date: "2024-11-14", location: "Three Sisters, Makira-Ulawa Province, Solomon Islands" },
  },
  {
    registryNumber: "LR-BEE-HUMMINGBIRD-SMALLEST-BIRD", slug: "smallest-bird-species", title: "Smallest bird species",
    subcategory: "Ornithology", direction: "MINIMIZE",
    metricName: "Body length of the smallest known bird species", unit: "cm",
    formalStatement: "The smallest confirmed adult body length of any bird species.",
    summary: "The bee hummingbird (Mellisuga helenae), found only in Cuba, measures just 5-6 cm long and weighs about 2 grams — the smallest bird species in the world, roughly the size and weight of a large bumblebee, which it resembles in flight.",
    value: "5.5",
    methodSummary: "Direct physical measurement of specimens, per ornithological field research.",
    source: { title: "American Bird Conservancy — Bee Hummingbird", url: "https://www.abcbirds.org/bird/bee-hummingbird/", date: "2020-01-01", location: "Cuba" },
  },
  {
    registryNumber: "LR-TUBE-LIPPED-BAT-LONGEST-TONGUE", slug: "longest-tongue-relative-to-body-size", title: "Longest tongue relative to body size",
    subcategory: "Mammalogy", direction: "MAXIMIZE",
    metricName: "Tongue length as a multiple of body length in the mammal with the longest relative tongue", unit: "×body length",
    formalStatement: "The greatest ratio of tongue length to body length confirmed for any mammal species.",
    summary: "The tube-lipped nectar bat (Anoura fistulata) of Ecuador has a tongue 1.5 times the length of its own body — the longest tongue relative to body size of any mammal — stored coiled inside its rib cage when not in use, extended to reach nectar deep inside long tubular flowers.",
    value: "1.5",
    methodSummary: "Direct physical measurement of captured specimens, published in a peer-reviewed zoology study.",
    source: { title: "Muchhala, \"Nectar bat stows huge tongue in its rib cage,\" Nature (2006)", url: "https://www.nature.com/articles/444701a", date: "2006-12-07", location: "Ecuador" },
  },
  {
    registryNumber: "LR-KOALA-MOST-SLEEP", slug: "mammal-that-sleeps-the-most", title: "Mammal that sleeps the most",
    subcategory: "Mammalogy", direction: "MAXIMIZE",
    metricName: "Average daily sleep duration of the mammal species that sleeps the most", unit: "hours",
    formalStatement: "The greatest average daily sleep duration confirmed for any mammal species.",
    summary: "Koalas sleep an average of 20-22 hours per day — more than almost any other mammal — largely because their diet of eucalyptus leaves is low in calories and difficult to digest, leaving little energy for anything but rest.",
    value: "21",
    methodSummary: "Behavioral observation studies of wild and captive koalas, per zoological research literature.",
    source: { title: "Australian Koala Foundation — Koala facts", url: "https://www.savethekoala.com/about-koalas/koala-facts/", date: "2020-01-01", location: "Eastern Australia" },
  },
  {
    registryNumber: "LR-SPERM-WHALE-LARGEST-BRAIN", slug: "largest-brain-by-absolute-mass", title: "Largest brain by absolute mass",
    subcategory: "Cetology", direction: "MAXIMIZE",
    metricName: "Mass of the largest known animal brain", unit: "kg",
    formalStatement: "The greatest absolute mass of any known animal's brain.",
    summary: "The sperm whale has the largest brain of any known animal, weighing up to 8 kg — about five times the mass of a human brain — though relative to its enormous body size, its brain-to-body ratio is lower than that of humans or dolphins.",
    value: "8",
    methodSummary: "Direct dissection and weighing of stranded and harvested specimens, per cetology reference literature.",
    source: { title: "Marino, \"Cetacean brain evolution,\" International Society for Comparative Psychology (2004)", url: "https://escholarship.org/uc/item/3f4576kx", date: "2004-01-01", location: "Sperm whale populations, worldwide oceans" },
  },
  {
    registryNumber: "LR-GENTOO-PENGUIN-FASTEST-SWIMMING-BIRD", slug: "fastest-swimming-bird", title: "Fastest-swimming bird",
    subcategory: "Ornithology", direction: "MAXIMIZE",
    metricName: "Fastest sustained underwater swimming speed measured for a bird", unit: "km/h",
    formalStatement: "The fastest sustained underwater swimming speed directly measured for any bird species.",
    summary: "Gentoo penguins have been recorded swimming at sustained speeds up to 36 km/h (22 mph) underwater — the fastest of any bird species — using their flipper-like wings for propulsion in a style of swimming sometimes called 'flying through water.'",
    value: "36",
    methodSummary: "Speed tracking via attached data loggers on wild penguins, published in marine biology research.",
    source: { title: "British Antarctic Survey — Gentoo Penguin", url: "https://www.bas.ac.uk/", date: "2015-01-01", location: "Sub-Antarctic islands" },
  },
  {
    registryNumber: "LR-WILDEBEEST-LARGEST-MAMMAL-MIGRATION", slug: "largest-migration-of-a-single-mammal-species", title: "Largest migration of a single mammal species",
    subcategory: "Animal Locomotion", direction: "MAXIMIZE",
    metricName: "Estimated number of individuals in the largest annual mammal migration", unit: "individuals",
    formalStatement: "The greatest estimated number of individual animals participating in a single recurring annual mammal migration.",
    summary: "The Serengeti-Mara wildebeest migration involves an estimated 1.5 million blue wildebeest, along with hundreds of thousands of zebra and gazelle, moving in a roughly circular route across Tanzania and Kenya each year in search of fresh grazing — the largest overland migration of mammals on Earth by number of individuals.",
    value: "1500000",
    methodSummary: "Aerial population census surveys conducted by Tanzanian and Kenyan wildlife authorities.",
    source: { title: "Serengeti National Park — The Great Migration", url: "https://www.serengeti.org/", date: "2020-01-01", location: "Serengeti-Mara ecosystem, Tanzania and Kenya" },
  },
  {
    registryNumber: "LR-KORI-BUSTARD-HEAVIEST-FLYING-BIRD", slug: "heaviest-flying-bird", title: "Heaviest flying bird",
    subcategory: "Ornithology", direction: "MAXIMIZE",
    metricName: "Body mass of the heaviest bird confirmed capable of powered flight", unit: "kg",
    formalStatement: "The greatest confirmed body mass of any bird species still capable of powered flight.",
    summary: "The kori bustard (Ardeotis kori), found across eastern and southern Africa, can weigh up to 19 kg — the heaviest bird confirmed capable of flight, though males at the upper end of this weight range fly only reluctantly and prefer to walk or run when possible.",
    value: "19",
    methodSummary: "Direct weight measurement of captured specimens, per ornithological field research.",
    source: { title: "Guinness World Records — Heaviest flying bird", url: "https://www.guinnessworldrecords.com/world-records/heaviest-flying-bird", date: "2020-01-01", location: "Eastern and southern Africa" },
  },
  {
    registryNumber: "LR-GREAT-POND-SNAIL-MOST-TEETH", slug: "animal-with-the-most-teeth", title: "Animal with the most teeth",
    subcategory: "Malacology", direction: "MAXIMIZE",
    metricName: "Number of teeth on the radula of the animal species with the most", unit: "teeth",
    formalStatement: "The greatest number of teeth confirmed for any animal species, counting the rows of microscopic teeth on a snail's radula (feeding organ).",
    summary: "The great pond snail (Lymnaea stagnalis) has a radula (a ribbon-like feeding structure) covered in as many as 20,000-plus microscopic teeth arranged in rows — more individual teeth than any other animal, continuously worn down and regrown as the snail feeds by scraping algae off surfaces.",
    value: "20000",
    methodSummary: "Scanning electron microscope examination of the radula, published in malacology research literature.",
    source: { title: "Natural History Museum, London — Snail radula facts", url: "https://www.nhm.ac.uk/", date: "2018-01-01", location: "Freshwater habitats, Europe and Asia" },
  },
  {
    registryNumber: "LR-COCONUT-CRAB-LARGEST-ARTHROPOD", slug: "largest-terrestrial-arthropod", title: "Largest land-living arthropod",
    subcategory: "Carcinology", direction: "MAXIMIZE",
    metricName: "Leg span of the largest known land-living arthropod species", unit: "m",
    formalStatement: "The greatest leg span confirmed for any arthropod species that lives on land as an adult.",
    summary: "The coconut crab (Birgus latro), found on islands across the Indian and Pacific Oceans, can have a leg span of up to 1 m and weigh up to 4 kg — the largest land-living arthropod in the world, strong enough to crack open coconuts with its claws, which is how it gets its name.",
    value: "1",
    methodSummary: "Direct physical measurement of wild specimens, per carcinological field research.",
    source: { title: "Smithsonian Ocean — Coconut Crab", url: "https://ocean.si.edu/ocean-life/invertebrates/coconut-crabs-gentle-giants", date: "2018-01-01", location: "Indian and Pacific Ocean islands" },
  },
  {
    registryNumber: "LR-HUMMINGBIRD-FASTEST-WINGBEAT", slug: "fastest-wingbeat-of-any-bird", title: "Fastest wingbeat of any bird",
    subcategory: "Ornithology", direction: "MAXIMIZE",
    metricName: "Highest wingbeat frequency measured for a bird during courtship display", unit: "beats/sec",
    formalStatement: "The highest wingbeat frequency directly measured for any bird species, during its fastest recorded behavior (courtship display flight).",
    summary: "Some hummingbird species, including certain Anna's hummingbirds during high-speed courtship dives, have been recorded beating their wings up to roughly 80 times per second — the fastest wingbeat frequency of any bird, compared to about 50 times per second during normal hovering flight.",
    value: "80",
    methodSummary: "High-speed video analysis of courtship display flights, published in avian biomechanics research.",
    source: { title: "Clark, \"Wing, tail, and vocal contributions to the complex acoustic signals of courting Calliope hummingbirds,\" Current Zoology (2014)", url: "https://academic.oup.com/cz/article/60/1/104/1806142", date: "2014-01-01", location: "Western North America" },
  },
  {
    registryNumber: "LR-EMPEROR-PENGUIN-LONGEST-FAST", slug: "longest-fasting-period-survived-by-an-animal", title: "Longest fasting period survived by a bird",
    subcategory: "Ornithology", direction: "MAXIMIZE",
    metricName: "Longest period an animal has been observed surviving without food", unit: "days",
    formalStatement: "The longest confirmed period a male emperor penguin survives without feeding while incubating an egg through the Antarctic winter.",
    summary: "Male emperor penguins fast for up to 115-120 days (roughly 4 months) while incubating a single egg on their feet through the Antarctic winter, surviving entirely on stored fat reserves and losing up to 45% of their body weight before their mate returns to relieve them.",
    value: "120",
    methodSummary: "Long-term field observation of breeding colonies, per polar biology research literature.",
    source: { title: "British Antarctic Survey — Emperor Penguin breeding cycle", url: "https://www.bas.ac.uk/", date: "2018-01-01", location: "Antarctica" },
  },
  {
    registryNumber: "LR-VALONIA-LARGEST-SINGLE-CELL", slug: "largest-single-celled-organism", title: "Largest single-celled organism",
    subcategory: "Botany", direction: "MAXIMIZE",
    metricName: "Diameter of the largest known single-celled organism", unit: "cm",
    formalStatement: "The greatest diameter confirmed for any single-celled organism, visible without magnification.",
    summary: "Valonia ventricosa, a species of algae nicknamed 'sailor's eyeball,' forms a single cell that can reach up to 4 cm in diameter — among the largest single-celled organisms known, visible to the naked eye despite being just one cell, found attached to rocks and coral in shallow tropical waters.",
    value: "4",
    methodSummary: "Direct physical measurement of specimens, per marine botany reference literature.",
    source: { title: "Smithsonian Marine Station — Valonia ventricosa", url: "https://naturalhistory2.si.edu/smsfp/irlspec/Valonia_ventric.htm", date: "2015-01-01", location: "Tropical and subtropical oceans worldwide" },
  },
  {
    registryNumber: "LR-ALPINE-SWIFT-LONGEST-CONTINUOUS-FLIGHT", slug: "longest-continuous-time-airborne-by-a-bird", title: "Longest continuous time airborne by a bird",
    subcategory: "Ornithology", direction: "MAXIMIZE",
    metricName: "Longest confirmed period a bird has remained continuously airborne without landing", unit: "days",
    formalStatement: "The longest confirmed period a bird has been tracked remaining continuously airborne, including sleeping in flight, without landing.",
    summary: "A 2013 tracking study found that common swifts (Apus apus, the same species that holds the level-flight speed record) can remain continuously airborne for up to 10 months at a stretch outside the breeding season, landing only to nest — among the longest confirmed continuous flight periods of any bird, with the animal apparently able to sleep in short bursts while gliding.",
    value: "300",
    methodSummary: "Miniature activity-logging tags attached to wild swifts, published in a peer-reviewed ornithology journal.",
    source: { title: "Hedenström et al., \"Annual 10-Month Aerial Life Phase in the Common Swift,\" Current Biology (2016)", url: "https://www.cell.com/current-biology/fulltext/S0960-9822(16)30913-6", date: "2016-10-27", location: "Sweden (tracked individuals)" },
  },
];

// Fills in the existing LR-DRAFT-BIO-18 stub (title already reserved as "Cheetah sprint speed")
// with real, sourced content rather than creating a new registry number.
export const CHEETAH_SPEED_UPDATE = {
  registryNumber: "LR-DRAFT-BIO-18",
  subcategory: "Animal Locomotion",
  direction: "MAXIMIZE" as const,
  metricName: "Peak recorded running speed (Acinonyx jubatus, timed run)",
  unit: "km/h",
  formalStatement: "The fastest instantaneous running speed recorded for a cheetah (Acinonyx jubatus) on a measured, timed course.",
  summary: "Sarah, a cheetah at the Cincinnati Zoo, ran a certified 100-meter course in 5.95 seconds on June 20, 2012, with an instantaneous top speed clocked at 61 mph (98.2 km/h) — faster than her own previous record of 6.13 seconds set in 2009. It remains the most-cited record for the fastest confirmed speed of any land animal.",
  value: "98.2",
  methodSummary: "Timed on a course certified by the Road Running Technical Council of USA Track & Field; instantaneous top speed measured during the run, not the 100 m average pace.",
  source: { title: "Cincinnati Zoo cheetah speed record", url: "https://cincinnatizoo.org/cincinnati-zoo-cheetah-sets-new-world-speed-record/", date: "2012-06-20", location: "Cincinnati Zoo & Botanical Garden, Ohio, USA" },
};
