export type MathClaim = { relation: "=" | ">=" | "<="; value: string; claimType: "EXACT_VALUE" | "LOWER_BOUND" | "UPPER_BOUND"; summary: string };
export type MathSource = { title: string; url: string; date: string; venue: string; doi?: string; location: string };
export type MathematicsRecord = { registryNumber: string; title: string; slug: string; summary: string; subcategory: string; direction: "MINIMIZE" | "MAXIMIZE"; metricName: string; unit: string; formalStatement: string; constraints: Record<string, unknown>; status: "OPEN" | "PROVEN"; claims: MathClaim[]; source: MathSource };
const slugify = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
const survey: MathSource = { title: "Small Ramsey Numbers, revision 18", url: "https://www.combinatorics.org/ojs/index.php/eljc/article/view/DS1", date: "2026-04-24", venue: "Electronic Journal of Combinatorics, Dynamic Surveys", doi: "10.37236/21", location: "Sections 2.1 and 6.1; Tables Ia and Ib" };
const kissingSurvey: MathSource = { title: "Kissing Numbers, Sphere Packings, and Some Unexpected Proofs", url: "https://www.ams.org/journals/notices/200408/200408FullIssue.pdf", date: "2004-09-01", venue: "Notices of the American Mathematical Society", location: "Status table and Delsarte-method discussion" };
const ramsey = (index: number, a: number, b: number, lower: number, upper = lower): MathematicsRecord => ({ registryNumber: `LR-${String(3100 + index).padStart(6, "0")}`, title: `Ramsey number R(${a},${b})`, slug: `ramsey-number-r-${a}-${b}`, summary: lower === upper ? `The exact two-color Ramsey number R(${a},${b}) is ${lower}.` : `The current verified interval for the open Ramsey number R(${a},${b}) is ${lower}–${upper}.`, subcategory: "Ramsey theory", direction: "MINIMIZE", metricName: `R(${a},${b})`, unit: "vertices", formalStatement: `Determine the least n such that every red-blue edge coloring of K_n contains a red K_${a} or a blue K_${b}.`, constraints: { colors: 2, avoidedRedCliqueOrder: a, avoidedBlueCliqueOrder: b, graph: "complete", induced: false, surveyRevision: 18 }, status: lower === upper ? "PROVEN" : "OPEN", claims: lower === upper ? [{ relation: "=", value: String(lower), claimType: "EXACT_VALUE", summary: `Matching construction and impossibility results establish R(${a},${b}) = ${lower}.` }] : [{ relation: ">=", value: String(lower), claimType: "LOWER_BOUND", summary: `A coloring on ${lower - 1} vertices avoids both forbidden monochromatic cliques.` }, { relation: "<=", value: String(upper), claimType: "UPPER_BOUND", summary: `Every coloring on ${upper} vertices contains one of the forbidden monochromatic cliques.` }], source: survey });
const exact = (index: number, fields: Omit<MathematicsRecord, "registryNumber" | "slug" | "status" | "claims"> & { value: string; proof: string }): MathematicsRecord => ({ ...fields, registryNumber: `LR-${String(3100 + index).padStart(6, "0")}`, slug: slugify(fields.title), status: "PROVEN", claims: [{ relation: "=", value: fields.value, claimType: "EXACT_VALUE", summary: fields.proof }] });
export const mathematicsFoundationRecords: MathematicsRecord[] = [
  ramsey(0,3,3,6), ramsey(1,3,4,9), ramsey(2,3,5,14), ramsey(3,3,6,18), ramsey(4,3,7,23), ramsey(5,3,8,28), ramsey(6,3,9,36), ramsey(7,4,4,18), ramsey(8,4,5,25), ramsey(9,4,6,36,40), ramsey(10,5,5,43,46),
  exact(11, { title: "Three-color Ramsey number R(3,3,3)", summary: "The exact three-color triangle Ramsey number is 17.", subcategory: "Ramsey theory", direction: "MINIMIZE", metricName: "R(3,3,3)", unit: "vertices", formalStatement: "Determine the least n such that every three-coloring of the edges of K_n contains a monochromatic triangle.", constraints: { colors: 3, cliqueOrder: 3, graph: "complete", induced: false, surveyRevision: 18 }, value: "17", proof: "Greenwood and Gleason's matching bounds establish R(3,3,3) = 17.", source: survey }),
  ...([[12,1,"2"],[13,2,"6"],[14,3,"12"],[15,4,"24"],[16,8,"240"],[17,24,"196560"]] as const).map(([index,dimension,value]) => exact(index, { title: `Kissing number in ${dimension === 1 ? "one dimension" : dimension === 2 ? "two dimensions" : dimension === 3 ? "three dimensions" : dimension === 4 ? "four dimensions" : `${dimension} dimensions`}`, summary: `The exact Euclidean kissing number in dimension ${dimension} is ${value}.`, subcategory: "Discrete geometry / kissing numbers", direction: "MAXIMIZE", metricName: `k(${dimension})`, unit: "spheres", formalStatement: `Determine the maximum number of nonoverlapping unit spheres in R^${dimension} that can simultaneously touch a central unit sphere.`, constraints: { dimension, sphereRadius: 1, ambientSpace: `Euclidean R^${dimension}`, interiorsDisjoint: true, tangencyToCentralSphere: true }, value, proof: `Matching construction and upper-bound proof establish k(${dimension}) = ${value}.`, source: dimension === 4 ? { title: "The kissing number in four dimensions", url: "https://annals.math.princeton.edu/wp-content/uploads/annals-v168-n1-p01.pdf", date: "2008-07-01", venue: "Annals of Mathematics", doi: "10.4007/annals.2008.168.1", location: "Main theorem" } : kissingSurvey })),
  exact(18, { title: "Optimal sphere packing in dimension 2", summary: "The hexagonal packing is the densest congruent-circle packing in the Euclidean plane.", subcategory: "Discrete geometry / sphere packing", direction: "MAXIMIZE", metricName: "packing density", unit: "dimensionless", formalStatement: "Determine the supremum density of packings of congruent circles in the Euclidean plane.", constraints: { dimension: 2, ambientSpace: "Euclidean R^2", congruentBalls: true, densityDefinition: "upper asymptotic density" }, value: "pi/sqrt(12)", proof: "The hexagonal packing attains the matching optimal density pi/sqrt(12).", source: { title: "Über die dichteste Zusammenstellung von kongruenten Kreisen in einer Ebene", url: "https://eudml.org/doc/157093", date: "1910-01-01", venue: "Christiania Videnskabs-Selskabets Skrifter", location: "Main theorem" } }),
  exact(19, { title: "Optimal sphere packing in eight dimensions", summary: "The E8 lattice packing is optimal among all congruent-sphere packings in R^8.", subcategory: "Discrete geometry / sphere packing", direction: "MAXIMIZE", metricName: "packing density", unit: "dimensionless", formalStatement: "Determine the supremum density of packings of congruent balls in Euclidean R^8.", constraints: { dimension: 8, ambientSpace: "Euclidean R^8", congruentBalls: true, densityDefinition: "upper asymptotic density" }, value: "pi^4/384", proof: "Viazovska proved that no packing exceeds the E8 lattice packing density.", source: { title: "The sphere packing problem in dimension 8", url: "https://annals.math.princeton.edu/2017/185-3/p07", date: "2017-04-12", venue: "Annals of Mathematics", doi: "10.4007/annals.2017.185.3.7", location: "Main theorem" } }),
  exact(20, { title: "Optimal sphere packing in dimension 24", summary: "The Leech lattice packing is optimal among all congruent-sphere packings in R^24.", subcategory: "Discrete geometry / sphere packing", direction: "MAXIMIZE", metricName: "packing density", unit: "dimensionless", formalStatement: "Determine the supremum density of packings of congruent balls in Euclidean R^24.", constraints: { dimension: 24, ambientSpace: "Euclidean R^24", congruentBalls: true, densityDefinition: "upper asymptotic density" }, value: "pi^12/12!", proof: "Cohn, Kumar, Miller, Radchenko, and Viazovska proved that no packing exceeds the Leech lattice packing density.", source: { title: "The sphere packing problem in dimension 24", url: "https://annals.math.princeton.edu/2017/185-3/p08", date: "2017-04-12", venue: "Annals of Mathematics", doi: "10.4007/annals.2017.185.3.8", location: "Main theorem" } }),
];
