export type NetworkingRfcRecord = { registryNumber: string; slug: string; title: string; summary: string; direction: "MINIMIZE" | "MAXIMIZE"; metricName: string; unit: string; value: string; formalStatement: string; constraints: Record<string, unknown>; rfc: number; sourceTitle: string; sourceUrl: string; sourceDate: string; location: string };
type Input = Omit<NetworkingRfcRecord, "registryNumber" | "slug" | "summary" | "formalStatement" | "sourceUrl"> & { title: string; scope: string; note?: string };
const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
const define = (index: number, input: Input): NetworkingRfcRecord => ({ ...input, registryNumber: `LR-${String(3000 + index).padStart(6, "0")}`, slug: slugify(input.title), summary: `${input.title} is ${input.value} ${input.unit} under ${input.scope}.${input.note ? ` ${input.note}` : ""}`, formalStatement: `Under ${input.scope}, what exact standards-defined value applies to ${input.metricName}?`, sourceUrl: `https://www.rfc-editor.org/rfc/rfc${input.rfc}.html` });
const MAX = "MAXIMIZE" as const, MIN = "MINIMIZE" as const;
const tcp = { rfc: 9293, sourceTitle: "Transmission Control Protocol (TCP)", sourceDate: "2022-08-01" };
const quic = { rfc: 9000, sourceTitle: "QUIC: A UDP-Based Multiplexed and Secure Transport", sourceDate: "2021-05-01" };
/** Exact, versioned protocol limits sourced directly from authoritative IETF RFCs. */
export const networkingRfcRecords: NetworkingRfcRecord[] = [
  define(0, { title: "Maximum ordinary UDP payload over IPv4", direction: MAX, metricName: "UDP payload length", unit: "bytes", value: "65507", scope: "UDP over IPv4 with a 20-byte IPv4 header and 8-byte UDP header", note: "IPv4 options are excluded.", constraints: { protocol: "UDP over IPv4", ipv4HeaderBytes: 20, udpHeaderBytes: 8, excludes: ["IPv4 options", "application-layer fragmentation"] }, rfc: 8085, sourceTitle: "UDP Usage Guidelines", sourceDate: "2017-03-01", location: "Introduction, UDP payload maxima" }),
  define(1, { title: "Maximum ordinary UDP payload over IPv6", direction: MAX, metricName: "UDP payload length", unit: "bytes", value: "65527", scope: "ordinary UDP over IPv6 with an 8-byte UDP header", note: "IPv6 jumbograms and extension-header overhead are excluded.", constraints: { protocol: "UDP over IPv6", udpHeaderBytes: 8, excludes: ["IPv6 jumbograms", "extension-header overhead"] }, rfc: 8085, sourceTitle: "UDP Usage Guidelines", sourceDate: "2017-03-01", location: "Introduction, UDP payload maxima" }),
  define(2, { title: "UDP length-field width", direction: MAX, metricName: "UDP Length field width", unit: "bits", value: "16", scope: "the RFC 768 UDP header", note: "The encoded length includes the eight-byte UDP header.", constraints: { protocol: "UDP", field: "Length", includesHeader: true, minimumEncodedValue: 8 }, rfc: 768, sourceTitle: "User Datagram Protocol", sourceDate: "1980-08-28", location: "Header format and Fields" }),
  define(3, { title: "TCP source-port field width", direction: MAX, metricName: "Source Port field width", unit: "bits", value: "16", scope: "the RFC 9293 TCP header", constraints: { protocol: "TCP", field: "Source Port" }, ...tcp, location: "Section 3.1, Header Format" }),
  define(4, { title: "TCP destination-port field width", direction: MAX, metricName: "Destination Port field width", unit: "bits", value: "16", scope: "the RFC 9293 TCP header", constraints: { protocol: "TCP", field: "Destination Port" }, ...tcp, location: "Section 3.1, Header Format" }),
  define(5, { title: "TCP sequence-number field width", direction: MAX, metricName: "Sequence Number field width", unit: "bits", value: "32", scope: "the RFC 9293 TCP header", constraints: { protocol: "TCP", field: "Sequence Number" }, ...tcp, location: "Section 3.1, Header Format" }),
  define(6, { title: "TCP acknowledgment-number field width", direction: MAX, metricName: "Acknowledgment Number field width", unit: "bits", value: "32", scope: "the RFC 9293 TCP header", constraints: { protocol: "TCP", field: "Acknowledgment Number" }, ...tcp, location: "Section 3.1, Header Format" }),
  define(7, { title: "TCP receive-window field width", direction: MAX, metricName: "base Window field width", unit: "bits", value: "16", scope: "the unscaled RFC 9293 TCP header", note: "The RFC 7323 Window Scale extension is excluded.", constraints: { protocol: "TCP", field: "Window", excludes: ["RFC 7323 Window Scale option"] }, ...tcp, location: "Section 3.1, Header Format" }),
  define(8, { title: "TCP checksum field width", direction: MAX, metricName: "Checksum field width", unit: "bits", value: "16", scope: "the RFC 9293 TCP header", constraints: { protocol: "TCP", field: "Checksum" }, ...tcp, location: "Section 3.1, Checksum" }),
  define(9, { title: "TCP MSS value-field width", direction: MAX, metricName: "MSS value-field width", unit: "bits", value: "16", scope: "the mandatory four-byte RFC 9293 TCP MSS option", constraints: { protocol: "TCP", optionKind: 2, totalOptionBytes: 4, valueBytes: 2 }, ...tcp, location: "Section 3.2, Maximum Segment Size Option" }),
  define(10, { title: "Default TCP MSS for IPv4", direction: MAX, metricName: "default send MSS", unit: "bytes", value: "536", scope: "RFC 9293 TCP over IPv4 when no MSS option is received", note: "The value is derived as 576 minus 40 header bytes.", constraints: { protocol: "TCP over IPv4", condition: "No MSS option received", derivation: "576 - 40" }, ...tcp, location: "Section 3.7.1, Maximum Segment Size Option" }),
  define(11, { title: "Default TCP MSS for IPv6", direction: MAX, metricName: "default send MSS", unit: "bytes", value: "1220", scope: "RFC 9293 TCP over IPv6 when no MSS option is received", note: "The value is derived as 1280 minus 60 header bytes.", constraints: { protocol: "TCP over IPv6", condition: "No MSS option received", derivation: "1280 - 60" }, ...tcp, location: "Section 3.7.1, Maximum Segment Size Option" }),
  define(12, { title: "IPv4 total-length field maximum", direction: MAX, metricName: "complete IPv4 datagram length", unit: "bytes", value: "65535", scope: "the RFC 791 16-bit Total Length field", note: "The value includes the IPv4 header and payload.", constraints: { protocol: "IPv4", field: "Total Length", fieldWidthBits: 16, includes: ["IPv4 header", "payload"] }, rfc: 791, sourceTitle: "Internet Protocol", sourceDate: "1981-09-01", location: "Section 3.1, Total Length" }),
  define(13, { title: "IPv6 minimum link MTU", direction: MIN, metricName: "link MTU", unit: "bytes", value: "1280", scope: "RFC 8200 IPv6 links", note: "Links unable to convey it in one piece must provide lower-layer fragmentation and reassembly.", constraints: { protocol: "IPv6", lowerLayerFragmentationRequiredBelow: 1280 }, rfc: 8200, sourceTitle: "Internet Protocol, Version 6 (IPv6) Specification", sourceDate: "2017-07-01", location: "Section 5, Packet Size Issues" }),
  define(14, { title: "IPv6 jumbo-payload length maximum", direction: MAX, metricName: "IPv6 jumbo payload length", unit: "bytes", value: "4294967295", scope: "the RFC 2675 32-bit Jumbo Payload option", note: "Jumbograms begin at 65,536 bytes.", constraints: { protocol: "IPv6", extension: "Jumbo Payload option", fieldWidthBits: 32, minimumJumbogramPayload: 65536 }, rfc: 2675, sourceTitle: "IPv6 Jumbograms", sourceDate: "1999-08-01", location: "Abstract and Section 2" }),
  define(15, { title: "QUIC minimum supported datagram size", direction: MIN, metricName: "supported UDP payload", unit: "bytes", value: "1200", scope: "a network path carrying QUIC version 1", note: "This is UDP payload size, excluding IP and UDP headers.", constraints: { protocol: "QUIC version 1", layer: "UDP payload", excludes: ["IP header", "UDP header"] }, ...quic, location: "Section 14, Datagram Size" }),
  define(16, { title: "QUIC variable-length integer maximum", direction: MAX, metricName: "encoded integer", unit: "dimensionless", value: "4611686018427387903", scope: "the QUIC version 1 variable-length integer format", note: "Eight-byte encodings contain 62 usable value bits.", constraints: { protocol: "QUIC version 1", encodingBytes: [1, 2, 4, 8], maximumUsableBits: 62, formula: "2^62 - 1" }, ...quic, location: "Section 16, Variable-Length Integer Encoding" }),
  define(17, { title: "QUIC v1 connection-ID maximum length", direction: MAX, metricName: "connection-ID length", unit: "bytes", value: "20", scope: "Source and Destination Connection IDs in a QUIC version 1 long header", constraints: { protocol: "QUIC version 1", fields: ["Destination Connection ID", "Source Connection ID"], headerForm: "long" }, ...quic, location: "Section 17.2, Long Header Packets" }),
  define(18, { title: "QUIC stateless-reset-token length", direction: MAX, metricName: "token length", unit: "bytes", value: "16", scope: "a QUIC version 1 stateless reset token", constraints: { protocol: "QUIC version 1", field: "stateless_reset_token" }, ...quic, location: "Sections 10.3 and 18.2" }),
  define(19, { title: "QUIC default maximum UDP payload", direction: MAX, metricName: "default receive UDP payload limit", unit: "bytes", value: "65527", scope: "the omitted QUIC version 1 max_udp_payload_size transport parameter", note: "This endpoint receive limit is not a path MTU, and values below 1,200 are invalid.", constraints: { protocol: "QUIC version 1", parameter: "max_udp_payload_size", invalidBelow: 1200, distinction: "Endpoint receive limit, not a path MTU" }, ...quic, location: "Section 18.2, Transport Parameter Definitions" }),
  define(20, { title: "DNS-over-UDP historical message-size limit", direction: MAX, metricName: "DNS message length", unit: "bytes", value: "512", scope: "original RFC 1035 DNS over UDP", note: "The historical limit excludes IP and UDP headers and predates EDNS.", constraints: { protocol: "DNS over UDP", historical: true, excludes: ["IP header", "UDP header", "EDNS extensions"] }, rfc: 1035, sourceTitle: "Domain Names — Implementation and Specification", sourceDate: "1987-11-01", location: "Section 4.2.1, UDP usage" }),
];
