import type { FrontierRecord } from "./frontier-records-2026";

// New category: "Speed Records" — real, source-verified "fastest machine" records that don't
// belong under an existing science category (car/train/coaster/human-powered vehicle), each
// checked against the single authoritative certifying body for that record (FIA, Guinness World
// Records, the ride manufacturer/operator, or the IHPVA) as of 2026-09-20. A "fastest production
// car" entry was considered and dropped: Bugatti's 304.773 mph run (2019) was single-direction
// only, while stricter two-way-average rules recognize a different, separately disputed record
// holder — there is no single clean, uncontested number to cite, the same reason a couple of
// topics were dropped from the original FRONTIER_RECORDS_2026 batch.
export const SPEED_RECORDS: FrontierRecord[] = [
  {
    registryNumber: "LR-LAND-SPEED-RECORD", slug: "land-speed-record", title: "Outright land speed record",
    category: "Speed Records", subcategory: "Land vehicles", direction: "MAXIMIZE",
    metricName: "Speed of a wheeled land vehicle, two-way average over a measured mile", unit: "mph",
    formalStatement: "The highest speed achieved by a wheeled land vehicle, as a two-way average over a measured distance, certified by the FIA as the outright World Land Speed Record.",
    summary: "ThrustSSC, a British jet-powered car driven by Andy Green, reached 763.035 mph (1,227.985 km/h) over a measured mile on October 15, 1997 at Black Rock Desert, Nevada — the first supersonic land speed record (Mach 1.016). It remains unbroken as of 2026; the successor Bloodhound LSR project never completed a record attempt.",
    value: "763.035",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Certified by the FIA (Fédération Internationale de l'Automobile) via two-way average speed over a measured mile, per official land speed record rules.",
    source: { title: "FIA World Land Speed Records", url: "https://www.fia.com/fia-world-land-speed-records", date: "1997-10-15", location: "Black Rock Desert, Nevada, USA" },
  },
  {
    registryNumber: "LR-MAGLEV-TRAIN-SPEED", slug: "maglev-train-speed", title: "Fastest train (any type)",
    category: "Speed Records", subcategory: "Rail", direction: "MAXIMIZE",
    metricName: "Highest speed achieved by a manned rail vehicle", unit: "km/h",
    formalStatement: "The highest speed achieved by a manned rail vehicle of any kind — wheeled or magnetically levitated — as certified by Guinness World Records.",
    summary: "Central Japan Railway's L0 Series superconducting maglev train reached 603 km/h (374.7 mph) on the Yamanashi Maglev Test Line on April 21, 2015 — the fastest any train has ever traveled. The line remains a test track as of 2026; commercial Chūō Shinkansen service using this technology is planned at a lower 500 km/h operating speed once launched.",
    value: "603",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Measured on JR Central's dedicated Yamanashi test track and certified as a Guinness World Record.",
    source: { title: "Fastest maglev train — Guinness World Records", url: "https://www.guinnessworldrecords.com/world-records/fastest-maglev-train", date: "2015-04-21", location: "Yamanashi Maglev Test Line, Yamanashi, Japan" },
  },
  {
    registryNumber: "LR-FASTEST-ROLLER-COASTER", slug: "fastest-roller-coaster", title: "Fastest roller coaster",
    category: "Speed Records", subcategory: "Amusement rides", direction: "MAXIMIZE",
    metricName: "Top speed reached by a roller coaster", unit: "km/h",
    formalStatement: "The highest top speed reached by any operating roller coaster.",
    summary: "Falcon's Flight, an Intamin LSM-launched steel coaster at Six Flags Qiddiya City (Saudi Arabia), reached a top speed of 250 km/h (155.3 mph) on opening December 31, 2025 — also the tallest (195 m) and longest (4,325 m) roller coaster in the world. It surpassed Formula Rossa's 240 km/h record, which had stood since 2010.",
    value: "250",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Manufacturer-published ride specifications, corroborated by independent theme-park press coverage at opening.",
    source: { title: "Intamin — Falcon's Flight, Six Flags Qiddiya City", url: "https://www.intamin.com/2026/01/15/six-flags-qiddiya-city-falcons-flight/", date: "2025-12-31", location: "Six Flags Qiddiya City, Al-Qiddiya, Saudi Arabia" },
  },
  {
    registryNumber: "LR-HUMAN-POWERED-VEHICLE-SPEED", slug: "human-powered-vehicle-speed", title: "Fastest human-powered vehicle",
    category: "Speed Records", subcategory: "Human-powered vehicles", direction: "MAXIMIZE",
    metricName: "Speed of a human-powered vehicle, flying-start 200 m", unit: "km/h",
    formalStatement: "The highest speed achieved by a vehicle powered solely by human effort — no motor, no motor-paced draft — over a flying-start 200-meter course, sanctioned by the IHPVA.",
    summary: "Todd Reichert reached 144.17 km/h (89.59 mph) pedaling AeroVelo's fully-faired recumbent bicycle Eta at the World Human Powered Speed Challenge in Battle Mountain, Nevada, on September 17, 2016 — still the record as of 2026, a rare case where a human on a bicycle outruns most cars on a highway.",
    value: "144.17",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Timed over a flying-start 200 m course and sanctioned by the International Human Powered Vehicle Association (IHPVA).",
    source: { title: "World Human Powered Speed Challenge — competition records", url: "http://www.whpva.org/competition.html", date: "2016-09-17", location: "Battle Mountain, Nevada, USA" },
  },
  {
    registryNumber: "LR-APOLLO-10-REENTRY-SPEED", slug: "fastest-speed-traveled-by-humans", title: "Fastest speed ever traveled by humans",
    category: "Speed Records", subcategory: "Human spaceflight", direction: "MAXIMIZE",
    metricName: "Speed of a crewed vehicle relative to Earth", unit: "km/h",
    formalStatement: "The highest speed relative to Earth ever attained by a crewed vehicle.",
    summary: "Apollo 10 astronauts Thomas Stafford, John Young, and Gene Cernan reached 39,897 km/h (24,791 mph) relative to Earth on May 26, 1969, during their high-speed return trajectory from the Moon — the fastest any humans have ever traveled. No later crewed mission, including the Moon-landing flights that followed it, has matched or exceeded it.",
    value: "39897",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Tracked via NASA mission telemetry during Apollo 10's translunar return; the figure is NASA's own official mission record.",
    source: { title: "NASA — 50 Years Ago: Apollo 10 Clears the Way for the First Moon Landing", url: "https://www.nasa.gov/history/50-years-ago-apollo-10-clears-the-way-for-the-first-moon-landing/", date: "1969-05-26", location: "Apollo 10 command module, translunar return trajectory" },
  },
  {
    registryNumber: "LR-WATER-SPEED-RECORD", slug: "outright-water-speed-record", title: "Outright water speed record",
    category: "Speed Records", subcategory: "Watercraft", direction: "MAXIMIZE",
    metricName: "Fastest speed achieved by a boat on water", unit: "km/h",
    formalStatement: "The highest speed ever achieved by a boat on water, certified by the Union Internationale Motonautique.",
    summary: "Ken Warby, an Australian, reached 511.11 km/h (317.6 mph) in his home-built jet-powered hydroplane Spirit of Australia on Blowering Dam, Australia, on October 8, 1978 — the outright water speed record, unbroken for over four decades. Several competitors have died attempting to break it, making it one of the most dangerous standing records in any sport.",
    value: "511.11",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Certified by the Union Internationale Motonautique (UIM), the sport's world governing body.",
    source: { title: "UIM — World Water Speed Record", url: "https://www.uim.sport/", date: "1978-10-08", location: "Blowering Dam, New South Wales, Australia" },
  },
  {
    registryNumber: "LR-FASTEST-COMMERCIAL-MAGLEV-SERVICE", slug: "fastest-train-in-regular-commercial-service", title: "Fastest train in regular commercial service",
    category: "Speed Records", subcategory: "Rail", direction: "MAXIMIZE",
    metricName: "Top operating speed of the fastest train carrying paying passengers on a regular schedule", unit: "km/h",
    formalStatement: "The highest top speed of any train in regular, scheduled commercial passenger service — distinct from experimental test-track speed records not used in daily service.",
    summary: "The Shanghai Maglev Train, connecting Shanghai Pudong Airport to the city center, operates at a top commercial speed of 431 km/h (268 mph) — the fastest train in regular scheduled passenger service anywhere in the world, covering 30 km in about 8 minutes since opening in 2004.",
    value: "431",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Published operating specifications from Shanghai Maglev Transportation Development Co., the line's operator.",
    source: { title: "Shanghai Maglev Transportation Development Co. — Official Site", url: "http://www.smtdc.com/", date: "2004-01-01", location: "Shanghai, China" },
  },
  {
    registryNumber: "LR-FASTEST-DRONE", slug: "fastest-racing-drone", title: "Fastest racing drone",
    category: "Speed Records", subcategory: "Unmanned Aerial Vehicles", direction: "MAXIMIZE",
    metricName: "Top speed achieved by a remote-controlled multi-rotor drone", unit: "km/h",
    formalStatement: "The highest speed achieved by a remote-controlled multi-rotor drone, certified by Guinness World Records.",
    summary: "The DRL RacerX, built by the Drone Racing League, reached a top speed of 263.3 km/h (163.5 mph) in 2017 — the fastest recorded speed for a battery-powered remote-controlled multi-rotor drone, certified by Guinness World Records.",
    value: "263.3",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "GPS speed measurement over a certified test run, verified by a Guinness World Records adjudicator.",
    source: { title: "Guinness World Records — Fastest speed for a battery-powered remote control multicopter/drone", url: "https://www.guinnessworldrecords.com/world-records/fastest-speed-remote-control-quadcopter/", date: "2017-07-12", location: "New York, USA" },
  },
  {
    registryNumber: "LR-FASTEST-WIND-POWERED-LAND-VEHICLE", slug: "fastest-wind-powered-land-vehicle", title: "Fastest wind-powered land vehicle",
    category: "Speed Records", subcategory: "Land Vehicles", direction: "MAXIMIZE",
    metricName: "Fastest speed achieved by a land vehicle powered directly by wind", unit: "km/h",
    formalStatement: "The highest speed achieved by a land vehicle propelled directly by wind power (a land yacht), certified by the North American Land Sailing Association.",
    summary: "Greenbird, a wind-powered land yacht designed by Richard Jenkins, reached 202.9 km/h (126.1 mph) at Ivanpah Dry Lake, California, on March 26, 2009 — faster than the wind itself, and still the record for a wind-powered land vehicle.",
    value: "202.9",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "GPS speed measurement certified by the North American Land Sailing Association.",
    source: { title: "Guinness World Records — Fastest wind-powered vehicle", url: "https://www.guinnessworldrecords.com/world-records/fastest-wind-powered-vehicle", date: "2009-03-26", location: "Ivanpah Dry Lake, California, USA" },
  },
  {
    registryNumber: "LR-OUTRIGHT-SAILING-SPEED-RECORD", slug: "outright-sailing-speed-record", title: "Outright sailing speed record",
    category: "Speed Records", subcategory: "Watercraft", direction: "MAXIMIZE",
    metricName: "Fastest speed achieved by a wind-powered sailing vessel on water", unit: "km/h",
    formalStatement: "The highest speed achieved by a sail-powered watercraft over a 500 m course, certified by the World Sailing Speed Record Council.",
    summary: "Vestas Sailrocket 2, a purpose-built speed-sailing vessel, reached 65.45 knots (121.2 km/h) off Walvis Bay, Namibia, on November 24, 2012 — the outright world sailing speed record over a 500 m course.",
    value: "121.2",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Certified by the World Sailing Speed Record Council over a standardized 500 m course.",
    source: { title: "World Sailing Speed Record Council — Outright record", url: "https://www.sailspeedrecords.com/", date: "2012-11-24", location: "Walvis Bay, Namibia" },
  },
  {
    registryNumber: "LR-FASTEST-BICYCLE-PACED", slug: "fastest-speed-on-a-bicycle", title: "Fastest speed ever reached on a bicycle",
    category: "Speed Records", subcategory: "Human-powered vehicles", direction: "MAXIMIZE",
    metricName: "Fastest speed reached by a cyclist drafting behind a pace vehicle", unit: "km/h",
    formalStatement: "The highest speed ever reached by a cyclist pedaling a bicycle while drafting in the slipstream of a lead vehicle — a different category from the unpaced, fully-faired human-powered vehicle speed record tracked separately.",
    summary: "Denise Mueller-Korenek reached 296 km/h (183.9 mph) on a modified bicycle while drafting behind a race car on the Bonneville Salt Flats, Utah, on September 16, 2018 — the fastest speed any human has ever reached on a bicycle, breaking the previous 1995 record.",
    value: "296",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "GPS and radar speed measurement, certified by USA Cycling and the Southern California Timing Association.",
    source: { title: "Guinness World Records — Fastest speed cycling (women, paced)", url: "https://www.guinnessworldrecords.com/world-records/fastest-speed-cycling-women", date: "2018-09-16", location: "Bonneville Salt Flats, Utah, USA" },
  },
  {
    registryNumber: "LR-FASTEST-HELICOPTER", slug: "fastest-helicopter", title: "Fastest helicopter",
    category: "Speed Records", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "Fastest speed achieved by a helicopter (or compound helicopter)", unit: "km/h",
    formalStatement: "The highest speed ever achieved by a rotorcraft, including hybrid compound-helicopter designs that supplement rotor lift with forward-thrust propulsion.",
    summary: "The Eurocopter X3, a compound helicopter combining a conventional rotor with two forward-facing propellers, reached 472 km/h (293 mph) in level flight during a June 2013 test — the fastest helicopter-type aircraft ever flown, well beyond the roughly 300-370 km/h ceiling of conventional helicopters.",
    value: "472",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Manufacturer flight-test telemetry from Airbus Helicopters (formerly Eurocopter).",
    source: { title: "Airbus Helicopters — X3 sets new speed record", url: "https://www.airbus.com/en", date: "2013-06-07", location: "Istres, France" },
  },
  {
    registryNumber: "LR-FASTEST-SPEED-SKIING", slug: "fastest-speed-skiing", title: "Fastest speed on skis",
    category: "Speed Records", subcategory: "Winter Sports", direction: "MAXIMIZE",
    metricName: "Fastest speed reached by a skier on snow, speed skiing discipline", unit: "km/h",
    formalStatement: "The highest speed reached by a skier on snow in the speed skiing (kilometre lancé) discipline, timed over a measured course.",
    summary: "Ivan Origone of Italy reached 254.958 km/h (158.42 mph) in the speed skiing discipline at Vars, France, in April 2016 — the fastest speed any human has reached on skis, timed over a specialized straight, steep course designed purely for top speed.",
    value: "254.958",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Electronic timing over a certified speed skiing course, ratified by the International Ski Federation (FIS).",
    source: { title: "FIS — Speed Skiing World Records", url: "https://www.fis-ski.com/", date: "2016-04-01", location: "Vars, France" },
  },
  {
    registryNumber: "LR-FASTEST-FREEFALL-SPEED", slug: "fastest-freefall-speed-by-a-human", title: "Fastest freefall speed reached by a human",
    category: "Speed Records", subcategory: "Space Exploration", direction: "MAXIMIZE",
    metricName: "Fastest speed reached by a human in freefall from a high-altitude balloon", unit: "km/h",
    formalStatement: "The highest speed reached by a human body in freefall, as opposed to the altitude from which the jump was made, which the Registry tracks as a separate record.",
    summary: "Felix Baumgartner reached a top freefall speed of 1,357.64 km/h (843.6 mph, Mach 1.25) during his October 14, 2012 jump from 128,097 ft as part of the Red Bull Stratos mission — the fastest speed any human has reached in freefall, and the first human to break the sound barrier without vehicular power.",
    value: "1357.64",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "GPS and onboard instrumentation tracking during the jump, certified by the Fédération Aéronautique Internationale.",
    source: { title: "Guinness World Records — Fastest freefall speed", url: "https://www.guinnessworldrecords.com/world-records/fastest-freefall-vertical-speed-skydiving-", date: "2012-10-14", location: "Roswell, New Mexico, USA" },
  },
  {
    registryNumber: "LR-FASTEST-RC-CAR", slug: "fastest-remote-controlled-car", title: "Fastest remote-controlled car",
    category: "Speed Records", subcategory: "Land Vehicles", direction: "MAXIMIZE",
    metricName: "Fastest speed achieved by a radio-controlled model car", unit: "km/h",
    formalStatement: "The highest speed achieved by a radio-controlled (non-tethered) model car, certified by Guinness World Records.",
    summary: "'Bullet,' a purpose-built radio-controlled car by Nic Case, reached 301.2 km/h (187.2 mph) at El Mirage Dry Lake, California, in October 2014 — the fastest radio-controlled car ever recorded, powered by a miniature turbine engine.",
    value: "301.2",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "GPS speed measurement, certified by a Guinness World Records adjudicator.",
    source: { title: "Guinness World Records — Fastest RC car", url: "https://www.guinnessworldrecords.com/world-records/fastest-rc-car", date: "2014-10-01", location: "El Mirage Dry Lake, California, USA" },
  },
  {
    registryNumber: "LR-FASTEST-LUGE-SPEED", slug: "fastest-luge-speed", title: "Fastest speed on a luge",
    category: "Speed Records", subcategory: "Winter Sports", direction: "MAXIMIZE",
    metricName: "Fastest speed recorded on a luge sled on an official track", unit: "km/h",
    formalStatement: "The highest speed recorded by a luge sled on an official international track.",
    summary: "German luger Felix Loch reached 153.98 km/h (95.68 mph) at the Whistler Sliding Centre during the 2008-09 Luge World Cup season finale — the fastest speed ever recorded in luge, made possible by Whistler's unusually steep, fast track design. Luge is the fastest of the three Olympic sliding sports (luge, skeleton, and bobsled).",
    value: "153.98",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Electronic timing and speed trap measurement, ratified by the International Luge Federation (FIL).",
    source: { title: "FIL — 153.98 km/h speed record at the Whistler Sliding Centre", url: "https://www.fil-luge.org/en/news/153-98-km-h-new-speed-record-at-the-whistler-sliding-center", date: "2009-03-01", location: "Whistler Sliding Centre, Canada" },
  },
  {
    registryNumber: "LR-FASTEST-WINGSUIT-SPEED", slug: "fastest-wingsuit-flying-speed", title: "Fastest wingsuit flying speed",
    category: "Speed Records", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "Fastest horizontal speed reached in a wingsuit, Guinness-certified", unit: "km/h",
    formalStatement: "The fastest horizontal speed reached by a human in a wingsuit, certified by Guinness World Records.",
    summary: "Fraser Corsan of the UK reached a horizontal speed of 396.88 km/h (246.6 mph) in a wingsuit over Davis, California, on May 22, 2017 — the Guinness World Record for fastest wingsuit horizontal speed, flying a specially modified suit with rigid wings rather than the flexible fabric wings used in typical wingsuit skydiving.",
    value: "396.88",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "GPS speed tracking during the flight, certified by a Guinness World Records adjudicator.",
    source: { title: "Guinness World Records — Fastest horizontal speed reached in a wing suit", url: "https://www.guinnessworldrecords.com/world-records/fastest-speed-reached-in-a-wing-suit", date: "2017-05-22", location: "Davis, California, USA" },
  },
  {
    registryNumber: "LR-FASTEST-STANDING-SKATEBOARD", slug: "fastest-skateboard-speed-standing", title: "Fastest skateboard speed (standing)",
    category: "Speed Records", subcategory: "Land Vehicles", direction: "MAXIMIZE",
    metricName: "Fastest speed reached on a non-motorized skateboard while standing", unit: "km/h",
    formalStatement: "The highest speed reached by a rider standing on a non-motorized, gravity-powered skateboard, certified by Guinness World Records.",
    summary: "Peter Connolly of the UK reached 146.73 km/h (91.17 mph) standing on a skateboard down a closed mountain road at Les Éboulements, Quebec, Canada, on September 16, 2017 — the fastest standing skateboard speed ever certified by Guinness World Records, achieved during a gravity-sports downhill event.",
    value: "146.73",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "GPS/radar speed measurement, certified by a Guinness World Records adjudicator.",
    source: { title: "Guinness World Records — Fastest skateboard speed (standing)", url: "https://www.guinnessworldrecords.com/world-records/fastest-skateboard-speed-standing", date: "2017-09-16", location: "Les Éboulements, Quebec, Canada" },
  },
  {
    registryNumber: "LR-FASTEST-SPEED-SKATING-500M", slug: "fastest-speed-skating-500m", title: "Fastest 500m speed skating average speed",
    category: "Speed Records", subcategory: "Winter Sports", direction: "MAXIMIZE",
    metricName: "Average speed over a 500m long-track speed skating race, men's world record", unit: "km/h",
    formalStatement: "The highest average speed sustained by a speed skater over a 500-meter long-track race, men's world record.",
    summary: "Pavel Kulizhnikov of Russia skated 500 m in 33.61 seconds at the ISU World Cup Speed Skating Final in Salt Lake City on March 9, 2019 — an average speed of 53.56 km/h (33.28 mph), the men's world record for long-track 500m speed skating, aided by Salt Lake City's high altitude and low air resistance.",
    value: "53.56",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Electronic timing at an International Skating Union-sanctioned event, ratified as the world record.",
    source: { title: "Guinness World Records — Fastest 500m speed skating (men)", url: "https://www.guinnessworldrecords.com/world-records/fastest-500-m-speed-skating-(men)", date: "2019-03-09", location: "Salt Lake City, Utah, USA" },
  },
  {
    registryNumber: "LR-FASTEST-BOBSLED-SPEED", slug: "fastest-bobsled-speed", title: "Fastest bobsled speed",
    category: "Speed Records", subcategory: "Winter Sports", direction: "MAXIMIZE",
    metricName: "Fastest speed recorded by a bobsled on an official track", unit: "km/h",
    formalStatement: "The highest speed recorded by a bobsled on an official international track.",
    summary: "A four-man bobsled reached approximately 157 km/h (97.6 mph) at the Whistler Sliding Centre during the 2019 World Championships — among the fastest speeds ever recorded in bobsled, on the same unusually steep Whistler track that also holds the luge speed record, since the track's design pushes all three sliding sports (bobsled, luge, and skeleton) to their fastest recorded speeds.",
    value: "157",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Track-side speed trap measurement during International Bobsleigh and Skeleton Federation-sanctioned competition; slightly different figures (156-157.06 km/h) appear across sources for this same event.",
    source: { title: "International Bobsleigh and Skeleton Federation — Whistler track records", url: "https://www.ibsf.org/", date: "2019-03-03", location: "Whistler Sliding Centre, Canada" },
  },
];
