import type { FrontierRecord } from "./frontier-records-2026";

// Tenth real-world-records batch — Science, exploration, and history, compiled 2026-10-05.
// Domains: Mathematics, Space Exploration, History, Engineering, Materials Science, Geography,
// and Economics. Every topic was checked against the full existing catalog (2,894 entries,
// including summaries) and the parallel batch-10 energy/culture file before writing. Topics
// already present under any wording — the largest generalized Fermat prime, Boolean Pythagorean
// triples, first human/animal in orbit, first Jupiter flyby, NEAR's asteroid landing, the first
// commercial spacewalk, Gagarin, Sputnik, Kongō Gumi, the oldest hotel, Vanguard 1, the tallest
// church, smallest country, highest capital, Dead Sea, and the Manitoulin, Indonesia and Vatican
// records — were deliberately skipped. Planned entries dropped after checking current sources:
// first Mars landing (Mars 3 vs. Viking 1 dispute), Syncom 3, the longest runway and pedestrian
// bridge (conflicting claims), the KVLY mast, Umling La (surpassed by Mig La in 2025), the Jeddah
// flagpole (surpassed in 2021), Black Death and Stalingrad death tolls. Prime records follow the
// Prime Pages (t5k.org) top-20 tables as of 2026-10-05; fast-moving or estimated figures are
// LITERATURE_ASSERTED.
export const WORLD_RECORDS_BATCH10_SCIENCE_HISTORY: FrontierRecord[] = [
  // --- Mathematics ---
  {
    registryNumber: "LR-LARGEST-KNOWN-FERMAT-PRIME", slug: "largest-known-fermat-prime", title: "Largest known Fermat prime",
    category: "Mathematics", subcategory: "Prime Numbers", direction: "MAXIMIZE",
    metricName: "Value of the largest Fermat number 2^(2^n) + 1 known to be prime", unit: "integer",
    formalStatement: "The largest known prime of the form F_n = 2^(2^n) + 1.",
    summary: "F4 = 2^16 + 1 = 65,537 is the largest known Fermat prime. Only F0 through F4 (3, 5, 17, 257, 65,537) are known to be prime; every Fermat number from F5 up to the limits of current computation that has been tested has proved composite, and it is an open problem whether any further Fermat primes exist.",
    value: "65537",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Primality of F0–F4 is elementary; compositeness of the larger tested Fermat numbers comes from explicit factors or Pépin's test.",
    source: { title: "Wikipedia — Fermat number", url: "https://en.wikipedia.org/wiki/Fermat_number", date: "2026-10-05", location: "Global" },
  },
  {
    registryNumber: "LR-LARGEST-KNOWN-CULLEN-PRIME", slug: "largest-known-cullen-prime", title: "Largest known Cullen prime",
    category: "Mathematics", subcategory: "Prime Numbers", direction: "MAXIMIZE",
    metricName: "Decimal digits of the largest known prime of the form n·2^n + 1", unit: "digits",
    formalStatement: "The number of decimal digits of the largest known Cullen prime, a prime of the form n·2^n + 1.",
    summary: "The Cullen number 6679881 · 2^6679881 + 1, with 2,010,852 decimal digits, was found prime by the PrimeGrid distributed-computing project in August 2009 and remains the largest known Cullen prime. Only 16 Cullen primes are known.",
    value: "2010852",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Proth-type primality test on distributed volunteer computers; listed in the Prime Pages top-20 database.",
    source: { title: "The Prime Pages — The Top Twenty: Cullen primes", url: "https://t5k.org/top20/page.php?id=6", date: "2009-08-05", location: "PrimeGrid (distributed)" },
  },
  {
    registryNumber: "LR-LARGEST-KNOWN-WOODALL-PRIME", slug: "largest-known-woodall-prime", title: "Largest known Woodall prime",
    category: "Mathematics", subcategory: "Prime Numbers", direction: "MAXIMIZE",
    metricName: "Decimal digits of the largest known prime of the form n·2^n − 1", unit: "digits",
    formalStatement: "The number of decimal digits of the largest known Woodall prime, a prime of the form n·2^n − 1.",
    summary: "The Woodall number 17016602 · 2^17016602 − 1 (equivalently 8508301 · 2^17016603 − 1), with 5,122,515 decimal digits, was found prime in March 2018 by Diego Bertolotti through the PrimeGrid project. It is the largest known Woodall prime.",
    value: "5122515",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Lucas–Lehmer–Riesel-type primality test run on PrimeGrid volunteer hardware.",
    source: { title: "The Prime Pages — The Top Twenty: Woodall primes", url: "https://t5k.org/top20/page.php?id=7", date: "2018-03-22", location: "PrimeGrid (distributed)" },
  },
  {
    registryNumber: "LR-LARGEST-KNOWN-GENERALIZED-CULLEN-PRIME", slug: "largest-known-generalized-cullen-prime", title: "Largest known generalized Cullen prime",
    category: "Mathematics", subcategory: "Prime Numbers", direction: "MAXIMIZE",
    metricName: "Decimal digits of the largest known prime of the form n·b^n + 1", unit: "digits",
    formalStatement: "The number of decimal digits of the largest known generalized Cullen prime, a prime of the form n·b^n + 1 with base b > 2.",
    summary: "The generalized Cullen number 4052186 · 69^4052186 + 1, with 7,451,366 decimal digits, was proved prime in April 2025 by a PrimeGrid participant. It is the largest known generalized Cullen prime.",
    value: "7451366",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Deterministic primality test for numbers with a fully factored N − 1, run through PrimeGrid.",
    source: { title: "The Prime Pages — The Top Twenty: Generalized Cullen", url: "https://t5k.org/top20/page.php?id=42", date: "2025-04-01", location: "PrimeGrid (distributed)" },
  },
  {
    registryNumber: "LR-LARGEST-KNOWN-GENERALIZED-WOODALL-PRIME", slug: "largest-known-generalized-woodall-prime", title: "Largest known generalized Woodall prime",
    category: "Mathematics", subcategory: "Prime Numbers", direction: "MAXIMIZE",
    metricName: "Decimal digits of the largest known prime of the form n·b^n − 1", unit: "digits",
    formalStatement: "The number of decimal digits of the largest known generalized Woodall prime, a prime of the form n·b^n − 1.",
    summary: "The generalized Woodall prime 5287180 · 3^10574360 − 1, with 5,045,259 decimal digits, was found in November 2024 and heads the Prime Pages list of generalized Woodall primes.",
    value: "5045259",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Primality test for numbers with a fully factored N + 1; recorded in the Prime Pages database.",
    source: { title: "The Prime Pages — The Top Twenty: Generalized Woodall", url: "https://t5k.org/top20/page.php?id=45", date: "2024-11-01", location: "Global" },
  },
  {
    registryNumber: "LR-LARGEST-KNOWN-PALINDROMIC-PRIME", slug: "largest-known-palindromic-prime", title: "Largest known palindromic prime",
    category: "Mathematics", subcategory: "Prime Numbers", direction: "MAXIMIZE",
    metricName: "Decimal digits of the largest known prime that reads the same forwards and backwards in base 10", unit: "digits",
    formalStatement: "The number of decimal digits of the largest known prime whose base-10 representation is a palindrome.",
    summary: "The palindromic prime 10^2718281 − 5·10^1631138 − 5·10^1087142 − 1, with 2,718,281 decimal digits, was found in August 2024 by Ryan Propper and Serge Batalov. It is the largest known palindromic prime, surpassing their own 2,000,007-digit palindrome from January 2024.",
    value: "2718281",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Primality proven using the special form of the number (factorable N ± 1), recorded in the Prime Pages database.",
    source: { title: "The Prime Pages — The Top Twenty: Palindrome", url: "https://t5k.org/top20/page.php?id=53", date: "2024-08-01", location: "Global" },
  },
  {
    registryNumber: "LR-LARGEST-PROVEN-WAGSTAFF-PRIME", slug: "largest-proven-wagstaff-prime", title: "Largest proven Wagstaff prime",
    category: "Mathematics", subcategory: "Prime Numbers", direction: "MAXIMIZE",
    metricName: "Decimal digits of the largest Wagstaff prime (2^p + 1)/3 with a completed primality proof", unit: "digits",
    formalStatement: "The number of decimal digits of the largest number of the form (2^p + 1)/3 that has been rigorously proven prime.",
    summary: "(2^141079 + 1)/3, with 42,469 decimal digits, was proven prime in October 2025 using elliptic-curve primality proving, making it the largest proven Wagstaff prime. Much larger Wagstaff numbers are known to be probable primes, but none has a completed proof.",
    value: "42469",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Elliptic curve primality proving (ECPP), recorded in the Prime Pages database.",
    source: { title: "The Prime Pages — The Top Twenty: Wagstaff", url: "https://t5k.org/top20/page.php?id=67", date: "2025-10-01", location: "Global" },
  },
  {
    registryNumber: "LR-LARGEST-PROVEN-REPUNIT-PRIME", slug: "largest-proven-repunit-prime", title: "Largest proven repunit prime",
    category: "Mathematics", subcategory: "Prime Numbers", direction: "MAXIMIZE",
    metricName: "Number of digits (all ones) in the largest repunit proven prime", unit: "digits",
    formalStatement: "The number of decimal digits of the largest repunit (10^n − 1)/9 that has been rigorously proven prime.",
    summary: "The repunit R(109297), consisting of 109,297 ones, was proven prime on 26 May 2025 using elliptic-curve primality proving. It is the largest proven repunit prime and also the largest prime ever proven by ECPP. Larger repunits such as R(8177207) are known only to be probable primes.",
    value: "109297",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Elliptic curve primality proving (ECPP) certificate, recorded in the Prime Pages database.",
    source: { title: "The Prime Pages — The Top Twenty: Repunit", url: "https://t5k.org/top20/page.php?id=57", date: "2025-05-27", location: "Global" },
  },
  {
    registryNumber: "LR-LARGEST-KNOWN-FIBONACCI-PRIME", slug: "largest-known-fibonacci-prime", title: "Largest known proven Fibonacci prime",
    category: "Mathematics", subcategory: "Prime Numbers", direction: "MAXIMIZE",
    metricName: "Decimal digits of the largest Fibonacci number proven prime", unit: "digits",
    formalStatement: "The number of decimal digits of the largest Fibonacci number F(n) that has been rigorously proven prime.",
    summary: "The Fibonacci number F(201107), with 42,029 decimal digits, was proven prime in September 2023 using elliptic-curve primality proving. It is the largest proven Fibonacci prime.",
    value: "42029",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Elliptic curve primality proving (ECPP), recorded in the Prime Pages database.",
    source: { title: "The Prime Pages — The Top Twenty: Fibonacci Number", url: "https://t5k.org/top20/page.php?id=39", date: "2023-09-01", location: "Global" },
  },
  {
    registryNumber: "LR-LARGEST-KNOWN-LUCAS-PRIME", slug: "largest-known-lucas-prime", title: "Largest known proven Lucas prime",
    category: "Mathematics", subcategory: "Prime Numbers", direction: "MAXIMIZE",
    metricName: "Decimal digits of the largest Lucas number proven prime", unit: "digits",
    formalStatement: "The number of decimal digits of the largest Lucas number L(n) that has been rigorously proven prime.",
    summary: "The Lucas number L(202667), with 42,355 decimal digits, was proven prime in November 2023 using elliptic-curve primality proving. It is the largest proven Lucas prime.",
    value: "42355",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Elliptic curve primality proving (ECPP), recorded in the Prime Pages database.",
    source: { title: "The Prime Pages — The Top Twenty: Lucas Number", url: "https://t5k.org/top20/page.php?id=48", date: "2023-11-01", location: "Global" },
  },
  {
    registryNumber: "LR-LARGEST-KNOWN-PRIME-QUADRUPLET", slug: "largest-known-prime-quadruplet", title: "Largest known prime quadruplet",
    category: "Mathematics", subcategory: "Prime Numbers", direction: "MAXIMIZE",
    metricName: "Decimal digits of the smallest member of the largest known prime quadruplet", unit: "digits",
    formalStatement: "The number of decimal digits of the largest known prime quadruplet (p, p + 2, p + 6, p + 8), all four members prime.",
    summary: "The prime quadruplet beginning with 667674063382677 · 2^33608 − 1, whose members have 10,132 decimal digits each, was found in February 2019. It is the largest known set of four primes in the tightest possible admissible pattern.",
    value: "10132",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Sieving followed by primality proofs of all four members, recorded in the Prime Pages database.",
    source: { title: "The Prime Pages — The Top Twenty: Quadruplet", url: "https://t5k.org/top20/page.php?id=55", date: "2019-02-01", location: "Global" },
  },
  {
    registryNumber: "LR-LARGEST-KNOWN-PRIME-TRIPLET", slug: "largest-known-prime-triplet", title: "Largest known prime triplet",
    category: "Mathematics", subcategory: "Prime Numbers", direction: "MAXIMIZE",
    metricName: "Decimal digits of the members of the largest known prime triplet", unit: "digits",
    formalStatement: "The number of decimal digits of the largest known prime triplet, three primes in the pattern (p, p + 2, p + 6) or (p, p + 4, p + 6).",
    summary: "The prime triplet beginning with 57612705200181 · 2^69801 − 1, whose members have 21,026 decimal digits, was found in January 2026 and tops the Prime Pages list of prime triplets.",
    value: "21026",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Sieving followed by primality proofs of all three members, recorded in the Prime Pages database.",
    source: { title: "The Prime Pages — The Top Twenty: Triplet", url: "https://t5k.org/top20/page.php?id=61", date: "2026-01-01", location: "Global" },
  },
  {
    registryNumber: "LR-LARGEST-KNOWN-PARTITION-NUMBER-PRIME", slug: "largest-known-partition-number-prime", title: "Largest known prime partition number",
    category: "Mathematics", subcategory: "Prime Numbers", direction: "MAXIMIZE",
    metricName: "Decimal digits of the largest partition number p(n) proven prime", unit: "digits",
    formalStatement: "The number of decimal digits of the largest value of the integer partition function p(n) that has been proven prime.",
    summary: "The partition number p(3000484833), the number of ways to write 3,000,484,833 as a sum of positive integers, has 61,012 decimal digits and was proven prime in September 2026 using elliptic-curve primality proving, the largest known prime partition number.",
    value: "61012",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Elliptic curve primality proving (ECPP), recorded in the Prime Pages database.",
    source: { title: "The Prime Pages — The Top Twenty: Partitions", url: "https://t5k.org/top20/page.php?id=54", date: "2026-09-01", location: "Global" },
  },
  // --- Space Exploration ---
  {
    registryNumber: "LR-FIRST-SPACECRAFT-FLYBY-OF-SATURN", slug: "first-spacecraft-flyby-of-saturn", title: "First spacecraft flyby of Saturn",
    category: "Space Exploration", subcategory: "Planetary Exploration", direction: "MINIMIZE",
    metricName: "Year of the first spacecraft encounter with Saturn", unit: "year (CE)",
    formalStatement: "The year in which a spacecraft first flew past the planet Saturn.",
    summary: "NASA's Pioneer 11 made the first spacecraft encounter with Saturn on 1 September 1979, passing about 21,000 km above the cloud tops after a Jupiter flyby in 1974. It returned the first close-up images of the planet and discovered its F ring.",
    value: "1979",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Spacecraft trajectory and encounter data published by NASA.",
    source: { title: "NASA — Pioneer 11", url: "https://science.nasa.gov/mission/pioneer-11/", date: "1979-09-01", location: "Saturn" },
  },
  {
    registryNumber: "LR-FIRST-SPACECRAFT-FLYBY-OF-MERCURY", slug: "first-spacecraft-flyby-of-mercury", title: "First spacecraft flyby of Mercury",
    category: "Space Exploration", subcategory: "Planetary Exploration", direction: "MINIMIZE",
    metricName: "Year of the first spacecraft encounter with Mercury", unit: "year (CE)",
    formalStatement: "The year in which a spacecraft first flew past the planet Mercury.",
    summary: "NASA's Mariner 10 made the first flyby of Mercury on 29 March 1974. It was also the first spacecraft to visit two planets and the first mission to use a gravity assist from one planet (Venus) to reach another.",
    value: "1974",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Spacecraft trajectory and encounter data published by NASA.",
    source: { title: "NASA — Mariner 10", url: "https://science.nasa.gov/mission/mariner-10/", date: "1974-03-29", location: "Mercury" },
  },
  {
    registryNumber: "LR-FIRST-SPACECRAFT-TO-ORBIT-VENUS", slug: "first-spacecraft-to-orbit-venus", title: "First spacecraft to orbit Venus",
    category: "Space Exploration", subcategory: "Planetary Exploration", direction: "MINIMIZE",
    metricName: "Year a spacecraft first entered orbit around Venus", unit: "year (CE)",
    formalStatement: "The year in which a spacecraft first entered orbit around the planet Venus.",
    summary: "The Soviet Venera 9 orbiter entered orbit around Venus on 20 October 1975, becoming the first artificial satellite of Venus, while its lander descended to the surface two days later.",
    value: "1975",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Mission records of the Soviet Venera programme as archived by NASA's NSSDCA.",
    source: { title: "NASA NSSDCA — Venera 9 Orbiter", url: "https://nssdc.gsfc.nasa.gov/nmc/spacecraft/display.action?id=1975-050A", date: "1975-10-20", location: "Venus orbit" },
  },
  {
    registryNumber: "LR-FIRST-PROBE-TO-ANALYZE-ANOTHER-PLANETS-ATMOSPHERE", slug: "first-probe-to-analyze-another-planets-atmosphere", title: "First in-place analysis of another planet's atmosphere",
    category: "Space Exploration", subcategory: "Planetary Exploration", direction: "MINIMIZE",
    metricName: "Year a probe first returned in-situ measurements from within another planet's atmosphere", unit: "year (CE)",
    formalStatement: "The year in which a spacecraft first transmitted direct measurements taken inside the atmosphere of another planet.",
    summary: "The Soviet Venera 4 probe descended into the atmosphere of Venus on 18 October 1967 and transmitted the first direct chemical analysis of another planet's atmosphere, showing it to be mostly carbon dioxide.",
    value: "1967",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Descent-probe telemetry from the Venera programme, archived by NASA's NSSDCA.",
    source: { title: "NASA NSSDCA — Venera 4", url: "https://nssdc.gsfc.nasa.gov/nmc/spacecraft/display.action?id=1967-058A", date: "1967-10-18", location: "Venus atmosphere" },
  },
  {
    registryNumber: "LR-FIRST-ROBOTIC-LUNAR-SAMPLE-RETURN", slug: "first-robotic-lunar-sample-return", title: "First robotic lunar sample return",
    category: "Space Exploration", subcategory: "Lunar Exploration", direction: "MINIMIZE",
    metricName: "Year the first uncrewed spacecraft returned lunar soil to Earth", unit: "year (CE)",
    formalStatement: "The year in which a robotic spacecraft first landed on the Moon and returned a sample to Earth.",
    summary: "The Soviet Luna 16 landed in Mare Fecunditatis in September 1970 and returned 101 grams of lunar soil to Earth on 24 September 1970 — the first sample of another world collected and returned entirely by a robotic spacecraft.",
    value: "1970",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Mission records of the Soviet Luna programme as archived by NASA's NSSDCA.",
    source: { title: "NASA NSSDCA — Luna 16", url: "https://nssdc.gsfc.nasa.gov/nmc/spacecraft/display.action?id=1970-072A", date: "1970-09-24", location: "Mare Fecunditatis, Moon" },
  },
  {
    registryNumber: "LR-FIRST-ARTIFICIAL-SATELLITE-OF-THE-MOON", slug: "first-artificial-satellite-of-the-moon", title: "First artificial satellite of the Moon",
    category: "Space Exploration", subcategory: "Lunar Exploration", direction: "MINIMIZE",
    metricName: "Year a spacecraft first entered orbit around the Moon", unit: "year (CE)",
    formalStatement: "The year in which a spacecraft first entered orbit around the Moon.",
    summary: "The Soviet Luna 10 entered lunar orbit on 3 April 1966, becoming the first spacecraft to orbit the Moon. It studied the lunar gravity field, radiation environment, and infrared emissions.",
    value: "1966",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Mission records of the Soviet Luna programme as archived by NASA's NSSDCA.",
    source: { title: "NASA NSSDCA — Luna 10", url: "https://nssdc.gsfc.nasa.gov/nmc/spacecraft/display.action?id=1966-027A", date: "1966-04-03", location: "Lunar orbit" },
  },
  {
    registryNumber: "LR-FIRST-SPACECRAFT-IN-HELIOCENTRIC-ORBIT", slug: "first-spacecraft-in-heliocentric-orbit", title: "First spacecraft to reach heliocentric orbit",
    category: "Space Exploration", subcategory: "Spaceflight Firsts", direction: "MINIMIZE",
    metricName: "Year a human-made object first entered orbit around the Sun", unit: "year (CE)",
    formalStatement: "The year in which a spacecraft first escaped Earth orbit and entered an independent orbit around the Sun.",
    summary: "The Soviet Luna 1, launched on 2 January 1959, missed the Moon by about 5,900 km and became the first spacecraft to leave Earth's orbit and the first human-made object in heliocentric orbit, earning the nickname 'Artificial Planet 1'.",
    value: "1959",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Trajectory records of the Soviet Luna programme as archived by NASA's NSSDCA.",
    source: { title: "NASA NSSDCA — Luna 1", url: "https://nssdc.gsfc.nasa.gov/nmc/spacecraft/display.action?id=1959-012A", date: "1959-01-02", location: "Heliocentric orbit" },
  },
  {
    registryNumber: "LR-FIRST-HUMAN-MADE-OBJECT-TO-REACH-SPACE", slug: "first-human-made-object-to-reach-space", title: "First human-made object to reach outer space",
    category: "Space Exploration", subcategory: "Spaceflight Firsts", direction: "MINIMIZE",
    metricName: "Year a human-made object first crossed the 100 km Kármán line", unit: "year (CE)",
    formalStatement: "The year in which an artificial object first reached an altitude above 100 km, the conventional boundary of outer space.",
    summary: "The German V-2 test rocket MW 18014, launched from Peenemünde on 20 June 1944, reached an apogee of about 176 km, making it the first human-made object to cross the Kármán line into outer space.",
    value: "1944",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Reconstructed flight records of the Peenemünde test-launch programme.",
    source: { title: "Wikipedia — MW 18014", url: "https://en.wikipedia.org/wiki/MW_18014", date: "1944-06-20", location: "Peenemünde, Germany" },
  },
  {
    registryNumber: "LR-FIRST-WEATHER-SATELLITE", slug: "first-weather-satellite", title: "First operational weather satellite",
    category: "Space Exploration", subcategory: "Satellites", direction: "MINIMIZE",
    metricName: "Year the first operational weather satellite was launched", unit: "year (CE)",
    formalStatement: "The year in which the first operational meteorological satellite was launched.",
    summary: "NASA's TIROS-1, launched on 1 April 1960, was the first operational weather satellite. During its 75-day mission it returned television images of cloud systems, demonstrating that weather could be monitored from orbit.",
    value: "1960",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "NASA mission records.",
    source: { title: "NASA NSSDCA — TIROS 1", url: "https://nssdc.gsfc.nasa.gov/nmc/spacecraft/display.action?id=1960-002B", date: "1960-04-01", location: "Low Earth orbit" },
  },
  {
    registryNumber: "LR-FIRST-COMMUNICATIONS-SATELLITE", slug: "first-communications-satellite", title: "First communications satellite",
    category: "Space Exploration", subcategory: "Satellites", direction: "MINIMIZE",
    metricName: "Year the first communications relay satellite was launched", unit: "year (CE)",
    formalStatement: "The year in which a satellite was first used to relay communications.",
    summary: "Project SCORE, launched by the United States on 18 December 1958 atop an Atlas rocket, was the first communications relay satellite. It broadcast a recorded Christmas message from President Dwight D. Eisenhower from orbit.",
    value: "1958",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "U.S. Air Force and ARPA project records.",
    source: { title: "Wikipedia — SCORE (satellite)", url: "https://en.wikipedia.org/wiki/SCORE_(satellite)", date: "1958-12-18", location: "Low Earth orbit" },
  },
  {
    registryNumber: "LR-FIRST-SUCCESSFUL-SPACE-TELESCOPE", slug: "first-successful-space-telescope", title: "First successful space telescope",
    category: "Space Exploration", subcategory: "Satellites", direction: "MINIMIZE",
    metricName: "Year the first successful orbiting astronomical telescope was launched", unit: "year (CE)",
    formalStatement: "The year in which the first space telescope to operate successfully in orbit was launched.",
    summary: "NASA's Orbiting Astronomical Observatory 2 (OAO-2, 'Stargazer'), launched on 7 December 1968, was the first successful space telescope. Its ultraviolet telescopes observed until early 1973, providing the first high-quality ultraviolet observations of many stars and galaxies.",
    value: "1968",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "NASA mission records.",
    source: { title: "NASA — NASA's First Stellar Observatory, OAO 2, Turns 50", url: "https://www.nasa.gov/feature/goddard/2018/nasa-s-first-stellar-observatory-oao-2-turns-50", date: "2018-12-11", location: "Low Earth orbit" },
  },
  {
    registryNumber: "LR-FIRST-MULTI-CREW-SPACEFLIGHT", slug: "first-multi-crew-spaceflight", title: "First multi-crew spaceflight",
    category: "Space Exploration", subcategory: "Human Spaceflight", direction: "MINIMIZE",
    metricName: "Year a spacecraft first carried more than one person into orbit", unit: "year (CE)",
    formalStatement: "The year in which a single spacecraft first carried more than one person into orbit.",
    summary: "The Soviet Voskhod 1, launched on 12 October 1964, carried cosmonauts Vladimir Komarov, Konstantin Feoktistov, and Boris Yegorov — the first spaceflight with more than one crew member, and the first flown without spacesuits.",
    value: "1964",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Soviet mission records.",
    source: { title: "Wikipedia — Voskhod 1", url: "https://en.wikipedia.org/wiki/Voskhod_1", date: "1964-10-12", location: "Low Earth orbit" },
  },
  {
    registryNumber: "LR-FIRST-UNTETHERED-SPACEWALK", slug: "first-untethered-spacewalk", title: "First untethered spacewalk",
    category: "Space Exploration", subcategory: "Human Spaceflight", direction: "MINIMIZE",
    metricName: "Year of the first spacewalk made without a tether to the spacecraft", unit: "year (CE)",
    formalStatement: "The year in which an astronaut first moved freely in space without any physical tether to a spacecraft.",
    summary: "On 7 February 1984, during Space Shuttle mission STS-41-B, NASA astronaut Bruce McCandless II used the Manned Maneuvering Unit jetpack to fly up to about 100 m from Challenger — the first untethered spacewalk.",
    value: "1984",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "NASA mission records.",
    source: { title: "NASA — STS-41B", url: "https://www.nasa.gov/mission/sts-41b/", date: "1984-02-07", location: "Low Earth orbit" },
  },
  {
    registryNumber: "LR-LARGEST-CREW-ABOARD-A-SINGLE-SPACECRAFT", slug: "largest-crew-aboard-a-single-spacecraft", title: "Largest crew aboard a single spacecraft",
    category: "Space Exploration", subcategory: "Human Spaceflight", direction: "MAXIMIZE",
    metricName: "Number of people launched and landed aboard one spacecraft", unit: "people",
    formalStatement: "The largest number of people carried aboard a single spacecraft for an entire mission, from launch to landing.",
    summary: "Space Shuttle mission STS-61-A (Challenger, 30 October – 6 November 1985), the West German Spacelab D-1 mission, carried eight astronauts from launch to landing — the largest crew ever aboard a single spacecraft for a whole flight. It was the only Shuttle flight to launch with eight people.",
    value: "8",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "NASA mission records.",
    source: { title: "NASA — STS-61A", url: "https://www.nasa.gov/mission/sts-61a/", date: "1985-10-30", location: "Low Earth orbit" },
  },
  {
    registryNumber: "LR-FIRST-ORBITAL-FLIGHT-OF-A-REUSABLE-CREWED-SPACECRAFT", slug: "first-orbital-flight-of-a-reusable-crewed-spacecraft", title: "First orbital flight of a reusable crewed spacecraft",
    category: "Space Exploration", subcategory: "Human Spaceflight", direction: "MINIMIZE",
    metricName: "Year a reusable crewed spacecraft first flew to orbit", unit: "year (CE)",
    formalStatement: "The year in which a crewed spacecraft designed for reuse first flew to orbit.",
    summary: "STS-1, flown by John Young and Robert Crippen aboard Space Shuttle Columbia from 12 to 14 April 1981, was the first orbital flight of the Space Shuttle and the first orbital flight of a reusable crewed spacecraft. Columbia completed 36 orbits before landing at Edwards Air Force Base.",
    value: "1981",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "NASA mission records.",
    source: { title: "NASA — STS-1", url: "https://www.nasa.gov/mission/sts-1/", date: "1981-04-12", location: "Low Earth orbit" },
  },
  {
    registryNumber: "LR-FIRST-CREWED-VEHICLE-DRIVEN-ON-THE-MOON", slug: "first-crewed-vehicle-driven-on-the-moon", title: "First crewed vehicle driven on the Moon",
    category: "Space Exploration", subcategory: "Human Spaceflight", direction: "MINIMIZE",
    metricName: "Year a crewed vehicle was first driven on the lunar surface", unit: "year (CE)",
    formalStatement: "The year in which astronauts first drove a vehicle on the surface of the Moon.",
    summary: "The Lunar Roving Vehicle was first driven on the Moon on 31 July 1971 by Apollo 15 astronauts David Scott and James Irwin at Hadley–Apennine. Rovers were also used on Apollo 16 and 17.",
    value: "1971",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "NASA mission records.",
    source: { title: "NASA — Apollo 15", url: "https://www.nasa.gov/mission/apollo-15/", date: "1971-07-31", location: "Hadley–Apennine, Moon" },
  },
  {
    registryNumber: "LR-FIRST-SPACECRAFT-FLYBY-OF-AN-ASTEROID", slug: "first-spacecraft-flyby-of-an-asteroid", title: "First spacecraft flyby of an asteroid",
    category: "Space Exploration", subcategory: "Small Bodies", direction: "MINIMIZE",
    metricName: "Year a spacecraft first flew past an asteroid", unit: "year (CE)",
    formalStatement: "The year in which a spacecraft first made a close encounter with an asteroid.",
    summary: "NASA's Galileo spacecraft flew past the asteroid 951 Gaspra on 29 October 1991 while en route to Jupiter, making Gaspra the first asteroid ever visited by a spacecraft and returning the first close-up images of an asteroid.",
    value: "1991",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "NASA mission records.",
    source: { title: "NASA — Galileo", url: "https://science.nasa.gov/mission/galileo/", date: "1991-10-29", location: "951 Gaspra, asteroid belt" },
  },
  {
    registryNumber: "LR-FIRST-SPACECRAFT-ENCOUNTER-WITH-A-COMET", slug: "first-spacecraft-encounter-with-a-comet", title: "First spacecraft encounter with a comet",
    category: "Space Exploration", subcategory: "Small Bodies", direction: "MINIMIZE",
    metricName: "Year a spacecraft first visited a comet", unit: "year (CE)",
    formalStatement: "The year in which a spacecraft first made a close encounter with a comet.",
    summary: "NASA's International Cometary Explorer (ICE) passed through the plasma tail of comet 21P/Giacobini–Zinner about 7,800 km from the nucleus on 11 September 1985, becoming the first spacecraft to visit a comet — months before the Halley armada.",
    value: "1985",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "NASA mission records.",
    source: { title: "NASA NSSDCA — ISEE 3 / International Cometary Explorer", url: "https://nssdc.gsfc.nasa.gov/nmc/spacecraft/display.action?id=1978-079A", date: "1985-09-11", location: "Comet 21P/Giacobini–Zinner" },
  },
  {
    registryNumber: "LR-FIRST-LIVING-ORGANISMS-IN-SPACE", slug: "first-living-organisms-in-space", title: "First living organisms launched into space",
    category: "Space Exploration", subcategory: "Life in Space", direction: "MINIMIZE",
    metricName: "Year living organisms were first launched into space", unit: "year (CE)",
    formalStatement: "The year in which living organisms were first carried above the boundary of space.",
    summary: "Fruit flies launched aboard a U.S. V-2 rocket from White Sands, New Mexico, in 1946 became the first living organisms sent to space; on 20 February 1947 another V-2 carried fruit flies above 100 km and they were recovered alive by parachute.",
    value: "1946",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Historical records of the U.S. V-2 upper-atmosphere research flights.",
    source: { title: "Wikipedia — Fruit flies in space", url: "https://en.wikipedia.org/wiki/Fruit_flies_in_space", date: "1947-02-20", location: "White Sands, New Mexico, USA" },
  },
  {
    registryNumber: "LR-FIRST-PRIMATE-IN-SPACE", slug: "first-primate-in-space", title: "First primate and first mammal in space",
    category: "Space Exploration", subcategory: "Life in Space", direction: "MINIMIZE",
    metricName: "Year a primate was first launched into space", unit: "year (CE)",
    formalStatement: "The year in which a primate (and the first mammal) was first carried into space.",
    summary: "Albert II, a rhesus macaque, was launched on V-2 flight No. 47 from New Mexico on 14 June 1949 and became the first primate and first mammal in space, reaching an altitude of about 134 km. He died on impact when the parachute failed.",
    value: "1949",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "U.S. Air Force flight records.",
    source: { title: "Wikipedia — Albert II (monkey)", url: "https://en.wikipedia.org/wiki/Albert_II_(monkey)", date: "1949-06-14", location: "Holloman AFB / White Sands, New Mexico, USA" },
  },
  {
    registryNumber: "LR-FIRST-COMMERCIAL-SPACECRAFT-TO-BERTH-WITH-A-SPACE-STATION", slug: "first-commercial-spacecraft-to-berth-with-a-space-station", title: "First commercial spacecraft to berth with a space station",
    category: "Space Exploration", subcategory: "Commercial Spaceflight", direction: "MINIMIZE",
    metricName: "Year a privately built spacecraft first berthed with a space station", unit: "year (CE)",
    formalStatement: "The year in which a commercially developed spacecraft first rendezvoused and berthed with a space station.",
    summary: "SpaceX's Dragon capsule on the COTS Demo Flight 2 mission was captured by the station's robotic arm and berthed to the International Space Station on 25 May 2012 — the first commercial spacecraft to rendezvous and berth with another spacecraft.",
    value: "2012",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "NASA and SpaceX mission records.",
    source: { title: "NASA — SpaceX Dragon arrives at the International Space Station", url: "https://www.nasa.gov/mission_pages/station/main/index.html", date: "2012-05-25", location: "International Space Station" },
  },
  // --- History ---
  {
    registryNumber: "LR-FIRST-COUNTRY-TO-GRANT-WOMEN-THE-VOTE", slug: "first-country-to-grant-women-the-vote", title: "First self-governing country to grant women the vote",
    category: "History", subcategory: "Political History", direction: "MINIMIZE",
    metricName: "Year all women in a self-governing country first gained the right to vote in national elections", unit: "year (CE)",
    formalStatement: "The year in which a self-governing country first gave all adult women the right to vote in parliamentary elections.",
    summary: "New Zealand's Electoral Act 1893, given royal assent on 19 September 1893 after campaigning led by Kate Sheppard, gave all women aged 21 or older the right to vote — the first self-governing country to do so. Women voted for the first time in the general election of 28 November 1893.",
    value: "1893",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Statute records and New Zealand electoral history.",
    source: { title: "New Zealand History — Women and the vote", url: "https://nzhistory.govt.nz/politics/womens-suffrage", date: "1893-09-19", location: "New Zealand" },
  },
  {
    registryNumber: "LR-FIRST-EXPEDITION-TO-REACH-THE-SOUTH-POLE", slug: "first-expedition-to-reach-the-south-pole", title: "First expedition to reach the South Pole",
    category: "History", subcategory: "Exploration", direction: "MINIMIZE",
    metricName: "Year humans first reached the geographic South Pole", unit: "year (CE)",
    formalStatement: "The year in which people first reached the Earth's geographic South Pole.",
    summary: "Norwegian explorer Roald Amundsen and four companions — Olav Bjaaland, Helmer Hanssen, Sverre Hassel and Oscar Wisting — reached the geographic South Pole on 14 December 1911, about five weeks before Robert Falcon Scott's British party.",
    value: "1911",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Expedition records and contemporary accounts.",
    source: { title: "Wikipedia — Amundsen's South Pole expedition", url: "https://en.wikipedia.org/wiki/Amundsen%27s_South_Pole_expedition", date: "1911-12-14", location: "Geographic South Pole, Antarctica" },
  },
  {
    registryNumber: "LR-FIRST-ASCENT-OF-MOUNT-EVEREST", slug: "first-ascent-of-mount-everest", title: "First ascent of Mount Everest",
    category: "History", subcategory: "Exploration", direction: "MINIMIZE",
    metricName: "Year of the first confirmed ascent of Mount Everest", unit: "year (CE)",
    formalStatement: "The year in which climbers first reached the summit of Mount Everest, the highest mountain on Earth.",
    summary: "Edmund Hillary of New Zealand and Tenzing Norgay, a Sherpa of Nepal, reached the summit of Mount Everest on 29 May 1953 as members of the British expedition led by John Hunt — the first confirmed ascent of the world's highest mountain.",
    value: "1953",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Expedition records.",
    source: { title: "Wikipedia — 1953 British Mount Everest expedition", url: "https://en.wikipedia.org/wiki/1953_British_Mount_Everest_expedition", date: "1953-05-29", location: "Mount Everest, Nepal–China border" },
  },
  {
    registryNumber: "LR-FIRST-CREWED-HOT-AIR-BALLOON-FLIGHT", slug: "first-crewed-hot-air-balloon-flight", title: "First crewed free flight in a hot-air balloon",
    category: "History", subcategory: "History of Aviation", direction: "MINIMIZE",
    metricName: "Year humans first flew in an untethered aircraft", unit: "year (CE)",
    formalStatement: "The year of the first confirmed free flight by humans in a lighter-than-air craft.",
    summary: "On 21 November 1783 Jean-François Pilâtre de Rozier and the Marquis d'Arlandes flew over Paris in a hot-air balloon built by the Montgolfier brothers — the first confirmed free flight by humans.",
    value: "1783",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Contemporary accounts of the Montgolfier balloon flights.",
    source: { title: "Wikipedia — Montgolfier brothers", url: "https://en.wikipedia.org/wiki/Montgolfier_brothers", date: "1783-11-21", location: "Paris, France" },
  },
  {
    registryNumber: "LR-FIRST-AIRPLANE-FLIGHT-ACROSS-THE-ENGLISH-CHANNEL", slug: "first-airplane-flight-across-the-english-channel", title: "First airplane flight across the English Channel",
    category: "History", subcategory: "History of Aviation", direction: "MINIMIZE",
    metricName: "Year an airplane first crossed the English Channel", unit: "year (CE)",
    formalStatement: "The year in which a heavier-than-air aircraft first flew across the English Channel.",
    summary: "French aviator Louis Blériot flew his Blériot XI monoplane from near Calais to Dover on 25 July 1909 in about 36 minutes, the first airplane crossing of the English Channel, winning the Daily Mail's £1,000 prize.",
    value: "1909",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Contemporary press records.",
    source: { title: "Wikipedia — Louis Blériot", url: "https://en.wikipedia.org/wiki/Louis_Bl%C3%A9riot", date: "1909-07-25", location: "Calais, France – Dover, England" },
  },
  {
    registryNumber: "LR-FIRST-NONSTOP-TRANSATLANTIC-FLIGHT", slug: "first-nonstop-transatlantic-flight", title: "First non-stop transatlantic flight",
    category: "History", subcategory: "History of Aviation", direction: "MINIMIZE",
    metricName: "Year of the first non-stop airplane flight across the Atlantic Ocean", unit: "year (CE)",
    formalStatement: "The year in which an aircraft first flew across the Atlantic Ocean without stopping.",
    summary: "British aviators John Alcock and Arthur Whitten Brown flew a modified Vickers Vimy bomber from St. John's, Newfoundland, to Clifden, Ireland, on 14–15 June 1919 — the first non-stop transatlantic flight, taking about 16 hours.",
    value: "1919",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Contemporary records of the Daily Mail transatlantic prize.",
    source: { title: "Wikipedia — Transatlantic flight of Alcock and Brown", url: "https://en.wikipedia.org/wiki/Transatlantic_flight_of_Alcock_and_Brown", date: "1919-06-15", location: "St. John's, Newfoundland – Clifden, Ireland" },
  },
  {
    registryNumber: "LR-FIRST-AERIAL-CIRCUMNAVIGATION", slug: "first-aerial-circumnavigation", title: "First aerial circumnavigation of the world",
    category: "History", subcategory: "History of Aviation", direction: "MINIMIZE",
    metricName: "Year aircraft first flew around the world", unit: "year (CE)",
    formalStatement: "The year in which aircraft first completed a flight around the world.",
    summary: "In 1924 two Douglas World Cruiser biplanes of the U.S. Army Air Service, crewed by aviators from an eight-man team, completed the first flight around the world — a 175-day journey from April to September covering more than 26,345 miles (about 42,400 km).",
    value: "1924",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "U.S. Army Air Service records.",
    source: { title: "Wikipedia — First aerial circumnavigation", url: "https://en.wikipedia.org/wiki/First_aerial_circumnavigation", date: "1924-09-28", location: "Seattle, Washington, USA (start and finish)" },
  },
  {
    registryNumber: "LR-FIRST-SUCCESSFUL-TELEPHONE-TRANSMISSION-OF-SPEECH", slug: "first-successful-telephone-transmission-of-speech", title: "First successful telephone transmission of speech",
    category: "History", subcategory: "History of Technology", direction: "MINIMIZE",
    metricName: "Year of the first intelligible speech transmitted by telephone", unit: "year (CE)",
    formalStatement: "The year in which intelligible speech was first transmitted by an electric telephone.",
    summary: "On 10 March 1876 in Boston, Alexander Graham Bell transmitted the words 'Mr. Watson, come here, I want to see you' to his assistant Thomas Watson in another room — the first successful telephone transmission of intelligible speech, recorded in Bell's laboratory notebook.",
    value: "1876",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Bell's laboratory notebook, held by the Library of Congress.",
    source: { title: "Library of Congress — Alexander Graham Bell Family Papers", url: "https://www.loc.gov/collections/alexander-graham-bell-papers/", date: "1876-03-10", location: "Boston, Massachusetts, USA" },
  },
  {
    registryNumber: "LR-FIRST-NUCLEAR-WEAPON-DETONATION", slug: "first-nuclear-weapon-detonation", title: "First nuclear weapon detonation",
    category: "History", subcategory: "Nuclear Age", direction: "MINIMIZE",
    metricName: "Year of the first detonation of a nuclear weapon", unit: "year (CE)",
    formalStatement: "The year in which a nuclear weapon was first detonated.",
    summary: "The Trinity test, conducted by the U.S. Army's Manhattan Project in the Jornada del Muerto desert of New Mexico on 16 July 1945, was the first detonation of a nuclear weapon. The plutonium implosion device yielded roughly 25 kilotons of TNT equivalent by modern estimates.",
    value: "1945",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Manhattan Project records.",
    source: { title: "Wikipedia — Trinity (nuclear test)", url: "https://en.wikipedia.org/wiki/Trinity_(nuclear_test)", date: "1945-07-16", location: "Alamogordo Bombing Range, New Mexico, USA" },
  },
  {
    registryNumber: "LR-MOST-POWERFUL-NUCLEAR-WEAPON-EVER-TESTED", slug: "most-powerful-nuclear-weapon-ever-tested", title: "Most powerful nuclear weapon ever tested",
    category: "History", subcategory: "Nuclear Age", direction: "MAXIMIZE",
    metricName: "Explosive yield of the largest nuclear explosion", unit: "megatons of TNT",
    formalStatement: "The largest explosive yield of any nuclear weapon ever detonated.",
    summary: "The Soviet thermonuclear bomb known as Tsar Bomba was air-dropped over the Novaya Zemlya test site on 30 October 1961 and produced a yield of about 50 megatons of TNT (estimates range from 50 to 58 Mt) — the most powerful explosion ever created by humans.",
    value: "50",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Yield estimates from Soviet test records and seismic/atmospheric analyses.",
    source: { title: "Wikipedia — Tsar Bomba", url: "https://en.wikipedia.org/wiki/Tsar_Bomba", date: "1961-10-30", location: "Novaya Zemlya, USSR" },
  },
  {
    registryNumber: "LR-OLDEST-CONTINUOUSLY-OPERATING-SCHOOL", slug: "oldest-continuously-operating-school", title: "Oldest continuously operating school",
    category: "History", subcategory: "Education", direction: "MINIMIZE",
    metricName: "Founding year of the oldest school still operating", unit: "year (CE)",
    formalStatement: "The founding year of the oldest school that has operated continuously to the present.",
    summary: "The King's School in Canterbury, England, traces its foundation to 597 CE, when Augustine of Canterbury established a cathedral school after arriving in England. It is widely regarded as the oldest continuously operating school in the world.",
    value: "597",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Institutional history; the founding date is traditional and based on the arrival of Augustine's mission.",
    source: { title: "The King's School, Canterbury — History", url: "https://www.kings-school.co.uk/", date: "2026-10-05", location: "Canterbury, England" },
  },
  {
    registryNumber: "LR-OLDEST-COMPLETE-STAR-ATLAS", slug: "oldest-complete-star-atlas", title: "Oldest known complete star atlas",
    category: "History", subcategory: "History of Astronomy", direction: "MINIMIZE",
    metricName: "Approximate year of creation of the oldest known complete star atlas", unit: "year (CE)",
    formalStatement: "The approximate year of creation of the oldest surviving map covering the whole visible sky.",
    summary: "The Dunhuang Star Chart, a Tang-dynasty manuscript found among the Dunhuang manuscripts and now in the British Library (Or.8210/S.3326), was made around the year 700 CE and depicts about 1,300 stars. It is regarded as the oldest known complete star atlas.",
    value: "700",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Dating from paleographic and astronomical analysis of the manuscript.",
    source: { title: "International Dunhuang Project — The Dunhuang Chinese Sky", url: "https://idp.bl.uk/", date: "2009-01-01", location: "Dunhuang, China (now British Library, London)" },
  },
  {
    registryNumber: "LR-FIRST-MODERN-OLYMPIC-GAMES", slug: "first-modern-olympic-games", title: "First modern Olympic Games",
    category: "History", subcategory: "History of Sport", direction: "MINIMIZE",
    metricName: "Year of the first modern Olympic Games", unit: "year (CE)",
    formalStatement: "The year in which the first Olympic Games of the modern era were held.",
    summary: "The Games of the I Olympiad were held in Athens from 6 to 15 April 1896 at the Panathenaic Stadium, featuring 43 events in 9 sports. They were the first Olympic Games of the modern era, revived by Pierre de Coubertin's International Olympic Committee.",
    value: "1896",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "International Olympic Committee records.",
    source: { title: "International Olympic Committee — Athens 1896", url: "https://www.olympics.com/en/olympic-games/athens-1896", date: "1896-04-06", location: "Athens, Greece" },
  },
  // --- Engineering ---
  {
    registryNumber: "LR-FIRST-LOCOMOTIVE-HAULED-RAILWAY-JOURNEY", slug: "first-locomotive-hauled-railway-journey", title: "First locomotive-hauled railway journey",
    category: "Engineering", subcategory: "Rail Transport", direction: "MINIMIZE",
    metricName: "Year a steam locomotive first hauled a train on rails", unit: "year (CE)",
    formalStatement: "The year in which a steam locomotive first hauled a train along a railway.",
    summary: "On 21 February 1804 Richard Trevithick's unnamed steam locomotive hauled a train along the tramway of the Penydarren Ironworks in Merthyr Tydfil, Wales — the world's first locomotive-hauled railway journey.",
    value: "1804",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Historical records of the Penydarren tramway.",
    source: { title: "Wikipedia — Richard Trevithick", url: "https://en.wikipedia.org/wiki/Richard_Trevithick", date: "1804-02-21", location: "Merthyr Tydfil, Wales" },
  },
  {
    registryNumber: "LR-FIRST-PUBLIC-STEAM-RAILWAY", slug: "first-public-steam-railway", title: "First public railway to use steam locomotives",
    category: "Engineering", subcategory: "Rail Transport", direction: "MINIMIZE",
    metricName: "Year the first public steam-hauled railway opened", unit: "year (CE)",
    formalStatement: "The year in which the first public railway using steam locomotives opened.",
    summary: "The Stockton and Darlington Railway in north-east England opened on 27 September 1825, the world's first public railway to use steam locomotives, with George Stephenson's Locomotion No. 1 hauling the opening train.",
    value: "1825",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Railway company records.",
    source: { title: "Wikipedia — Stockton and Darlington Railway", url: "https://en.wikipedia.org/wiki/Stockton_and_Darlington_Railway", date: "1825-09-27", location: "County Durham, England" },
  },
  {
    registryNumber: "LR-FIRST-UNDERGROUND-RAILWAY", slug: "first-underground-railway", title: "First underground passenger railway",
    category: "Engineering", subcategory: "Rail Transport", direction: "MINIMIZE",
    metricName: "Year the first underground passenger railway opened", unit: "year (CE)",
    formalStatement: "The year in which the first passenger-carrying underground railway opened.",
    summary: "The Metropolitan Railway in London opened to the public on 10 January 1863 between Paddington and Farringdon, with gas-lit wooden carriages hauled by steam locomotives — the world's first passenger-carrying underground railway and the origin of the London Underground.",
    value: "1863",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Railway company records.",
    source: { title: "Transport for London — London Underground history", url: "https://tfl.gov.uk/", date: "1863-01-10", location: "London, England" },
  },
  {
    registryNumber: "LR-LONGEST-HIGH-SPEED-RAIL-LINE", slug: "longest-high-speed-rail-line", title: "Longest high-speed rail line",
    category: "Engineering", subcategory: "Rail Transport", direction: "MAXIMIZE",
    metricName: "Route length of the longest single high-speed rail line", unit: "kilometers",
    formalStatement: "The route length of the longest single high-speed railway line.",
    summary: "The Beijing–Guangzhou high-speed railway in China, which opened end to end on 26 December 2012 and runs at up to 350 km/h, is 2,230 km long — the world's longest high-speed rail route. It now forms part of the Beijing–Hong Kong corridor.",
    value: "2230",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Published line specifications of China Railway.",
    source: { title: "Wikipedia — Beijing–Guangzhou high-speed railway", url: "https://en.wikipedia.org/wiki/Beijing%E2%80%93Guangzhou_high-speed_railway", date: "2012-12-26", location: "Beijing – Guangzhou, China" },
  },
  {
    registryNumber: "LR-LONGEST-TRAIN-EVER-RUN", slug: "longest-train-ever-run", title: "Longest and heaviest train ever run",
    category: "Engineering", subcategory: "Rail Transport", direction: "MAXIMIZE",
    metricName: "Length of the longest train ever operated", unit: "kilometers",
    formalStatement: "The length of the longest train ever operated on a railway.",
    summary: "On 21 June 2001 BHP ran an iron-ore train in the Pilbara region of Western Australia that was 7.353 km long, with 682 wagons pulled by eight locomotives — the longest and heaviest train ever run.",
    value: "7.353",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Railway operating records.",
    source: { title: "Wikipedia — Longest trains", url: "https://en.wikipedia.org/wiki/Longest_trains", date: "2001-06-21", location: "Pilbara, Western Australia" },
  },
  {
    registryNumber: "LR-RAILWAY-STATION-WITH-THE-MOST-PLATFORMS", slug: "railway-station-with-the-most-platforms", title: "Railway station with the most platforms",
    category: "Engineering", subcategory: "Rail Transport", direction: "MAXIMIZE",
    metricName: "Number of platforms at a single railway station", unit: "platforms",
    formalStatement: "The largest number of platforms at a single railway station.",
    summary: "Grand Central Terminal in New York City holds the Guinness World Record for the railway station with the most platforms: 44 platforms (on 28 physical platform structures) spread across two underground levels.",
    value: "44",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Guinness World Records certification.",
    source: { title: "Guinness World Records — Largest railway station (no. of platforms)", url: "https://www.guinnessworldrecords.com/world-records/largest-railway-station-(no-of-platforms)", date: "2026-10-05", location: "New York City, USA" },
  },
  {
    registryNumber: "LR-FIRST-MODERN-AUTOMOBILE", slug: "first-modern-automobile", title: "First modern automobile",
    category: "Engineering", subcategory: "Road Transport", direction: "MINIMIZE",
    metricName: "Year of the first practical gasoline-powered automobile", unit: "year (CE)",
    formalStatement: "The year in which the first purpose-built automobile powered by an internal combustion engine was patented.",
    summary: "Carl Benz's Benz Patent-Motorwagen, a three-wheeled vehicle powered by a 954 cc single-cylinder engine, was patented in January 1886 and is widely regarded as the first modern automobile.",
    value: "1886",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "German Imperial patent DRP 37435.",
    source: { title: "Mercedes-Benz Group — Benz Patent Motor Car: the first automobile (1885–1886)", url: "https://group.mercedes-benz.com/", date: "1886-01-29", location: "Mannheim, Germany" },
  },
  {
    registryNumber: "LR-HIGHEST-MOTORABLE-ROAD", slug: "highest-motorable-road", title: "Highest motorable road",
    category: "Engineering", subcategory: "Road Transport", direction: "MAXIMIZE",
    metricName: "Elevation of the highest road open to motor vehicles", unit: "meters",
    formalStatement: "The highest elevation reached by a road built for motor vehicles.",
    summary: "A road built by India's Border Roads Organisation over the Mig La pass in Ladakh reaches about 5,913 m (19,400 ft), surpassing the Umling La road (about 5,799 m) in 2025 to become the world's highest motorable road.",
    value: "5913",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Border Roads Organisation survey figures as reported in 2025.",
    source: { title: "Wikipedia — Mig La", url: "https://en.wikipedia.org/wiki/Mig_La", date: "2025-10-04", location: "Ladakh, India" },
  },
  {
    registryNumber: "LR-FIRST-TURBOJET-AIRCRAFT-FLIGHT", slug: "first-turbojet-aircraft-flight", title: "First turbojet-powered aircraft flight",
    category: "Engineering", subcategory: "Aviation", direction: "MINIMIZE",
    metricName: "Year of the first flight of an aircraft powered by a turbojet", unit: "year (CE)",
    formalStatement: "The year in which an aircraft first flew on turbojet thrust.",
    summary: "The Heinkel He 178, powered by Hans von Ohain's turbojet engine, made its first flight on 27 August 1939 in Germany — the world's first aircraft to fly using the thrust of a turbojet.",
    value: "1939",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Heinkel company and flight-test records.",
    source: { title: "Wikipedia — Heinkel He 178", url: "https://en.wikipedia.org/wiki/Heinkel_He_178", date: "1939-08-27", location: "Rostock-Marienehe, Germany" },
  },
  {
    registryNumber: "LR-FIRST-PILOTED-SUPERSONIC-LEVEL-FLIGHT", slug: "first-piloted-supersonic-level-flight", title: "First piloted supersonic flight in level flight",
    category: "Engineering", subcategory: "Aviation", direction: "MINIMIZE",
    metricName: "Year a piloted aircraft first exceeded the speed of sound in level flight", unit: "year (CE)",
    formalStatement: "The year in which a piloted airplane first exceeded the speed of sound in level flight.",
    summary: "On 14 October 1947 Chuck Yeager flew the rocket-powered Bell X-1 'Glamorous Glennis' to Mach 1.06 over the Mojave Desert, the first piloted airplane to exceed the speed of sound in level flight.",
    value: "1947",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "U.S. Air Force and NACA flight-test records.",
    source: { title: "Smithsonian National Air and Space Museum — Bell X-1", url: "https://airandspace.si.edu/collection-objects/bell-x-1-glamorous-glennis/nasm_A19510007000", date: "1947-10-14", location: "Mojave Desert, California, USA" },
  },
  {
    registryNumber: "LR-HIGHEST-CIVILIAN-AIRPORT", slug: "highest-civilian-airport", title: "Highest civilian airport",
    category: "Engineering", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "Elevation of the highest civilian airport", unit: "meters above sea level",
    formalStatement: "The elevation above sea level of the highest airport serving civilian traffic.",
    summary: "Daocheng Yading Airport in Sichuan, China, opened on 16 September 2013 at an elevation of 4,411 m, is the highest civilian airport in the world, ahead of Qamdo Bamda Airport in Tibet at 4,334 m.",
    value: "4411",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Published aerodrome elevation data.",
    source: { title: "Wikipedia — List of highest airports", url: "https://en.wikipedia.org/wiki/List_of_highest_airports", date: "2013-09-16", location: "Daocheng County, Sichuan, China" },
  },
  {
    registryNumber: "LR-LONGEST-CONTINUOUS-BRIDGE-OVER-WATER", slug: "longest-continuous-bridge-over-water", title: "Longest continuous bridge over water",
    category: "Engineering", subcategory: "Bridges", direction: "MAXIMIZE",
    metricName: "Length of the longest continuous bridge span over water", unit: "kilometers",
    formalStatement: "The length of the longest bridge running continuously over open water.",
    summary: "The Lake Pontchartrain Causeway in Louisiana, two parallel bridges opened in 1956 and 1969, holds the Guinness World Record as the longest continuous bridge over water. The longer span is about 23.8 miles (about 38.4 km).",
    value: "38.4",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Guinness World Records certification and Causeway Commission figures.",
    source: { title: "Guinness World Records — Longest bridge over water (continuous)", url: "https://www.guinnessworldrecords.com/world-records/97851-longest-bridge-over-water-continuous", date: "1969-05-10", location: "Lake Pontchartrain, Louisiana, USA" },
  },
  {
    registryNumber: "LR-TALLEST-MINARET", slug: "tallest-minaret", title: "Tallest minaret",
    category: "Engineering", subcategory: "Structures", direction: "MAXIMIZE",
    metricName: "Height of the tallest minaret", unit: "meters",
    formalStatement: "The height of the tallest minaret in the world.",
    summary: "The minaret of the Djamaa el Djazaïr (Great Mosque of Algiers), opened in April 2019, rises 265 m, making it the world's tallest minaret. The mosque is the third-largest in the world.",
    value: "265",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Published building specifications.",
    source: { title: "Wikipedia — Djamaa el Djazaïr", url: "https://en.wikipedia.org/wiki/Djamaa_el_Djaza%C3%AFr", date: "2019-04-01", location: "Algiers, Algeria" },
  },
  {
    registryNumber: "LR-TALLEST-CLOCK-TOWER", slug: "tallest-clock-tower", title: "Tallest clock tower",
    category: "Engineering", subcategory: "Structures", direction: "MAXIMIZE",
    metricName: "Height of the tallest clock tower", unit: "meters",
    formalStatement: "The height of the tallest building or tower bearing a clock.",
    summary: "The Makkah Royal Clock Tower, the central tower of the Abraj Al Bait complex in Mecca, Saudi Arabia, completed in 2012, stands 601 m tall and is recognized by Guinness World Records as the tallest clock tower in the world.",
    value: "601",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "CTBUH height data and Guinness World Records certification.",
    source: { title: "CTBUH Skyscraper Center — Makkah Royal Clock Tower", url: "https://www.skyscrapercenter.com/building/makkah-royal-clock-tower/84", date: "2012-01-01", location: "Mecca, Saudi Arabia" },
  },
  {
    registryNumber: "LR-LARGEST-CLOCK-FACE", slug: "largest-clock-face", title: "Largest clock face",
    category: "Engineering", subcategory: "Structures", direction: "MAXIMIZE",
    metricName: "Diameter of the largest clock face", unit: "meters",
    formalStatement: "The diameter of the largest clock face in the world.",
    summary: "Each of the four clock faces on the Makkah Royal Clock Tower in Mecca is 43 m in diameter — the largest clock faces in the world, mounted about 400 m above the ground.",
    value: "43",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Published building specifications.",
    source: { title: "Wikipedia — List of largest clock faces", url: "https://en.wikipedia.org/wiki/List_of_largest_clock_faces", date: "2012-01-01", location: "Mecca, Saudi Arabia" },
  },
  {
    registryNumber: "LR-TALLEST-FLAGPOLE", slug: "tallest-flagpole", title: "Tallest flagpole",
    category: "Engineering", subcategory: "Structures", direction: "MAXIMIZE",
    metricName: "Height of the tallest flagpole", unit: "meters",
    formalStatement: "The height of the tallest unsupported flagpole in the world.",
    summary: "The flagpole in Egypt's New Administrative Capital east of Cairo, completed in 2021, stands 201.952 m tall and holds the Guinness World Record for the tallest flagpole, surpassing the 171 m Jeddah Flagpole in Saudi Arabia.",
    value: "201.952",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Guinness World Records certification.",
    source: { title: "Guinness World Records — Tallest flagpole", url: "https://www.guinnessworldrecords.com/world-records/tallest-unsupported-flagpole", date: "2021-01-01", location: "New Administrative Capital, Egypt" },
  },
  {
    registryNumber: "LR-LONGEST-ROLLER-COASTER", slug: "longest-roller-coaster", title: "Longest roller coaster",
    category: "Engineering", subcategory: "Amusement Rides", direction: "MAXIMIZE",
    metricName: "Track length of the longest roller coaster", unit: "meters",
    formalStatement: "The track length of the longest roller coaster in the world.",
    summary: "Falcons Flight at Six Flags Qiddiya City in Saudi Arabia, built by Intamin and opened on 31 December 2025, has a track length of about 4,250 m, ending the 25-year reign of Japan's Steel Dragon 2000 (2,479 m) as the world's longest roller coaster.",
    value: "4250",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Manufacturer and Roller Coaster DataBase specifications.",
    source: { title: "Wikipedia — Falcons Flight", url: "https://en.wikipedia.org/wiki/Falcons_Flight", date: "2025-12-31", location: "Qiddiya City, Saudi Arabia" },
  },
  {
    registryNumber: "LR-TALLEST-ROLLER-COASTER-FALCONS-FLIGHT", slug: "tallest-roller-coaster", title: "Tallest roller coaster",
    category: "Engineering", subcategory: "Amusement Rides", direction: "MAXIMIZE",
    metricName: "Height of the tallest roller coaster", unit: "meters",
    formalStatement: "The structural height of the tallest roller coaster in the world.",
    summary: "Falcons Flight at Six Flags Qiddiya City, Saudi Arabia, opened on 31 December 2025 with a height of 163 m and an overall elevation change of about 195 m by using the natural cliffs of the site, making it the world's tallest roller coaster and the first 'exa coaster'.",
    value: "163",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Roller Coaster DataBase specifications.",
    source: { title: "Wikipedia — Falcons Flight", url: "https://en.wikipedia.org/wiki/Falcons_Flight", date: "2025-12-31", location: "Qiddiya City, Saudi Arabia" },
  },
  // --- Materials Science ---
  {
    registryNumber: "LR-MOST-MALLEABLE-METAL", slug: "most-malleable-metal", title: "Most malleable metal",
    category: "Materials Science", subcategory: "Metals", direction: "MAXIMIZE",
    metricName: "Area of sheet into which one gram of the metal can be beaten", unit: "square meters per gram",
    formalStatement: "The metal that can be hammered into the thinnest, largest sheet per unit mass.",
    summary: "Gold is the most malleable metal: a single gram can be beaten into a sheet of about 1 square meter, and gold leaf can be made thin enough to be semi-transparent, transmitting greenish-blue light.",
    value: "1",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Long-established goldbeating practice and materials-handbook data.",
    source: { title: "Wikipedia — Gold", url: "https://en.wikipedia.org/wiki/Gold", date: "2026-10-05", location: "Global" },
  },
  {
    registryNumber: "LR-DISCOVERY-OF-SUPERCONDUCTIVITY", slug: "discovery-of-superconductivity", title: "Discovery of superconductivity",
    category: "Materials Science", subcategory: "Superconductors", direction: "MINIMIZE",
    metricName: "Year superconductivity was first observed", unit: "year (CE)",
    formalStatement: "The year in which a material was first observed to lose all electrical resistance below a critical temperature.",
    summary: "Heike Kamerlingh Onnes discovered superconductivity on 8 April 1911 in Leiden, when the electrical resistance of solid mercury cooled with liquid helium vanished below about 4.2 K. He received the 1913 Nobel Prize in Physics for his low-temperature work.",
    value: "1911",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Laboratory notebooks and Onnes's 1911 publications in the Communications from the Physical Laboratory at Leiden.",
    source: { title: "Nobel Prize — Heike Kamerlingh Onnes, Facts", url: "https://www.nobelprize.org/prizes/physics/1913/onnes/facts/", date: "1911-04-08", location: "Leiden, Netherlands" },
  },
  {
    registryNumber: "LR-FIRST-HIGH-TEMPERATURE-SUPERCONDUCTOR", slug: "first-high-temperature-superconductor", title: "First high-temperature superconductor",
    category: "Materials Science", subcategory: "Superconductors", direction: "MINIMIZE",
    metricName: "Year the first high-temperature (cuprate) superconductor was discovered", unit: "year (CE)",
    formalStatement: "The year in which the first high-temperature superconductor was discovered.",
    summary: "In 1986 IBM Zürich researchers Georg Bednorz and K. Alex Müller discovered superconductivity at about 35 K in a lanthanum barium copper oxide — the first high-temperature superconductor, which earned them the 1987 Nobel Prize in Physics.",
    value: "1986",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Peer-reviewed publication in Zeitschrift für Physik B (1986).",
    source: { title: "Nobel Prize in Physics 1987 — Bednorz and Müller", url: "https://www.nobelprize.org/prizes/physics/1987/summary/", date: "1986-04-17", location: "IBM Zürich Research Laboratory, Switzerland" },
  },
  {
    registryNumber: "LR-FIRST-ISOLATION-OF-GRAPHENE", slug: "first-isolation-of-graphene", title: "First isolation of graphene",
    category: "Materials Science", subcategory: "Two-Dimensional Materials", direction: "MINIMIZE",
    metricName: "Year graphene was first isolated and characterized", unit: "year (CE)",
    formalStatement: "The year in which single-layer graphene was first isolated and its electronic properties characterized.",
    summary: "In 2004 Andre Geim and Konstantin Novoselov at the University of Manchester isolated graphene by peeling layers from graphite with adhesive tape and characterized its electronic properties, work recognized with the 2010 Nobel Prize in Physics.",
    value: "2004",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Peer-reviewed publication in Science (2004).",
    source: { title: "Nobel Prize in Physics 2010 — Geim and Novoselov", url: "https://www.nobelprize.org/prizes/physics/2010/summary/", date: "2004-10-22", location: "University of Manchester, England" },
  },
  {
    registryNumber: "LR-FIRST-AEROGEL", slug: "first-aerogel", title: "First aerogel",
    category: "Materials Science", subcategory: "Porous Materials", direction: "MINIMIZE",
    metricName: "Year the first aerogel was produced", unit: "year (CE)",
    formalStatement: "The year in which the first aerogel was created.",
    summary: "Samuel Stephens Kistler created the first documented aerogel in 1931 by replacing the liquid in a silica gel with a gas through supercritical drying, which avoided the collapse that ordinary evaporation causes.",
    value: "1931",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Kistler's 1931 letter to Nature, 'Coherent Expanded Aerogels and Jellies'.",
    source: { title: "Nature — Coherent Expanded Aerogels and Jellies", url: "https://www.nature.com/articles/127741a0", date: "1931-05-16", location: "College of the Pacific, Stockton, California, USA" },
  },
  {
    registryNumber: "LR-FIRST-METALLIC-GLASS", slug: "first-metallic-glass", title: "First metallic glass",
    category: "Materials Science", subcategory: "Metals", direction: "MINIMIZE",
    metricName: "Year the first metallic glass was reported", unit: "year (CE)",
    formalStatement: "The year in which the first amorphous (glassy) metal alloy was produced and reported.",
    summary: "The first reported metallic glass, a gold–silicon alloy (Au75Si25), was produced at Caltech by W. Klement, R. H. Willens and Pol Duwez by rapidly quenching the molten alloy, and published in Nature in 1960.",
    value: "1960",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Peer-reviewed publication in Nature (1960).",
    source: { title: "Nature — Non-crystalline Structure in Solidified Gold–Silicon Alloys", url: "https://www.nature.com/articles/187869b0", date: "1960-09-03", location: "Caltech, Pasadena, California, USA" },
  },
  {
    registryNumber: "LR-FIRST-SYNTHETIC-DIAMOND", slug: "first-synthetic-diamond", title: "First synthetic diamond",
    category: "Materials Science", subcategory: "Synthetic Materials", direction: "MINIMIZE",
    metricName: "Year diamond was first synthesized", unit: "year (CE)",
    formalStatement: "The year in which diamond was first reproducibly synthesized from non-diamond carbon.",
    summary: "The first known diamond synthesis was achieved on 16 February 1953 in Stockholm by the Swedish electrical company ASEA, though it was not reported at the time. General Electric's Tracy Hall independently achieved the first commercially successful synthesis on 16 December 1954.",
    value: "1953",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Company records of ASEA and General Electric.",
    source: { title: "Wikipedia — Synthetic diamond", url: "https://en.wikipedia.org/wiki/Synthetic_diamond", date: "1953-02-16", location: "Stockholm, Sweden" },
  },
  {
    registryNumber: "LR-FIRST-COMMERCIALLY-SUCCESSFUL-SYNTHETIC-THERMOPLASTIC", slug: "first-commercially-successful-synthetic-thermoplastic", title: "First commercially successful synthetic thermoplastic",
    category: "Materials Science", subcategory: "Polymers", direction: "MINIMIZE",
    metricName: "Year the first commercially successful synthetic thermoplastic polymer was synthesized", unit: "year (CE)",
    formalStatement: "The year in which the first commercially successful synthetic thermoplastic polymer was first made.",
    summary: "Nylon 66, the first nylon, was synthesized on 28 February 1935 by Wallace Hume Carothers at DuPont's Experimental Station in Delaware. Nylon became the first commercially successful synthetic thermoplastic polymer.",
    value: "1935",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "DuPont laboratory records.",
    source: { title: "American Chemical Society — Foundations of Polymer Science: Wallace Carothers and the Development of Nylon", url: "https://www.acs.org/", date: "1935-02-28", location: "DuPont Experimental Station, Wilmington, Delaware, USA" },
  },
  {
    registryNumber: "LR-INVENTION-OF-PORTLAND-CEMENT", slug: "invention-of-portland-cement", title: "Invention of Portland cement",
    category: "Materials Science", subcategory: "Construction Materials", direction: "MINIMIZE",
    metricName: "Year Portland cement was patented", unit: "year (CE)",
    formalStatement: "The year in which Portland cement, the most common modern cement, was patented.",
    summary: "Joseph Aspdin of Leeds, England, patented Portland cement in 1824, naming it after the pale Portland stone it resembled once hardened. Portland cement is now the basic ingredient of most concrete, mortar and grout.",
    value: "1824",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "British patent records.",
    source: { title: "Wikipedia — Portland cement", url: "https://en.wikipedia.org/wiki/Portland_cement", date: "1824-10-21", location: "Leeds, England" },
  },
  {
    registryNumber: "LR-FIRST-INEXPENSIVE-MASS-PRODUCTION-OF-STEEL", slug: "first-inexpensive-mass-production-of-steel", title: "First inexpensive mass-production process for steel",
    category: "Materials Science", subcategory: "Metals", direction: "MINIMIZE",
    metricName: "Year the first inexpensive industrial process for mass-producing steel was patented", unit: "year (CE)",
    formalStatement: "The year in which the first inexpensive industrial process for mass-producing steel from molten pig iron was patented.",
    summary: "Henry Bessemer patented the Bessemer process in 1856, blowing air through molten pig iron to burn off impurities. It was the first inexpensive industrial process for the mass production of steel.",
    value: "1856",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "British patent records.",
    source: { title: "Wikipedia — Bessemer process", url: "https://en.wikipedia.org/wiki/Bessemer_process", date: "1856-01-01", location: "England" },
  },
  // --- Geography ---
  {
    registryNumber: "LR-LARGEST-RIVER-DELTA", slug: "largest-river-delta", title: "Largest river delta",
    category: "Geography", subcategory: "Rivers", direction: "MAXIMIZE",
    metricName: "Area of the largest river delta", unit: "square kilometers",
    formalStatement: "The area of the largest river delta on Earth.",
    summary: "The Ganges–Brahmaputra Delta (Ganges Delta), lying mostly in Bangladesh and the Indian state of West Bengal, covers more than 105,000 km² and is the largest river delta in the world.",
    value: "105000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Published geographic estimates.",
    source: { title: "Wikipedia — Ganges Delta", url: "https://en.wikipedia.org/wiki/Ganges_Delta", date: "2026-10-05", location: "Bangladesh and West Bengal, India" },
  },
  {
    registryNumber: "LR-LONGEST-RIVER-IN-AUSTRALIA", slug: "longest-river-in-australia", title: "Longest river in Australia",
    category: "Geography", subcategory: "Rivers", direction: "MAXIMIZE",
    metricName: "Length of the longest river in Australia", unit: "kilometers",
    formalStatement: "The length of the longest river in Australia.",
    summary: "The Murray River, which flows 2,508 km from the Australian Alps to the Southern Ocean in South Australia, is Australia's longest river.",
    value: "2508",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Geoscience Australia figures.",
    source: { title: "Geoscience Australia — Longest rivers", url: "https://www.ga.gov.au/", date: "2026-10-05", location: "New South Wales, Victoria and South Australia, Australia" },
  },
  {
    registryNumber: "LR-HIGHEST-MOUNTAIN-IN-MAINLAND-AUSTRALIA", slug: "highest-mountain-in-mainland-australia", title: "Highest mountain in mainland Australia",
    category: "Geography", subcategory: "Mountains", direction: "MAXIMIZE",
    metricName: "Elevation of the highest mountain on the Australian mainland", unit: "meters",
    formalStatement: "The elevation of the highest summit on mainland Australia.",
    summary: "Mount Kosciuszko in the Snowy Mountains of New South Wales rises 2,228 m, making it the highest mountain on the Australian mainland.",
    value: "2228",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Geoscience Australia survey data.",
    source: { title: "Geoscience Australia — Highest mountains", url: "https://www.ga.gov.au/", date: "2026-10-05", location: "New South Wales, Australia" },
  },
  {
    registryNumber: "LR-HIGHEST-COUNTRY-BY-AVERAGE-ELEVATION", slug: "highest-country-by-average-elevation", title: "Highest country by average elevation",
    category: "Geography", subcategory: "Countries", direction: "MAXIMIZE",
    metricName: "Mean elevation of a country's land surface", unit: "meters",
    formalStatement: "The highest mean elevation of the land surface of any country.",
    summary: "Bhutan has the highest average elevation of any country, about 3,280 m above sea level, ahead of Nepal (about 3,265 m) and Tajikistan (about 3,186 m).",
    value: "3280",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Published average-elevation estimates.",
    source: { title: "Wikipedia — List of countries by average elevation", url: "https://en.wikipedia.org/wiki/List_of_countries_by_average_elevation", date: "2026-10-05", location: "Bhutan" },
  },
  {
    registryNumber: "LR-MOST-POPULOUS-LANDLOCKED-COUNTRY", slug: "most-populous-landlocked-country", title: "Most populous landlocked country",
    category: "Geography", subcategory: "Countries", direction: "MAXIMIZE",
    metricName: "Population of the most populous landlocked country", unit: "people",
    formalStatement: "The population of the most populous country without a coastline.",
    summary: "Ethiopia, landlocked since Eritrea's independence in 1993, is the most populous landlocked country in the world with about 138 million inhabitants as of 2026, making it also Africa's second most populous country.",
    value: "138000000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "National and UN population estimates.",
    source: { title: "CIA World Factbook — Ethiopia", url: "https://www.cia.gov/the-world-factbook/countries/ethiopia/", date: "2026-10-05", location: "Ethiopia" },
  },
  {
    registryNumber: "LR-LARGEST-COUNTRY-IN-AFRICA", slug: "largest-country-in-africa", title: "Largest country in Africa",
    category: "Geography", subcategory: "Countries", direction: "MAXIMIZE",
    metricName: "Area of the largest African country", unit: "square kilometers",
    formalStatement: "The total area of the largest country in Africa.",
    summary: "Algeria, covering 2,381,741 km², has been the largest country in Africa since the 2011 breakup of Sudan; it is also the largest country of the Mediterranean basin and the tenth largest in the world.",
    value: "2381741",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "National and UN statistical data.",
    source: { title: "Wikipedia — Algeria", url: "https://en.wikipedia.org/wiki/Algeria", date: "2026-10-05", location: "Algeria" },
  },
  {
    registryNumber: "LR-LARGEST-LAKE-ENTIRELY-IN-EUROPE", slug: "largest-lake-entirely-in-europe", title: "Largest lake entirely in Europe",
    category: "Geography", subcategory: "Lakes", direction: "MAXIMIZE",
    metricName: "Surface area of the largest lake located entirely in Europe", unit: "square kilometers",
    formalStatement: "The surface area of the largest lake lying entirely within Europe.",
    summary: "Lake Ladoga in north-western Russia, near Saint Petersburg, has an average surface area of about 17,891 km² (excluding islands), making it the largest lake located entirely in Europe.",
    value: "17891",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Published limnological data.",
    source: { title: "Wikipedia — Lake Ladoga", url: "https://en.wikipedia.org/wiki/Lake_Ladoga", date: "2026-10-05", location: "Republic of Karelia and Leningrad Oblast, Russia" },
  },
  {
    registryNumber: "LR-LARGEST-ISLAND-IN-EUROPE", slug: "largest-island-in-europe", title: "Largest island in Europe",
    category: "Geography", subcategory: "Islands", direction: "MAXIMIZE",
    metricName: "Area of the largest European island", unit: "square kilometers",
    formalStatement: "The area of the largest island in Europe.",
    summary: "Great Britain, with an area of 209,331 km², is the largest island in Europe and the largest of the British Isles, and the ninth-largest island in the world.",
    value: "209331",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Ordnance Survey and UNEP island data.",
    source: { title: "Wikipedia — Great Britain", url: "https://en.wikipedia.org/wiki/Great_Britain", date: "2026-10-05", location: "United Kingdom" },
  },
  {
    registryNumber: "LR-LARGEST-ISLAND-IN-ASIA", slug: "largest-island-in-asia", title: "Largest island in Asia",
    category: "Geography", subcategory: "Islands", direction: "MAXIMIZE",
    metricName: "Area of the largest Asian island", unit: "square kilometers",
    formalStatement: "The area of the largest island in Asia.",
    summary: "Borneo, shared by Indonesia, Malaysia and Brunei, covers about 743,330 km², making it the largest island in Asia and the third-largest island in the world after Greenland and New Guinea.",
    value: "743330",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Published geographic area estimates (figures range from about 743,000 to 748,000 km²).",
    source: { title: "Wikipedia — Borneo", url: "https://en.wikipedia.org/wiki/Borneo", date: "2026-10-05", location: "Indonesia, Malaysia and Brunei" },
  },
  {
    registryNumber: "LR-LARGEST-COUNTRY-IN-SOUTH-AMERICA", slug: "largest-country-in-south-america", title: "Largest country in South America",
    category: "Geography", subcategory: "Countries", direction: "MAXIMIZE",
    metricName: "Area of the largest South American country", unit: "square kilometers",
    formalStatement: "The total area of the largest country in South America.",
    summary: "Brazil, with a total area of about 8,515,767 km² according to the Brazilian Institute of Geography and Statistics (IBGE), is the largest country in South America and the fifth-largest country in the world.",
    value: "8515767",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official IBGE territorial area figure.",
    source: { title: "IBGE — Território brasileiro", url: "https://www.ibge.gov.br/", date: "2026-10-05", location: "Brazil" },
  },
  // --- Economics ---
  {
    registryNumber: "LR-FIRST-CASH-MACHINE", slug: "first-cash-machine", title: "First cash machine (ATM)",
    category: "Economics", subcategory: "Banking", direction: "MINIMIZE",
    metricName: "Year the first cash-dispensing machine was installed", unit: "year (CE)",
    formalStatement: "The year in which the first automated cash-dispensing machine was put into service at a bank.",
    summary: "The first cash machine was installed at Barclays Bank in Enfield, north London, on 27 June 1967, and was first used by the comedy actor Reg Varney as part of the launch publicity.",
    value: "1967",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Barclays company records.",
    source: { title: "Barclays — The world's first cash machine", url: "https://home.barclays/", date: "1967-06-27", location: "Enfield, London, England" },
  },
  {
    registryNumber: "LR-FIRST-NATIONAL-MINIMUM-WAGE-LAW", slug: "first-national-minimum-wage-law", title: "First national minimum-wage law",
    category: "Economics", subcategory: "Labor Economics", direction: "MINIMIZE",
    metricName: "Year the first national minimum-wage law was enacted", unit: "year (CE)",
    formalStatement: "The year in which a national government first enacted a law providing for legally binding minimum wages.",
    summary: "New Zealand's Industrial Conciliation and Arbitration Act 1894 created the first modern national system for setting legally enforceable minimum wages, followed by Australia (Victoria) in 1896 and the United Kingdom in 1909.",
    value: "1894",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Statute records.",
    source: { title: "Wikipedia — Minimum wage", url: "https://en.wikipedia.org/wiki/Minimum_wage", date: "1894-08-31", location: "New Zealand" },
  },
  {
    registryNumber: "LR-FIRST-VALUE-ADDED-TAX", slug: "first-value-added-tax", title: "First value-added tax",
    category: "Economics", subcategory: "Public Finance", direction: "MINIMIZE",
    metricName: "Year a modern value-added tax was first implemented", unit: "year (CE)",
    formalStatement: "The year in which a modern value-added tax was first put into effect.",
    summary: "French tax official Maurice Lauré implemented the first modern value-added tax on 10 April 1954 in France's Ivory Coast colony; judging it a success, France introduced it domestically in 1958. VAT is now used by more than 170 countries.",
    value: "1954",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "French fiscal records.",
    source: { title: "Wikipedia — Value-added tax", url: "https://en.wikipedia.org/wiki/Value-added_tax", date: "1954-04-10", location: "Ivory Coast (French colony)" },
  },
  {
    registryNumber: "LR-OLDEST-STOCK-INDEX-STILL-IN-USE", slug: "oldest-stock-index-still-in-use", title: "Oldest stock index still in use",
    category: "Economics", subcategory: "Financial Markets", direction: "MINIMIZE",
    metricName: "Year the oldest stock market index still in use was created", unit: "year (CE)",
    formalStatement: "The year of creation of the oldest stock market index still published.",
    summary: "The Dow Jones Transportation Average was created by Charles Dow on 3 July 1884 in the 'Customer's Afternoon Letter'. It is the oldest stock index still in use, predating the Dow Jones Industrial Average (1896).",
    value: "1884",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "S&P Dow Jones Indices records.",
    source: { title: "S&P Dow Jones Indices — Dow Jones Transportation Average", url: "https://www.spglobal.com/spdji/en/indices/equity/dow-jones-transportation-average/", date: "1884-07-03", location: "New York City, USA" },
  },
  {
    registryNumber: "LR-FIRST-ELECTRONIC-STOCK-MARKET", slug: "first-electronic-stock-market", title: "First fully electronic stock market",
    category: "Economics", subcategory: "Financial Markets", direction: "MINIMIZE",
    metricName: "Year the first fully electronic stock market began operations", unit: "year (CE)",
    formalStatement: "The year in which the first stock market operating entirely by electronic means opened.",
    summary: "The Nasdaq Stock Market, founded by the National Association of Securities Dealers, commenced operations on 8 February 1971 as the world's first fully electronic stock market, initially as a computerized quotation system.",
    value: "1971",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Nasdaq corporate history.",
    source: { title: "Nasdaq — Our history", url: "https://www.nasdaq.com/about", date: "1971-02-08", location: "New York City, USA" },
  },
  {
    registryNumber: "LR-OLDEST-BOND-STILL-PAYING-INTEREST", slug: "oldest-bond-still-paying-interest", title: "Oldest bond still paying interest",
    category: "Economics", subcategory: "Bonds", direction: "MINIMIZE",
    metricName: "Year of issue of the oldest bond still paying interest", unit: "year (CE)",
    formalStatement: "The year of issue of the oldest bond that still pays interest to its holder.",
    summary: "A perpetual bond issued on 15 May 1624 by the Dutch water board Lekdijk Bovendams, originally sold to Elsken Jorisdochter, still pays interest and is recognized by Guinness World Records as the oldest active bond.",
    value: "1624",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Guinness World Records certification and the original bond document.",
    source: { title: "Guinness World Records — Oldest active bond", url: "https://www.guinnessworldrecords.com/world-records/549529-oldest-active-bond", date: "1624-05-15", location: "Netherlands" },
  },
  {
    registryNumber: "LR-LARGEST-GOLD-COIN", slug: "largest-gold-coin", title: "Largest gold coin",
    category: "Economics", subcategory: "Currency", direction: "MAXIMIZE",
    metricName: "Mass of the largest gold coin ever minted", unit: "kilograms",
    formalStatement: "The mass of the largest gold coin ever produced.",
    summary: "In October 2011 the Perth Mint in Western Australia created a one-tonne gold Australian Kangaroo coin of 99.99% pure gold, breaking the record for the biggest and most valuable gold coin previously held by the Royal Canadian Mint's 100 kg Big Maple Leaf.",
    value: "1000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Guinness World Records certification.",
    source: { title: "The Perth Mint — The world's largest gold coin", url: "https://www.perthmint.com/", date: "2011-10-01", location: "Perth, Western Australia" },
  },
  {
    registryNumber: "LR-FIRST-COUNTRY-TO-ADOPT-BITCOIN-AS-LEGAL-TENDER", slug: "first-country-to-adopt-bitcoin-as-legal-tender", title: "First country to adopt bitcoin as legal tender",
    category: "Economics", subcategory: "Currency", direction: "MINIMIZE",
    metricName: "Year a country first made bitcoin legal tender", unit: "year (CE)",
    formalStatement: "The year in which a country first made a cryptocurrency legal tender.",
    summary: "El Salvador's Legislative Assembly passed the Bitcoin Law on 9 June 2021, and bitcoin became legal tender alongside the U.S. dollar on 7 September 2021 — the first country in the world to do so. The law was amended in 2025 to make acceptance voluntary.",
    value: "2021",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Legislative records of El Salvador.",
    source: { title: "Wikipedia — Bitcoin in El Salvador", url: "https://en.wikipedia.org/wiki/Bitcoin_in_El_Salvador", date: "2021-09-07", location: "El Salvador" },
  },
  {
    registryNumber: "LR-FIRST-CENTRAL-BANK-DIGITAL-CURRENCY", slug: "first-central-bank-digital-currency", title: "First nationwide central bank digital currency",
    category: "Economics", subcategory: "Currency", direction: "MINIMIZE",
    metricName: "Year the first nationwide central bank digital currency was launched", unit: "year (CE)",
    formalStatement: "The year in which a central bank first issued a digital currency to the general public nationwide.",
    summary: "The Central Bank of The Bahamas launched the Sand Dollar, a digital version of the Bahamian dollar, nationwide in October 2020, making the Bahamas the first country to issue a central bank digital currency to the public.",
    value: "2020",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Central Bank of The Bahamas records.",
    source: { title: "Central Bank of The Bahamas — Sand Dollar", url: "https://www.sanddollar.bs/", date: "2020-10-20", location: "The Bahamas" },
  },
];
