import type { FrontierRecord } from "./frontier-records-2026";

// Fourth real-world-records batch — math/CS, space exploration, technology, history, sports,
// economics, physics, geography, and culture. Every current-record-holder fact was verified
// against a live source before writing, since several of these (the supercomputer and pole-vault
// records in the prior batch; the internet-speed, transistor-node, and NFL field-goal records
// here) had changed within the last year and would have been wrong from training data alone.
// Two entries use an explicit "as of" framing rather than a final number, since the underlying
// quantity keeps changing while the record holder remains active (Cristiano Ronaldo's still-rising
// goal tally; Novak Djokovic's still-active Grand Slam count) — matching how Voyager 1's
// continuously increasing distance was handled in the prior batch.
export const WORLD_RECORDS_BATCH4: FrontierRecord[] = [
  // --- Mathematics / Computing ---
  {
    registryNumber: "LR-LARGEST-KNOWN-PRIME", slug: "largest-known-prime-number", title: "Largest known prime number",
    category: "Mathematics", subcategory: "Number Theory", direction: "MAXIMIZE",
    metricName: "Decimal digits of the largest known prime number", unit: "digits",
    formalStatement: "The greatest number of decimal digits in any number proven to be prime.",
    summary: "The Mersenne number 2^136,279,841 − 1, with 41,024,320 decimal digits, was discovered to be prime on October 12, 2024 by Luke Durant using the Great Internet Mersenne Prime Search (GIMPS) distributed computing project — the largest known prime as of 2026, and only the 52nd Mersenne prime ever found in GIMPS's 30-year search.",
    value: "41024320",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Distributed-computing primality proof via the Lucas-Lehmer test, independently verified by multiple GIMPS participants using different software and hardware.",
    source: { title: "GIMPS — Mersenne Prime Discovery: 2^136279841-1", url: "https://www.mersenne.org/primes/?press=M136279841", date: "2024-10-12", location: "Great Internet Mersenne Prime Search (distributed)" },
  },
  {
    registryNumber: "LR-BUSY-BEAVER-BB5", slug: "busy-beaver-bb5", title: "Busy Beaver function value, BB(5)",
    category: "Mathematics", subcategory: "Computability Theory", direction: "MAXIMIZE",
    metricName: "Maximum number of steps a halting 5-state, 2-symbol Turing machine can take", unit: "steps",
    formalStatement: "The exact value of the Busy Beaver function BB(5): the maximum number of steps any halting 5-state, 2-symbol Turing machine can take before halting, starting from a blank tape.",
    summary: "On July 2, 2024, the Busy Beaver Challenge — a distributed research effort led by Tristan Stérin — proved BB(5) = 47,176,870, closing a question open since a candidate machine was found in 1989. The proof was formally verified by a computer proof assistant (Rocq/Coq), ending a 60-year quest and closing what had been an open frontier the Registry now tracks as resolved.",
    value: "47176870",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "PROVEN",
    methodSummary: "Exhaustive case analysis over all candidate 5-state Turing machines, with the final proof formally verified in the Rocq (formerly Coq) proof assistant.",
    source: { title: "Scott Aaronson — BusyBeaver(5) is now known to be 47,176,870", url: "https://scottaaronson.blog/?p=8088", date: "2024-07-02", location: "Busy Beaver Challenge (distributed collaboration)" },
  },

  // --- Space Exploration ---
  {
    registryNumber: "LR-MOST-TIME-IN-SPACE", slug: "most-cumulative-time-in-space", title: "Most cumulative time in space",
    category: "Astrophysics", subcategory: "Space Exploration", direction: "MAXIMIZE",
    metricName: "Total cumulative days spent in space by an individual across all missions", unit: "days",
    formalStatement: "The greatest total cumulative time spent in space by a single individual, summed across all of their spaceflights.",
    summary: "Russian cosmonaut Oleg Kononenko surpassed 1,111 cumulative days in space across five missions to the International Space Station by the end of his fifth flight in September 2024 — the most time any human has ever spent in space, more than three full years total.",
    value: "1111",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Mission duration records maintained by Roscosmos and NASA, summed across all of Kononenko's spaceflights.",
    source: { title: "Roscosmos / NASA — Oleg Kononenko cumulative spaceflight record", url: "https://www.space.com/cosmonaut-oleg-kononenko-breaks-record-time-in-space", date: "2024-09-23", location: "International Space Station" },
  },
  {
    registryNumber: "LR-HIGHEST-ALTITUDE-FREEFALL", slug: "highest-altitude-freefall-jump", title: "Highest-altitude freefall jump",
    category: "Astrophysics", subcategory: "Space Exploration", direction: "MAXIMIZE",
    metricName: "Altitude of the highest human freefall jump from a balloon", unit: "ft",
    formalStatement: "The greatest altitude from which a human has jumped and freefallen (before parachute deployment) from a high-altitude balloon.",
    summary: "Alan Eustace, a Google executive, ascended via helium balloon and jumped from 135,908 ft (41.4 km) on October 24, 2014, breaking the sound barrier during his descent — the highest-altitude freefall jump ever recorded, surpassing Felix Baumgartner's 2012 Red Bull Stratos jump from 128,097 ft by roughly 7,800 ft.",
    value: "135908",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "GPS and barometric altitude tracking during the balloon ascent, certified as a world record by the sanctioning skydiving federation.",
    source: { title: "Smithsonian Air & Space — New High-Altitude Jump Record", url: "https://airandspace.si.edu/stories/editorial/new-high-altitude-jump", date: "2014-10-24", location: "Roswell, New Mexico, USA" },
  },
  {
    registryNumber: "LR-FIRST-HUMAN-SPACEFLIGHT", slug: "first-human-spaceflight", title: "First human spaceflight",
    category: "Astrophysics", subcategory: "Space Exploration", direction: "MAXIMIZE",
    metricName: "Duration of the first crewed orbital spaceflight", unit: "min",
    formalStatement: "The duration of the first spaceflight by a human being to reach orbit.",
    summary: "Soviet cosmonaut Yuri Gagarin became the first human in space aboard Vostok 1 on April 12, 1961, completing a single orbit of Earth in 108 minutes before landing by parachute after ejecting from the capsule — the flight that opened the era of human spaceflight.",
    value: "108",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official Soviet space program mission records, corroborated by international tracking of the flight.",
    source: { title: "NASA — 50th Anniversary of the Space Age", url: "https://www.nasa.gov/history/first-human-spaceflight/", date: "1961-04-12", location: "Vostok 1, Earth orbit" },
  },
  {
    registryNumber: "LR-FASTEST-SPACECRAFT-PARKER", slug: "fastest-human-made-object-by-speed", title: "Fastest human-made object (speed relative to the Sun)",
    category: "Astrophysics", subcategory: "Space Exploration", direction: "MAXIMIZE",
    metricName: "Maximum speed relative to the Sun reached by a human-made spacecraft", unit: "km/h",
    formalStatement: "The greatest speed relative to the Sun ever reached by a human-made object — a different metric from Apollo 10's speed record relative to Earth, since Parker Solar Probe's speed comes from its close solar orbit rather than an Earth-return trajectory.",
    summary: "NASA's Parker Solar Probe reached approximately 690,000 km/h (192 km/s) relative to the Sun during a close perihelion pass on December 24, 2024 — the fastest speed any human-made object has ever achieved, driven by the Sun's gravity as the probe dives to within 6.1 million km of the solar surface.",
    value: "690000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Tracked via NASA Deep Space Network telemetry and orbital mechanics calculations for the probe's trajectory.",
    source: { title: "NASA — Parker Solar Probe Mission", url: "https://www.nasa.gov/mission/parker-solar-probe/", date: "2024-12-24", location: "Parker Solar Probe, near-solar orbit" },
  },
  {
    registryNumber: "LR-JWST-LARGEST-SPACE-TELESCOPE", slug: "largest-space-telescope-mirror", title: "Largest space telescope mirror",
    category: "Astrophysics", subcategory: "Space Exploration", direction: "MAXIMIZE",
    metricName: "Primary mirror diameter of the largest telescope ever launched into space", unit: "m",
    formalStatement: "The greatest primary mirror diameter of any telescope operating in space, as opposed to ground-based observatories.",
    summary: "The James Webb Space Telescope, launched December 25, 2021, has a segmented primary mirror 6.5 m in diameter — the largest mirror ever launched into space, over six times the light-collecting area of the Hubble Space Telescope's 2.4 m mirror. Its 18 gold-coated beryllium segments unfolded after launch, since the mirror was too large to launch fully assembled.",
    value: "6.5",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Engineering specification from NASA, ESA, and the Canadian Space Agency, the telescope's operating partners.",
    source: { title: "NASA — James Webb Space Telescope: Mirrors", url: "https://webb.nasa.gov/content/observatory/ote/mirrors/index.html", date: "2021-12-25", location: "Sun-Earth L2 Lagrange point" },
  },

  // --- Technology ---
  {
    registryNumber: "LR-STRONGEST-MAGNETIC-FIELD", slug: "strongest-magnetic-field-created", title: "Strongest magnetic field ever created",
    category: "Computing", subcategory: "Physics Instrumentation", direction: "MAXIMIZE",
    metricName: "Peak magnetic field strength generated in a laboratory", unit: "T",
    formalStatement: "The highest magnetic field strength ever generated in a laboratory, by any method (including destructive, single-shot techniques).",
    summary: "A team at the University of Tokyo led by Shojiro Takeyama generated a magnetic field of 1,200 tesla in April 2018 using an electromagnetic flux-compression technique that destroys the coil in the process — the strongest magnetic field ever created in a laboratory, lasting about 40 microseconds. Non-destructive (reusable) magnets top out far lower, around 100 tesla for pulsed fields and under 50 tesla for continuous fields.",
    value: "1200",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Electromagnetic flux-compression generator, a single-use destructive technique, published in a peer-reviewed physics journal.",
    source: { title: "Guinness World Records — Strongest magnetic field created", url: "https://www.guinnessworldrecords.com/world-records/66147-strongest-magnetic-field-created", date: "2018-04-01", location: "University of Tokyo, Japan" },
  },
  {
    registryNumber: "LR-LARGEST-COMPUTER-CHIP", slug: "largest-computer-chip", title: "Largest single computer chip",
    category: "Computing", subcategory: "Semiconductor Engineering", direction: "MAXIMIZE",
    metricName: "Transistor count of the largest single-die computer chip", unit: "transistors",
    formalStatement: "The greatest number of transistors on a single, contiguous silicon die.",
    summary: "Cerebras Systems' Wafer-Scale Engine 3 (WSE-3), announced in 2024, packs 4 trillion transistors and 900,000 AI-optimized cores onto a single 21.5 cm-per-side chip cut from an entire 300mm silicon wafer — the largest single computer chip ever built, roughly 57 times larger than the biggest conventional GPU die.",
    value: "4000000000000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Manufacturer specification from Cerebras Systems, built on TSMC's 5-nanometer process.",
    source: { title: "Cerebras — Third-Generation Wafer Scale Engine", url: "https://www.cerebras.ai/press-release/cerebras-announces-third-generation-wafer-scale-engine", date: "2024-03-13", location: "Cerebras Systems, Sunnyvale, California, USA" },
  },
  {
    registryNumber: "LR-SMALLEST-TRANSISTOR-NODE", slug: "smallest-commercial-transistor-node", title: "Smallest commercial transistor manufacturing node",
    category: "Computing", subcategory: "Semiconductor Engineering", direction: "MINIMIZE",
    metricName: "Smallest process node in volume commercial semiconductor production", unit: "nm",
    formalStatement: "The smallest transistor process node scale in active, volume commercial semiconductor manufacturing.",
    summary: "TSMC began volume production of its N2 process — the industry's first commercial 2-nanometer-class node, using gate-all-around transistor architecture for the first time — in late 2025, ramping to roughly 90,000 wafers per month across two Taiwan fabs by late 2026. It is the smallest commercial transistor node in production as of 2026, offering roughly 10-15% better performance and 25-30% lower power than the prior 3nm node.",
    value: "2",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Manufacturer-disclosed process node specifications and production ramp figures from TSMC.",
    source: { title: "TSMC — N2 Technology", url: "https://www.tsmc.com/english/dedicatedFoundry/technology/logic/l_2nm", date: "2025-12-01", location: "TSMC fabs, Hsinchu and Kaohsiung, Taiwan" },
  },
  {
    registryNumber: "LR-MOST-POWERFUL-LASER", slug: "most-powerful-laser", title: "Most powerful laser",
    category: "Computing", subcategory: "Physics Instrumentation", direction: "MAXIMIZE",
    metricName: "Peak power of the most powerful operational laser facility", unit: "PW",
    formalStatement: "The greatest peak power output of any operational laser facility.",
    summary: "The Extreme Light Infrastructure Nuclear Physics (ELI-NP) facility in Măgurele, Romania, operates two 10-petawatt lasers that can be combined to focus 20 petawatts onto a single target — the most powerful operational laser system in the world as of 2026. Higher-power exawatt-class facilities remain in the planning and early-construction stages globally.",
    value: "20",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Peak power specification published by the ELI-NP facility, part of the European Union's Extreme Light Infrastructure project.",
    source: { title: "ELI-NP — High Power Laser System", url: "https://www.eli-np.ro/", date: "2019-03-01", location: "Măgurele, Romania" },
  },
  {
    registryNumber: "LR-SHORTEST-LASER-PULSE", slug: "shortest-laser-pulse-ever-created", title: "Shortest laser pulse ever created",
    category: "Computing", subcategory: "Physics Instrumentation", direction: "MINIMIZE",
    metricName: "Duration of the shortest experimentally measured isolated light pulse", unit: "as",
    formalStatement: "The shortest duration of any isolated light pulse experimentally generated and measured.",
    summary: "Researchers at Kansas State University generated and characterized an isolated light pulse lasting just 18 attoseconds (18 x 10^-18 seconds) in 2026 — the shortest light pulse ever experimentally measured, part of the broader field of attosecond science used to observe electron motion inside atoms and molecules in real time.",
    value: "18",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Attosecond streaking measurement technique, published in a peer-reviewed physics journal.",
    source: { title: "Kansas State University — Shortest light pulse ever created", url: "https://phys.org/news/2025-12-shortest-pulse-captures-ultrafast-electron.html", date: "2025-12-01", location: "Kansas State University, USA" },
  },
  {
    registryNumber: "LR-FASTEST-INTERNET-DEPLOYED", slug: "fastest-internet-speed-over-deployed-infrastructure", title: "Fastest data transmission over deployed fiber infrastructure",
    category: "Computing", subcategory: "Networking", direction: "MAXIMIZE",
    metricName: "Data transmission rate achieved over existing, commercially installed optical fiber", unit: "Tbit/s",
    formalStatement: "The highest data transmission rate demonstrated over already-installed, commercially deployed optical fiber infrastructure — a different, more practically relevant metric than pure laboratory records set over specially constructed fiber.",
    summary: "A team including UCL researchers achieved a data transmission rate of 450 terabits per second over existing, field-deployed optical fiber in March 2026, using additional wavelength bands beyond what standard equipment uses — a 50% increase over the same team's own 300.28 Tbit/s record from five months earlier. This is distinct from pure laboratory records (Japan's NICT reported 1.02 petabits/s in 2025) which use specially constructed fiber not representative of installed networks.",
    value: "450",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Multi-band (E+S+C+L) wavelength-division multiplexing over commercially installed fiber, presented at the OFC optical fiber conference.",
    source: { title: "UCL News — New fibre optic data transmission speed record", url: "https://www.ucl.ac.uk/news/2026/apr/new-fibre-optic-data-transmission-speed-record", date: "2026-03-01", location: "University College London, UK" },
  },
  {
    registryNumber: "LR-LARGEST-TELESCOPE-MIRROR-GROUND", slug: "largest-operational-ground-telescope-mirror", title: "Largest operational ground-based telescope mirror",
    category: "Astrophysics", subcategory: "Astronomical Instrumentation", direction: "MAXIMIZE",
    metricName: "Primary mirror diameter of the largest currently operating ground-based optical telescope", unit: "m",
    formalStatement: "The greatest primary mirror diameter of any ground-based optical telescope currently in operation. Larger telescopes (the 39 m Extremely Large Telescope and 25.4 m Giant Magellan Telescope) are under construction but not yet operational as of 2026.",
    summary: "The Gran Telescopio Canarias, on the Canary Island of La Palma, Spain, has a segmented primary mirror 10.4 m in diameter and has been the largest operational single optical telescope in the world since it began operations in 2009.",
    value: "10.4",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Engineering specification published by the Instituto de Astrofísica de Canarias, the telescope's operator.",
    source: { title: "Gran Telescopio Canarias — Official Site", url: "https://www.gtc.iac.es/", date: "2009-07-24", location: "Roque de los Muchachos Observatory, La Palma, Spain" },
  },

  // --- History ---
  {
    registryNumber: "LR-LARGEST-EMPIRE-BY-AREA", slug: "largest-empire-by-land-area", title: "Largest empire by land area",
    category: "Earth & Climate", subcategory: "History", direction: "MAXIMIZE",
    metricName: "Total land area controlled by an empire at its territorial peak", unit: "km²",
    formalStatement: "The greatest total land area ever controlled by a single empire at its peak, whether contiguous or not.",
    summary: "The British Empire covered approximately 35.5 million km² at its territorial peak in 1920 — roughly a quarter of Earth's land area, spanning every inhabited continent — making it the largest empire in history by total area, though not contiguous. The largest contiguous land empire in history was the Mongol Empire, which controlled roughly 24 million km² of connected territory in the 13th century.",
    value: "35500000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Historical territorial area compiled by historians from period records and modern cartographic reconstruction.",
    source: { title: "Encyclopaedia Britannica — British Empire", url: "https://www.britannica.com/place/British-Empire", date: "1920-01-01", location: "Global, multiple continents" },
  },
  {
    registryNumber: "LR-LONGEST-REIGNING-MONARCH", slug: "longest-reigning-monarch-verified", title: "Longest verified reign of any monarch",
    category: "Earth & Climate", subcategory: "History", direction: "MAXIMIZE",
    metricName: "Length of reign of the longest-reigning verified monarch in history", unit: "years",
    formalStatement: "The greatest length of reign of any monarch in recorded history, verified by contemporary historical records.",
    summary: "Louis XIV of France reigned for 72 years and 110 days, from his accession at age 4 in 1643 (with regents governing until his majority) until his death in 1715 — the longest verified reign of any monarch in history. Some ancient or legendary reigns are claimed to be longer, but lack the same level of contemporary documentary verification.",
    value: "72",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Contemporary French royal court records and historical chronicles, cross-referenced by modern historians.",
    source: { title: "Encyclopaedia Britannica — Louis XIV", url: "https://www.britannica.com/biography/Louis-XIV-king-of-France", date: "1715-09-01", location: "Kingdom of France" },
  },
  {
    registryNumber: "LR-OLDEST-UNIVERSITY", slug: "oldest-continuously-operating-university", title: "Oldest continuously operating university",
    category: "Earth & Climate", subcategory: "History", direction: "MINIMIZE",
    metricName: "Founding year of the oldest continuously operating university", unit: "year",
    formalStatement: "The founding year of the oldest institution of higher education that has continuously operated as a university to the present day.",
    summary: "The University of Bologna, in Italy, was founded in 1088 and has operated continuously since — recognized by historians and the university itself as the oldest continuously operating university in the Western world. Older institutions of learning existed elsewhere (such as Al-Qarawiyyin in Morocco, founded 859 CE), but their classification as a 'university' in the same institutional sense is debated among historians.",
    value: "1088",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Institutional founding records and continuous operational history, documented by the university and independent historians.",
    source: { title: "University of Bologna — History", url: "https://www.unibo.it/en/university/who-we-are/our-history/university-from-13th-to-20th-century", date: "1088-01-01", location: "Bologna, Italy" },
  },
  {
    registryNumber: "LR-LONGEST-WALL", slug: "longest-wall-ever-built", title: "Longest wall ever built",
    category: "Engineering", subcategory: "Civil Engineering", direction: "MAXIMIZE",
    metricName: "Total length of the longest defensive wall structure, including all branches", unit: "km",
    formalStatement: "The greatest total length of any human-built wall structure, including all branches and sections built across different historical periods.",
    summary: "China's Great Wall, built and rebuilt across multiple dynasties from roughly the 7th century BCE to the 17th century CE, totals approximately 21,196 km when every wall, trench, and natural defensive barrier from all its branches is included, per a comprehensive 2012 survey by China's State Administration of Cultural Heritage — the longest wall ever built by a wide margin.",
    value: "21196",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Comprehensive archaeological and satellite survey of all wall sections, branches, and associated defensive structures, conducted by China's State Administration of Cultural Heritage.",
    source: { title: "China's State Administration of Cultural Heritage — Great Wall survey results", url: "https://www.chinadaily.com.cn/china/2012-06/05/content_15479242.htm", date: "2012-06-05", location: "Northern China" },
  },

  // --- Sports Records ---
  {
    registryNumber: "LR-MOST-MLB-HOME-RUNS", slug: "most-mlb-career-home-runs", title: "Most MLB career home runs",
    category: "Sports Records", subcategory: "Baseball", direction: "MAXIMIZE",
    metricName: "Career home runs hit in Major League Baseball", unit: "home runs",
    formalStatement: "The greatest number of home runs hit across a career in Major League Baseball.",
    summary: "Barry Bonds hit 762 home runs across his MLB career (1986-2007) — the all-time career record, seven more than Hank Aaron's previous record of 755. Bonds also holds the single-season record with 73 home runs in 2001.",
    value: "762",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official career statistics maintained by Major League Baseball.",
    source: { title: "Baseball-Reference — Career Home Run Leaders", url: "https://www.baseball-reference.com/leaders/HR_career.shtml", date: "2007-09-26", location: "Major League Baseball, USA" },
  },
  {
    registryNumber: "LR-MOST-FOOTBALL-GOALS-CAREER", slug: "most-career-goals-football", title: "Most career goals in football (soccer)",
    category: "Sports Records", subcategory: "Football", direction: "MAXIMIZE",
    metricName: "Career goals scored across club and international football", unit: "goals",
    formalStatement: "The greatest number of goals scored across a career in men's professional and international football, combining club and international appearances. This figure keeps increasing while the player remains active.",
    summary: "Cristiano Ronaldo has scored 979 career goals across club football (Sporting Lisbon, Manchester United, Real Madrid, Juventus, Al-Nassr) and international appearances for Portugal, as of September 2026 — the most in the history of men's football, and closing in on the milestone of 1,000. He also holds the record for most international goals (146) of any male player.",
    value: "979",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Cumulative goal tallies compiled from official club and international match records, tracked by football statistics services.",
    source: { title: "ESPN — Cristiano Ronaldo goal tracker: road to 1,000 career goals", url: "https://www.espn.com/soccer/story/_/id/46751020/cristiano-ronaldo-goal-tracker-road-1000-career-goals", date: "2026-09-01", location: "Club and international football, worldwide" },
  },
  {
    registryNumber: "LR-LONGEST-NFL-FIELD-GOAL", slug: "longest-nfl-field-goal", title: "Longest NFL field goal",
    category: "Sports Records", subcategory: "American Football", direction: "MAXIMIZE",
    metricName: "Longest successful field goal in an NFL regular season game", unit: "yd",
    formalStatement: "The longest field goal successfully kicked in an NFL regular-season game.",
    summary: "Cam Little of the Jacksonville Jaguars kicked a 68-yard field goal against the Las Vegas Raiders on November 2, 2025 — the longest field goal in NFL history, surpassing the previous record of 66 yards.",
    value: "68",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Officially measured and recorded by the NFL during a regular-season game.",
    source: { title: "NFL.com — Cam Little delivers longest field goal in NFL history", url: "https://www.nfl.com/videos/can-t-miss-play-68-yard-field-goal-cam-little-delivers-longest-fg-in-nfl-history", date: "2025-11-02", location: "EverBank Stadium, Jacksonville, Florida, USA" },
  },
  {
    registryNumber: "LR-MOST-POINTS-SINGLE-NBA-GAME", slug: "most-points-single-nba-game", title: "Most points scored in a single NBA game",
    category: "Sports Records", subcategory: "Basketball", direction: "MAXIMIZE",
    metricName: "Points scored by one player in a single NBA game", unit: "points",
    formalStatement: "The greatest number of points scored by a single player in one NBA game.",
    summary: "Wilt Chamberlain scored 100 points for the Philadelphia Warriors against the New York Knicks on March 2, 1962 — still the single-game scoring record over six decades later, and the only 100-point game in NBA history. No player has come within 19 points of it since Kobe Bryant's 81-point game in 2006.",
    value: "100",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official NBA box score from the game, corroborated by contemporary sports reporting.",
    source: { title: "NBA.com — Wilt Chamberlain's 100-point game", url: "https://www.nba.com/history/wilt-chamberlain-100-point-game", date: "1962-03-02", location: "Hershey, Pennsylvania, USA" },
  },
  {
    registryNumber: "LR-MOST-GRAND-SLAM-TITLES-MEN", slug: "most-grand-slam-singles-titles-men", title: "Most Grand Slam singles titles, men's tennis",
    category: "Sports Records", subcategory: "Tennis", direction: "MAXIMIZE",
    metricName: "Career Grand Slam singles titles won, men's tennis", unit: "titles",
    formalStatement: "The greatest number of Grand Slam (major) singles tennis titles won across a career by a male player. This figure could still increase while the player remains active.",
    summary: "Novak Djokovic has won 24 Grand Slam men's singles titles as of 2026, the most in tennis history, two ahead of Rafael Nadal's 22. Djokovic remained active and was pursuing a 25th title as of mid-2026, so this record could move again before the season ends.",
    value: "24",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official tournament records maintained by the four Grand Slam tournaments (Australian Open, French Open, Wimbledon, US Open) and the ATP.",
    source: { title: "ATP Tour — Novak Djokovic Grand Slam titles", url: "https://www.atptour.com/en/players/novak-djokovic/d643/overview", date: "2023-09-10", location: "Grand Slam tournaments, worldwide" },
  },

  // --- Economics ---
  {
    registryNumber: "LR-LARGEST-CORPORATE-BANKRUPTCY", slug: "largest-corporate-bankruptcy", title: "Largest corporate bankruptcy",
    category: "Economics", subcategory: "Corporate Finance", direction: "MAXIMIZE",
    metricName: "Total assets of a company at the time of its bankruptcy filing", unit: "USD",
    formalStatement: "The greatest total assets reported by any company at the time it filed for bankruptcy.",
    summary: "Lehman Brothers filed for Chapter 11 bankruptcy on September 15, 2008, reporting approximately $691 billion in assets at the time of filing — the largest corporate bankruptcy in history by a wide margin, and a central event of the 2008 global financial crisis.",
    value: "691000000000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Bankruptcy filing documents submitted to the U.S. Bankruptcy Court, Southern District of New York.",
    source: { title: "U.S. Courts — Lehman Brothers Holdings Inc. bankruptcy filing", url: "https://www.uscourts.gov/", date: "2008-09-15", location: "U.S. Bankruptcy Court, Southern District of New York" },
  },
  {
    registryNumber: "LR-LARGEST-IPO-EVER", slug: "largest-ipo-ever", title: "Largest initial public offering ever",
    category: "Economics", subcategory: "Corporate Finance", direction: "MAXIMIZE",
    metricName: "Capital raised in a single initial public offering", unit: "USD",
    formalStatement: "The greatest amount of capital raised in a single initial public offering (IPO) of a company's shares.",
    summary: "Saudi Aramco's initial public offering on the Riyadh stock exchange (Tadawul) in December 2019 raised $25.6 billion, later extended to $29.4 billion after an over-allotment option — the largest IPO in history, valuing the company at approximately $1.7 trillion at listing.",
    value: "29400000000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official IPO prospectus and Tadawul stock exchange listing filings.",
    source: { title: "Reuters — Aramco IPO raises $25.6 billion", url: "https://www.reuters.com/article/us-saudi-aramco-ipo/", date: "2019-12-11", location: "Tadawul, Riyadh, Saudi Arabia" },
  },
  {
    registryNumber: "LR-LARGEST-SOVEREIGN-WEALTH-FUND", slug: "largest-sovereign-wealth-fund", title: "Largest sovereign wealth fund",
    category: "Economics", subcategory: "Public Finance", direction: "MAXIMIZE",
    metricName: "Total assets under management of the largest sovereign wealth fund", unit: "USD",
    formalStatement: "The greatest total assets under management of any sovereign wealth fund.",
    summary: "Norway's Government Pension Fund Global, funded by the country's oil and gas revenues since 1996, held assets of approximately $1.7 trillion as of 2025 — the largest single sovereign wealth fund in the world, owning roughly 1.5% of all publicly listed shares globally.",
    value: "1700000000000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official fund holdings reported by Norges Bank Investment Management, the fund's manager.",
    source: { title: "Norges Bank Investment Management — Government Pension Fund Global", url: "https://www.nbim.no/en/", date: "2025-06-30", location: "Norway" },
  },

  // --- Physics / Chemistry ---
  {
    registryNumber: "LR-HOTTEST-MANMADE-TEMPERATURE", slug: "hottest-temperature-achieved", title: "Hottest temperature ever achieved",
    category: "Astrophysics", subcategory: "Particle Astrophysics", direction: "MAXIMIZE",
    metricName: "Highest temperature ever artificially achieved", unit: "°C",
    formalStatement: "The highest temperature ever artificially created, as measured in a controlled particle-physics experiment.",
    summary: "CERN's ALICE experiment at the Large Hadron Collider created a quark-gluon plasma — a state of matter last naturally present microseconds after the Big Bang — reaching temperatures of about 5.5 trillion degrees Celsius during lead-ion collisions reported in 2012, roughly 400,000 times hotter than the center of the Sun. It remains the hottest temperature humans have ever created.",
    value: "5500000000000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Temperature inferred from particle energy-loss measurements during heavy-ion collisions, published in a peer-reviewed physics paper by the ALICE Collaboration.",
    source: { title: "CERN — ALICE experiment achieves record temperature", url: "https://home.cern/news/press-release/cern/alice-experiment-cern-confirms-record-temperature-quark-gluon-plasma", date: "2012-08-13", location: "Large Hadron Collider, CERN, Switzerland" },
  },

  // --- Geography ---
  {
    registryNumber: "LR-HIGHEST-CAPITAL-CITY", slug: "highest-capital-city", title: "Highest capital city",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Elevation above sea level of the highest seat-of-government capital city", unit: "m",
    formalStatement: "The greatest elevation above sea level of any city that serves as the seat of national government.",
    summary: "La Paz, Bolivia's administrative capital and seat of government, sits at an average elevation of about 3,640 m (11,942 ft) above sea level — the highest capital city (by seat of government) in the world. Bolivia's constitutional capital, Sucre, is lower but does not house the executive and legislative branches.",
    value: "3640",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Standard geographic elevation survey data for the city center.",
    source: { title: "Encyclopaedia Britannica — La Paz", url: "https://www.britannica.com/place/La-Paz-Bolivia", date: "2022-01-01", location: "La Paz, Bolivia" },
  },
  {
    registryNumber: "LR-LARGEST-COUNTRY-AREA", slug: "largest-country-by-area", title: "Largest country by area",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Total land area of the largest sovereign country", unit: "km²",
    formalStatement: "The greatest total land area of any sovereign nation.",
    summary: "Russia covers approximately 17.1 million km² — nearly twice the area of the next-largest country, Canada (9.98 million km²) — spanning 11 time zones, making it by far the largest country on Earth by land area.",
    value: "17100000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Standard geographic area measurement compiled by the United Nations Statistics Division.",
    source: { title: "United Nations Statistics Division — Demographic Yearbook", url: "https://unstats.un.org/unsd/demographic-social/products/dyb/", date: "2022-01-01", location: "Russian Federation" },
  },
  {
    registryNumber: "LR-SMALLEST-COUNTRY-AREA", slug: "smallest-country-by-area", title: "Smallest country by area",
    category: "Earth & Climate", subcategory: "Geography", direction: "MINIMIZE",
    metricName: "Total land area of the smallest sovereign country", unit: "km²",
    formalStatement: "The smallest total land area of any sovereign, UN-recognized or widely recognized independent nation.",
    summary: "Vatican City, an independent city-state entirely enclosed within Rome, Italy, covers just 0.44 km² (0.17 sq mi) — smaller than most golf courses — making it by far the smallest sovereign country in the world, with a population of under 1,000.",
    value: "0.44",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Standard geographic area measurement per the Holy See's own official records.",
    source: { title: "Encyclopaedia Britannica — Vatican City", url: "https://www.britannica.com/place/Vatican-City", date: "2022-01-01", location: "Vatican City" },
  },
  {
    registryNumber: "LR-LARGEST-CORAL-REEF", slug: "largest-coral-reef-system", title: "Largest coral reef system",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Total area of the largest coral reef system", unit: "km²",
    formalStatement: "The greatest total area of any coral reef system on Earth.",
    summary: "The Great Barrier Reef off Australia's northeast coast covers approximately 344,400 km² and includes over 2,900 individual reefs — the largest coral reef system in the world, and the only living structure visible from space.",
    value: "344400",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Satellite and aerial survey mapping conducted by the Great Barrier Reef Marine Park Authority.",
    source: { title: "Great Barrier Reef Marine Park Authority — About the Reef", url: "https://www2.gbrmpa.gov.au/learn/reef-facts", date: "2022-01-01", location: "Coral Sea, off Queensland, Australia" },
  },
  {
    registryNumber: "LR-DRIEST-PLACE-EARTH", slug: "driest-place-on-earth", title: "Driest place on Earth",
    category: "Earth & Climate", subcategory: "Extreme Weather", direction: "MINIMIZE",
    metricName: "Average annual rainfall at the driest continuously monitored weather station", unit: "mm/yr",
    formalStatement: "The lowest average annual rainfall recorded at any continuously monitored weather station on Earth.",
    summary: "A weather station near Yungay in Chile's Atacama Desert recorded an average of just 0.5 mm (0.02 in) of rainfall per year between 1964 and 2001 — the lowest sustained rainfall average of any monitored location on Earth. Researchers studying the region's hyper-arid core have found soil conditions there comparable to Mars, useful for testing planetary exploration equipment.",
    value: "0.5",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Continuous rain-gauge monitoring at the Yungay weather station, published in a peer-reviewed geology study.",
    source: { title: "McKay et al., \"Temperature and moisture conditions for life in the extreme arid region of the Atacama Desert,\" Astrobiology (2003)", url: "https://www.liebertpub.com/doi/10.1089/153110703769016630", date: "2003-12-01", location: "Yungay, Atacama Desert, Chile" },
  },

  // --- Food & Culture, continued ---
  {
    registryNumber: "LR-TALLEST-STATUE", slug: "tallest-statue", title: "Tallest statue",
    category: "Food & Culture", subcategory: "Architecture", direction: "MAXIMIZE",
    metricName: "Height of the tallest statue in the world", unit: "m",
    formalStatement: "The greatest height of any free-standing statue in the world.",
    summary: "The Statue of Unity, depicting Indian statesman Sardar Vallabhbhai Patel, stands 182 m (597 ft) tall in Gujarat, India — completed in 2018, it is the tallest statue in the world, nearly twice the height of the Statue of Liberty including its pedestal.",
    value: "182",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Engineering specification published by the Gujarat state government, the statue's commissioning authority.",
    source: { title: "Statue of Unity — Official Site", url: "https://www.statueofunity.in.net/", date: "2018-10-31", location: "Kevadia, Gujarat, India" },
  },
  {
    registryNumber: "LR-LARGEST-STOCK-CRASH-PERCENTAGE", slug: "largest-single-day-stock-market-crash", title: "Largest single-day stock market crash (percentage)",
    category: "Economics", subcategory: "Financial History", direction: "MAXIMIZE",
    metricName: "Largest single-day percentage decline of a major stock market index", unit: "%",
    formalStatement: "The greatest single-day percentage decline recorded for a major stock market index.",
    summary: "On October 19, 1987 — 'Black Monday' — the Dow Jones Industrial Average fell 22.6% in a single trading day, the largest one-day percentage decline in the index's history, exceeding even the single-day drops during the 1929 crash. The cause remains debated among economists, though early program trading is widely cited as an amplifying factor.",
    value: "22.6",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official Dow Jones Industrial Average closing price data for October 16 and October 19, 1987.",
    source: { title: "Federal Reserve History — Stock Market Crash of 1987", url: "https://www.federalreservehistory.org/essays/stock-market-crash-of-1987", date: "1987-10-19", location: "New York Stock Exchange, USA" },
  },
  {
    registryNumber: "LR-LONGEST-PAPER-AIRPLANE-FLIGHT", slug: "longest-paper-airplane-flight", title: "Longest paper airplane flight",
    category: "Food & Culture", subcategory: "Records", direction: "MAXIMIZE",
    metricName: "Greatest distance flown by a hand-launched paper airplane", unit: "ft",
    formalStatement: "The greatest distance flown by a paper airplane launched by hand, under Guinness World Records-witnessed conditions.",
    summary: "John Collins designed a paper airplane that Joe Ayoob threw 226 ft 10 in (69.14 m) on February 26, 2012, inside McClellan Air Force Base's hangar in California — the longest flight of a hand-launched paper airplane ever certified by Guinness World Records.",
    value: "226.83",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Officially measured throw distance, witnessed and certified by a Guinness World Records adjudicator.",
    source: { title: "Guinness World Records — Farthest flight by paper aircraft", url: "https://www.guinnessworldrecords.com/world-records/farthest-flight-by-paper-aircraft", date: "2012-02-26", location: "McClellan Air Force Base, California, USA" },
  },
  {
    registryNumber: "LR-LARGEST-OMELETTE", slug: "largest-omelette-ever-made", title: "Largest omelette ever made",
    category: "Food & Culture", subcategory: "Food Records", direction: "MAXIMIZE",
    metricName: "Weight of the largest omelette ever made", unit: "kg",
    formalStatement: "The greatest weight of any single omelette made, per Guinness World Records certification.",
    summary: "A team in Portugal made a 6,466 kg (14,255 lb) omelette using 145,000 eggs on the island of Santa Maria, Azores, in August 2012 — certified by Guinness World Records as the largest omelette ever made, cooked in a specially constructed 40 m diameter pan.",
    value: "6466",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Physical weight measurement, certified by an on-site Guinness World Records adjudicator.",
    source: { title: "Guinness World Records — Largest omelette", url: "https://www.guinnessworldrecords.com/world-records/largest-omelette", date: "2012-08-11", location: "Santa Maria, Azores, Portugal" },
  },
  {
    registryNumber: "LR-MOST-EXPENSIVE-CAR-AUCTION", slug: "most-expensive-car-sold-at-auction", title: "Most expensive car ever sold at auction",
    category: "Food & Culture", subcategory: "Collectibles", direction: "MAXIMIZE",
    metricName: "Hammer-plus-fees price paid for a single car at public auction", unit: "USD",
    formalStatement: "The highest price ever paid for a single automobile sold at a public auction.",
    summary: "A 1955 Mercedes-Benz 300 SLR Uhlenhaut Coupé — one of only two ever built, previously kept in Mercedes-Benz's own museum collection — sold for €135 million (approximately $143 million) at a private RM Sotheby's sale in May 2022, the highest price ever paid for a car. Because it was a private sale rather than a fully public auction, some record-keepers list it separately from open-auction records, but it remains the highest documented sale price for any automobile.",
    value: "143000000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Sale price confirmed by RM Sotheby's, the auction house that brokered the sale, and Mercedes-Benz Group.",
    source: { title: "RM Sotheby's / Mercedes-Benz — 1955 Mercedes-Benz 300 SLR Uhlenhaut Coupé sale", url: "https://www.rmsothebys.com/", date: "2022-05-05", location: "Mercedes-Benz Museum, Stuttgart, Germany" },
  },
  {
    registryNumber: "LR-LONGEST-FINGERNAILS", slug: "longest-fingernails-ever-grown", title: "Longest fingernails ever grown",
    category: "Medicine & Physiology", subcategory: "Human Anatomy", direction: "MAXIMIZE",
    metricName: "Combined length of the longest set of fingernails ever grown on both hands", unit: "cm",
    formalStatement: "The greatest combined length of fingernails ever grown by a single person on both hands, as certified by Guinness World Records.",
    summary: "Diana Armstrong (USA) grew her fingernails for over 30 years, reaching a combined length of 1,306.58 cm (42 ft 10.4 in) across both hands before cutting them in 2021 — the longest set of fingernails ever recorded, certified by Guinness World Records.",
    value: "1306.58",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Physical measurement of each nail, summed and certified by a Guinness World Records adjudicator.",
    source: { title: "Guinness World Records — Longest fingernails ever (female)", url: "https://www.guinnessworldrecords.com/world-records/longest-fingernails-ever-female", date: "2021-02-11", location: "Sun Prairie, Wisconsin, USA" },
  },

  // --- Astronomy, continued ---
  {
    registryNumber: "LR-LONGEST-SOLAR-ECLIPSE-DURATION", slug: "longest-possible-total-solar-eclipse", title: "Longest possible total solar eclipse duration",
    category: "Astrophysics", subcategory: "Celestial Mechanics", direction: "MAXIMIZE",
    metricName: "Maximum possible duration of totality for a total solar eclipse", unit: "min",
    formalStatement: "The theoretical maximum possible duration of totality for a total solar eclipse, arising from the geometry of Earth, Moon, and Sun orbital distances.",
    summary: "The longest a total solar eclipse can theoretically last is 7 minutes 32 seconds, per NASA orbital calculations, occurring only under the rare combination of the Moon at its closest approach to Earth (perigee) and Earth at its farthest from the Sun (aphelion), with the eclipse path crossing the equator. The longest eclipse actually observed in recent centuries was 6 minutes 39 seconds, on July 22, 2009, over Asia and the Pacific.",
    value: "7.53",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Orbital mechanics calculation of Earth-Moon-Sun geometry across all possible eclipse configurations, published by NASA's eclipse research program.",
    source: { title: "NASA Eclipse Web Site — Frequently Asked Questions", url: "https://eclipse.gsfc.nasa.gov/SEhelp/SEhelp.html", date: "2008-01-01", location: "NASA Goddard Space Flight Center" },
  },
];
