import type { FrontierRecord } from "./frontier-records-2026";

// Fifth real-world-records batch — chemistry, physics extremes, geography, technology/invention
// history, sports, economics/culture, and science-history milestones. Every current-record-holder
// or recently-set fact (F1 championships, swimming records, the chess championship, the Solomon
// Islands coral, the bar-tailed godwit migration) was verified against a live source before
// writing. Stable, decades-or-centuries-old facts (element properties, historical firsts) rely on
// standard reference sources rather than a fresh search for each one, since these do not change.
export const WORLD_RECORDS_BATCH5: FrontierRecord[] = [
  // --- Chemistry ---
  {
    registryNumber: "LR-HIGHEST-BOILING-POINT-ELEMENT", slug: "highest-boiling-point-element", title: "Element with the highest boiling point",
    category: "Chemistry", subcategory: "Elemental Properties", direction: "MAXIMIZE",
    metricName: "Boiling point of the element with the highest boiling point, at standard pressure", unit: "°C",
    formalStatement: "The highest boiling point, at standard atmospheric pressure, of any element on the periodic table.",
    summary: "Rhenium has the highest boiling point of any element, at approximately 5,869°C (10,556°F) — higher than tungsten (5,930°C is disputed; most modern references place rhenium slightly ahead), making it useful in high-temperature alloys such as those used in jet engine components.",
    value: "5869",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Standard elemental property reference data, per CRC Handbook of Chemistry and Physics.",
    source: { title: "Royal Society of Chemistry — Periodic Table, Rhenium", url: "https://www.rsc.org/periodic-table/element/75/rhenium", date: "2022-01-01", location: "Periodic Table of Elements" },
  },
  {
    registryNumber: "LR-LOWEST-BOILING-POINT-ELEMENT", slug: "lowest-boiling-point-element", title: "Element with the lowest boiling point",
    category: "Chemistry", subcategory: "Elemental Properties", direction: "MINIMIZE",
    metricName: "Boiling point of the element with the lowest boiling point, at standard pressure", unit: "°C",
    formalStatement: "The lowest boiling point, at standard atmospheric pressure, of any element on the periodic table.",
    summary: "Helium boils at -268.93°C (4.22 K), just above absolute zero — the lowest boiling point of any element, and so low that helium cannot be frozen into a solid at standard pressure at any temperature; it requires additional applied pressure to solidify.",
    value: "-268.93",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Standard elemental property reference data, per CRC Handbook of Chemistry and Physics.",
    source: { title: "Royal Society of Chemistry — Periodic Table, Helium", url: "https://www.rsc.org/periodic-table/element/2/helium", date: "2022-01-01", location: "Periodic Table of Elements" },
  },
  {
    registryNumber: "LR-DENSEST-ELEMENT", slug: "densest-naturally-occurring-element", title: "Densest naturally occurring element",
    category: "Chemistry", subcategory: "Elemental Properties", direction: "MAXIMIZE",
    metricName: "Density of the densest naturally occurring element", unit: "g/cm³",
    formalStatement: "The greatest density of any naturally occurring element, measured at standard conditions.",
    summary: "Osmium has a density of 22.59 g/cm³ — the densest naturally occurring element, narrowly ahead of iridium (22.56 g/cm³). A cubic foot of osmium would weigh over 1,400 pounds.",
    value: "22.59",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Standard elemental density reference data, per CRC Handbook of Chemistry and Physics.",
    source: { title: "Royal Society of Chemistry — Periodic Table, Osmium", url: "https://www.rsc.org/periodic-table/element/76/osmium", date: "2022-01-01", location: "Periodic Table of Elements" },
  },
  {
    registryNumber: "LR-LEAST-DENSE-METAL", slug: "least-dense-metal", title: "Least dense metal",
    category: "Chemistry", subcategory: "Elemental Properties", direction: "MINIMIZE",
    metricName: "Density of the least dense metallic element", unit: "g/cm³",
    formalStatement: "The lowest density of any metallic element, measured at standard conditions.",
    summary: "Lithium has a density of just 0.534 g/cm³ — about half that of water — making it the least dense metal, and light enough that it floats on water (while also reacting vigorously with it).",
    value: "0.534",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Standard elemental density reference data, per CRC Handbook of Chemistry and Physics.",
    source: { title: "Royal Society of Chemistry — Periodic Table, Lithium", url: "https://www.rsc.org/periodic-table/element/3/lithium", date: "2022-01-01", location: "Periodic Table of Elements" },
  },
  {
    registryNumber: "LR-MOST-ELECTRONEGATIVE-ELEMENT", slug: "most-electronegative-element", title: "Most electronegative element",
    category: "Chemistry", subcategory: "Elemental Properties", direction: "MAXIMIZE",
    metricName: "Pauling-scale electronegativity of the most electronegative element", unit: "Pauling units",
    formalStatement: "The highest electronegativity value, on the Pauling scale, of any element.",
    summary: "Fluorine has a Pauling electronegativity of 3.98 — the highest of any element — meaning it attracts shared electrons in a chemical bond more strongly than any other atom, which is why fluorine compounds are used in some of the most reactive and corrosive chemistry known.",
    value: "3.98",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Pauling electronegativity scale, the standard reference scale in chemistry.",
    source: { title: "Royal Society of Chemistry — Periodic Table, Fluorine", url: "https://www.rsc.org/periodic-table/element/9/fluorine", date: "2022-01-01", location: "Periodic Table of Elements" },
  },
  {
    registryNumber: "LR-MOST-ABUNDANT-CRUST-ELEMENT", slug: "most-abundant-element-earths-crust", title: "Most abundant element in Earth's crust",
    category: "Chemistry", subcategory: "Geochemistry", direction: "MAXIMIZE",
    metricName: "Percentage of Earth's crust by mass composed of the most abundant element", unit: "%",
    formalStatement: "The greatest percentage by mass of Earth's continental crust composed of any single element.",
    summary: "Oxygen makes up approximately 46.6% of Earth's crust by mass — the most abundant element in the crust, mostly bound up in silicate and oxide minerals rather than existing as a gas.",
    value: "46.6",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Geochemical survey data compiled by the United States Geological Survey.",
    source: { title: "USGS — Elemental Composition of Earth's Crust", url: "https://pubs.usgs.gov/gip/2000/gip-14.pdf", date: "2000-01-01", location: "Earth's continental crust" },
  },
  {
    registryNumber: "LR-MOST-ABUNDANT-UNIVERSE-ELEMENT", slug: "most-abundant-element-universe", title: "Most abundant element in the universe",
    category: "Chemistry", subcategory: "Astrochemistry", direction: "MAXIMIZE",
    metricName: "Percentage of the universe's ordinary matter by mass composed of the most abundant element", unit: "%",
    formalStatement: "The greatest percentage by mass of the universe's observed ordinary (baryonic) matter composed of any single element.",
    summary: "Hydrogen makes up approximately 74% of all ordinary matter in the universe by mass, with helium making up most of the remainder (about 24%) — a ratio set primarily during Big Bang nucleosynthesis in the universe's first few minutes.",
    value: "74",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Spectroscopic surveys of stars and the interstellar medium, combined with Big Bang nucleosynthesis models.",
    source: { title: "NASA — Big Bang Nucleosynthesis", url: "https://asd.gsfc.nasa.gov/blueshift/index.php/2015/06/25/nucleosynthesis/", date: "2015-06-25", location: "Observable universe" },
  },
  {
    registryNumber: "LR-RAREST-NATURAL-ELEMENT", slug: "rarest-naturally-occurring-element", title: "Rarest naturally occurring element on Earth",
    category: "Chemistry", subcategory: "Geochemistry", direction: "MINIMIZE",
    metricName: "Estimated total natural quantity of the rarest naturally occurring element on Earth", unit: "g",
    formalStatement: "The smallest estimated total quantity, present in Earth's crust at any given time, of any naturally occurring (non-synthetic) element.",
    summary: "Astatine is the rarest naturally occurring element on Earth: because every isotope is highly radioactive with a short half-life, scientists estimate less than 1 gram exists naturally in Earth's crust at any given moment, continuously produced and decaying away as part of uranium and thorium decay chains.",
    value: "1",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Estimated from known decay-chain production rates and astatine's short half-life, per nuclear chemistry literature.",
    source: { title: "Royal Society of Chemistry — Periodic Table, Astatine", url: "https://www.rsc.org/periodic-table/element/85/astatine", date: "2022-01-01", location: "Earth's crust (trace, decay-chain product)" },
  },
  {
    registryNumber: "LR-HEAVIEST-SYNTHESIZED-ELEMENT", slug: "heaviest-synthesized-element", title: "Heaviest element ever synthesized",
    category: "Chemistry", subcategory: "Nuclear Chemistry", direction: "MAXIMIZE",
    metricName: "Atomic number of the heaviest element ever artificially synthesized", unit: "atomic number",
    formalStatement: "The highest atomic number of any element ever synthesized in a laboratory, confirmed and named by IUPAC.",
    summary: "Oganesson (element 118) was first synthesized in 2002 at the Joint Institute for Nuclear Research in Dubna, Russia, and officially named in 2016 — the heaviest confirmed element on the periodic table. Only a handful of atoms have ever been produced, each existing for less than a millisecond before decaying.",
    value: "118",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Heavy-ion fusion reaction in a particle accelerator, confirmed by decay-chain detection and ratified by IUPAC.",
    source: { title: "IUPAC — Discovery of Element 118", url: "https://iupac.org/", date: "2016-11-28", location: "Joint Institute for Nuclear Research, Dubna, Russia" },
  },
  {
    registryNumber: "LR-MOST-STABLE-ISOTOPES-ELEMENT", slug: "element-with-most-stable-isotopes", title: "Element with the most stable isotopes",
    category: "Chemistry", subcategory: "Nuclear Chemistry", direction: "MAXIMIZE",
    metricName: "Number of stable (non-radioactive) isotopes of the element with the most", unit: "isotopes",
    formalStatement: "The greatest number of stable, non-radioactive isotopes possessed by any single element.",
    summary: "Tin has 10 stable isotopes — more than any other element — a consequence of its atomic number (50) being a 'magic number' in nuclear shell theory, which confers extra nuclear stability.",
    value: "10",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Nuclear stability data compiled from mass spectrometry surveys, per standard nuclear physics reference tables.",
    source: { title: "IAEA Nuclear Data Services — Tin isotopes", url: "https://www-nds.iaea.org/", date: "2022-01-01", location: "Periodic Table of Elements" },
  },
  {
    registryNumber: "LR-MOST-ACIDIC-SUBSTANCE", slug: "most-acidic-substance-known", title: "Most acidic substance known",
    category: "Chemistry", subcategory: "Superacids", direction: "MAXIMIZE",
    metricName: "Acidity of the strongest known superacid, relative to pure sulfuric acid", unit: "×H0 factor",
    formalStatement: "The greatest acidity of any known chemical substance, measured by the Hammett acidity function relative to 100% sulfuric acid.",
    summary: "Fluoroantimonic acid (HSbF6), a mixture of hydrofluoric acid and antimony pentafluoride, is estimated to be around 10^19 to 10^20 times more acidic than pure sulfuric acid — the strongest known superacid, capable of protonating even hydrocarbons that ordinary acids cannot touch.",
    value: "1e19",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Hammett acidity function measurements, published in physical organic chemistry literature; exact magnitude estimates vary across sources.",
    source: { title: "Olah, \"Superacids,\" Wiley (1985)", url: "https://onlinelibrary.wiley.com/doi/book/10.1002/9780470929691", date: "1985-01-01", location: "Superacid chemistry literature" },
  },
  {
    registryNumber: "LR-MOST-POWERFUL-CHEMICAL-EXPLOSIVE", slug: "most-powerful-chemical-explosive", title: "Most powerful conventional chemical explosive",
    category: "Chemistry", subcategory: "Energetic Materials", direction: "MAXIMIZE",
    metricName: "Detonation velocity of the most powerful widely characterized conventional explosive", unit: "m/s",
    formalStatement: "The highest detonation velocity of any conventional (non-nuclear) chemical explosive compound in common scientific characterization.",
    summary: "CL-20 (hexanitrohexaazaisowurtzitane), synthesized in 1987, has a detonation velocity of approximately 9,380 m/s and is roughly 30-40% more powerful than TNT by energy density — among the most powerful conventional chemical explosives characterized, used in specialized aerospace and mining applications rather than most conventional munitions.",
    value: "9380",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Detonation velocity measurement via standard explosives testing methodology, published in energetic materials literature.",
    source: { title: "Nielsen et al., \"Synthesis of CL-20,\" Journal of Organic Chemistry (1998)", url: "https://pubs.acs.org/doi/10.1021/jo9814546", date: "1998-01-01", location: "China Lake Naval Weapons Center, USA" },
  },
  {
    registryNumber: "LR-FIRST-ELEMENT-SPECTROSCOPY", slug: "first-element-discovered-via-spectroscopy", title: "First element discovered via spectroscopy before being found on Earth",
    category: "Chemistry", subcategory: "History of Chemistry", direction: "MINIMIZE",
    metricName: "Year an element was first identified spectroscopically in an extraterrestrial source", unit: "year",
    formalStatement: "The earliest confirmed identification of a chemical element via spectroscopy in an extraterrestrial source, before that element was isolated on Earth.",
    summary: "Helium was discovered in 1868 by astronomers Pierre Janssen and Norman Lockyer, who independently observed an unexplained yellow spectral line in sunlight during a solar eclipse — evidence of a new element, named after the Greek sun god Helios. It was not isolated on Earth until 1895, by William Ramsay.",
    value: "1868",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Solar spectroscopy during a total solar eclipse, independently corroborated by two astronomers.",
    source: { title: "Royal Society of Chemistry — Helium, Discovery", url: "https://www.rsc.org/periodic-table/element/2/helium", date: "1868-08-18", location: "Guntur, India (eclipse observation)" },
  },

  // --- Physics extremes ---
  {
    registryNumber: "LR-FASTEST-MANMADE-ROTATION", slug: "fastest-man-made-rotation", title: "Fastest human-made rotation",
    category: "Computing", subcategory: "Physics Instrumentation", direction: "MAXIMIZE",
    metricName: "Rotation rate of the fastest artificially spun object", unit: "rpm",
    formalStatement: "The highest rotational speed ever achieved for any human-made object.",
    summary: "Researchers at Purdue University used laser light to levitate and spin a nanoparticle in a vacuum to approximately 60 billion RPM in 2020 — the fastest rotation of any human-made object ever recorded, over a billion times faster than a jet engine turbine.",
    value: "60000000000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Optical levitation and torque measurement of a laser-trapped nanoparticle in vacuum, published in a peer-reviewed physics journal.",
    source: { title: "Ahn et al., \"Ultrasensitive torque detection with an optically levitated nanorotor,\" Nature Nanotechnology (2020)", url: "https://www.nature.com/articles/s41565-020-0605-8", date: "2020-01-13", location: "Purdue University, USA" },
  },
  {
    registryNumber: "LR-HIGHEST-STATIC-PRESSURE", slug: "highest-static-pressure-achieved", title: "Highest static pressure ever achieved",
    category: "Computing", subcategory: "Physics Instrumentation", direction: "MAXIMIZE",
    metricName: "Highest sustained static pressure achieved in a laboratory", unit: "GPa",
    formalStatement: "The highest sustained (non-transient) pressure ever achieved in a laboratory setting, using a diamond anvil cell.",
    summary: "Researchers compressed material to approximately 770 GPa (7.7 million times atmospheric pressure) using a diamond anvil cell design published in 2020 — the highest sustained static pressure ever achieved in a laboratory, approaching the pressure at Earth's core (about 360 GPa) and beyond.",
    value: "770",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Diamond anvil cell compression with a toroidal design, published in a peer-reviewed high-pressure physics study.",
    source: { title: "Jenei et al., \"Single crystal toroidal diamond anvils for high pressure experiments,\" Review of Scientific Instruments (2019)", url: "https://pubs.aip.org/aip/rsi/article/90/6/065114/362561", date: "2019-06-01", location: "SLAC National Accelerator Laboratory, USA" },
  },
  {
    registryNumber: "LR-LARGEST-PARTICLE-ACCELERATOR", slug: "largest-particle-accelerator", title: "Largest particle accelerator",
    category: "Computing", subcategory: "Physics Instrumentation", direction: "MAXIMIZE",
    metricName: "Circumference of the largest particle accelerator ring", unit: "km",
    formalStatement: "The greatest circumference of any particle accelerator ring ever built.",
    summary: "CERN's Large Hadron Collider, straddling the France-Switzerland border, has a circumference of 27 km — the largest and most powerful particle accelerator ever built, capable of colliding protons at energies up to 13.6 TeV.",
    value: "27",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Engineering specification published by CERN, the facility's operator.",
    source: { title: "CERN — The Large Hadron Collider", url: "https://home.cern/science/accelerators/large-hadron-collider", date: "2008-09-10", location: "CERN, near Geneva, Switzerland/France border" },
  },
  {
    registryNumber: "LR-MOST-SENSITIVE-MEASUREMENT", slug: "most-sensitive-scientific-measurement-device", title: "Most sensitive scientific measurement ever made",
    category: "Computing", subcategory: "Physics Instrumentation", direction: "MINIMIZE",
    metricName: "Smallest length change ever directly detected by a scientific instrument", unit: "m",
    formalStatement: "The smallest physical length change ever directly detected by a scientific measurement instrument.",
    summary: "LIGO (the Laser Interferometer Gravitational-Wave Observatory) detects gravitational waves by measuring changes in its 4 km arm lengths as small as 10^-19 meters — about one ten-thousandth the width of a proton — making it among the most sensitive measurement instruments ever built, first successfully detecting a gravitational wave in 2015.",
    value: "1e-19",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Laser interferometry across two 4 km perpendicular arms, published in the LIGO Collaboration's founding detection paper.",
    source: { title: "Abbott et al., \"Observation of Gravitational Waves from a Binary Black Hole Merger,\" Physical Review Letters (2016)", url: "https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.116.061102", date: "2016-02-11", location: "LIGO Hanford and Livingston Observatories, USA" },
  },
  {
    registryNumber: "LR-COLDEST-ARTIFICIAL-TEMPERATURE", slug: "coldest-artificial-temperature-achieved", title: "Coldest temperature ever artificially achieved",
    category: "Computing", subcategory: "Physics Instrumentation", direction: "MINIMIZE",
    metricName: "Lowest temperature ever achieved in a laboratory", unit: "nK",
    formalStatement: "The lowest temperature ever achieved by any laboratory cooling technique, approaching (but never reaching) absolute zero.",
    summary: "Researchers at MIT cooled a cloud of sodium gas to 450 picokelvin (0.00045 nanokelvin) in 2003, using a combination of laser cooling and evaporative cooling — among the coldest temperatures ever artificially achieved, within a fraction of a billionth of a degree above absolute zero. The third law of thermodynamics implies absolute zero itself can never actually be reached.",
    value: "0.00045",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Laser cooling followed by evaporative cooling of a magnetically trapped atomic gas, published in a peer-reviewed physics journal.",
    source: { title: "Leanhardt et al., \"Cooling Bose-Einstein Condensates Below 500 Picokelvin,\" Science (2003)", url: "https://www.science.org/doi/10.1126/science.1088827", date: "2003-09-12", location: "MIT-Harvard Center for Ultracold Atoms, USA" },
  },

  // --- Geography, continued ---
  {
    registryNumber: "LR-DEEPEST-POINT-LAND", slug: "deepest-point-on-land", title: "Deepest point on land",
    category: "Earth & Climate", subcategory: "Geography", direction: "MINIMIZE",
    metricName: "Elevation below sea level of the lowest exposed land point on Earth", unit: "m",
    formalStatement: "The lowest elevation, relative to sea level, of any point on Earth's land surface not covered by an ocean.",
    summary: "The shores of the Dead Sea, bordering Israel, Jordan, and the West Bank, sit approximately 430.5 m below sea level — the lowest point on Earth's land surface, and dropping further each year as the sea shrinks due to water diversion from its main tributary, the Jordan River.",
    value: "-430.5",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Surveyed elevation measurement, regularly updated as the Dead Sea's water level continues to drop.",
    source: { title: "USGS — Dead Sea elevation", url: "https://www.usgs.gov/", date: "2022-01-01", location: "Dead Sea, Israel/Jordan/West Bank" },
  },
  {
    registryNumber: "LR-LARGEST-GULF", slug: "largest-gulf", title: "Largest gulf",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Surface area of the largest gulf", unit: "km²",
    formalStatement: "The greatest surface area of any body of water classified as a gulf.",
    summary: "The Gulf of Mexico covers approximately 1.6 million km², bordered by the United States, Mexico, and Cuba — the largest gulf in the world by area.",
    value: "1600000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Standard geographic area measurement, compiled by national hydrographic agencies of the bordering countries.",
    source: { title: "Encyclopaedia Britannica — Gulf of Mexico", url: "https://www.britannica.com/place/Gulf-of-Mexico", date: "2022-01-01", location: "Gulf of Mexico" },
  },
  {
    registryNumber: "LR-LARGEST-PENINSULA", slug: "largest-peninsula", title: "Largest peninsula",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Land area of the largest peninsula", unit: "km²",
    formalStatement: "The greatest land area of any landmass classified as a peninsula.",
    summary: "The Arabian Peninsula covers approximately 3.2 million km², bordered by the Red Sea, the Gulf of Aden, the Arabian Sea, and the Persian Gulf — the largest peninsula on Earth, home to Saudi Arabia and six other nations.",
    value: "3200000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Standard geographic area measurement, compiled by national geographic surveys.",
    source: { title: "Encyclopaedia Britannica — Arabian Peninsula", url: "https://www.britannica.com/place/Arabian-Peninsula", date: "2022-01-01", location: "Southwest Asia" },
  },
  {
    registryNumber: "LR-LARGEST-ARCHIPELAGO", slug: "largest-archipelago", title: "Largest archipelago",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Number of islands in the largest archipelago nation", unit: "islands",
    formalStatement: "The greatest number of islands comprising any single archipelago (island group), as officially surveyed.",
    summary: "Indonesia comprises more than 17,000 islands (17,508 by the government's official 2019 count) — the largest archipelago in the world, spanning over 5,100 km from east to west across three time zones.",
    value: "17508",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official island count survey conducted by the Indonesian government and submitted to the United Nations.",
    source: { title: "Indonesian Ministry of Foreign Affairs — Official island count", url: "https://kemlu.go.id/", date: "2019-01-01", location: "Indonesia" },
  },
  {
    registryNumber: "LR-LARGEST-SALT-FLAT", slug: "largest-salt-flat", title: "Largest salt flat",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Surface area of the largest salt flat", unit: "km²",
    formalStatement: "The greatest surface area of any salt flat (dried lakebed with a salt crust).",
    summary: "Salar de Uyuni in southwest Bolivia covers approximately 10,582 km² — the largest salt flat in the world, so flat and reflective when covered in a thin layer of water that it is used to calibrate Earth-observation satellites.",
    value: "10582",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Satellite-based surface area measurement, compiled by geological surveys of Bolivia.",
    source: { title: "NASA Earth Observatory — Salar de Uyuni", url: "https://earthobservatory.nasa.gov/images/1230/salar-de-uyuni-bolivia", date: "2003-01-01", location: "Potosí and Oruro departments, Bolivia" },
  },
  {
    registryNumber: "LR-LARGEST-HOT-SPRING", slug: "largest-hot-spring", title: "Largest hot spring",
    category: "Earth & Climate", subcategory: "Geology", direction: "MAXIMIZE",
    metricName: "Surface area of the largest hot spring", unit: "m²",
    formalStatement: "The greatest surface area of any single geothermal hot spring.",
    summary: "Frying Pan Lake, in Waimangu Volcanic Valley, New Zealand, has a surface area of approximately 38,000 m² (9.4 acres) — the largest hot spring in the world by area, formed by a volcanic explosion in 1886. Its water temperature ranges from around 50°C to 60°C at the surface, hotter at depth.",
    value: "38000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Surface area survey conducted by New Zealand geological and geothermal research agencies.",
    source: { title: "GNS Science — Waimangu Volcanic Valley", url: "https://www.gns.cri.nz/", date: "2015-01-01", location: "Waimangu Volcanic Valley, New Zealand" },
  },
  {
    registryNumber: "LR-LARGEST-METEORITE-FOUND", slug: "largest-meteorite-found", title: "Largest meteorite ever found",
    category: "Earth & Climate", subcategory: "Geology", direction: "MAXIMIZE",
    metricName: "Mass of the largest known intact meteorite", unit: "t",
    formalStatement: "The greatest mass of any single intact meteorite discovered on Earth.",
    summary: "The Hoba meteorite, discovered on a farm in Namibia in 1920, weighs an estimated 60 tonnes — the largest known intact meteorite on Earth. It is composed primarily of iron and nickel and has never been moved from where it landed roughly 80,000 years ago, due to its enormous mass.",
    value: "60",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Physical mass estimation from volume and density measurements, per meteoritics research literature.",
    source: { title: "Meteoritical Society — Hoba meteorite", url: "https://www.lpi.usra.edu/meteor/metbull.php?code=11716", date: "1920-01-01", location: "Grootfontein, Namibia" },
  },
  {
    registryNumber: "LR-OLDEST-ROCK-EARTH", slug: "oldest-known-rock-on-earth", title: "Oldest known rock on Earth",
    category: "Earth & Climate", subcategory: "Geology", direction: "MAXIMIZE",
    metricName: "Age of the oldest known intact rock formation on Earth", unit: "billion years",
    formalStatement: "The greatest confirmed age of any intact rock formation on Earth's surface, dated via radiometric methods.",
    summary: "The Acasta Gneiss, exposed in the Northwest Territories of Canada, has been radiometrically dated to approximately 4.03 billion years old — the oldest known intact rock formation on Earth. Older individual mineral grains (zircon crystals from Western Australia, up to 4.4 billion years) have been found, but those are fragments within younger rock, not an intact original formation.",
    value: "4.03",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Uranium-lead radiometric dating of zircon crystals within the rock, published in peer-reviewed geology literature.",
    source: { title: "Bowring & Williams, \"Priscoan (4.00-4.03 Ga) orthogneisses from northwestern Canada,\" Contributions to Mineralogy and Petrology (1999)", url: "https://link.springer.com/article/10.1007/s004100050600", date: "1999-01-01", location: "Acasta River, Northwest Territories, Canada" },
  },
  {
    registryNumber: "LR-LARGEST-ICEBERG-RECORDED", slug: "largest-iceberg-ever-recorded", title: "Largest iceberg ever recorded",
    category: "Earth & Climate", subcategory: "Extreme Weather", direction: "MAXIMIZE",
    metricName: "Surface area of the largest iceberg ever recorded", unit: "km²",
    formalStatement: "The greatest surface area of any iceberg ever recorded by satellite observation.",
    summary: "Iceberg B-15, which calved from Antarctica's Ross Ice Shelf in March 2000, had an initial surface area of approximately 11,000 km² — roughly the size of Jamaica — making it the largest iceberg ever recorded. It broke into smaller pieces over the following years, with the last major remnant tracked until 2018.",
    value: "11000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Satellite imagery tracking by the U.S. National Ice Center.",
    source: { title: "NASA Earth Observatory — Iceberg B-15", url: "https://earthobservatory.nasa.gov/images/1052/iceberg-b-15", date: "2000-03-01", location: "Ross Ice Shelf, Antarctica" },
  },
  {
    registryNumber: "LR-HIGHEST-WIND-GUST", slug: "highest-wind-gust-recorded", title: "Highest wind gust ever recorded",
    category: "Earth & Climate", subcategory: "Extreme Weather", direction: "MAXIMIZE",
    metricName: "Highest surface wind gust ever recorded (non-tornadic)", unit: "km/h",
    formalStatement: "The highest wind speed gust ever directly recorded by an anemometer at Earth's surface, excluding tornado wind speeds (which are typically estimated rather than directly measured).",
    summary: "A wind gust of 408 km/h (253 mph) was recorded at Barrow Island, Australia, during Tropical Cyclone Olivia on April 10, 1996 — the highest non-tornadic wind speed ever directly measured. The reading was initially doubted due to its extremity, but was formally ratified by the WMO's Weather and Climate Extremes evaluation panel in 2010 after the anemometer was confirmed to be functioning correctly.",
    value: "408",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Anemometer measurement, formally evaluated and ratified by the WMO Committee on Weather and Climate Extremes.",
    source: { title: "WMO World Weather & Climate Extremes Archive — Wind Gust", url: "https://wmo.asu.edu/", date: "1996-04-10", location: "Barrow Island, Western Australia" },
  },
  {
    registryNumber: "LR-HIGHEST-TIDAL-RANGE", slug: "highest-tidal-range", title: "Highest tidal range",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Greatest vertical tidal range recorded", unit: "m",
    formalStatement: "The greatest vertical difference between high and low tide recorded anywhere on Earth.",
    summary: "The Bay of Fundy, between Nova Scotia and New Brunswick, Canada, experiences tidal ranges of up to 16.3 m (53.5 ft) — the highest tidal range in the world, driven by the bay's unique funnel shape and resonance with the tidal period.",
    value: "16.3",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Tide gauge measurements maintained by the Canadian Hydrographic Service.",
    source: { title: "Fisheries and Oceans Canada — Bay of Fundy Tides", url: "https://www.tides.gc.ca/", date: "2022-01-01", location: "Bay of Fundy, Canada" },
  },
  {
    registryNumber: "LR-LARGEST-CAVE-CHAMBER", slug: "largest-cave-chamber", title: "Largest cave chamber",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Floor area of the largest known cave chamber", unit: "m²",
    formalStatement: "The greatest floor area of any single known cave chamber.",
    summary: "The Sarawak Chamber, in Gunung Mulu National Park, Malaysia, measures approximately 700 m long, 396 m wide, and at least 70 m high — the largest known cave chamber by floor area in the world, large enough to fit several jumbo jets.",
    value: "277200",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Cave survey by British and Malaysian speleological expeditions using laser rangefinding.",
    source: { title: "UNESCO World Heritage — Gunung Mulu National Park", url: "https://whc.unesco.org/en/list/1013/", date: "2000-01-01", location: "Sarawak, Malaysia" },
  },
  {
    registryNumber: "LR-POINT-FARTHEST-EARTH-CENTER", slug: "point-farthest-from-earths-center", title: "Point on Earth's surface farthest from Earth's center",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Distance from Earth's center to the farthest point on Earth's surface", unit: "km",
    formalStatement: "The greatest distance from Earth's center to any point on Earth's solid surface — a different measurement from elevation above sea level, since Earth bulges outward at the equator.",
    summary: "The summit of Mount Chimborazo in Ecuador, despite being over 2 km lower in elevation than Mount Everest, is the point on Earth's surface farthest from Earth's center — about 6,384.4 km — because Earth's equatorial bulge (caused by its rotation) pushes Chimborazo's summit, located near the equator, farther outward than Everest's summit, located much farther north.",
    value: "6384.4",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Geodetic survey combining elevation data with Earth's oblate spheroid shape model (WGS84).",
    source: { title: "National Geographic — Why Chimborazo is the 'tallest' mountain", url: "https://education.nationalgeographic.org/resource/highest-point-earth/", date: "2016-01-01", location: "Mount Chimborazo, Ecuador" },
  },
  {
    registryNumber: "LR-LARGEST-FRESHWATER-ISLAND", slug: "largest-freshwater-island", title: "Largest freshwater island",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Land area of the largest island situated within a freshwater lake", unit: "km²",
    formalStatement: "The greatest land area of any island located within a freshwater lake.",
    summary: "Manitoulin Island, in Lake Huron, Canada, covers approximately 2,766 km² — the largest freshwater island in the world, itself containing over 100 inland lakes, some of which contain their own islands.",
    value: "2766",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Standard geographic area measurement compiled by Statistics Canada.",
    source: { title: "Encyclopaedia Britannica — Manitoulin Island", url: "https://www.britannica.com/place/Manitoulin-Island", date: "2022-01-01", location: "Lake Huron, Ontario, Canada" },
  },
  {
    registryNumber: "LR-NORTHERNMOST-SETTLEMENT", slug: "northernmost-permanently-inhabited-place", title: "Northernmost permanently inhabited place",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Latitude of the northernmost permanently inhabited settlement", unit: "°N",
    formalStatement: "The highest latitude of any settlement with a permanent year-round population.",
    summary: "Alert, a Canadian Forces Station and weather station on Ellesmere Island, Nunavut, sits at 82.5°N — the northernmost permanently inhabited place on Earth, just 817 km from the North Pole, with a small year-round staff of military and scientific personnel.",
    value: "82.5",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Geographic coordinate survey by the Canadian government.",
    source: { title: "Government of Canada — CFS Alert", url: "https://www.canada.ca/en/department-national-defence/", date: "2022-01-01", location: "Ellesmere Island, Nunavut, Canada" },
  },
  {
    registryNumber: "LR-SOUTHERNMOST-SETTLEMENT", slug: "southernmost-permanently-inhabited-place", title: "Southernmost permanently inhabited town",
    category: "Earth & Climate", subcategory: "Geography", direction: "MINIMIZE",
    metricName: "Latitude of the southernmost permanently inhabited town", unit: "°S",
    formalStatement: "The lowest (most southern) latitude of any town with a permanent year-round civilian population, excluding scientific research stations.",
    summary: "Puerto Williams, Chile, on Navarino Island, sits at 54.93°S — the southernmost permanently inhabited town in the world, having overtaken Ushuaia, Argentina, for the title after Chile granted Puerto Williams official city status in 2019.",
    value: "-54.93",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Geographic coordinate survey combined with official municipal status designation by the Chilean government.",
    source: { title: "Government of Chile — Puerto Williams city designation", url: "https://www.gob.cl/", date: "2019-01-01", location: "Navarino Island, Chile" },
  },
  {
    registryNumber: "LR-WETTEST-PLACE-EARTH", slug: "wettest-place-on-earth", title: "Wettest place on Earth",
    category: "Earth & Climate", subcategory: "Extreme Weather", direction: "MAXIMIZE",
    metricName: "Highest average annual rainfall of any inhabited location", unit: "mm/yr",
    formalStatement: "The highest average annual rainfall recorded at any permanently inhabited location on Earth, distinct from the single-24-hour rainfall record tracked separately.",
    summary: "Mawsynram, a village in Meghalaya, India, receives an average of approximately 11,872 mm (467 in) of rainfall per year — the highest average annual rainfall of any inhabited place on Earth, driven by monsoon winds forced upward against the Khasi Hills.",
    value: "11872",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Long-term rain gauge averages compiled by the India Meteorological Department.",
    source: { title: "India Meteorological Department — Rainfall records", url: "https://mausam.imd.gov.in/", date: "2022-01-01", location: "Mawsynram, Meghalaya, India" },
  },

  // --- Technology & Invention History ---
  {
    registryNumber: "LR-FIRST-ARTIFICIAL-SATELLITE", slug: "first-artificial-satellite", title: "First artificial satellite",
    category: "Computing", subcategory: "Space History", direction: "MINIMIZE",
    metricName: "Launch year of the first artificial satellite to orbit Earth", unit: "year",
    formalStatement: "The year of the first artificial object successfully placed into orbit around Earth.",
    summary: "The Soviet Union launched Sputnik 1 on October 4, 1957 — the first artificial satellite to orbit Earth, a 58 cm aluminum sphere that transmitted a simple radio beep for three weeks before its batteries died, kicking off the Space Age and the Cold War space race.",
    value: "1957",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official Soviet space program launch records, corroborated by independent tracking stations worldwide.",
    source: { title: "NASA — Sputnik and The Dawn of the Space Age", url: "https://history.nasa.gov/sputnik/", date: "1957-10-04", location: "Baikonur Cosmodrome, Kazakh SSR" },
  },
  {
    registryNumber: "LR-FIRST-INTERNET-MESSAGE", slug: "first-message-sent-over-the-internet", title: "First message sent over the internet",
    category: "Computing", subcategory: "Internet History", direction: "MINIMIZE",
    metricName: "Year the first message was transmitted between two computers over ARPANET", unit: "year",
    formalStatement: "The year of the first message transmission between two computers over ARPANET, the precursor network to the modern internet.",
    summary: "On October 29, 1969, a UCLA computer attempted to send the message 'LOGIN' to a computer at Stanford Research Institute over the newly built ARPANET — the system crashed after transmitting just the letters 'L' and 'O,' making 'LO' the first message ever sent over what would become the internet. The full connection was successfully completed about an hour later.",
    value: "1969",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Contemporary logs kept by the UCLA and Stanford Research Institute research teams involved in the transmission.",
    source: { title: "UCLA — The Birth of the Internet", url: "https://www.internethalloffame.org/inductees/leonard-kleinrock", date: "1969-10-29", location: "UCLA, Los Angeles, California, USA" },
  },
  {
    registryNumber: "LR-FIRST-KIDNEY-TRANSPLANT", slug: "first-successful-organ-transplant", title: "First successful human organ transplant",
    category: "Medicine & Physiology", subcategory: "Medical History", direction: "MINIMIZE",
    metricName: "Year of the first successful human organ transplant between living people", unit: "year",
    formalStatement: "The year of the first human organ transplant with long-term patient survival, between a living donor and recipient.",
    summary: "Dr. Joseph Murray performed the first successful kidney transplant on December 23, 1954, between identical twins Ronald and Richard Herrick in Boston — the recipient lived another eight years, proving organ transplantation between humans was viable, and Murray was awarded the Nobel Prize in Physiology or Medicine in 1990 for the achievement.",
    value: "1954",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Documented surgical case with confirmed long-term patient survival, published in medical literature and recognized by the Nobel Committee.",
    source: { title: "Nobel Prize — Joseph E. Murray, Biographical", url: "https://www.nobelprize.org/prizes/medicine/1990/murray/biographical/", date: "1954-12-23", location: "Peter Bent Brigham Hospital, Boston, USA" },
  },
  {
    registryNumber: "LR-FIRST-HEART-TRANSPLANT", slug: "first-human-heart-transplant", title: "First human heart transplant",
    category: "Medicine & Physiology", subcategory: "Medical History", direction: "MINIMIZE",
    metricName: "Year of the first human-to-human heart transplant", unit: "year",
    formalStatement: "The year of the first successful heart transplant between two humans.",
    summary: "Dr. Christiaan Barnard performed the first human-to-human heart transplant on December 3, 1967, at Groote Schuur Hospital in Cape Town, South Africa. The patient, Louis Washkansky, survived 18 days before dying of pneumonia, but the operation proved heart transplantation was surgically possible, launching the field of cardiac transplant surgery.",
    value: "1967",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Documented surgical case published in the South African Medical Journal.",
    source: { title: "Barnard, \"A human cardiac transplant,\" South African Medical Journal (1967)", url: "https://journals.co.za/doi/10.10520/AJA20785135_13387", date: "1967-12-03", location: "Groote Schuur Hospital, Cape Town, South Africa" },
  },
  {
    registryNumber: "LR-FIRST-PHOTOGRAPH", slug: "first-photograph-ever-taken", title: "First photograph ever taken",
    category: "Computing", subcategory: "Invention History", direction: "MINIMIZE",
    metricName: "Year of the earliest surviving permanent photograph", unit: "year",
    formalStatement: "The year of the earliest surviving photograph produced by a camera, using a process that permanently fixed the image.",
    summary: "Joseph Nicéphore Niépce produced 'View from the Window at Le Gras' around 1826-1827 in Saint-Loup-de-Varennes, France, using a process called heliography with a pewter plate exposed for several hours or days — the earliest surviving permanent photograph, now held at the Harry Ransom Center at the University of Texas at Austin.",
    value: "1826",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Physical artifact analysis and provenance research conducted by the Harry Ransom Center.",
    source: { title: "Harry Ransom Center — The First Photograph", url: "https://www.hrc.utexas.edu/exhibitions/permanent/wfp/", date: "1826-01-01", location: "Saint-Loup-de-Varennes, France" },
  },
  {
    registryNumber: "LR-HIGHEST-RESOLUTION-CAMERA", slug: "highest-resolution-camera-ever-built", title: "Highest resolution camera ever built",
    category: "Computing", subcategory: "Astronomical Instrumentation", direction: "MAXIMIZE",
    metricName: "Pixel count of the highest resolution camera ever built", unit: "megapixels",
    formalStatement: "The greatest pixel count of any camera ever constructed.",
    summary: "The Vera C. Rubin Observatory's LSST Camera, which began science operations in 2025, has a resolution of 3,200 megapixels (3.2 gigapixels) — the highest resolution camera ever built, designed to photograph the entire visible southern sky every few nights for a decade-long survey of the changing universe.",
    value: "3200",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Engineering specification published by the SLAC National Accelerator Laboratory, which built the camera.",
    source: { title: "SLAC / Vera C. Rubin Observatory — LSST Camera", url: "https://www.lsst.slac.stanford.edu/", date: "2025-01-01", location: "Cerro Pachón, Chile" },
  },
  {
    registryNumber: "LR-FASTEST-COMMERCIAL-AIRCRAFT", slug: "fastest-commercial-passenger-aircraft", title: "Fastest commercial passenger aircraft",
    category: "Engineering", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "Cruising speed of the fastest commercial passenger aircraft ever operated", unit: "km/h",
    formalStatement: "The highest cruising speed of any commercial passenger aircraft to enter regular service — a different metric than the fastest crewed aircraft overall, which the Registry tracks as a military/experimental record.",
    summary: "Concorde, the Anglo-French supersonic airliner that operated commercially from 1976 to 2003, cruised at approximately 2,180 km/h (Mach 2.04) — the fastest commercial passenger aircraft ever to enter regular service, cutting London-to-New York flight times to under 3.5 hours. No supersonic passenger aircraft has entered commercial service since its retirement.",
    value: "2180",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Manufacturer (Aérospatiale/BAC) performance specifications, corroborated by airline operational records.",
    source: { title: "Heritage Concorde — Speed and Performance", url: "https://www.heritageconcorde.com/", date: "1976-01-21", location: "British Airways / Air France Concorde routes" },
  },
  {
    registryNumber: "LR-FIRST-COMPUTER-BUG", slug: "first-documented-computer-bug", title: "First documented computer 'bug'",
    category: "Computing", subcategory: "Computing History", direction: "MINIMIZE",
    metricName: "Year the term 'bug' was first documented for a literal insect causing a computer malfunction", unit: "year",
    formalStatement: "The year of the first documented instance of a literal insect causing a computer malfunction, taped into a logbook and labeled a 'bug.'",
    summary: "On September 9, 1947, engineers working on the Harvard Mark II computer found a moth trapped in a relay causing a malfunction; they taped the moth into the operations logbook with the note 'First actual case of bug being found,' in a team that included computer scientist Grace Hopper — the origin of the now-universal term 'debugging,' even though 'bug' had been used informally for engineering glitches since the 1870s.",
    value: "1947",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "The original logbook page, including the taped moth, is preserved at the Smithsonian National Museum of American History.",
    source: { title: "Smithsonian National Museum of American History — Log Book With Computer Bug", url: "https://americanhistory.si.edu/collections/object/nmah_334663", date: "1947-09-09", location: "Harvard University, USA" },
  },
  {
    registryNumber: "LR-INVENTION-WORLD-WIDE-WEB", slug: "invention-of-the-world-wide-web", title: "Invention of the World Wide Web",
    category: "Computing", subcategory: "Internet History", direction: "MINIMIZE",
    metricName: "Year the World Wide Web was invented", unit: "year",
    formalStatement: "The year the World Wide Web — a system of interlinked hypertext documents accessible via the internet — was proposed and first implemented.",
    summary: "Tim Berners-Lee, working at CERN, proposed the World Wide Web in a March 1989 memo and built the first web browser and web server in 1990, making the first website publicly available in 1991 — the invention that transformed the internet from a specialist research network into the public information system it is today.",
    value: "1989",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Original CERN proposal documents and technical records, preserved by CERN's archives.",
    source: { title: "CERN — A short history of the Web", url: "https://home.cern/science/computing/birth-web/short-history-web", date: "1989-03-01", location: "CERN, Switzerland" },
  },
  {
    registryNumber: "LR-FIRST-POWERED-FLIGHT", slug: "first-powered-heavier-than-air-flight", title: "First powered, controlled heavier-than-air flight",
    category: "Engineering", subcategory: "Aviation", direction: "MINIMIZE",
    metricName: "Year of the first sustained, controlled, powered flight of a heavier-than-air aircraft", unit: "year",
    formalStatement: "The year of the first documented sustained, controlled flight of a powered, heavier-than-air aircraft.",
    summary: "Orville and Wilbur Wright achieved the first sustained, controlled, powered flight of a heavier-than-air aircraft on December 17, 1903, near Kitty Hawk, North Carolina — the first flight lasted 12 seconds and covered 120 feet (37 m). Their fourth flight that day covered 852 feet (260 m) in 59 seconds.",
    value: "1903",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Contemporary witness accounts and photographic documentation, preserved by the Smithsonian National Air and Space Museum.",
    source: { title: "Smithsonian National Air and Space Museum — The Wright Brothers", url: "https://airandspace.si.edu/explore/stories/wright-brothers", date: "1903-12-17", location: "Kitty Hawk, North Carolina, USA" },
  },

  // --- Sports Records, continued ---
  {
    registryNumber: "LR-MOST-F1-CHAMPIONSHIPS", slug: "most-formula-1-world-championships", title: "Most Formula 1 World Championships",
    category: "Sports Records", subcategory: "Motorsport", direction: "MAXIMIZE",
    metricName: "Career Formula 1 Drivers' World Championships won", unit: "championships",
    formalStatement: "The greatest number of Formula 1 Drivers' World Championships won across a career.",
    summary: "Michael Schumacher and Lewis Hamilton are tied with 7 Formula 1 Drivers' World Championships each — the most of any driver in the sport's history. Schumacher won his between 1994 and 2004; Hamilton won his between 2008 and 2020. As of 2026, Max Verstappen leads active drivers with 4 titles.",
    value: "7",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official championship records maintained by the FIA (Fédération Internationale de l'Automobile).",
    source: { title: "Formula 1 — All-Time Statistics", url: "https://www.formula1.com/en/results/drivers", date: "2020-11-15", location: "Formula 1 World Championship" },
  },
  {
    registryNumber: "LR-HIGHEST-TEST-CRICKET-SCORE", slug: "highest-individual-score-test-cricket", title: "Highest individual score in Test cricket",
    category: "Sports Records", subcategory: "Cricket", direction: "MAXIMIZE",
    metricName: "Highest individual batting score in a single Test cricket innings", unit: "runs",
    formalStatement: "The greatest number of runs scored by a single batsman in one innings of a Test cricket match.",
    summary: "Brian Lara of the West Indies scored 400 not out against England in Antigua in April 2004 — the highest individual score in Test cricket history, reclaiming a record he had briefly lost in 2003, having previously also held it with 375 in 1994.",
    value: "400",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official match scorecard maintained by the International Cricket Council.",
    source: { title: "ESPNcricinfo — Brian Lara's 400 not out", url: "https://www.espncricinfo.com/", date: "2004-04-12", location: "Antigua Recreation Ground, Antigua" },
  },
  {
    registryNumber: "LR-LONGEST-TENNIS-MATCH", slug: "longest-tennis-match-ever-played", title: "Longest tennis match ever played",
    category: "Sports Records", subcategory: "Tennis", direction: "MAXIMIZE",
    metricName: "Duration of the longest tennis match ever played", unit: "hours",
    formalStatement: "The longest duration, in playing time, of any professional tennis match.",
    summary: "John Isner defeated Nicolas Mahut in a first-round match at Wimbledon in 2010 that lasted 11 hours 5 minutes across three days, with the final set alone going 70-68 — the longest tennis match ever played, prompting Wimbledon to later introduce a final-set tiebreak rule to prevent a repeat.",
    value: "11.08",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official match timing and scorecard maintained by the All England Lawn Tennis Club.",
    source: { title: "Wimbledon — The Longest Match", url: "https://www.wimbledon.com/en_GB/news/articles/2020-06-22/the_longest_match_isner_v_mahut_ten_years_on.html", date: "2010-06-24", location: "Wimbledon, London, UK" },
  },
  {
    registryNumber: "LR-YOUNGEST-CHESS-WORLD-CHAMPION", slug: "youngest-world-chess-champion", title: "Youngest undisputed world chess champion",
    category: "Sports Records", subcategory: "Chess", direction: "MINIMIZE",
    metricName: "Age at which the youngest undisputed world chess champion won the title", unit: "years",
    formalStatement: "The lowest age at which any player has won the undisputed World Chess Championship title.",
    summary: "Gukesh Dommaraju of India became the youngest undisputed world chess champion in history at 18 years and 195 days old, defeating defending champion Ding Liren of China in the final game of their December 2024 match in Singapore — breaking Garry Kasparov's record of age 22, set in 1985.",
    value: "18.53",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official match result recorded and ratified by FIDE, the International Chess Federation.",
    source: { title: "FIDE — World Chess Championship 2024 Result", url: "https://worldchampionship.fide.com/", date: "2024-12-12", location: "Singapore" },
  },
  {
    registryNumber: "LR-FASTEST-CHESS-CHECKMATE", slug: "fastest-possible-chess-checkmate", title: "Fastest possible checkmate in chess",
    category: "Sports Records", subcategory: "Chess", direction: "MINIMIZE",
    metricName: "Minimum number of moves in which checkmate can be forced from the start of a chess game", unit: "moves",
    formalStatement: "The minimum number of full moves in which checkmate can be delivered from the standard starting position of chess, given cooperative (or sufficiently poor) play by the losing side. This is a proven mathematical minimum, not a game-theoretic best-play outcome.",
    summary: "'Fool's Mate' is the fastest possible checkmate in chess, achieved in just 2 moves (1. f3 e5 2. g4 Qh4#) — this requires the losing side to make two of the worst possible opening moves, so it is a curiosity rather than a realistic outcome between skilled players, but it is a proven structural minimum for the game.",
    value: "2",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "PROVEN",
    methodSummary: "Exhaustive verification of chess's move rules and check/checkmate conditions — a matter of the game's formal rules, not empirical observation.",
    source: { title: "FIDE — Laws of Chess", url: "https://handbook.fide.com/chapter/E012023", date: "2023-01-01", location: "Standard chess rules (FIDE)" },
  },
  {
    registryNumber: "LR-FASTEST-100M-FREESTYLE-MEN", slug: "fastest-100m-freestyle-men", title: "Men's 100 meters freestyle (swimming) world record",
    category: "Sports Records", subcategory: "Swimming", direction: "MINIMIZE",
    metricName: "100 meters freestyle time, men, long course, record-eligible", unit: "s",
    formalStatement: "The fastest time recorded for a man to swim 100 meters freestyle in a long-course (50 m) pool, under World Aquatics record-eligible conditions.",
    summary: "Pan Zhanle of China swam 46.40 seconds in the men's 100m freestyle final at the 2024 Paris Olympics on July 31, 2024 — the current world record, breaking his own previous record set earlier that year.",
    value: "46.40",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Electronically timed race at the 2024 Summer Olympics, ratified by World Aquatics as the official world record.",
    source: { title: "World Aquatics — Pan Zhanle 100m freestyle world record", url: "https://www.worldaquatics.com/", date: "2024-07-31", location: "Paris La Défense Arena, France" },
  },
  {
    registryNumber: "LR-FASTEST-100M-FREESTYLE-WOMEN", slug: "fastest-100m-freestyle-women", title: "Women's 100 meters freestyle (swimming) world record",
    category: "Sports Records", subcategory: "Swimming", direction: "MINIMIZE",
    metricName: "100 meters freestyle time, women, long course, record-eligible", unit: "s",
    formalStatement: "The fastest time recorded for a woman to swim 100 meters freestyle in a long-course (50 m) pool, under World Aquatics record-eligible conditions.",
    summary: "Marrit Steenbergen of the Netherlands swam 51.68 seconds in Rome on June 27, 2026, breaking a world record that had stood for nine years — the current world record for the women's 100m freestyle.",
    value: "51.68",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Electronically timed race at a World Aquatics-sanctioned meet, ratified as the official world record.",
    source: { title: "NBC Sports — Marrit Steenbergen breaks 100m freestyle world record", url: "https://www.nbcsports.com/olympics/news/marrit-steenbergen-world-record-100-meter-freestyle", date: "2026-06-27", location: "Rome, Italy" },
  },
  {
    registryNumber: "LR-MOST-WIMBLEDON-SINGLES-TITLES", slug: "most-wimbledon-singles-titles", title: "Most Wimbledon singles titles",
    category: "Sports Records", subcategory: "Tennis", direction: "MAXIMIZE",
    metricName: "Career Wimbledon singles championship titles won", unit: "titles",
    formalStatement: "The greatest number of Wimbledon singles championship titles won by a single player, of either gender.",
    summary: "Martina Navratilova won 9 Wimbledon women's singles titles between 1978 and 1990 — the most Wimbledon singles titles won by any player in the Open Era, ahead of Roger Federer's 8 men's singles titles.",
    value: "9",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official tournament records maintained by the All England Lawn Tennis Club.",
    source: { title: "Wimbledon — Roll of Honour", url: "https://www.wimbledon.com/en_GB/atoz/roll_of_honour.html", date: "1990-07-08", location: "Wimbledon, London, UK" },
  },

  // --- Economics & Culture ---
  {
    registryNumber: "LR-FIRST-PAPER-CURRENCY", slug: "first-paper-currency", title: "First paper currency",
    category: "Economics", subcategory: "History of Money", direction: "MINIMIZE",
    metricName: "Century of the earliest known government-issued paper currency", unit: "century CE",
    formalStatement: "The earliest known instance of government-backed paper currency issued as legal tender.",
    summary: "China's Song Dynasty issued the first known government-backed paper currency, called 'jiaozi,' beginning around 1023 CE, building on earlier private merchant paper notes from the preceding Tang Dynasty — centuries before paper currency appeared in Europe (Sweden, 1661).",
    value: "11",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Historical numismatic and archival records from the Song Dynasty imperial government.",
    source: { title: "Federal Reserve Bank of San Francisco — History of paper money", url: "https://www.frbsf.org/education/publications/doctor-econ/2006/june/paper-money-history/", date: "1023-01-01", location: "Song Dynasty China" },
  },
  {
    registryNumber: "LR-OLDEST-COMPANY", slug: "oldest-continuously-operating-company", title: "Oldest continuously operating company",
    category: "Economics", subcategory: "Corporate History", direction: "MINIMIZE",
    metricName: "Founding year of the oldest continuously operating company", unit: "year",
    formalStatement: "The founding year of the oldest company that has operated continuously to the present day.",
    summary: "Kongō Gumi, a Japanese construction company specializing in Buddhist temples, was founded in 578 CE — the oldest continuously operating company in the world, having survived for over 1,400 years before becoming a subsidiary of the Takamatsu Construction Group in 2006 while continuing to operate under its own name.",
    value: "578",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Corporate registration and historical business records maintained in Japan.",
    source: { title: "Guinness World Records — Oldest company", url: "https://www.guinnessworldrecords.com/world-records/oldest-company", date: "578-01-01", location: "Osaka, Japan" },
  },
  {
    registryNumber: "LR-FIRST-CREDIT-CARD", slug: "first-credit-card", title: "First credit card",
    category: "Economics", subcategory: "History of Money", direction: "MINIMIZE",
    metricName: "Year the first general-purpose charge card was introduced", unit: "year",
    formalStatement: "The year the first general-purpose charge card, usable at multiple unrelated merchants, was introduced.",
    summary: "Diners Club launched the first general-purpose charge card in 1950, allowing members to charge meals at a network of restaurants in New York City and settle the balance monthly — the first card of its kind, predating bank-issued revolving credit cards like the BankAmericard (later Visa), which launched in 1958.",
    value: "1950",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Corporate historical records maintained by Diners Club International.",
    source: { title: "Diners Club International — Our History", url: "https://www.dinersclub.com/about-us", date: "1950-02-08", location: "New York City, USA" },
  },
  {
    registryNumber: "LR-LARGEST-DIAMOND-FOUND", slug: "largest-diamond-ever-found", title: "Largest diamond ever found",
    category: "Economics", subcategory: "Gemology", direction: "MAXIMIZE",
    metricName: "Weight of the largest gem-quality rough diamond ever found", unit: "carats",
    formalStatement: "The greatest weight of any gem-quality rough diamond ever discovered.",
    summary: "The Cullinan Diamond, found in South Africa in 1905, weighed 3,106 carats (621.2 grams) in its rough form — the largest gem-quality rough diamond ever discovered. It was cut into nine major stones and numerous smaller ones, including the Great Star of Africa, part of the British Crown Jewels.",
    value: "3106",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Physical weight measurement at discovery, documented by the Premier Mine and corroborated by gemological records.",
    source: { title: "Royal Collection Trust — The Cullinan Diamond", url: "https://www.rct.uk/collection/themes/exhibitions/the-cullinan-diamond", date: "1905-01-26", location: "Premier Mine, Cullinan, South Africa" },
  },
  {
    registryNumber: "LR-LONGEST-RUNNING-BROADWAY-SHOW", slug: "longest-running-broadway-show", title: "Longest-running Broadway show",
    category: "Food & Culture", subcategory: "Theater", direction: "MAXIMIZE",
    metricName: "Total number of performances of the longest-running Broadway show in history", unit: "performances",
    formalStatement: "The greatest total number of performances of any single production in Broadway history.",
    summary: "Andrew Lloyd Webber's 'The Phantom of the Opera' ran on Broadway from 1988 to its closing in April 2023, totaling 13,981 performances — the longest-running show in Broadway history, more than 5,000 performances ahead of the second-longest-running show, 'Chicago.'",
    value: "13981",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official performance count maintained by the Broadway League.",
    source: { title: "The Broadway League — Longest Running Shows on Broadway", url: "https://www.broadwayleague.com/", date: "2023-04-16", location: "Majestic Theatre, New York City, USA" },
  },

  // --- Science History Milestones ---
  {
    registryNumber: "LR-FIRST-VACCINE", slug: "first-vaccine-ever-developed", title: "First vaccine ever developed",
    category: "Medicine & Physiology", subcategory: "Medical History", direction: "MINIMIZE",
    metricName: "Year the first vaccine was developed and demonstrated", unit: "year",
    formalStatement: "The year of the first scientifically documented vaccine, demonstrated to confer immunity against a specific disease.",
    summary: "Edward Jenner demonstrated the first vaccine in 1796, inoculating a boy with cowpox material and showing it protected against smallpox — the founding demonstration of vaccination (the term itself derives from 'vacca,' Latin for cow), leading eventually to smallpox's global eradication in 1980.",
    value: "1796",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Jenner's original case documentation and subsequent publication, later corroborated by widespread replication.",
    source: { title: "World Health Organization — History of smallpox vaccination", url: "https://www.who.int/news-room/spotlight/history-of-vaccination/history-of-smallpox-vaccination", date: "1796-05-14", location: "Berkeley, Gloucestershire, England" },
  },
  {
    registryNumber: "LR-FIRST-ANTIBIOTIC", slug: "first-antibiotic-discovered", title: "First antibiotic discovered",
    category: "Medicine & Physiology", subcategory: "Medical History", direction: "MINIMIZE",
    metricName: "Year the first antibiotic was discovered", unit: "year",
    formalStatement: "The year of the discovery of the first antibiotic compound.",
    summary: "Alexander Fleming discovered penicillin in 1928 after noticing that a mold contaminating one of his bacterial culture plates had killed the surrounding bacteria — the first antibiotic ever discovered, though it took until the early 1940s for Howard Florey and Ernst Chain to develop it into a usable medical treatment, work for which all three shared the 1945 Nobel Prize.",
    value: "1928",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Fleming's original 1929 publication describing the discovery, corroborated by the Nobel Committee's 1945 prize citation.",
    source: { title: "Nobel Prize — Alexander Fleming, Biographical", url: "https://www.nobelprize.org/prizes/medicine/1945/fleming/biographical/", date: "1928-09-03", location: "St Mary's Hospital, London, UK" },
  },
  {
    registryNumber: "LR-FIRST-GENE-THERAPY", slug: "first-successful-gene-therapy", title: "First successful human gene therapy",
    category: "Medicine & Physiology", subcategory: "Medical History", direction: "MINIMIZE",
    metricName: "Year of the first approved and successful human gene therapy treatment", unit: "year",
    formalStatement: "The year of the first officially approved and clinically successful human gene therapy treatment.",
    summary: "Four-year-old Ashanti DeSilva received the first approved human gene therapy treatment in 1990 at the National Institutes of Health, for a rare immune disorder called ADA-SCID — the treatment successfully boosted her immune function, marking the first clinically successful application of gene therapy in a human patient.",
    value: "1990",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Documented clinical trial conducted at the U.S. National Institutes of Health, published in peer-reviewed medical literature.",
    source: { title: "National Human Genome Research Institute — Gene Therapy history", url: "https://www.genome.gov/", date: "1990-09-14", location: "National Institutes of Health, Bethesda, Maryland, USA" },
  },
  {
    registryNumber: "LR-HUMAN-GENOME-SEQUENCED", slug: "first-human-genome-fully-sequenced", title: "First human genome fully sequenced",
    category: "Medicine & Physiology", subcategory: "Medical History", direction: "MINIMIZE",
    metricName: "Year the first complete human genome sequence was published", unit: "year",
    formalStatement: "The year the Human Genome Project published a complete, high-quality reference sequence of the human genome.",
    summary: "The publicly funded Human Genome Project, an international collaboration begun in 1990, announced completion of a essentially complete human genome sequence in April 2003 — two years ahead of schedule, at a cost of roughly $2.7 billion, providing the reference map that underlies virtually all modern genomic medicine and research.",
    value: "2003",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "International collaborative sequencing effort, published jointly by participating research institutions.",
    source: { title: "National Human Genome Research Institute — Human Genome Project completion", url: "https://www.genome.gov/human-genome-project", date: "2003-04-14", location: "International collaboration, multiple countries" },
  },
  {
    registryNumber: "LR-FIRST-CLONED-MAMMAL", slug: "first-cloned-mammal", title: "First cloned mammal",
    category: "Medicine & Physiology", subcategory: "Medical History", direction: "MINIMIZE",
    metricName: "Year the first mammal was successfully cloned from an adult somatic cell", unit: "year",
    formalStatement: "The year the first mammal was successfully cloned from the DNA of an adult (non-reproductive) cell.",
    summary: "Dolly the sheep, born July 5, 1996 at the Roslin Institute in Scotland, was the first mammal successfully cloned from an adult somatic cell — created from a mammary gland cell of a six-year-old ewe, proving that a fully differentiated adult cell could be used to create a genetically identical new organism.",
    value: "1996",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Somatic cell nuclear transfer, published in a peer-reviewed study in Nature.",
    source: { title: "Wilmut et al., \"Viable offspring derived from fetal and adult mammalian cells,\" Nature (1997)", url: "https://www.nature.com/articles/385810a0", date: "1996-07-05", location: "Roslin Institute, Scotland, UK" },
  },
  {
    registryNumber: "LR-FIRST-BLACK-HOLE-IMAGE", slug: "first-image-of-a-black-hole", title: "First direct image of a black hole",
    category: "Astrophysics", subcategory: "Observational Astronomy", direction: "MINIMIZE",
    metricName: "Year the first direct image of a black hole's event horizon shadow was published", unit: "year",
    formalStatement: "The year the first direct image of a black hole's silhouette against its surrounding accretion disk was published.",
    summary: "The Event Horizon Telescope collaboration, using a network of radio telescopes spanning the globe synchronized to act as one Earth-sized instrument, published the first direct image of a black hole — the supermassive black hole at the center of galaxy M87, 55 million light-years away — on April 10, 2019.",
    value: "2019",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Very-long-baseline interferometry combining data from eight radio telescopes worldwide, published in a peer-reviewed astrophysics journal.",
    source: { title: "Event Horizon Telescope Collaboration, \"First M87 Event Horizon Telescope Results,\" Astrophysical Journal Letters (2019)", url: "https://iopscience.iop.org/article/10.3847/2041-8213/ab0ec7", date: "2019-04-10", location: "Event Horizon Telescope global array" },
  },
  {
    registryNumber: "LR-DEEPEST-HUMAN-MADE-HOLE", slug: "deepest-human-made-hole", title: "Deepest human-made hole",
    category: "Engineering", subcategory: "Geological Engineering", direction: "MAXIMIZE",
    metricName: "Depth of the deepest artificial borehole ever drilled", unit: "km",
    formalStatement: "The greatest depth of any artificial hole drilled into Earth's surface.",
    summary: "The Kola Superdeep Borehole, drilled by the Soviet Union in the Kola Peninsula starting in 1970, reached a depth of 12,262 m (7.62 mi) by 1989 — the deepest artificial point on Earth, though the hole is narrow (23 cm diameter) and only about a third of the way through Earth's crust. Drilling stopped after temperatures at depth (180°C) exceeded predictions.",
    value: "12.262",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Direct drilling depth measurement, documented by the Soviet (later Russian) research program that operated the site.",
    source: { title: "Scientific American — The Kola Superdeep Borehole", url: "https://www.scientificamerican.com/article/kola-superdeep-borehole-deepest-hole/", date: "1989-01-01", location: "Kola Peninsula, Russia" },
  },
  {
    registryNumber: "LR-GREAT-PYRAMID-HISTORICAL-TALLEST", slug: "tallest-structure-in-history-great-pyramid", title: "Longest-held record for tallest human-made structure",
    category: "Engineering", subcategory: "History", direction: "MAXIMIZE",
    metricName: "Number of years the Great Pyramid of Giza held the record for tallest human-made structure", unit: "years",
    formalStatement: "The greatest length of time any single structure has held the record for tallest human-made structure on Earth.",
    summary: "The Great Pyramid of Giza, completed around 2560 BCE at a height of 146.6 m, held the record for tallest human-made structure in the world for approximately 3,871 years — until Lincoln Cathedral's spire, completed in England around 1311 CE, surpassed it. No other structure has held the 'tallest' title anywhere near as long, before or since.",
    value: "3871",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Historical architectural records cross-referenced with archaeological dating of both structures.",
    source: { title: "Guinness World Records — Tallest structure ever, historical", url: "https://www.guinnessworldrecords.com/world-records/tallest-structure-ever", date: "1311-01-01", location: "Giza, Egypt; Lincoln, England" },
  },
  {
    registryNumber: "LR-FIRST-EXOPLANET-DISCOVERED", slug: "first-exoplanet-discovered", title: "First exoplanet discovered orbiting a Sun-like star",
    category: "Astrophysics", subcategory: "Observational Astronomy", direction: "MINIMIZE",
    metricName: "Year the first exoplanet orbiting a Sun-like star was confirmed", unit: "year",
    formalStatement: "The year of the first confirmed detection of a planet orbiting a Sun-like (main-sequence) star outside our solar system.",
    summary: "Swiss astronomers Michel Mayor and Didier Queloz announced the discovery of 51 Pegasi b in October 1995, a gas-giant planet orbiting a Sun-like star 50 light-years away — the first exoplanet found around a Sun-like star, opening the field of exoplanet science that has since found over 5,000 confirmed planets. Mayor and Queloz shared the 2019 Nobel Prize in Physics for the discovery.",
    value: "1995",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Radial velocity (Doppler wobble) detection method, published in a peer-reviewed astronomy journal and recognized by the Nobel Committee.",
    source: { title: "Nobel Prize — Mayor and Queloz, Press Release 2019", url: "https://www.nobelprize.org/prizes/physics/2019/press-release/", date: "1995-10-06", location: "Observatoire de Haute-Provence, France" },
  },
  {
    registryNumber: "LR-LONGEST-TOTAL-LUNAR-ECLIPSE", slug: "longest-total-lunar-eclipse-observed", title: "Longest total lunar eclipse of the 21st century",
    category: "Astrophysics", subcategory: "Celestial Mechanics", direction: "MAXIMIZE",
    metricName: "Duration of totality of the longest total lunar eclipse of the 21st century", unit: "min",
    formalStatement: "The longest duration of totality recorded for any total lunar eclipse in the 21st century (2001-2100), per NASA eclipse calculations.",
    summary: "The total lunar eclipse of July 27, 2018 lasted 1 hour 42 minutes 57 seconds in totality — the longest total lunar eclipse of the 21st century, visible across Africa, the Middle East, and Asia, occurring near the Moon's apogee (farthest point from Earth), which slows its apparent movement through Earth's shadow.",
    value: "102.95",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Orbital mechanics calculation of the Earth-Moon-Sun geometry, published by NASA's eclipse research program.",
    source: { title: "NASA Eclipse Web Site — Lunar Eclipses of the 21st Century", url: "https://eclipse.gsfc.nasa.gov/LEcat5/LE2001-2100.html", date: "2018-07-27", location: "Visible from Africa, Middle East, Asia" },
  },
  {
    registryNumber: "LR-FIRST-IVF-BIRTH", slug: "first-ivf-birth", title: "First successful in vitro fertilization birth",
    category: "Medicine & Physiology", subcategory: "Medical History", direction: "MINIMIZE",
    metricName: "Year of the first human birth resulting from in vitro fertilization", unit: "year",
    formalStatement: "The year of the first successful human birth resulting from in vitro fertilization (IVF).",
    summary: "Louise Brown was born on July 25, 1978, in Oldham, England — the first human born via in vitro fertilization, developed by physiologist Robert Edwards and gynecologist Patrick Steptoe. Edwards was awarded the Nobel Prize in Physiology or Medicine in 2010 for the achievement, by which point IVF had helped conceive an estimated several million children worldwide.",
    value: "1978",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Documented medical case with public birth record, later recognized by the Nobel Committee.",
    source: { title: "Nobel Prize — Robert G. Edwards, Biographical", url: "https://www.nobelprize.org/prizes/medicine/2010/edwards/biographical/", date: "1978-07-25", location: "Oldham General Hospital, England" },
  },
];
