import type { FrontierRecord } from "./frontier-records-2026";

// Ninth real-world-records batch (2026-10-05) — focused on Engineering, Energy, and Materials Science.
// Covers record buildings, bridges, tunnels, rail, aviation, ships and heavy vehicles; power
// generation efficiency, transmission, fusion and oil & gas extremes; and materials records
// (toughness, thermal, magnetic, optical, electronic, superconducting). Cross-checked against the
// full list of existing registry titles to avoid duplicates — e.g. "highest railway bridge" and
// "tallest bridge by structural height" are distinct from the existing deck-height record, and
// "highest-voltage AC line" is distinct from the existing DC transmission record.
export const WORLD_RECORDS_BATCH9_ENGINEERING: FrontierRecord[] = [
  // --- Engineering: Buildings & Civil Structures ---
  {
    registryNumber: "LR-TALLEST-BUILDING-BURJ-KHALIFA", slug: "tallest-building-burj-khalifa", title: "Tallest building in the world",
    category: "Engineering", subcategory: "Skyscrapers", direction: "MAXIMIZE",
    metricName: "Architectural height of a completed habitable building", unit: "m",
    formalStatement: "The greatest architectural height (to spire, excluding antennas) of any completed building with occupiable floors, as measured under CTBUH criteria.",
    summary: "Burj Khalifa in Dubai, United Arab Emirates, designed by Adrian Smith at Skidmore, Owings & Merrill and opened on January 4, 2010, stands 828 m tall with 163 floors. It has held the title of world's tallest building ever since; Jeddah Tower in Saudi Arabia, intended to exceed 1,000 m, remained under construction in 2026.",
    value: "828",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Height to architectural top certified by the Council on Tall Buildings and Urban Habitat (CTBUH) under its standard height criteria.",
    source: { title: "CTBUH Skyscraper Center — Burj Khalifa", url: "https://www.skyscrapercenter.com/building/burj-khalifa/3", date: "2010-01-04", location: "Dubai, United Arab Emirates" },
  },
  {
    registryNumber: "LR-TALLEST-RESIDENTIAL-BUILDING-CENTRAL-PARK-TOWER", slug: "tallest-residential-building-central-park-tower", title: "Tallest residential building",
    category: "Engineering", subcategory: "Skyscrapers", direction: "MAXIMIZE",
    metricName: "Architectural height of an all-residential building", unit: "m",
    formalStatement: "The greatest architectural height of a completed building whose occupiable floor area is predominantly residential.",
    summary: "Central Park Tower (also called Nordstrom Tower) at 225 West 57th Street in Manhattan, New York City, developed by Extell and designed by Adrian Smith + Gordon Gill Architecture, topped out in 2019 and was completed in 2020 at 472 m (1,550 ft). It is the tallest residential-only building in the world and has the highest roof of any building outside Asia.",
    value: "472",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Architectural height recorded by the CTBUH Skyscraper Center.",
    source: { title: "CTBUH Skyscraper Center — Central Park Tower", url: "https://www.skyscrapercenter.com/building/central-park-tower/14269", date: "2020-10-01", location: "New York City, New York, USA" },
  },
  {
    registryNumber: "LR-TALLEST-TWIN-TOWERS-PETRONAS", slug: "tallest-twin-towers-petronas", title: "Tallest twin towers",
    category: "Engineering", subcategory: "Skyscrapers", direction: "MAXIMIZE",
    metricName: "Architectural height of the tallest identical twin-tower pair", unit: "m",
    formalStatement: "The greatest architectural height of a pair of identical towers built as a single twin-tower development.",
    summary: "The Petronas Twin Towers in Kuala Lumpur, Malaysia, designed by César Pelli and completed in 1998, each stand 451.9 m tall and are linked by a two-storey skybridge at levels 41–42. They were the world's tallest buildings from 1998 until Taipei 101 surpassed them in 2004, and they remain the tallest twin towers ever built.",
    value: "451.9",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Architectural height to spire tip certified by the CTBUH.",
    source: { title: "CTBUH Skyscraper Center — Petronas Twin Towers", url: "https://www.skyscrapercenter.com/building/petronas-twin-tower-1/419", date: "1998-01-01", location: "Kuala Lumpur, Malaysia" },
  },
  {
    registryNumber: "LR-LARGEST-OFFICE-BUILDING-FLOOR-AREA", slug: "largest-office-building-floor-area", title: "Largest office building by floor area",
    category: "Engineering", subcategory: "Buildings", direction: "MAXIMIZE",
    metricName: "Total gross floor area of a single office building complex", unit: "m²",
    formalStatement: "The largest gross floor area of any single building designed primarily for office use.",
    summary: "The Surat Diamond Bourse in Gujarat, India, a 15-storey complex of nine interconnected towers designed by Indian firm Morphogenesis, has about 660,000 m² (7.1 million sq ft) of floor space. Guinness World Records recognised it in August 2023 as the world's largest office building, ending the Pentagon's roughly 80-year hold on the title.",
    value: "660000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Floor area as certified by Guinness World Records from architectural documentation.",
    source: { title: "Guinness World Records — Surat Diamond Bourse surpasses the Pentagon as world's largest office building", url: "https://www.guinnessworldrecords.com/news/2023/8/surat-diamond-bourse-surpasses-the-pentagon-as-worlds-largest-office-building-757334", date: "2023-08-22", location: "Surat, Gujarat, India" },
  },
  {
    registryNumber: "LR-LARGEST-STADIUM-BY-SEATING-CAPACITY", slug: "largest-stadium-by-seating-capacity", title: "Largest stadium by seating capacity",
    category: "Engineering", subcategory: "Buildings", direction: "MAXIMIZE",
    metricName: "Official spectator seating capacity of a single stadium", unit: "seats",
    formalStatement: "The highest official seated spectator capacity of any existing sports stadium.",
    summary: "Narendra Modi Stadium in Ahmedabad, India, rebuilt on the site of the former Sardar Patel (Motera) Stadium and inaugurated in February 2021, has an official seating capacity of about 132,000 — the largest of any stadium in the world. Capacity claims for some other venues (such as Pyongyang's Rungrado 1st of May Stadium, often quoted at 114,000–150,000) are poorly documented.",
    value: "132000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Official seating capacity published by the Gujarat Cricket Association; competing venues' figures are not independently audited.",
    source: { title: "Gujarat Cricket Association — Narendra Modi Stadium", url: "https://www.gujaratcricketassociation.com/", date: "2021-02-24", location: "Ahmedabad, Gujarat, India" },
  },
  {
    registryNumber: "LR-TALLEST-STRUCTURE-EVER-MOVED-TROLL-A", slug: "tallest-structure-ever-moved-troll-a", title: "Tallest structure ever moved",
    category: "Engineering", subcategory: "Offshore Structures", direction: "MAXIMIZE",
    metricName: "Total height of a structure relocated as a single unit", unit: "m",
    formalStatement: "The greatest total height of any structure moved intact across land or sea from its construction site to its final location.",
    summary: "The Troll A natural-gas platform's concrete gravity-base structure, 472 m tall overall and weighing about 656,000 tonnes, was towed more than 200 km from Vats, Norway, to the Troll field in the North Sea in 1995. It is recognised as the tallest — and among the heaviest — structures ever moved by humans; most of it sits below the waterline in about 303 m of water.",
    value: "472",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Structural height from Norwegian Contractors/Equinor engineering specifications; recognised by Guinness World Records.",
    source: { title: "Equinor — Troll A platform", url: "https://www.equinor.com/energy/troll", date: "1995-05-01", location: "Troll field, North Sea, Norway" },
  },
  // --- Engineering: Bridges & Tunnels ---
  {
    registryNumber: "LR-LONGEST-ARCH-BRIDGE-SPAN", slug: "longest-arch-bridge-span", title: "Longest arch bridge span",
    category: "Engineering", subcategory: "Bridges", direction: "MAXIMIZE",
    metricName: "Main span length of an arch bridge", unit: "m",
    formalStatement: "The longest clear main span of any completed arch bridge of any material.",
    summary: "The Tian'e Longtan Bridge over the Hongshui River in Guangxi, China, opened on February 1, 2024, with a 600 m main arch span — the longest arch span in the world and 155 m longer than the previous concrete-arch record. Its steel-reinforced concrete arch was built around an internal steel-tube skeleton, surpassing the 552 m Chaotianmen (steel) and 575 m Pingnan Third Bridge (concrete-filled steel tube) arches.",
    value: "600",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Span from design and construction documentation reported in peer-reviewed engineering literature.",
    source: { title: "Advances in Bridge Engineering — Key innovations in the construction of Tian'e Longtan Bridge", url: "https://link.springer.com/article/10.1186/s43251-026-00222-7", date: "2024-02-01", location: "Tian'e County, Guangxi, China" },
  },
  {
    registryNumber: "LR-LONGEST-FLOATING-BRIDGE", slug: "longest-floating-bridge", title: "Longest floating bridge",
    category: "Engineering", subcategory: "Bridges", direction: "MAXIMIZE",
    metricName: "Length of the floating section of a pontoon bridge", unit: "m",
    formalStatement: "The longest floating (pontoon-supported) bridge span in the world, measured along the floating portion.",
    summary: "The Evergreen Point Floating Bridge (State Route 520) across Lake Washington between Seattle and Medina, Washington, opened in April 2016 with a floating section of 2,350 m (7,710 ft), supported by 77 concrete pontoons. It replaced a 1963 floating bridge that had itself held the record and is recognised by Guinness World Records as the world's longest floating bridge.",
    value: "2350",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Length from Washington State Department of Transportation project specifications; Guinness World Records certification.",
    source: { title: "WSDOT — SR 520 Floating Bridge", url: "https://wsdot.wa.gov/construction-planning/major-projects/sr-520-bridge-replacement-and-hov-program", date: "2016-04-25", location: "Lake Washington, Washington, USA" },
  },
  {
    registryNumber: "LR-LONGEST-BRIDGE-TUNNEL-SEA-CROSSING", slug: "longest-bridge-tunnel-sea-crossing", title: "Longest bridge-tunnel sea crossing",
    category: "Engineering", subcategory: "Bridges", direction: "MAXIMIZE",
    metricName: "Total length of a fixed sea crossing combining bridges, artificial islands and an undersea tunnel", unit: "km",
    formalStatement: "The longest fixed link across open sea built as a combined bridge-island-tunnel system.",
    summary: "The Hong Kong–Zhuhai–Macao Bridge, opened on October 24, 2018, spans about 55 km across the Pearl River Estuary, combining three cable-stayed bridges, two artificial islands and a 6.7 km immersed-tube tunnel. It is the longest sea-crossing fixed link in the world.",
    value: "55",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Overall length from the Hong Kong–Zhuhai–Macao Bridge Authority.",
    source: { title: "Hong Kong–Zhuhai–Macao Bridge Authority", url: "https://www.hzmb.org/", date: "2018-10-24", location: "Pearl River Estuary, China" },
  },
  {
    registryNumber: "LR-HIGHEST-RAILWAY-BRIDGE-CHENAB", slug: "highest-railway-bridge-chenab", title: "Highest railway bridge",
    category: "Engineering", subcategory: "Bridges", direction: "MAXIMIZE",
    metricName: "Height of rail deck above the river bed/water", unit: "m",
    formalStatement: "The greatest height of a railway bridge's deck above the river or valley floor it crosses.",
    summary: "The Chenab Rail Bridge in the Reasi district of Jammu and Kashmir, India, carries the Udhampur–Srinagar–Baramulla railway 359 m above the Chenab River on a 467 m steel arch. Inaugurated on June 6, 2025, it is the highest railway bridge in the world, about 35 m higher than the Eiffel Tower.",
    value: "359",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Deck height from Indian Railways / Konkan Railway Corporation design specifications.",
    source: { title: "Indian Railways — Chenab Bridge", url: "https://indianrailways.gov.in/", date: "2025-06-06", location: "Reasi, Jammu and Kashmir, India" },
  },
  {
    registryNumber: "LR-TALLEST-BRIDGE-BY-STRUCTURAL-HEIGHT-MILLAU", slug: "tallest-bridge-by-structural-height-millau", title: "Tallest bridge by structural height",
    category: "Engineering", subcategory: "Bridges", direction: "MAXIMIZE",
    metricName: "Height from base to top of the tallest mast/pylon", unit: "m",
    formalStatement: "The tallest bridge structure measured from the base of its tallest pier to the top of its mast, irrespective of deck height.",
    summary: "The Millau Viaduct, a cable-stayed bridge across the Tarn valley in southern France designed by Michel Virlogeux and Norman Foster and opened in December 2004, reaches 343 m from the base of its tallest pier to the top of its mast. It remains the tallest bridge in the world by structural height, though deeper gorges in China have bridges with higher decks.",
    value: "343",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Structural height from the operator, Compagnie Eiffage du Viaduc de Millau.",
    source: { title: "Viaduc de Millau — official site", url: "https://www.leviaducdemillau.com/", date: "2004-12-16", location: "Millau, Aveyron, France" },
  },
  {
    registryNumber: "LR-LONGEST-ROAD-TUNNEL-LAERDAL", slug: "longest-road-tunnel-laerdal", title: "Longest road tunnel",
    category: "Engineering", subcategory: "Tunnels", direction: "MAXIMIZE",
    metricName: "Length of a single road tunnel bore", unit: "km",
    formalStatement: "The longest tunnel built for road vehicles, measured portal to portal.",
    summary: "The Lærdal Tunnel on Norway's E16 between Lærdal and Aurland, opened on November 27, 2000, is 24.51 km long — the longest road tunnel in the world. It contains three large lit caverns to reduce driver fatigue; Norway's Rogfast subsea tunnel, under construction, is planned to exceed it.",
    value: "24.51",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Length from the Norwegian Public Roads Administration (Statens vegvesen).",
    source: { title: "Statens vegvesen — Lærdal Tunnel", url: "https://www.vegvesen.no/", date: "2000-11-27", location: "Lærdal–Aurland, Norway" },
  },
  {
    registryNumber: "LR-LONGEST-UNDERSEA-TUNNEL-SECTION", slug: "longest-undersea-tunnel-section", title: "Longest undersea tunnel section",
    category: "Engineering", subcategory: "Tunnels", direction: "MAXIMIZE",
    metricName: "Length of tunnel running beneath the seabed", unit: "km",
    formalStatement: "The longest continuous portion of any tunnel that lies beneath the sea.",
    summary: "The Channel Tunnel between Folkestone, England, and Coquelles, France, opened on May 6, 1994, is 50.45 km long, of which about 37.9 km runs beneath the English Channel — the longest undersea tunnel section in the world. Japan's Seikan Tunnel is longer overall (53.85 km) but has a shorter undersea portion (23.3 km).",
    value: "37.9",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Tunnel geometry from Getlink (Eurotunnel) engineering data.",
    source: { title: "Getlink — The Channel Tunnel", url: "https://www.getlinkgroup.com/en/our-group/channel-tunnel/", date: "1994-05-06", location: "English Channel, UK–France" },
  },
  {
    registryNumber: "LR-LARGEST-TUNNEL-BORING-MACHINE", slug: "largest-tunnel-boring-machine", title: "Largest tunnel boring machine by diameter",
    category: "Engineering", subcategory: "Tunnels", direction: "MAXIMIZE",
    metricName: "Cutterhead/shield diameter of a tunnel boring machine", unit: "m",
    formalStatement: "The largest bore diameter of any tunnel boring machine put into service.",
    summary: "A Herrenknecht mixshield TBM used by Dragages–Bouygues on Hong Kong's Tuen Mun–Chek Lap Kok Link subsea road tunnel had a 17.6 m (17.63 m) shield diameter, recognised by Guinness World Records as the largest TBM ever. It began boring in 2015 and was slightly larger than Seattle's 17.45 m 'Bertha'.",
    value: "17.6",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Shield diameter from manufacturer specification (Herrenknecht AG); Guinness World Records certification.",
    source: { title: "Herrenknecht — Tuen Mun–Chek Lap Kok Link project", url: "https://www.herrenknecht.com/en/", date: "2015-01-01", location: "Hong Kong, China" },
  },
  {
    registryNumber: "LR-DEEPEST-METRO-STATION", slug: "deepest-metro-station", title: "Deepest metro station",
    category: "Engineering", subcategory: "Rail", direction: "MAXIMIZE",
    metricName: "Depth of station platforms below ground level", unit: "m",
    formalStatement: "The greatest depth below the surface of any passenger metro station in service.",
    summary: "Arsenalna station on the Kyiv Metro's Sviatoshynsko-Brovarska line in Ukraine, opened in 1960, lies about 105.5 m below ground, making it the deepest metro station in the world. Because of the hilly terrain, passengers ride two long escalator flights to reach the platforms.",
    value: "105.5",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Station depth from Kyiv Metro operator data.",
    source: { title: "Kyiv Metro — Arsenalna station", url: "https://www.metro.kyiv.ua/", date: "1960-11-06", location: "Kyiv, Ukraine" },
  },
  // --- Engineering: Rail & Transport Infrastructure ---
  {
    registryNumber: "LR-LARGEST-HIGH-SPEED-RAIL-NETWORK", slug: "largest-high-speed-rail-network", title: "Largest national high-speed rail network",
    category: "Engineering", subcategory: "Rail", direction: "MAXIMIZE",
    metricName: "Total route length of high-speed (≥250 km/h) lines in one country", unit: "km",
    formalStatement: "The greatest total route length of dedicated high-speed railway lines operated in a single country.",
    summary: "China's high-speed rail network exceeded 50,000 route-km by the end of 2025, according to China State Railway Group — more than the rest of the world's high-speed lines combined. The first dedicated line, Beijing–Tianjin, opened only in 2008.",
    value: "50000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Route-length statistics published by China State Railway Group; definitions of 'high-speed' vary by country.",
    source: { title: "Railway Gazette International — China's 'eight by eight' network nears completion", url: "https://www.railwaygazette.com/emu/2026/03/07/china-eight-by-eight-network-nears-completion-with-latest-wave-of-openings/", date: "2025-12-31", location: "China" },
  },
  {
    registryNumber: "LR-LONGEST-STRAIGHT-RAILWAY-TRACK", slug: "longest-straight-railway-track", title: "Longest straight stretch of railway",
    category: "Engineering", subcategory: "Rail", direction: "MAXIMIZE",
    metricName: "Length of railway track without a curve", unit: "km",
    formalStatement: "The longest section of railway line that runs perfectly straight.",
    summary: "The Trans-Australian Railway crosses the Nullarbor Plain with a 478 km (297 mi) section of dead-straight track between Ooldea, South Australia, and Loongana, Western Australia. Completed in 1917, it is the longest straight stretch of railway in the world.",
    value: "478",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Track alignment data from the Australian Rail Track Corporation, operator of the line.",
    source: { title: "Australian Rail Track Corporation — Trans-Australian line", url: "https://www.artc.com.au/", date: "1917-10-17", location: "Nullarbor Plain, Australia" },
  },
  {
    registryNumber: "LR-STEEPEST-COGWHEEL-RAILWAY", slug: "steepest-cogwheel-railway", title: "Steepest cogwheel railway",
    category: "Engineering", subcategory: "Rail", direction: "MAXIMIZE",
    metricName: "Maximum gradient of a rack railway", unit: "%",
    formalStatement: "The steepest maximum gradient on any rack (cogwheel) railway in passenger service.",
    summary: "The Pilatus Railway near Lucerne, Switzerland, opened in 1889, reaches a maximum gradient of 48% using the unique Locher rack system with horizontal cogwheels that prevent derailment. It is the steepest cogwheel railway in the world.",
    value: "48",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Gradient from the operator, Pilatus-Bahnen AG.",
    source: { title: "Pilatus-Bahnen — Cogwheel railway", url: "https://www.pilatus.ch/en/", date: "1889-06-04", location: "Alpnachstad–Pilatus Kulm, Switzerland" },
  },
  {
    registryNumber: "LR-STEEPEST-FUNICULAR-RAILWAY", slug: "steepest-funicular-railway", title: "Steepest funicular railway",
    category: "Engineering", subcategory: "Rail", direction: "MAXIMIZE",
    metricName: "Maximum gradient of a cable-hauled funicular", unit: "%",
    formalStatement: "The steepest maximum gradient of any funicular railway in passenger service.",
    summary: "The Stoosbahn in the canton of Schwyz, Switzerland, opened in December 2017, climbs gradients of up to 110% (about 47.7°) using cylindrical, self-levelling passenger cabins. It is the steepest funicular railway in the world.",
    value: "110",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Gradient from the operator, Stoosbahnen AG.",
    source: { title: "Stoosbahnen — Steepest funicular in the world", url: "https://www.stoos.ch/", date: "2017-12-16", location: "Schwyz–Stoos, Switzerland" },
  },
  {
    registryNumber: "LR-LONGEST-THREE-ROPE-CABLE-CAR", slug: "longest-three-rope-cable-car", title: "Longest non-stop three-rope cable car",
    category: "Engineering", subcategory: "Cableways", direction: "MAXIMIZE",
    metricName: "Length of a continuous three-rope (3S) cable car line", unit: "m",
    formalStatement: "The longest three-rope aerial cableway in a single continuous section.",
    summary: "The Hon Thom cable car in Phu Quoc, Vietnam, built by Doppelmayr for Sun Group and opened in 2018, runs 7,899.9 m over the sea between An Thoi and Hon Thom island. Guinness World Records recognised it as the longest non-stop three-rope cable car in the world.",
    value: "7899.9",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Line length certified by Guinness World Records from Doppelmayr documentation.",
    source: { title: "Doppelmayr — Hon Thom 3S cable car", url: "https://www.doppelmayr.com/en/", date: "2018-02-02", location: "Phu Quoc, Kien Giang, Vietnam" },
  },
  {
    registryNumber: "LR-LONGEST-OUTDOOR-COVERED-ESCALATOR-SYSTEM", slug: "longest-outdoor-covered-escalator-system", title: "Longest outdoor covered escalator system",
    category: "Engineering", subcategory: "Vertical Transport", direction: "MAXIMIZE",
    metricName: "Total length of a linked outdoor escalator system", unit: "m",
    formalStatement: "The longest outdoor covered escalator and travelator system serving as public transport.",
    summary: "The Central–Mid-Levels escalator and walkway system in Hong Kong, opened in October 1993, runs about 800 m and climbs 135 m from Central to the Mid-Levels. It is the longest outdoor covered escalator system in the world, reversing direction according to commuter flow.",
    value: "800",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Length from Hong Kong Transport Department data.",
    source: { title: "Hong Kong Transport Department — Central–Mid-Levels Escalator", url: "https://www.td.gov.hk/", date: "1993-10-15", location: "Hong Kong, China" },
  },
  // --- Engineering: Aviation ---
  {
    registryNumber: "LR-LARGEST-AIRCRAFT-BY-WINGSPAN", slug: "largest-aircraft-by-wingspan", title: "Largest aircraft by wingspan",
    category: "Engineering", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "Wingspan of an aircraft that has flown", unit: "m",
    formalStatement: "The greatest wingspan of any aircraft to have achieved flight.",
    summary: "Stratolaunch's Model 351 'Roc', a twin-fuselage carrier aircraft built by Scaled Composites, has a 117 m (385 ft) wingspan — longer than an American football field. It first flew from the Mojave Air and Space Port, California, on April 13, 2019.",
    value: "117",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Dimensions from Stratolaunch manufacturer specifications.",
    source: { title: "Stratolaunch — Roc carrier aircraft", url: "https://www.stratolaunch.com/", date: "2019-04-13", location: "Mojave, California, USA" },
  },
  {
    registryNumber: "LR-HEAVIEST-AIRCRAFT-MAX-TAKEOFF-WEIGHT", slug: "heaviest-aircraft-max-takeoff-weight", title: "Heaviest aircraft ever flown",
    category: "Engineering", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "Maximum take-off weight", unit: "t",
    formalStatement: "The highest maximum take-off weight of any aircraft that has flown.",
    summary: "The Antonov An-225 Mriya, a six-engine Soviet/Ukrainian strategic airlifter that first flew on December 21, 1988, had a maximum take-off weight of 640 tonnes — the heaviest of any aircraft. The only completed example was destroyed at Hostomel Airport during the Russian invasion of Ukraine in February 2022.",
    value: "640",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Maximum take-off weight from Antonov manufacturer specifications.",
    source: { title: "Antonov Company — An-225 Mriya", url: "https://www.antonov.com/en/history/an-225", date: "1988-12-21", location: "Kyiv, Ukraine" },
  },
  {
    registryNumber: "LR-LARGEST-PASSENGER-AIRLINER-CAPACITY", slug: "largest-passenger-airliner-capacity", title: "Largest certified passenger capacity of an airliner",
    category: "Engineering", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "Maximum certified passenger seating of an airliner type", unit: "passengers",
    formalStatement: "The highest maximum passenger capacity certified for any commercial airliner type.",
    summary: "The Airbus A380, a full double-deck airliner that first flew on April 27, 2005, is certified for up to 853 passengers in an all-economy layout — the highest of any airliner. Production ended in 2021 after 251 aircraft.",
    value: "853",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Exit-limit passenger capacity from Airbus specifications and EASA/FAA type certification.",
    source: { title: "Airbus — A380", url: "https://aircraft.airbus.com/en/aircraft/a380", date: "2005-04-27", location: "Toulouse, France" },
  },
  {
    registryNumber: "LR-MOST-POWERFUL-JET-ENGINE-THRUST", slug: "most-powerful-jet-engine-thrust", title: "Most powerful jet engine by thrust",
    category: "Engineering", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "Maximum thrust of a commercial aircraft jet engine in test", unit: "lbf",
    formalStatement: "The highest thrust recorded by a commercial aircraft turbofan engine during testing.",
    summary: "General Electric's GE9X, developed for the Boeing 777X, produced 134,300 lbf (597 kN) of thrust during a test at GE's Peebles, Ohio, facility on November 10, 2017. Guinness World Records recognised it in 2019, breaking the 127,900 lbf record set by its predecessor GE90-115B in 2002.",
    value: "134300",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Test-cell thrust measurement certified by Guinness World Records.",
    source: { title: "GE Aerospace — GE9X Breaks GUINNESS WORLD RECORDS Title for Thrust", url: "https://www.geaerospace.com/news/press-releases/commercial-engines/ge9x-breaks-guinness-world-recordstm-title-thrust", date: "2019-07-12", location: "Peebles, Ohio, USA" },
  },
  {
    registryNumber: "LR-LONGEST-FLIGHT-WITHOUT-REFUELLING", slug: "longest-flight-without-refuelling", title: "Longest aircraft flight without refuelling",
    category: "Engineering", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "Great-circle distance flown non-stop without refuelling", unit: "km",
    formalStatement: "The longest distance flown by any aircraft in one non-stop flight without refuelling.",
    summary: "Steve Fossett flew the Virgin Atlantic GlobalFlyer, a single-jet aircraft designed by Burt Rutan's Scaled Composites, 41,467 km from Kennedy Space Center, Florida, to Bournemouth, England, in February 2006. It remains the FAI absolute record for distance without landing.",
    value: "41467",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Ratified by the Fédération Aéronautique Internationale (FAI) from flight-recorder data.",
    source: { title: "FAI — Absolute records (distance without landing)", url: "https://www.fai.org/records", date: "2006-02-11", location: "Kennedy Space Center, Florida, USA – Bournemouth, UK" },
  },
  {
    registryNumber: "LR-LONGEST-SCHEDULED-COMMERCIAL-FLIGHT", slug: "longest-scheduled-commercial-flight", title: "Longest scheduled non-stop commercial flight",
    category: "Engineering", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "Great-circle distance of a scheduled passenger route", unit: "km",
    formalStatement: "The longest great-circle distance of any regularly scheduled non-stop passenger airline route.",
    summary: "Singapore Airlines flights SQ23/SQ24 between Singapore Changi and New York JFK, launched in November 2020 using Airbus A350-900ULR aircraft, cover about 15,349 km great-circle distance and take roughly 18–19 hours. Qantas's 'Project Sunrise' Sydney–London and Sydney–New York flights are planned but were not yet in service.",
    value: "15349",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Great-circle distance between airport coordinates; route data from Singapore Airlines schedules.",
    source: { title: "Singapore Airlines — Singapore–New York non-stop", url: "https://www.singaporeair.com/", date: "2020-11-09", location: "Singapore – New York, USA" },
  },
  {
    registryNumber: "LR-LARGEST-AIRSHIP-EVER-BUILT", slug: "largest-airship-ever-built", title: "Largest airship ever flown",
    category: "Engineering", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "Overall length of a rigid airship", unit: "m",
    formalStatement: "The greatest length of any airship that has flown.",
    summary: "The German Zeppelin LZ 129 Hindenburg and its sister LZ 130 Graf Zeppelin II were 245 m long, the largest aircraft ever to fly by length and volume (about 200,000 m³ of gas). Hindenburg first flew in March 1936 and was destroyed by fire at Lakehurst, New Jersey, on May 6, 1937.",
    value: "245",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Dimensions from Luftschiffbau Zeppelin construction records.",
    source: { title: "Smithsonian National Air and Space Museum — Hindenburg", url: "https://airandspace.si.edu/", date: "1936-03-04", location: "Friedrichshafen, Germany" },
  },
  {
    registryNumber: "LR-LARGEST-HOVERCRAFT", slug: "largest-hovercraft", title: "Largest hovercraft",
    category: "Engineering", subcategory: "Naval Engineering", direction: "MAXIMIZE",
    metricName: "Full-load displacement of an air-cushion vehicle", unit: "t",
    formalStatement: "The heaviest air-cushion vehicle (hovercraft) ever built.",
    summary: "The Soviet Project 1232.2 'Zubr' (NATO: Pomornik) class landing craft, introduced in 1988, is about 57 m long with a full-load displacement of roughly 555 tonnes, able to carry three main battle tanks. It is the largest hovercraft class in the world, operated by Russia and Greece.",
    value: "555",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Displacement from naval reference publications; official figures vary slightly by source.",
    source: { title: "Naval Technology — Zubr class air cushion landing craft", url: "https://www.naval-technology.com/projects/zubr/", date: "1988-01-01", location: "Russia" },
  },
  {
    registryNumber: "LR-LARGEST-HELICOPTER-EVER-BUILT", slug: "largest-helicopter-ever-built", title: "Largest helicopter ever built",
    category: "Engineering", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "Maximum take-off weight of a helicopter", unit: "kg",
    formalStatement: "The highest maximum take-off weight of any helicopter that has flown.",
    summary: "The Soviet Mil V-12 (Mi-12), a twin-rotor transverse helicopter first flown in 1968, had a maximum take-off weight of about 105,000 kg and a span of about 67 m across its rotors. In 1969 it lifted a payload of over 40 tonnes to more than 2,000 m — an FAI record still standing; only two prototypes were built.",
    value: "105000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Weight from Mil design bureau data; payload record ratified by the FAI.",
    source: { title: "FAI — Rotorcraft records", url: "https://www.fai.org/records", date: "1969-08-06", location: "Moscow region, USSR" },
  },
  {
    registryNumber: "LR-HIGHEST-ALTITUDE-HELICOPTER-FLIGHT", slug: "highest-altitude-helicopter-flight", title: "Highest altitude reached by a helicopter",
    category: "Engineering", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "Absolute altitude reached by a helicopter", unit: "m",
    formalStatement: "The highest altitude ever reached by a helicopter in flight.",
    summary: "French test pilot Jean Boulet flew an Aérospatiale SA 315B Lama to 12,442 m on June 21, 1972, at Istres, France. The record still stands; the engine flamed out at peak altitude and Boulet completed the longest-ever helicopter autorotation descent.",
    value: "12442",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Ratified by the Fédération Aéronautique Internationale (FAI).",
    source: { title: "FAI — Rotorcraft absolute altitude record", url: "https://www.fai.org/records", date: "1972-06-21", location: "Istres, France" },
  },
  {
    registryNumber: "LR-LONGEST-SOLO-SOLAR-POWERED-FLIGHT", slug: "longest-solo-solar-powered-flight", title: "Longest solar-powered crewed flight by duration",
    category: "Engineering", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "Duration of a single non-stop crewed solar-powered flight", unit: "h",
    formalStatement: "The longest duration of a single non-stop flight by a crewed solar-powered aircraft.",
    summary: "André Borschberg piloted Solar Impulse 2 from Nagoya, Japan, to Kalaeloa, Hawaii, between June 28 and July 3, 2015, flying 117 hours 52 minutes without fuel — the longest solo flight of any kind in duration. The leg was part of Solar Impulse's round-the-world journey, completed in July 2016.",
    value: "117.87",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Flight data ratified by the FAI.",
    source: { title: "Solar Impulse Foundation — Round-the-world flight", url: "https://aroundtheworld.solarimpulse.com/", date: "2015-07-03", location: "Nagoya, Japan – Hawaii, USA" },
  },
  {
    registryNumber: "LR-FIRST-SOLAR-POWERED-CIRCUMNAVIGATION", slug: "first-solar-powered-circumnavigation", title: "First round-the-world flight by a solar-powered aircraft",
    category: "Engineering", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "Distance flown on the circumnavigation using only solar energy", unit: "km",
    formalStatement: "The first circumnavigation of the Earth by a crewed aircraft powered solely by solar energy.",
    summary: "Bertrand Piccard and André Borschberg completed the first solar-powered circumnavigation in Solar Impulse 2, departing Abu Dhabi on March 9, 2015 and returning there on July 26, 2016 after 17 legs. The aircraft, with 17,248 solar cells over a 72 m wingspan, covered about 42,000 km without fuel.",
    value: "42438",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Total distance from Solar Impulse mission records; individual legs ratified by the FAI.",
    source: { title: "Solar Impulse Foundation — Round-the-world flight", url: "https://aroundtheworld.solarimpulse.com/", date: "2016-07-26", location: "Abu Dhabi, United Arab Emirates" },
  },
  {
    registryNumber: "LR-LONGEST-UNCREWED-AIRCRAFT-FLIGHT-DURATION", slug: "longest-uncrewed-aircraft-flight-duration", title: "Longest continuous flight by an uncrewed aircraft",
    category: "Engineering", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "Continuous flight duration of an uncrewed aircraft", unit: "days",
    formalStatement: "The longest continuous airborne duration of any uncrewed heavier-than-air aircraft.",
    summary: "AALTO's Zephyr, a solar-powered high-altitude platform station developed by Airbus, flew continuously in the stratosphere for 67 days, 6 hours and 52 minutes after launching from Kenya on February 20, 2025, landing on April 28, 2025. It beat Zephyr's own 2022 record of about 64 days.",
    value: "67.29",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Flight duration reported by the operator (AALTO, an Airbus subsidiary).",
    source: { title: "AALTO — Zephyr sets world record for longest continuous flight", url: "https://www.aaltohaps.com/zephyr-sets-world-record-for-longest-continuous-flight-flying-67-days-in-stratosphere/", date: "2025-04-28", location: "Kenya – Australia" },
  },
  // --- Engineering: Ships & Heavy Vehicles ---
  {
    registryNumber: "LR-LARGEST-CRUISE-SHIP-GROSS-TONNAGE", slug: "largest-cruise-ship-gross-tonnage", title: "Largest cruise ship by gross tonnage",
    category: "Engineering", subcategory: "Naval Engineering", direction: "MAXIMIZE",
    metricName: "Gross tonnage of a passenger cruise ship", unit: "GT",
    formalStatement: "The highest gross tonnage of any cruise ship in service.",
    summary: "Royal Caribbean's Icon-class ships — Icon of the Seas (January 2024), Star of the Seas (August 2025) and Legend of the Seas (2026) — measure about 248,663 GT and 365 m long, the largest cruise ships ever built. Each can carry around 7,600 passengers at maximum occupancy.",
    value: "248663",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Gross tonnage from ship registry/classification data and operator specifications; sister ships differ marginally.",
    source: { title: "Royal Caribbean — Icon of the Seas", url: "https://www.royalcaribbean.com/", date: "2024-01-27", location: "Meyer Turku shipyard, Finland" },
  },
  {
    registryNumber: "LR-LARGEST-AIRCRAFT-CARRIER", slug: "largest-aircraft-carrier", title: "Largest aircraft carrier",
    category: "Engineering", subcategory: "Naval Engineering", direction: "MAXIMIZE",
    metricName: "Full-load displacement of an aircraft carrier", unit: "long tons",
    formalStatement: "The greatest full-load displacement of any aircraft carrier (and warship) built.",
    summary: "USS Gerald R. Ford (CVN-78), commissioned on July 22, 2017 and built by Huntington Ingalls Industries in Newport News, Virginia, displaces about 100,000 long tons at full load and is 337 m long. It is the largest warship ever built.",
    value: "100000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Displacement from U.S. Navy fact files.",
    source: { title: "U.S. Navy — Aircraft Carriers fact file", url: "https://www.navy.mil/Resources/Fact-Files/Display-FactFiles/Article/2169795/aircraft-carriers-cvn/", date: "2017-07-22", location: "Newport News, Virginia, USA" },
  },
  {
    registryNumber: "LR-LARGEST-SUBMARINE", slug: "largest-submarine", title: "Largest submarine ever built",
    category: "Engineering", subcategory: "Naval Engineering", direction: "MAXIMIZE",
    metricName: "Submerged displacement of a submarine", unit: "t",
    formalStatement: "The greatest submerged displacement of any submarine class.",
    summary: "The Soviet Project 941 Akula (NATO: Typhoon) ballistic-missile submarines, the first of which entered service in 1981, displaced about 48,000 tonnes submerged and were 175 m long. Six were built at Severodvinsk; they remain the largest submarines ever constructed.",
    value: "48000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Displacement from naval reference publications.",
    source: { title: "Naval Technology — Typhoon class submarine", url: "https://www.naval-technology.com/projects/typhoon/", date: "1981-12-12", location: "Severodvinsk, Russia" },
  },
  {
    registryNumber: "LR-LARGEST-LNG-CARRIER", slug: "largest-lng-carrier", title: "Largest LNG carrier by cargo capacity",
    category: "Engineering", subcategory: "Naval Engineering", direction: "MAXIMIZE",
    metricName: "Liquefied natural gas cargo capacity", unit: "m³",
    formalStatement: "The largest cargo capacity of any liquefied natural gas carrier class.",
    summary: "Qatar's Q-Max LNG carriers, the first of which (Mozah) was delivered by Samsung Heavy Industries in 2008, have a cargo capacity of about 266,000 m³ and are 345 m long. They are the largest LNG carriers ever built; 14 were delivered for Qatar's export fleet.",
    value: "266000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Capacity from shipbuilder and operator (Nakilat) specifications.",
    source: { title: "Nakilat — Q-Max fleet", url: "https://www.nakilat.com/", date: "2008-07-11", location: "Geoje, South Korea" },
  },
  {
    registryNumber: "LR-LARGEST-BULK-CARRIER", slug: "largest-bulk-carrier", title: "Largest bulk carrier class",
    category: "Engineering", subcategory: "Naval Engineering", direction: "MAXIMIZE",
    metricName: "Deadweight tonnage of a dry bulk carrier", unit: "DWT",
    formalStatement: "The highest deadweight tonnage of any dry bulk carrier class in service.",
    summary: "The Valemax very large ore carriers, commissioned by Brazilian miner Vale from 2011, carry about 400,000 deadweight tonnes of iron ore and are 360 m long. They are the largest bulk carriers ever built, with dozens in service on Brazil–Asia routes.",
    value: "400000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Deadweight from Vale and classification society data.",
    source: { title: "Vale — Valemax ships", url: "https://vale.com/", date: "2011-05-01", location: "Brazil–Asia ore routes" },
  },
  {
    registryNumber: "LR-LARGEST-ICEBREAKER", slug: "largest-icebreaker", title: "Largest icebreaker",
    category: "Engineering", subcategory: "Naval Engineering", direction: "MAXIMIZE",
    metricName: "Full-load displacement of an icebreaker", unit: "t",
    formalStatement: "The greatest displacement of any icebreaker in service.",
    summary: "Russia's nuclear-powered Arktika, lead ship of Project 22220, commissioned in October 2020, displaces about 33,500 tonnes and is 173 m long, with 60 MW of propulsion power from two RITM-200 reactors. The Project 22220 ships are the largest and most powerful icebreakers in service.",
    value: "33500",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Displacement from Rosatom/Atomflot specifications; reported figures vary slightly.",
    source: { title: "Rosatom — Arktika nuclear icebreaker", url: "https://rosatom.ru/en/", date: "2020-10-21", location: "Saint Petersburg, Russia" },
  },
  {
    registryNumber: "LR-LARGEST-DIESEL-ENGINE", slug: "largest-diesel-engine", title: "Most powerful diesel engine",
    category: "Engineering", subcategory: "Machines", direction: "MAXIMIZE",
    metricName: "Rated continuous power output of a single reciprocating diesel engine", unit: "kW",
    formalStatement: "The highest rated output of any reciprocating internal-combustion diesel engine.",
    summary: "The 14-cylinder Wärtsilä-Sulzer RT-flex96C two-stroke marine diesel engine, first entering service in 2006 aboard the container ship Emma Mærsk, produces about 80,080 kW (107,390 hp). Standing 13.5 m tall and weighing about 2,300 tonnes, it is the largest and most powerful diesel engine built.",
    value: "80080",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Rated output from Wärtsilä engine specifications.",
    source: { title: "Wärtsilä — RT-flex96C engine", url: "https://www.wartsila.com/", date: "2006-09-01", location: "Winterthur, Switzerland" },
  },
  {
    registryNumber: "LR-LARGEST-DUMP-TRUCK", slug: "largest-dump-truck", title: "Largest haul truck by payload",
    category: "Engineering", subcategory: "Heavy Vehicles", direction: "MAXIMIZE",
    metricName: "Rated payload capacity of a dump truck", unit: "t",
    formalStatement: "The highest rated payload of any mining haul (dump) truck.",
    summary: "The Belarusian BelAZ 75710, unveiled in 2013, has a rated payload of 450 tonnes, driven by two diesel engines and electric drive on eight wheels. In 2014 it set a Guinness World Record by carrying 503.5 tonnes at a test site.",
    value: "450",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Rated payload from BelAZ specifications; test load certified by Guinness World Records.",
    source: { title: "BelAZ — 75710 haul truck", url: "https://belaz.by/en/", date: "2013-09-23", location: "Zhodino, Belarus" },
  },
  {
    registryNumber: "LR-HEAVIEST-LAND-VEHICLE-BAGGER-293", slug: "heaviest-land-vehicle-bagger-293", title: "Heaviest land vehicle",
    category: "Engineering", subcategory: "Heavy Vehicles", direction: "MAXIMIZE",
    metricName: "Operating mass of a self-propelled land vehicle", unit: "t",
    formalStatement: "The heaviest self-propelled land vehicle ever built.",
    summary: "Bagger 293, a bucket-wheel excavator built by TAKRAF and completed in 1995 for the Hambach open-pit lignite mine in Germany, weighs about 14,200 tonnes and is 225 m long and 96 m tall. It is recognised by Guinness World Records as the heaviest land vehicle, moving 240,000 m³ of overburden per day.",
    value: "14200",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Mass from manufacturer (TAKRAF) data; Guinness World Records certification.",
    source: { title: "Guinness World Records — Heaviest land vehicle", url: "https://www.guinnessworldrecords.com/world-records/heaviest-land-vehicle", date: "1995-01-01", location: "Hambach mine, North Rhine-Westphalia, Germany" },
  },
  // --- Energy: Generation & Efficiency ---
  {
    registryNumber: "LR-LARGEST-SINGLE-SITE-SOLAR-PV-PLANT", slug: "largest-single-site-solar-pv-plant", title: "Largest single-site solar photovoltaic plant",
    category: "Energy", subcategory: "Solar Power", direction: "MAXIMIZE",
    metricName: "Installed PV capacity at a single site", unit: "GW",
    formalStatement: "The highest installed photovoltaic capacity at a single contiguous solar power station.",
    summary: "The Midong solar plant near Ürümqi in Xinjiang, China, operated by a subsidiary of China Green Electricity Investment of Tianjin, connected 3.5 GW of capacity in June 2024 using about 5.26 million bifacial modules over roughly 13,000 hectares. It was the largest single solar PV plant in the world as of its completion; rapid Chinese build-out means larger sites may follow.",
    value: "3.5",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Capacity reported by the operator and trade press; site boundaries are defined differently across projects.",
    source: { title: "POWER Magazine — Solar by the Numbers: Midong Is China's Latest Mega-Marvel", url: "https://www.powermag.com/solar-by-the-numbers-midong-is-chinas-latest-mega-marvel/", date: "2024-06-03", location: "Ürümqi, Xinjiang, China" },
  },
  {
    registryNumber: "LR-HIGHEST-EFFICIENCY-SILICON-SOLAR-CELL", slug: "highest-efficiency-silicon-solar-cell", title: "Highest-efficiency single-junction silicon solar cell",
    category: "Energy", subcategory: "Photovoltaics", direction: "MAXIMIZE",
    metricName: "Certified power-conversion efficiency of a single-junction crystalline-silicon cell", unit: "%",
    formalStatement: "The highest independently certified efficiency of a single-junction crystalline-silicon solar cell under standard one-sun test conditions.",
    summary: "LONGi Green Energy reported a 27.81% efficiency for a commercial-size hybrid interdigitated-back-contact (HIBC) silicon cell in April 2025, certified by ISFH in Germany. This approaches the ~29.4% theoretical limit for single-junction silicon cells.",
    value: "27.81",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Efficiency certified by the Institute for Solar Energy Research Hamelin (ISFH) under standard test conditions.",
    source: { title: "LONGi — Dual World Records in Solar Cell Efficiency for HIBC and Tandem", url: "https://www.longi.com/eu/news/dual-world-record-hibc-tandem/", date: "2025-04-01", location: "Xi'an, China" },
  },
  {
    registryNumber: "LR-HIGHEST-EFFICIENCY-PEROVSKITE-SILICON-TANDEM", slug: "highest-efficiency-perovskite-silicon-tandem", title: "Highest-efficiency perovskite–silicon tandem solar cell",
    category: "Energy", subcategory: "Photovoltaics", direction: "MAXIMIZE",
    metricName: "Certified efficiency of a two-terminal perovskite-on-silicon tandem cell", unit: "%",
    formalStatement: "The highest independently certified efficiency of a perovskite–crystalline-silicon tandem solar cell under one-sun illumination.",
    summary: "LONGi announced a 34.85% efficient two-terminal perovskite–silicon tandem cell in April 2025, certified by the U.S. National Renewable Energy Laboratory (NREL). It is the highest efficiency reported for any non-concentrator two-junction silicon-based cell; the field moves quickly.",
    value: "34.85",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Efficiency certified by NREL and listed on its Best Research-Cell Efficiency chart.",
    source: { title: "pv magazine — Longi achieves 34.85% efficiency for tandem perovskite cell", url: "https://www.pv-magazine.com/2025/04/18/longi-achieves-34-85-efficiency-for-two-terminal-tandem-perovskite-solar-cell/", date: "2025-04-18", location: "Xi'an, China" },
  },
  {
    registryNumber: "LR-MOST-EFFICIENT-COMBINED-CYCLE-POWER-PLANT", slug: "most-efficient-combined-cycle-power-plant", title: "Most efficient combined-cycle power plant",
    category: "Energy", subcategory: "Fossil Fuel Power", direction: "MAXIMIZE",
    metricName: "Gross thermal efficiency of a combined-cycle gas turbine power block", unit: "%",
    formalStatement: "The highest certified gross electrical efficiency of a combined-cycle (gas plus steam turbine) power plant.",
    summary: "Chubu Electric's Nishi-Nagoya Thermal Power Station Block 1 in Aichi, Japan, using GE 9HA gas turbines, achieved 63.08% gross efficiency and was recognised by Guinness World Records in 2018. It beat the 62.22% set by EDF's Bouchain plant in France in 2016.",
    value: "63.08",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Gross efficiency measured in performance testing; Guinness World Records certification.",
    source: { title: "POWER Magazine — GE HA turbine snags another world record for CCGT efficiency", url: "https://www.powermag.com/ge-ha-turbine-snags-another-world-record-for-ccgt-efficiency/", date: "2018-03-27", location: "Tobishima, Aichi, Japan" },
  },
  {
    registryNumber: "LR-MOST-POWERFUL-GAS-TURBINE", slug: "most-powerful-gas-turbine", title: "Most powerful gas turbine",
    category: "Energy", subcategory: "Fossil Fuel Power", direction: "MAXIMIZE",
    metricName: "Simple-cycle rated output of a single heavy-duty gas turbine", unit: "MW",
    formalStatement: "The highest simple-cycle rated electrical output of a single gas turbine model.",
    summary: "Siemens Energy's SGT5-9000HL heavy-duty gas turbine is rated at 593 MW in simple-cycle operation and about 880 MW in a combined-cycle configuration, with over 64% combined-cycle efficiency. It is the highest-rated gas turbine on the market, ahead of GE's 9HA.02 at about 571 MW.",
    value: "593",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Manufacturer-rated output (ISO conditions) published by Siemens Energy.",
    source: { title: "Siemens Energy — SGT5-9000HL", url: "https://www.siemens-energy.com/global/en/home/products-services/product/sgt5-9000hl.html", date: "2019-01-01", location: "Berlin, Germany" },
  },
  {
    registryNumber: "LR-HIGHEST-HEAD-HYDROELECTRIC-PLANT", slug: "highest-head-hydroelectric-plant", title: "Highest-head hydroelectric power plant",
    category: "Energy", subcategory: "Hydroelectric Power", direction: "MAXIMIZE",
    metricName: "Gross hydraulic head of a hydroelectric power station", unit: "m",
    formalStatement: "The greatest height difference (head) between reservoir and turbines of any hydroelectric power plant.",
    summary: "The Bieudron hydroelectric plant in Valais, Switzerland, part of the Cleuson-Dixence scheme and commissioned in 1998, uses a head of 1,883 m from the Grande Dixence reservoir. Its three Pelton turbines of 423 MW each set Guinness World Records for head and Pelton output.",
    value: "1883",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Head from the operator (Grande Dixence SA / Alpiq) and Guinness World Records certification.",
    source: { title: "Grande Dixence SA — Cleuson-Dixence scheme", url: "https://www.grande-dixence.ch/", date: "1998-12-01", location: "Valais, Switzerland" },
  },
  {
    registryNumber: "LR-TALLEST-SOLAR-POWER-TOWER", slug: "tallest-solar-power-tower", title: "Tallest concentrated solar power tower",
    category: "Energy", subcategory: "Solar Power", direction: "MAXIMIZE",
    metricName: "Height of a CSP central-receiver tower", unit: "m",
    formalStatement: "The tallest central-receiver tower built for a concentrated solar power plant.",
    summary: "The 100 MW solar tower of Noor Energy 1, part of the Mohammed bin Rashid Al Maktoum Solar Park in Dubai, reaches 263.126 m, certified by Guinness World Records on May 29, 2023. About 70,000 heliostats focus sunlight on its receiver.",
    value: "263.126",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Height certified by Guinness World Records.",
    source: { title: "Guinness World Records — Tallest concentrated solar power tower", url: "https://www.guinnessworldrecords.com/world-records/620817-tallest-solar-power-tower", date: "2023-05-29", location: "Dubai, United Arab Emirates" },
  },
  // --- Energy: Grid & Transmission ---
  {
    registryNumber: "LR-TALLEST-ELECTRICITY-PYLONS", slug: "tallest-electricity-pylons", title: "Tallest electricity transmission towers",
    category: "Energy", subcategory: "Electrical Transmission", direction: "MAXIMIZE",
    metricName: "Height of an overhead-line transmission tower", unit: "m",
    formalStatement: "The tallest lattice towers built to carry overhead electricity transmission lines.",
    summary: "Two 385 m transmission towers carrying a 500 kV line across the Yangtze River at Jiangyin, Jiangsu, China, completed in 2022, are the tallest electricity pylons in the world. They surpassed the 380 m towers of the Zhoushan island crossing in Zhejiang (2019).",
    value: "385",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Tower heights reported by State Grid Corporation of China.",
    source: { title: "Transformer Magazine — World's tallest power transmission towers wired across Yangtze River", url: "https://transformer-magazine.com/news/worlds-tallest-power-transmission-towers-wired-across-yangtze-river/", date: "2022-05-20", location: "Jiangyin, Jiangsu, China" },
  },
  {
    registryNumber: "LR-LONGEST-OVERHEAD-POWER-LINE-SPAN", slug: "longest-overhead-power-line-span", title: "Longest overhead power line span",
    category: "Energy", subcategory: "Electrical Transmission", direction: "MAXIMIZE",
    metricName: "Distance between two consecutive supports of an overhead power line", unit: "m",
    formalStatement: "The longest span of conductor between two adjacent supporting structures on any overhead electricity line.",
    summary: "The Ameralik Span in Greenland, part of a 132 kV line from the Buksefjord hydroelectric plant to Nuuk completed in 1993, crosses the Ameralik fjord with a single span of 5,376 m. It is the longest overhead power line span in the world.",
    value: "5376",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Span length from the Greenlandic utility Nukissiorfiit and engineering literature.",
    source: { title: "Nukissiorfiit — Buksefjord hydropower", url: "https://www.nukissiorfiit.gl/", date: "1993-01-01", location: "Ameralik fjord, Greenland" },
  },
  {
    registryNumber: "LR-HIGHEST-VOLTAGE-AC-TRANSMISSION-LINE", slug: "highest-voltage-ac-transmission-line", title: "Highest-voltage AC transmission line",
    category: "Energy", subcategory: "Electrical Transmission", direction: "MAXIMIZE",
    metricName: "Operating line voltage of an alternating-current transmission line", unit: "kV",
    formalStatement: "The highest alternating-current voltage at which a commercial transmission line has been operated.",
    summary: "The Soviet Ekibastuz–Kokshetau line in Kazakhstan was operated at 1,150 kV AC from 1985, the highest AC transmission voltage ever used commercially; it was later downrated to 500 kV. China's 1,000 kV UHV AC network is the highest-voltage AC system in operation today. (Distinct from DC lines such as China's ±1,100 kV Changji–Guquan link.)",
    value: "1150",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Operating voltage reported by the line's operator (KEGOC) and CIGRE literature.",
    source: { title: "KEGOC — Kazakhstan national grid", url: "https://www.kegoc.kz/en/", date: "1985-08-01", location: "Ekibastuz–Kokshetau, Kazakhstan" },
  },
  // --- Energy: Nuclear & Fusion ---
  {
    registryNumber: "LR-LONGEST-TOKAMAK-PLASMA-DURATION", slug: "longest-tokamak-plasma-duration", title: "Longest tokamak plasma duration",
    category: "Energy", subcategory: "Nuclear Fusion", direction: "MAXIMIZE",
    metricName: "Duration of a single sustained tokamak plasma discharge", unit: "s",
    formalStatement: "The longest continuous plasma discharge sustained in a tokamak fusion device.",
    summary: "On February 12, 2025, the CEA's WEST tokamak at Cadarache, France, sustained a hydrogen plasma for 1,337 seconds (about 22 minutes) with 2.6 GJ of injected energy. It beat the 1,066-second H-mode record set weeks earlier by China's EAST tokamak.",
    value: "1337",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Discharge duration reported by CEA-IRFM from machine diagnostics.",
    source: { title: "CEA-IRFM — WEST sets a new plasma duration record", url: "https://irfm.cea.fr/en/2025/02/west-sets-a-new-plasma-duration-record/", date: "2025-02-12", location: "Cadarache, France" },
  },
  {
    registryNumber: "LR-HIGHEST-FUSION-ENERGY-SINGLE-PULSE", slug: "highest-fusion-energy-single-pulse", title: "Most fusion energy released in a single magnetic-confinement pulse",
    category: "Energy", subcategory: "Nuclear Fusion", direction: "MAXIMIZE",
    metricName: "Fusion energy released in one tokamak plasma pulse", unit: "MJ",
    formalStatement: "The greatest total fusion energy produced in a single plasma pulse by a magnetic-confinement device.",
    summary: "The Joint European Torus (JET) at Culham, UK, produced 69 MJ of fusion energy from about 0.2 mg of deuterium–tritium fuel in a 5-second pulse during its final DT campaign in October 2023, announced in February 2024. JET was shut down at the end of 2023 after 40 years of operation.",
    value: "69",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Neutron-yield measurements by the EUROfusion consortium and UKAEA.",
    source: { title: "UKAEA — JET's final tritium experiments yield new fusion energy record", url: "https://www.gov.uk/government/news/jets-final-tritium-experiments-yield-new-fusion-energy-record", date: "2024-02-08", location: "Culham, Oxfordshire, UK" },
  },
  {
    registryNumber: "LR-LARGEST-TOKAMAK-UNDER-CONSTRUCTION-ITER", slug: "largest-tokamak-under-construction-iter", title: "Largest tokamak ever built (plasma volume)",
    category: "Energy", subcategory: "Nuclear Fusion", direction: "MAXIMIZE",
    metricName: "Design plasma volume of a tokamak", unit: "m³",
    formalStatement: "The largest design plasma volume of any tokamak built or under construction.",
    summary: "ITER, under construction at Saint-Paul-lez-Durance in southern France by a 35-nation collaboration, is designed for a plasma volume of about 840 m³ — ten times larger than any previous tokamak — aiming at 500 MW of fusion power from 50 MW of heating (Q = 10). Its first plasma is scheduled for the 2030s.",
    value: "840",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Design parameter from the ITER Organization; machine is not yet operating.",
    source: { title: "ITER Organization — Facts & Figures", url: "https://www.iter.org/", date: "2025-01-01", location: "Saint-Paul-lez-Durance, France" },
  },
  {
    registryNumber: "LR-LARGEST-STELLARATOR", slug: "largest-stellarator", title: "Largest stellarator fusion device",
    category: "Energy", subcategory: "Nuclear Fusion", direction: "MAXIMIZE",
    metricName: "Plasma volume of a stellarator", unit: "m³",
    formalStatement: "The largest plasma volume of any operating stellarator-type fusion experiment.",
    summary: "Wendelstein 7-X at the Max Planck Institute for Plasma Physics in Greifswald, Germany, which produced its first plasma in December 2015, confines about 30 m³ of plasma using 50 non-planar superconducting coils. It is the world's largest stellarator.",
    value: "30",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Design parameters from the Max Planck Institute for Plasma Physics.",
    source: { title: "Max Planck Institute for Plasma Physics — Wendelstein 7-X", url: "https://www.ipp.mpg.de/w7x", date: "2015-12-10", location: "Greifswald, Germany" },
  },
  {
    registryNumber: "LR-LARGEST-NUCLEAR-POWER-STATION-CAPACITY", slug: "largest-nuclear-power-station-capacity", title: "Largest nuclear power station by installed capacity",
    category: "Energy", subcategory: "Nuclear Power", direction: "MAXIMIZE",
    metricName: "Total net installed capacity of a single nuclear power station", unit: "MW",
    formalStatement: "The largest total installed net electrical capacity of reactors at a single nuclear power station site.",
    summary: "Kashiwazaki-Kariwa in Niigata Prefecture, Japan, operated by TEPCO, has seven boiling-water reactors with a combined net capacity of about 7,965 MW (8,212 MW gross), the largest of any nuclear plant. Its units were idled after the 2011 Fukushima accident; Canada's Bruce station is the largest by capacity in continuous operation.",
    value: "7965",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Capacity from the IAEA Power Reactor Information System (PRIS); operational status varies.",
    source: { title: "IAEA PRIS — Power Reactor Information System", url: "https://pris.iaea.org/pris/", date: "1997-07-02", location: "Kashiwazaki and Kariwa, Niigata, Japan" },
  },
  // --- Energy: Oil & Gas ---
  {
    registryNumber: "LR-LARGEST-OIL-REFINERY-COMPLEX", slug: "largest-oil-refinery-complex", title: "Largest oil refinery complex",
    category: "Energy", subcategory: "Oil & Gas", direction: "MAXIMIZE",
    metricName: "Crude processing capacity of a single refinery complex", unit: "barrels/day",
    formalStatement: "The largest crude-oil processing capacity of any refinery complex at a single site.",
    summary: "Reliance Industries' Jamnagar refinery complex in Gujarat, India, opened in 1999 and expanded in 2008, can process about 1.4 million barrels of crude per day across two adjacent refineries. It is the largest refining complex in the world.",
    value: "1400000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Capacity from Reliance Industries corporate disclosures; capacity definitions vary.",
    source: { title: "Reliance Industries — Jamnagar", url: "https://www.ril.com/", date: "2008-12-25", location: "Jamnagar, Gujarat, India" },
  },
  {
    registryNumber: "LR-DEEPEST-OFFSHORE-OIL-PRODUCTION", slug: "deepest-offshore-oil-production", title: "Deepest offshore oil and gas production facility",
    category: "Energy", subcategory: "Oil & Gas", direction: "MAXIMIZE",
    metricName: "Water depth of a producing offshore oil and gas facility", unit: "m",
    formalStatement: "The greatest water depth at which an offshore oil and gas production facility operates.",
    summary: "Shell's Stones development in the U.S. Gulf of Mexico began production in September 2016 in about 2,900 m (9,500 ft) of water, using the Turritella floating production, storage and offloading (FPSO) vessel. It is the deepest offshore oil and gas production project in the world.",
    value: "2900",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Water depth reported by Shell.",
    source: { title: "Shell — Stones deepwater project", url: "https://www.shell.com/", date: "2016-09-08", location: "Gulf of Mexico, USA" },
  },
  // --- Materials Science ---
  {
    registryNumber: "LR-HIGHEST-MELTING-POINT-COMPOUND", slug: "highest-melting-point-compound", title: "Highest melting point of any compound",
    category: "Materials Science", subcategory: "Refractory Materials", direction: "MAXIMIZE",
    metricName: "Measured melting temperature of a compound", unit: "°C",
    formalStatement: "The highest experimentally measured melting point of any chemical compound.",
    summary: "Laser-heating experiments by Imperial College London researchers, published in Scientific Reports in 2016, measured hafnium carbide (HfC) melting at about 3,958 °C — the highest melting point measured for any compound. Simulations suggest hafnium carbonitride could melt above 4,000 °C.",
    value: "3958",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Laser-heating with pyrometric temperature measurement; published by Cedillos-Barraza et al.",
    source: { title: "Scientific Reports — Investigating the highest melting temperature materials", url: "https://www.nature.com/articles/srep37962", date: "2016-11-29", location: "Imperial College London, UK" },
  },
  {
    registryNumber: "LR-STRONGEST-BIOLOGICAL-MATERIAL-LIMPET-TEETH", slug: "strongest-biological-material-limpet-teeth", title: "Strongest known biological material",
    category: "Materials Science", subcategory: "Biomaterials", direction: "MAXIMIZE",
    metricName: "Tensile strength of a natural biological material", unit: "GPa",
    formalStatement: "The highest measured tensile strength of any naturally produced biological material.",
    summary: "Researchers at the University of Portsmouth measured the teeth of the common limpet (Patella vulgata), made of goethite nanofibres in a protein matrix, at tensile strengths up to about 4.9 GPa. Published in 2015, the result exceeds spider silk, the previous record holder among biological materials.",
    value: "4.9",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Atomic-force-microscope tensile tests on micro-machined samples; Barber et al.",
    source: { title: "Journal of the Royal Society Interface — Extreme strength observed in limpet teeth", url: "https://royalsocietypublishing.org/doi/10.1098/rsif.2014.1326", date: "2015-02-18", location: "University of Portsmouth, UK" },
  },
  {
    registryNumber: "LR-TOUGHEST-SPIDER-SILK", slug: "toughest-spider-silk", title: "Toughest spider silk",
    category: "Materials Science", subcategory: "Biomaterials", direction: "MAXIMIZE",
    metricName: "Toughness (energy to fracture per volume) of spider dragline silk", unit: "MJ/m³",
    formalStatement: "The highest toughness measured for any spider silk.",
    summary: "Dragline silk from Darwin's bark spider (Caerostris darwini) of Madagascar has an average toughness of about 350 MJ/m³, with samples up to about 520 MJ/m³, according to Agnarsson and colleagues in 2010. It is the toughest biological material known — about ten times tougher than Kevlar.",
    value: "350",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Tensile testing of individual silk fibres; Agnarsson et al., PLoS ONE.",
    source: { title: "PLoS ONE — Bioprospecting finds the toughest biological material", url: "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0011234", date: "2010-09-16", location: "Madagascar / University of Puerto Rico" },
  },
  {
    registryNumber: "LR-HIGHEST-FRACTURE-TOUGHNESS-ANY-MATERIAL", slug: "highest-fracture-toughness-any-material", title: "Highest fracture toughness of any material",
    category: "Materials Science", subcategory: "Mechanical Properties", direction: "MAXIMIZE",
    metricName: "Crack-initiation fracture toughness", unit: "MPa·m^½",
    formalStatement: "The highest fracture toughness measured for any material.",
    summary: "Lawrence Berkeley and Oak Ridge National Laboratory researchers reported in Science in December 2022 that the CrCoNi medium-entropy alloy reaches crack-initiation toughness of up to 500 MPa·m½ at 20 K (−253 °C) — the highest fracture toughness ever recorded. Its toughness increases as it gets colder, unlike most metals.",
    value: "500",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "J-integral fracture testing at cryogenic temperatures; Liu et al.",
    source: { title: "Science — Exceptional fracture toughness of CrCoNi-based medium- and high-entropy alloys at 20 kelvin", url: "https://www.science.org/doi/10.1126/science.abp8070", date: "2022-12-01", location: "Lawrence Berkeley National Laboratory, California, USA" },
  },
  {
    registryNumber: "LR-HIGHEST-THERMAL-CONDUCTIVITY-NON-CARBON-CRYSTAL", slug: "highest-thermal-conductivity-non-carbon-crystal", title: "Highest thermal conductivity of a non-carbon bulk crystal",
    category: "Materials Science", subcategory: "Thermal Materials", direction: "MAXIMIZE",
    metricName: "Room-temperature thermal conductivity", unit: "W/(m·K)",
    formalStatement: "The highest room-temperature thermal conductivity measured in a bulk crystal not made of carbon.",
    summary: "Isotope-enriched cubic boron nitride crystals were measured at about 1,600 W/(m·K) at room temperature by Chen and colleagues in Science in 2020, second only to diamond among bulk materials. Isotope purification increased its conductivity by about 80%.",
    value: "1600",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Time-domain thermoreflectance measurements; Chen et al.",
    source: { title: "Science — Ultrahigh thermal conductivity in isotope-enriched cubic boron nitride", url: "https://www.science.org/doi/10.1126/science.aaz6149", date: "2020-01-31", location: "University of Texas at Dallas / USA" },
  },
  {
    registryNumber: "LR-HIGHEST-SATURATION-MAGNETIZATION-ALLOY", slug: "highest-saturation-magnetization-alloy", title: "Highest saturation magnetisation of a bulk alloy",
    category: "Materials Science", subcategory: "Magnetic Materials", direction: "MAXIMIZE",
    metricName: "Saturation magnetic flux density at room temperature", unit: "T",
    formalStatement: "The highest room-temperature saturation magnetic polarisation of any bulk material.",
    summary: "Iron–cobalt alloys near Fe65Co35 have a saturation polarisation of about 2.45 T, the peak of the Slater–Pauling curve and the highest of any bulk material at room temperature. Commercial alloys such as Hiperco and Permendur are used in aircraft generators and high-flux electromagnets.",
    value: "2.45",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Magnetometry of bulk alloys; standard magnetic-materials references.",
    source: { title: "ASM International — Magnetic properties of iron–cobalt alloys", url: "https://www.asminternational.org/", date: "1929-01-01", location: "Various" },
  },
  {
    registryNumber: "LR-HIGHEST-CURIE-TEMPERATURE", slug: "highest-curie-temperature", title: "Highest Curie temperature of any element",
    category: "Materials Science", subcategory: "Magnetic Materials", direction: "MAXIMIZE",
    metricName: "Ferromagnetic Curie temperature", unit: "K",
    formalStatement: "The highest temperature at which an element remains ferromagnetic.",
    summary: "Cobalt remains ferromagnetic up to its Curie temperature of about 1,388 K (1,115 °C), the highest of any element — well above iron (1,043 K) and nickel (627 K). This makes cobalt-based permanent magnets suitable for high-temperature applications.",
    value: "1388",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Standard reference data (CRC Handbook of Chemistry and Physics).",
    source: { title: "CRC Handbook of Chemistry and Physics — Magnetic properties", url: "https://hbcp.chemnetbase.com/", date: "1950-01-01", location: "Reference data" },
  },
  {
    registryNumber: "LR-LARGEST-ROOM-TEMPERATURE-MAGNETOSTRICTION", slug: "largest-room-temperature-magnetostriction", title: "Largest room-temperature magnetostriction",
    category: "Materials Science", subcategory: "Magnetic Materials", direction: "MAXIMIZE",
    metricName: "Saturation magnetostrictive strain", unit: "ppm",
    formalStatement: "The largest strain produced by an applied magnetic field in a material at room temperature (excluding magnetic shape-memory alloys).",
    summary: "Terfenol-D, a terbium–dysprosium–iron alloy (Tb0.3Dy0.7Fe2) developed at the U.S. Naval Ordnance Laboratory in the 1970s, shows saturation magnetostriction of about 2,000 ppm at room temperature — the largest of any conventional magnetostrictive material. It is used in sonar transducers and actuators.",
    value: "2000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Strain-gauge magnetostriction measurements; standard references.",
    source: { title: "U.S. Naval Research Laboratory — Terfenol-D", url: "https://www.nrl.navy.mil/", date: "1972-01-01", location: "Naval Ordnance Laboratory, Maryland, USA" },
  },
  {
    registryNumber: "LR-LOWEST-THERMAL-EXPANSION-METAL-ALLOY-INVAR", slug: "lowest-thermal-expansion-metal-alloy-invar", title: "Lowest thermal expansion of a metallic alloy (Invar)",
    category: "Materials Science", subcategory: "Thermal Materials", direction: "MINIMIZE",
    metricName: "Room-temperature linear coefficient of thermal expansion", unit: "10⁻⁶/K",
    formalStatement: "The lowest room-temperature thermal expansion coefficient of a widely used metallic alloy.",
    summary: "Invar, an iron–36% nickel alloy discovered by Charles-Édouard Guillaume in 1896, has a linear thermal expansion coefficient of about 1.2 × 10⁻⁶/K near room temperature — roughly a tenth that of ordinary steel. Guillaume received the 1920 Nobel Prize in Physics for the discovery.",
    value: "1.2",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Dilatometry; Nobel Prize citation and standard materials references.",
    source: { title: "NobelPrize.org — Charles Édouard Guillaume, Nobel Prize in Physics 1920", url: "https://www.nobelprize.org/prizes/physics/1920/guillaume/facts/", date: "1896-01-01", location: "Bureau International des Poids et Mesures, Sèvres, France" },
  },
  {
    registryNumber: "LR-LARGEST-ISOTROPIC-NEGATIVE-THERMAL-EXPANSION", slug: "largest-isotropic-negative-thermal-expansion", title: "Strongest isotropic negative thermal expansion over a wide range",
    category: "Materials Science", subcategory: "Thermal Materials", direction: "MAXIMIZE",
    metricName: "Magnitude of negative linear thermal expansion coefficient", unit: "10⁻⁶/K",
    formalStatement: "The largest isotropic negative thermal expansion coefficient sustained over a wide temperature range.",
    summary: "Zirconium tungstate (ZrW2O8) contracts isotropically when heated, with a linear expansion coefficient of about −8.7 × 10⁻⁶/K, over a range from near absolute zero to about 1,050 K. Reported by Mary and colleagues at Oregon State University in Science in 1996.",
    value: "8.7",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Neutron and X-ray diffraction of lattice parameters versus temperature; Mary et al.",
    source: { title: "Science — Negative thermal expansion from 0.3 to 1050 Kelvin in ZrW2O8", url: "https://www.science.org/doi/10.1126/science.272.5258.90", date: "1996-04-05", location: "Oregon State University, Oregon, USA" },
  },
  {
    registryNumber: "LR-BLACKEST-MATERIAL", slug: "blackest-material", title: "Blackest material ever made",
    category: "Materials Science", subcategory: "Optical Materials", direction: "MAXIMIZE",
    metricName: "Fraction of incident visible light absorbed", unit: "%",
    formalStatement: "The highest fraction of incident visible light absorbed by a man-made material.",
    summary: "MIT engineers led by Brian Wardle reported in 2019 a coating of vertically aligned carbon nanotubes grown on chlorine-etched aluminium foil that absorbs more than 99.995% of incoming light. It is ten times blacker than any previously reported material, including Vantablack.",
    value: "99.995",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Reflectance spectroscopy reported by Cui, Wardle et al., ACS Applied Materials & Interfaces.",
    source: { title: "MIT News — MIT engineers develop 'blackest black' material to date", url: "https://news.mit.edu/2019/blackest-black-material-cnt-0913", date: "2019-09-12", location: "MIT, Cambridge, Massachusetts, USA" },
  },
  {
    registryNumber: "LR-WHITEST-PAINT", slug: "whitest-paint", title: "Whitest paint",
    category: "Materials Science", subcategory: "Optical Materials", direction: "MAXIMIZE",
    metricName: "Solar reflectance of a paint", unit: "%",
    formalStatement: "The highest solar reflectance achieved by a paint.",
    summary: "Purdue University engineers led by Xiulin Ruan developed an ultra-white barium sulfate paint that reflects about 98.1% of sunlight, reported in 2021 and recognised by Guinness World Records. It can cool surfaces below ambient temperature in direct sunlight without power.",
    value: "98.1",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Spectral reflectance measurement; Guinness World Records certification.",
    source: { title: "Purdue University — The whitest paint is here", url: "https://www.purdue.edu/newsroom/releases/2021/Q2/the-whitest-paint-is-here-and-its-the-coolest.-literally..html", date: "2021-04-15", location: "Purdue University, Indiana, USA" },
  },
  {
    registryNumber: "LR-HIGHEST-ELECTRON-MOBILITY-2DEG", slug: "highest-electron-mobility-2deg", title: "Highest electron mobility in a semiconductor",
    category: "Materials Science", subcategory: "Electronic Materials", direction: "MAXIMIZE",
    metricName: "Low-temperature electron mobility in a two-dimensional electron gas", unit: "cm²/(V·s)",
    formalStatement: "The highest electron mobility ever measured in any semiconductor structure.",
    summary: "Princeton University researchers led by Loren Pfeiffer reported in 2021 GaAs/AlGaAs quantum wells grown by ultra-pure molecular beam epitaxy with a low-temperature electron mobility of about 57 million cm²/(V·s). It is the highest mobility measured in any semiconductor.",
    value: "57000000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Low-temperature transport measurements; Chung et al., Nature Materials.",
    source: { title: "Nature Materials — Ultra-high-quality two-dimensional electron systems", url: "https://www.nature.com/articles/s41563-021-01018-8", date: "2021-05-20", location: "Princeton University, New Jersey, USA" },
  },
  {
    registryNumber: "LR-HIGHEST-ROOM-TEMPERATURE-ELECTRON-MOBILITY-BULK", slug: "highest-room-temperature-electron-mobility-bulk", title: "Highest room-temperature electron mobility in a bulk semiconductor",
    category: "Materials Science", subcategory: "Electronic Materials", direction: "MAXIMIZE",
    metricName: "Room-temperature electron mobility in a bulk crystal", unit: "cm²/(V·s)",
    formalStatement: "The highest room-temperature electron mobility of any common bulk inorganic semiconductor.",
    summary: "Indium antimonide (InSb), a narrow-bandgap III–V semiconductor, has a room-temperature electron mobility of about 77,000 cm²/(V·s) — around 50 times that of silicon. It is used in infrared detectors and Hall-effect sensors.",
    value: "77000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Standard semiconductor reference data (Ioffe Institute database).",
    source: { title: "Ioffe Institute — InSb electrical properties", url: "https://www.ioffe.ru/SVA/NSM/Semicond/InSb/electric.html", date: "1960-01-01", location: "Reference data" },
  },
  {
    registryNumber: "LR-HIGHEST-TC-ELEMENTAL-SUPERCONDUCTOR-AMBIENT", slug: "highest-tc-elemental-superconductor-ambient", title: "Highest superconducting critical temperature of an element at ambient pressure",
    category: "Materials Science", subcategory: "Superconductors", direction: "MAXIMIZE",
    metricName: "Superconducting transition temperature", unit: "K",
    formalStatement: "The highest superconducting critical temperature of any pure element at ambient pressure.",
    summary: "Niobium becomes superconducting at about 9.25 K, the highest critical temperature of any element at ordinary pressure. Its alloys, such as niobium–titanium and niobium–tin, are used in MRI magnets and the LHC's superconducting magnets.",
    value: "9.25",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Standard reference data from resistivity and magnetic susceptibility measurements.",
    source: { title: "CRC Handbook of Chemistry and Physics — Superconductivity data", url: "https://hbcp.chemnetbase.com/", date: "1930-01-01", location: "Reference data" },
  },
  {
    registryNumber: "LR-HIGHEST-TC-ELEMENT-UNDER-PRESSURE", slug: "highest-tc-element-under-pressure", title: "Highest superconducting critical temperature of an element under pressure",
    category: "Materials Science", subcategory: "Superconductors", direction: "MAXIMIZE",
    metricName: "Superconducting transition temperature of a pure element", unit: "K",
    formalStatement: "The highest superconducting critical temperature achieved by any pure element under any pressure.",
    summary: "Scandium compressed to about 260 GPa becomes superconducting at about 36 K, reported by Chinese Academy of Sciences researchers in Physical Review Letters in 2023. It is the highest critical temperature of any element, beating titanium's 26 K.",
    value: "36",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Resistance measurements in a diamond anvil cell; Ying et al.",
    source: { title: "Physical Review Letters — Record high 36 K transition temperature to the superconducting state of elemental scandium", url: "https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.130.256002", date: "2023-06-21", location: "Institute of Physics, CAS, Beijing, China" },
  },
  {
    registryNumber: "LR-HIGHEST-TC-NICKELATE-SUPERCONDUCTOR", slug: "highest-tc-nickelate-superconductor", title: "Highest superconducting critical temperature of a nickelate",
    category: "Materials Science", subcategory: "Superconductors", direction: "MAXIMIZE",
    metricName: "Superconducting transition temperature of a nickel-oxide compound", unit: "K",
    formalStatement: "The highest superconducting critical temperature reported for any nickelate (nickel-oxide) superconductor.",
    summary: "Sun Yat-sen University researchers reported in Nature in 2023 that the bilayer nickelate La3Ni2O7 superconducts at about 80 K under pressures of 14 GPa or more. It is the highest critical temperature found in a nickelate, opening a second family of liquid-nitrogen-temperature oxide superconductors after the cuprates.",
    value: "80",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Resistance and magnetic susceptibility under pressure; Sun et al.",
    source: { title: "Nature — Signatures of superconductivity near 80 K in a nickelate under high pressure", url: "https://www.nature.com/articles/s41586-023-06408-7", date: "2023-07-12", location: "Sun Yat-sen University, Guangzhou, China" },
  },
  {
    registryNumber: "LR-HIGHEST-DIELECTRIC-CONSTANT-MATERIAL", slug: "highest-dielectric-constant-material", title: "Highest dielectric constant of a ceramic material",
    category: "Materials Science", subcategory: "Electronic Materials", direction: "MAXIMIZE",
    metricName: "Relative permittivity at room temperature", unit: "dimensionless",
    formalStatement: "The largest room-temperature relative permittivity measured in a stable ceramic oxide.",
    summary: "Calcium copper titanate (CaCu3Ti4O12, CCTO), reported by Subramanian and colleagues at DuPont in 2000, has a room-temperature dielectric constant of about 100,000 at kilohertz frequencies, nearly unchanged from 100 K to 600 K. This 'colossal' permittivity is linked to barrier-layer effects.",
    value: "100000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Impedance spectroscopy; Subramanian et al., Journal of Solid State Chemistry.",
    source: { title: "Journal of Solid State Chemistry — High dielectric constant in ACu3Ti4O12", url: "https://www.sciencedirect.com/journal/journal-of-solid-state-chemistry", date: "2000-06-01", location: "DuPont Central Research, Delaware, USA" },
  },
  {
    registryNumber: "LR-STRONGEST-BULK-STEEL", slug: "strongest-bulk-steel", title: "Strongest steel ever produced",
    category: "Materials Science", subcategory: "Metals & Alloys", direction: "MAXIMIZE",
    metricName: "Tensile strength of a steel", unit: "GPa",
    formalStatement: "The highest tensile strength ever measured in a steel.",
    summary: "Cold-drawn pearlitic steel wire, with carbon segregated at nanoscale grain boundaries, reached a tensile strength of about 7 GPa, reported by Li and colleagues at the Max Planck Institute for Iron Research in Physical Review Letters in 2014. This is the strongest steel ever made, approaching the theoretical limit for iron.",
    value: "7",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Tensile testing with atom-probe tomography; Li et al.",
    source: { title: "Physical Review Letters — Segregation stabilizes nanocrystalline bulk steel with near theoretical strength", url: "https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.113.106104", date: "2014-09-04", location: "Max-Planck-Institut für Eisenforschung, Düsseldorf, Germany" },
  },
  {
    registryNumber: "LR-STRONGEST-DENSIFIED-WOOD", slug: "strongest-densified-wood", title: "Strongest processed natural wood",
    category: "Materials Science", subcategory: "Biomaterials", direction: "MAXIMIZE",
    metricName: "Tensile strength of chemically treated and densified wood", unit: "MPa",
    formalStatement: "The highest tensile strength reported for wood processed into a densified form.",
    summary: "University of Maryland researchers led by Liangbing Hu reported in Nature in 2018 that partially removing lignin and hot-pressing natural wood raised its tensile strength to about 548 MPa, more than ten times that of natural wood. Its specific strength is comparable to titanium alloys.",
    value: "548",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Tensile testing; Song et al., Nature.",
    source: { title: "Nature — Processing bulk natural wood into a high-performance structural material", url: "https://www.nature.com/articles/nature25476", date: "2018-02-07", location: "University of Maryland, College Park, USA" },
  },
  {
    registryNumber: "LR-LARGEST-ELASTIC-STRAIN-DIAMOND", slug: "largest-elastic-strain-diamond", title: "Largest elastic strain in diamond",
    category: "Materials Science", subcategory: "Mechanical Properties", direction: "MAXIMIZE",
    metricName: "Maximum reversible tensile strain", unit: "%",
    formalStatement: "The largest reversible elastic strain demonstrated in diamond.",
    summary: "Researchers from City University of Hong Kong, MIT and Ulsan National Institute of Science and Technology reported in Science in 2018 that single-crystal diamond nanoneedles could bend elastically to about 9% local tensile strain and spring back. This is far above the under 1% elastic strain possible in bulk diamond.",
    value: "9",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "In-situ electron microscope nano-indentation and finite element analysis; Banerjee et al.",
    source: { title: "Science — Ultralarge elastic deformation of nanoscale diamond", url: "https://www.science.org/doi/10.1126/science.aar4165", date: "2018-04-20", location: "City University of Hong Kong" },
  },
];
