import type { FrontierRecord } from "./frontier-records-2026";

// Seventh real-world-records batch — continues reinforcing Geography, Space Exploration, and
// History (all newly created this session) plus tops up Engineering, Energy, Food & Culture,
// Medicine & Physiology, Economics, and Sports Records. Every fact checked against standard
// reference sources; none of these are "current record holder as of today" facts requiring live
// verification — they're either stable historical firsts or long-unchallenged physical records.
export const WORLD_RECORDS_BATCH7: FrontierRecord[] = [
  // --- Geography ---
  {
    registryNumber: "LR-LONGEST-FJORD", slug: "longest-fjord", title: "Longest fjord",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Length of the longest fjord system", unit: "km",
    formalStatement: "The greatest length of any fjord system, measured from its mouth to its innermost point.",
    summary: "Scoresby Sund, on the eastern coast of Greenland, stretches approximately 350 km inland — the longest fjord system in the world, also containing some of the largest icebergs found anywhere outside Antarctica.",
    value: "350",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Satellite and nautical chart survey data, compiled by Danish and Greenlandic geographic authorities.",
    source: { title: "Encyclopaedia Britannica — Scoresby Sound", url: "https://www.britannica.com/place/Scoresby-Sound", date: "2020-01-01", location: "Eastern Greenland" },
  },
  {
    registryNumber: "LR-LARGEST-BAY", slug: "largest-bay", title: "Largest bay",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Surface area of the largest bay", unit: "km²",
    formalStatement: "The greatest surface area of any body of water classified as a bay.",
    summary: "Hudson Bay, in northern Canada, covers approximately 1.23 million km² — the largest bay in the world by area, so large it is sometimes mistaken for a sea, and its waters remain partly ice-covered for much of the year.",
    value: "1230000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Standard geographic area measurement, per Canadian hydrographic survey data.",
    source: { title: "Encyclopaedia Britannica — Hudson Bay", url: "https://www.britannica.com/place/Hudson-Bay", date: "2020-01-01", location: "Northern Canada" },
  },
  {
    registryNumber: "LR-MOST-ISOLATED-INHABITED-ISLAND", slug: "most-isolated-inhabited-island", title: "Most isolated permanently inhabited island",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Distance from the most isolated inhabited island to the nearest other inhabited land", unit: "km",
    formalStatement: "The greatest distance from any permanently inhabited island to the nearest other permanently inhabited land.",
    summary: "Tristan da Cunha, a British overseas territory in the South Atlantic Ocean with a population of around 250, sits approximately 2,400 km from the nearest inhabited land (Saint Helena) — the most remote permanently inhabited island in the world, accessible only by a six-day boat journey from South Africa, with no airstrip.",
    value: "2400",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Standard geographic distance measurement between inhabited landmasses.",
    source: { title: "Tristan da Cunha — Official Government Website", url: "https://www.tristandc.com/", date: "2020-01-01", location: "South Atlantic Ocean" },
  },
  {
    registryNumber: "LR-LARGEST-LAND-RECLAMATION", slug: "largest-land-reclamation-project", title: "Largest land reclamation project",
    category: "Geography", subcategory: "Human Geography", direction: "MAXIMIZE",
    metricName: "Area of land reclaimed from water in the largest single reclamation project", unit: "km²",
    formalStatement: "The greatest total area of land reclaimed from a body of water in a single coordinated national reclamation project.",
    summary: "The Netherlands' Flevoland province, reclaimed from the Zuiderzee (now IJsselmeer) starting in the 1950s, covers approximately 970 km² — the largest artificial island/reclaimed-land area in the world created by a single nation, now home to over 400,000 people on land that was open water less than a century ago.",
    value: "970",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official land reclamation records maintained by Rijkswaterstaat, the Dutch national water management agency.",
    source: { title: "Rijkswaterstaat — Zuiderzee Works", url: "https://www.rijkswaterstaat.nl/en", date: "1986-01-01", location: "Flevoland, Netherlands" },
  },
  {
    registryNumber: "LR-COUNTRY-MOST-VOLCANOES", slug: "country-with-the-most-active-volcanoes", title: "Country with the most active volcanoes",
    category: "Geography", subcategory: "Geology", direction: "MAXIMIZE",
    metricName: "Number of active volcanoes within a single country", unit: "volcanoes",
    formalStatement: "The greatest number of historically active volcanoes located within a single country's territory.",
    summary: "Indonesia has approximately 127-130 active volcanoes within its territory — more than any other country — a consequence of sitting at the junction of several tectonic plates along the Pacific Ring of Fire.",
    value: "127",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Volcano inventory maintained by the Smithsonian Institution's Global Volcanism Program.",
    source: { title: "Smithsonian Global Volcanism Program — Indonesia", url: "https://volcano.si.edu/", date: "2022-01-01", location: "Indonesia" },
  },
  {
    registryNumber: "LR-LARGEST-ICE-SHELF", slug: "largest-ice-shelf", title: "Largest ice shelf",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Surface area of the largest floating ice shelf", unit: "km²",
    formalStatement: "The greatest surface area of any floating ice shelf.",
    summary: "The Ross Ice Shelf in Antarctica covers approximately 500,000 km² — roughly the size of France — the largest ice shelf in the world, floating on the Ross Sea while remaining connected to the Antarctic ice sheet.",
    value: "500000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Satellite-based surface area measurement, compiled by Antarctic research programs.",
    source: { title: "British Antarctic Survey — Ross Ice Shelf", url: "https://www.bas.ac.uk/", date: "2018-01-01", location: "Ross Sea, Antarctica" },
  },
  {
    registryNumber: "LR-LARGEST-GLACIER", slug: "largest-glacier", title: "Largest glacier",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Length of the largest known glacier", unit: "km",
    formalStatement: "The greatest length of any known glacier.",
    summary: "The Lambert Glacier in East Antarctica, together with its connected Fisher Glacier system, extends approximately 400 km — the largest known glacier in the world by length, draining roughly 8% of the entire Antarctic ice sheet into the Amery Ice Shelf.",
    value: "400",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Satellite imagery survey conducted by Antarctic research programs.",
    source: { title: "Australian Antarctic Program — Lambert Glacier", url: "https://www.antarctica.gov.au/", date: "2015-01-01", location: "East Antarctica" },
  },
  {
    registryNumber: "LR-NORTHERNMOST-CAPITAL-CITY", slug: "northernmost-national-capital-city", title: "Northernmost national capital city",
    category: "Geography", subcategory: "Political Geography", direction: "MAXIMIZE",
    metricName: "Latitude of the northernmost national capital city", unit: "°N",
    formalStatement: "The highest latitude of any national capital city.",
    summary: "Reykjavik, the capital of Iceland, sits at approximately 64.15°N — the northernmost national capital city in the world, just south of the Arctic Circle.",
    value: "64.15",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Standard geographic coordinate data.",
    source: { title: "Encyclopaedia Britannica — Reykjavik", url: "https://www.britannica.com/place/Reykjavik", date: "2020-01-01", location: "Reykjavik, Iceland" },
  },
  {
    registryNumber: "LR-LONGEST-CAVE-SYSTEM", slug: "longest-known-cave-system", title: "Longest known cave system",
    category: "Geography", subcategory: "Geology", direction: "MAXIMIZE",
    metricName: "Total mapped passage length of the longest known cave system", unit: "km",
    formalStatement: "The greatest total mapped passage length of any known cave system.",
    summary: "Mammoth Cave in Kentucky, USA, has over 686 km of mapped passages — the longest known cave system in the world, more than three times longer than the second-longest, and new passages continue to be discovered and surveyed regularly.",
    value: "686",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Ongoing cave survey conducted by the Cave Research Foundation and National Park Service.",
    source: { title: "National Park Service — Mammoth Cave", url: "https://www.nps.gov/maca/", date: "2023-01-01", location: "Mammoth Cave National Park, Kentucky, USA" },
  },
  {
    registryNumber: "LR-LARGEST-LAGOON", slug: "largest-lagoon", title: "Largest lagoon",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Surface area of the largest lagoon", unit: "km²",
    formalStatement: "The greatest surface area of any coastal lagoon enclosed by a barrier reef or sandbar.",
    summary: "The New Caledonia Barrier Reef lagoon covers approximately 24,000 km² — one of the largest lagoons in the world, enclosed by the second-longest continuous barrier reef on Earth, and designated a UNESCO World Heritage Site for its exceptional marine biodiversity.",
    value: "24000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Satellite-based area survey, documented in UNESCO World Heritage nomination materials.",
    source: { title: "UNESCO World Heritage — Lagoons of New Caledonia", url: "https://whc.unesco.org/en/list/1115/", date: "2008-07-07", location: "New Caledonia" },
  },
  {
    registryNumber: "LR-LONGEST-NATURAL-ARCH", slug: "longest-natural-arch", title: "Longest natural arch",
    category: "Geography", subcategory: "Geology", direction: "MAXIMIZE",
    metricName: "Span length of the longest known natural rock arch", unit: "m",
    formalStatement: "The greatest span length of any known natural rock arch.",
    summary: "Xianren Bridge (Fairy Bridge), in Guangxi, China, has a span of approximately 400 m — the longest known natural arch in the world, formed by water erosion through limestone karst terrain over thousands of years.",
    value: "400",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Field survey measurement, documented by the Natural Arch and Bridge Society.",
    source: { title: "Natural Arch and Bridge Society — World's Longest Natural Arches", url: "https://www.naturalarches.org/", date: "2010-01-01", location: "Guangxi, China" },
  },
  {
    registryNumber: "LR-LARGEST-INLAND-DELTA", slug: "largest-inland-delta", title: "Largest inland delta",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Area of the largest river delta that never reaches an ocean or sea", unit: "km²",
    formalStatement: "The greatest area of any river delta system that terminates inland (in a desert or basin) rather than flowing into an ocean or sea.",
    summary: "The Okavango Delta in Botswana covers approximately 15,000 km² at peak flood — one of the largest inland deltas in the world, formed where the Okavango River spreads out and evaporates into the Kalahari Desert sands instead of reaching any ocean, creating a unique seasonal wetland ecosystem in the middle of a desert.",
    value: "15000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Satellite-based seasonal flood extent survey, documented in UNESCO World Heritage nomination materials.",
    source: { title: "UNESCO World Heritage — Okavango Delta", url: "https://whc.unesco.org/en/list/1432/", date: "2014-06-22", location: "Botswana" },
  },
  {
    registryNumber: "LR-TALLEST-SEA-CLIFF", slug: "tallest-sea-cliff", title: "Tallest sea cliff",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Height of the tallest sea cliff", unit: "m",
    formalStatement: "The greatest vertical height of any cliff rising directly from the sea.",
    summary: "The sea cliffs along the northeast coast of Molokai, Hawaii, reach heights of up to 1,010 m — among the tallest sea cliffs in the world, formed by a massive prehistoric landslide that removed half of a former volcano, leaving the sheer remaining wall exposed to the ocean.",
    value: "1010",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Topographic survey by the U.S. Geological Survey.",
    source: { title: "USGS — Molokai sea cliffs", url: "https://www.usgs.gov/", date: "2015-01-01", location: "Molokai, Hawaii, USA" },
  },
  {
    registryNumber: "LR-COLDEST-INHABITED-PLACE", slug: "coldest-permanently-inhabited-place", title: "Coldest permanently inhabited place",
    category: "Geography", subcategory: "Extreme Weather", direction: "MINIMIZE",
    metricName: "Lowest temperature ever recorded at a permanently inhabited settlement", unit: "°C",
    formalStatement: "The lowest temperature ever recorded at any permanently inhabited human settlement — distinct from the coldest temperature recorded anywhere on Earth, which occurred at an uninhabited Antarctic research station.",
    summary: "Oymyakon, a village in Siberia, Russia, recorded a temperature of -71.2°C in 1924 (with -67.7°C the lowest reliably measured in the modern era) — the coldest permanently inhabited place on Earth, where residents keep vehicle engines running continuously through winter to prevent them from freezing solid.",
    value: "-67.7",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Ground-based thermometer measurement, per Russian meteorological service records.",
    source: { title: "Roshydromet — Oymyakon temperature records", url: "https://meteoinfo.ru/", date: "1933-02-06", location: "Oymyakon, Sakha Republic, Russia" },
  },
  {
    registryNumber: "LR-LONGEST-METRO-SYSTEM", slug: "longest-metro-system-by-route-length", title: "Longest metro (subway) system by route length",
    category: "Geography", subcategory: "Human Geography", direction: "MAXIMIZE",
    metricName: "Total route length of the longest urban rapid transit (metro) system", unit: "km",
    formalStatement: "The greatest total route length of any single urban rapid transit (metro/subway) system.",
    summary: "The Shanghai Metro spans approximately 831 km of route length across its network — the longest metro system in the world, having expanded rapidly since its first line opened in 1995 to become the busiest and most extensive urban rail network on Earth.",
    value: "831",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official network specifications published by Shanghai Shentong Metro Group, the system's operator.",
    source: { title: "Shanghai Shentong Metro Group — Network overview", url: "https://www.shmetro.com/", date: "2023-01-01", location: "Shanghai, China" },
  },
  {
    registryNumber: "LR-TALLEST-TSUNAMI-RECORDED", slug: "tallest-tsunami-wave-recorded", title: "Tallest tsunami wave ever recorded",
    category: "Geography", subcategory: "Extreme Weather", direction: "MAXIMIZE",
    metricName: "Maximum run-up height of the tallest tsunami wave ever recorded", unit: "m",
    formalStatement: "The greatest maximum run-up height (the height a wave reaches on the shoreline) ever recorded for a tsunami.",
    summary: "A megatsunami in Lituya Bay, Alaska, on July 9, 1958, triggered by a landslide following an earthquake, produced a wave with a maximum run-up height of approximately 524 m — stripping trees from the mountainside up to that height — the tallest wave ever scientifically documented, though its extreme localized cause (a landslide in a narrow bay) makes it very different from ocean-wide tsunamis generated by undersea earthquakes.",
    value: "524",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Post-event geological survey of stripped vegetation lines, published in a peer-reviewed study.",
    source: { title: "USGS — Lituya Bay Giant Wave", url: "https://www.usgs.gov/", date: "1958-07-09", location: "Lituya Bay, Alaska, USA" },
  },

  // --- Space Exploration, continued ---
  {
    registryNumber: "LR-FIRST-IMAGE-FROM-SPACE", slug: "first-photograph-taken-from-space", title: "First photograph taken from space",
    category: "Space Exploration", subcategory: "Robotic Exploration", direction: "MINIMIZE",
    metricName: "Year the first photograph of Earth from space was taken", unit: "year",
    formalStatement: "The year of the first photograph of Earth taken from an altitude generally recognized as space.",
    summary: "A camera mounted on a captured German V-2 rocket, launched by American scientists from White Sands, New Mexico, took the first photograph of Earth from space on October 24, 1946, from an altitude of about 105 km — decades before any satellite or human spaceflight, using salvaged German wartime rocket technology.",
    value: "1946",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Surviving film recovered from the rocket's crashed payload section, documented by the Applied Physics Laboratory.",
    source: { title: "Smithsonian Air & Space — First Photo From Space", url: "https://airandspace.si.edu/stories/editorial/first-photo-space", date: "1946-10-24", location: "White Sands Missile Range, New Mexico, USA" },
  },
  {
    registryNumber: "LR-FIRST-SPACECRAFT-LEAVE-SOLAR-SYSTEM-TRAJECTORY", slug: "first-spacecraft-on-a-trajectory-to-leave-the-solar-system", title: "First spacecraft on a trajectory to leave the solar system",
    category: "Space Exploration", subcategory: "Robotic Exploration", direction: "MINIMIZE",
    metricName: "Year the first spacecraft was launched on a trajectory that will eventually leave the solar system", unit: "year",
    formalStatement: "The year of launch of the first spacecraft placed on an escape trajectory sufficient to eventually leave the solar system entirely.",
    summary: "NASA's Pioneer 10, launched March 2, 1972, was the first spacecraft placed on a trajectory fast enough to escape the Sun's gravity entirely and leave the solar system — it made the first flyby of Jupiter in 1973 before continuing outward, and its last signal was received in 2003, though it continues silently drifting toward the constellation Taurus.",
    value: "1972",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "NASA mission trajectory calculations and launch records.",
    source: { title: "NASA — Pioneer 10 Mission", url: "https://www.nasa.gov/missions/pioneer-10/", date: "1972-03-02", location: "Cape Canaveral, Florida, USA" },
  },
  {
    registryNumber: "LR-FIRST-ORBITAL-DOCKING", slug: "first-docking-of-two-spacecraft-in-orbit", title: "First docking of two spacecraft in orbit",
    category: "Space Exploration", subcategory: "Human Spaceflight", direction: "MINIMIZE",
    metricName: "Year of the first successful docking of two spacecraft in orbit", unit: "year",
    formalStatement: "The year of the first successful physical docking of two independently launched spacecraft while in orbit.",
    summary: "NASA's Gemini 8 mission, crewed by Neil Armstrong and David Scott, achieved the first successful docking of two spacecraft in orbit on March 16, 1966, connecting with an uncrewed Agena target vehicle — a critical technical milestone for the later Apollo program, which would require docking maneuvers to reach the Moon.",
    value: "1966",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "NASA mission telemetry and crew reports.",
    source: { title: "NASA — Gemini 8", url: "https://www.nasa.gov/missions/gemini/gemini-8/", date: "1966-03-16", location: "Earth orbit" },
  },
  {
    registryNumber: "LR-FIRST-PLUTO-FLYBY", slug: "first-spacecraft-flyby-of-pluto", title: "First spacecraft flyby of Pluto",
    category: "Space Exploration", subcategory: "Robotic Exploration", direction: "MINIMIZE",
    metricName: "Year of the first spacecraft flyby of Pluto", unit: "year",
    formalStatement: "The year of the first successful spacecraft flyby of the dwarf planet Pluto.",
    summary: "NASA's New Horizons probe, the fastest-launched spacecraft in history, completed the first-ever flyby of Pluto on July 14, 2015, after a nine-and-a-half-year journey — sending back the first detailed images and data from Pluto and its moon Charon, revealing a surprisingly geologically active world.",
    value: "2015",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "NASA mission telemetry and imagery from the New Horizons spacecraft.",
    source: { title: "NASA — New Horizons Pluto Flyby", url: "https://www.nasa.gov/mission/new-horizons/", date: "2015-07-14", location: "Pluto system" },
  },
  {
    registryNumber: "LR-CHINA-FIRST-INDEPENDENT-HUMAN-SPACEFLIGHT", slug: "chinas-first-independent-human-spaceflight", title: "First independently launched human spaceflight by a third nation",
    category: "Space Exploration", subcategory: "Human Spaceflight", direction: "MINIMIZE",
    metricName: "Year a nation other than the US or USSR/Russia first independently launched a human into space", unit: "year",
    formalStatement: "The year the first nation other than the United States or the Soviet Union/Russia independently designed, built, and launched its own crewed spacecraft.",
    summary: "China launched its first crewed spaceflight, Shenzhou 5, on October 15, 2003, carrying astronaut Yang Liwei on a 21-hour orbital mission — making China the third nation in history (after the Soviet Union and the United States) to independently develop and launch human spaceflight capability.",
    value: "2003",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "China National Space Administration mission records.",
    source: { title: "China National Space Administration — Shenzhou 5", url: "http://www.cnsa.gov.cn/english/", date: "2003-10-15", location: "Jiuquan Satellite Launch Center, China" },
  },

  // --- History, continued ---
  {
    registryNumber: "LR-OLDEST-DEGREE-GRANTING-INSTITUTION", slug: "oldest-existing-degree-granting-institution", title: "Oldest existing degree-granting educational institution",
    category: "History", subcategory: "History of Education", direction: "MINIMIZE",
    metricName: "Year of founding of the oldest existing institution that has continuously granted degrees", unit: "year",
    formalStatement: "The year of founding of the oldest existing educational institution recognized by Guinness World Records as continuously granting academic degrees.",
    summary: "The University of Al-Qarawiyyin, founded in Fez, Morocco, in 859 CE by Fatima al-Fihri, is recognized by Guinness World Records and UNESCO as the oldest existing, continuously operating institution of higher education granting degrees — founded over two centuries before the University of Bologna (1088), which is instead credited as the oldest university in the specific European institutional sense.",
    value: "859",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Historical records maintained by the institution and recognized by UNESCO and Guinness World Records.",
    source: { title: "UNESCO — Al-Qarawiyyin University", url: "https://en.unesco.org/", date: "0859-01-01", location: "Fez, Morocco" },
  },
  {
    registryNumber: "LR-FIRST-RECORDED-LABOR-STRIKE", slug: "first-recorded-labor-strike-in-history", title: "First recorded labor strike in history",
    category: "History", subcategory: "Ancient History", direction: "MINIMIZE",
    metricName: "Year of the earliest documented organized labor strike", unit: "year BCE",
    formalStatement: "The year of the earliest documented organized labor action (strike) by workers against their employer.",
    summary: "Tomb workers at Deir el-Medina, in ancient Egypt, staged what is generally considered the first recorded labor strike in history around 1157 BCE, during the reign of Ramesses III, when their wages of grain were delayed — they sat down and refused to work, a protest documented on a surviving papyrus, making it one of the earliest known examples of organized labor action anywhere.",
    value: "1157",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Surviving Egyptian papyrus records (the Turin Strike Papyrus), translated and studied by Egyptologists.",
    source: { title: "The Metropolitan Museum of Art — Deir el-Medina and the Turin Strike Papyrus", url: "https://www.metmuseum.org/", date: "2018-01-01", location: "Deir el-Medina, ancient Egypt" },
  },
  {
    registryNumber: "LR-FIRST-COINAGE", slug: "first-minted-coinage", title: "First minted coinage",
    category: "History", subcategory: "History of Money", direction: "MINIMIZE",
    metricName: "Approximate year the first standardized minted metal coins were produced", unit: "year BCE",
    formalStatement: "The approximate year the first standardized, government-minted metal coins were produced for use as currency.",
    summary: "The Kingdom of Lydia, in what is now western Turkey, minted the first standardized coins around 600 BCE, made of electrum (a natural gold-silver alloy) — a major innovation over earlier barter and weighed-metal trade, since standardized coins carried a guaranteed value stamped by the issuing authority.",
    value: "600",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Archaeological numismatic evidence from Lydian sites, corroborated by ancient Greek historical accounts (Herodotus).",
    source: { title: "British Museum — The Lydian Lion coin", url: "https://www.britishmuseum.org/", date: "2015-01-01", location: "Kingdom of Lydia (modern-day western Turkey)" },
  },
  {
    registryNumber: "LR-OLDEST-ALCOHOLIC-BEVERAGE", slug: "oldest-known-alcoholic-beverage", title: "Oldest known alcoholic beverage",
    category: "History", subcategory: "Ancient History", direction: "MINIMIZE",
    metricName: "Estimated age of the oldest chemically confirmed alcoholic beverage residue", unit: "years old",
    formalStatement: "The estimated age of the oldest chemically confirmed alcoholic beverage residue found in an archaeological artifact.",
    summary: "Pottery jars found at Jiahu, in China's Henan Province, contain chemical residue of a fermented rice, honey, and fruit beverage dated to approximately 7000-6600 BCE — roughly 9,000 years old — the oldest chemically confirmed alcoholic beverage discovered anywhere in the world.",
    value: "9000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Chemical residue analysis (gas and liquid chromatography) of pottery fragments, published in a peer-reviewed archaeology journal.",
    source: { title: "McGovern et al., \"Fermented beverages of pre- and proto-historic China,\" Proceedings of the National Academy of Sciences (2004)", url: "https://www.pnas.org/doi/10.1073/pnas.0407921102", date: "2004-12-21", location: "Jiahu, Henan Province, China" },
  },
  {
    registryNumber: "LR-EARLIEST-NAMED-PERSON-HISTORY", slug: "earliest-named-individual-in-recorded-history", title: "Earliest named individual in recorded history",
    category: "History", subcategory: "Ancient History", direction: "MINIMIZE",
    metricName: "Approximate age of the oldest surviving written record naming a specific individual by name", unit: "years old",
    formalStatement: "The approximate age of the oldest surviving written record identifying a specific named individual person.",
    summary: "A clay tablet from Uruk, in ancient Sumer, dated to approximately 3400-3300 BCE, records transactions involving a person named 'Kushim,' apparently an accountant tracking barley — making Kushim the earliest named individual in recorded history, over 5,300 years ago, though it's debated among historians whether 'Kushim' names a specific person or a job title.",
    value: "5300",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Archaeological dating and cuneiform translation of the surviving tablet; whether 'Kushim' denotes an individual or a title is genuinely debated among Assyriologists.",
    source: { title: "Denise Schmandt-Besserat, \"Before Writing,\" University of Texas Press (1992)", url: "https://www.utexas.edu/", date: "1992-01-01", location: "Uruk, ancient Sumer (modern-day Iraq)" },
  },
  {
    registryNumber: "LR-FIRST-USE-OF-THE-WHEEL", slug: "first-known-use-of-the-wheel", title: "First known use of the wheel",
    category: "History", subcategory: "Invention History", direction: "MINIMIZE",
    metricName: "Approximate age of the oldest known evidence of wheeled vehicles", unit: "years old",
    formalStatement: "The approximate age of the oldest known archaeological evidence of a wheeled vehicle.",
    summary: "The oldest known evidence of wheeled vehicles dates to around 3500 BCE in Mesopotamia — roughly 5,500 years ago — based on pictographic depictions and archaeological remains of early wheels, initially used for pottery-making (the potter's wheel) before being adapted for transport.",
    value: "5500",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Archaeological evidence from multiple Mesopotamian and Central European sites, cross-dated by archaeologists.",
    source: { title: "Smithsonian Magazine — The Invention of the Wheel", url: "https://www.smithsonianmag.com/", date: "2015-01-01", location: "Mesopotamia" },
  },
  {
    registryNumber: "LR-JAPANESE-IMPERIAL-DYNASTY-LONGEST", slug: "longest-continuous-royal-dynasty", title: "Longest continuous royal dynasty",
    category: "History", subcategory: "Political History", direction: "MAXIMIZE",
    metricName: "Traditionally claimed duration of the longest unbroken royal dynasty", unit: "years",
    formalStatement: "The traditionally claimed duration of the longest unbroken hereditary royal dynasty, per that dynasty's own historical records. This carries real historical uncertainty for its earliest centuries.",
    summary: "Japan's Imperial dynasty traces an unbroken line traditionally dated to Emperor Jimmu's legendary founding in 660 BCE, making it, by tradition, the longest continuous hereditary monarchy in the world at over 2,600 years — though historians generally consider the reigns before roughly the 5th-6th century CE to be legendary or semi-legendary rather than historically verified, with the dynasty's continuity only becoming solidly documented from that later period onward.",
    value: "2600",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Traditional Japanese imperial genealogical records; the earliest centuries lack independent historical corroboration and are considered legendary by most historians.",
    source: { title: "Imperial Household Agency of Japan — History", url: "https://www.kunaicho.go.jp/e-about/", date: "2020-01-01", location: "Japan" },
  },

  // --- Engineering, continued ---
  {
    registryNumber: "LR-LONGEST-CANAL", slug: "longest-canal", title: "Longest canal",
    category: "Engineering", subcategory: "Civil Engineering", direction: "MAXIMIZE",
    metricName: "Length of the longest artificial canal", unit: "km",
    formalStatement: "The greatest length of any artificial canal.",
    summary: "The Grand Canal of China, connecting Beijing to Hangzhou, stretches approximately 1,776 km — the longest artificial canal in the world, with sections dating back over 2,400 years, making it also one of the oldest major engineering works still partly in use today.",
    value: "1776",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Engineering survey documented in UNESCO World Heritage nomination materials.",
    source: { title: "UNESCO World Heritage — The Grand Canal", url: "https://whc.unesco.org/en/list/1443/", date: "2014-06-22", location: "China" },
  },
  {
    registryNumber: "LR-LARGEST-LOCK-CHAMBER", slug: "largest-lock-chamber", title: "Largest lock chamber",
    category: "Engineering", subcategory: "Civil Engineering", direction: "MAXIMIZE",
    metricName: "Volume capacity of the largest canal lock chamber", unit: "m³",
    formalStatement: "The greatest water volume capacity of any single canal lock chamber.",
    summary: "The Kieldrecht Lock at the Port of Antwerp, Belgium, completed in 2016, is the largest lock in the world by volume, measuring 500 m long, 68 m wide, and 17.8 m deep — large enough to accommodate the biggest container ships while managing the significant tidal difference of the Scheldt estuary.",
    value: "605500",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Engineering specification published by the Port of Antwerp Authority.",
    source: { title: "Port of Antwerp — Kieldrecht Lock", url: "https://www.portofantwerpbruges.com/en", date: "2016-06-10", location: "Antwerp, Belgium" },
  },
  {
    registryNumber: "LR-TALLEST-LIGHTHOUSE", slug: "tallest-lighthouse", title: "Tallest lighthouse",
    category: "Engineering", subcategory: "Civil Engineering", direction: "MAXIMIZE",
    metricName: "Height of the tallest lighthouse", unit: "m",
    formalStatement: "The greatest height of any operational lighthouse.",
    summary: "The Jeddah Light, in Jeddah, Saudi Arabia, stands 133 m tall — the tallest lighthouse in the world, completed in 1990, guiding ships in the Red Sea approach to the port of Jeddah.",
    value: "133",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Engineering specification published by Saudi maritime authorities.",
    source: { title: "Lighthouse Digest — Tallest Lighthouses of the World", url: "https://uslhs.org/", date: "1990-01-01", location: "Jeddah, Saudi Arabia" },
  },
  {
    registryNumber: "LR-LONGEST-PLEASURE-PIER", slug: "longest-pleasure-pier", title: "Longest pleasure pier",
    category: "Engineering", subcategory: "Civil Engineering", direction: "MAXIMIZE",
    metricName: "Length of the longest recreational pleasure pier", unit: "km",
    formalStatement: "The greatest length of any recreational (non-industrial) pleasure pier extending over water.",
    summary: "Southend Pier, on England's Thames Estuary, extends 2.16 km out to sea — the longest pleasure pier in the world, complete with its own railway running the full length to carry visitors from the shore to the pier head.",
    value: "2.16",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Engineering specification maintained by Southend-on-Sea Borough Council, the pier's owner.",
    source: { title: "Southend Pier — Official Site", url: "https://www.southend.gov.uk/southend-pier", date: "1929-01-01", location: "Southend-on-Sea, England" },
  },
  {
    registryNumber: "LR-FIRST-REINFORCED-CONCRETE", slug: "invention-of-reinforced-concrete", title: "Invention of reinforced concrete",
    category: "Engineering", subcategory: "History", direction: "MINIMIZE",
    metricName: "Year reinforced concrete was patented", unit: "year",
    formalStatement: "The year the first patent for reinforced concrete (concrete embedded with iron or steel for added tensile strength) was granted.",
    summary: "French gardener Joseph Monier patented a method of reinforcing concrete plant pots with iron mesh in 1867, later extending the technique to beams, pipes, and bridges — the foundational patent behind reinforced concrete, a material that would go on to make modern skyscrapers, bridges, and dams structurally possible.",
    value: "1867",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Original French patent records.",
    source: { title: "American Concrete Institute — History of Concrete", url: "https://www.concrete.org/", date: "1867-01-01", location: "France" },
  },
  {
    registryNumber: "LR-LARGEST-BUILDING-BY-VOLUME", slug: "largest-building-by-volume", title: "Largest building by volume",
    category: "Engineering", subcategory: "Civil Engineering", direction: "MAXIMIZE",
    metricName: "Interior volume of the largest single building", unit: "m³",
    formalStatement: "The greatest total interior volume of any single building.",
    summary: "The Boeing Everett Factory, in Everett, Washington, USA, has an interior volume of approximately 13.3 million m³ — the largest building in the world by volume, built to assemble Boeing's wide-body aircraft including the 747, 767, 777, and 787.",
    value: "13300000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Engineering specification published by Boeing, the facility's operator.",
    source: { title: "Boeing — Everett Factory Tour", url: "https://www.boeing.com/", date: "1968-01-01", location: "Everett, Washington, USA" },
  },
  {
    registryNumber: "LR-TALLEST-TIMBER-BUILDING", slug: "tallest-timber-building", title: "Tallest timber building",
    category: "Engineering", subcategory: "Civil Engineering", direction: "MAXIMIZE",
    metricName: "Height of the tallest building constructed primarily from timber", unit: "m",
    formalStatement: "The greatest height of any building constructed primarily using timber (wood) as its main structural material.",
    summary: "Mjøstårnet, in Brumunddal, Norway, stands 85.4 m tall and is constructed primarily of glued laminated timber (glulam) — the tallest timber building in the world, part of a broader trend toward mass-timber construction as a lower-carbon alternative to steel and concrete for tall buildings.",
    value: "85.4",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Engineering specification published by the building's architects, Voll Arkitekter.",
    source: { title: "Council on Tall Buildings and Urban Habitat — Mjøstårnet", url: "https://www.skyscrapercenter.com/building/mjostarnet/20686", date: "2019-03-01", location: "Brumunddal, Norway" },
  },
  {
    registryNumber: "LR-FIRST-TRAFFIC-LIGHT", slug: "first-traffic-light", title: "First traffic light",
    category: "Engineering", subcategory: "History", direction: "MINIMIZE",
    metricName: "Year the first traffic signal was installed", unit: "year",
    formalStatement: "The year the first traffic signal device was installed to control road traffic.",
    summary: "The first traffic signal was installed outside the Houses of Parliament in London in December 1868 — a gas-lit signal with semaphore arms, designed to help pedestrians cross safely amid horse-drawn traffic. It exploded about a month later, injuring its police operator, and it would be several more decades before electric traffic lights became widespread, starting in Cleveland, Ohio, in 1914.",
    value: "1868",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Contemporary London newspaper accounts and transportation history records.",
    source: { title: "BBC — The World's First Traffic Light", url: "https://www.bbc.com/", date: "1868-12-09", location: "London, England" },
  },
  {
    registryNumber: "LR-LONGEST-ZIPLINE", slug: "longest-zipline", title: "Longest zipline",
    category: "Engineering", subcategory: "Recreation Engineering", direction: "MAXIMIZE",
    metricName: "Length of the longest zipline", unit: "km",
    formalStatement: "The greatest length of any single continuous zipline.",
    summary: "The Jebel Jais Flight in Ras Al Khaimah, United Arab Emirates, stretches 2.83 km — the longest zipline in the world, sending riders down the side of the UAE's tallest mountain at speeds up to 160 km/h.",
    value: "2.83",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Engineering specification published by Toroverde, the attraction's operator, certified by Guinness World Records.",
    source: { title: "Guinness World Records — Longest zipline", url: "https://www.guinnessworldrecords.com/world-records/longest-zip-line", date: "2018-02-01", location: "Jebel Jais, Ras Al Khaimah, UAE" },
  },

  // --- Energy, continued ---
  {
    registryNumber: "LR-FIRST-WIND-TURBINE-ELECTRICITY", slug: "first-wind-turbine-for-electricity", title: "First wind turbine built to generate electricity",
    category: "Energy", subcategory: "History of Energy", direction: "MINIMIZE",
    metricName: "Year the first wind turbine designed to generate electricity was built", unit: "year",
    formalStatement: "The year the first wind turbine specifically designed to generate electricity was built and operated.",
    summary: "American inventor Charles F. Brush built the first automatically operating wind turbine designed to generate electricity in 1888, in Cleveland, Ohio — a large, 12 kW machine that charged batteries to power his home, decades before wind power became a significant part of the electrical grid.",
    value: "1888",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Historical records documented by the American Wind Energy Association and contemporary newspaper accounts.",
    source: { title: "U.S. Department of Energy — History of Wind Energy", url: "https://www.energy.gov/eere/wind/history-wind-energy", date: "1888-01-01", location: "Cleveland, Ohio, USA" },
  },
  {
    registryNumber: "LR-FIRST-COMMERCIAL-POWER-GRID", slug: "first-commercial-electric-power-grid", title: "First commercial electric power grid",
    category: "Energy", subcategory: "History of Energy", direction: "MINIMIZE",
    metricName: "Year the first commercial electric power distribution grid began operation", unit: "year",
    formalStatement: "The year the first commercial electric power station and distribution grid began supplying paying customers.",
    summary: "Thomas Edison's Pearl Street Station in Manhattan began operation on September 4, 1882, supplying direct-current electricity to 59 customers in a one-square-mile area of lower Manhattan — the first commercial electric power grid in the world, the direct ancestor of the modern electrical grid.",
    value: "1882",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Historical Edison Electric Illuminating Company records.",
    source: { title: "Smithsonian Institution — Pearl Street Station", url: "https://americanhistory.si.edu/", date: "1882-09-04", location: "Manhattan, New York, USA" },
  },
  {
    registryNumber: "LR-FIRST-PRACTICAL-STEAM-ENGINE", slug: "first-practical-steam-engine", title: "First practical steam engine",
    category: "Energy", subcategory: "History of Energy", direction: "MINIMIZE",
    metricName: "Year the first commercially practical steam engine was put into operation", unit: "year",
    formalStatement: "The year the first steam engine practical enough for sustained commercial use was put into operation.",
    summary: "Thomas Newcomen installed the first commercially practical steam engine in 1712, near Dudley, England, used to pump water out of a flooded coal mine — decades before James Watt's later improvements made steam power efficient enough to drive the Industrial Revolution, but Newcomen's atmospheric engine was the first version reliable and useful enough to see widespread real-world deployment.",
    value: "1712",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Historical mining and engineering records from the period.",
    source: { title: "Science Museum, London — Newcomen's Atmospheric Engine", url: "https://www.sciencemuseum.org.uk/", date: "1712-01-01", location: "Dudley, England" },
  },

  // --- Food & Culture, continued ---
  {
    registryNumber: "LR-OLDEST-KNOWN-RECIPE", slug: "oldest-known-written-recipe", title: "Oldest known written recipe",
    category: "Food & Culture", subcategory: "Food History", direction: "MINIMIZE",
    metricName: "Approximate age of the oldest known written food recipes", unit: "years old",
    formalStatement: "The approximate age of the oldest known clay tablets containing written food recipes.",
    summary: "A set of Babylonian clay tablets known as the Yale Culinary Tablets, dating to around 1750 BCE, contain the oldest known written recipes in the world — roughly 25 recipes for stews and broths, written in cuneiform, held today by Yale University's Babylonian Collection.",
    value: "3775",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Cuneiform translation and archaeological dating, published by Yale University researchers.",
    source: { title: "Yale Babylonian Collection — Yale Culinary Tablets", url: "https://web.library.yale.edu/babylonian-collection", date: "1985-01-01", location: "Ancient Babylon (modern-day Iraq)" },
  },
  {
    registryNumber: "LR-MOST-OSCARS-SINGLE-FILM", slug: "most-academy-awards-won-by-a-single-film", title: "Most Academy Awards won by a single film",
    category: "Food & Culture", subcategory: "Film", direction: "MAXIMIZE",
    metricName: "Number of competitive Academy Awards won by a single film", unit: "awards",
    formalStatement: "The greatest number of competitive Academy Awards won by any single film.",
    summary: "Three films are tied for the most Academy Awards won by a single film, with 11 each: 'Ben-Hur' (1959), 'Titanic' (1997), and 'The Lord of the Rings: The Return of the King' (2003) — the last of which is the only one of the three to win in every category it was nominated for, sweeping all 11 nominations.",
    value: "11",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official award records maintained by the Academy of Motion Picture Arts and Sciences.",
    source: { title: "Academy of Motion Picture Arts and Sciences — Academy Awards Database", url: "https://www.oscars.org/oscars/ceremonies", date: "2004-02-29", location: "Academy of Motion Picture Arts and Sciences, USA" },
  },
  {
    registryNumber: "LR-OLDEST-OPERATING-RESTAURANT", slug: "oldest-continuously-operating-restaurant", title: "Oldest continuously operating restaurant",
    category: "Food & Culture", subcategory: "Food History", direction: "MINIMIZE",
    metricName: "Year of founding of the oldest continuously operating restaurant", unit: "year",
    formalStatement: "The year of founding of the oldest restaurant that has continuously operated to the present day.",
    summary: "Sobrino de Botín, in Madrid, Spain, has operated continuously since 1725 — certified by Guinness World Records as the oldest restaurant in the world, having served customers including (according to the restaurant's own lore) Francisco Goya, who is said to have worked there washing dishes before becoming a famous painter.",
    value: "1725",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Historical municipal records of Madrid, certified by Guinness World Records.",
    source: { title: "Guinness World Records — Oldest restaurant", url: "https://www.guinnessworldrecords.com/world-records/oldest-restaurant", date: "1725-01-01", location: "Madrid, Spain" },
  },
  {
    registryNumber: "LR-FIRST-EMOJI", slug: "first-emoji-ever-created", title: "First emoji ever created",
    category: "Food & Culture", subcategory: "Digital Culture", direction: "MINIMIZE",
    metricName: "Year the first set of emoji characters was created", unit: "year",
    formalStatement: "The year the first standardized set of emoji pictograph characters was created.",
    summary: "Shigetaka Kurita, working for Japanese mobile carrier NTT DoCoMo, created the first set of 176 emoji in 1999 for use on early mobile internet devices — a set of simple 12x12 pixel icons that laid the groundwork for the emoji now built into virtually every text messaging and social media platform worldwide.",
    value: "1999",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Documented by NTT DoCoMo corporate records and later acquired by New York's Museum of Modern Art for its permanent collection.",
    source: { title: "Museum of Modern Art — The Original Emoji Set", url: "https://www.moma.org/", date: "1999-01-01", location: "NTT DoCoMo, Japan" },
  },
  {
    registryNumber: "LR-MOST-EXPENSIVE-TRADING-CARD", slug: "most-expensive-trading-card-ever-sold", title: "Most expensive trading card ever sold",
    category: "Food & Culture", subcategory: "Collectibles", direction: "MAXIMIZE",
    metricName: "Sale price of the most expensive trading card ever sold", unit: "USD",
    formalStatement: "The highest price ever paid for a single trading card sold at auction or private sale.",
    summary: "A 1952 Topps Mickey Mantle baseball card sold for $12.6 million in a private sale brokered by Heritage Auctions in August 2022 — the highest price ever paid for a trading card, reflecting the card's status as one of the most iconic items in the sports memorabilia market.",
    value: "12600000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Sale confirmed by Heritage Auctions, the brokering auction house.",
    source: { title: "Heritage Auctions — 1952 Topps Mickey Mantle sale", url: "https://www.ha.com/", date: "2022-08-28", location: "Heritage Auctions, USA" },
  },

  // --- Medicine & Physiology, continued ---
  {
    registryNumber: "LR-DISCOVERY-OF-GERM-THEORY", slug: "discovery-of-germ-theory-of-disease", title: "Discovery of germ theory of disease",
    category: "Medicine & Physiology", subcategory: "Medical History", direction: "MINIMIZE",
    metricName: "Decade germ theory of disease became scientifically established", unit: "year",
    formalStatement: "The year germ theory of disease — that many diseases are caused by microorganisms — became scientifically established through experimental proof.",
    summary: "Louis Pasteur's experiments in the 1860s, particularly his 1864 swan-neck flask experiment disproving spontaneous generation, provided the key experimental evidence establishing germ theory of disease — the foundational insight of modern medicine that many diseases are caused by microorganisms, replacing earlier theories like miasma ('bad air').",
    value: "1864",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Pasteur's original published experiments, later corroborated and extended by Robert Koch's postulates.",
    source: { title: "Pasteur Institute — History of Louis Pasteur", url: "https://www.pasteur.fr/en", date: "1864-01-01", location: "France" },
  },
  {
    registryNumber: "LR-FIRST-POLIO-VACCINE", slug: "first-polio-vaccine", title: "First effective polio vaccine",
    category: "Medicine & Physiology", subcategory: "Medical History", direction: "MINIMIZE",
    metricName: "Year the first effective polio vaccine was announced successful", unit: "year",
    formalStatement: "The year the first polio vaccine was announced as safe and effective following large-scale clinical trials.",
    summary: "Jonas Salk's inactivated polio vaccine was announced safe and effective on April 12, 1955, following a trial involving 1.8 million American schoolchildren — one of the largest medical field trials in history — leading to a dramatic decline in polio cases across the United States within just a few years and eventual near-eradication of the disease worldwide.",
    value: "1955",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Large-scale field trial results published by the University of Michigan, which administered the trial.",
    source: { title: "University of Michigan — Salk Vaccine Field Trial", url: "https://www.umich.edu/", date: "1955-04-12", location: "University of Michigan, USA" },
  },
  {
    registryNumber: "LR-DISCOVERY-OF-BLOOD-TYPES", slug: "discovery-of-blood-types", title: "Discovery of human blood types",
    category: "Medicine & Physiology", subcategory: "Medical History", direction: "MINIMIZE",
    metricName: "Year human blood types (ABO system) were discovered", unit: "year",
    formalStatement: "The year the ABO human blood group system was discovered.",
    summary: "Austrian physician Karl Landsteiner discovered the ABO blood group system in 1901, explaining why some blood transfusions succeeded while others caused fatal reactions — a discovery that made blood transfusion a safe, reliable medical procedure for the first time, earning Landsteiner the 1930 Nobel Prize in Physiology or Medicine.",
    value: "1901",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Landsteiner's original published research, recognized by the Nobel Committee.",
    source: { title: "Nobel Prize — Karl Landsteiner, Biographical", url: "https://www.nobelprize.org/prizes/medicine/1930/landsteiner/biographical/", date: "1901-01-01", location: "University of Vienna, Austria" },
  },
  {
    registryNumber: "LR-FIRST-ARTIFICIAL-HEART", slug: "first-permanent-artificial-heart-implant", title: "First permanent artificial heart implant",
    category: "Medicine & Physiology", subcategory: "Medical History", direction: "MINIMIZE",
    metricName: "Year of the first permanent artificial heart implantation in a human", unit: "year",
    formalStatement: "The year of the first implantation of a permanent (non-bridging) mechanical artificial heart in a human patient.",
    summary: "Barney Clark received the first permanent artificial heart, the Jarvik-7, on December 2, 1982, at the University of Utah — he survived 112 days connected to an external air compressor powering the device, a landmark demonstration that a mechanical heart could sustain human life, even though the technology at the time was far from a practical long-term solution.",
    value: "1982",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Documented surgical case at the University of Utah Medical Center, published in peer-reviewed medical literature.",
    source: { title: "University of Utah — Barney Clark and the Jarvik-7", url: "https://healthcare.utah.edu/", date: "1982-12-02", location: "University of Utah Medical Center, Salt Lake City, USA" },
  },

  // --- Economics, continued ---
  {
    registryNumber: "LR-FIRST-INSURANCE-MARKET", slug: "first-insurance-market", title: "First organized insurance market",
    category: "Economics", subcategory: "History of Finance", direction: "MINIMIZE",
    metricName: "Year the first organized marine insurance market was established", unit: "year",
    formalStatement: "The year the first organized marketplace for underwriting insurance was established.",
    summary: "Lloyd's of London traces its origins to 1688, when merchants, ship owners, and underwriters gathered at Edward Lloyd's coffee house in London to arrange marine insurance for shipping voyages — evolving into the world's first organized insurance market and eventually the modern Lloyd's insurance and reinsurance marketplace.",
    value: "1688",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Historical records maintained by Lloyd's of London.",
    source: { title: "Lloyd's of London — Our History", url: "https://www.lloyds.com/about-lloyds/history", date: "1688-01-01", location: "London, England" },
  },
  {
    registryNumber: "LR-FIRST-CREDIT-RATING-AGENCY", slug: "first-credit-rating-agency", title: "First bond credit rating agency",
    category: "Economics", subcategory: "History of Finance", direction: "MINIMIZE",
    metricName: "Year the first modern bond credit rating agency was established", unit: "year",
    formalStatement: "The year the first agency to publish standardized letter-grade credit ratings for bonds was established.",
    summary: "John Moody founded Moody's in 1909, publishing the first standardized letter-grade credit ratings for railroad bonds — introducing the now-familiar AAA-to-D rating system that would later expand to cover corporate and government debt worldwide, becoming a central (and often controversial) institution in global financial markets.",
    value: "1909",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Historical corporate records maintained by Moody's Corporation.",
    source: { title: "Moody's — Our History", url: "https://www.moodys.com/", date: "1909-01-01", location: "New York, USA" },
  },
  {
    registryNumber: "LR-EARLIEST-GOVERNMENT-BOND", slug: "earliest-known-government-bond", title: "Earliest known government bond",
    category: "Economics", subcategory: "History of Finance", direction: "MINIMIZE",
    metricName: "Approximate year of the earliest known government debt instrument resembling a modern bond", unit: "year",
    formalStatement: "The approximate year of the earliest known government-issued debt instrument functioning similarly to a modern bond.",
    summary: "The Republic of Venice issued 'prestiti' — forced loans from wealthy citizens that paid regular interest and could be traded among investors — starting around 1171 CE, making them among the earliest known government bonds, centuries before the more commonly cited Bank of England annuities of 1693.",
    value: "1171",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Historical Venetian civic financial records, studied by economic historians.",
    source: { title: "Sidney Homer & Richard Sylla, \"A History of Interest Rates,\" Wiley (2005)", url: "https://www.wiley.com/", date: "2005-01-01", location: "Republic of Venice" },
  },

  // --- Sports Records, continued ---
  {
    registryNumber: "LR-LONGEST-NBA-WIN-STREAK", slug: "longest-winning-streak-major-north-american-pro-sports", title: "Longest winning streak in major North American professional sports",
    category: "Sports Records", subcategory: "Basketball", direction: "MAXIMIZE",
    metricName: "Longest consecutive winning streak by a team in a major North American professional sports league", unit: "games",
    formalStatement: "The greatest number of consecutive games won by a single team in any major North American professional sports league, within a single season or across seasons.",
    summary: "The Los Angeles Lakers won 33 consecutive games during the 1971-72 NBA season — still the longest winning streak in the history of any major North American professional sports league (NBA, NFL, MLB, or NHL), a record that has stood for over five decades.",
    value: "33",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official NBA game records.",
    source: { title: "NBA.com — Lakers' 33-game winning streak", url: "https://www.nba.com/history/", date: "1972-01-09", location: "1971-72 NBA season" },
  },
  {
    registryNumber: "LR-MOST-WINTER-OLYMPIC-MEDALS", slug: "most-winter-olympic-medals", title: "Most Winter Olympic medals won by an individual",
    category: "Sports Records", subcategory: "Olympics", direction: "MAXIMIZE",
    metricName: "Career Winter Olympic medals won by a single athlete", unit: "medals",
    formalStatement: "The greatest number of Winter Olympic medals (of any color) won across a career by a single athlete.",
    summary: "Norwegian cross-country skier Marit Bjørgen won 15 Winter Olympic medals across her career (2002-2018), including 8 golds — the most Winter Olympic medals of any athlete in history, male or female.",
    value: "15",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official medal records maintained by the International Olympic Committee.",
    source: { title: "Olympics.com — Marit Bjørgen", url: "https://www.olympics.com/en/athletes/marit-bjoergen", date: "2018-02-25", location: "Winter Olympic Games, 2002-2018" },
  },

  // --- Space Exploration, final additions ---
  {
    registryNumber: "LR-FIRST-GPS-SATELLITE", slug: "first-gps-satellite-launched", title: "First GPS satellite launched",
    category: "Space Exploration", subcategory: "Satellite Technology", direction: "MINIMIZE",
    metricName: "Year the first Global Positioning System satellite was launched", unit: "year",
    formalStatement: "The year the first satellite of what became the Global Positioning System (GPS) was launched.",
    summary: "The U.S. Air Force launched Navigation Technology Satellite 2 (part of the program that became GPS) in 1977, with the first dedicated Navstar GPS satellite following in February 1978 — the beginning of the satellite navigation constellation that today underlies navigation, timing, and positioning for billions of devices worldwide, originally developed for military use before being opened to civilian applications.",
    value: "1978",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "U.S. Department of Defense and Air Force Space Command historical launch records.",
    source: { title: "GPS.gov — GPS History", url: "https://www.gps.gov/systems/gps/history/", date: "1978-02-22", location: "Vandenberg Air Force Base, California, USA" },
  },
  {
    registryNumber: "LR-LARGEST-KNOWN-ASTEROID", slug: "largest-known-asteroid", title: "Largest known asteroid",
    category: "Space Exploration", subcategory: "Robotic Exploration", direction: "MAXIMIZE",
    metricName: "Diameter of the largest known asteroid in the asteroid belt", unit: "km",
    formalStatement: "The greatest diameter of any known object in the asteroid belt, whether classified as an asteroid or dwarf planet.",
    summary: "Ceres, with a diameter of approximately 940 km, is the largest known object in the asteroid belt between Mars and Jupiter — first discovered in 1801 and originally classified as a planet, then an asteroid, and since 2006 reclassified as a dwarf planet, though it remains by far the largest body in the asteroid belt regardless of category.",
    value: "940",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Direct imaging by NASA's Dawn spacecraft, which orbited Ceres from 2015 to 2018.",
    source: { title: "NASA — Ceres Facts", url: "https://solarsystem.nasa.gov/planets/dwarf-planets/ceres/", date: "2015-03-06", location: "Asteroid belt, between Mars and Jupiter" },
  },
  {
    registryNumber: "LR-FIRST-COMET-LANDING", slug: "first-spacecraft-landing-on-a-comet", title: "First spacecraft landing on a comet",
    category: "Space Exploration", subcategory: "Robotic Exploration", direction: "MINIMIZE",
    metricName: "Year of the first successful spacecraft landing on a comet", unit: "year",
    formalStatement: "The year of the first successful controlled landing of a spacecraft on a comet's surface.",
    summary: "The European Space Agency's Philae lander, deployed from the Rosetta spacecraft, achieved the first controlled landing on a comet on November 12, 2014, touching down on Comet 67P/Churyumov-Gerasimenko — though its anchoring harpoons failed to fire, causing it to bounce before settling in a shadowed location that limited its solar power, it still returned the first-ever images and data from a comet's surface.",
    value: "2014",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "European Space Agency mission telemetry from the Rosetta orbiter and Philae lander.",
    source: { title: "European Space Agency — Rosetta and Philae", url: "https://www.esa.int/Science_Exploration/Space_Science/Rosetta", date: "2014-11-12", location: "Comet 67P/Churyumov-Gerasimenko" },
  },
  {
    registryNumber: "LR-FIRST-SPACECRAFT-ORBIT-ANOTHER-PLANET", slug: "first-spacecraft-to-orbit-another-planet", title: "First spacecraft to orbit another planet",
    category: "Space Exploration", subcategory: "Robotic Exploration", direction: "MINIMIZE",
    metricName: "Year of the first successful insertion of a spacecraft into orbit around another planet", unit: "year",
    formalStatement: "The year of the first successful insertion of a human-made spacecraft into orbit around a planet other than Earth.",
    summary: "NASA's Mariner 9 became the first spacecraft to orbit another planet when it entered orbit around Mars on November 14, 1971 — arriving during a global Martian dust storm that initially obscured the surface, it went on to map the entire planet in detail, discovering Olympus Mons (the solar system's largest volcano) and the Valles Marineris canyon system.",
    value: "1971",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "NASA Jet Propulsion Laboratory mission telemetry.",
    source: { title: "NASA JPL — Mariner 9", url: "https://www.jpl.nasa.gov/missions/mariner-9", date: "1971-11-14", location: "Mars orbit" },
  },

  // --- Geography, final additions ---
  {
    registryNumber: "LR-FIRST-RECORDED-ROGUE-WAVE", slug: "first-scientifically-recorded-rogue-wave", title: "First scientifically recorded rogue wave",
    category: "Geography", subcategory: "Oceanography", direction: "MINIMIZE",
    metricName: "Year the first rogue wave was directly measured by scientific instruments", unit: "year",
    formalStatement: "The year the first oceanic rogue wave (an unusually large, unpredicted wave) was directly measured by scientific instruments, confirming a phenomenon sailors had long reported but scientists had doubted.",
    summary: "The Draupner wave, measured by a laser sensor on the Draupner oil platform in the North Sea on January 1, 1995, reached a height of 25.6 m — nearly three times the height of surrounding waves — the first scientifically measured confirmation that rogue waves are real, ending decades of scientific skepticism about sailors' reports of freak ocean waves.",
    value: "1995",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Laser-based wave height sensor on the Draupner platform, published in a peer-reviewed oceanography study.",
    source: { title: "Haver, \"A possible freak wave event measured at the Draupner Jacket January 1 1995,\" Rogue Waves 2004", url: "https://www.ifremer.fr/", date: "1995-01-01", location: "Draupner platform, North Sea" },
  },
  {
    registryNumber: "LR-LARGEST-IMPACT-CRATER-LAKE", slug: "largest-impact-crater-lake", title: "Largest impact crater lake",
    category: "Geography", subcategory: "Geology", direction: "MAXIMIZE",
    metricName: "Diameter of the largest lake formed within an impact crater", unit: "km",
    formalStatement: "The greatest diameter of any lake formed within a confirmed asteroid or comet impact crater.",
    summary: "The Manicouagan Reservoir in Quebec, Canada, forms a distinctive ring shape within an impact crater approximately 100 km in diameter, created by an asteroid impact around 214 million years ago — one of the largest and best-preserved impact crater lakes on Earth, clearly visible from space as a giant circular 'eye.'",
    value: "100",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Geological survey and radiometric dating of shock-metamorphosed rock, published in peer-reviewed geology literature.",
    source: { title: "Natural Resources Canada — Manicouagan Crater", url: "https://www.rncan.gc.ca/", date: "2015-01-01", location: "Quebec, Canada" },
  },
  {
    registryNumber: "LR-LONGEST-RAILWAY-LINE", slug: "longest-railway-line", title: "Longest single railway line",
    category: "Geography", subcategory: "Human Geography", direction: "MAXIMIZE",
    metricName: "Total length of the longest single continuous railway line", unit: "km",
    formalStatement: "The greatest total length of any single continuous railway line.",
    summary: "The Trans-Siberian Railway, connecting Moscow to Vladivostok, stretches approximately 9,289 km — the longest railway line in the world, crossing eight time zones and taking about a week to traverse end to end.",
    value: "9289",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official route specifications published by Russian Railways.",
    source: { title: "Russian Railways — Trans-Siberian Railway", url: "https://eng.rzd.ru/", date: "1916-01-01", location: "Russia" },
  },
  {
    registryNumber: "LR-HIGHEST-RAILWAY-POINT", slug: "highest-point-on-any-railway", title: "Highest point on any railway",
    category: "Geography", subcategory: "Human Geography", direction: "MAXIMIZE",
    metricName: "Elevation of the highest point reached by any railway track", unit: "m",
    formalStatement: "The greatest elevation above sea level reached by any railway track.",
    summary: "The Qinghai-Tibet Railway in China reaches an elevation of 5,072 m at the Tanggula Pass — the highest point on any railway in the world, requiring specially pressurized passenger cars (similar to an aircraft cabin) to protect travelers from the effects of high-altitude oxygen deprivation.",
    value: "5072",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Engineering specification published by China Railway, the line's operator.",
    source: { title: "China Railway — Qinghai-Tibet Railway", url: "http://www.china-railway.com.cn/", date: "2006-07-01", location: "Tanggula Pass, Tibet, China" },
  },

  // --- Engineering, final additions ---
  {
    registryNumber: "LR-FIRST-NUCLEAR-SUBMARINE", slug: "first-nuclear-powered-submarine", title: "First nuclear-powered submarine",
    category: "Engineering", subcategory: "Naval Engineering", direction: "MINIMIZE",
    metricName: "Year the first nuclear-powered submarine was commissioned", unit: "year",
    formalStatement: "The year the first nuclear-powered submarine was commissioned into naval service.",
    summary: "USS Nautilus, commissioned by the U.S. Navy in 1954, was the first nuclear-powered submarine — able to remain submerged for weeks at a time rather than the hours or days limited by earlier diesel-electric submarines' battery capacity, and in 1958 became the first vessel to cross the North Pole while submerged.",
    value: "1954",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "U.S. Navy commissioning records.",
    source: { title: "U.S. Naval History and Heritage Command — USS Nautilus", url: "https://www.history.navy.mil/", date: "1954-09-30", location: "Groton, Connecticut, USA" },
  },
  {
    registryNumber: "LR-LARGEST-WIND-TUNNEL", slug: "largest-wind-tunnel", title: "Largest wind tunnel",
    category: "Engineering", subcategory: "Aerospace Engineering", direction: "MAXIMIZE",
    metricName: "Test section size of the largest wind tunnel", unit: "m²",
    formalStatement: "The greatest test section cross-sectional area of any operational wind tunnel.",
    summary: "The National Full-Scale Aerodynamics Complex at NASA Ames Research Center has a test section measuring 40 ft by 80 ft (approximately 297 m²) — the largest wind tunnel in the world, large enough to test full-scale aircraft rather than scale models.",
    value: "297",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Engineering specification published by NASA Ames Research Center.",
    source: { title: "NASA Ames Research Center — National Full-Scale Aerodynamics Complex", url: "https://www.nasa.gov/ames/", date: "1987-01-01", location: "Moffett Field, California, USA" },
  },
  {
    registryNumber: "LR-FIRST-MODERN-CABLE-STAYED-BRIDGE", slug: "first-modern-cable-stayed-bridge", title: "First modern cable-stayed bridge",
    category: "Engineering", subcategory: "History", direction: "MINIMIZE",
    metricName: "Year the first modern cable-stayed bridge was completed", unit: "year",
    formalStatement: "The year the first cable-stayed bridge of the modern engineering type (using steel cables running directly from deck to tower) was completed.",
    summary: "The Strömsund Bridge in Sweden, completed in 1955 and designed by German engineer Franz Dischinger, is generally credited as the first modern cable-stayed bridge — a structural type that has since become common worldwide for medium-to-long-span bridges, offering a lighter, often more economical alternative to suspension bridges.",
    value: "1955",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Structural engineering historical records.",
    source: { title: "Structurae — Strömsund Bridge", url: "https://structurae.net/en/structures/stromsund-bridge", date: "1955-01-01", location: "Strömsund, Sweden" },
  },
  {
    registryNumber: "LR-FIRST-NUCLEAR-AIRCRAFT-CARRIER", slug: "first-nuclear-powered-aircraft-carrier", title: "First nuclear-powered aircraft carrier",
    category: "Engineering", subcategory: "Naval Engineering", direction: "MINIMIZE",
    metricName: "Year the first nuclear-powered aircraft carrier was commissioned", unit: "year",
    formalStatement: "The year the first nuclear-powered aircraft carrier was commissioned into naval service.",
    summary: "USS Enterprise, commissioned by the U.S. Navy in 1961, was the first nuclear-powered aircraft carrier — powered by eight nuclear reactors and able to operate for years without refueling, it served for 51 years before being decommissioned in 2012, the longest active service of any U.S. Navy vessel of its kind.",
    value: "1961",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "U.S. Navy commissioning records.",
    source: { title: "U.S. Naval History and Heritage Command — USS Enterprise (CVN-65)", url: "https://www.history.navy.mil/", date: "1961-11-25", location: "Newport News, Virginia, USA" },
  },

  // --- Food & Culture, final additions ---
  {
    registryNumber: "LR-FIRST-SYNCHRONIZED-SOUND-FILM", slug: "first-film-with-synchronized-sound", title: "First feature film with synchronized sound",
    category: "Food & Culture", subcategory: "Film", direction: "MINIMIZE",
    metricName: "Year of release of the first commercially successful feature film with synchronized sound dialogue", unit: "year",
    formalStatement: "The year of release of the first commercially successful feature-length film incorporating synchronized sound dialogue, marking the transition from silent film.",
    summary: "'The Jazz Singer,' released October 6, 1927, was the first feature film to include synchronized sound dialogue as part of its story (earlier films had used synchronized music or effects) — its commercial success rapidly accelerated the film industry's transition away from silent films, effectively ending the silent film era within just a few years.",
    value: "1927",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Film industry historical records maintained by the American Film Institute.",
    source: { title: "American Film Institute — The Jazz Singer", url: "https://catalog.afi.com/", date: "1927-10-06", location: "United States" },
  },
  {
    registryNumber: "LR-FIRST-VIDEO-GAME-CONSOLE", slug: "first-commercial-video-game-console", title: "First commercial home video game console",
    category: "Food & Culture", subcategory: "Digital Culture", direction: "MINIMIZE",
    metricName: "Year the first commercially released home video game console was launched", unit: "year",
    formalStatement: "The year the first commercially released home video game console became available for purchase.",
    summary: "The Magnavox Odyssey, released in 1972, was the first commercial home video game console — it played simple games using plastic overlays placed on the television screen to simulate graphics the console's simple hardware couldn't generate, predating Atari's Pong (also 1972, first as an arcade game) by several months.",
    value: "1972",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Video game industry historical records maintained by The Strong National Museum of Play.",
    source: { title: "The Strong National Museum of Play — Magnavox Odyssey", url: "https://www.museumofplay.org/", date: "1972-08-01", location: "United States" },
  },
  {
    registryNumber: "LR-OLDEST-CONTINUOUS-CARNIVAL", slug: "oldest-continuously-held-carnival", title: "Oldest continuously held carnival",
    category: "Food & Culture", subcategory: "Cultural Traditions", direction: "MINIMIZE",
    metricName: "Year of the first recorded celebration of the oldest continuously held annual carnival", unit: "year",
    formalStatement: "The year of the first recorded celebration of the oldest carnival tradition still held annually today.",
    summary: "The Venice Carnival traces documented references back to 1162, when the Venetian Senate declared a public celebration to mark a military victory — making it among the oldest continuously referenced carnival traditions in the world, though its modern annual form as an elaborate masked festival developed more fully over subsequent centuries.",
    value: "1162",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Historical Venetian civic records; the exact continuity of the tradition across the following 863 years, including periods of suppression, is difficult to fully document.",
    source: { title: "Venice Carnival — Official History", url: "https://www.carnevale.venezia.it/en/", date: "1162-01-01", location: "Venice, Republic of Venice (modern-day Italy)" },
  },
  {
    registryNumber: "LR-MOST-TRANSLATED-DOCUMENT", slug: "most-translated-document-in-the-world", title: "Most translated document in the world",
    category: "Food & Culture", subcategory: "Records", direction: "MAXIMIZE",
    metricName: "Number of languages the most translated document has been translated into", unit: "languages",
    formalStatement: "The greatest number of distinct languages any single document has been officially translated into.",
    summary: "The Universal Declaration of Human Rights, adopted by the United Nations General Assembly in 1948, has been translated into over 500 languages — certified by Guinness World Records as the most translated document in the world, reflecting its status as a foundational (though non-binding) statement of international human rights norms.",
    value: "500",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Translation count maintained by the Office of the United Nations High Commissioner for Human Rights, certified by Guinness World Records.",
    source: { title: "Guinness World Records — Most translated document", url: "https://www.guinnessworldrecords.com/world-records/most-translations-of-a-document", date: "2009-01-01", location: "United Nations" },
  },

  // --- History, final additions ---
  {
    registryNumber: "LR-FIRST-KNOWN-USE-OF-GUNPOWDER", slug: "first-known-use-of-gunpowder", title: "First known use of gunpowder",
    category: "History", subcategory: "Invention History", direction: "MINIMIZE",
    metricName: "Approximate century gunpowder was first developed", unit: "year",
    formalStatement: "The approximate century in which gunpowder was first developed, according to the earliest surviving written formulas.",
    summary: "Chinese alchemists, seeking an elixir of immortality, are believed to have accidentally developed gunpowder sometime around the 9th century CE, with the earliest surviving written formula appearing in a military text dated to 1044 CE — initially used for fireworks and signaling before its military applications (rockets, then firearms) were developed over subsequent centuries.",
    value: "850",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Historical Chinese Taoist alchemical texts and the later Wujing Zongyao military compendium (1044 CE); the exact earliest date of discovery predates the surviving written formula and is not precisely known.",
    source: { title: "Needham, \"Science and Civilisation in China,\" Cambridge University Press", url: "https://www.cambridge.org/", date: "1986-01-01", location: "Tang Dynasty China" },
  },
  {
    registryNumber: "LR-OLDEST-MARITIME-LAW-CODE", slug: "oldest-known-maritime-law-code", title: "Oldest known maritime law code",
    category: "History", subcategory: "Ancient History", direction: "MINIMIZE",
    metricName: "Approximate age of the oldest known codified maritime law", unit: "years old",
    formalStatement: "The approximate age of the oldest known codified system of maritime (sea) law.",
    summary: "The Rhodian Sea Law, developed by the maritime trading state of Rhodes in the ancient Greek world around 800-600 BCE, is the earliest known codified system of maritime law, establishing principles like 'general average' (shared loss compensation when cargo is jettisoned to save a ship) that remain foundational to maritime law today, over 2,600 years later.",
    value: "2600",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "References to Rhodian maritime law preserved in later Roman legal texts (the Digest of Justinian); no complete original Rhodian text survives.",
    source: { title: "Yale Law School Avalon Project — Rhodian Sea Law", url: "https://avalon.law.yale.edu/", date: "2008-01-01", location: "Rhodes, ancient Greece" },
  },
  {
    registryNumber: "LR-FIRST-ECLIPSE-PREDICTION", slug: "first-recorded-eclipse-prediction", title: "First recorded prediction of a solar eclipse",
    category: "History", subcategory: "Ancient History", direction: "MINIMIZE",
    metricName: "Year of the earliest solar eclipse traditionally credited as successfully predicted in advance", unit: "year BCE",
    formalStatement: "The year of the earliest solar eclipse traditionally credited to a named individual as having been predicted in advance, per ancient historical accounts.",
    summary: "The Greek philosopher Thales of Miletus is traditionally credited with predicting a solar eclipse that occurred in 585 BCE, famously said to have interrupted a battle between the Lydians and the Medes, who took the sudden darkness as a divine sign to make peace — though modern historians debate whether Thales genuinely predicted the eclipse's timing or simply knew from Babylonian records that eclipses recurred periodically in that region.",
    value: "585",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "The story survives only through later ancient historians (notably Herodotus, writing over a century after the event), so its precise accuracy cannot be independently verified.",
    source: { title: "NASA Eclipse Web Site — Historical Eclipses", url: "https://eclipse.gsfc.nasa.gov/", date: "2005-01-01", location: "Asia Minor (modern-day Turkey)" },
  },
  {
    registryNumber: "LR-FIRST-MUTUAL-FUND", slug: "first-open-end-mutual-fund", title: "First open-end mutual fund",
    category: "Economics", subcategory: "History of Finance", direction: "MINIMIZE",
    metricName: "Year the first open-end mutual fund was established in the United States", unit: "year",
    formalStatement: "The year the first open-end mutual fund (a pooled investment fund that continuously issues and redeems shares) was established in the United States.",
    summary: "The Massachusetts Investors Trust, established in Boston in 1924, was the first open-end mutual fund in the United States — allowing ordinary investors to buy into a professionally managed, diversified portfolio and redeem their shares at any time, a structure that would go on to become the dominant form of retail investing worldwide.",
    value: "1924",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Historical financial industry records maintained by the Investment Company Institute.",
    source: { title: "Investment Company Institute — History of Mutual Funds", url: "https://www.ici.org/", date: "1924-03-21", location: "Boston, Massachusetts, USA" },
  },

  // --- Sports Records, final additions ---
  {
    registryNumber: "LR-MOST-PGA-TOUR-WINS", slug: "most-pga-tour-wins-career", title: "Most PGA Tour wins, career",
    category: "Sports Records", subcategory: "Golf", direction: "MAXIMIZE",
    metricName: "Career PGA Tour victories", unit: "wins",
    formalStatement: "The greatest number of official PGA Tour event victories won across a career.",
    summary: "Sam Snead won 82 official PGA Tour events across his career (1936-1965) — a record that stood alone for over five decades until Tiger Woods matched it in 2019 with his own 82nd career win, making the two golfers tied for the most PGA Tour wins in history.",
    value: "82",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official career statistics maintained by the PGA Tour.",
    source: { title: "PGA Tour — All-Time Career Wins Leaders", url: "https://www.pgatour.com/", date: "2019-09-15", location: "PGA Tour, USA" },
  },
  {
    registryNumber: "LR-MOST-OLYMPIC-GAMES-HOSTED-CITY", slug: "city-that-has-hosted-the-most-olympic-games", title: "City that has hosted the most Olympic Games",
    category: "Sports Records", subcategory: "Olympics", direction: "MAXIMIZE",
    metricName: "Number of times a single city has hosted the Olympic Games", unit: "times",
    formalStatement: "The greatest number of times any single city has hosted the Olympic Games (Summer or Winter).",
    summary: "London has hosted the Summer Olympic Games three times — in 1908, 1948, and 2012 — more than any other city in the world, a distinction unlikely to be matched soon given the decades-long gaps typically required between a city's turns hosting.",
    value: "3",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official hosting records maintained by the International Olympic Committee.",
    source: { title: "International Olympic Committee — Host City Election", url: "https://olympics.com/ioc/", date: "2012-08-12", location: "London, United Kingdom" },
  },

  // --- Medicine & Physiology, final addition ---
  {
    registryNumber: "LR-FIRST-PANCREAS-TRANSPLANT", slug: "first-successful-pancreas-transplant", title: "First successful pancreas transplant",
    category: "Medicine & Physiology", subcategory: "Medical History", direction: "MINIMIZE",
    metricName: "Year of the first pancreas transplant performed in a human", unit: "year",
    formalStatement: "The year of the first pancreas transplant performed in a human patient.",
    summary: "Surgeons William Kelly and Richard Lillehei performed the first pancreas transplant at the University of Minnesota in 1966, in a patient with diabetes and kidney failure — an early and technically difficult milestone in transplant surgery that, after decades of refinement, became a viable treatment option for patients with severe type 1 diabetes.",
    value: "1966",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Documented surgical case published in peer-reviewed surgical literature.",
    source: { title: "University of Minnesota — History of Transplantation", url: "https://med.umn.edu/", date: "1966-12-17", location: "University of Minnesota, Minneapolis, USA" },
  },
];
