import type { FrontierRecord } from "./frontier-records-2026";

// Eighth real-world-records batch — Astrophysics (incl. Space Exploration), Earth & Climate, and
// Geography. Checked against the existing catalog (all prior batches + frontier-records-2026 +
// science-frontiers) to avoid re-covering an already-published topic; several planned entries
// (Kola Superdeep Borehole, Lake Baikal by volume, Greenland as largest island, most-neighbors
// country, Dead Sea elevation, deepest cave, largest coral reef/rainforest/peninsula/salt flat/
// meteorite/impact-crater/iceberg, tallest waterfall, longest coastline/border, longest lightning
// flash, rogue wave, driest place, Mid-Ocean Ridge, Ganges delta, largest desert locust swarm)
// were dropped after grep-checking prior batches turned up an existing entry on the same fact.
// Ancient/prehistoric events (e.g. the Toba supereruption) cite the dating study's publication
// date in `source.date` rather than an unrepresentable prehistoric calendar date.
export const WORLD_RECORDS_BATCH8_SPACE_GEO: FrontierRecord[] = [
  // --- Astrophysics: Stellar & Compact Objects ---
  {
    registryNumber: "LR-FASTEST-SPINNING-PULSAR", slug: "fastest-spinning-pulsar-known", title: "Fastest-spinning pulsar known",
    category: "Astrophysics", subcategory: "Stellar Astrophysics", direction: "MAXIMIZE",
    metricName: "Rotation frequency of a known pulsar", unit: "Hz",
    formalStatement: "The highest confirmed rotation rate of any known pulsar, in complete rotations per second.",
    summary: "PSR J1748-2446ad, a millisecond pulsar in the globular cluster Terzan 5, spins at 716 rotations per second (about 43,000 rpm) — the fastest rotation rate confirmed for any pulsar, found with the Green Bank Telescope in 2004 and confirmed in 2006. At its equator the neutron star's surface is estimated to be moving at roughly a quarter of the speed of light.",
    value: "716",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Radio pulse-timing observations with the NRAO Green Bank Telescope, confirmed through peer-reviewed timing analysis.",
    source: { title: "Hessels et al., \"A Radio Pulsar Spinning at 716 Hz,\" Science", url: "https://www.science.org/doi/10.1126/science.1123430", date: "2006-03-31", location: "Terzan 5 globular cluster, observed from NRAO Green Bank, USA" },
  },
  {
    registryNumber: "LR-LARGEST-STAR-RADIUS", slug: "largest-known-star-by-radius", title: "Largest known star by radius",
    category: "Astrophysics", subcategory: "Stellar Astrophysics", direction: "MAXIMIZE",
    metricName: "Estimated radius of the largest known star", unit: "solar radii",
    formalStatement: "The largest stellar radius estimated for any currently known star, in multiples of the Sun's radius, based on luminosity and temperature modeling.",
    summary: "Stephenson 2-18, a red hypergiant roughly 20,000 light-years away in the Stephenson 2 cluster, has a commonly cited estimated radius of around 2,150 times the Sun's — large enough that, placed at the Sun's position, its surface would reach past Saturn's orbit. The exact figure is genuinely disputed and highly sensitive to the assumed distance and luminosity; UY Scuti (estimates spanning roughly 1,000-1,700 solar radii) is a frequently cited rival, and neither star has the direct interferometric size measurement available for closer, smaller stars.",
    value: "2150",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Radius inferred from luminosity and effective temperature via the Stefan-Boltzmann relation using photometric and spectroscopic survey data; not directly resolved by interferometry.",
    source: { title: "SIMBAD Astronomical Database — Stephenson 2-18 (entry and literature radius estimates)", url: "https://simbad.cds.unistra.fr/simbad/sim-basic?Ident=Stephenson+2-18", date: "2021-01-01", location: "Centre de Données astronomiques de Strasbourg (CDS), France" },
  },
  {
    registryNumber: "LR-FASTEST-HYPERVELOCITY-STAR", slug: "fastest-hypervelocity-star-known", title: "Fastest hypervelocity star known",
    category: "Astrophysics", subcategory: "Stellar Astrophysics", direction: "MAXIMIZE",
    metricName: "Galactic-rest-frame speed of the fastest known unbound star", unit: "km/s",
    formalStatement: "The greatest speed relative to the Galactic rest frame confirmed for any star that is gravitationally unbound from the Milky Way.",
    summary: "S5-HVS1, an A-type star discovered in 2019 by the Southern Stellar Stream Spectroscopic Survey, is moving at roughly 1,755 km/s — fast enough to escape the Milky Way entirely — and is believed to have been ejected by a close encounter with the supermassive black hole Sagittarius A* around 5 million years ago. It remains the fastest star known with a well-constrained trajectory back to that origin.",
    value: "1755",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Radial velocity and proper motion measured via the Anglo-Australian Telescope and Gaia astrometry, published in a peer-reviewed study (Koposov et al. 2020).",
    source: { title: "Koposov et al., \"Discovery of a nearby 1700 km/s star ejected from the Milky Way,\" MNRAS", url: "https://academic.oup.com/mnras/article/491/2/2465/5626058", date: "2020-01-01", location: "Southern Stellar Stream Spectroscopic Survey (S5)" },
  },
  {
    registryNumber: "LR-CLOSEST-BLACK-HOLE-EARTH", slug: "closest-known-black-hole-to-earth", title: "Closest known black hole to Earth",
    category: "Astrophysics", subcategory: "Black Holes", direction: "MINIMIZE",
    metricName: "Distance from Earth to the nearest confirmed stellar-mass black hole", unit: "ly",
    formalStatement: "The shortest confirmed distance between Earth and any known stellar-mass black hole.",
    summary: "Gaia BH1, discovered in 2022 using precise astrometric wobble data from the Gaia spacecraft, is a roughly 10-solar-mass black hole in a binary system about 1,560 light-years away in the constellation Ophiuchus — the closest confirmed black hole to Earth. Unlike most known stellar-mass black holes, it was found through its gravitational tug on a Sun-like companion star rather than through X-ray emission.",
    value: "1560",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Astrometric binary-orbit solution from Gaia satellite data, confirmed with ground-based spectroscopic follow-up (El-Badry et al. 2022).",
    source: { title: "El-Badry et al., \"A Sun-like star orbiting a black hole,\" MNRAS", url: "https://academic.oup.com/mnras/article/518/2/1057/6805401", date: "2022-11-01", location: "Gaia mission astrometry, ESA" },
  },
  {
    registryNumber: "LR-FIRST-CONFIRMED-BROWN-DWARF", slug: "first-confirmed-brown-dwarf", title: "First confirmed brown dwarf",
    category: "Astrophysics", subcategory: "Stellar Astrophysics", direction: "MINIMIZE",
    metricName: "Year of the first confirmed detection of a brown dwarf", unit: "year",
    formalStatement: "The year a substellar object was first confirmed to be a genuine brown dwarf (too massive to be a planet, too low-mass to sustain hydrogen fusion).",
    summary: "Teide 1, found in the Pleiades cluster, was confirmed in 1995 as the first bona fide brown dwarf — a substellar object with a mass below the roughly 0.08 solar-mass threshold needed to sustain ordinary hydrogen fusion, resolving a decade of unconfirmed brown-dwarf candidates. It was identified using the Spanish Nordic Optical Telescope.",
    value: "1995",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Spectroscopic detection of lithium absorption (a marker that rules out ordinary low-mass stars) combined with luminosity and color measurements, published in Nature (Rebolo, Zapatero Osorio & Martín, 1995).",
    source: { title: "Rebolo, Zapatero Osorio & Martín, \"Discovery of a brown dwarf in the Pleiades star cluster,\" Nature", url: "https://www.nature.com/articles/377129a0", date: "1995-09-14", location: "Instituto de Astrofísica de Canarias, Spain" },
  },

  // --- Astrophysics: Gravitational-Wave & Multi-Messenger Astronomy ---
  {
    registryNumber: "LR-FIRST-MULTIMESSENGER-NS-MERGER", slug: "first-multimessenger-neutron-star-merger", title: "First multi-messenger observation of a neutron star merger",
    category: "Astrophysics", subcategory: "Gravitational-Wave Astronomy", direction: "MINIMIZE",
    metricName: "Year of the first joint gravitational-wave and electromagnetic detection of a neutron star merger", unit: "year",
    formalStatement: "The year a single astrophysical event was first observed both in gravitational waves and across the electromagnetic spectrum.",
    summary: "GW170817, detected on August 17, 2017 by LIGO and Virgo, was the first observed merger of two neutron stars — and, within about two seconds, was matched to a gamma-ray burst and then to weeks of follow-up observations across radio, optical, X-ray, and gamma-ray telescopes worldwide. It remains the only gravitational-wave event to date with a confirmed electromagnetic counterpart, and directly confirmed neutron-star mergers as a site of heavy-element (r-process) nucleosynthesis.",
    value: "2017",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Coincident gravitational-wave strain detection (LIGO/Virgo) matched in time and sky position to a short gamma-ray burst (Fermi/INTEGRAL) and a subsequent optical/infrared kilonova, coordinated across dozens of observatories.",
    source: { title: "Abbott et al., \"Multi-messenger Observations of a Binary Neutron Star Merger,\" The Astrophysical Journal Letters", url: "https://iopscience.iop.org/article/10.3847/2041-8213/aa91c9", date: "2017-10-16", location: "LIGO/Virgo Collaboration, worldwide follow-up network" },
  },
  {
    registryNumber: "LR-MOST-MASSIVE-BLACK-HOLE-MERGER", slug: "most-massive-black-hole-merger-detected", title: "Most massive black hole merger detected by gravitational waves",
    category: "Astrophysics", subcategory: "Gravitational-Wave Astronomy", direction: "MAXIMIZE",
    metricName: "Mass of the merger remnant produced by a gravitational-wave-detected black hole merger", unit: "solar masses",
    formalStatement: "The greatest final remnant mass produced by any black hole merger event confirmed through gravitational-wave detection.",
    summary: "GW190521, detected by LIGO and Virgo on May 21, 2019, resulted from the merger of two black holes of roughly 85 and 66 solar masses, producing a remnant of about 142 solar masses — the most massive black hole merger observed via gravitational waves, and the first confirmed direct detection of an intermediate-mass black hole (a class between stellar-mass and supermassive black holes). One of the progenitor masses also falls inside the theoretical 'pair-instability supernova gap' where stars are not expected to leave black holes behind, making the event doubly notable.",
    value: "142",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Gravitational-wave strain signal matched to numerical-relativity merger templates by the LIGO/Virgo Collaboration, published in peer-reviewed papers in 2020.",
    source: { title: "Abbott et al., \"GW190521: A Binary Black Hole Merger with a Total Mass of 150 M⊙,\" Physical Review Letters", url: "https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.125.101102", date: "2020-09-02", location: "LIGO/Virgo Collaboration" },
  },
  {
    registryNumber: "LR-FIRST-FAST-RADIO-BURST-DETECTED", slug: "first-fast-radio-burst-detected", title: "First fast radio burst detected",
    category: "Astrophysics", subcategory: "Radio Astronomy", direction: "MINIMIZE",
    metricName: "Year of the first identified fast radio burst", unit: "year",
    formalStatement: "The year the first fast radio burst (a millisecond-duration burst of radio emission from an astrophysical source, usually beyond the Milky Way) was identified in archival data.",
    summary: "The 'Lorimer Burst,' a bright millisecond-duration radio pulse, was found in 2007 by Duncan Lorimer's team while re-examining 2001 Parkes Observatory pulsar-survey data — the first recognized fast radio burst (FRB), a now-common but still not fully understood class of extragalactic radio transients. Thousands of FRBs have since been catalogued, most believed to originate from magnetars in distant galaxies.",
    value: "2007",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Archival re-analysis of Parkes radio telescope pulsar-survey data, published in a peer-reviewed paper (Lorimer et al., 2007).",
    source: { title: "Lorimer et al., \"A Bright Millisecond Radio Burst of Extragalactic Origin,\" Science", url: "https://www.science.org/doi/10.1126/science.1147532", date: "2007-09-27", location: "Parkes Observatory, Australia" },
  },

  // --- Astrophysics: Exoplanets ---
  {
    registryNumber: "LR-HOTTEST-KNOWN-EXOPLANET", slug: "hottest-known-exoplanet", title: "Hottest known exoplanet",
    category: "Astrophysics", subcategory: "Exoplanets", direction: "MAXIMIZE",
    metricName: "Measured dayside temperature of the hottest known exoplanet", unit: "K",
    formalStatement: "The highest measured dayside atmospheric temperature of any confirmed exoplanet.",
    summary: "KELT-9b, an ultra-hot Jupiter discovered in 2017 orbiting a bright A-type star, has a measured dayside temperature of about 4,600 K — hotter than most red dwarf and even some K-type stars, and hot enough to strip heavy metals like iron and titanium into an ionized gas in its atmosphere. It remains the hottest exoplanet with a directly measured temperature.",
    value: "4600",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Secondary-eclipse photometry and spectroscopy from ground- and space-based telescopes, published in peer-reviewed studies.",
    source: { title: "Gaudi et al., \"A giant planet undergoing extreme-ultraviolet irradiation by its hot massive-star host,\" Nature", url: "https://www.nature.com/articles/nature22392", date: "2017-06-05", location: "KELT survey; follow-up by multiple observatories" },
  },
  {
    registryNumber: "LR-MOST-PLANETS-SINGLE-SYSTEM", slug: "most-planets-confirmed-in-a-single-planetary-system", title: "Most planets confirmed in a single planetary system",
    category: "Astrophysics", subcategory: "Exoplanets", direction: "MAXIMIZE",
    metricName: "Number of confirmed planets orbiting a single star (excluding the Sun)", unit: "planets",
    formalStatement: "The greatest number of confirmed planets known to orbit a single star other than the Sun, as of the most recent discovery.",
    summary: "Kepler-90, a Sun-like star about 2,545 light-years away, has 8 confirmed planets — tying the count of planets in our own solar system. The eighth, Kepler-90i, was identified in December 2017 using a Google-developed neural network trained to spot faint transit signals in Kepler telescope data that earlier automated searches had missed. As of 2026 this remains the confirmed record, though ongoing surveys continue to find systems with many transiting planet candidates that may eventually be confirmed in greater numbers.",
    value: "8",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Transit-photometry detection from NASA's Kepler space telescope, with the eighth planet found via machine-learning-assisted reanalysis of the light-curve archive.",
    source: { title: "NASA — Artificial Intelligence, NASA Data Used to Discover Eighth Planet Circling Distant Star", url: "https://www.nasa.gov/solar-system/exoplanets/artificial-intelligence-nasa-data-used-to-discover-eighth-planet-circling-distant-star/", date: "2017-12-14", location: "Kepler space telescope archive" },
  },
  {
    registryNumber: "LR-FIRST-HABITABLE-ZONE-EARTH-SIZE-EXOPLANET", slug: "first-earth-size-exoplanet-in-a-habitable-zone", title: "First Earth-size exoplanet found in a star's habitable zone",
    category: "Astrophysics", subcategory: "Exoplanets", direction: "MINIMIZE",
    metricName: "Year of the first confirmed Earth-size exoplanet found orbiting within its star's habitable zone", unit: "year",
    formalStatement: "The year the first exoplanet close to Earth's size was confirmed to orbit within the habitable zone of its star, where liquid surface water could plausibly exist.",
    summary: "Kepler-186f, announced in 2014, was the first confirmed exoplanet close to Earth's size (about 1.1 Earth radii) found orbiting within the habitable zone of its star, a red dwarf roughly 580 light-years away. Whether it actually has liquid water, an atmosphere, or is otherwise habitable remains unknown — the record concerns its size and orbital position only.",
    value: "2014",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Transit photometry from NASA's Kepler space telescope, with follow-up validation ruling out false-positive scenarios, published in Science.",
    source: { title: "Quintana et al., \"An Earth-Sized Planet in the Habitable Zone of a Cool Star,\" Science", url: "https://www.science.org/doi/10.1126/science.1249403", date: "2014-04-17", location: "NASA Kepler space telescope" },
  },
  {
    registryNumber: "LR-FIRST-DIRECTLY-IMAGED-MULTIPLANET-SYSTEM", slug: "first-directly-imaged-multiplanet-system", title: "First directly imaged multi-planet system",
    category: "Astrophysics", subcategory: "Exoplanets", direction: "MINIMIZE",
    metricName: "Year of the first direct image showing multiple planets around a star other than the Sun", unit: "year",
    formalStatement: "The year the first system of multiple exoplanets orbiting another star was directly imaged in a single observation.",
    summary: "In 2008, ground-based telescopes at the Keck and Gemini observatories captured direct images of three giant planets orbiting the young star HR 8799, roughly 129 light-years away — the first time multiple planets around another star had been directly imaged together (a fourth, innermost planet was found in follow-up imaging in 2010). The planets are visible only because they are young, hot, and far enough from their host star for its glare to be blocked out.",
    value: "2008",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Adaptive-optics direct imaging with coronagraphic starlight suppression at the Keck and Gemini North observatories, published in Science.",
    source: { title: "Marois et al., \"Direct Imaging of Multiple Planets Orbiting the Star HR 8799,\" Science", url: "https://www.science.org/doi/10.1126/science.1166585", date: "2008-11-13", location: "W. M. Keck Observatory and Gemini North, Hawaii" },
  },
  {
    registryNumber: "LR-FASTEST-EXOPLANET-ORBIT", slug: "fastest-known-exoplanet-orbital-period", title: "Fastest known exoplanet orbital period",
    category: "Astrophysics", subcategory: "Exoplanets", direction: "MINIMIZE",
    metricName: "Orbital period of the exoplanet with the shortest confirmed orbit", unit: "hours",
    formalStatement: "The shortest confirmed orbital period of any known exoplanet around its host star.",
    summary: "KOI 1843.03, an ultra-short-period rocky planet candidate identified in Kepler data, orbits its red dwarf host star once every 4.245 hours — the fastest known exoplanet orbit, skimming so close to its star that its rock must be dense enough (iron-rich) to avoid being torn apart by tidal forces. Its extreme proximity means a 'year' there is shorter than a single work shift on Earth.",
    value: "4.245",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Transit-timing analysis of Kepler space telescope photometric data, published in a peer-reviewed study of ultra-short-period planet candidates (Rappaport et al., 2013).",
    source: { title: "Rappaport et al., \"Possible Disintegrating Short-Period Super-Mercury Orbiting KOI 1843,\" The Astrophysical Journal", url: "https://iopscience.iop.org/article/10.1088/0004-637X/773/1/1", date: "2013-08-01", location: "NASA Kepler space telescope archive" },
  },

  // --- Astrophysics: Planetary Science (Solar System) ---
  {
    registryNumber: "LR-TALLEST-VOLCANO-SOLAR-SYSTEM", slug: "tallest-known-mountain-in-the-solar-system", title: "Tallest known mountain in the solar system",
    category: "Astrophysics", subcategory: "Planetary Science", direction: "MAXIMIZE",
    metricName: "Height of the tallest known mountain/volcano in the solar system, base to summit", unit: "km",
    formalStatement: "The greatest base-to-summit height of any known mountain or volcanic edifice in the solar system, on any planet or moon.",
    summary: "Olympus Mons, a shield volcano on Mars, rises about 21.9 km from its base — roughly two and a half times the height of Mount Everest above sea level — and spans about 600 km across at its base, making it the tallest known mountain in the solar system. It could form so large partly because Mars lacks plate tectonics, letting lava build up in one place over hundreds of millions of years instead of the crust shifting the hotspot away, as on Earth (compare Earth's Tamu Massif, which is far larger by footprint but much shorter in height).",
    value: "21.9",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Laser altimetry from NASA's Mars Global Surveyor (MOLA instrument), corroborated by later orbital imaging missions.",
    source: { title: "NASA — Mars Global Surveyor MOLA Science Investigation, Olympus Mons topography", url: "https://mars.nasa.gov/mgs/", date: "2001-01-01", location: "Olympus Mons, Mars (measured via Mars orbit)" },
  },
  {
    registryNumber: "LR-LARGEST-CANYON-SOLAR-SYSTEM", slug: "largest-canyon-system-in-the-solar-system", title: "Largest canyon system in the solar system",
    category: "Astrophysics", subcategory: "Planetary Science", direction: "MAXIMIZE",
    metricName: "Total length of the largest known canyon system in the solar system", unit: "km",
    formalStatement: "The greatest total length of any known canyon system in the solar system, on any planet or moon.",
    summary: "Valles Marineris on Mars stretches roughly 4,000 km — about a fifth of the planet's circumference — and reaches depths of up to 7 km in places, making it both the longest and one of the deepest known canyon systems in the solar system, dwarfing Earth's Grand Canyon (about 450 km long and up to 1.8 km deep). It likely formed through a combination of tectonic rifting and later erosion, rather than being carved by a river as the Grand Canyon was.",
    value: "4000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Orbital imaging and laser altimetry from multiple Mars missions, including Viking, Mars Global Surveyor, and Mars Express.",
    source: { title: "NASA — Valles Marineris: The Grand Canyon of Mars", url: "https://www.jpl.nasa.gov/images/pia00422-valles-marineris-the-grand-canyon-of-mars", date: "2002-01-01", location: "Valles Marineris, Mars" },
  },
  {
    registryNumber: "LR-STRONGEST-WINDS-SOLAR-SYSTEM", slug: "strongest-winds-recorded-on-any-planet", title: "Strongest winds recorded on any planet",
    category: "Astrophysics", subcategory: "Planetary Science", direction: "MAXIMIZE",
    metricName: "Highest sustained wind speed directly measured on any planet in the solar system", unit: "km/h",
    formalStatement: "The greatest sustained wind speed directly measured in the atmosphere of any planet in the solar system, including Earth.",
    summary: "NASA's Voyager 2 spacecraft measured sustained winds of roughly 2,100 km/h (about 580 m/s) in Neptune's atmosphere during its 1989 flyby — the strongest planetary winds ever directly measured, despite Neptune receiving only about 0.1% of the sunlight (and thus far less driving solar energy) that Earth does. The mechanism behind such extreme winds on a cold, distant planet remains an open question in planetary science.",
    value: "2100",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Cloud-tracking from Voyager 2 imaging during its August 1989 Neptune flyby, published in peer-reviewed planetary science literature.",
    source: { title: "NASA JPL — Neptune: In Depth", url: "https://science.nasa.gov/neptune/facts/", date: "1989-08-25", location: "Neptune, observed via Voyager 2 flyby" },
  },
  {
    registryNumber: "LR-LARGEST-STORM-SOLAR-SYSTEM", slug: "largest-storm-in-the-solar-system", title: "Largest storm in the solar system",
    category: "Astrophysics", subcategory: "Planetary Science", direction: "MAXIMIZE",
    metricName: "Diameter of the largest persistent storm system known in the solar system", unit: "km",
    formalStatement: "The greatest diameter of any long-lived atmospheric storm system observed in the solar system.",
    summary: "Jupiter's Great Red Spot, an anticyclonic storm that has been observed continuously since at least the 1830s (and possibly since the 1600s), currently measures roughly 16,000 km across — still larger than Earth's diameter, though it has been steadily shrinking for over a century from an estimated 40,000 km in the late 1800s. It remains the largest and longest-lived storm system known anywhere in the solar system.",
    value: "16000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Telescopic and spacecraft imaging measurements tracked over more than a century, most recently by the Hubble Space Telescope and the Juno mission.",
    source: { title: "NASA — Jupiter's Great Red Spot", url: "https://science.nasa.gov/jupiter/jupiter-facts/", date: "2021-01-01", location: "Jupiter, tracked via ground telescopes, Hubble, and Juno" },
  },
  {
    registryNumber: "LR-LARGEST-MOON-SOLAR-SYSTEM", slug: "largest-moon-in-the-solar-system", title: "Largest moon in the solar system",
    category: "Astrophysics", subcategory: "Planetary Science", direction: "MAXIMIZE",
    metricName: "Diameter of the largest known moon in the solar system", unit: "km",
    formalStatement: "The greatest diameter of any known natural satellite (moon) in the solar system.",
    summary: "Ganymede, one of Jupiter's Galilean moons, has a diameter of about 5,268 km — larger than the planet Mercury, and larger than the dwarf planet Pluto — making it the largest moon in the solar system. It is also the only known moon with its own internally generated magnetic field, and is thought to host a subsurface saltwater ocean beneath its icy crust.",
    value: "5268",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Radar and spacecraft imaging measurements from multiple missions including Voyager, Galileo, and Juno.",
    source: { title: "NASA JPL — Ganymede: In Depth", url: "https://science.nasa.gov/moon/moons-of-jupiter/ganymede/", date: "2021-01-01", location: "Ganymede, Jupiter system" },
  },
  {
    registryNumber: "LR-LARGEST-LIQUID-WATER-RESERVOIR-SOLAR-SYSTEM", slug: "largest-known-liquid-water-reservoir-in-the-solar-system", title: "Largest known liquid-water reservoir in the solar system",
    category: "Astrophysics", subcategory: "Planetary Science", direction: "MAXIMIZE",
    metricName: "Estimated volume of the largest known extraterrestrial subsurface ocean, relative to Earth's oceans", unit: "x Earth ocean volume",
    formalStatement: "The largest volume of liquid water inferred to exist anywhere in the solar system outside Earth, expressed as a multiple of the total volume of Earth's oceans.",
    summary: "Europa, one of Jupiter's moons, is thought to harbor a global subsurface saltwater ocean beneath its icy shell holding roughly twice the volume of all of Earth's oceans combined, based on gravity, magnetic, and geological data from the Galileo and Juno missions. Ganymede and Enceladus are also thought to hold large subsurface oceans, but Europa's is the most extensively studied and is the primary target of NASA's Europa Clipper mission, launched in 2024. Exact volume estimates remain modeled rather than directly measured, since no mission has yet sampled the ocean itself.",
    value: "2",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Inferred from gravity data, induced magnetic field measurements, and ice-shell thickness modeling from the Galileo mission and subsequent studies.",
    source: { title: "NASA — Europa Clipper: Ocean World", url: "https://europa.nasa.gov/why-europa/ocean-world/", date: "2024-01-01", location: "Europa, Jupiter system" },
  },
  {
    registryNumber: "LR-MOST-EXTENSIVE-RING-SYSTEM", slug: "most-extensive-planetary-ring-system", title: "Most extensive planetary ring system",
    category: "Astrophysics", subcategory: "Planetary Science", direction: "MAXIMIZE",
    metricName: "Outer radial extent of the most extensive known planetary ring system", unit: "km",
    formalStatement: "The greatest outer radial extent of any planetary ring system in the solar system, including faint outer rings detected by spacecraft.",
    summary: "Saturn's ring system, including its faint outer rings such as the Phoebe ring, extends to roughly 282,000 km from the planet's surface at its widest confirmed extent — far more extensive than the fainter, narrower ring systems found around Jupiter, Uranus, and Neptune. Despite this enormous width, the main visible rings are extraordinarily thin, in most places under a kilometer thick.",
    value: "282000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Infrared and spacecraft imaging measurements, including the Spitzer Space Telescope's 2009 discovery of the vast, faint Phoebe ring.",
    source: { title: "NASA — Spitzer Telescope Finds Saturn's Largest Ring", url: "https://www.nasa.gov/missions/spitzer-space-telescope/spitzer-telescope-finds-saturns-largest-ring/", date: "2009-10-06", location: "Saturn ring system, observed via Spitzer Space Telescope" },
  },

  // --- Astrophysics: Space Exploration Milestones ---
  {
    registryNumber: "LR-FIRST-SPACECRAFT-TOUCH-SUN", slug: "first-spacecraft-to-fly-through-the-suns-corona", title: "First spacecraft to fly through the Sun's corona",
    category: "Astrophysics", subcategory: "Space Exploration", direction: "MINIMIZE",
    metricName: "Year a spacecraft first flew through the Sun's outer atmosphere (corona)", unit: "year",
    formalStatement: "The year a spacecraft first passed through the Sun's corona, its outer atmosphere, making direct in-situ measurements.",
    summary: "NASA's Parker Solar Probe became the first spacecraft to fly through the Sun's corona on April 28, 2021, passing through the Alfvén surface (the boundary where the corona's magnetic field dominates over the outward solar wind) and sampling particles and magnetic fields directly. The milestone, announced by NASA in December 2021, was described as the equivalent of a spacecraft finally 'touching the Sun.'",
    value: "2021",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "In-situ magnetic field and particle measurements from Parker Solar Probe's onboard instruments during a close perihelion pass, published in Physical Review Letters.",
    source: { title: "NASA — NASA Enters the Solar Atmosphere for the First Time", url: "https://www.nasa.gov/missions/parker-solar-probe/nasa-enters-the-solar-atmosphere-for-the-first-time-bringing-new-discoveries/", date: "2021-12-14", location: "Parker Solar Probe, within the Sun's corona" },
  },
  {
    registryNumber: "LR-FIRST-INTERSTELLAR-OBJECT", slug: "first-confirmed-interstellar-object", title: "First confirmed interstellar object detected in the solar system",
    category: "Astrophysics", subcategory: "Space Exploration", direction: "MINIMIZE",
    metricName: "Year the first confirmed interstellar object was detected passing through the solar system", unit: "year",
    formalStatement: "The year an object was first confirmed, from its hyperbolic (unbound) trajectory, to have originated outside the solar system.",
    summary: "ʻOumuamua, discovered by the Pan-STARRS survey telescope in Hawaii on October 19, 2017, was the first object confirmed to have originated from outside the solar system, based on its hyperbolic trajectory and speed that ruled out a solar-system origin. Its unusual elongated shape and lack of a visible cometary tail fueled ongoing scientific debate over its exact nature before it became too faint to observe further.",
    value: "2017",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Orbital trajectory determination from Pan-STARRS survey telescope observations, confirmed through international follow-up astrometry.",
    source: { title: "NASA JPL — 'Oumuamua: The First Interstellar Visitor", url: "https://www.jpl.nasa.gov/news/solar-systems-first-known-interstellar-object-makes-close-approach/", date: "2017-11-20", location: "Pan-STARRS1 telescope, Haleakalā Observatory, Hawaii" },
  },
  {
    registryNumber: "LR-FIRST-FAR-SIDE-MOON-SAMPLE-RETURN", slug: "first-sample-return-mission-from-the-lunar-far-side", title: "First sample-return mission from the lunar far side",
    category: "Astrophysics", subcategory: "Space Exploration", direction: "MINIMIZE",
    metricName: "Year of the first successful robotic sample-return mission from the far side of the Moon", unit: "year",
    formalStatement: "The year a robotic mission first collected and returned to Earth physical samples from the far side of the Moon.",
    summary: "China's Chang'e 6 mission landed in the Moon's South Pole-Aitken Basin on the lunar far side on June 1-2, 2024, collected roughly 1.9 kg of surface and subsurface material, and returned it to Earth on June 25, 2024 — the first sample-return mission from the far side of the Moon, following the earlier Chang'e 4 mission which achieved the first landing there in January 2019 without returning samples.",
    value: "2024",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Robotic surface sampling (drilling and scooping), ascent to lunar orbit, and Earth-return capsule recovery, confirmed by the China National Space Administration.",
    source: { title: "CNSA / Xinhua — Chang'e-6 returns world's first samples from moon's far side", url: "http://www.cnsa.gov.cn/english/", date: "2024-06-25", location: "South Pole-Aitken Basin, lunar far side; recovery in Inner Mongolia, China" },
  },
  {
    registryNumber: "LR-MOST-POWERFUL-ROCKET-THRUST", slug: "most-powerful-rocket-by-liftoff-thrust", title: "Most powerful rocket by liftoff thrust",
    category: "Astrophysics", subcategory: "Space Exploration", direction: "MAXIMIZE",
    metricName: "Total liftoff thrust of the most powerful rocket ever flown", unit: "MN",
    formalStatement: "The greatest combined liftoff thrust generated by any launch vehicle that has flown, measured at sea level.",
    summary: "SpaceX's Starship/Super Heavy launch system, whose Super Heavy first stage uses 33 Raptor engines, generates roughly 74 meganewtons (about 16.7 million lbf) of liftoff thrust — surpassing the Soviet N1 rocket (about 45 MN) and the Saturn V (about 35 MN) to become the most powerful rocket ever flown, first reaching orbital-class flight in 2023-2024. SpaceX has stated planned upgrades (Starship V3) intended to push thrust even higher, so this figure is likely to keep climbing.",
    value: "74.3",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Manufacturer-published per-engine thrust figures for the Raptor 2 engine multiplied by engine count, corroborated by static-fire and launch telemetry.",
    source: { title: "SpaceX — Starship", url: "https://www.spacex.com/vehicles/starship/", date: "2023-11-18", location: "SpaceX Starbase, Boca Chica, Texas, USA" },
  },

  // --- Astrophysics: Cosmology & Deep-Sky Objects ---
  {
    registryNumber: "LR-MOST-DISTANT-CONFIRMED-GALAXY", slug: "most-distant-spectroscopically-confirmed-galaxy", title: "Most distant spectroscopically confirmed galaxy",
    category: "Astrophysics", subcategory: "Cosmology", direction: "MAXIMIZE",
    metricName: "Spectroscopically confirmed redshift of the most distant known galaxy", unit: "redshift (z)",
    formalStatement: "The highest redshift confirmed for any galaxy via spectroscopy, as verified by the most recent published measurement.",
    summary: "JADES-GS-z14-0, identified by the JWST Advanced Deep Extragalactic Survey (JADES), was spectroscopically confirmed in 2024 at redshift z=14.32 — corresponding to roughly 290 million years after the Big Bang — making it the most distant galaxy with a confirmed spectroscopic redshift as of 2026. Photometric (unconfirmed) candidates at even higher apparent redshifts are regularly proposed as JWST deep surveys continue, so this exact record is expected to keep moving as spectroscopic follow-up catches up.",
    value: "14.32",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Near-infrared spectroscopy with JWST's NIRSpec instrument, confirming redshift via detected emission lines, published by the JADES collaboration in Nature.",
    source: { title: "Carniani et al., \"A shining cosmic dawn: spectroscopic confirmation of two galaxies at z ~ 14,\" Nature", url: "https://www.nature.com/articles/s41586-024-07860-9", date: "2024-05-30", location: "JWST JADES survey" },
  },
  {
    registryNumber: "LR-LARGEST-KNOWN-GALAXY", slug: "largest-known-galaxy-by-size", title: "Largest known galaxy by size",
    category: "Astrophysics", subcategory: "Cosmology", direction: "MAXIMIZE",
    metricName: "Total extent of the largest known galaxy, including its radio lobes", unit: "million ly",
    formalStatement: "The greatest total physical extent of any known galaxy, including detected radio emission lobes.",
    summary: "Alcyoneus, a giant radio galaxy discovered in 2022 using data from the LOFAR radio telescope network, has jets and radio lobes spanning approximately 16.3 million light-years (about 5 megaparsecs) end to end — making it the largest known galaxy, roughly 100 times the diameter of the Milky Way. Its central galaxy itself is unremarkable; the record comes entirely from the enormous scale of its jet-powered radio lobes.",
    value: "16.3",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Low-frequency radio imaging with the LOFAR (Low-Frequency Array) telescope network, published in a peer-reviewed study (Oei et al., 2022).",
    source: { title: "Oei et al., \"The discovery of a radio galaxy of at least 5 Mpc,\" Astronomy & Astrophysics", url: "https://www.aanda.org/articles/aa/full_html/2022/02/aa41634-21/aa41634-21.html", date: "2022-02-01", location: "LOFAR radio telescope network, Europe" },
  },
  {
    registryNumber: "LR-LARGEST-COSMIC-VOID", slug: "largest-known-cosmic-void", title: "Largest known cosmic void",
    category: "Astrophysics", subcategory: "Cosmology", direction: "MAXIMIZE",
    metricName: "Diameter of the largest known cosmic void", unit: "million ly",
    formalStatement: "The greatest diameter of any known cosmic void — a large region of space containing far fewer galaxies than average.",
    summary: "The Boötes Void, discovered in 1981, is a roughly spherical region of space about 330 million light-years across containing dramatically fewer galaxies than its surroundings — one of the largest known voids in the observable universe. Its near-emptiness (fewer than 60 galaxies have been identified within it, versus thousands expected in an equivalent volume) made it an early, striking piece of evidence for the large-scale 'cosmic web' structure of galaxy filaments and voids.",
    value: "330",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Galaxy redshift survey mapping, originally identified by Robert Kirshner's team and refined by later large-scale structure surveys.",
    source: { title: "Kirshner et al., \"A million cubic megaparsec void in Bootes,\" The Astrophysical Journal", url: "https://ui.adsabs.harvard.edu/abs/1981ApJ...248L..57K", date: "1981-09-01", location: "Boötes constellation region" },
  },
  {
    registryNumber: "LR-BRIGHTEST-GAMMA-RAY-BURST", slug: "brightest-gamma-ray-burst-ever-recorded", title: "Brightest gamma-ray burst ever recorded",
    category: "Astrophysics", subcategory: "Cosmology", direction: "MAXIMIZE",
    metricName: "Gamma-ray fluence of the brightest gamma-ray burst detected since monitoring began", unit: "erg/cm²",
    formalStatement: "The highest total gamma-ray fluence (energy per unit area) measured for any gamma-ray burst since systematic satellite monitoring began in the 1990s.",
    summary: "GRB 221009A, detected on October 9, 2022 and nicknamed the 'BOAT' (Brightest Of All Time) by astronomers, was roughly ten times brighter than any previously recorded gamma-ray burst, with a measured fluence so high it temporarily blinded or saturated the detectors on several gamma-ray satellites. Originating about 2.4 billion light-years away, it also produced the highest-energy photons ever recorded from a gamma-ray burst, detected by the LHAASO observatory in China at energies up to 18 teraelectronvolts.",
    value: "0.019",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Gamma-ray fluence measured by NASA's Fermi Gamma-ray Burst Monitor and Swift Observatory, with very-high-energy photon detection by the LHAASO ground-based observatory, published across multiple peer-reviewed papers in 2023.",
    source: { title: "NASA — NASA Missions Study What May Be a 1-in-10,000-Year Gamma-ray Burst", url: "https://www.nasa.gov/solar-system/nasa-missions-study-what-may-be-a-1-in-10000-year-gamma-ray-burst/", date: "2023-03-08", location: "GRB 221009A, detected by Fermi, Swift, and LHAASO" },
  },
  {
    registryNumber: "LR-MOST-MASSIVE-DWARF-PLANET", slug: "most-massive-known-dwarf-planet", title: "Most massive known dwarf planet",
    category: "Astrophysics", subcategory: "Planetary Science", direction: "MAXIMIZE",
    metricName: "Mass of the most massive known dwarf planet", unit: "10^21 kg",
    formalStatement: "The greatest mass measured for any object classified as a dwarf planet in the solar system.",
    summary: "Eris, a distant Kuiper Belt object discovered in 2005, has a mass of about 1.66 x 10^22 kg — roughly 27% more massive than Pluto, though slightly smaller in diameter — making it the most massive known dwarf planet. Its discovery directly triggered the International Astronomical Union's 2006 redefinition of 'planet,' which reclassified Pluto (and Eris itself) as dwarf planets.",
    value: "16.6",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Mass derived from the orbit of Eris's moon Dysnomia, measured via Hubble Space Telescope and ground-based adaptive-optics imaging.",
    source: { title: "Brown & Schaller, \"The Mass of Dwarf Planet Eris,\" Science", url: "https://www.science.org/doi/10.1126/science.1139415", date: "2007-06-15", location: "Keck Observatory and Hubble Space Telescope observations" },
  },

  // --- Earth & Climate: Atmospheric & Weather Extremes ---
  {
    registryNumber: "LR-HIGHEST-SEA-LEVEL-PRESSURE", slug: "highest-sea-level-adjusted-atmospheric-pressure-recorded", title: "Highest sea-level-adjusted atmospheric pressure recorded",
    category: "Earth & Climate", subcategory: "Weather Extremes", direction: "MAXIMIZE",
    metricName: "Highest sea-level-reduced barometric pressure ever recorded", unit: "hPa",
    formalStatement: "The highest atmospheric pressure, reduced to mean sea level, ever recorded at a surface weather station.",
    summary: "A pressure of 1,083.8 hPa (32.01 inHg) was recorded at Agata, Siberia, on December 31, 1968 — the highest sea-level-adjusted atmospheric pressure ever measured at a surface station, recognized by the World Meteorological Organization. It occurred under an intense Siberian winter high-pressure system, a regime that regularly produces the world's highest surface pressures.",
    value: "1083.8",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Surface barometric measurement, verified and archived by the World Meteorological Organization's Global Weather and Climate Extremes Archive.",
    source: { title: "WMO Global Weather & Climate Extremes Archive — Highest sea level pressure", url: "https://wmo.asu.edu/", date: "1968-12-31", location: "Agata, Evenk Autonomous Okrug, Russia (then USSR)" },
  },
  {
    registryNumber: "LR-LOWEST-PRESSURE-TROPICAL-CYCLONE", slug: "lowest-sea-level-pressure-in-a-tropical-cyclone", title: "Lowest sea-level pressure recorded in a tropical cyclone",
    category: "Earth & Climate", subcategory: "Weather Extremes", direction: "MINIMIZE",
    metricName: "Lowest central sea-level pressure ever measured in a tropical cyclone", unit: "hPa",
    formalStatement: "The lowest central barometric pressure ever directly measured in any tropical cyclone.",
    summary: "Typhoon Tip, in the western Pacific in October 1979, reached a central pressure of 870 hPa on October 12 — the lowest sea-level pressure ever recorded in a tropical cyclone, and still the global record more than four decades later. Tip was also, by gale-force wind field diameter, the largest tropical cyclone ever recorded, at roughly 2,220 km across.",
    value: "870",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Direct pressure measurement via reconnaissance aircraft dropsonde, archived by the U.S. Joint Typhoon Warning Center and the WMO extremes archive.",
    source: { title: "WMO Global Weather & Climate Extremes Archive — Lowest sea level pressure (tropical cyclone)", url: "https://wmo.asu.edu/", date: "1979-10-12", location: "Northwestern Pacific Ocean, near Guam" },
  },
  {
    registryNumber: "LR-LARGEST-TROPICAL-CYCLONE-DIAMETER", slug: "largest-tropical-cyclone-by-diameter", title: "Largest tropical cyclone by diameter",
    category: "Earth & Climate", subcategory: "Weather Extremes", direction: "MAXIMIZE",
    metricName: "Diameter of gale-force winds of the largest tropical cyclone on record", unit: "km",
    formalStatement: "The greatest diameter of gale-force (34-knot) sustained winds ever measured for a tropical cyclone.",
    summary: "Typhoon Tip, the same 1979 western Pacific storm that holds the record for lowest central pressure, also had a gale-force wind field roughly 2,220 km across at its peak — the largest tropical cyclone ever measured by areal extent, nearly half the width of the continental United States, even though its most intense winds were concentrated in a much smaller core.",
    value: "2220",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Satellite imagery and reconnaissance aircraft wind-field measurement, archived by the U.S. Joint Typhoon Warning Center.",
    source: { title: "Joint Typhoon Warning Center — Typhoon Tip (1979) best track data", url: "https://www.metoc.navy.mil/jtwc/jtwc.html", date: "1979-10-12", location: "Northwestern Pacific Ocean" },
  },
  {
    registryNumber: "LR-STRONGEST-SUSTAINED-CYCLONE-WINDS", slug: "strongest-sustained-winds-in-a-tropical-cyclone-western-hemisphere", title: "Strongest sustained winds in a tropical cyclone (Western Hemisphere)",
    category: "Earth & Climate", subcategory: "Weather Extremes", direction: "MAXIMIZE",
    metricName: "Highest 1-minute sustained wind speed estimated for a Western Hemisphere tropical cyclone", unit: "km/h",
    formalStatement: "The highest 1-minute sustained wind speed estimated by satellite-based analysis for any tropical cyclone in the Western Hemisphere.",
    summary: "Hurricane Patricia, off Mexico's Pacific coast in October 2015, reached estimated 1-minute sustained winds of about 345 km/h (215 mph) shortly before landfall — the strongest sustained winds ever estimated for a tropical cyclone in the Western Hemisphere, per the U.S. National Hurricane Center. Because such extreme intensities are usually derived from satellite-based Dvorak-technique estimates rather than direct in-storm instrument readings, the figure carries meaningfully more uncertainty than a surface-station measurement.",
    value: "345",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Satellite-based Dvorak technique intensity estimation, cross-checked with reconnaissance aircraft data, per the U.S. National Hurricane Center's final report.",
    source: { title: "National Hurricane Center — Hurricane Patricia Tropical Cyclone Report", url: "https://www.nhc.noaa.gov/data/tcr/EP202015_Patricia.pdf", date: "2016-02-02", location: "Eastern Pacific Ocean, off Jalisco, Mexico" },
  },
  {
    registryNumber: "LR-MOST-TORNADOES-SINGLE-OUTBREAK", slug: "most-tornadoes-confirmed-in-a-single-outbreak", title: "Most tornadoes confirmed in a single outbreak",
    category: "Earth & Climate", subcategory: "Weather Extremes", direction: "MAXIMIZE",
    metricName: "Number of confirmed tornadoes produced by a single multi-day tornado outbreak", unit: "tornadoes",
    formalStatement: "The greatest number of tornadoes confirmed to have touched down during a single, continuous multi-day tornado outbreak.",
    summary: "The 2011 Super Outbreak, which struck the southern and eastern United States from April 25-28, 2011, produced 360 confirmed tornadoes — the most of any tornado outbreak on record — including four rated EF5, the highest rating on the Enhanced Fujita scale. The outbreak killed over 300 people and remains the costliest tornado outbreak in U.S. history.",
    value: "360",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Post-event storm survey and damage assessment by National Weather Service forecast offices, compiled by NOAA's Storm Prediction Center.",
    source: { title: "NOAA National Weather Service — The Super Tornado Outbreak of April 25-28, 2011", url: "https://www.weather.gov/oun/events-20110427", date: "2011-04-27", location: "Southern and eastern United States" },
  },
  {
    registryNumber: "LR-WIDEST-TORNADO-RECORDED", slug: "widest-tornado-ever-recorded", title: "Widest tornado ever recorded",
    category: "Earth & Climate", subcategory: "Weather Extremes", direction: "MAXIMIZE",
    metricName: "Maximum path width of the widest tornado ever surveyed", unit: "km",
    formalStatement: "The greatest confirmed path width of any tornado on record, as determined by post-event damage survey.",
    summary: "The El Reno, Oklahoma tornado of May 31, 2013 reached a maximum path width of about 4.2 km (2.6 miles) at its peak — the widest tornado ever confirmed by National Weather Service damage and radar survey, wider than the tornado is long in most tornado tracks. It killed several storm chasers, including experienced researcher Tim Samaras, underscoring how unpredictable its extreme width and erratic path made it.",
    value: "4.2",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Post-event damage survey combined with mobile Doppler radar path-width analysis, conducted by the National Weather Service.",
    source: { title: "NOAA National Weather Service — The El Reno, OK Tornado of May 31, 2013", url: "https://www.weather.gov/oun/events-20130531", date: "2013-05-31", location: "El Reno, Oklahoma, USA" },
  },
  {
    registryNumber: "LR-LONGEST-TORNADO-TRACK", slug: "longest-continuous-tornado-track", title: "Longest continuous tornado track",
    category: "Earth & Climate", subcategory: "Weather Extremes", direction: "MAXIMIZE",
    metricName: "Length of the longest continuous single-tornado damage path on record", unit: "km",
    formalStatement: "The greatest length of a damage path attributed to a single continuous tornado, as determined by historical damage survey.",
    summary: "The Tri-State Tornado of March 18, 1925 tracked roughly 352 km (219 miles) across Missouri, Illinois, and Indiana — the longest continuous tornado damage path on record — killing 695 people, still the deadliest single tornado in U.S. history. Some modern meteorologists argue the historical damage path may actually represent a short-lived family of several tornadoes rather than one continuous funnel, given the limits of 1920s-era damage surveying, but it remains the officially recognized record.",
    value: "352",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Historical damage-path reconstruction from contemporary reports and later meteorological re-analysis, compiled by NOAA's National Weather Service.",
    source: { title: "NOAA National Weather Service — The Tri-State Tornado of March 18, 1925", url: "https://www.weather.gov/pah/1925TriStateTornado", date: "1925-03-18", location: "Missouri, Illinois, and Indiana, USA" },
  },
  {
    registryNumber: "LR-HEAVIEST-HAILSTONE-BY-MASS", slug: "heaviest-hailstone-ever-recorded", title: "Heaviest hailstone ever recorded",
    category: "Earth & Climate", subcategory: "Weather Extremes", direction: "MAXIMIZE",
    metricName: "Mass of the heaviest hailstone ever officially recorded", unit: "kg",
    formalStatement: "The greatest mass of any single hailstone officially recorded and verified, as distinct from records for largest hailstone diameter.",
    summary: "A hailstone weighing 1.02 kg (2.25 lb) fell on Gopalganj District, Bangladesh, on April 14, 1986, during a storm that killed 92 people — the heaviest hailstone ever officially recorded, per the World Meteorological Organization. This is a distinct record from the largest hailstone by diameter (a 2010 stone from Vivian, South Dakota, USA, measuring about 20 cm across), since diameter and mass records are not always held by the same stone.",
    value: "1.02",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Direct weighing of recovered hailstone fragments, verified and archived by the World Meteorological Organization's Global Weather and Climate Extremes Archive.",
    source: { title: "WMO Global Weather & Climate Extremes Archive — Heaviest hailstone", url: "https://wmo.asu.edu/", date: "1986-04-14", location: "Gopalganj District, Bangladesh" },
  },
  {
    registryNumber: "LR-HIGHEST-AVERAGE-ANNUAL-RAINFALL", slug: "highest-average-annual-rainfall-location", title: "Highest average annual rainfall location",
    category: "Earth & Climate", subcategory: "Weather Extremes", direction: "MAXIMIZE",
    metricName: "Highest long-term average annual rainfall recorded at an inhabited location", unit: "mm/year",
    formalStatement: "The highest long-term average annual rainfall recorded at any permanently inhabited location on Earth, distinct from single-day or single-year rainfall extremes.",
    summary: "Mawsynram, a village in the Indian state of Meghalaya, holds the record for highest average annual rainfall at approximately 11,872 mm (about 467 inches) per year, based on long-term meteorological records — narrowly surpassing its nearby rival Cherrapunji (also in Meghalaya), which holds several single-year and single-month rainfall records. Both owe their extreme rainfall to monsoon winds being forced sharply upward against the Khasi Hills.",
    value: "11872",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Long-term meteorological station averaging, compiled by the India Meteorological Department.",
    source: { title: "India Meteorological Department — Climatological Normals", url: "https://mausam.imd.gov.in/", date: "2020-01-01", location: "Mawsynram, Meghalaya, India" },
  },
  {
    registryNumber: "LR-HIGHEST-UV-INDEX-RECORDED", slug: "highest-uv-index-ever-recorded", title: "Highest UV Index ever recorded",
    category: "Earth & Climate", subcategory: "Atmospheric Science", direction: "MAXIMIZE",
    metricName: "Highest ground-level UV Index ever measured", unit: "UV Index",
    formalStatement: "The highest ground-level ultraviolet radiation index ever measured at Earth's surface by a calibrated instrument.",
    summary: "A UV Index of 43.3 was measured at a high-altitude site on the Bolivian Altiplano in the early 2000s — far above the value of 11 that most public UV-Index scales treat as 'extreme' — attributed to the combination of high elevation (thinner, clearer atmosphere), low ozone, and the sun's near-overhead position close to the tropics in the Southern Hemisphere summer. The exact measurement and publication details are less widely corroborated than most entries in this registry, so this figure should be treated as a notable literature-reported extreme rather than an official WMO record.",
    value: "43.3",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Ground-based UV radiometer measurement at high altitude, reported in atmospheric science literature on extreme high-altitude UV exposure.",
    source: { title: "NOAA / World Meteorological Organization — background on UV Index extremes at high-altitude tropical sites", url: "https://www.esrl.noaa.gov/gmd/grad/neubrew/docs/UVindex.pdf", date: "2004-01-01", location: "Bolivian Altiplano, Bolivia" },
  },

  // --- Earth & Climate: Cryosphere, Volcanism, Geomagnetism & Oceans ---
  {
    registryNumber: "LR-LARGEST-OZONE-HOLE", slug: "largest-antarctic-ozone-hole-ever-recorded", title: "Largest Antarctic ozone hole ever recorded",
    category: "Earth & Climate", subcategory: "Atmospheric Science", direction: "MAXIMIZE",
    metricName: "Maximum single-day area of the Antarctic ozone hole", unit: "million km²",
    formalStatement: "The greatest single-day area ever measured for the seasonal Antarctic stratospheric ozone hole, per satellite monitoring.",
    summary: "The Antarctic ozone hole reached its largest-ever single-day extent of approximately 29.9 million km² on September 24, 2006 — roughly three and a half times the area of the contiguous United States — as measured by NASA and NOAA satellites. Ozone-hole area has generally trended smaller since the 1987 Montreal Protocol phased out ozone-depleting chemicals, though it still varies significantly year to year with stratospheric weather conditions.",
    value: "29.9",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Satellite-based total-column ozone measurement (NASA's Aura satellite/OMI instrument and NOAA polar-orbiting satellites), analyzed by NASA's Ozone Watch program.",
    source: { title: "NASA Ozone Watch — Largest Ozone Hole on Record", url: "https://ozonewatch.gsfc.nasa.gov/", date: "2006-09-24", location: "Antarctica, monitored via NASA/NOAA satellites" },
  },
  {
    registryNumber: "LR-DEEPEST-OLDEST-ICE-CORE", slug: "oldest-continuous-ice-core-climate-record", title: "Oldest continuous ice-core climate record",
    category: "Earth & Climate", subcategory: "Cryosphere", direction: "MAXIMIZE",
    metricName: "Age of the oldest continuous climate record recovered from an ice core", unit: "years",
    formalStatement: "The greatest age of any continuous, dated climate record recovered from a single ice core.",
    summary: "The European 'Beyond EPICA - Oldest Ice' project reached bedrock at Little Dome C, East Antarctica, in January 2025, at a depth of roughly 2,800 m — recovering a continuous ice-core climate record estimated to extend back about 1.2 million years, more than 400,000 years further back than the previous record held by the original EPICA Dome C core (about 800,000 years). The extended record is expected to help explain why the pace of Earth's ice ages shifted roughly 900,000-1,200,000 years ago.",
    value: "1200000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Deep ice-core drilling to bedrock with layer-counting and ice-flow-model dating, conducted by the EU-funded Beyond EPICA consortium.",
    source: { title: "British Antarctic Survey / Beyond EPICA — Oldest continuous ice core reaches bedrock", url: "https://www.beyondepica.eu/en/", date: "2025-01-09", location: "Little Dome C, East Antarctica" },
  },
  {
    registryNumber: "LR-FASTEST-FLOWING-GLACIER", slug: "fastest-flowing-glacier-on-earth", title: "Fastest-flowing glacier on Earth",
    category: "Earth & Climate", subcategory: "Cryosphere", direction: "MAXIMIZE",
    metricName: "Peak recorded flow speed of the fastest-moving major glacier", unit: "m/day",
    formalStatement: "The highest sustained ice-flow speed recorded for any major glacier, as measured by satellite or GPS tracking.",
    summary: "Jakobshavn Isbræ (Sermeq Kujalleq), one of Greenland's largest outlet glaciers, was recorded flowing at speeds of up to about 46 m per day (roughly 17 km per year) during a peak period around 2012-2013 — among the fastest sustained glacier flow speeds ever recorded, and a major single contributor to Greenland's ice loss and global sea-level rise. Its speed fluctuates significantly year to year with ocean temperature and calving-front position, and has slowed somewhat since that peak as the fjord's geometry changed.",
    value: "46",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Satellite radar interferometry and repeat optical imagery tracking of surface ice features, published in peer-reviewed glaciology studies (e.g. Joughin et al.).",
    source: { title: "NASA Earth Observatory — Jakobshavn Isbrae", url: "https://earthobservatory.nasa.gov/images/81281/jakobshavn-glacier-continues-to-lose-ice", date: "2013-01-01", location: "Jakobshavn Isbræ, western Greenland" },
  },
  {
    registryNumber: "LR-LARGEST-VOLCANIC-SO2-INJECTION", slug: "largest-volcanic-so2-injection-measured-by-satellite", title: "Largest volcanic sulfur dioxide injection measured by satellite",
    category: "Earth & Climate", subcategory: "Geology", direction: "MAXIMIZE",
    metricName: "Mass of sulfur dioxide injected into the stratosphere by a single eruption, as measured by satellite", unit: "million tonnes",
    formalStatement: "The greatest mass of sulfur dioxide injected into the stratosphere by a single volcanic eruption, as directly measured by satellite instruments — a specific atmospheric-chemistry metric distinct from an eruption's overall explosivity (VEI).",
    summary: "The June 1991 eruption of Mount Pinatubo in the Philippines injected an estimated 20 million tonnes of sulfur dioxide into the stratosphere — the largest such injection measured by satellite instruments since systematic monitoring began — where it formed a global sulfate aerosol layer that cooled average global surface temperatures by roughly 0.5°C for about a year afterward. It remains the best-studied example of how large eruptions can temporarily affect global climate.",
    value: "20",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Satellite ultraviolet backscatter measurement via the Total Ozone Mapping Spectrometer (TOMS), analyzed by USGS and NASA researchers.",
    source: { title: "USGS — Effects of the June 1991 eruption of Mount Pinatubo, Philippines", url: "https://www.usgs.gov/volcanoes/mount-pinatubo", date: "1991-06-15", location: "Mount Pinatubo, Luzon, Philippines" },
  },
  {
    registryNumber: "LR-LARGEST-SUPERVOLCANIC-ERUPTION-GEOLOGIC-RECORD", slug: "largest-known-supervolcanic-eruption-in-the-geologic-record", title: "Largest known supervolcanic eruption in the geologic record",
    category: "Earth & Climate", subcategory: "Geology", direction: "MAXIMIZE",
    metricName: "Estimated bulk erupted volume (dense-rock equivalent) of the largest known supervolcanic eruption in roughly the last 2 million years", unit: "km³",
    formalStatement: "The greatest estimated erupted volume of any single volcanic eruption identified in the geologic record over roughly the last 2 million years — distinct from the largest eruption within written human history, a separate and more precisely measured record.",
    summary: "The Toba supereruption, which occurred in Sumatra, Indonesia, roughly 74,000 years ago, is estimated to have ejected on the order of 2,000-2,800 km³ of material (dense-rock equivalent) — the largest known volcanic eruption of the last approximately 2 million years, rated VEI 8 on the Volcanic Explosivity Index. It left behind Lake Toba, now the world's largest volcanic crater lake, and has been linked (with ongoing scientific debate) to a period of global cooling and a possible human population bottleneck.",
    value: "2800",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Geological volume reconstruction from ash-fall deposit mapping and radiometric dating of eruptive material, synthesized across multiple peer-reviewed studies.",
    source: { title: "Smithsonian Institution Global Volcanism Program — Toba", url: "https://volcano.si.edu/volcano.cfm?vn=261080", date: "2013-01-01", location: "Lake Toba, Sumatra, Indonesia" },
  },
  {
    registryNumber: "LR-LONGEST-CONTINUOUSLY-ACTIVE-VOLCANO", slug: "longest-documented-continuously-active-volcano", title: "Longest documented continuously active volcano",
    category: "Earth & Climate", subcategory: "Geology", direction: "MAXIMIZE",
    metricName: "Number of years a volcano has been documented as continuously or near-continuously active", unit: "years",
    formalStatement: "The greatest number of years any volcano has been documented as continuously or near-continuously erupting, based on historical and geological records.",
    summary: "Stromboli, on its namesake island off Sicily, has been in a state of continuous mild eruption for at least 2,000 years and possibly far longer, with its glowing nighttime explosions visible from passing ships giving it the nickname 'Lighthouse of the Mediterranean' since antiquity — the longest continuously documented volcanic activity of any volcano on Earth. Its remarkably steady, low-intensity 'Strombolian' eruption style, characterized by regular small explosions every few minutes to hours, has even lent its name to that entire class of eruptions in volcanology.",
    value: "2000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Historical eyewitness records combined with geological deposit dating, compiled by the Istituto Nazionale di Geofisica e Vulcanologia (INGV) and the Smithsonian Global Volcanism Program.",
    source: { title: "Smithsonian Institution Global Volcanism Program — Stromboli", url: "https://volcano.si.edu/volcano.cfm?vn=211040", date: "2020-01-01", location: "Stromboli Island, Aeolian Islands, Italy" },
  },
  {
    registryNumber: "LR-TALLEST-VOLCANIC-ERUPTION-PLUME", slug: "tallest-volcanic-eruption-plume-ever-recorded", title: "Tallest volcanic eruption plume ever recorded",
    category: "Earth & Climate", subcategory: "Geology", direction: "MAXIMIZE",
    metricName: "Maximum altitude reached by a volcanic eruption plume, as measured by satellite", unit: "km",
    formalStatement: "The greatest altitude ever reached by a volcanic eruption plume, as directly measured by satellite observation.",
    summary: "The January 15, 2022 eruption of Hunga Tonga-Hunga Ha'apai in the South Pacific produced an eruption plume that reached approximately 57 km in altitude — well into the mesosphere, and by a wide margin the tallest volcanic plume ever measured by satellite, surpassing the previous record (Pinatubo in 1991, which reached about 40 km). The same eruption also generated the most intense volcanic lightning storm ever recorded, with over 192,000 lightning events detected in a single six-hour window, and triggered a globally observed atmospheric pressure wave and tsunami.",
    value: "57",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Stereoscopic satellite imagery from multiple geostationary weather satellites, used to triangulate plume-top altitude, published in a peer-reviewed study (Proud, Prata & Schmauss, 2022).",
    source: { title: "Proud, Prata & Schmauss, \"The January 2022 eruption of Hunga Tonga-Hunga Ha'apai volcano reached the mesosphere,\" Science", url: "https://www.science.org/doi/10.1126/science.abo4076", date: "2022-05-19", location: "Hunga Tonga-Hunga Ha'apai, Tonga, South Pacific" },
  },
  {
    registryNumber: "LR-MOST-INTENSE-GEOMAGNETIC-STORM", slug: "most-intense-geomagnetic-storm-on-record", title: "Most intense geomagnetic storm on record",
    category: "Earth & Climate", subcategory: "Space Weather", direction: "MAXIMIZE",
    metricName: "Estimated peak magnitude of geomagnetic disturbance (Dst index) during the most intense recorded geomagnetic storm", unit: "nT",
    formalStatement: "The greatest magnitude of geomagnetic disturbance, reconstructed from historical magnetometer records, ever attributed to a single solar-driven storm.",
    summary: "The Carrington Event of September 1859, triggered by an intense solar flare and coronal mass ejection observed by British astronomer Richard Carrington, produced the most intense geomagnetic storm on record, with a reconstructed peak Dst index of roughly -1,600 to -1,760 nT — far exceeding any storm in the modern satellite era. It induced currents strong enough to spark fires in telegraph offices and produced aurorae visible as far south as the Caribbean and Colombia; a storm of similar scale today would be expected to cause widespread damage to electrical grids and satellites.",
    value: "1600",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Reconstruction from historical ground-based magnetometer records (Colaba Observatory, India) combined with modern geomagnetic-storm modeling, published in peer-reviewed space-weather literature.",
    source: { title: "NOAA Space Weather Prediction Center — The Carrington Event", url: "https://www.swpc.noaa.gov/news/great-space-weather-events-history", date: "1859-09-02", location: "Global, observed from Colaba Observatory, Bombay, India and elsewhere" },
  },
  {
    registryNumber: "LR-HIGHEST-AVERAGE-ANNUAL-TEMPERATURE", slug: "highest-average-annual-temperature-of-any-inhabited-place", title: "Highest average annual temperature of any inhabited place",
    category: "Earth & Climate", subcategory: "Weather Extremes", direction: "MAXIMIZE",
    metricName: "Highest long-term average annual air temperature recorded at a permanently inhabited location", unit: "°C",
    formalStatement: "The highest long-term average annual air temperature recorded at any permanently inhabited settlement, as distinct from any single-day temperature extreme.",
    summary: "Dallol, a small settlement in Ethiopia's Danakil Depression, recorded an average annual temperature of about 34.4°C over a six-year measurement period (1960-1966) — the highest average annual temperature ever recorded for a permanently inhabited place, according to Guinness World Records. The extreme heat comes from Dallol's location roughly 125 m below sea level in one of the hottest, most volcanically active deserts on Earth.",
    value: "34.4",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Multi-year meteorological station averaging, cited by Guinness World Records and standard climatology references.",
    source: { title: "Guinness World Records — Hottest place, annual mean temperature", url: "https://www.guinnessworldrecords.com/world-records/hottest-place-annual-mean-temperature", date: "1966-01-01", location: "Dallol, Danakil Depression, Ethiopia" },
  },
  {
    registryNumber: "LR-STRONGEST-OCEAN-CURRENT-TRANSPORT", slug: "largest-ocean-current-by-volume-transport", title: "Largest ocean current by volume transport",
    category: "Earth & Climate", subcategory: "Oceanography", direction: "MAXIMIZE",
    metricName: "Estimated volume transport of the largest ocean current", unit: "Sverdrups",
    formalStatement: "The greatest estimated volume of water transported by any single ocean current, measured in Sverdrups (1 Sv = 1 million m³/s).",
    summary: "The Antarctic Circumpolar Current, which flows unbroken around Antarctica and connects the Atlantic, Pacific, and Indian Oceans, carries an estimated 100-170 Sverdrups of water through the Drake Passage — more than 100 times the combined flow of every river on Earth — making it by far the largest ocean current by volume transport. Its exact transport estimate has been revised upward across studies as measurement techniques have improved, so the figure should be read as an active area of oceanographic research rather than a single settled number.",
    value: "135",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Direct current-meter mooring arrays and satellite altimetry combined with ocean circulation models, synthesized across multiple oceanographic studies.",
    source: { title: "British Antarctic Survey — The Antarctic Circumpolar Current", url: "https://www.bas.ac.uk/data/our-data/publication/the-antarctic-circumpolar-current/", date: "2018-01-01", location: "Southern Ocean, Drake Passage" },
  },
  {
    registryNumber: "LR-LARGEST-TRANSATLANTIC-DUST-PLUME", slug: "largest-trans-atlantic-saharan-dust-plume-recorded-by-satellite", title: "Largest trans-Atlantic Saharan dust plume recorded by satellite",
    category: "Earth & Climate", subcategory: "Atmospheric Science", direction: "MAXIMIZE",
    metricName: "Approximate distance traveled by the most significant Saharan dust plume observed crossing the Atlantic in the satellite era", unit: "km",
    formalStatement: "The approximate distance traveled by the most significant single Saharan dust plume tracked by satellite as it crossed the Atlantic Ocean and reached the Americas.",
    summary: "In June 2020, a uniquely dense plume of Saharan dust — nicknamed the 'Godzilla dust cloud' by NASA researchers — traveled roughly 8,000 km across the Atlantic Ocean from West Africa to the Caribbean and southern United States, described by NASA and NOAA as the most significant such event observed in the satellite record of the past several decades. Saharan dust plumes cross the Atlantic most years, but the 2020 event stood out for its density and areal extent as measured by satellite aerosol instruments; this is a qualitative 'most significant observed' claim from atmospheric scientists rather than a strict numerical record maintained by a standards body.",
    value: "8000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Satellite aerosol optical depth tracking (NASA/NOAA GOES and CALIPSO instruments), reported by NASA Earth Observatory.",
    source: { title: "NASA Earth Observatory — Saharan Dust Blots Out the Sky", url: "https://earthobservatory.nasa.gov/images/146914/saharan-dust-plume-choking-the-caribbean", date: "2020-06-24", location: "Tracked via satellite from West Africa to the Caribbean and Gulf of Mexico" },
  },

  // --- Geography ---
  {
    registryNumber: "LR-LARGEST-DESERT-ALL-TYPES", slug: "largest-desert-of-any-kind-including-polar", title: "Largest desert of any kind (including polar deserts)",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Surface area of the largest desert on Earth, using a precipitation-based definition that includes cold and polar deserts", unit: "km²",
    formalStatement: "The greatest surface area of any region classified as a desert under a precipitation-based definition that includes cold and polar deserts, distinct from a comparison restricted to hot deserts only.",
    summary: "Under the standard climatological definition of a desert as any region receiving very little precipitation, Antarctica — not the Sahara — is the largest desert on Earth, covering roughly 14.2 million km². The Sahara remains the largest hot desert, but Antarctica's extreme dryness (some interior areas receive under 50 mm of precipitation per year, nearly all as snow) qualifies the entire continent as a polar desert under this broader definition.",
    value: "14200000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Climatological classification based on annual precipitation thresholds, per British Antarctic Survey and NOAA definitions of desert biomes.",
    source: { title: "British Antarctic Survey — Antarctica the driest continent", url: "https://www.bas.ac.uk/", date: "2015-01-01", location: "Antarctica" },
  },
  {
    registryNumber: "LR-DEEPEST-LAND-CANYON", slug: "deepest-land-canyon-on-earth", title: "Deepest land canyon on Earth",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Maximum depth from rim to river floor of the deepest terrestrial canyon", unit: "m",
    formalStatement: "The greatest depth from rim to valley floor of any canyon on Earth's land surface, as commonly cited in geographic references, acknowledging that competing claims exist depending on measurement methodology.",
    summary: "The Yarlung Tsangpo Grand Canyon in Tibet, carved by the Yarlung Tsangpo (Brahmaputra) River as it curves around the Himalayan peak of Namcha Barwa, reaches a depth of roughly 5,382 m at its deepest point — commonly cited as the deepest land canyon on Earth, well over three times the depth of the Grand Canyon in the United States (up to about 1.8 km). The claim is genuinely contested: Peru's Cotahuasi Canyon and Colca Canyon are sometimes cited as rivals depending on whether depth is measured from the canyon's true rim or from a nearby peak, and measurement methodology varies across sources.",
    value: "5382",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Topographic survey and satellite elevation modeling of the canyon rim and river floor, as reported in Chinese geographic survey literature and international geographic references.",
    source: { title: "Encyclopaedia Britannica — Yarlung Zangbo Canyon", url: "https://www.britannica.com/place/Yarlung-Zangbo-Canyon", date: "2020-01-01", location: "Tibet Autonomous Region, China" },
  },
  {
    registryNumber: "LR-LARGEST-TROPICAL-WETLAND", slug: "largest-tropical-wetland-on-earth", title: "Largest tropical wetland on Earth",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Surface area of the largest tropical freshwater wetland", unit: "km²",
    formalStatement: "The greatest surface area of any tropical freshwater wetland ecosystem on Earth, distinct from a mangrove-forest-specific comparison.",
    summary: "The Pantanal, spanning parts of Brazil, Bolivia, and Paraguay, covers an estimated 150,000-195,000 km² of seasonally flooded grassland and forest — the largest tropical wetland on Earth, roughly ten times the size of Florida's Everglades. Its size is inherently fuzzy to pin down precisely because its flooded extent expands and contracts dramatically between wet and dry seasons.",
    value: "150000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Satellite-based land-cover mapping and hydrological survey, compiled by conservation organizations including WWF.",
    source: { title: "WWF — Pantanal", url: "https://www.worldwildlife.org/places/pantanal", date: "2019-01-01", location: "Brazil, Bolivia, and Paraguay" },
  },
  {
    registryNumber: "LR-TALLEST-MOUNTAIN-BASE-TO-PEAK", slug: "tallest-mountain-measured-base-to-summit", title: "Tallest mountain measured base to summit",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Height of the tallest mountain measured from its base (including any portion below sea level) to its summit", unit: "m",
    formalStatement: "The greatest total height of any mountain measured from its true base — including any portion submerged below sea level — to its summit, as distinct from height measured relative to sea level alone.",
    summary: "Mauna Kea, a dormant volcano in Hawaii, rises about 10,210 m from its base on the Pacific Ocean floor to its summit, of which only about 4,207 m is above sea level — making it taller than Mount Everest (8,849 m above sea level) when measured base-to-peak, even though it falls far short of Everest's official 'highest point on Earth' record, which is measured relative to sea level rather than from a mountain's true base.",
    value: "10210",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Bathymetric and topographic survey combining seafloor depth at the volcano's base with summit elevation, per USGS and NOAA data.",
    source: { title: "USGS Hawaiian Volcano Observatory — Mauna Kea", url: "https://www.usgs.gov/volcanoes/mauna-kea", date: "2015-01-01", location: "Island of Hawaii, USA" },
  },
  {
    registryNumber: "LR-TALLEST-SAND-DUNES", slug: "tallest-sand-dunes-on-earth", title: "Tallest sand dunes on Earth",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Height of the tallest stationary sand dunes on Earth", unit: "m",
    formalStatement: "The greatest height of any stationary (non-migrating) sand dune formation on Earth, as recognized by Guinness World Records.",
    summary: "The Badain Jaran Desert in Inner Mongolia, China, contains sand dunes reaching heights of roughly 460-500 m — recognized by Guinness World Records as the tallest stationary sand dunes on Earth. Unusually, the desert also contains over 100 spring-fed lakes nestled among the dunes, a rare combination that scientists have studied to understand how such a dune field forms and remains stable rather than migrating like most large dune fields.",
    value: "500",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Topographic survey and satellite elevation measurement, cited in Guinness World Records and Chinese geographic survey literature.",
    source: { title: "Guinness World Records — Tallest sand dunes", url: "https://www.guinnessworldrecords.com/world-records/tallest-sand-dunes", date: "2018-01-01", location: "Badain Jaran Desert, Inner Mongolia, China" },
  },
  {
    registryNumber: "LR-LARGEST-SAND-SEA", slug: "largest-contiguous-sand-desert-erg", title: "Largest contiguous sand desert (erg)",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Surface area of the largest contiguous sand sea (erg)", unit: "km²",
    formalStatement: "The greatest surface area of any single contiguous sand sea (erg), as distinct from the total area of a broader desert region that includes rocky or gravel terrain.",
    summary: "The Rub' al Khali (Empty Quarter), spanning parts of Saudi Arabia, Oman, the UAE, and Yemen, covers roughly 650,000 km² of continuous sand — the largest contiguous sand sea (erg) on Earth. This is a distinct comparison from the Sahara's status as the largest hot desert overall, since much of the Sahara is rocky or gravel terrain (reg and hamada) rather than sand.",
    value: "650000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Satellite land-cover classification distinguishing sand-sea (erg) terrain from rocky desert terrain, per standard physical geography references.",
    source: { title: "Encyclopaedia Britannica — Rub' al-Khali", url: "https://www.britannica.com/place/Rub-al-Khali", date: "2020-01-01", location: "Arabian Peninsula" },
  },
  {
    registryNumber: "LR-OLDEST-DESERT-ON-EARTH", slug: "oldest-desert-on-earth", title: "Oldest desert on Earth",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Estimated age of the oldest desert on Earth that has remained continuously arid", unit: "million years",
    formalStatement: "The greatest estimated length of time any of Earth's deserts has remained continuously arid, based on geological and paleoclimate evidence.",
    summary: "The Namib Desert, along the Atlantic coast of Namibia, is widely considered the oldest desert on Earth, with geological evidence suggesting it has remained continuously arid for at least 55-80 million years, cooled and dried by the cold Benguela ocean current offshore. The exact age estimate varies across studies depending on which sedimentary evidence is used, so it is best treated as an approximate, actively researched figure rather than a single precise number.",
    value: "55",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Sedimentary and geomorphological dating of desert landforms, synthesized across paleoclimate and geology literature.",
    source: { title: "Encyclopaedia Britannica — Namib Desert", url: "https://www.britannica.com/place/Namib-Desert", date: "2019-01-01", location: "Namibia, southwestern Africa" },
  },
  {
    registryNumber: "LR-LARGEST-ATOLL-LAND-AREA", slug: "largest-coral-atoll-by-land-area", title: "Largest coral atoll by land area",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Total dry land area of the largest coral atoll on Earth", unit: "km²",
    formalStatement: "The greatest total dry land area of any coral atoll on Earth.",
    summary: "Kiritimati (Christmas Island), part of the Republic of Kiribati in the central Pacific, has a total land area of about 388 km² — the largest coral atoll on Earth by land area, despite its low elevation (nowhere more than a few meters above sea level) making it especially vulnerable to sea-level rise. It also hosts one of the largest seabird breeding colonies in the world.",
    value: "388",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Land-area survey via satellite imagery and national geographic records of Kiribati.",
    source: { title: "Encyclopaedia Britannica — Kiritimati", url: "https://www.britannica.com/place/Kiritimati", date: "2019-01-01", location: "Republic of Kiribati, central Pacific Ocean" },
  },
  {
    registryNumber: "LR-LARGEST-TIDAL-BORE", slug: "largest-tidal-bore-on-earth", title: "Largest tidal bore on Earth",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Maximum recorded wave height of the largest tidal bore on Earth", unit: "m",
    formalStatement: "The greatest recorded wave height of any tidal bore (a tide-driven wave that travels up a river against the current) on Earth.",
    summary: "The Qiantang River tidal bore, in eastern China, can reach wave heights of up to about 9 m and travel at speeds over 40 km/h as it surges upstream against the river's current — the largest tidal bore on Earth, drawing large crowds who gather along the riverbanks (sometimes dangerously close) to watch it each year, especially at the autumn equinox when it is strongest.",
    value: "9",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Hydrological survey and tide-gauge measurement by Chinese river authorities, corroborated by international tidal-bore research literature.",
    source: { title: "Encyclopaedia Britannica — Qiantang River", url: "https://www.britannica.com/place/Qiantang-River", date: "2019-01-01", location: "Zhejiang Province, China" },
  },
  {
    registryNumber: "LR-LARGEST-SUBGLACIAL-LAKE", slug: "largest-known-subglacial-lake", title: "Largest known subglacial lake",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Surface area of the largest known lake beneath a glacier or ice sheet", unit: "km²",
    formalStatement: "The greatest surface area of any known lake of liquid water trapped beneath a glacier or ice sheet.",
    summary: "Lake Vostok, buried beneath roughly 4 km of Antarctic ice near Russia's Vostok Station, covers an estimated 12,500 km² — comparable in area to Lake Ontario — making it the largest known subglacial lake on Earth. Kept liquid by geothermal heat and immense pressure despite sitting under one of the coldest places on the planet, it had been isolated from the surface for possibly millions of years before Russian researchers drilled into it in 2012.",
    value: "12500",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Ice-penetrating radar surveys conducted by British, Russian, and American Antarctic research programs.",
    source: { title: "British Antarctic Survey — Lake Vostok", url: "https://www.bas.ac.uk/data/our-data/publication/lake-vostok/", date: "2012-02-01", location: "Vostok Station, East Antarctica" },
  },
  {
    registryNumber: "LR-CONTINENTAL-POLE-OF-INACCESSIBILITY", slug: "continental-pole-of-inaccessibility", title: "Continental pole of inaccessibility (farthest point from any ocean)",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Distance from the farthest inland point on Earth's landmass to the nearest coastline", unit: "km",
    formalStatement: "The greatest straight-line distance from any point on Earth's continental landmass to the nearest ocean coastline.",
    summary: "The Eurasian pole of inaccessibility, located in the Dzoosotoyn Elisen desert of Xinjiang, China, sits approximately 2,645 km from the nearest coastline in any direction — the farthest any point on a continental landmass gets from the sea. Because the exact figure depends on the coastline dataset and calculation method used, published estimates for this point vary by a few hundred kilometers.",
    value: "2645",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Geographic information system (GIS) analysis computing minimum distance from every inland point to the nearest mapped coastline.",
    source: { title: "National Geographic Society — Pole of Inaccessibility", url: "https://education.nationalgeographic.org/resource/pole-inaccessibility/", date: "2011-01-01", location: "Dzoosotoyn Elisen, Xinjiang, China" },
  },
  {
    registryNumber: "LR-SALTIEST-NATURAL-WATER-BODY", slug: "saltiest-known-natural-body-of-water-on-earth", title: "Saltiest known natural body of water on Earth",
    category: "Geography", subcategory: "Hydrology", direction: "MAXIMIZE",
    metricName: "Salinity concentration of the saltiest known natural body of water", unit: "g/L",
    formalStatement: "The highest dissolved-salt concentration measured in any known naturally occurring body of water on Earth.",
    summary: "Gaet'ale Pond, a small hypersaline pool in Ethiopia's Danakil Depression, was measured in a 2022 scientific study at a salinity of roughly 433 g/L (about 43% dissolved salt by weight) — surpassing Antarctica's Don Juan Pond (previously considered the saltiest natural body of water) to become the saltiest known natural body of water on Earth. Despite the extreme salinity and near-boiling surface temperatures nearby, researchers found evidence of microbial life adapted to the pond's harsh chemistry.",
    value: "433",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Direct water sampling and salinity/ion analysis conducted by an international research team studying the Danakil Depression's hypersaline ponds.",
    source: { title: "Belilla et al., research on hypersaline ponds of the Danakil Depression, Ethiopia", url: "https://www.nature.com/", date: "2022-06-01", location: "Danakil Depression, Ethiopia" },
  },
  {
    registryNumber: "LR-LARGEST-NATIONAL-PARK", slug: "largest-national-park-in-the-world", title: "Largest national park in the world",
    category: "Geography", subcategory: "Human Geography", direction: "MAXIMIZE",
    metricName: "Total area of the largest single national park on Earth", unit: "km²",
    formalStatement: "The greatest total protected area of any single designated national park on Earth.",
    summary: "Northeast Greenland National Park covers approximately 972,000 km² — larger than every country in the world except the 30 or so largest — making it by far the largest national park on Earth, roughly seven times the size of the next-largest. Established in 1974 and later expanded, it protects one of the last great wilderness areas on Earth, home to muskoxen, polar bears, and narwhals, with almost no permanent human population.",
    value: "972000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official protected-area boundary designation by the Government of Greenland/Denmark.",
    source: { title: "Encyclopaedia Britannica — Northeast Greenland National Park", url: "https://www.britannica.com/place/Northeast-Greenland-National-Park", date: "2019-01-01", location: "Northeastern Greenland" },
  },
  {
    registryNumber: "LR-LARGEST-UNDERWATER-WATERFALL", slug: "largest-underwater-cascade-on-earth", title: "Largest underwater cascade on Earth",
    category: "Geography", subcategory: "Oceanography", direction: "MAXIMIZE",
    metricName: "Total vertical drop of the largest known underwater density-driven cascade", unit: "m",
    formalStatement: "The greatest total vertical drop of any known underwater cascade, where dense cold water sinks and flows over a submarine sill — a distinct oceanographic phenomenon from any above-water waterfall.",
    summary: "Between Greenland and Iceland, cold, dense water from the Nordic Seas sinks and cascades over the Denmark Strait sill into the deeper Irminger Basin, dropping roughly 3,505 m in total — a far greater vertical drop than any waterfall above sea level, though it is a slow, diffuse density-driven current rather than a visible plunging waterfall. It is a key part of the global thermohaline ocean circulation that helps drive deep-ocean water mass formation in the North Atlantic.",
    value: "3505",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Oceanographic current and bathymetric survey of the Denmark Strait overflow, published in physical oceanography literature.",
    source: { title: "Woods Hole Oceanographic Institution — Denmark Strait overflow research", url: "https://www.whoi.edu/", date: "2017-01-01", location: "Denmark Strait, between Greenland and Iceland" },
  },
  {
    registryNumber: "LR-LARGEST-LAKE-SINGLE-COUNTRY", slug: "largest-lake-located-entirely-within-one-country", title: "Largest lake located entirely within one country",
    category: "Geography", subcategory: "Physical Geography", direction: "MAXIMIZE",
    metricName: "Surface area of the largest lake whose entire shoreline lies within a single country's borders", unit: "km²",
    formalStatement: "The greatest surface area of any lake located entirely within the borders of a single country, as distinct from the largest lake overall (which is transboundary).",
    summary: "Lake Michigan, one of North America's Great Lakes, covers approximately 58,000 km² and lies entirely within the United States — unlike the other Great Lakes, which are shared with Canada — making it the largest lake located entirely within a single country. This is a distinct comparison from the largest lake overall (the transboundary Caspian Sea) and from the largest lake by depth or volume (Russia's Lake Baikal, also entirely within one country but far smaller in surface area).",
    value: "58000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Standard geographic surface-area measurement and national boundary determination, per NOAA Great Lakes data.",
    source: { title: "NOAA Great Lakes Environmental Research Laboratory — Lake Michigan", url: "https://www.glerl.noaa.gov/", date: "2018-01-01", location: "Michigan, Wisconsin, Illinois, and Indiana, USA" },
  },
];
