import type { FrontierRecord } from "./frontier-records-2026";

// Eighth real-world-records batch — Sports Records, Speed Records, Economics, History, and Food &
// Culture. Cross-checked against the full existing catalog (1,350+ entries across all files) before
// writing, not just the topic list supplied at drafting time — several initially planned topics
// (Test cricket's highest score and most career wickets, fastest production car, fastest train,
// fastest crewed airplane, fastest human-made object, fastest commercial aircraft, fastest bird in
// level flight, highest-denomination banknote, largest sovereign wealth fund, largest IPO, largest
// corporate bankruptcy, highest Fed policy rate, longest monarch reign, oldest university (both
// Al-Qarawiyyin and Bologna), oldest law code, oldest peace treaty, longest-held tallest-structure
// record, oldest writing system, and largest ancient library) turned out to already exist under
// those or adjacent titles and were dropped in favor of genuinely distinct angles. A "fastest
// production car" entry was deliberately not reintroduced for the same reason speed-records.ts
// already excludes one: no single two-way-averaged, uncontested figure exists. Fast-moving figures
// (Hour Record, F1 speed trap, WSM titles, GDP, sovereign debt levels, currency values) are marked
// LITERATURE_ASSERTED and framed with an explicit as-of date rather than presented as permanently
// current.
export const WORLD_RECORDS_BATCH8_CULTURE_SPORTS: FrontierRecord[] = [
  // --- Sports Records ---
  {
    registryNumber: "LR-HIGHEST-ODI-INNINGS-SCORE", slug: "highest-individual-score-odi-cricket", title: "Highest individual score in a One Day International cricket innings",
    category: "Sports Records", subcategory: "Cricket", direction: "MAXIMIZE",
    metricName: "Runs scored by a single batter in one ODI innings", unit: "runs",
    formalStatement: "The greatest number of runs scored by an individual batter in a single innings of a One Day International cricket match, as recorded by the International Cricket Council.",
    summary: "Rohit Sharma of India scored 264 runs off 173 balls against Sri Lanka in Kolkata on November 13, 2014, the highest individual score ever recorded in a One Day International — surpassing his own earlier record of 209, also against Australia, set the previous year.",
    value: "264",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official ODI match scorecard certified by the International Cricket Council.",
    source: { title: "International Cricket Council — ODI Batting Records", url: "https://www.icc-cricket.com/", date: "2014-11-13", location: "Kolkata, India" },
  },
  {
    registryNumber: "LR-RWC-ALL-TIME-POINTS-SCORER", slug: "rugby-world-cup-all-time-points-scorer", title: "Rugby World Cup all-time leading points scorer",
    category: "Sports Records", subcategory: "Rugby Union", direction: "MAXIMIZE",
    metricName: "Total points scored by a single player across all Rugby World Cup tournaments", unit: "points",
    formalStatement: "The greatest cumulative number of points scored by an individual player across all editions of the Rugby World Cup, as recorded by World Rugby.",
    summary: "England fly-half Jonny Wilkinson scored 277 points across the 1999, 2003, 2007, and 2011 Rugby World Cups, the most of any player in the tournament's history — including the drop goal that won the 2003 final against Australia.",
    value: "277",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Cumulative official World Rugby tournament statistics across four Rugby World Cup editions.",
    source: { title: "World Rugby — Rugby World Cup Records", url: "https://www.world.rugby/", date: "2011-10-23", location: "Multiple venues" },
  },
  {
    registryNumber: "LR-MOST-CONSECUTIVE-HEAVYWEIGHT-TITLE-DEFENSES", slug: "most-consecutive-heavyweight-boxing-title-defenses", title: "Most consecutive heavyweight boxing title defenses",
    category: "Sports Records", subcategory: "Boxing", direction: "MAXIMIZE",
    metricName: "Number of successful title defenses by a reigning heavyweight boxing champion", unit: "defenses",
    formalStatement: "The greatest number of consecutive successful title defenses by a single reigning world heavyweight boxing champion.",
    summary: "Joe Louis defended the world heavyweight title 25 times between 1937 and 1949, a record for consecutive heavyweight title defenses that remains unmatched — a stretch of dominance nicknamed the 'Bum of the Month Club' by sportswriters of the era.",
    value: "25",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Boxing record maintained by the International Boxing Hall of Fame based on sanctioned title bouts.",
    source: { title: "International Boxing Hall of Fame — Joe Louis", url: "https://ibhof.com/", date: "1949-03-01", location: "United States" },
  },
  {
    registryNumber: "LR-LONGEST-UNBEATEN-STREAK-GRECO-ROMAN-WRESTLING", slug: "longest-unbeaten-streak-greco-roman-wrestling", title: "Longest unbeaten streak by an Olympic Greco-Roman wrestling champion",
    category: "Sports Records", subcategory: "Wrestling", direction: "MAXIMIZE",
    metricName: "Duration of an unbeaten competitive streak by a super-heavyweight Greco-Roman wrestler", unit: "years",
    formalStatement: "The longest widely-reported continuous unbeaten streak by an individual competitor in top-level Greco-Roman wrestling, from first major loss to next.",
    summary: "Russian wrestler Aleksandr Karelin went unbeaten in international super-heavyweight Greco-Roman wrestling for about 13 years, from 1987 until his stunning loss to American Rulon Gardner in the final of the 2000 Sydney Olympics — a streak widely regarded as one of the most dominant in the sport's history, though no federation formally certifies 'unbeaten streaks' as a statistic.",
    value: "13",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Compiled from international Greco-Roman wrestling competition results and widely repeated historical sports reporting.",
    source: { title: "International Olympic Committee — Aleksandr Karelin", url: "https://www.olympics.com/en/athletes/aleksandr-karelin", date: "2000-09-27", location: "Sydney, Australia" },
  },
  {
    registryNumber: "LR-MOST-PARALYMPIC-GOLD-MEDALS-INDIVIDUAL", slug: "most-paralympic-gold-medals-individual-athlete", title: "Most Paralympic gold medals won by an individual athlete",
    category: "Sports Records", subcategory: "Paralympic Sports", direction: "MAXIMIZE",
    metricName: "Total career Paralympic gold medals won by a single athlete", unit: "gold medals",
    formalStatement: "The greatest number of individual Paralympic Games gold medals won by a single athlete across their competitive career.",
    summary: "American Paralympic swimmer Trischa Zorn, who is blind, won 41 gold medals (55 medals overall) across the 1980 to 2004 Paralympic Games — the most gold medals and the most total medals of any athlete in Paralympic history, across any sport.",
    value: "41",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Cumulative official medal records maintained by the International Paralympic Committee.",
    source: { title: "International Paralympic Committee — Trischa Zorn", url: "https://www.paralympic.org/", date: "2004-09-28", location: "Multiple venues" },
  },
  {
    registryNumber: "LR-MOST-GYMNASTICS-GOLDS-SINGLE-OLYMPICS", slug: "most-gymnastics-gold-medals-single-olympic-games", title: "Most gold medals won by a gymnast at a single Olympic Games",
    category: "Sports Records", subcategory: "Gymnastics", direction: "MAXIMIZE",
    metricName: "Gold medals won by an individual gymnast at one Olympic Games", unit: "gold medals",
    formalStatement: "The greatest number of gold medals won by a single gymnast across all events at one edition of the Olympic Games.",
    summary: "Vitaly Scherbo, competing for the Unified Team of former Soviet republics at the 1992 Barcelona Olympics, won six gold medals in gymnastics — team combined exercises, the individual all-around, and four apparatus finals — the most golds ever won by a gymnast at a single Olympics.",
    value: "6",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official Olympic medal records maintained by the International Olympic Committee.",
    source: { title: "International Olympic Committee — Vitaly Scherbo", url: "https://www.olympics.com/en/athletes/vitaly-scherbo", date: "1992-08-08", location: "Barcelona, Spain" },
  },
  {
    registryNumber: "LR-UCI-HOUR-RECORD-CYCLING", slug: "uci-hour-record-track-cycling", title: "UCI Hour Record (track cycling)",
    category: "Sports Records", subcategory: "Track Cycling", direction: "MAXIMIZE",
    metricName: "Greatest unpaced distance covered by a cyclist on a velodrome in one hour", unit: "km",
    formalStatement: "The greatest distance covered by a cyclist riding alone and unpaced on a velodrome in exactly one hour, under UCI rules for the modern 'Best Human Effort' Hour Record.",
    summary: "Italian cyclist Filippo Ganna covered 56.792 km in one hour at the Tissot Velodrome in Grenchen, Switzerland, on October 8, 2022, setting the UCI Hour Record as of that date. The record has changed hands repeatedly over the decades as equipment rules evolved, so this figure should be read as 'the record as of October 2022' rather than a permanently settled number.",
    value: "56.792",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "UCI-certified velodrome time trial performed under official Hour Record regulations.",
    source: { title: "Union Cycliste Internationale — Hour Record", url: "https://www.uci.org/", date: "2022-10-08", location: "Grenchen, Switzerland" },
  },
  {
    registryNumber: "LR-HEAVIEST-OLYMPIC-CLEAN-AND-JERK", slug: "heaviest-olympic-clean-and-jerk-super-heavyweight", title: "Heaviest clean & jerk lift at an Olympic Games (super-heavyweight)",
    category: "Sports Records", subcategory: "Weightlifting", direction: "MAXIMIZE",
    metricName: "Heaviest clean & jerk successfully lifted in Olympic men's super-heavyweight competition", unit: "kg",
    formalStatement: "The greatest weight successfully lifted in the clean & jerk discipline by a men's super-heavyweight (+109kg/+110kg category) weightlifter at an Olympic Games.",
    summary: "Georgian weightlifter Lasha Talakhadze lifted 265 kg in the clean & jerk at the Tokyo 2020 Olympics (held in August 2021), setting an Olympic record in the men's +109kg category as part of a then-world-record 488 kg total — the standard against which subsequent super-heavyweight lifting has been measured.",
    value: "265",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "IWF-certified competition lift, verified by International Weightlifting Federation officials and doping control.",
    source: { title: "International Weightlifting Federation — Tokyo 2020 Results", url: "https://iwf.sport/", date: "2021-08-04", location: "Tokyo, Japan" },
  },
  {
    registryNumber: "LR-FASTEST-MAXIMUM-BREAK-SNOOKER", slug: "fastest-maximum-147-break-snooker", title: "Fastest maximum 147 break in professional snooker",
    category: "Sports Records", subcategory: "Snooker", direction: "MINIMIZE",
    metricName: "Time taken to compile a maximum 147 break in a professional snooker frame", unit: "s",
    formalStatement: "The shortest elapsed time in which a professional snooker player has compiled a maximum break of 147 points in a single frame.",
    summary: "Ronnie O'Sullivan compiled a maximum 147 break in 5 minutes and 20 seconds during the first round of the 1997 World Snooker Championship at the Crucible Theatre, against Mick Price — the fastest maximum break ever recorded in professional competition.",
    value: "320",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Timed and ratified by World Snooker Tour officials during televised championship play.",
    source: { title: "World Snooker Tour — Fastest 147 Break", url: "https://www.wst.tv/", date: "1997-04-21", location: "Sheffield, England" },
  },
  {
    registryNumber: "LR-FIRST-TELEVISED-NINE-DART-FINISH", slug: "first-televised-nine-dart-finish-darts", title: "First televised nine-dart finish in professional darts",
    category: "Sports Records", subcategory: "Darts", direction: "MINIMIZE",
    metricName: "Darts thrown to complete a standard 501 leg, first achieved on television", unit: "darts",
    formalStatement: "The fewest possible darts (nine) needed to complete a standard 501 leg, first achieved during a televised professional darts tournament.",
    summary: "English darts player John Lowe threw the first nine-dart finish achieved on televised competition, during the 1984 World Matchplay, winning a bonus prize of £102,000 for the feat — nine darts being the theoretical minimum needed to complete a 501 leg.",
    value: "9",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Officiated and broadcast during a sanctioned televised professional darts tournament (ITV).",
    source: { title: "Darts Database — Nine-Dart Finish History", url: "https://www.dartsdatabase.co.uk/", date: "1984-10-13", location: "England" },
  },
  {
    registryNumber: "LR-FIRST-CERTIFIED-900-SERIES-BOWLING", slug: "first-certified-900-series-ten-pin-bowling", title: "First USBC-certified 900 series in ten-pin bowling",
    category: "Sports Records", subcategory: "Ten-Pin Bowling", direction: "MAXIMIZE",
    metricName: "Highest possible three-game series score in ten-pin bowling (three consecutive perfect games)", unit: "pins",
    formalStatement: "The maximum possible score across three consecutive games of ten-pin bowling (three perfect 300 games), first officially certified as legitimate.",
    summary: "Jeremy Sonnenfeld bowled three consecutive perfect games — a 900 series — on February 2, 1997, in Lincoln, Nebraska, the first 900 series ever certified by the American Bowling Congress (predecessor to today's United States Bowling Congress), a feat so rare that only a small handful of bowlers have repeated it since.",
    value: "900",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Certified by the American Bowling Congress following equipment and lane inspection.",
    source: { title: "United States Bowling Congress — 900 Series History", url: "https://www.bowl.com/", date: "1997-02-02", location: "Lincoln, Nebraska, USA" },
  },
  {
    registryNumber: "LR-FIRST-62-MENS-MAJOR-GOLF-ROUND", slug: "first-62-scored-in-a-mens-major-golf-championship", title: "First round of 62 scored in a men's major golf championship",
    category: "Sports Records", subcategory: "Golf", direction: "MINIMIZE",
    metricName: "Lowest 18-hole round score recorded in men's major championship golf, first instance", unit: "strokes",
    formalStatement: "The first instance of a golfer completing an 18-hole round in 62 strokes at a men's major championship.",
    summary: "South African golfer Branden Grace shot a final-round 62 at the 2017 Open Championship at Royal Birkdale, becoming the first player in the history of men's major championship golf to break 63 in a major round — a barrier since matched by other players but first broken by Grace.",
    value: "62",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official scoring certified by The R&A during a sanctioned major championship.",
    source: { title: "The Open Championship — Records", url: "https://www.theopen.com/", date: "2017-07-23", location: "Royal Birkdale, England" },
  },
  {
    registryNumber: "LR-MILE-RUN-WORLD-RECORD", slug: "mile-run-world-record", title: "Mile run world record (men)",
    category: "Sports Records", subcategory: "Track and Field", direction: "MINIMIZE",
    metricName: "Fastest time recorded for a men's outdoor one-mile foot race", unit: "s",
    formalStatement: "The fastest time recorded by a male athlete for the one-mile (1,609.344 m) foot race, ratified by World Athletics.",
    summary: "Moroccan middle-distance runner Hicham El Guerrouj ran a mile in 3:43.13 in Rome on July 7, 1999 — a record that, as of the most recent editions of this registry's sources, has stood for over two decades, longer than any previous mile world record of the modern era.",
    value: "223.13",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Electronically timed and ratified by World Athletics (then the IAAF) under standard record procedures.",
    source: { title: "World Athletics — Mile Records", url: "https://worldathletics.org/", date: "1999-07-07", location: "Rome, Italy" },
  },
  {
    registryNumber: "LR-MOST-WORLDS-STRONGEST-MAN-TITLES", slug: "most-worlds-strongest-man-titles", title: "Most World's Strongest Man titles won",
    category: "Sports Records", subcategory: "Strongman", direction: "MAXIMIZE",
    metricName: "Number of World's Strongest Man overall titles won by a single competitor", unit: "titles",
    formalStatement: "The greatest number of times a single competitor has won the annual World's Strongest Man multi-event strength competition.",
    summary: "Polish strongman Mariusz Pudzianowski won the World's Strongest Man title five times (2002, 2003, 2005, 2007, and 2008), the most of any competitor as of the most recent editions covered by this registry's sources — ahead of competitors such as Brian Shaw and Žydrūnas Savickas, who have each won four.",
    value: "5",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Annual competition results compiled by the World's Strongest Man organization.",
    source: { title: "World's Strongest Man — Past Winners", url: "https://theworldsstrongestman.com/", date: "2008-09-01", location: "Multiple venues" },
  },

  // --- Speed Records ---
  {
    registryNumber: "LR-FASTEST-STEAM-LOCOMOTIVE-SPEED", slug: "fastest-steam-locomotive-speed", title: "Fastest speed recorded by a steam locomotive",
    category: "Speed Records", subcategory: "Rail", direction: "MAXIMIZE",
    metricName: "Highest speed recorded by a steam-powered railway locomotive", unit: "km/h",
    formalStatement: "The highest speed officially recorded by a steam locomotive under controlled test conditions, distinct from the outright fastest-train record held by a maglev vehicle.",
    summary: "The LNER Class A4 steam locomotive 'Mallard' reached 126 mph (203 km/h) while descending Stoke Bank in Lincolnshire, England, on July 3, 1938 — the fastest speed ever recorded by a steam locomotive, a record that still stands today even though far faster non-steam trains now exist.",
    value: "203",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Recorded by an onboard dynamometer car during a sanctioned speed test run.",
    source: { title: "National Railway Museum — Mallard", url: "https://www.railwaymuseum.org.uk/", date: "1938-07-03", location: "Stoke Bank, Lincolnshire, England" },
  },
  {
    registryNumber: "LR-FASTEST-PASSENGER-ELEVATOR-SPEED", slug: "fastest-passenger-elevator-speed", title: "Fastest passenger elevator speed",
    category: "Speed Records", subcategory: "Vertical Transport", direction: "MAXIMIZE",
    metricName: "Fastest certified travel speed of a passenger elevator in commercial operation", unit: "m/s",
    formalStatement: "The highest certified travel speed of a passenger elevator in commercial operation.",
    summary: "The high-speed elevators installed by Mitsubishi Electric in the Shanghai Tower in China travel at up to 20.5 m/s (73.8 km/h / 45.8 mph), certified by Guinness World Records as the fastest elevators in the world.",
    value: "20.5",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Certified by Guinness World Records based on manufacturer specifications and independent testing.",
    source: { title: "Guinness World Records — Fastest Elevator", url: "https://www.guinnessworldrecords.com/", date: "2016-07-08", location: "Shanghai, China" },
  },
  {
    registryNumber: "LR-FASTEST-TORNADO-WIND-SPEED-ESTIMATE", slug: "fastest-tornado-wind-speed-estimate", title: "Fastest tornado wind speed ever estimated",
    category: "Speed Records", subcategory: "Meteorology", direction: "MAXIMIZE",
    metricName: "Highest near-surface wind speed ever estimated inside a tornado by mobile Doppler radar", unit: "km/h",
    formalStatement: "The highest wind speed ever estimated inside a tornado using mobile Doppler radar, distinct from the highest wind speed directly measured by a fixed surface anemometer (a separate record held by a non-tornadic cyclone gust).",
    summary: "A mobile Doppler-on-Wheels radar unit estimated a wind speed of roughly 484 km/h (301 mph), some tens of meters above the ground, inside the Bridge Creek–Moore tornado near Oklahoma City on May 3, 1999 — the highest wind speed ever attributed to a tornado. Because the reading is a radar-based estimate rather than a direct anemometer measurement, and was taken above ground level, meteorologists treat it as the highest tornadic wind speed estimate rather than a directly recorded surface value.",
    value: "484",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Mobile Doppler radar measurement analyzed by university and NOAA storm researchers.",
    source: { title: "NOAA National Severe Storms Laboratory", url: "https://www.nssl.noaa.gov/", date: "1999-05-03", location: "Bridge Creek–Moore, Oklahoma, USA" },
  },
  {
    registryNumber: "LR-FASTEST-SWIMMING-SPEED-SAILFISH", slug: "fastest-swimming-speed-attributed-to-a-fish", title: "Fastest swimming speed attributed to a fish (sailfish)",
    category: "Speed Records", subcategory: "Marine Biology", direction: "MAXIMIZE",
    metricName: "Peak burst swimming speed commonly attributed to the Atlantic sailfish", unit: "km/h",
    formalStatement: "The peak burst swimming speed commonly attributed to the sailfish, historically cited as the fastest swimming speed of any fish species.",
    summary: "The sailfish (Istiophorus platypterus) is commonly cited as the fastest fish in the ocean, with a widely repeated figure of around 110 km/h (68 mph) based on a 1940s measurement of fishing-line spooling speed. Modern hydrodynamic analyses argue this figure is likely a substantial overestimate and that sustained speeds are probably much lower, so this should be read as a widely cited but methodologically contested claim rather than a rigorously verified one.",
    value: "110",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Historical estimate based on fishing-reel line-spooling speed, since questioned by hydrodynamic modeling studies.",
    source: { title: "Florida Museum of Natural History — Ichthyology, Sailfish", url: "https://www.floridamuseum.ufl.edu/", date: "2018-01-01", location: "Atlantic and Pacific Oceans" },
  },
  {
    registryNumber: "LR-FASTEST-INSTANTANEOUS-HUMAN-SPRINT-SPEED", slug: "fastest-instantaneous-human-sprinting-speed", title: "Fastest instantaneous speed recorded for a human sprinter",
    category: "Speed Records", subcategory: "Athletics", direction: "MAXIMIZE",
    metricName: "Peak instantaneous running speed recorded for a human during a timed race segment", unit: "km/h",
    formalStatement: "The highest instantaneous (split-segment) running speed ever recorded for a human sprinter during an official race, distinct from average full-race pace.",
    summary: "During his 100 m world-record run of 9.58 seconds at the 2009 World Championships in Berlin, Usain Bolt reached a peak instantaneous speed of approximately 44.72 km/h (12.42 m/s) between the 60 m and 80 m marks — biomechanically the fastest a human has ever been recorded running.",
    value: "44.72",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Laser-velocity and high-speed video biomechanical analysis conducted alongside the IAAF-sanctioned championship.",
    source: { title: "World Athletics — Berlin 2009 Biomechanics Report", url: "https://worldathletics.org/", date: "2009-08-16", location: "Berlin, Germany" },
  },
  {
    registryNumber: "LR-FASTEST-SPEED-RECORDED-FORMULA-1-CAR", slug: "fastest-speed-recorded-by-a-formula-1-car", title: "Fastest speed ever recorded by a Formula 1 car",
    category: "Speed Records", subcategory: "Motorsport", direction: "MAXIMIZE",
    metricName: "Highest speed-trap reading recorded by a Formula 1 car during an official session", unit: "km/h",
    formalStatement: "The highest speed recorded by an FIA trackside speed trap for a Formula 1 car during an official Grand Prix weekend session.",
    summary: "Valtteri Bottas's Williams was clocked at 372.5 km/h (231.4 mph) during final practice for the 2016 Mexican Grand Prix, aided by thin high-altitude air and a long slipstream-assisted straight — widely cited as the highest speed-trap reading ever recorded during an official Formula 1 session, though it came in practice rather than qualifying or the race itself.",
    value: "372.5",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "FIA-operated trackside speed-trap radar during an official practice session.",
    source: { title: "Formula 1 — Speed Trap Records", url: "https://www.formula1.com/", date: "2016-10-28", location: "Mexico City, Mexico" },
  },
  {
    registryNumber: "LR-FASTEST-SPEED-SURVIVED-ROCKET-SLED", slug: "fastest-speed-survived-by-a-human-in-a-land-vehicle", title: "Fastest speed voluntarily reached by a human in a land vehicle",
    category: "Speed Records", subcategory: "Human Endurance", direction: "MAXIMIZE",
    metricName: "Peak speed reached by a human test subject riding a land-based rocket sled", unit: "km/h",
    formalStatement: "The highest speed a human being has voluntarily reached while riding a land vehicle under controlled test conditions, and survived.",
    summary: "U.S. Air Force flight surgeon John Stapp rode a rocket-powered sled to a peak speed of 1,017 km/h (632 mph) at Holloman Air Force Base on December 10, 1954, then decelerated from that speed to a stop in about 1.4 seconds — earning him the nickname 'the fastest man on Earth' and generating data on human tolerance to extreme acceleration used in later aviation and automotive safety design.",
    value: "1017",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Instrumented rocket-sled test track run, tracked and documented by U.S. Air Force researchers.",
    source: { title: "U.S. Air Force — John Paul Stapp, Sonic Wind No. 1", url: "https://www.af.mil/", date: "1954-12-10", location: "Holloman Air Force Base, New Mexico, USA" },
  },
  {
    registryNumber: "LR-FASTEST-SUBMARINE-SPEED", slug: "fastest-submarine-speed-ever-recorded", title: "Fastest submerged speed ever recorded by a submarine",
    category: "Speed Records", subcategory: "Naval Vessels", direction: "MAXIMIZE",
    metricName: "Highest submerged speed attributed to a military submarine", unit: "knots",
    formalStatement: "The highest submerged speed attributed to any submarine, based on declassified and publicly reported naval performance figures.",
    summary: "The Soviet Project 705 Lira (NATO reporting name 'Alfa') class attack submarines, powered by a lead-cooled fast reactor, were reportedly capable of submerged speeds of around 41 knots (76 km/h), with some trial reports citing even higher figures — widely regarded as the fastest submarines ever built, though exact top-speed figures remain only partly declassified.",
    value: "41",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Compiled from declassified naval intelligence assessments and published naval history sources.",
    source: { title: "Federation of American Scientists — Alfa Class Submarine", url: "https://fas.org/", date: "1991-01-01", location: "Soviet Union" },
  },
  {
    registryNumber: "LR-FASTEST-AIR-BREATHING-AIRCRAFT-SCRAMJET", slug: "fastest-air-breathing-aircraft-scramjet", title: "Fastest air-breathing (non-rocket) aircraft ever flown",
    category: "Speed Records", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "Highest speed recorded by an air-breathing (scramjet-powered) aircraft", unit: "km/h",
    formalStatement: "The highest speed ever recorded by an aircraft using an air-breathing (scramjet) engine, as distinct from rocket-powered aircraft.",
    summary: "NASA's unmanned X-43A research aircraft reached Mach 9.6 — approximately 11,230 km/h (6,980 mph) — on November 16, 2004, powered by a supersonic-combustion ramjet (scramjet) engine, the fastest speed ever achieved by an air-breathing aircraft, as part of NASA's Hyper-X program.",
    value: "11230",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Tracked by ground radar and onboard flight instrumentation during a NASA research flight.",
    source: { title: "NASA — Hyper-X Program, X-43A", url: "https://www.nasa.gov/", date: "2004-11-16", location: "Pacific Ocean, off the California coast, USA" },
  },
  {
    registryNumber: "LR-FASTEST-BASEBALL-PITCH", slug: "fastest-baseball-pitch-ever-recorded", title: "Fastest baseball pitch ever recorded",
    category: "Speed Records", subcategory: "Sports Biomechanics", direction: "MAXIMIZE",
    metricName: "Highest recorded velocity of a pitched baseball in a Major League Baseball game", unit: "mph",
    formalStatement: "The highest pitch velocity ever recorded during a Major League Baseball game by an official radar/tracking system.",
    summary: "Cuban-American relief pitcher Aroldis Chapman threw a pitch recorded at 105.1 mph (169.1 km/h) on September 24, 2010, while playing for the Cincinnati Reds against the San Diego Padres — the fastest pitch ever recorded in a Major League Baseball game, certified by Guinness World Records.",
    value: "105.1",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "PITCHf/x radar tracking system data, verified by Major League Baseball and Guinness World Records.",
    source: { title: "Guinness World Records — Fastest Baseball Pitch", url: "https://www.guinnessworldrecords.com/", date: "2010-09-24", location: "San Diego, California, USA" },
  },
  {
    registryNumber: "LR-FASTEST-INDY-500-QUALIFYING-LAP", slug: "fastest-indianapolis-500-qualifying-lap-speed", title: "Fastest single-lap qualifying speed at the Indianapolis 500",
    category: "Speed Records", subcategory: "Motorsport", direction: "MAXIMIZE",
    metricName: "Highest single-lap qualifying speed recorded at the Indianapolis Motor Speedway", unit: "mph",
    formalStatement: "The highest single-lap qualifying speed ever recorded at the Indianapolis Motor Speedway for the Indianapolis 500.",
    summary: "Dutch driver Arie Luyendyk set a one-lap qualifying record of 237.498 mph (382.216 km/h) at the Indianapolis Motor Speedway in May 1996 — a track qualifying record that, as of the most recent editions covered by this registry's sources, still stands, since subsequent aerodynamic and engine rule changes have kept qualifying speeds lower.",
    value: "237.498",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Official timed qualifying lap certified by the Indianapolis Motor Speedway and sanctioning body.",
    source: { title: "Indianapolis Motor Speedway — Track Records", url: "https://www.indianapolismotorspeedway.com/", date: "1996-05-12", location: "Indianapolis, Indiana, USA" },
  },
  {
    registryNumber: "LR-FASTEST-LABORATORY-LAUNCHED-PROJECTILE", slug: "fastest-laboratory-launched-projectile-speed", title: "Fastest laboratory-launched projectile speed",
    category: "Speed Records", subcategory: "Aerospace Engineering", direction: "MAXIMIZE",
    metricName: "Highest speed achieved by a small projectile fired by a light-gas gun for hypervelocity-impact research", unit: "km/h",
    formalStatement: "The highest speed achieved by a small projectile fired from a light-gas gun facility used for hypervelocity-impact research, such as simulating micrometeoroid or space-debris impacts.",
    summary: "NASA's Ames Vertical Gun Range and similar light-gas gun facilities can fire small projectiles at speeds of up to roughly 7 km/s (about 25,200 km/h, or 15,660 mph) to simulate micrometeoroid and orbital-debris impacts on spacecraft materials — among the fastest speeds any human-made object has been deliberately accelerated to at ground level.",
    value: "25200",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Light-gas gun launch facility instrumentation, documented by NASA Ames Research Center.",
    source: { title: "NASA Ames Research Center — Ames Vertical Gun Range", url: "https://www.nasa.gov/ames/", date: "2015-01-01", location: "Moffett Field, California, USA" },
  },
  {
    registryNumber: "LR-FASTEST-MOVING-TECTONIC-PLATE", slug: "fastest-moving-tectonic-plate", title: "Fastest-moving tectonic plate",
    category: "Speed Records", subcategory: "Geophysics", direction: "MAXIMIZE",
    metricName: "Fastest measured horizontal motion rate of a tectonic plate", unit: "cm/year",
    formalStatement: "The highest horizontal motion rate measured by GPS geodesy for any of Earth's major or minor tectonic plates.",
    summary: "The small Tonga microplate, in the southwest Pacific, moves at up to about 24 cm per year relative to neighboring plates — the fastest tectonic plate motion ever measured by GPS geodesy, driven by the rapid rollback of the Tonga subduction trench.",
    value: "24",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "GPS geodetic network measurements analyzed by geophysical researchers and the U.S. Geological Survey.",
    source: { title: "U.S. Geological Survey — Plate Motion and GPS Geodesy", url: "https://www.usgs.gov/", date: "2010-01-01", location: "Tonga Trench, southwest Pacific Ocean" },
  },
  {
    registryNumber: "LR-FASTEST-TYPING-SPEED-HUMAN", slug: "fastest-typing-speed-ever-recorded", title: "Fastest typing speed ever recorded",
    category: "Speed Records", subcategory: "Human Performance", direction: "MAXIMIZE",
    metricName: "Peak typing speed recorded for a human typist", unit: "wpm",
    formalStatement: "The highest peak typing speed, in words per minute, ever certified for a human typist using a standard keyboard layout.",
    summary: "American typist Barbara Blackburn reached a peak speed of 212 words per minute on a Dvorak Simplified Keyboard, with a sustained speed of around 150 wpm — certified by Guinness World Records as the fastest typing speed ever recorded.",
    value: "212",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Timed typing test certified by Guinness World Records.",
    source: { title: "Guinness World Records — Fastest Typing Speed", url: "https://www.guinnessworldrecords.com/", date: "2005-01-01", location: "United States" },
  },

  // --- Economics ---
  {
    registryNumber: "LR-US-NATIONAL-DEBT-SURPASSES-34-TRILLION", slug: "united-states-national-debt-surpasses-34-trillion", title: "First national government debt to surpass $34 trillion",
    category: "Economics", subcategory: "Public Finance", direction: "MAXIMIZE",
    metricName: "Gross outstanding government debt of a single nation", unit: "USD",
    formalStatement: "The point at which a single national government's total outstanding public debt first exceeded $34 trillion — the largest sovereign debt of any nation in nominal dollar terms.",
    summary: "The gross national debt of the United States surpassed $34 trillion for the first time on January 4, 2024, according to the U.S. Treasury Department — by far the largest national debt of any country in nominal dollar terms, having roughly doubled over the preceding decade.",
    value: "34000000000000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Daily Treasury statement published by the U.S. Department of the Treasury's Bureau of the Fiscal Service.",
    source: { title: "U.S. Department of the Treasury — Debt to the Penny", url: "https://fiscaldata.treasury.gov/", date: "2024-01-04", location: "United States" },
  },
  {
    registryNumber: "LR-LARGEST-ANNUAL-TRADE-DEFICIT-SINGLE-COUNTRY", slug: "largest-annual-trade-deficit-single-country", title: "Largest annual goods-and-services trade deficit recorded by a single country",
    category: "Economics", subcategory: "International Trade", direction: "MAXIMIZE",
    metricName: "Annual trade deficit (imports minus exports of goods and services) recorded by a single nation", unit: "USD",
    formalStatement: "The greatest annual trade deficit in goods and services recorded by any single country in a calendar year, as measured by that country's official trade statistics.",
    summary: "The United States recorded a goods-and-services trade deficit of approximately $948 billion in 2022, according to the U.S. Bureau of Economic Analysis — the largest annual trade deficit of any country on record, driven by strong domestic demand for imports and volatile energy prices.",
    value: "948000000000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Annual balance-of-payments trade statistics compiled by the U.S. Bureau of Economic Analysis.",
    source: { title: "U.S. Bureau of Economic Analysis — U.S. International Trade in Goods and Services", url: "https://www.bea.gov/", date: "2023-02-07", location: "United States" },
  },
  {
    registryNumber: "LR-MOST-EXPENSIVE-HOME-SOLD-US", slug: "most-expensive-home-ever-sold-in-the-united-states", title: "Most expensive private home ever sold in the United States",
    category: "Economics", subcategory: "Real Estate", direction: "MAXIMIZE",
    metricName: "Sale price of the most expensive single-family residential property transaction in the United States", unit: "USD",
    formalStatement: "The highest publicly confirmed sale price ever paid for a single private residential property in the United States.",
    summary: "Hedge fund manager Ken Griffin purchased a penthouse at 220 Central Park South in Manhattan for $238 million in January 2019 — the most expensive home ever sold in the United States, and among the most expensive residential property sales recorded anywhere in the world.",
    value: "238000000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Public property records and financial-press reporting on the transaction.",
    source: { title: "The Wall Street Journal — Ken Griffin Penthouse Purchase", url: "https://www.wsj.com/", date: "2019-01-24", location: "New York City, USA" },
  },
  {
    registryNumber: "LR-LARGEST-BANK-FAILURE-US-HISTORY", slug: "largest-bank-failure-in-us-history", title: "Largest bank failure in United States history",
    category: "Economics", subcategory: "Banking", direction: "MAXIMIZE",
    metricName: "Total assets held by a bank at the time of its failure", unit: "USD",
    formalStatement: "The greatest total assets held by any bank at the time it failed and was seized by regulators in United States history.",
    summary: "Washington Mutual, with approximately $307 billion in assets, was seized by the Federal Deposit Insurance Corporation on September 25, 2008, and its banking operations sold to JPMorgan Chase — the largest bank failure in U.S. history.",
    value: "307000000000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Regulatory seizure and resolution records published by the Federal Deposit Insurance Corporation.",
    source: { title: "Federal Deposit Insurance Corporation — Washington Mutual", url: "https://www.fdic.gov/", date: "2008-09-25", location: "United States" },
  },
  {
    registryNumber: "LR-HIGHEST-VALUED-CURRENCY-UNIT", slug: "highest-valued-currency-unit-in-the-world", title: "Highest-valued currency unit in the world",
    category: "Economics", subcategory: "Currency", direction: "MAXIMIZE",
    metricName: "Exchange value of one unit of currency against the U.S. dollar", unit: "USD per unit",
    formalStatement: "The national currency whose single base unit trades for the greatest value against the U.S. dollar among currencies in general circulation.",
    summary: "The Kuwaiti dinar has traded at roughly 3.2–3.3 US dollars per dinar in recent years, making it consistently the highest-valued currency unit in the world — a position it has held for decades, underpinned by Kuwait's oil wealth and a currency peg managed by its central bank.",
    value: "3.25",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Foreign exchange rate data compiled from central bank and market sources.",
    source: { title: "Central Bank of Kuwait — Exchange Rates", url: "https://www.cbk.gov.kw/", date: "2024-01-01", location: "Kuwait" },
  },
  {
    registryNumber: "LR-LARGEST-SINGLE-FISCAL-STIMULUS-BILL-US", slug: "largest-single-fiscal-stimulus-bill-in-us-history", title: "Largest single fiscal stimulus bill in United States history",
    category: "Economics", subcategory: "Fiscal Policy", direction: "MAXIMIZE",
    metricName: "Total appropriated value of a single piece of economic stimulus/relief legislation", unit: "USD",
    formalStatement: "The greatest total appropriated dollar value of any single economic stimulus or relief act passed by the United States Congress.",
    summary: "The Coronavirus Aid, Relief, and Economic Security (CARES) Act, signed into law on March 27, 2020, appropriated approximately $2.2 trillion in economic relief in response to the COVID-19 pandemic — the largest single stimulus bill in U.S. history at the time of its passage.",
    value: "2200000000000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Congressional Budget Office cost estimate of the enacted legislation.",
    source: { title: "Congressional Budget Office — CARES Act Cost Estimate", url: "https://www.cbo.gov/", date: "2020-03-27", location: "United States" },
  },
  {
    registryNumber: "LR-LARGEST-NATIONAL-ECONOMY-NOMINAL-GDP", slug: "largest-national-economy-by-nominal-gdp", title: "Largest national economy by nominal GDP",
    category: "Economics", subcategory: "Macroeconomics", direction: "MAXIMIZE",
    metricName: "Annual gross domestic product of the world's largest national economy, at nominal (current) prices", unit: "USD",
    formalStatement: "The greatest annual gross domestic product at current (nominal) prices recorded by any single national economy.",
    summary: "The United States recorded a nominal GDP of approximately $27.7 trillion in 2023, according to the Bureau of Economic Analysis, making it by far the largest national economy in the world by nominal GDP — roughly equal to the combined size of the next three or four largest economies below China.",
    value: "27700000000000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Annual national income accounts published by the U.S. Bureau of Economic Analysis.",
    source: { title: "U.S. Bureau of Economic Analysis — Gross Domestic Product", url: "https://www.bea.gov/", date: "2024-01-25", location: "United States" },
  },
  {
    registryNumber: "LR-LARGEST-GOVERNMENT-FINANCIAL-BAILOUT-PROGRAM", slug: "largest-government-financial-bailout-program", title: "Largest government financial-sector bailout program in history",
    category: "Economics", subcategory: "Fiscal Policy", direction: "MAXIMIZE",
    metricName: "Total funds authorized under a single national financial-sector bailout program", unit: "USD",
    formalStatement: "The greatest total dollar amount authorized by a single national government program to stabilize its financial sector.",
    summary: "The U.S. Troubled Asset Relief Program (TARP), authorized by Congress in October 2008 during the global financial crisis, provided up to $700 billion to purchase distressed assets and inject capital into banks and other institutions — the largest coordinated financial-sector bailout program in history at the time.",
    value: "700000000000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Legislative authorization under the Emergency Economic Stabilization Act of 2008, tracked by the U.S. Treasury and Government Accountability Office.",
    source: { title: "U.S. Government Accountability Office — TARP Program", url: "https://www.gao.gov/", date: "2008-10-03", location: "United States" },
  },
  {
    registryNumber: "LR-FIRST-NEGATIVE-OIL-FUTURES-PRICE", slug: "first-negative-oil-futures-price-in-history", title: "First time a major oil futures contract traded at a negative price",
    category: "Economics", subcategory: "Commodity Markets", direction: "MINIMIZE",
    metricName: "Settlement price of the West Texas Intermediate crude oil futures contract", unit: "USD per barrel",
    formalStatement: "The lowest settlement price ever recorded for a major crude oil futures benchmark, the first and only time such a contract has settled below zero.",
    summary: "The May 2020 West Texas Intermediate crude oil futures contract settled at -$37.63 per barrel on April 20, 2020, on the New York Mercantile Exchange — the first and only time a major oil futures benchmark has ever traded and settled at a negative price, as collapsing COVID-19 demand and full storage tanks left traders paying to avoid taking physical delivery.",
    value: "-37.63",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official contract settlement price published by the CME Group / New York Mercantile Exchange.",
    source: { title: "CME Group — WTI Crude Oil Futures Settlement", url: "https://www.cmegroup.com/", date: "2020-04-20", location: "New York Mercantile Exchange, USA" },
  },
  {
    registryNumber: "LR-HIGHEST-US-UNEMPLOYMENT-RATE-GREAT-DEPRESSION", slug: "highest-us-unemployment-rate-great-depression", title: "Highest unemployment rate ever recorded in the United States",
    category: "Economics", subcategory: "Labor Economics", direction: "MAXIMIZE",
    metricName: "Peak national unemployment rate during the Great Depression", unit: "%",
    formalStatement: "The highest annual unemployment rate ever estimated for the United States workforce.",
    summary: "The U.S. unemployment rate is estimated to have peaked at around 24.9% in 1933, at the depth of the Great Depression, according to historical Bureau of Labor Statistics reconstructions — the highest level of joblessness ever recorded for the United States, roughly one in four workers.",
    value: "24.9",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Historical reconstruction of labor force statistics by economic historians and the Bureau of Labor Statistics, since pre-1940 unemployment data was not collected using modern survey methods.",
    source: { title: "U.S. Bureau of Labor Statistics — Historical Unemployment Estimates", url: "https://www.bls.gov/", date: "1933-01-01", location: "United States" },
  },
  {
    registryNumber: "LR-FIRST-RECORDED-SPECULATIVE-ASSET-BUBBLE", slug: "first-recorded-speculative-asset-bubble-tulip-mania", title: "First well-documented speculative asset-price bubble in economic history",
    category: "Economics", subcategory: "Financial History", direction: "MINIMIZE",
    metricName: "Year of the first widely documented speculative asset-price bubble and crash", unit: "year",
    formalStatement: "The year of the earliest speculative asset-price bubble and subsequent crash widely documented in economic history.",
    summary: "'Tulip mania' in the Dutch Republic, in which contracts for tulip bulbs reached extraordinarily high prices before collapsing in February 1637, is commonly cited by economic historians as the first well-documented speculative asset bubble — though some historians argue its scale and economic impact have been exaggerated by later accounts.",
    value: "1637",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Historical Dutch trading records and contracts, studied by economic historians.",
    source: { title: "Britannica — Tulip Mania", url: "https://www.britannica.com/event/tulip-mania", date: "1637-02-01", location: "Dutch Republic" },
  },
  {
    registryNumber: "LR-OLDEST-CURRENCY-STILL-IN-CIRCULATION", slug: "oldest-currency-still-in-continuous-circulation", title: "Oldest currency still in continuous circulation",
    category: "Economics", subcategory: "Currency", direction: "MINIMIZE",
    metricName: "Approximate year the currency now known as the pound sterling first came into use", unit: "year",
    formalStatement: "The approximate year of origin of the oldest national currency still in continuous circulation today.",
    summary: "The pound sterling traces its origins to Anglo-Saxon England, where silver pennies and the 'pound' as a unit of account were in use by around 775 CE — commonly cited as the oldest currency still in continuous use in the world today, though the coins and monetary system have of course changed enormously since then.",
    value: "775",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Numismatic and historical records of Anglo-Saxon coinage, studied by monetary historians.",
    source: { title: "The Royal Mint Museum — History of British Coinage", url: "https://www.royalmintmuseum.org.uk/", date: "2015-01-01", location: "England" },
  },
  {
    registryNumber: "LR-LARGEST-SOVEREIGN-DEBT-DEFAULT-2001", slug: "largest-sovereign-debt-default-argentina-2001", title: "Largest sovereign debt default in history (Argentina, 2001)",
    category: "Economics", subcategory: "Sovereign Debt", direction: "MAXIMIZE",
    metricName: "Total value of sovereign bonds defaulted on in a single national debt default", unit: "USD",
    formalStatement: "The greatest total face value of sovereign bonds defaulted on by a single national government in one default event, as of the time it occurred.",
    summary: "Argentina defaulted on approximately $100 billion of sovereign debt in December 2001, the largest sovereign debt default in history at the time it occurred, triggering years of litigation with holdout creditors that continued for more than a decade afterward. Later restructurings elsewhere (such as Greece in 2012) have since been described by some analysts as larger by certain measures, so this record is best understood as the largest sovereign default of its era.",
    value: "100000000000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Sovereign debt restructuring records compiled by the IMF and financial-press reporting.",
    source: { title: "International Monetary Fund — Argentina and the IMF", url: "https://www.imf.org/", date: "2001-12-23", location: "Argentina" },
  },
  {
    registryNumber: "LR-HIGHEST-NOMINAL-OIL-PRICE-EVER-RECORDED", slug: "highest-nominal-oil-price-ever-recorded", title: "Highest nominal price ever recorded for a barrel of crude oil",
    category: "Economics", subcategory: "Commodity Markets", direction: "MAXIMIZE",
    metricName: "Highest intraday nominal price recorded for a barrel of West Texas Intermediate crude oil", unit: "USD per barrel",
    formalStatement: "The highest nominal (not inflation-adjusted) intraday price ever recorded for West Texas Intermediate crude oil futures.",
    summary: "West Texas Intermediate crude oil futures briefly touched an intraday price of $147.27 per barrel on July 11, 2008, on the New York Mercantile Exchange — the highest nominal price ever recorded for crude oil, shortly before prices collapsed amid the onset of the global financial crisis.",
    value: "147.27",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official intraday trading price recorded on the New York Mercantile Exchange.",
    source: { title: "U.S. Energy Information Administration — Crude Oil Prices", url: "https://www.eia.gov/", date: "2008-07-11", location: "New York Mercantile Exchange, USA" },
  },

  // --- History ---
  {
    registryNumber: "LR-LONGEST-REIGN-FEMALE-MONARCH", slug: "longest-reign-of-a-female-monarch", title: "Longest verified reign of a female monarch",
    category: "History", subcategory: "Monarchy", direction: "MAXIMIZE",
    metricName: "Duration of a queen regnant's confirmed reign", unit: "years",
    formalStatement: "The longest confirmed reign of any female monarch ruling in her own right over a sovereign state.",
    summary: "Queen Elizabeth II reigned over the United Kingdom for 70 years and 214 days, from February 6, 1952, until her death on September 8, 2022 — the longest verified reign of any female monarch in history, and the longest reign of any British monarch of either sex.",
    value: "70",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official reign dates recorded by the British monarchy and UK government.",
    source: { title: "The Royal Household — Queen Elizabeth II", url: "https://www.royal.uk/", date: "2022-09-08", location: "United Kingdom" },
  },
  {
    registryNumber: "LR-LONGEST-SIEGE-IN-RECORDED-HISTORY", slug: "longest-siege-in-recorded-history", title: "Longest siege in recorded history",
    category: "History", subcategory: "Military History", direction: "MAXIMIZE",
    metricName: "Duration of the longest continuous military siege in recorded history", unit: "years",
    formalStatement: "The longest duration of a continuous military siege of a single fortified position recorded in history.",
    summary: "The Siege of Ceuta, in which Moroccan forces besieged the Spanish-held (later Portuguese-held) enclave of Ceuta in North Africa, lasted from 1694 to 1727 — 33 years — commonly cited by Guinness World Records as the longest siege in recorded history.",
    value: "33",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Historical military records of the Moroccan-Iberian conflicts over Ceuta, compiled by historians.",
    source: { title: "Guinness World Records — Longest Siege", url: "https://www.guinnessworldrecords.com/", date: "1727-01-01", location: "Ceuta, North Africa" },
  },
  {
    registryNumber: "LR-LONGEST-WAR-IN-RECORDED-HISTORY", slug: "longest-war-in-recorded-history", title: "Longest war in recorded history",
    category: "History", subcategory: "Military History", direction: "MAXIMIZE",
    metricName: "Duration of the longest continuous or intermittent war widely treated as a single conflict", unit: "years",
    formalStatement: "The longest duration of an intermittent military conflict widely treated by historians as a single continuous war.",
    summary: "The Reconquista — the centuries-long series of campaigns by Christian kingdoms to retake the Iberian Peninsula from Muslim rule, from the initial Umayyad conquest in 711 CE to the fall of Granada in 1492 — spanned 781 years, and is often cited as the longest war in history, though historians debate whether such a long, intermittent series of conflicts should be treated as a single 'war' at all.",
    value: "781",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Compiled from historical accounts of the medieval Iberian Peninsula conflicts.",
    source: { title: "Britannica — Reconquista", url: "https://www.britannica.com/event/Reconquista", date: "1492-01-02", location: "Iberian Peninsula" },
  },
  {
    registryNumber: "LR-OLDEST-PARLIAMENTARY-INSTITUTION", slug: "oldest-parliamentary-institution-still-in-existence", title: "Oldest parliamentary institution still in existence",
    category: "History", subcategory: "Political History", direction: "MINIMIZE",
    metricName: "Year of founding of the oldest parliamentary institution still functioning today", unit: "year CE",
    formalStatement: "The year of founding of the oldest legislative/parliamentary assembly that has continued to exist, in some form, into the present day.",
    summary: "The Icelandic Althing was founded in 930 CE at Þingvellir, where Icelandic chieftains gathered annually to make laws and settle disputes — it is widely regarded as the oldest parliamentary institution still in existence, even though its powers, form, and location have changed enormously since then.",
    value: "930",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Medieval Icelandic sagas and historical records, cross-referenced by historians of Norse settlement.",
    source: { title: "Althingi — The Icelandic Parliament, History", url: "https://www.althingi.is/", date: "0930-06-01", location: "Þingvellir, Iceland" },
  },
  {
    registryNumber: "LR-OLDEST-KNOWN-ANALOG-COMPUTING-DEVICE", slug: "oldest-known-analog-computing-device", title: "Oldest known analog computing device",
    category: "History", subcategory: "History of Science", direction: "MINIMIZE",
    metricName: "Approximate date of manufacture of the oldest known geared analog computing mechanism", unit: "year BCE",
    formalStatement: "The approximate date of manufacture of the oldest known mechanical device generally regarded as an analog computer.",
    summary: "The Antikythera mechanism, a geared bronze device recovered from a shipwreck off the Greek island of Antikythera in 1901, has been dated by researchers to approximately 100 BCE (with some estimates ranging as early as 150 BCE). It was used to predict astronomical positions and eclipses, and is widely regarded as the oldest known analog computing device, decades or centuries ahead of anything of comparable complexity.",
    value: "100",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Radiographic and inscriptional analysis by the Antikythera Mechanism Research Project.",
    source: { title: "Antikythera Mechanism Research Project", url: "https://www.antikythera-mechanism.gr/", date: "2008-01-01", location: "Antikythera, Greece" },
  },
  {
    registryNumber: "LR-OLDEST-PURPOSE-BUILT-PUBLIC-MUSEUM", slug: "oldest-purpose-built-public-museum", title: "Oldest purpose-built public museum",
    category: "History", subcategory: "Institutions", direction: "MINIMIZE",
    metricName: "Year a purpose-built museum building first opened to the general public", unit: "year CE",
    formalStatement: "The year the oldest surviving purpose-built museum building first opened its doors to the general public.",
    summary: "The Ashmolean Museum in Oxford, England, opened in 1683 in a building specifically constructed to house and display Elias Ashmole's collection — widely regarded as the first purpose-built museum building in the world to open to the public, predating the British Museum by seven decades.",
    value: "1683",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Institutional history records maintained by the University of Oxford and the Ashmolean Museum.",
    source: { title: "Ashmolean Museum — Our History", url: "https://www.ashmolean.org/", date: "1683-05-24", location: "Oxford, England" },
  },
  {
    registryNumber: "LR-LONGEST-VERIFIED-PAPAL-REIGN", slug: "longest-verified-papal-reign", title: "Longest verified reign of a Pope",
    category: "History", subcategory: "Religious History", direction: "MAXIMIZE",
    metricName: "Duration of the longest historically verified papacy, excluding Saint Peter's traditional but undated reign", unit: "years",
    formalStatement: "The longest reign of a Pope of the Roman Catholic Church for which the start and end dates are historically well documented, excluding the traditional reign attributed to Saint Peter, whose exact dates are not historically verifiable.",
    summary: "Pope Pius IX reigned from June 16, 1846, until his death on February 7, 1878 — nearly 32 years — the longest verified papal reign in the history of the Roman Catholic Church, a period that included the loss of the Papal States and the First Vatican Council.",
    value: "31",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official records of papal succession maintained by the Vatican and Catholic Church historians.",
    source: { title: "Encyclopaedia Britannica — Pius IX", url: "https://www.britannica.com/biography/Pius-IX", date: "1878-02-07", location: "Vatican City / Papal States" },
  },
  {
    registryNumber: "LR-OLDEST-SURVIVING-BRIDGE-STILL-STANDING", slug: "oldest-surviving-bridge-still-standing", title: "Oldest surviving bridge still in use",
    category: "History", subcategory: "Ancient Engineering", direction: "MINIMIZE",
    metricName: "Approximate construction date of the oldest bridge still standing and in use today", unit: "year BCE",
    formalStatement: "The approximate construction date of the oldest known bridge structure still standing and passable today.",
    summary: "The Arkadiko Bridge in the Peloponnese, Greece, built by the Mycenaeans around 1300 BCE using a corbelled (false-arch) construction technique, is commonly cited as the oldest bridge in the world still standing and usable — though some engineering historians note it is technically a corbel bridge rather than a true arch bridge, a distinction debated among specialists.",
    value: "1300",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Archaeological dating of Mycenaean-era construction techniques and materials.",
    source: { title: "Ministry of Culture, Greece — Mycenaean Bridges of the Argolid", url: "https://www.culture.gov.gr/", date: "1990-01-01", location: "Peloponnese, Greece" },
  },
  {
    registryNumber: "LR-OLDEST-SHIPWRECK-EVER-EXCAVATED", slug: "oldest-shipwreck-ever-excavated", title: "Oldest seafaring shipwreck ever scientifically excavated",
    category: "History", subcategory: "Maritime Archaeology", direction: "MINIMIZE",
    metricName: "Approximate age of the oldest fully excavated deep-sea shipwreck cargo", unit: "year BCE",
    formalStatement: "The approximate date of the oldest known seafaring shipwreck to have been scientifically excavated, based on its cargo and construction.",
    summary: "The Uluburun shipwreck, discovered off the coast of southern Turkey and excavated between 1984 and 1994, dates to around 1300 BCE (the Late Bronze Age) and carried a rich cargo of copper, tin, glass, and luxury goods from across the eastern Mediterranean — one of the oldest and most completely excavated seafaring shipwrecks ever studied.",
    value: "1300",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Underwater archaeological excavation and radiocarbon/artifact dating by the Institute of Nautical Archaeology.",
    source: { title: "Institute of Nautical Archaeology — Uluburun Shipwreck", url: "https://nauticalarch.org/", date: "1994-01-01", location: "Off Uluburun, Turkey" },
  },
  {
    registryNumber: "LR-EARLIEST-STANDARDIZED-WEIGHT-SYSTEM", slug: "earliest-known-standardized-weight-system", title: "Earliest known standardized system of weights",
    category: "History", subcategory: "Ancient Economies", direction: "MINIMIZE",
    metricName: "Approximate date of the earliest known highly standardized system of measurement weights", unit: "year BCE",
    formalStatement: "The approximate date of the earliest known civilization to use a highly standardized, mass-produced system of measurement weights across a wide territory.",
    summary: "The Indus Valley (Harappan) civilization, flourishing from around 2600 to 1900 BCE, used a remarkably standardized system of cubical stone weights following a binary and decimal ratio, found consistently across sites separated by hundreds of kilometers — among the earliest known highly standardized weight systems in the ancient world.",
    value: "2600",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Archaeological analysis of excavated weight artifacts from Harappan civilization sites.",
    source: { title: "Harappa.com — Indus Valley Weights and Measures", url: "https://www.harappa.com/", date: "2015-01-01", location: "Indus Valley (modern Pakistan and northwest India)" },
  },
  {
    registryNumber: "LR-EARLIEST-PLANNED-CITY-URBAN-GRID", slug: "earliest-known-planned-city-with-a-street-grid", title: "Earliest known planned city with a street grid",
    category: "History", subcategory: "Ancient Urban Planning", direction: "MINIMIZE",
    metricName: "Approximate founding date of the earliest known city built on a deliberate street grid with municipal infrastructure", unit: "year BCE",
    formalStatement: "The approximate founding date of the earliest known city constructed on a deliberate, planned street grid with organized municipal infrastructure such as drainage.",
    summary: "Mohenjo-daro, built around 2500 BCE in the Indus Valley (in present-day Pakistan), featured a grid layout of streets, standardized baked-brick construction, and one of the earliest known urban drainage and sanitation systems — making it one of the earliest known examples of deliberately planned city design anywhere in the ancient world.",
    value: "2500",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Archaeological excavation and urban-layout analysis of the Mohenjo-daro site.",
    source: { title: "UNESCO World Heritage Centre — Archaeological Ruins at Moenjodaro", url: "https://whc.unesco.org/en/list/138/", date: "1980-01-01", location: "Sindh, Pakistan" },
  },
  {
    registryNumber: "LR-EARLIEST-KNOWN-ALPHABETIC-SCRIPT", slug: "earliest-known-alphabetic-writing-system", title: "Earliest known alphabetic writing system",
    category: "History", subcategory: "History of Writing", direction: "MINIMIZE",
    metricName: "Approximate date of the earliest known alphabetic (as opposed to logographic or syllabic) writing system", unit: "year BCE",
    formalStatement: "The approximate date of the earliest known alphabetic writing system, in which symbols represent individual consonant or vowel sounds rather than whole words or syllables — distinct from earlier logographic systems such as cuneiform.",
    summary: "Proto-Sinaitic script, found inscribed at turquoise mining sites in the Sinai Peninsula and dated to roughly 1900–1700 BCE, is generally regarded by linguists as the earliest known alphabetic writing system — an adaptation of Egyptian hieroglyphic signs to represent Semitic consonant sounds, and the ancestor of the later Phoenician alphabet from which most modern alphabets descend.",
    value: "1900",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Epigraphic analysis of inscriptions found at Serabit el-Khadim and Wadi el-Hol, studied by historical linguists.",
    source: { title: "British Museum — Proto-Sinaitic Script", url: "https://www.britishmuseum.org/", date: "2010-01-01", location: "Sinai Peninsula, Egypt" },
  },
  {
    registryNumber: "LR-FIRST-ORGANIZED-POSTAL-RELAY-SYSTEM", slug: "first-organized-postal-relay-system", title: "First large-scale organized postal relay system",
    category: "History", subcategory: "Ancient Infrastructure", direction: "MINIMIZE",
    metricName: "Approximate date of the earliest large-scale, government-organized postal relay/courier system", unit: "year BCE",
    formalStatement: "The approximate date of the earliest large-scale, government-organized system of mounted relay couriers used to carry official messages across an empire.",
    summary: "The Achaemenid Persian Empire, under Darius I in the late 6th century BCE, built the Royal Road and an associated relay system of mounted couriers stationed at intervals who could carry messages across roughly 2,700 km in a matter of days — described admiringly by the Greek historian Herodotus, and often cited as one of the earliest large-scale organized postal relay systems, though similar courier networks likely existed in earlier Near Eastern empires as well.",
    value: "500",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Ancient historical accounts, primarily Herodotus's Histories, cross-referenced with archaeological remains of the Royal Road.",
    source: { title: "Livius.org — The Persian Royal Road", url: "https://www.livius.org/", date: "2019-01-01", location: "Achaemenid Persian Empire" },
  },
  {
    registryNumber: "LR-EARLIEST-USE-OF-ZERO-PLACEHOLDER", slug: "earliest-known-use-of-a-zero-placeholder", title: "Earliest known use of a zero placeholder in a positional number system",
    category: "History", subcategory: "History of Mathematics", direction: "MINIMIZE",
    metricName: "Approximate date of the earliest known consistent use of a zero placeholder symbol in a positional numeral system", unit: "year BCE",
    formalStatement: "The approximate date of the earliest known consistent use of a symbol as a placeholder for an empty position within a positional (place-value) number system, distinct from the later development of zero as a number in its own right.",
    summary: "Babylonian mathematicians, working in a base-60 (sexagesimal) positional number system, developed a consistent placeholder symbol for an empty position by around 300 BCE, with more sporadic precursor use extending back several centuries earlier — one of the earliest known uses of a zero-like placeholder, though it was not yet treated as a number that could be added, subtracted, or manipulated on its own, a development credited to Indian mathematicians centuries later.",
    value: "300",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Analysis of surviving Babylonian cuneiform mathematical and astronomical tablets by historians of mathematics.",
    source: { title: "MacTutor History of Mathematics Archive — A History of Zero", url: "https://mathshistory.st-andrews.ac.uk/", date: "2000-01-01", location: "Babylon, Mesopotamia (modern-day Iraq)" },
  },

  // --- Food & Culture ---
  {
    registryNumber: "LR-LARGEST-SINGLE-HUMAN-GATHERING-KUMBH-MELA", slug: "largest-single-gathering-of-humans-kumbh-mela", title: "Largest single gathering of humans for one event",
    category: "Food & Culture", subcategory: "Religious and Cultural Festivals", direction: "MAXIMIZE",
    metricName: "Estimated total attendance across a single edition of the Kumbh Mela festival", unit: "attendees",
    formalStatement: "The greatest total estimated number of people who gathered at a single event or festival over its full duration.",
    summary: "The 2019 Kumbh Mela in Prayagraj (Allahabad), India, drew estimated total attendance in excess of 200 million people across its roughly 49-day duration, according to Indian government estimates — widely cited as the largest single gathering of humans for any event in history, though independent estimates vary and the true figure is difficult to verify precisely given the festival's rolling, continuous nature.",
    value: "200000000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Crowd-size estimation by Indian state and national government authorities, based on transportation and infrastructure usage data.",
    source: { title: "Government of Uttar Pradesh — Kumbh Mela 2019", url: "https://www.up.gov.in/", date: "2019-03-04", location: "Prayagraj, India" },
  },
  {
    registryNumber: "LR-BEST-SELLING-SECULAR-BOOK", slug: "best-selling-secular-book-of-all-time", title: "Best-selling secular (non-religious) book of all time",
    category: "Food & Culture", subcategory: "Publishing", direction: "MAXIMIZE",
    metricName: "Estimated total copies distributed of the best-selling non-religious book", unit: "copies",
    formalStatement: "The greatest estimated total number of copies ever printed and distributed of a single non-religious book.",
    summary: "'Quotations from Chairman Mao Tse-tung,' commonly known as the Little Red Book, is estimated to have had somewhere between 800 million and over 1 billion copies printed and distributed in China from 1964 onward, making it, by most estimates, the best-selling secular book of all time (excluding religious texts such as the Bible and Quran, whose collective print histories are even harder to total precisely).",
    value: "1000000000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Estimated from Chinese state publishing records and historical accounts, compiled by publishing historians.",
    source: { title: "Britannica — Quotations from Chairman Mao Tse-tung", url: "https://www.britannica.com/topic/Quotations-from-Chairman-Mao-Tse-tung", date: "1976-01-01", location: "China" },
  },
  {
    registryNumber: "LR-BEST-SELLING-ALBUM-ALL-TIME", slug: "best-selling-album-of-all-time", title: "Best-selling music album of all time",
    category: "Food & Culture", subcategory: "Music", direction: "MAXIMIZE",
    metricName: "Certified worldwide sales of the best-selling music album", unit: "copies sold",
    formalStatement: "The greatest certified worldwide sales figure for a single music album.",
    summary: "Michael Jackson's 1982 album 'Thriller' has sold an estimated 70 million copies worldwide, certified by Guinness World Records in 2006 as the best-selling album of all time — a title it continues to hold, aided by ongoing catalog sales decades after its release.",
    value: "70000000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Worldwide sales certification compiled by Guinness World Records from record label and industry data.",
    source: { title: "Guinness World Records — Best-Selling Album of All Time", url: "https://www.guinnessworldrecords.com/", date: "2006-01-01", location: "Worldwide" },
  },
  {
    registryNumber: "LR-MOST-WATCHED-SCRIPTED-TV-FINALE", slug: "most-watched-scripted-television-series-finale", title: "Most-watched scripted television series finale in U.S. history",
    category: "Food & Culture", subcategory: "Television", direction: "MAXIMIZE",
    metricName: "Estimated U.S. viewership of the most-watched scripted television series finale", unit: "viewers",
    formalStatement: "The greatest estimated U.S. household/viewer audience for the final episode of a scripted (non-sporting) television series.",
    summary: "The series finale of M*A*S*H, titled 'Goodbye, Farewell and Amen,' aired on February 28, 1983, and was watched by an estimated 105.97 million viewers in the United States, according to Nielsen ratings — the most-watched series finale, and for decades the most-watched single television broadcast of any kind, in U.S. television history.",
    value: "105970000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Nielsen Media Research household ratings data from the broadcast night.",
    source: { title: "Nielsen — Historic U.S. Television Audience Records", url: "https://www.nielsen.com/", date: "1983-02-28", location: "United States" },
  },
  {
    registryNumber: "LR-MOST-VISITED-ART-MUSEUM", slug: "most-visited-art-museum-in-the-world", title: "Most-visited art museum in the world",
    category: "Food & Culture", subcategory: "Museums", direction: "MAXIMIZE",
    metricName: "Annual visitor attendance at the world's most-visited art museum", unit: "visitors per year",
    formalStatement: "The greatest annual visitor attendance recorded by any single art museum.",
    summary: "The Louvre in Paris has consistently been the most-visited art museum in the world for decades, drawing a record 10.2 million visitors in 2018 before the COVID-19 pandemic temporarily depressed attendance; it recorded about 8.7 million visitors in 2023, still the highest of any art museum worldwide.",
    value: "10200000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official annual visitor attendance figures published by the Musée du Louvre.",
    source: { title: "Musée du Louvre — Annual Attendance Reports", url: "https://www.louvre.fr/", date: "2019-01-03", location: "Paris, France" },
  },
  {
    registryNumber: "LR-LONGEST-RUNNING-ANIMATED-PRIMETIME-SERIES", slug: "longest-running-animated-primetime-television-series", title: "Longest-running animated primetime television series",
    category: "Food & Culture", subcategory: "Television", direction: "MAXIMIZE",
    metricName: "Number of years an animated primetime television series has continuously aired new episodes", unit: "years",
    formalStatement: "The greatest number of consecutive years a single animated television series has aired new episodes in primetime, as of its most recently confirmed renewal.",
    summary: "'The Simpsons' premiered as a half-hour series on December 17, 1989, and has aired new episodes continuously ever since, making it both the longest-running American primetime scripted television series and the longest-running animated series in U.S. television history, with well over 750 episodes produced.",
    value: "35",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Broadcast history and episode counts tracked by the Fox Broadcasting Company and industry trade press.",
    source: { title: "Guinness World Records — Longest-Running Animated Sitcom", url: "https://www.guinnessworldrecords.com/", date: "2024-01-01", location: "United States" },
  },
  {
    registryNumber: "LR-HIGHEST-GROSSING-FILM-UNADJUSTED", slug: "highest-grossing-film-of-all-time-unadjusted", title: "Highest-grossing film of all time (worldwide box office, unadjusted)",
    category: "Food & Culture", subcategory: "Film", direction: "MAXIMIZE",
    metricName: "Total worldwide box office gross of the highest-grossing film, not adjusted for inflation", unit: "USD",
    formalStatement: "The greatest total worldwide theatrical box office gross recorded by a single film, in nominal (not inflation-adjusted) dollars.",
    summary: "James Cameron's 'Avatar' (2009) reclaimed the record for highest-grossing film of all time (unadjusted for inflation) after a 2022 theatrical re-release pushed its worldwide total to roughly $2.92 billion, edging past 'Avengers: Endgame.' Because rankings at the very top have shifted repeatedly with re-releases and new blockbusters, this figure should be read as the standing as of the most recent editions covered by this registry's sources rather than a permanently fixed fact.",
    value: "2923000000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Worldwide theatrical box office tracking compiled by the film industry trade press (Box Office Mojo / Comscore).",
    source: { title: "Box Office Mojo — All Time Box Office", url: "https://www.boxofficemojo.com/", date: "2023-03-01", location: "Worldwide" },
  },
  {
    registryNumber: "LR-HIGHEST-GROSSING-FILM-INFLATION-ADJUSTED", slug: "highest-grossing-film-inflation-adjusted-domestic", title: "Highest-grossing film of all time (U.S. box office, inflation-adjusted)",
    category: "Food & Culture", subcategory: "Film", direction: "MAXIMIZE",
    metricName: "Estimated inflation-adjusted domestic (U.S. and Canada) box office gross of the highest-grossing film", unit: "USD",
    formalStatement: "The greatest estimated domestic (U.S. and Canada) box office gross of a film when adjusted for ticket-price inflation to present-day dollars.",
    summary: "'Gone with the Wind' (1939), when its domestic box office receipts are adjusted for decades of ticket-price inflation, remains by a wide margin the highest-grossing film of all time in the United States and Canada, with an inflation-adjusted gross estimated at around $1.9 billion — far ahead of any modern blockbuster measured the same way.",
    value: "1900000000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Historical box office receipts adjusted for average ticket-price inflation, as compiled by Box Office Mojo.",
    source: { title: "Box Office Mojo — Domestic Box Office, Adjusted for Inflation", url: "https://www.boxofficemojo.com/", date: "2020-01-01", location: "United States and Canada" },
  },
  {
    registryNumber: "LR-OLDEST-CONTINUOUSLY-PUBLISHED-NEWSPAPER", slug: "oldest-continuously-published-newspaper", title: "Oldest continuously published newspaper",
    category: "Food & Culture", subcategory: "Publishing", direction: "MINIMIZE",
    metricName: "Year of founding of the oldest newspaper still published continuously today", unit: "year CE",
    formalStatement: "The year of founding of the oldest newspaper that has been published continuously, in some form, up to the present day.",
    summary: "Post-och Inrikes Tidningar, Sweden's official gazette, was founded in 1645 and is recognized by Guinness World Records as the oldest continuously published newspaper in the world — though it transitioned from print to an exclusively digital, online-only publication in 2007.",
    value: "1645",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Publication history maintained by the Swedish Companies Registration Office, which now publishes the gazette.",
    source: { title: "Guinness World Records — Oldest Newspaper", url: "https://www.guinnessworldrecords.com/", date: "2007-01-01", location: "Sweden" },
  },
  {
    registryNumber: "LR-MOST-TRANSLATED-INDIVIDUAL-AUTHOR", slug: "most-translated-individual-author", title: "Most translated individual author",
    category: "Food & Culture", subcategory: "Literature", direction: "MAXIMIZE",
    metricName: "Number of translated editions of a single author's works recorded in UNESCO's Index Translationum", unit: "translated editions",
    formalStatement: "The greatest number of translated editions of a single named individual author's body of work, as recorded in UNESCO's Index Translationum database.",
    summary: "According to UNESCO's Index Translationum, British crime writer Agatha Christie is the most translated individual author in recorded history, with her works translated into more than 100 languages across thousands of editions — a distinct record from 'most translated document,' which is held by a collectively authored text rather than a single author.",
    value: "7000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Compiled from UNESCO's Index Translationum database of translated book editions worldwide.",
    source: { title: "UNESCO — Index Translationum", url: "http://www.unesco.org/xtrans/", date: "2020-01-01", location: "Worldwide" },
  },
  {
    registryNumber: "LR-LARGEST-CHOCOLATE-BAR-EVER-MADE", slug: "largest-chocolate-bar-ever-made", title: "Largest chocolate bar ever made",
    category: "Food & Culture", subcategory: "Confectionery", direction: "MAXIMIZE",
    metricName: "Weight of the largest single chocolate bar ever made", unit: "kg",
    formalStatement: "The greatest weight of a single chocolate bar ever manufactured, as certified by Guinness World Records.",
    summary: "British confectioner Thorntons made the largest chocolate bar ever, weighing 5,792.5 kg (12,772 lb), unveiled in Alfreton, Derbyshire, UK, in October 2011 — a Guinness World Record for the heaviest chocolate bar.",
    value: "5792.5",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Weighed and certified on-site by an official Guinness World Records adjudicator.",
    source: { title: "Guinness World Records — Largest Chocolate Bar", url: "https://www.guinnessworldrecords.com/", date: "2011-10-14", location: "Alfreton, Derbyshire, UK" },
  },
  {
    registryNumber: "LR-LARGEST-ICE-CREAM-SUNDAE-EVER-MADE", slug: "largest-ice-cream-sundae-ever-made", title: "Largest ice cream sundae ever made",
    category: "Food & Culture", subcategory: "Confectionery", direction: "MAXIMIZE",
    metricName: "Weight of the largest ice cream sundae ever made", unit: "tonnes",
    formalStatement: "The greatest weight of a single ice cream sundae ever assembled, as certified by Guinness World Records.",
    summary: "Palm Dairies Ltd. created a 24.91-tonne (54,914 lb) ice cream sundae in Edmonton, Alberta, Canada, on July 24, 1988 — a Guinness World Record for the largest ice cream sundae ever made, a record that has stood for decades in part because later rule changes have made it far more difficult to attempt.",
    value: "24.91",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Weighed and certified by Guinness World Records at the time of the event.",
    source: { title: "Guinness World Records — Largest Ice Cream Sundae", url: "https://www.guinnessworldrecords.com/", date: "1988-07-24", location: "Edmonton, Alberta, Canada" },
  },
  {
    registryNumber: "LR-LANGUAGE-MOST-NATIVE-SPEAKERS", slug: "language-with-the-most-native-speakers", title: "Language with the most native speakers in the world",
    category: "Food & Culture", subcategory: "Language", direction: "MAXIMIZE",
    metricName: "Estimated number of native (first-language) speakers of the world's most widely spoken native language", unit: "speakers",
    formalStatement: "The greatest estimated number of people who speak a given language as their first (native) language.",
    summary: "Mandarin Chinese has an estimated 940 million or so native speakers, more than any other language in the world, according to Ethnologue's widely used language survey — well ahead of Spanish and English, which typically follow in second and third place among native-speaker counts, though English has far more total speakers when second-language speakers are included.",
    value: "940000000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Compiled from national census and demographic linguistic survey data by Ethnologue (SIL International).",
    source: { title: "Ethnologue — Languages of the World", url: "https://www.ethnologue.com/", date: "2023-01-01", location: "Worldwide" },
  },
  {
    registryNumber: "LR-LARGEST-FIREWORKS-DISPLAY-EVER", slug: "largest-fireworks-display-ever-held", title: "Largest fireworks display ever held",
    category: "Food & Culture", subcategory: "Festivals", direction: "MAXIMIZE",
    metricName: "Number of firework shells launched in a single continuous fireworks display", unit: "fireworks",
    formalStatement: "The greatest number of individual firework shells launched during a single, continuous fireworks display, as certified by Guinness World Records.",
    summary: "The city of Iligan in the Philippines launched 810,904 fireworks in a display lasting just over an hour, spanning New Year's Eve 2016 into New Year's Day 2017 — certified by Guinness World Records as the largest fireworks display ever held, surpassing a previous record set in Kuwait.",
    value: "810904",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Shell count logged and certified on-site by an official Guinness World Records adjudicator.",
    source: { title: "Guinness World Records — Largest Fireworks Display", url: "https://www.guinnessworldrecords.com/", date: "2017-01-01", location: "Iligan City, Philippines" },
  },
];
