import type { FrontierRecord } from "./frontier-records-2026";

// Batch 8: Mathematics, AI, and Energy records. Verified against primary/authoritative sources
// (published papers, official lab/company announcements, Guinness World Records, Wikipedia
// summaries of primary data) as of 2026-09-21. Several energy "largest X" facts are point-in-time
// records that have since been superseded by newer projects (noted explicitly in the summary,
// e.g. Bhadla Solar Park, North Sea Link/Viking Link) — these are recorded as historical or
// current records with that caveat rather than presented as permanently unbeatable.
export const WORLD_RECORDS_BATCH8_MATH_AI_ENERGY: FrontierRecord[] = [
  // ================= MATHEMATICS =================
  {
    registryNumber: "LR-FERMATS-LAST-THEOREM", slug: "fermats-last-theorem", title: "Proof of Fermat's Last Theorem",
    category: "Mathematics", subcategory: "Number Theory", direction: "MAXIMIZE",
    metricName: "Resolution of a 358-year-old open conjecture", unit: "boolean (proven/unproven)",
    formalStatement: "There are no positive integers a, b, c satisfying a^n + b^n = c^n for any integer value of n greater than 2.",
    summary: "Andrew Wiles, with a key gap closed jointly with Richard Taylor, proved Fermat's Last Theorem, publishing the complete argument in the Annals of Mathematics in 1995. The proof works by establishing the modularity of semistable elliptic curves (via the Taniyama-Shimura-Weil conjecture) and connecting it to Fermat's equation through Ribet's theorem, closing a problem first stated by Pierre de Fermat in 1637.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "PROVEN",
    methodSummary: "Proved the modularity of semistable elliptic curves, connecting it to Fermat's equation via Ribet's theorem and the Frey curve construction; published after peer review in a top mathematics journal.",
    source: { title: "Wiles, 'Modular elliptic curves and Fermat's Last Theorem', Annals of Mathematics", url: "https://en.wikipedia.org/wiki/Wiles%27s_proof_of_Fermat%27s_Last_Theorem", date: "1995-05-01", location: "Princeton University, USA" },
  },
  {
    registryNumber: "LR-FOUR-COLOR-THEOREM", slug: "four-color-theorem", title: "Proof of the Four Color Theorem",
    category: "Mathematics", subcategory: "Graph Theory", direction: "MAXIMIZE",
    metricName: "First major theorem proved with essential computer assistance", unit: "boolean (proven/unproven)",
    formalStatement: "Any planar map can be colored using at most four colors such that no two adjacent regions share the same color.",
    summary: "Kenneth Appel and Wolfgang Haken proved the Four Color Theorem in 1976 at the University of Illinois, reducing the problem to checking 1,936 (later reduced) unavoidable configurations by computer — the first widely accepted major mathematical theorem whose proof depended essentially on computer verification, which was controversial among mathematicians at the time. A cleaner, independently verified proof was published by Robertson, Sanders, Seymour, and Thomas in 1997.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "PROVEN",
    methodSummary: "Reduced the general map-coloring problem to a finite (but large) set of unavoidable configurations, each checked exhaustively by computer program.",
    source: { title: "Appel & Haken, 'Every planar map is four colorable', Illinois Journal of Mathematics", url: "https://en.wikipedia.org/wiki/Four_color_theorem", date: "1976-07-01", location: "University of Illinois at Urbana-Champaign, USA" },
  },
  {
    registryNumber: "LR-POINCARE-CONJECTURE", slug: "poincare-conjecture", title: "Proof of the Poincaré Conjecture",
    category: "Mathematics", subcategory: "Topology", direction: "MAXIMIZE",
    metricName: "Resolution of a Clay Millennium Prize Problem", unit: "boolean (proven/unproven)",
    formalStatement: "Every simply connected, closed 3-manifold is homeomorphic to the 3-sphere.",
    summary: "Grigori Perelman proved the Poincaré Conjecture in a series of papers posted to arXiv in 2002-2003, by completing Richard Hamilton's Ricci flow program with a technique called 'surgery' to handle singularities. The mathematical community spent several years verifying the argument before it was widely accepted around 2006. Perelman was awarded the Clay Mathematics Institute's $1 million Millennium Prize in 2010 and the Fields Medal in 2006, both of which he declined.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "PROVEN",
    methodSummary: "Extended Hamilton's Ricci flow with surgery to resolve singularities that form during the flow, proving the stronger Geometrization Conjecture along the way.",
    source: { title: "Clay Mathematics Institute — Millennium Problems: Poincaré Conjecture", url: "https://www.claymath.org/millennium/poincare-conjecture/", date: "2010-03-18", location: "Steklov Institute of Mathematics, St. Petersburg, Russia" },
  },
  {
    registryNumber: "LR-KEPLER-CONJECTURE-FLYSPECK", slug: "kepler-conjecture-flyspeck", title: "Formal verification of the Kepler Conjecture (Flyspeck project)",
    category: "Mathematics", subcategory: "Discrete Geometry", direction: "MAXIMIZE",
    metricName: "Completion of a fully machine-checked formal proof", unit: "boolean (proven/unproven)",
    formalStatement: "No arrangement of equally sized spheres in three-dimensional space has a greater average density than the face-centered cubic (or equivalently hexagonal close) packing, which fills approximately 74.05% of space.",
    summary: "Thomas Hales announced a proof of the Kepler Conjecture in 1998 using an exhaustive computer-assisted case analysis, but reviewers could only be '99% certain' it was correct after four years of checking. Hales then led the Flyspeck project to formally verify every step in machine-checkable proof assistants (HOL Light and Isabelle), completing it in 2014 and publishing the fully formalized result in 2017.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "PROVEN",
    methodSummary: "Reduced the packing problem to optimizing a function over a finite (but enormous) set of configurations, verified computationally, then re-verified line by line in formal proof assistants over a ~12-year collaborative project.",
    source: { title: "Hales et al., 'A formal proof of the Kepler conjecture', Forum of Mathematics, Pi", url: "https://arxiv.org/abs/1501.02155", date: "2017-05-01", location: "University of Pittsburgh, USA (Flyspeck project)" },
  },
  {
    registryNumber: "LR-CLASSIFICATION-FINITE-SIMPLE-GROUPS", slug: "classification-finite-simple-groups", title: "Classification of Finite Simple Groups",
    category: "Mathematics", subcategory: "Group Theory", direction: "MAXIMIZE",
    metricName: "Total published page count of a single collaborative theorem's proof", unit: "pages",
    formalStatement: "Every finite simple group belongs to one of a small number of known families (cyclic, alternating, groups of Lie type) or is one of 26 'sporadic' exceptions, including the Monster group.",
    summary: "The classification theorem is the result of a collaborative effort by roughly 100 mathematicians across several hundred journal articles from the 1950s through the 1980s, organized largely under Daniel Gorenstein's program. A subtle gap in the classification of quasithin groups was identified and closed by Michael Aschbacher and Stephen Smith in a two-volume, 1,221-page work published in 2004, generally considered the point at which the classification was fully complete. Estimates of the total proof length across all contributing papers commonly run to 10,000-15,000 pages, making it the largest collaborative proof in mathematics.",
    value: "15000", claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "PROVEN",
    methodSummary: "Decades-long, multi-author case-by-case analysis of possible finite simple group structures, coordinated across the mathematical community and later revisited to close a remaining gap in the quasithin case.",
    source: { title: "Aschbacher & Smith, 'The Classification of Quasithin Groups', AMS Mathematical Surveys and Monographs", url: "https://en.wikipedia.org/wiki/Classification_of_finite_simple_groups", date: "2004-01-01", location: "American Mathematical Society" },
  },
  {
    registryNumber: "LR-GREEN-TAO-THEOREM", slug: "green-tao-theorem", title: "Green-Tao Theorem on primes in arithmetic progression",
    category: "Mathematics", subcategory: "Number Theory", direction: "MAXIMIZE",
    metricName: "Existence of arbitrarily long arithmetic progressions of primes", unit: "boolean (proven/unproven)",
    formalStatement: "For any positive integer k, there exist k prime numbers in arithmetic progression (i.e., k primes p, p+d, p+2d, ..., p+(k-1)d for some common difference d).",
    summary: "Ben Green and Terence Tao proved in a 2004 paper (published in Annals of Mathematics in 2008) that the prime numbers contain arithmetic progressions of every finite length, despite primes becoming increasingly sparse. The proof combines ergodic theory and additive combinatorics, extending Szemerédi's theorem on arithmetic progressions in dense sets to the 'sparse' set of primes via a transference principle.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "PROVEN",
    methodSummary: "Developed a transference principle extending Szemerédi's theorem from dense integer sets to sparse pseudorandom sets, then showed the primes have enough pseudorandom structure for the argument to apply.",
    source: { title: "Green & Tao, 'The primes contain arbitrarily long arithmetic progressions', Annals of Mathematics", url: "https://arxiv.org/abs/math/0404188", date: "2008-05-01", location: "University of Bristol, UK / UCLA, USA" },
  },
  {
    registryNumber: "LR-CATALANS-CONJECTURE", slug: "catalans-conjecture-mihailescu", title: "Proof of Catalan's Conjecture (Mihailescu's Theorem)",
    category: "Mathematics", subcategory: "Number Theory", direction: "MAXIMIZE",
    metricName: "Resolution of a 158-year-old Diophantine conjecture", unit: "boolean (proven/unproven)",
    formalStatement: "The only solution in the natural numbers of x^p - y^q = 1 for x, y, p, q all greater than 1 is 3^2 - 2^3 = 1, i.e. 8 and 9 are the only consecutive perfect powers.",
    summary: "Preda Mihailescu proved Catalan's Conjecture, first stated by Eugène Charles Catalan in 1844, in a 2002 paper published in Crelle's Journal in 2004. The proof uses techniques from the theory of cyclotomic fields, in particular results about Wieferich pairs, and settled a problem that had resisted attack for over 150 years despite earlier partial results by Cassels and others.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "PROVEN",
    methodSummary: "Applied the theory of cyclotomic fields and a refinement of Wieferich-pair criteria to rule out all solutions of the generalized Catalan equation other than the known 8, 9 case.",
    source: { title: "Mihailescu, 'Primary Cyclotomic Units and a Proof of Catalan's Conjecture', Journal für die reine und angewandte Mathematik", url: "https://en.wikipedia.org/wiki/Catalan%27s_conjecture", date: "2004-01-01", location: "University of Paderborn, Germany" },
  },
  {
    registryNumber: "LR-ERDOS-DISCREPANCY-PROBLEM", slug: "erdos-discrepancy-problem", title: "Proof of the Erdős Discrepancy Problem",
    category: "Mathematics", subcategory: "Combinatorics", direction: "MAXIMIZE",
    metricName: "Resolution of a discrepancy conjecture posed in the 1930s", unit: "boolean (proven/unproven)",
    formalStatement: "For any infinite sequence of +1s and -1s and any constant C, there exist integers d and k such that the sum of every d-th term up to the k-th multiple of d exceeds C in absolute value — i.e. the discrepancy of any ±1 sequence along homogeneous arithmetic progressions is unbounded.",
    summary: "Terence Tao proved the Erdős Discrepancy Problem in 2015, showing that the discrepancy of any infinite ±1 sequence along arithmetic progressions is unbounded, resolving a conjecture Paul Erdős posed around 1932. The proof built on the Polymath5 collaborative project and, notably, on a computer-generated 13-gigabyte SAT-solver proof by Boris Konev and Alexei Lisitsa (2014) that had already established the discrepancy exceeds 2, combined with new analytic number theory results connected to a partial resolution of the Elliott conjecture.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "PROVEN",
    methodSummary: "Combined an existing computer-assisted lower bound (via SAT solving) with a new proof of a special case of the Elliott conjecture on multiplicative functions to establish unbounded discrepancy in general.",
    source: { title: "Tao, 'The Erdős discrepancy problem', Discrete Analysis", url: "https://arxiv.org/abs/1509.05363", date: "2015-09-17", location: "UCLA, USA" },
  },
  {
    registryNumber: "LR-SPHERE-PACKING-DIMENSION-8", slug: "sphere-packing-dimension-8", title: "Optimal sphere packing in 8 dimensions (E8 lattice)",
    category: "Mathematics", subcategory: "Discrete Geometry", direction: "MAXIMIZE",
    metricName: "Proof of optimality of a specific lattice sphere packing", unit: "boolean (proven/unproven)",
    formalStatement: "The E8 lattice sphere packing achieves the maximum possible density of any arrangement of non-overlapping equal spheres in 8-dimensional Euclidean space.",
    summary: "Maryna Viazovska proved in 2016 that the E8 lattice gives the densest possible sphere packing in 8 dimensions, resolving a problem open for decades and doing so with a strikingly short (roughly 20-page) proof using modular forms to construct an optimal auxiliary function for the linear programming bound. The result won her a share of the 2022 Fields Medal.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "PROVEN",
    methodSummary: "Constructed an explicit modular form-based magic function achieving the Cohn-Elkies linear programming bound exactly for the E8 lattice, proving no denser packing can exist.",
    source: { title: "Viazovska, 'The sphere packing problem in dimension 8', Annals of Mathematics", url: "https://arxiv.org/abs/1603.04246", date: "2016-03-14", location: "École Polytechnique Fédérale de Lausanne, Switzerland" },
  },
  {
    registryNumber: "LR-SPHERE-PACKING-DIMENSION-24", slug: "sphere-packing-dimension-24", title: "Optimal sphere packing in 24 dimensions (Leech lattice)",
    category: "Mathematics", subcategory: "Discrete Geometry", direction: "MAXIMIZE",
    metricName: "Proof of optimality of a specific lattice sphere packing", unit: "boolean (proven/unproven)",
    formalStatement: "The Leech lattice sphere packing achieves the maximum possible density of any arrangement of non-overlapping equal spheres in 24-dimensional Euclidean space.",
    summary: "Weeks after Viazovska's 8-dimensional result, she and coauthors Henry Cohn, Abhinav Kumar, Stephen D. Miller, and Danylo Radchenko extended the same modular-forms technique to prove the Leech lattice is the optimal sphere packing in 24 dimensions, published in 2017. Dimensions 8 and 24 remain the only dimensions above 3 where the optimal sphere packing has been rigorously proven.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "PROVEN",
    methodSummary: "Generalized the modular-form magic function construction used for the E8 case to the higher-dimensional setting relevant to the Leech lattice, again achieving the Cohn-Elkies linear programming bound exactly.",
    source: { title: "Cohn, Kumar, Miller, Radchenko & Viazovska, 'The sphere packing problem in dimension 24', Annals of Mathematics", url: "https://arxiv.org/abs/1603.06518", date: "2017-01-01", location: "Microsoft Research New England / Rutgers University, USA" },
  },
  {
    registryNumber: "LR-TERNARY-GOLDBACH-CONJECTURE", slug: "ternary-goldbach-conjecture", title: "Proof of the ternary (weak) Goldbach Conjecture",
    category: "Mathematics", subcategory: "Number Theory", direction: "MAXIMIZE",
    metricName: "Full unconditional resolution of a 271-year-old conjecture", unit: "boolean (proven/unproven)",
    formalStatement: "Every odd integer greater than 5 can be written as the sum of three prime numbers.",
    summary: "Harald Helfgott gave a complete, unconditional proof of the ternary Goldbach Conjecture in 2013, building on Vinogradov's 1937 theorem that the result holds for all sufficiently large odd numbers. Helfgott's contribution was tightening the analytic estimates enough to push the 'sufficiently large' threshold down to a range that could be exhaustively checked by computer for all smaller cases, closing the last gap. The stronger binary (even number) Goldbach Conjecture remains open.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "PROVEN",
    methodSummary: "Improved circle-method estimates (major and minor arcs) to lower Vinogradov's threshold for 'sufficiently large' odd numbers to a computationally verifiable bound, then verified all remaining cases by direct computation.",
    source: { title: "Helfgott, 'The ternary Goldbach conjecture is true'", url: "https://arxiv.org/abs/1312.7748", date: "2013-12-01", location: "École Normale Supérieure, Paris, France" },
  },
  {
    registryNumber: "LR-CAP-SET-PROBLEM", slug: "cap-set-problem-polynomial-method", title: "Resolution of the Cap Set Problem growth rate",
    category: "Mathematics", subcategory: "Additive Combinatorics", direction: "MINIMIZE",
    metricName: "Exponential base bounding the maximum size of a cap set in F_3^n", unit: "base of exponential bound",
    formalStatement: "The maximum size of a subset of F_3^n containing no three-term arithmetic progression (a 'cap set') grows as O(c^n) for some constant c strictly less than 3, as n tends to infinity.",
    summary: "In May 2016, Ernie Croot, Vsevolod Lev, and Péter Pál Pach introduced a new polynomial method that, combined independently within days by Jordan Ellenberg and Dion Gijswijt, proved a sharp exponential upper bound on cap set size — resolving a growth-rate question about the cap set problem that had resisted attack via traditional Fourier-analytic methods for years. The result also resolved related problems, including bounding the size of 'sunflower-free' families and progression-free sets in other groups.",
    value: "2.756", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "PROVEN",
    methodSummary: "Applied the polynomial method (via the Croot-Lev-Pach lemma bounding tensor rank) to derive an exponential upper bound on progression-free set sizes, a technique quickly adapted from the finite-field setting to other combinatorial problems.",
    source: { title: "Ellenberg & Gijswijt, 'On large subsets of F_q^n with no three-term arithmetic progression', Annals of Mathematics", url: "https://arxiv.org/abs/1605.09223", date: "2016-05-31", location: "University of Wisconsin-Madison, USA / Delft University of Technology, Netherlands" },
  },
  {
    registryNumber: "LR-HADWIGER-NELSON-LOWER-BOUND", slug: "hadwiger-nelson-lower-bound", title: "Hadwiger-Nelson problem — chromatic number of the plane, lower bound raised to 5",
    category: "Mathematics", subcategory: "Combinatorial Geometry", direction: "MAXIMIZE",
    metricName: "Proven lower bound on the chromatic number of the plane", unit: "colors",
    formalStatement: "The minimum number of colors needed to color every point in the Euclidean plane so that no two points at exactly unit distance apart share the same color is at least 5 (the exact value remains unknown, with an upper bound of 7).",
    summary: "Aubrey de Grey, a biogerontologist working as a mathematics hobbyist, found an explicit 1,581-vertex unit-distance graph in April 2018 that cannot be properly colored with only 4 colors, raising the long-standing lower bound on the Hadwiger-Nelson problem from 4 to 5 for the first time since the bound was established in the 1950s. The exact chromatic number of the plane remains an open problem, bounded between 5 and 7.",
    value: "5", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Constructed an explicit finite unit-distance graph and used a SAT solver plus a Polymath-project-led collaborative effort to verify and later shrink the graph, showing it admits no valid 4-coloring.",
    source: { title: "de Grey, 'The chromatic number of the plane is at least 5'", url: "https://arxiv.org/abs/1804.02385", date: "2018-04-08", location: "SENS Research Foundation, Mountain View, California, USA" },
  },
  {
    registryNumber: "LR-CHECKERS-SOLVED", slug: "checkers-solved", title: "Checkers formally solved (weak solution)",
    category: "Mathematics", subcategory: "Combinatorial Game Theory", direction: "MAXIMIZE",
    metricName: "Complete game-theoretic solution of a nontrivial board game", unit: "boolean (proven/unproven)",
    formalStatement: "With perfect play by both sides, a game of checkers (English draughts, 8x8 board) always ends in a draw.",
    summary: "Jonathan Schaeffer and colleagues at the University of Alberta announced in 2007, after roughly 18 years of computation with their Chinook program, that checkers is a weakly solved game: with perfect play by both sides the outcome is always a draw. The proof required proving outcomes for a database of positions covering the vast majority of the roughly 5x10^20 possible checkers positions, published in Science.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "PROVEN",
    methodSummary: "Combined alpha-beta search from the game's start with retrograde endgame-database analysis working backward from all positions with 10 or fewer pieces, meeting in the middle to certify the draw outcome.",
    source: { title: "Schaeffer et al., 'Checkers Is Solved', Science", url: "https://www.science.org/doi/10.1126/science.1144079", date: "2007-07-19", location: "University of Alberta, Canada" },
  },
  {
    registryNumber: "LR-CONNECT-FOUR-SOLVED", slug: "connect-four-solved", title: "Connect Four formally solved (first-player win)",
    category: "Mathematics", subcategory: "Combinatorial Game Theory", direction: "MAXIMIZE",
    metricName: "Complete game-theoretic solution of a nontrivial board game", unit: "boolean (proven/unproven)",
    formalStatement: "On the standard 7-column, 6-row Connect Four board, the first player can always force a win with perfect play.",
    summary: "James D. Allen and, independently, Victor Allis both solved Connect Four in October 1988, proving the first player can always force a win by starting in the center column. Allis's solution used a knowledge-based approach with nine strategic rules; the game was later 'strongly solved' (giving the exact win/loss/draw outcome from every reachable position, not just the starting one) via exhaustive computer search by Allis and, independently, John Tromp.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "PROVEN",
    methodSummary: "Combined hand-derived strategic rules for forced wins with alpha-beta game-tree search to prove the outcome of optimal play from the empty board, later extended to exhaustive search over all reachable positions.",
    source: { title: "Allis, 'A Knowledge-based Approach of Connect-Four', MSc thesis, Vrije Universiteit Amsterdam", url: "https://en.wikipedia.org/wiki/Connect_Four", date: "1988-10-01", location: "Vrije Universiteit Amsterdam, Netherlands" },
  },
  {
    registryNumber: "LR-APERYS-THEOREM", slug: "aperys-theorem-zeta-3-irrational", title: "Apéry's Theorem — irrationality of zeta(3)",
    category: "Mathematics", subcategory: "Number Theory", direction: "MAXIMIZE",
    metricName: "Proof of irrationality of a specific value of the Riemann zeta function", unit: "boolean (proven/unproven)",
    formalStatement: "The value zeta(3) = sum over n>=1 of 1/n^3 (approximately 1.2020569..., also called Apéry's constant) is an irrational number.",
    summary: "Roger Apéry proved in 1978 that zeta(3) is irrational, presenting the surprising result at a conference in Marseille to an initially skeptical audience who found his methods opaque. The proof was later clarified and confirmed correct by other mathematicians, including Alfred van der Poorten and Frits Beukers, and it remains the only odd zeta value proven irrational — whether zeta(5), zeta(7), and other odd zeta values are irrational remains open (though Tanguy Rivoal showed in 2000 that infinitely many odd zeta values must be irrational).",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "PROVEN",
    methodSummary: "Constructed a rapidly converging rational approximation sequence to zeta(3) using recurrence relations, then applied a classical irrationality criterion showing no fraction could approximate it that well.",
    source: { title: "van der Poorten, 'A proof that Euler missed... Apéry's proof of the irrationality of zeta(3)'", url: "https://en.wikipedia.org/wiki/Ap%C3%A9ry%27s_theorem", date: "1979-01-01", location: "Conference in Marseille, France (1978)" },
  },
  {
    registryNumber: "LR-WEAIRE-PHELAN-STRUCTURE", slug: "weaire-phelan-structure", title: "Weaire-Phelan structure disproves Kelvin's conjecture",
    category: "Mathematics", subcategory: "Discrete Geometry", direction: "MINIMIZE",
    metricName: "Surface area per cell relative to Kelvin's proposed optimal foam structure", unit: "% of Kelvin structure's surface area",
    formalStatement: "There exists a partition of three-dimensional space into equal-volume cells with lower average surface area per cell than Lord Kelvin's 1887 tetrakaidecahedron ('Kelvin structure') partition, disproving Kelvin's conjecture that his structure was optimal.",
    summary: "Denis Weaire and Robert Phelan, physicists at Trinity College Dublin, found in 1993 a structure using two different cell shapes (irregular pentagonal dodecahedra and tetrakaidecahedra) that partitions space using approximately 0.3% less surface area per cell than Lord Kelvin's 1887 proposed optimal structure, disproving Kelvin's century-old conjecture. The Weaire-Phelan structure remains the best known partition of space by equal-volume cells, though it has not been proven optimal.",
    value: "99.7", claimType: "COUNTEREXAMPLE", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Computer simulation of candidate foam structures using minimal-surface energy calculations, discovering a lower-energy two-cell-type structure that beats the Kelvin structure's surface area.",
    source: { title: "Weaire & Phelan, 'A counter-example to Kelvin's conjecture on minimal surfaces', Philosophical Magazine Letters", url: "https://en.wikipedia.org/wiki/Weaire%E2%80%93Phelan_structure", date: "1993-01-01", location: "Trinity College Dublin, Ireland" },
  },
  {
    registryNumber: "LR-ROBERTSON-SEYMOUR-GRAPH-MINORS", slug: "robertson-seymour-graph-minors", title: "Robertson-Seymour Graph Minor Theorem",
    category: "Mathematics", subcategory: "Graph Theory", direction: "MAXIMIZE",
    metricName: "Length of a single theorem's proof, by paper count and years spanned", unit: "papers",
    formalStatement: "In any infinite collection of finite graphs, one graph is always a minor of another — i.e., finite graphs are well-quasi-ordered under the graph minor relation (proving Wagner's conjecture).",
    summary: "Neil Robertson and Paul Seymour proved the Graph Minor Theorem across a series of 20-plus papers published from 1983 to 2004, one of the longest and most technically demanding proofs in mathematics, running to roughly 500 combined journal pages. The theorem has significant algorithmic consequences, implying that many graph properties can be tested in polynomial time, and it settled a conjecture posed by Klaus Wagner.",
    value: "20", claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "PROVEN",
    methodSummary: "Developed the theory of graph 'tree-width' and a structure theorem describing how graphs excluding a fixed minor can be decomposed, built up incrementally across two decades of joint papers.",
    source: { title: "Robertson & Seymour, 'Graph Minors' series, Journal of Combinatorial Theory, Series B", url: "https://en.wikipedia.org/wiki/Robertson%E2%80%93Seymour_theorem", date: "2004-01-01", location: "Ohio State University / Princeton University, USA" },
  },
  {
    registryNumber: "LR-FEIT-THOMPSON-FORMALIZATION", slug: "feit-thompson-formalization", title: "Formal verification of the Feit-Thompson (Odd Order) Theorem",
    category: "Mathematics", subcategory: "Formal Verification", direction: "MAXIMIZE",
    metricName: "Lines of formalized proof code for a single classical theorem", unit: "lines of Coq code",
    formalStatement: "Every finite group of odd order is solvable (the Feit-Thompson theorem, originally proved in 1963), here machine-verified line by line in a formal proof assistant.",
    summary: "Georges Gonthier led a team at Microsoft Research-INRIA that in 2012 completed a full formalization of the Feit-Thompson theorem — originally a roughly 255-page proof from 1963 — in the Coq proof assistant, producing about 170,000 lines of formal proof code checked automatically by machine, at the time one of the largest formalized mathematical proofs ever completed. The project took about six years and helped establish formal proof assistants as viable for verifying genuinely deep, research-level mathematics.",
    value: "170000", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "PROVEN",
    methodSummary: "Translated the entire original group-theoretic proof into the Coq dependent type theory formal language, verified automatically by Coq's proof-checking kernel with no reliance on informal mathematical judgment.",
    source: { title: "Gonthier et al., 'A Machine-Checked Proof of the Odd Order Theorem', ITP 2013", url: "https://hal.inria.fr/hal-00816699", date: "2012-09-20", location: "Microsoft Research-INRIA Joint Centre, France" },
  },

  // ================= AI =================
  {
    registryNumber: "LR-DEEP-BLUE-KASPAROV", slug: "deep-blue-kasparov", title: "Deep Blue defeats Garry Kasparov",
    category: "AI", subcategory: "Game Playing", direction: "MAXIMIZE",
    metricName: "First defeat of a reigning world chess champion by a computer in a standard match", unit: "boolean (achieved/not achieved)",
    formalStatement: "In a six-game rematch under standard tournament time controls, IBM's Deep Blue defeated reigning World Chess Champion Garry Kasparov 3.5-2.5, the first time a computer had beaten a sitting world champion in a full match under normal conditions.",
    summary: "IBM's Deep Blue defeated Garry Kasparov in a six-game match held in New York in May 1997, scoring two wins, one loss, and three draws. Deep Blue was a purpose-built chess supercomputer capable of evaluating roughly 200 million chess positions per second using specialized chess hardware. The match remains a landmark, widely cited milestone in the public perception of AI capability.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Massively parallel, purpose-built chess hardware combining brute-force alpha-beta minimax search (roughly 200 million positions/second) with a hand-tuned evaluation function refined by chess grandmasters.",
    source: { title: "IBM Research — Deep Blue", url: "https://www.ibm.com/history/deep-blue", date: "1997-05-11", location: "IBM, New York, USA" },
  },
  {
    registryNumber: "LR-WATSON-JEOPARDY", slug: "watson-jeopardy-victory", title: "IBM Watson defeats human Jeopardy! champions",
    category: "AI", subcategory: "Natural Language Question Answering", direction: "MAXIMIZE",
    metricName: "First AI system to defeat top human champions in a natural-language quiz competition on television", unit: "boolean (achieved/not achieved)",
    formalStatement: "IBM's Watson question-answering system defeated Jeopardy!'s two most successful all-time human champions, Ken Jennings and Brad Rutter, in a televised two-game exhibition match.",
    summary: "IBM Watson defeated Ken Jennings and Brad Rutter in a televised Jeopardy! exhibition match aired February 14-16, 2011, finishing with $77,147 versus Jennings's $24,000 and Rutter's $21,600. Watson combined natural language processing, information retrieval across a large offline corpus (with no live internet access), and statistical confidence scoring to buzz in and answer faster and more reliably than its human opponents on open-domain trivia.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "DeepQA architecture: parsed natural-language clues, generated many candidate answers via parallel search across a large corpus of unstructured text, then scored and ranked candidates using hundreds of statistical evidence-gathering algorithms.",
    source: { title: "IBM Research — Watson and the Jeopardy! Challenge", url: "https://www.ibm.com/history/watson-jeopardy", date: "2011-02-16", location: "IBM, USA" },
  },
  {
    registryNumber: "LR-ALEXNET-IMAGENET", slug: "alexnet-imagenet-2012", title: "AlexNet's ImageNet breakthrough",
    category: "AI", subcategory: "Computer Vision", direction: "MINIMIZE",
    metricName: "Top-5 classification error rate on the ImageNet Large Scale Visual Recognition Challenge", unit: "% top-5 error",
    formalStatement: "AlexNet, a deep convolutional neural network trained on GPUs, achieved a 15.3% top-5 error rate on the 2012 ImageNet Large Scale Visual Recognition Challenge (ILSVRC), a roughly 10-percentage-point improvement over the next-best (non-deep-learning) entry's 26.2%.",
    summary: "Alex Krizhevsky, Ilya Sutskever, and Geoffrey Hinton's AlexNet won the 2012 ImageNet competition by a dramatic margin, widely credited as the moment that triggered the modern deep learning boom in computer vision and, subsequently, across AI broadly. The model trained a large convolutional network on two consumer GPUs (Nvidia GTX 580s), a then-novel approach that made training deep networks on large datasets practical.",
    value: "15.3", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Trained an eight-layer convolutional neural network on 1.2 million labeled ImageNet images using GPU-accelerated backpropagation, ReLU activations, dropout regularization, and data augmentation.",
    source: { title: "Krizhevsky, Sutskever & Hinton, 'ImageNet Classification with Deep Convolutional Neural Networks', NeurIPS 2012", url: "https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks", date: "2012-12-03", location: "University of Toronto, Canada" },
  },
  {
    registryNumber: "LR-RESNET-HUMAN-LEVEL-IMAGENET", slug: "resnet-surpasses-human-level-imagenet", title: "ResNet surpasses estimated human-level performance on ImageNet",
    category: "AI", subcategory: "Computer Vision", direction: "MINIMIZE",
    metricName: "Top-5 classification error rate on ImageNet, first below the human-level benchmark", unit: "% top-5 error",
    formalStatement: "Microsoft Research's ResNet achieved a 3.57% top-5 error rate on the ImageNet classification task in the 2015 ILSVRC, the first model to score below the commonly cited human-level benchmark of approximately 5.1% top-5 error established by a trained human annotator.",
    summary: "Kaiming He and colleagues at Microsoft Research introduced deep residual networks ('ResNet') in late 2015, winning the ILSVRC 2015 classification task with a 3.57% top-5 error rate using a 152-layer network — far deeper than prior architectures — made trainable via 'skip connections' that let gradients flow through many layers. It was the first model to beat the human-level ImageNet benchmark Andrej Karpathy had established by hand-labeling images himself in 2014.",
    value: "3.57", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Introduced residual ('skip') connections that let each layer learn a correction to the identity function, enabling stable training of networks over 100 layers deep, evaluated on the standard ImageNet-1k benchmark.",
    source: { title: "He, Zhang, Ren & Sun, 'Deep Residual Learning for Image Recognition', CVPR 2016", url: "https://arxiv.org/abs/1512.03385", date: "2015-12-10", location: "Microsoft Research, Beijing, China" },
  },
  {
    registryNumber: "LR-ALPHAGO-LEE-SEDOL", slug: "alphago-defeats-lee-sedol", title: "AlphaGo defeats Lee Sedol",
    category: "AI", subcategory: "Game Playing", direction: "MAXIMIZE",
    metricName: "First AI to defeat a top-ranked professional Go player in a full match without a handicap", unit: "match score",
    formalStatement: "DeepMind's AlphaGo defeated Lee Sedol, a 9-dan professional and one of the top Go players in the world, 4 games to 1 in a five-game match played in Seoul, South Korea in March 2016.",
    summary: "AlphaGo's victory over Lee Sedol in March 2016 was a landmark AI milestone: Go's enormous branching factor and reliance on intuitive pattern recognition had led many experts to predict computers were a decade or more away from beating top human players. AlphaGo combined deep neural networks trained on human expert games with Monte Carlo tree search and reinforcement learning from self-play.",
    value: "4", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Combined policy and value neural networks (trained via supervised learning on human games, then refined via self-play reinforcement learning) with Monte Carlo tree search to evaluate and select moves.",
    source: { title: "DeepMind — AlphaGo: The story so far", url: "https://deepmind.google/research/breakthroughs/alphago/", date: "2016-03-15", location: "Google DeepMind, Seoul, South Korea" },
  },
  {
    registryNumber: "LR-ALPHAGO-ZERO-SELF-PLAY", slug: "alphago-zero-self-play-training", title: "AlphaGo Zero — superhuman Go from pure self-play",
    category: "AI", subcategory: "Reinforcement Learning", direction: "MINIMIZE",
    metricName: "Days of self-play training required to reach superhuman Go strength, with zero human game data", unit: "days",
    formalStatement: "AlphaGo Zero, given only the rules of Go and no human game records or handcrafted features, trained purely through self-play reinforcement learning and surpassed the strength of the AlphaGo version that defeated Lee Sedol within 40 days of training.",
    summary: "DeepMind's AlphaGo Zero, described in an October 2017 Nature paper, learned Go entirely from self-play starting from random moves, using a single neural network trained via a novel reinforcement learning algorithm without any human game data. It surpassed the version of AlphaGo that had beaten Lee Sedol after about 40 days of self-play training on a single machine, and its architecture was subsequently generalized into AlphaZero for chess and shogi.",
    value: "40", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "A single deep neural network jointly predicting move probabilities and position value, trained purely via self-play reinforcement learning guided by Monte Carlo tree search, with no human game data or handcrafted features.",
    source: { title: "Silver et al., 'Mastering the game of Go without human knowledge', Nature", url: "https://www.nature.com/articles/nature24270", date: "2017-10-18", location: "Google DeepMind, London, UK" },
  },
  {
    registryNumber: "LR-LIBRATUS-HEADS-UP-POKER", slug: "libratus-heads-up-poker", title: "Libratus defeats top humans at heads-up no-limit poker",
    category: "AI", subcategory: "Game Playing", direction: "MAXIMIZE",
    metricName: "First AI to decisively beat elite human professionals in heads-up no-limit Texas hold'em", unit: "boolean (achieved/not achieved)",
    formalStatement: "Carnegie Mellon University's Libratus AI defeated four top human heads-up no-limit Texas hold'em specialists by a statistically significant margin over a 120,000-hand, 20-day match in January 2017.",
    summary: "Libratus, developed by Noam Brown and Tuomas Sandholm at Carnegie Mellon University, beat four elite professional heads-up poker players (Dong Kim, Jason Les, Jimmy Chou, and Daniel McAulay) by a combined margin of over $1.7 million in chips across 120,000 hands played at the Rivers Casino in Pittsburgh in the 'Brains vs. Artificial Intelligence' competition. It was the first AI to beat top humans decisively at a game of imperfect information with this much strategic depth.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Computed an approximate Nash equilibrium strategy offline via counterfactual regret minimization over an abstracted version of the game, then used real-time subgame solving to refine strategy for specific situations during play.",
    source: { title: "Brown & Sandholm, 'Superhuman AI for heads-up no-limit poker: Libratus beats top professionals', Science", url: "https://www.science.org/doi/10.1126/science.aao1733", date: "2017-12-01", location: "Carnegie Mellon University, Pittsburgh, USA" },
  },
  {
    registryNumber: "LR-ALPHAZERO-STOCKFISH", slug: "alphazero-defeats-stockfish", title: "AlphaZero defeats Stockfish in chess after hours of self-play",
    category: "AI", subcategory: "Game Playing", direction: "MINIMIZE",
    metricName: "Hours of self-play training required to reach superhuman chess strength from the rules alone", unit: "hours",
    formalStatement: "DeepMind's AlphaZero, trained from random play using only the rules of chess and 9 hours of self-play reinforcement learning with no opening books, endgame tables, or human game data, decisively defeated the 2016 world computer chess champion program Stockfish 8 in a 100-game match.",
    summary: "AlphaZero generalized the AlphaGo Zero self-play approach to chess (and shogi), and in a December 2017 paper DeepMind reported that after just 9 hours of self-play training it defeated Stockfish 8 (then the strongest conventional chess engine) in a 100-game match, winning 28 games, drawing 72, and losing none, while evaluating vastly fewer positions per second than Stockfish's brute-force search. The result showed that a general-purpose self-play algorithm could surpass decades of hand-engineered chess-specific search heuristics.",
    value: "9", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "A single deep neural network trained purely via self-play reinforcement learning guided by Monte Carlo tree search, with no game-specific heuristics beyond the rules, generalized from the AlphaGo Zero algorithm.",
    source: { title: "Silver et al., 'Mastering Chess and Shogi by Self-Play with a General Reinforcement Learning Algorithm'", url: "https://arxiv.org/abs/1712.01815", date: "2017-12-05", location: "Google DeepMind, London, UK" },
  },
  {
    registryNumber: "LR-PLURIBUS-SIX-PLAYER-POKER", slug: "pluribus-six-player-poker", title: "Pluribus defeats top humans at six-player no-limit poker",
    category: "AI", subcategory: "Game Playing", direction: "MAXIMIZE",
    metricName: "First AI to beat elite human professionals in a multi-player (six-way), no-limit poker format", unit: "boolean (achieved/not achieved)",
    formalStatement: "Pluribus, developed by Carnegie Mellon University and Facebook AI Research, defeated a table of five elite human professionals simultaneously (and separately, one elite pro against five copies of itself) at six-player no-limit Texas hold'em, the first superhuman AI result in a poker format with more than two players.",
    summary: "Pluribus, described in a 2019 Science paper by Noam Brown and Tuomas Sandholm, beat groups of professional poker players at six-player no-limit Texas hold'em across 10,000 hands, a substantially harder problem than the earlier two-player result (Libratus) because game-theoretic guarantees for Nash equilibria largely break down with more than two players. It was reportedly trained using under $150 of cloud computing resources, far less than prior game-playing AI milestones.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Combined self-play using a variant of counterfactual regret minimization with fast, depth-limited real-time search during play, using a simplified abstraction of the game rather than exact equilibrium computation.",
    source: { title: "Brown & Sandholm, 'Superhuman AI for multiplayer poker', Science", url: "https://www.science.org/doi/10.1126/science.aay2400", date: "2019-07-11", location: "Carnegie Mellon University / Facebook AI Research, USA" },
  },
  {
    registryNumber: "LR-OPENAI-FIVE-DOTA2", slug: "openai-five-dota2-champions", title: "OpenAI Five defeats reigning Dota 2 world champions",
    category: "AI", subcategory: "Game Playing", direction: "MAXIMIZE",
    metricName: "First AI to defeat a reigning esports world champion team in a complex real-time team game", unit: "boolean (achieved/not achieved)",
    formalStatement: "OpenAI Five, a team of five cooperating neural network agents, defeated OG, the reigning Dota 2 world champions, 2 games to 0 in a showcase match at OpenAI's Finals event in April 2019.",
    summary: "OpenAI Five was trained to play Dota 2, a real-time multiplayer team game with a much larger action space and longer time horizons than board games like chess or Go, using large-scale reinforcement learning. In April 2019 it defeated OG, who had just won the 2018 International (Dota 2's world championship), demonstrating that deep reinforcement learning could handle long-horizon, high-dimensional, partially observed, cooperative multi-agent tasks at a professional human level.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Large-scale proximal policy optimization (PPO) reinforcement learning, with each of five agents controlled by an LSTM-based policy network, trained via self-play across roughly 45,000 years of simulated game experience.",
    source: { title: "OpenAI — OpenAI Five defeats Dota 2 world champions", url: "https://openai.com/index/openai-five-defeats-dota-2-world-champions/", date: "2019-04-13", location: "OpenAI, San Francisco, USA" },
  },
  {
    registryNumber: "LR-ALPHASTAR-GRANDMASTER", slug: "alphastar-starcraft-grandmaster", title: "AlphaStar reaches Grandmaster rank in StarCraft II",
    category: "AI", subcategory: "Game Playing", direction: "MAXIMIZE",
    metricName: "First AI to reach the top competitive rank (Grandmaster) in a popular esport, across multiple in-game factions, without game-specific restrictions", unit: "boolean (achieved/not achieved)",
    formalStatement: "DeepMind's AlphaStar reached Grandmaster level on the official Battle.net ladder for StarCraft II, ranking above 99.8% of officially ranked human players, using all three playable races and without any restrictions on its camera view or action rate beyond human-comparable limits.",
    summary: "DeepMind reported in an October 2019 Nature paper that AlphaStar achieved Grandmaster status — the highest league on the official StarCraft II ladder — playing under conditions designed to match human constraints (a limited camera view of the game rather than full map access, and an action-per-minute rate capped to be comparable to skilled human players). StarCraft II presented harder challenges than earlier game AI milestones because of its long time horizons, imperfect information, and enormous action space.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "A deep neural network combining transformer and LSTM components, trained via a mix of supervised learning on human replays and multi-agent reinforcement learning in a league of continually competing AlphaStar variants ('AlphaStar League').",
    source: { title: "Vinyals et al., 'Grandmaster level in StarCraft II using multi-agent reinforcement learning', Nature", url: "https://www.nature.com/articles/s41586-019-1724-z", date: "2019-10-30", location: "Google DeepMind, London, UK" },
  },
  {
    registryNumber: "LR-GPT3-PARAMETER-COUNT", slug: "gpt3-largest-language-model-2020", title: "GPT-3 — largest publicly documented language model of its time",
    category: "AI", subcategory: "Language Models", direction: "MAXIMIZE",
    metricName: "Parameter count of a publicly documented dense transformer language model, at time of release", unit: "billion parameters",
    formalStatement: "OpenAI's GPT-3, described in a May 2020 paper, was released as a 175-billion-parameter dense transformer language model, more than 10x larger than the next largest publicly documented dense language model at the time (Microsoft's Turing-NLG, 17 billion parameters).",
    summary: "GPT-3's 175-billion-parameter scale, detailed in OpenAI's 'Language Models are Few-Shot Learners' paper, was the largest publicly documented dense language model at its May 2020 release, requiring an estimated 3.14x10^23 floating-point operations to train. It demonstrated strong 'few-shot' task performance from prompting alone, without task-specific fine-tuning, and its scale is widely credited with popularizing the empirical scaling-laws approach to language model development.",
    value: "175", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Trained a decoder-only transformer architecture on a large filtered web-text corpus using next-token prediction, with model and data scale substantially larger than prior public language models.",
    source: { title: "Brown et al., 'Language Models are Few-Shot Learners', NeurIPS 2020", url: "https://arxiv.org/abs/2005.14165", date: "2020-05-28", location: "OpenAI, San Francisco, USA" },
  },
  {
    registryNumber: "LR-ALPHAFOLD2-CASP14", slug: "alphafold2-casp14-protein-folding", title: "AlphaFold2 effectively solves the protein structure prediction problem at CASP14",
    category: "AI", subcategory: "Scientific Machine Learning", direction: "MAXIMIZE",
    metricName: "Median Global Distance Test (GDT_TS) score on the CASP14 blind protein structure prediction benchmark", unit: "GDT_TS score (0-100)",
    formalStatement: "DeepMind's AlphaFold2 achieved a median GDT_TS score of 92.4 across the CASP14 (Critical Assessment of protein Structure Prediction) benchmark targets in 2020, within the margin of error of experimentally determined structures, on a problem that had resisted computational solution for roughly 50 years.",
    summary: "AlphaFold2's results at the biennial, independently organized CASP14 competition in late 2020 were widely described by structural biologists as effectively solving the decades-old protein structure prediction problem for the majority of protein targets, achieving atomic-level accuracy competitive with experimental methods like X-ray crystallography for most cases. DeepMind and EMBL-EBI subsequently released predicted structures for nearly all catalogued proteins known to science via the AlphaFold Protein Structure Database.",
    value: "92.4", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "A deep neural network (the 'Evoformer') jointly reasoning over multiple sequence alignments and pairwise residue relationships, trained end-to-end to predict 3D atomic coordinates, evaluated via blind prediction on CASP14's independently sequestered target proteins.",
    source: { title: "CASP14 results and DeepMind, 'AlphaFold: a solution to a 50-year-old grand challenge in biology'", url: "https://deepmind.google/discover/blog/alphafold-a-solution-to-a-50-year-old-grand-challenge-in-biology/", date: "2020-11-30", location: "Google DeepMind, London, UK" },
  },
  {
    registryNumber: "LR-SWITCH-TRANSFORMER-PARAMETERS", slug: "switch-transformer-trillion-parameters", title: "Switch Transformer — first publicly documented trillion-parameter model",
    category: "AI", subcategory: "Language Models", direction: "MAXIMIZE",
    metricName: "Parameter count of a publicly documented sparse mixture-of-experts language model, at time of release", unit: "billion parameters",
    formalStatement: "Google's Switch Transformer, described in a January 2021 paper, scaled a sparsely activated mixture-of-experts transformer to 1.6 trillion parameters, the first publicly documented language model to cross the trillion-parameter mark, while keeping the computational cost per input comparable to much smaller dense models.",
    summary: "The Switch Transformer, developed by William Fedus, Barret Zoph, and Noam Shazeer at Google, used a simplified mixture-of-experts routing scheme (each input token activated only one, rather than several, expert sub-networks) to reach 1.6 trillion total parameters while each individual token's forward pass used only a fraction of that capacity. It demonstrated large gains in pre-training speed over dense models of comparable computational cost.",
    value: "1600", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Sparse mixture-of-experts transformer architecture with simplified top-1 token routing to one of many expert feed-forward sub-networks per layer, trained on the Colossal Clean Crawled Corpus (C4).",
    source: { title: "Fedus, Zoph & Shazeer, 'Switch Transformers: Scaling to Trillion Parameter Models with Simple and Efficient Sparsity'", url: "https://arxiv.org/abs/2101.03961", date: "2021-01-11", location: "Google Brain, USA" },
  },
  {
    registryNumber: "LR-CEREBRAS-WAFER-SCALE-ENGINE", slug: "cerebras-wafer-scale-engine-2", title: "Cerebras WSE-2 — largest computer chip ever manufactured",
    category: "AI", subcategory: "AI Hardware", direction: "MAXIMIZE",
    metricName: "Transistor count of a single manufactured computer chip built for AI compute", unit: "trillion transistors",
    formalStatement: "Cerebras Systems' Wafer-Scale Engine 2 (WSE-2), announced in April 2021, is manufactured from an entire 300mm silicon wafer as a single chip containing 2.6 trillion transistors and 850,000 AI-optimized cores, the largest computer chip ever manufactured by transistor count and physical die area.",
    summary: "Rather than cutting a silicon wafer into many individual chips as is standard practice, Cerebras Systems manufactures its Wafer-Scale Engine chips from a single, essentially uncut 300mm wafer, avoiding the interconnect bottlenecks of chip-to-chip communication for large AI workloads. The WSE-2 has roughly 2.55x the transistor count of its 2019 predecessor (the WSE-1, 1.2 trillion transistors) and, as of its release, was by a wide margin the largest chip ever built for any purpose.",
    value: "2.6", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Manufactured using TSMC's 7nm process on an entire silicon wafer, using specialized cross-die interconnect and redundancy techniques to work around the manufacturing defects that normally limit chip size.",
    source: { title: "Cerebras Systems — Wafer-Scale Engine 2 announcement", url: "https://www.cerebras.net/product-chip/", date: "2021-04-20", location: "Cerebras Systems, Sunnyvale, California, USA" },
  },
  {
    registryNumber: "LR-ALPHACODE-CODEFORCES", slug: "alphacode-competitive-programming", title: "AlphaCode reaches median human level on competitive programming contests",
    category: "AI", subcategory: "Code Generation", direction: "MAXIMIZE",
    metricName: "Estimated percentile ranking among human participants on real Codeforces competitive programming contests", unit: "percentile",
    formalStatement: "DeepMind's AlphaCode, evaluated on 10 real recent Codeforces contests under the same rules as human contestants, achieved an estimated average ranking within the top 54.3% of participants, roughly the level of a median competitive programmer.",
    summary: "AlphaCode, described in a February 2022 Science paper, generated solutions to competitive programming problems requiring understanding natural-language problem statements and producing working code that satisfies hidden test cases, a task requiring reasoning well beyond simple code completion. It was evaluated under contest-realistic conditions on real, previously unseen Codeforces problems rather than static benchmark datasets, and it placed at approximately the level of the median human contestant.",
    value: "54.3", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "A large transformer-based code generation model that sampled up to millions of candidate solutions per problem, then filtered and clustered them using the contest's own visible example test cases before submitting a small number of final candidates.",
    source: { title: "Li et al., 'Competition-Level Code Generation with AlphaCode', Science", url: "https://www.science.org/doi/10.1126/science.abq1158", date: "2022-02-08", location: "Google DeepMind, London, UK" },
  },
  {
    registryNumber: "LR-PALM-TRAINING-COMPUTE", slug: "palm-540b-training-compute", title: "PaLM — largest publicly documented dense model training compute of its era",
    category: "AI", subcategory: "Language Models", direction: "MAXIMIZE",
    metricName: "Parameter count of a publicly documented dense transformer language model, at time of release", unit: "billion parameters",
    formalStatement: "Google's Pathways Language Model (PaLM), announced in April 2022, was a 540-billion-parameter dense transformer trained across two TPU v4 Pods, among the largest dense (non-mixture-of-experts) language models publicly documented at the time, and reported state-of-the-art results on the majority of the roughly 150 language benchmark tasks it was evaluated on.",
    summary: "PaLM was notable both for its dense (as opposed to sparse mixture-of-experts) 540-billion-parameter scale and for demonstrating that Google's Pathways system could efficiently train a single model across two TPU v4 Pods (over 6,000 chips) with high hardware utilization. Google reported PaLM showed 'breakthrough' performance on tasks requiring multi-step reasoning when combined with chain-of-thought prompting, exceeding average human performance on the BIG-bench suite as reported in its technical paper.",
    value: "540", claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Dense decoder-only transformer trained via the Pathways distributed training system across two TPU v4 Pods, using a mixture of filtered web, book, code, and multilingual text data.",
    source: { title: "Chowdhery et al., 'PaLM: Scaling Language Modeling with Pathways'", url: "https://arxiv.org/abs/2204.02311", date: "2022-04-04", location: "Google Research, USA" },
  },
  {
    registryNumber: "LR-GPT4-BAR-EXAM", slug: "gpt4-uniform-bar-exam", title: "GPT-4 scores near the top decile on a simulated bar exam",
    category: "AI", subcategory: "Language Models", direction: "MAXIMIZE",
    metricName: "Estimated percentile rank among human test-takers on a simulated Uniform Bar Examination", unit: "percentile",
    formalStatement: "OpenAI reported in its March 2023 GPT-4 Technical Report that GPT-4 scored around the 90th percentile of human test-takers on a simulated Uniform Bar Examination, compared to GPT-3.5's reported score around the 10th percentile on the same test.",
    summary: "OpenAI's GPT-4 Technical Report presented results across a battery of professional and academic exams, most notably a simulated Uniform Bar Exam on which GPT-4 was reported to score near the 90th percentile of human test-takers. The specific percentile figure was later scrutinized and partially disputed by outside researchers who argued the true percentile depended heavily on the reference population used for comparison, so this figure should be read as OpenAI's self-reported result rather than an independently adjudicated one.",
    value: "90", claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Evaluated GPT-4 zero-shot or few-shot on a released simulated Uniform Bar Exam, with the resulting raw score mapped to a percentile using published human test-taker score distributions.",
    source: { title: "OpenAI, 'GPT-4 Technical Report'", url: "https://arxiv.org/abs/2303.08774", date: "2023-03-14", location: "OpenAI, San Francisco, USA" },
  },
  {
    registryNumber: "LR-ALPHAPROOF-IMO-2024", slug: "alphaproof-imo-2024-silver-medal", title: "AlphaProof and AlphaGeometry 2 reach silver-medal standard at the International Mathematical Olympiad",
    category: "AI", subcategory: "Mathematical Reasoning", direction: "MAXIMIZE",
    metricName: "Points scored on the 2024 International Mathematical Olympiad under official competition scoring", unit: "points (out of 42)",
    formalStatement: "Google DeepMind's AlphaProof and AlphaGeometry 2 systems together solved 4 of the 6 problems from the 2024 International Mathematical Olympiad, scoring 28 out of 42 possible points — one point short of the gold-medal threshold and equal to a silver-medal score — with solutions graded by official IMO methodology and reviewed by Fields medalist Timothy Gowers and IMO problem coordinator Joseph Myers.",
    summary: "Announced by DeepMind in July 2024, this was the first time an AI system had reached medal-level performance on the IMO, historically considered one of the most prestigious tests of mathematical problem-solving talent for pre-university students. AlphaProof, which formalizes and searches for proofs in the Lean proof assistant using reinforcement learning, solved two algebra problems and a number theory problem (including the hardest problem of the competition, solved by only a handful of the human contestants), while AlphaGeometry 2 solved the geometry problem in 19 seconds. Neither system solved either combinatorics problem.",
    value: "28", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "AlphaProof combined a large language model with reinforcement learning to generate and formally verify proof steps within the Lean theorem prover, training on millions of auto-formalized problems; AlphaGeometry 2 combined a language model with a symbolic geometry deduction engine.",
    source: { title: "Google DeepMind — AI achieves silver-medal standard solving International Mathematical Olympiad problems", url: "https://deepmind.google/discover/blog/ai-solves-imo-problems-at-silver-medal-level/", date: "2024-07-25", location: "Google DeepMind, London, UK" },
  },
  {
    registryNumber: "LR-MLPERF-GPT3-TRAINING-RECORD", slug: "mlperf-gpt3-training-speed-record", title: "Fastest GPT-3 (175B) training time on the MLPerf Training benchmark",
    category: "AI", subcategory: "Training Efficiency", direction: "MINIMIZE",
    metricName: "Wall-clock time to train a GPT-3 (175B parameter)-scale model to the MLPerf reference validation loss", unit: "minutes",
    formalStatement: "NVIDIA's 'Eos' supercomputer, using 3,584 H100 GPUs, trained a GPT-3 (175-billion-parameter)-scale reference model to the target validation loss in 10.9 minutes on the MLPerf Training v3.0 benchmark, when the GPT-3 task was introduced to the suite in June 2023, the fastest submitted result at the time.",
    summary: "MLPerf Training, run by the independent, industry-wide MLCommons consortium, is the standard benchmark for comparing large-scale AI training hardware and software under audited, reproducible conditions. NVIDIA's result on the newly introduced GPT-3 175B-scale training task in the June 2023 (v3.0) round used nearly the full capacity of its Eos DGX SuperPOD system, demonstrating the growing role of purpose-built AI supercomputers in large language model training; results in this specific task category have continued to improve in later MLPerf rounds.",
    value: "10.9", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Distributed data- and model-parallel training of a GPT-3-scale transformer across 3,584 NVIDIA H100 GPUs interconnected via NVLink and InfiniBand, measured to an MLCommons-defined validation loss target and audited under MLPerf's submission rules.",
    source: { title: "NVIDIA Developer Blog — Breaking MLPerf Training Records with NVIDIA H100 GPUs", url: "https://developer.nvidia.com/blog/breaking-mlperf-training-records-with-nvidia-h100-gpus/", date: "2023-06-27", location: "NVIDIA, Santa Clara, California, USA" },
  },

  // ================= ENERGY =================
  {
    registryNumber: "LR-THREE-GORGES-CAPACITY", slug: "three-gorges-dam-capacity", title: "Three Gorges Dam — largest hydroelectric power station by installed capacity",
    category: "Energy", subcategory: "Hydroelectric Power", direction: "MAXIMIZE",
    metricName: "Total installed electrical generating capacity of a single hydroelectric power station", unit: "MW",
    formalStatement: "The Three Gorges Dam on the Yangtze River, China, has a total installed generating capacity of 22,500 MW across 34 turbine-generator units, the largest installed capacity of any power station of any kind in the world.",
    summary: "Completed in stages between 2003 and 2012 (with the final generating units added in 2012 and an additional underground plant), the Three Gorges Dam is the world's largest power station by installed capacity, roughly 36% larger than the second-place Baihetan Dam. It is also the world's largest concrete structure and displaced an estimated 1.3 million people during construction.",
    value: "22500", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Verified against China Three Gorges Corporation's published technical specifications and cross-referenced international power station capacity listings.",
    source: { title: "China Three Gorges Corporation — Three Gorges Project overview", url: "https://en.ctg.com.cn/sbtjs/tgpp/", date: "2012-07-04", location: "Yichang, Hubei Province, China" },
  },
  {
    registryNumber: "LR-ANNUAL-HYDRO-GENERATION-RECORD", slug: "highest-annual-electricity-generation-single-plant", title: "Highest annual electricity generation by a single power station",
    category: "Energy", subcategory: "Hydroelectric Power", direction: "MAXIMIZE",
    metricName: "Total electricity generated by a single power station in one calendar year", unit: "TWh",
    formalStatement: "The Three Gorges Dam generated approximately 111.8 TWh of electricity in 2020, the highest annual output ever recorded by a single power station, surpassing the previous record of 103.1 TWh set by the Itaipu Dam (Brazil/Paraguay) in 2016.",
    summary: "Because annual electricity output depends on river flow and reservoir management as much as on installed capacity, the record for a single year's generation has swapped between Itaipu and Three Gorges: Itaipu, with more consistent year-round river flow despite lower nameplate capacity, held the record from 2016 (103.1 TWh) until unusually heavy Yangtze basin monsoon rains in 2020 pushed Three Gorges's output to roughly 111.8 TWh, an amount comparable to the annual electricity consumption of a mid-sized country.",
    value: "111.8", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Compiled from official annual generation figures reported by China Three Gorges Corporation and Itaipu Binacional, both of which publicly report yearly output totals.",
    source: { title: "China Three Gorges Corporation — 2020 annual generation record announcement", url: "https://en.ctg.com.cn/", date: "2021-01-01", location: "Yichang, Hubei Province, China" },
  },
  {
    registryNumber: "LR-THE-GEYSERS-GEOTHERMAL", slug: "the-geysers-largest-geothermal-field", title: "The Geysers — largest geothermal power complex in the world",
    category: "Energy", subcategory: "Geothermal Power", direction: "MAXIMIZE",
    metricName: "Total installed nameplate generating capacity of a single geothermal field's power plants", unit: "MW",
    formalStatement: "The Geysers geothermal field in the Mayacamas Mountains of Northern California hosts 18 currently operating geothermal power plants with a combined nameplate capacity of approximately 1,517 MW, the largest concentration of geothermal generating capacity in the world, per Guinness World Records.",
    summary: "The Geysers has been in commercial operation since 1960, making it also one of the longest continuously operating geothermal developments anywhere. Actual net output (around 900 MW as of recent years) runs below nameplate capacity because of natural, gradual steam-pressure decline in the underlying reservoir, which operators partially offset by injecting treated wastewater into the field to help sustain steam production.",
    value: "1517", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Verified against Guinness World Records' certified 'highest capacity geothermal power station' entry and field operator Calpine's published plant specifications.",
    source: { title: "Guinness World Records — Highest capacity geothermal power station", url: "https://www.guinnessworldrecords.com/world-records/most-powerful-geothermal-power-station", date: "2016-01-01", location: "Mayacamas Mountains, Sonoma/Lake Counties, California, USA" },
  },
  {
    registryNumber: "LR-SIHWA-TIDAL-POWER", slug: "sihwa-lake-tidal-power-station", title: "Sihwa Lake Tidal Power Station — largest tidal power station in the world",
    category: "Energy", subcategory: "Tidal Power", direction: "MAXIMIZE",
    metricName: "Installed generating capacity of a single tidal barrage power station", unit: "MW",
    formalStatement: "The Sihwa Lake Tidal Power Station in South Korea, completed in 2011, has an installed capacity of 254 MW across 10 turbines, making it the largest tidal power station in the world by generating capacity.",
    summary: "Sihwa was built into an existing seawall originally constructed for flood control and agricultural reclamation, repurposing tidal flows moving in and out of the artificial lake to generate power while also helping flush and improve the lake's water quality, which had degraded after the seawall cut it off from the sea. It generates roughly 552 GWh annually.",
    value: "254", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Uses bulb-type turbines installed within an existing tidal barrage/seawall structure, generating electricity as tidal flow passes through the turbines during the incoming tide.",
    source: { title: "K-water — Sihwa Tidal Power Plant", url: "https://english.kwater.or.kr/", date: "2011-08-01", location: "Ansan, Gyeonggi Province, South Korea" },
  },
  {
    registryNumber: "LR-RANCE-TIDAL-FIRST", slug: "rance-tidal-power-station-first", title: "Rance Tidal Power Station — world's first tidal power station",
    category: "Energy", subcategory: "Tidal Power", direction: "MAXIMIZE",
    metricName: "First utility-scale tidal barrage power station to enter commercial operation", unit: "boolean (achieved/not achieved)",
    formalStatement: "The Rance Tidal Power Station on the Rance estuary in Brittany, France, began commercial operation in 1966 with a capacity of 240 MW, becoming the world's first tidal power station and, for 45 years, the largest by capacity until South Korea's Sihwa station surpassed it in 2011.",
    summary: "Commissioned by Électricité de France, the Rance station exploits a tidal range in the Rance estuary of up to about 8 meters, among the largest in the world, using 24 bulb turbines that can generate power on both the incoming and outgoing tide. It remains in operation today, 60 years after opening, and is often cited as a benchmark for the long operating lifespan achievable by tidal infrastructure.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "A barrage across the Rance estuary housing bidirectional bulb turbines that generate electricity from tidal water flow in both directions, verified against EDF's plant operating records.",
    source: { title: "EDF — La Rance Tidal Power Station", url: "https://www.edf.fr/en/the-edf-group/dedicated-sections/production-and-innovation/renewable-energies/marine-power/tidal-power/the-rance-tidal-power-station", date: "1966-11-26", location: "Rance estuary, Brittany, France" },
  },
  {
    registryNumber: "LR-FENGNING-PUMPED-STORAGE", slug: "fengning-pumped-storage-largest", title: "Fengning Pumped Storage Power Station — largest pumped-storage hydroelectric facility",
    category: "Energy", subcategory: "Pumped-Storage Hydropower", direction: "MAXIMIZE",
    metricName: "Total installed capacity of a single pumped-storage hydroelectric facility", unit: "MW",
    formalStatement: "The Fengning Pumped Storage Power Station in Hebei Province, China, reached its full installed capacity of 3,600 MW across 12 units in August 2024, making it the largest pumped-storage hydroelectric power station in the world, surpassing Virginia's Bath County Pumped Storage Station (3,003 MW), the previous record holder.",
    summary: "Pumped-storage hydropower remains the world's dominant form of grid-scale energy storage by total capacity. Fengning stores roughly 40 GWh of energy by pumping water uphill to a reservoir during periods of surplus (often wind and solar) generation and releasing it through turbines during demand peaks, with construction proceeding in phases from 2021 through full commissioning in 2024.",
    value: "3600", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Verified against State Grid Corporation of China's commissioning announcements and the International Hydropower Association's project reporting.",
    source: { title: "International Hydropower Association — China's Fengning Station: World's Largest Pumped Hydro Power Plant Sets New Global Benchmark", url: "https://www.hydropower.org/news/chinas-fengning-station-worlds-largest-pumped-hydro-power-plant-sets-new-global-benchmark", date: "2024-08-01", location: "Fengning Manchu Autonomous County, Hebei Province, China" },
  },
  {
    registryNumber: "LR-ISLAY-LIMPET-WAVE-POWER", slug: "islay-limpet-first-commercial-wave-power", title: "Islay LIMPET — first commercial grid-connected wave power station",
    category: "Energy", subcategory: "Wave Power", direction: "MAXIMIZE",
    metricName: "First wave energy converter to sell electricity commercially to a national grid", unit: "boolean (achieved/not achieved)",
    formalStatement: "The Land Installed Marine Powered Energy Transformer (LIMPET) on the Isle of Islay, Scotland, began commercial operation in 2000 with a capacity of 500 kW, becoming the world's first commercial wave power station connected to a national electricity grid.",
    summary: "Developed by Wavegen (later part of Voith Hydro), LIMPET used an Oscillating Water Column design built into the shoreline: waves force air in and out of a chamber, driving a Wells turbine that spins regardless of airflow direction. Though modest in capacity, LIMPET demonstrated that wave energy conversion could be commercially grid-connected rather than remaining purely experimental, and it operated for over a decade before being decommissioned.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "An Oscillating Water Column (OWC) device built into a shoreline gully, using incoming and outgoing wave motion to alternately compress and decompress air through a self-rectifying Wells turbine.",
    source: { title: "European Marine Energy Centre — LIMPET Wave Energy Device", url: "https://www.emec.org.uk/about-us/wave-clients/limpet/", date: "2000-11-01", location: "Isle of Islay, Scotland, UK" },
  },
  {
    registryNumber: "LR-JINPING-DAM-HEIGHT", slug: "jinping-i-dam-tallest", title: "Jinping-I Dam — tallest dam in the world",
    category: "Energy", subcategory: "Hydroelectric Power", direction: "MAXIMIZE",
    metricName: "Structural height of a single dam", unit: "meters",
    formalStatement: "The Jinping-I Dam on the Yalong River in Sichuan, China, completed in 2014, stands 305 meters tall, making it the tallest dam of any type in the world.",
    summary: "Jinping-I is a double-curvature concrete arch dam built in a narrow, deep gorge, chosen specifically because such sites allow arch dams to transfer enormous hydrostatic loads into the surrounding rock. Its associated hydropower station has an installed capacity of 3,600 MW; the dam also created a reservoir requiring the resettlement of tens of thousands of people.",
    value: "305", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Verified against published Chinese hydropower engineering literature and the International Commission on Large Dams' (ICOLD) world register of dams.",
    source: { title: "International Commission on Large Dams (ICOLD) — World Register of Dams", url: "https://www.icold-cigb.org/", date: "2014-08-01", location: "Yalong River, Sichuan Province, China" },
  },
  {
    registryNumber: "LR-TUOKETUO-COAL-PLANT", slug: "tuoketuo-largest-coal-power-plant", title: "Tuoketuo Power Station — largest coal-fired power plant in the world",
    category: "Energy", subcategory: "Fossil Fuel Power", direction: "MAXIMIZE",
    metricName: "Total installed generating capacity of a single coal-fired power station", unit: "MW",
    formalStatement: "The Tuoketuo Power Station in Inner Mongolia, China, has a total installed capacity of 6,720 MW across a series of 600 MW generating units commissioned in phases, making it the largest coal-fired power station in the world by installed capacity.",
    summary: "Operated by China Datang Corporation, Tuoketuo was built out in six phases from 1995 through the early 2010s, ultimately generating roughly 33 TWh of electricity annually. It remains a striking illustration of the scale gap between the largest fossil-fuel plants and the largest hydro or nuclear plants, which run several times larger still.",
    value: "6720", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Verified against published plant specifications from China Datang Corporation and cross-referenced international power station capacity listings.",
    source: { title: "Global Energy Monitor — Togtoh (Tuoketuo) power station", url: "https://www.gem.wiki/Togtoh_power_station", date: "2011-01-01", location: "Togtoh County, Hohhot, Inner Mongolia, China" },
  },
  {
    registryNumber: "LR-SURGUT-2-GAS-PLANT", slug: "surgut-2-largest-gas-power-plant", title: "Surgut-2 Power Station — largest natural-gas-fired power plant in the world",
    category: "Energy", subcategory: "Fossil Fuel Power", direction: "MAXIMIZE",
    metricName: "Total installed generating capacity of a single natural-gas-fired power station", unit: "MW",
    formalStatement: "The Surgutskaya GRES-2 (Surgut-2) power station in western Siberia, Russia, has a certified installed capacity of 5,657.1 MW, the highest of any natural-gas-fired power station in the world, per Guinness World Records.",
    summary: "Located on the Ob River near the city of Surgut, the plant burns a mix of associated petroleum gas (a byproduct of regional oil production, roughly 70% of its fuel) and natural gas (roughly 30%), consuming approximately 10 billion cubic meters of gas annually. Its scale reflects the concentration of Siberian oil and gas extraction infrastructure in the surrounding Khanty-Mansi region.",
    value: "5657.1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Verified against Guinness World Records' certified 'highest capacity natural gas power station' entry.",
    source: { title: "Guinness World Records — Highest capacity natural gas power station", url: "https://www.guinnessworldrecords.com/world-records/106606-largest-natural-gas-power-station", date: "2016-01-01", location: "Surgut, Khanty-Mansi Autonomous Okrug, Russia" },
  },
  {
    registryNumber: "LR-VIKING-LINK-INTERCONNECTOR", slug: "viking-link-longest-interconnector", title: "Viking Link — world's longest land-and-subsea electricity interconnector",
    category: "Energy", subcategory: "Grid Transmission", direction: "MAXIMIZE",
    metricName: "Total length of a single high-voltage direct current (HVDC) electricity interconnector cable", unit: "km",
    formalStatement: "Viking Link, a 1,400 MW HVDC interconnector between Denmark and the United Kingdom that entered commercial operation in December 2023, runs 765 km in total length (approximately 650 km of which is subsea), making it the longest land-and-subsea electricity interconnector in the world, surpassing the previous record held by the Norway-UK North Sea Link (720 km, commissioned 2021).",
    summary: "Built jointly by Denmark's Energinet and Britain's National Grid, Viking Link lets the two countries' grids trade surplus renewable generation (particularly Danish wind power) across the North Sea. The record for longest interconnector has shifted repeatedly in recent years as European grid operators have built a series of increasingly long HVDC subsea links to help balance renewable generation across the continent, so the current record is likely to be surpassed again as newer, longer interconnectors are completed.",
    value: "765", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Verified against the joint project specifications published by transmission system operators Energinet (Denmark) and National Grid Electricity Transmission (UK).",
    source: { title: "National Grid — Viking Link project overview", url: "https://www.nationalgrid.com/electricity-transmission/network-and-infrastructure/viking-link", date: "2023-12-29", location: "Denmark-United Kingdom North Sea interconnector" },
  },
  {
    registryNumber: "LR-HORNSDALE-POWER-RESERVE", slug: "hornsdale-power-reserve-frequency-response", title: "Hornsdale Power Reserve demonstrates grid-scale battery frequency response",
    category: "Energy", subcategory: "Grid-Scale Battery Storage", direction: "MINIMIZE",
    metricName: "Response time of a grid-scale lithium-ion battery installation providing frequency control ancillary services", unit: "milliseconds",
    formalStatement: "The Hornsdale Power Reserve in South Australia, a 100 MW / 129 MWh lithium-ion battery installation built by Tesla and commissioned in December 2017, was among the first grid-scale batteries to demonstrate sub-second (sub-200-millisecond) automated response to grid frequency deviations at commercial scale, and was built within 100 days per a public commitment made by Elon Musk.",
    summary: "Commissioned in response to a series of South Australian blackouts and grid-stability issues in 2016-2017, Hornsdale demonstrated that lithium-ion batteries could respond to frequency disturbances roughly 100 times faster than conventional gas 'peaker' plants, prompting Australia's electricity market operator to create new, faster-responding ancillary service categories. Its early commercial success helped catalyze a wave of grid-scale battery investment worldwide; the facility has since been expanded well beyond its original 100 MW capacity.",
    value: "150", claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Tesla Powerpack lithium-ion battery units paired with grid-frequency-sensing control software that automatically dispatches stored energy within milliseconds of detecting a frequency deviation, verified through Australian Energy Market Operator (AEMO) performance reporting.",
    source: { title: "Australian Energy Market Operator — Hornsdale Power Reserve performance reports", url: "https://aemo.com.au/", date: "2018-01-01", location: "Jamestown, South Australia, Australia" },
  },
  {
    registryNumber: "LR-SINOPEC-KUQA-GREEN-HYDROGEN", slug: "sinopec-kuqa-largest-green-hydrogen", title: "Sinopec Kuqa — largest operating green hydrogen production plant",
    category: "Energy", subcategory: "Hydrogen Production", direction: "MAXIMIZE",
    metricName: "Designed annual production capacity of a solar-powered electrolytic (green) hydrogen production facility", unit: "tonnes/year",
    formalStatement: "Sinopec's Kuqa green hydrogen project in Xinjiang, China, entered production in 2023 with a designed annual capacity of 20,000 tonnes of hydrogen produced via water electrolysis powered by roughly 300 MW of dedicated solar generation and 260 MW of electrolyzer capacity, making it the largest green hydrogen production facility in operation at the time.",
    summary: "The Kuqa plant supplies hydrogen to a nearby Sinopec oil refinery, displacing hydrogen that would otherwise be produced from natural gas or coal (a carbon-intensive process) and demonstrating green hydrogen's use in decarbonizing existing industrial demand rather than only new applications. Sinopec has reported the facility took longer than initially planned to ramp toward its full rated capacity, illustrating the operational challenges of matching intermittent solar output to continuous industrial hydrogen demand.",
    value: "20000", claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Proton-exchange-membrane and alkaline water electrolyzers powered by a co-located photovoltaic solar array, verified against Sinopec's public project announcements and independent industry reporting (Wood Mackenzie).",
    source: { title: "Sinopec — Xinjiang Kuqa Green Hydrogen Pilot Project enters operation", url: "https://www.prnewswire.com/news-releases/sinopec-xinjiang-kuqa-green-hydrogen-pilot-project-enters-operation-leading-chinas-green-hydrogen-development-301868802.html", date: "2023-06-30", location: "Kuqa, Xinjiang, China" },
  },
  {
    registryNumber: "LR-HYWIND-FLOATING-WIND", slug: "hywind-scotland-first-floating-wind-farm", title: "Hywind Scotland — world's first floating offshore wind farm",
    category: "Energy", subcategory: "Offshore Wind Power", direction: "MAXIMIZE",
    metricName: "First multi-turbine floating offshore wind farm to enter commercial operation", unit: "boolean (achieved/not achieved)",
    formalStatement: "Hywind Scotland, developed by Equinor off the coast of Peterhead, Scotland, began commercial operation in October 2017 with five 6 MW turbines (30 MW total) mounted on floating spar-buoy foundations, becoming the world's first commercially operating floating offshore wind farm.",
    summary: "Unlike conventional offshore wind turbines, which are fixed to the seabed and limited to shallow waters, Hywind's turbines float on ballasted structures anchored by mooring lines, allowing deployment in much deeper water where wind resources are often stronger and more consistent. The project demonstrated floating wind's commercial viability and achieved an average capacity factor exceeding 50% in its first years of operation, well above typical fixed-bottom offshore wind performance at the time.",
    value: "1", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Spar-buoy floating foundations, each ballasted with water and rock and secured to the seabed by three-point mooring systems, supporting standard offshore wind turbine nacelles and towers.",
    source: { title: "Equinor — Hywind Scotland: the world's first floating wind farm", url: "https://www.equinor.com/energy/hywind-scotland", date: "2017-10-18", location: "Peterhead, Aberdeenshire, Scotland, UK" },
  },
  {
    registryNumber: "LR-JIUQUAN-WIND-BASE", slug: "jiuquan-gansu-largest-wind-farm", title: "Jiuquan (Gansu) Wind Power Base — largest wind farm complex in the world",
    category: "Energy", subcategory: "Onshore Wind Power", direction: "MAXIMIZE",
    metricName: "Combined installed capacity of a single, geographically concentrated onshore wind farm complex", unit: "MW",
    formalStatement: "The Jiuquan Wind Power Base in Gansu Province, China, also known as the Gansu Wind Farm, had exceeded roughly 8,000 MW of installed capacity from over 7,000 turbines as of the mid-2020s, en route to a long-term planned buildout of 20,000 MW, making it the largest single wind farm complex in the world by both installed and planned capacity.",
    summary: "Located on the edge of the Gobi Desert, the Jiuquan base was designated one of China's seven major 'wind power bases' and required construction of a dedicated 2,383 km ultra-high-voltage transmission line to carry its output to demand centers in central and eastern China. Because the complex has been built out in successive large phases since 2009, reported installed-capacity figures vary somewhat by source and year; the planned 20,000 MW full buildout has not yet been fully completed.",
    value: "8000", claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Aggregated installed capacity across a large number of individually developed wind farm projects sited within the same designated Gansu wind resource zone, verified against Guinness World Records' 'highest capacity wind farm' entry and industry trade press.",
    source: { title: "Guinness World Records — Highest capacity wind farm", url: "https://www.guinnessworldrecords.com/world-records/highest-capacity-wind-farm", date: "2020-01-01", location: "Jiuquan, Gansu Province, China" },
  },
  {
    registryNumber: "LR-BHADLA-SOLAR-PARK", slug: "bhadla-solar-park-largest-at-completion", title: "Bhadla Solar Park — world's largest solar park at time of completion",
    category: "Energy", subcategory: "Solar Power", direction: "MAXIMIZE",
    metricName: "Installed capacity of a single, geographically concentrated utility-scale solar photovoltaic park", unit: "MW",
    formalStatement: "Bhadla Solar Park in Rajasthan, India, reached a total commissioned capacity of 2,245 MW in March 2020, at which point it was the largest solar park in the world by capacity; subsequent solar park developments elsewhere, particularly in China, have since surpassed it.",
    summary: "Spread across roughly 5,700 hectares of the Thar Desert, Bhadla combines several separately developed solar plants under a shared grid connection and land-allocation framework managed by the Rajasthan state government, a model since replicated for other large Indian solar parks. This entry records Bhadla's status as the largest solar park in the world specifically at its March 2020 completion — by 2024 it ranked outside the global top ten as multiple larger Chinese solar parks came online, illustrating how quickly utility-scale solar capacity records turn over.",
    value: "2245", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Aggregated commissioned capacity across multiple co-located solar plant developers within the Bhadla Solar Park zone, verified against Rajasthan state renewable energy agency figures and industry trade press (Mercom India).",
    source: { title: "Mercom India — With 2,245 MW of Commissioned Solar Projects, World's Largest Solar Park is Now at Bhadla", url: "https://www.mercomindia.com/world-largest-solar-park-bhadla", date: "2020-03-20", location: "Bhadla, Phalodi district, Rajasthan, India" },
  },
  {
    registryNumber: "LR-GRAND-COULEE-DAM", slug: "grand-coulee-dam-largest-north-america", title: "Grand Coulee Dam — largest power station in North America",
    category: "Energy", subcategory: "Hydroelectric Power", direction: "MAXIMIZE",
    metricName: "Total installed generating capacity of a single hydroelectric power station in North America", unit: "MW",
    formalStatement: "The Grand Coulee Dam on the Columbia River in Washington State, USA, has a total installed generating capacity of 6,809 MW, making it the largest power station of any kind in North America and the largest concrete structure built in the United States.",
    summary: "Completed in its original form in 1942 and substantially expanded with a third powerhouse in 1974, Grand Coulee was central to the mid-20th-century industrialization of the U.S. Pacific Northwest, providing power for wartime aluminum production and, later, large-scale irrigation of the Columbia Basin. It remains operated by the U.S. Bureau of Reclamation and is one of the largest hydroelectric facilities outside China and South America.",
    value: "6809", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Verified against the U.S. Bureau of Reclamation's published technical specifications for the Grand Coulee Power Office.",
    source: { title: "U.S. Bureau of Reclamation — Grand Coulee Dam", url: "https://www.usbr.gov/pn/grandcoulee/", date: "1975-01-01", location: "Grant/Okanogan Counties, Washington, USA" },
  },
  {
    registryNumber: "LR-BAIHETAN-HYDRO-TURBINES", slug: "baihetan-largest-hydro-turbine-units", title: "Baihetan Dam — largest single hydroelectric turbine-generator units in the world",
    category: "Energy", subcategory: "Hydroelectric Power", direction: "MAXIMIZE",
    metricName: "Rated capacity of a single hydroelectric turbine-generator unit", unit: "MW",
    formalStatement: "The Baihetan hydropower station on the Jinsha River, China, uses 16 Francis turbine-generator units each rated at 1,000 MW, the largest-capacity single hydroelectric turbine-generator units ever built, becoming fully operational in December 2022 with a combined station capacity of 16,000 MW (second only to the Three Gorges Dam).",
    summary: "Each Baihetan turbine unit weighs over 7,500 tonnes and stands roughly 50 meters tall, converting a reported 96.7% of the kinetic energy of falling water into electricity, among the highest efficiencies achieved at this scale. The distinction between Baihetan and Three Gorges is worth noting: Three Gorges holds the record for total station capacity using 32 smaller (700-777 MW) units, while Baihetan holds the record for the largest capacity of any single turbine-generator unit.",
    value: "1000", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Verified against China Three Gorges Corporation and International Hydropower Association technical reporting on Baihetan's turbine specifications.",
    source: { title: "International Hydropower Association — The world's largest turbine produces renewable energy", url: "https://www.hydropower.org/case-study/worlds-largest-turbine", date: "2022-12-20", location: "Jinsha River, Sichuan/Yunnan border, China" },
  },
  {
    registryNumber: "LR-DALIAN-FLOW-BATTERY", slug: "dalian-flow-battery-largest", title: "Dalian Flow Battery Energy Storage Station — largest vanadium redox flow battery in the world",
    category: "Energy", subcategory: "Grid-Scale Battery Storage", direction: "MAXIMIZE",
    metricName: "Installed power capacity of a single vanadium redox flow battery grid storage facility", unit: "MW",
    formalStatement: "The Dalian Flow Battery Energy Storage Peak-shaving Power Station in Liaoning Province, China, connected its first 100 MW / 400 MWh phase to the grid in September 2022, becoming the world's largest vanadium redox flow battery energy storage facility, with a planned second phase to expand total capacity to 200 MW / 800 MWh.",
    summary: "Developed using flow battery technology from the Dalian Institute of Chemical Physics (Chinese Academy of Sciences) and built by Rongke Power, the facility stores energy in liquid vanadium electrolyte tanks rather than solid electrodes, a chemistry that trades lower energy density for a very long cycle life (typically over 20,000 cycles) and negligible degradation compared to lithium-ion batteries — an advantage for the kind of daily grid peak-shaving and renewable-smoothing role this plant performs.",
    value: "100", claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Vanadium redox flow battery technology in which energy is stored chemically in external liquid electrolyte tanks and converted via electrochemical stacks, verified against Dalian Rongke Power's project announcements and independent industry press (PV Magazine, Energy-Storage.News).",
    source: { title: "PV Magazine — China connects world's largest redox flow battery system to grid", url: "https://www.pv-magazine.com/2022/09/29/china-connects-worlds-largest-redox-flow-battery-system-to-grid/", date: "2022-09-29", location: "Dalian, Liaoning Province, China" },
  },
];
