import type { FrontierRecord } from "./frontier-records-2026";

// Third real-world-records batch — geography/climate extremes, astrophysics, engineering,
// medicine, and two more new categories ("Sports Records" and "Food & Culture") for records that
// don't fit any existing science category. Every value checked against the single most
// authoritative body for that record (WMO, Guinness World Records, NASA, TOP500, a national
// survey/geological body, or the original peer-reviewed study) as of 2026-09-20. Two disputed
// topics are handled with an explicit caveat rather than a false single number: the Nile/Amazon
// "longest river" question (genuinely contested depending on measurement methodology) and the
// fastest tennis serve (Guinness's overall fastest vs. the ATP's own stricter tour record).
export const WORLD_RECORDS_BATCH3: FrontierRecord[] = [
  // --- Earth & Climate ---
  {
    registryNumber: "LR-COLDEST-TEMPERATURE", slug: "coldest-temperature-recorded", title: "Coldest temperature ever recorded on Earth",
    category: "Earth & Climate", subcategory: "Extreme Weather", direction: "MINIMIZE",
    metricName: "Lowest directly measured near-surface air temperature", unit: "°C",
    formalStatement: "The lowest air temperature ever directly measured at Earth's surface, as recognized by the World Meteorological Organization.",
    summary: "A temperature of -89.2°C (-128.6°F) was recorded at Russia's Vostok Station, Antarctica, on July 21, 1983 — still the WMO's official record for the coldest directly measured air temperature. Satellite data has since detected even colder skin temperatures (as low as -98°C) on the East Antarctic Plateau, but these are not officially recognized because the exact height above ground they represent is difficult to determine.",
    value: "-89.2",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Ground-based thermometer reading at a staffed research station, certified by the WMO Committee on Weather and Climate Extremes.",
    source: { title: "Lowest temperature recorded on Earth — Guinness World Records", url: "https://www.guinnessworldrecords.com/world-records/66137-lowest-temperature-recorded-on-earth", date: "1983-07-21", location: "Vostok Station, Antarctica" },
  },
  {
    registryNumber: "LR-EVEREST-HEIGHT", slug: "mount-everest-height", title: "Height of the highest point on Earth",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Elevation above sea level of Mount Everest's summit", unit: "m",
    formalStatement: "The elevation above mean sea level of the highest point on Earth's surface, Mount Everest's summit, per the official joint China–Nepal survey.",
    summary: "China and Nepal jointly announced a new official elevation of 8,848.86 meters (29,031.7 ft) for Mount Everest's summit in December 2020, based on a fresh survey using GPS and gravity measurements — resolving a small long-standing discrepancy between the two countries' earlier independent figures (8,848m and 8,844.43m).",
    value: "8848.86",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Joint China–Nepal survey using GPS and gravity-based measurements of snow height above the underlying rock.",
    source: { title: "China, Nepal announce new height of Mount Qomolangma/Everest", url: "https://www.icimod.org/article/china-nepal-announce-new-height-of-mount-qomolangma-mount-everest/", date: "2020-12-08", location: "Mount Everest/Qomolangma, Nepal–China border" },
  },
  {
    registryNumber: "LR-LONGEST-RIVER", slug: "longest-river-in-the-world", title: "Longest river in the world",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Total length of the longest river system", unit: "km",
    formalStatement: "The greatest length of any river system on Earth, measured from its most distant headwater source to its mouth.",
    summary: "The Nile (~6,650 km) is the traditionally cited longest river and remains the answer most textbooks and atlases give. However, several studies since 2007 — using satellite tracking to identify the Amazon's most distant source and including certain contested tributary channels — argue the Amazon is actually longer, with estimates ranging from about 6,992 to 7,062 km. There is no single internationally agreed measurement standard for 'source' or 'mouth' on either river, so the ranking genuinely depends on methodology rather than a settled fact.",
    value: "6650",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Traditional Nile figure per standard geographic atlases; competing Amazon-longer studies use satellite-tracked headwater identification, a genuinely disputed methodology.",
    source: { title: "Encyclopaedia Britannica — Nile River", url: "https://www.britannica.com/place/Nile-River", date: "2007-01-01", location: "Nile River basin, Africa" },
  },
  {
    registryNumber: "LR-DEEPEST-CAVE", slug: "deepest-cave-in-the-world", title: "Deepest cave in the world",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Total explored vertical depth of a cave system", unit: "m",
    formalStatement: "The greatest explored vertical depth of any cave system on Earth, from its highest entrance to its lowest explored point.",
    summary: "Veryovkina Cave in the Arabika Massif, Abkhazia, was explored to a depth of 2,212 meters by a Russian speleological team (Perovo Speleo Club) in March 2018 — the deepest cave ever explored, narrowly surpassing the neighboring Krubera-Voronja Cave (2,197 m), which had held the record since 2004.",
    value: "2212",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Direct speleological survey and depth measurement by the exploring team, corroborated by the Ukrainian Speleological Association.",
    source: { title: "Ukrainian Speleological Association — Veryovkina Cave", url: "https://www.caves.org.ua/", date: "2018-03-01", location: "Arabika Massif, Abkhazia" },
  },
  {
    registryNumber: "LR-LARGEST-HOT-DESERT", slug: "largest-hot-desert", title: "Largest hot desert",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Total area of the largest subtropical hot desert", unit: "km²",
    formalStatement: "The greatest total area of any hot (subtropical) desert on Earth. Scoped specifically to hot deserts — Antarctica and the Arctic are technically larger 'cold deserts' by precipitation-based definitions, but are excluded from this comparison as a distinct climate category.",
    summary: "The Sahara Desert covers approximately 9.2 million km² across North Africa — roughly the size of the United States or China — making it by far the largest hot desert on Earth.",
    value: "9200000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Standard geographic area measurement via satellite imagery and national survey data, as compiled by National Geographic and similar atlases.",
    source: { title: "National Geographic — Sahara", url: "https://education.nationalgeographic.org/resource/sahara/", date: "2022-01-01", location: "North Africa" },
  },
  {
    registryNumber: "LR-LARGEST-RAINFOREST", slug: "largest-rainforest", title: "Largest rainforest",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Total area of the largest tropical rainforest", unit: "km²",
    formalStatement: "The greatest total area of any contiguous tropical rainforest on Earth.",
    summary: "The Amazon rainforest spans approximately 5.5 million km² across nine South American countries — more than the next two largest rainforests (the Congo Basin and Southeast Asia's combined) put together — making it the largest tropical rainforest on Earth.",
    value: "5500000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Satellite-based land-cover mapping, as compiled by the World Wildlife Fund and national forestry surveys of the Amazon basin countries.",
    source: { title: "WWF — Amazon", url: "https://www.worldwildlife.org/places/amazon", date: "2022-01-01", location: "Amazon Basin, South America" },
  },
  {
    registryNumber: "LR-LONGEST-MOUNTAIN-RANGE", slug: "longest-mountain-range", title: "Longest mountain range",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Total length of the longest continuous mountain range", unit: "km",
    formalStatement: "The greatest length of any continuous mountain range on Earth, including underwater ranges.",
    summary: "The Mid-Ocean Ridge, an underwater volcanic mountain range running through every ocean basin, stretches approximately 65,000 km — over nine times the length of the Andes (~7,000 km), the longest range above water. Most of it lies 1.5–3 km beneath the ocean surface and was fully mapped only in the mid-20th century, which is why the Andes is still the popular answer to 'longest mountain range' despite being far shorter overall.",
    value: "65000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Bathymetric survey mapping compiled by the National Oceanic and Atmospheric Administration (NOAA) and international oceanographic institutions.",
    source: { title: "NOAA Ocean Exploration — Mid-Ocean Ridge", url: "https://oceanexplorer.noaa.gov/facts/mid-ocean-ridge.html", date: "2013-01-01", location: "Global ocean basins" },
  },
  {
    registryNumber: "LR-LARGEST-LAKE-AREA", slug: "largest-lake-by-area", title: "Largest lake by surface area",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Surface area of the largest inland body of water", unit: "km²",
    formalStatement: "The greatest surface area of any inland body of water classified as a lake, whether freshwater or saline.",
    summary: "The Caspian Sea, a landlocked saltwater lake bordered by five countries, covers approximately 371,000 km² — larger than Germany — making it the largest lake on Earth by a wide margin over Lake Superior (~82,100 km²), the largest freshwater lake by area.",
    value: "371000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Satellite-based surface area measurement, compiled by national hydrographic surveys of the bordering countries.",
    source: { title: "Encyclopaedia Britannica — Caspian Sea", url: "https://www.britannica.com/place/Caspian-Sea", date: "2022-01-01", location: "Central Asia / Eastern Europe border" },
  },
  {
    registryNumber: "LR-DEEPEST-LAKE", slug: "deepest-lake", title: "Deepest lake",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Maximum depth of the deepest lake", unit: "m",
    formalStatement: "The greatest depth measured in any lake on Earth.",
    summary: "Lake Baikal in Siberia reaches a maximum depth of 1,642 meters — deeper than any other lake — and holds roughly 23,600 km³ of water, about 20% of all unfrozen fresh surface water on Earth, despite covering only the eighth-largest surface area of any lake.",
    value: "1642",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Bathymetric sonar survey, conducted by Russian and international limnological research institutes.",
    source: { title: "UNESCO World Heritage — Lake Baikal", url: "https://whc.unesco.org/en/list/754/", date: "1996-01-01", location: "Irkutsk Oblast and Buryatia, Russia" },
  },
  {
    registryNumber: "LR-LARGEST-IMPACT-CRATER", slug: "largest-impact-crater", title: "Largest confirmed impact crater on Earth",
    category: "Earth & Climate", subcategory: "Geology", direction: "MAXIMIZE",
    metricName: "Diameter of the largest confirmed terrestrial impact structure", unit: "km",
    formalStatement: "The greatest diameter of any confirmed asteroid or comet impact structure on Earth's surface.",
    summary: "The Vredefort crater in South Africa, formed by an asteroid impact roughly 2.02 billion years ago, has an estimated original diameter of about 300 km — the largest confirmed impact structure on Earth, though heavy erosion over two billion years means only its heavily weathered central dome is visible today.",
    value: "300",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Geological field mapping and shock-metamorphism analysis of the crater's remaining structure, per peer-reviewed geological literature.",
    source: { title: "UNESCO World Heritage — Vredefort Dome", url: "https://whc.unesco.org/en/list/1162/", date: "2005-07-14", location: "Free State province, South Africa" },
  },
  {
    registryNumber: "LR-LARGEST-HAILSTONE", slug: "largest-hailstone", title: "Largest hailstone ever recorded",
    category: "Earth & Climate", subcategory: "Extreme Weather", direction: "MAXIMIZE",
    metricName: "Diameter of the largest confirmed hailstone", unit: "cm",
    formalStatement: "The greatest diameter of any hailstone confirmed by official meteorological measurement.",
    summary: "A hailstone measuring 20.3 cm (8 inches) in diameter and weighing 0.88 kg (1.94 lb) fell in Vivian, South Dakota, USA, on July 23, 2010 — the largest hailstone diameter ever officially confirmed in the United States, verified by the National Weather Service.",
    value: "20.3",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Physical measurement of the preserved hailstone, verified by the U.S. National Weather Service.",
    source: { title: "NOAA — Record Hailstone", url: "https://www.weather.gov/abr/vivian", date: "2010-07-23", location: "Vivian, South Dakota, USA" },
  },
  {
    registryNumber: "LR-MOST-RAINFALL-24H", slug: "most-rainfall-in-24-hours", title: "Most rainfall in 24 hours",
    category: "Earth & Climate", subcategory: "Extreme Weather", direction: "MAXIMIZE",
    metricName: "Greatest rainfall total recorded in a single 24-hour period", unit: "mm",
    formalStatement: "The greatest total rainfall recorded at a single location within any consecutive 24-hour period, as certified by the World Meteorological Organization.",
    summary: "Foc-Foc, on the island of La Réunion in the Indian Ocean, recorded 1,825 mm (71.8 in) of rainfall in 24 hours during Tropical Cyclone Denise on January 7–8, 1966 — the WMO's official world record, driven by the island's steep volcanic terrain forcing extreme orographic rainfall.",
    value: "1825",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Rain gauge measurement, certified by the WMO Committee on Weather and Climate Extremes.",
    source: { title: "WMO World Weather & Climate Extremes Archive", url: "https://wmo.asu.edu/content/world-greatest-24-hour-precipitation", date: "1966-01-08", location: "Foc-Foc, Réunion" },
  },
  {
    registryNumber: "LR-TALLEST-WATERFALL", slug: "tallest-waterfall", title: "Tallest waterfall",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Total uninterrupted drop height of the tallest waterfall", unit: "m",
    formalStatement: "The greatest total height of uninterrupted drop of any waterfall on Earth.",
    summary: "Angel Falls in Venezuela drops 979 meters (3,212 ft), with a longest single free-fall section of 807 meters — by far the tallest waterfall in the world, roughly 15 times the height of Niagara Falls. It was 'discovered' internationally in 1933 by American aviator Jimmie Angel, though it had long been known to the indigenous Pemón people as Kerepakupai Merú.",
    value: "979",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Topographic survey measurement, per Venezuelan national park authority (Inparques) records.",
    source: { title: "Encyclopaedia Britannica — Angel Falls", url: "https://www.britannica.com/place/Angel-Falls", date: "1949-01-01", location: "Canaima National Park, Venezuela" },
  },
  {
    registryNumber: "LR-LARGEST-WATERFALL-FLOW", slug: "largest-waterfall-by-flow-rate", title: "Largest waterfall by average flow rate",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Average volumetric flow rate of the largest waterfall by discharge", unit: "m³/s",
    formalStatement: "The greatest average water discharge rate of any waterfall on Earth — a different metric from height, since the world's tallest waterfall (Angel Falls) is not the highest-volume one.",
    summary: "Boyoma Falls (formerly Stanley Falls), a series of cataracts on the Congo River in the Democratic Republic of the Congo, has an average flow rate of approximately 17,000 m³/s — the highest average discharge of any waterfall on Earth, roughly 7 times the average flow of Niagara Falls.",
    value: "17000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Hydrological discharge measurement on the Congo River, per national and international river-basin survey data.",
    source: { title: "Encyclopaedia Britannica — Boyoma Falls", url: "https://www.britannica.com/place/Boyoma-Falls", date: "2020-01-01", location: "Democratic Republic of the Congo" },
  },
  {
    registryNumber: "LR-LARGEST-VOLCANO", slug: "largest-volcano", title: "Largest known volcano",
    category: "Earth & Climate", subcategory: "Geology", direction: "MAXIMIZE",
    metricName: "Footprint area of the largest known single volcano", unit: "km²",
    formalStatement: "The greatest footprint area of any single volcano confirmed on Earth (or, at the time of its 2013 confirmation, anywhere in the Solar System).",
    summary: "Tamu Massif, an extinct shield volcano roughly 1,600 km east of Japan on the floor of the Pacific Ocean, covers approximately 310,000 km² — about the size of New Mexico or the British Isles. It was confirmed as a single volcano (rather than a cluster of several) by an International Ocean Discovery Program drilling and seismic study published in 2013.",
    value: "310000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Seismic reflection survey and rock-core drilling by the Integrated Ocean Drilling Program, published in a peer-reviewed study.",
    source: { title: "Sager et al., \"An immense shield volcano within the Shatsky Rise oceanic plateau,\" Nature Geoscience (2013)", url: "https://www.nature.com/articles/ngeo1934", date: "2013-09-05", location: "Shatsky Rise, northwest Pacific Ocean" },
  },
  {
    registryNumber: "LR-TAMBORA-ERUPTION", slug: "most-powerful-volcanic-eruption-recorded", title: "Most powerful volcanic eruption in recorded history",
    category: "Earth & Climate", subcategory: "Geology", direction: "MAXIMIZE",
    metricName: "Volcanic Explosivity Index (VEI) of the largest eruption in recorded human history", unit: "VEI",
    formalStatement: "The highest Volcanic Explosivity Index confirmed for any volcanic eruption during recorded human history.",
    summary: "The 1815 eruption of Mount Tambora, Indonesia, reached VEI 7 (\"super-colossal\"), ejecting an estimated 150 km³ of material and killing an estimated 71,000–100,000 people directly and through subsequent famine. Its stratospheric ash caused 1816 to become known as the 'Year Without a Summer' across the Northern Hemisphere, with widespread crop failures in Europe and North America.",
    value: "7",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Volcanic Explosivity Index rating based on ejected volume and eruption column height, per the Smithsonian Institution's Global Volcanism Program.",
    source: { title: "Smithsonian Institution Global Volcanism Program — Tambora", url: "https://volcano.si.edu/volcano.cfm?vn=264020", date: "1815-04-10", location: "Sumbawa Island, Indonesia" },
  },

  // --- Astrophysics ---
  {
    registryNumber: "LR-VOYAGER-1-DISTANCE", slug: "farthest-human-made-object", title: "Farthest human-made object from Earth",
    category: "Astrophysics", subcategory: "Space Exploration", direction: "MAXIMIZE",
    metricName: "Distance from Earth of the farthest-traveled human-made object", unit: "AU",
    formalStatement: "The greatest distance from Earth reached by any human-made object, as continuously tracked by NASA's Deep Space Network. This value increases daily — Voyager 1 remains active and continues moving outward at roughly 3.6 AU per year.",
    summary: "NASA's Voyager 1 probe, launched September 5, 1977, is the most distant human-made object ever, at approximately 171 AU (about 25.6 billion km) from Earth as of August 2026 and still transmitting data from interstellar space, which it entered in 2012. Its twin, Voyager 2, remains the second-farthest, having taken a different trajectory.",
    value: "171",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Continuously tracked via radio signal round-trip timing by NASA's Deep Space Network.",
    source: { title: "NASA Science — Where Are Voyager 1 and 2 Now?", url: "https://science.nasa.gov/mission/voyager/where-are-voyager-1-and-voyager-2-now/", date: "2026-08-01", location: "Interstellar space, beyond the heliosphere" },
  },
  {
    registryNumber: "LR-HIGHEST-ENERGY-COSMIC-RAY", slug: "highest-energy-cosmic-ray", title: "Highest-energy cosmic ray ever detected",
    category: "Astrophysics", subcategory: "Particle Astrophysics", direction: "MAXIMIZE",
    metricName: "Energy of the highest-energy cosmic ray particle ever detected", unit: "EeV",
    formalStatement: "The greatest energy ever measured for a single cosmic ray particle detected reaching Earth.",
    summary: "The 'Oh-My-God particle,' detected by the Fly's Eye telescope array in Dugway, Utah on October 15, 1991, carried an estimated 320 exa-electron-volts (EeV) of energy — millions of times more than particles reach at the Large Hadron Collider, packed into a single subatomic particle. Its exact source remains unidentified; it remains the highest-energy cosmic ray ever recorded, ahead of the 2021 'Amaterasu particle' (244 EeV).",
    value: "320",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Air-fluorescence detection technique, measuring faint light from nitrogen molecules excited by the particle's atmospheric shower.",
    source: { title: "University of Utah — The Oh-My-God Particle", url: "https://www.science.org/content/article/oh-my-god-its-real-particle", date: "1991-10-15", location: "Fly's Eye Observatory, Dugway Proving Ground, Utah, USA" },
  },
  {
    registryNumber: "LR-CLOSEST-STAR", slug: "closest-star-to-the-sun", title: "Closest star to the Sun",
    category: "Astrophysics", subcategory: "Stellar Astronomy", direction: "MINIMIZE",
    metricName: "Distance from the Sun to the nearest known star", unit: "ly",
    formalStatement: "The distance from the Sun to the nearest confirmed star other than the Sun itself.",
    summary: "Proxima Centauri, a red dwarf in the Alpha Centauri triple-star system, lies approximately 4.2465 light-years from the Sun — the closest known star. It hosts at least one confirmed exoplanet, Proxima Centauri b, discovered in 2016, orbiting within the star's habitable zone.",
    value: "4.2465",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Measured via stellar parallax, most precisely by the European Space Agency's Gaia astrometry mission.",
    source: { title: "ESA Gaia Data Release — Proxima Centauri", url: "https://www.cosmos.esa.int/web/gaia", date: "2018-04-25", location: "Alpha Centauri system" },
  },
  {
    registryNumber: "LR-AGE-OF-UNIVERSE", slug: "age-of-the-universe", title: "Age of the universe",
    category: "Astrophysics", subcategory: "Cosmology", direction: "MAXIMIZE",
    metricName: "Estimated age of the universe since the Big Bang", unit: "Gyr",
    formalStatement: "The best current estimate of the time elapsed since the Big Bang, per the standard cosmological (Lambda-CDM) model fit to cosmic microwave background data.",
    summary: "The Planck space telescope's final full-mission analysis of the cosmic microwave background, published in 2018, estimates the universe's age at 13.787 ± 0.020 billion years — the most precise estimate to date, consistent with (and complementary to) the independent lower bound the Registry separately tracks from the ages of the oldest known stars.",
    value: "13.787",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Cosmic microwave background power spectrum fit to the standard Lambda-CDM cosmological model, from the Planck satellite's final data release.",
    source: { title: "Planck Collaboration, \"Planck 2018 results. VI. Cosmological parameters\"", url: "https://arxiv.org/abs/1807.06209", date: "2018-07-17", location: "Planck space telescope, ESA" },
  },

  // --- Engineering ---
  {
    registryNumber: "LR-LONGEST-BRIDGE-OVERALL", slug: "longest-bridge-overall", title: "Longest bridge (total length)",
    category: "Engineering", subcategory: "Civil Engineering", direction: "MAXIMIZE",
    metricName: "Total length of the longest bridge structure", unit: "km",
    formalStatement: "The greatest total length of any bridge structure, including elevated viaduct approaches — a different metric from the longest single main span, which the Registry tracks separately.",
    summary: "The Danyang–Kunshan Grand Bridge, a viaduct carrying the Beijing–Shanghai High-Speed Railway through Jiangsu Province, China, stretches 164.8 km (102.4 miles) — the longest bridge in the world by total length since its completion in 2010, built by roughly 10,000 workers over four years.",
    value: "164.8",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Engineering specification from the bridge's constructor and operator, China Railway, corroborated by independent structural-engineering surveys.",
    source: { title: "Encyclopaedia Britannica — Danyang–Kunshan Grand Bridge", url: "https://www.britannica.com/topic/Danyang-Kunshan-Grand-Bridge", date: "2011-06-30", location: "Jiangsu Province, China" },
  },
  {
    registryNumber: "LR-FASTEST-SUPERCOMPUTER", slug: "fastest-supercomputer", title: "Fastest supercomputer",
    category: "Computing", subcategory: "High-Performance Computing", direction: "MAXIMIZE",
    metricName: "Sustained performance on the High Performance Linpack (HPL) benchmark", unit: "exaflop/s",
    formalStatement: "The highest sustained floating-point performance achieved by any supercomputer on the High Performance Linpack benchmark, per the twice-yearly TOP500 ranking.",
    summary: "LineShine, installed at the National Supercomputing Center in Shenzhen, China, achieved a sustained 2.198 exaflops on the HPL benchmark, topping the June 2026 TOP500 list and displacing the US Department of Energy's El Capitan (1.809 exaflops), which had held the top spot since November 2024.",
    value: "2.198",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "High Performance Linpack (HPL) benchmark result, independently ranked by the TOP500 project.",
    source: { title: "TOP500 — June 2026 List", url: "https://top500.org/", date: "2026-06-24", location: "National Supercomputing Center, Shenzhen, China" },
  },
  {
    registryNumber: "LR-DEEPEST-MINE", slug: "deepest-mine", title: "Deepest mine",
    category: "Engineering", subcategory: "Mining Engineering", direction: "MAXIMIZE",
    metricName: "Maximum depth below surface of a working mine", unit: "km",
    formalStatement: "The greatest depth below the surface reached by any operating mine.",
    summary: "Mponeng gold mine near Carletonville, South Africa, extends approximately 4 km below the surface, making it the deepest mine on Earth. Rock temperatures at the working face reach around 60°C, requiring extensive cooling infrastructure to make conditions survivable for miners.",
    value: "4",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Mine engineering survey data published by AngloGold Ashanti, the mine's operator.",
    source: { title: "AngloGold Ashanti — Mponeng Mine", url: "https://www.anglogoldashanti.com/", date: "2019-01-01", location: "Carletonville, Gauteng, South Africa" },
  },
  {
    registryNumber: "LR-TALLEST-FREESTANDING-STRUCTURE", slug: "tallest-freestanding-structure", title: "Tallest freestanding tower",
    category: "Engineering", subcategory: "Civil Engineering", direction: "MAXIMIZE",
    metricName: "Height of the tallest freestanding (non-habitable-building) structure", unit: "m",
    formalStatement: "The greatest height of any freestanding structure that is not classified as a habitable building — a category tracked separately from the tallest skyscraper, since a broadcasting/observation tower is engineered very differently from an occupied high-rise.",
    summary: "Tokyo Skytree, a broadcasting and observation tower completed in 2012, stands 634 meters tall — the tallest tower in the world, though shorter than the Burj Khalifa (828 m), which counts as a habitable building rather than a tower.",
    value: "634",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Structural engineering specification from the tower's operator, Tobu Tower Skytree Co.",
    source: { title: "Tokyo Skytree — Official Facts", url: "https://www.tokyo-skytree.jp/en/", date: "2012-05-22", location: "Sumida, Tokyo, Japan" },
  },
  {
    registryNumber: "LR-LONGEST-TUNNEL", slug: "longest-tunnel", title: "Longest tunnel",
    category: "Engineering", subcategory: "Civil Engineering", direction: "MAXIMIZE",
    metricName: "Length of the longest transportation tunnel", unit: "km",
    formalStatement: "The greatest length of any tunnel built for transportation (rail, road, or water conveyance).",
    summary: "The Gotthard Base Tunnel through the Swiss Alps, opened in 2016, runs 57.1 km — the longest railway tunnel and the longest transportation tunnel of any kind in the world, cutting the Zurich-to-Milan rail journey by roughly an hour.",
    value: "57.1",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Engineering specification from the tunnel's operator, AlpTransit Gotthard AG / Swiss Federal Railways.",
    source: { title: "Swiss Federal Railways — Gotthard Base Tunnel", url: "https://www.sbb.ch/en/travelcenter/tips-trends/gotthard/gotthard-base-tunnel.html", date: "2016-06-01", location: "Swiss Alps, Switzerland" },
  },
  {
    registryNumber: "LR-LARGEST-SHIP-EVER-BUILT", slug: "largest-ship-ever-built", title: "Largest ship ever built",
    category: "Engineering", subcategory: "Naval Engineering", direction: "MAXIMIZE",
    metricName: "Overall length of the longest ship ever built", unit: "m",
    formalStatement: "The greatest overall length of any ship ever constructed.",
    summary: "The supertanker Seawise Giant (later renamed Happy Giant, Jahre Viking, and Knock Nevis) measured 458.45 m (1,504 ft) in length when completed in 1979 — longer than the Empire State Building is tall — remaining the longest ship ever built even after being scrapped in 2010. It was too large to pass through the English Channel, the Suez Canal, or the Panama Canal.",
    value: "458.45",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Original shipyard construction specification (Sumitomo Heavy Industries), corroborated by maritime registry records.",
    source: { title: "Guinness World Records — Longest ship ever", url: "https://www.guinnessworldrecords.com/world-records/longest-ship", date: "1981-01-01", location: "Yokosuka, Japan (built); scrapped in Alang, India, 2010" },
  },

  // --- Medicine & Physiology ---
  {
    registryNumber: "LR-TALLEST-HUMAN-EVER", slug: "tallest-human-ever-recorded", title: "Tallest human ever recorded",
    category: "Medicine & Physiology", subcategory: "Human Anatomy", direction: "MAXIMIZE",
    metricName: "Height of the tallest medically verified human", unit: "cm",
    formalStatement: "The greatest height medically documented for a human being.",
    summary: "Robert Wadlow (USA, 1918–1940) reached a height of 272 cm (8 ft 11.1 in) before his death at age 22, caused by hyperplasia of his pituitary gland resulting in excess growth hormone. His height was medically measured and documented by physicians throughout his life, and remains the tallest verified human on record.",
    value: "272",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Direct medical measurement by treating physicians, documented in contemporary medical case records.",
    source: { title: "Guinness World Records — Tallest man ever", url: "https://www.guinnessworldrecords.com/world-records/tallest-man-ever", date: "1940-07-15", location: "Alton, Illinois, USA" },
  },
  {
    registryNumber: "LR-LONGEST-BREATH-HELD", slug: "longest-breath-held-voluntarily", title: "Longest breath held voluntarily",
    category: "Medicine & Physiology", subcategory: "Human Performance", direction: "MAXIMIZE",
    metricName: "Duration of voluntary static breath-hold (apnea)", unit: "min",
    formalStatement: "The longest duration a human has voluntarily held their breath underwater in a static position, under Guinness World Records-monitored conditions.",
    summary: "Budimir Šobat (Croatia) held his breath for 24 minutes 37 seconds in a pool in Zadar, Croatia, on March 27, 2021 — the longest voluntary breath-hold ever recorded. He first hyperventilated with pure oxygen (a Guinness-permitted technique for this category) before submerging.",
    value: "24.62",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Timed static apnea attempt under official Guinness World Records adjudication.",
    source: { title: "Guinness World Records — Longest time breath held voluntarily (male)", url: "https://www.guinnessworldrecords.com/world-records/60712-longest-time-breath-held-voluntarily-male", date: "2021-03-27", location: "Zadar, Croatia" },
  },
  {
    registryNumber: "LR-HIGHEST-BODY-TEMP-SURVIVED", slug: "highest-body-temperature-survived", title: "Highest human body temperature survived",
    category: "Medicine & Physiology", subcategory: "Human Anatomy", direction: "MAXIMIZE",
    metricName: "Highest recorded human body core temperature in a survived case", unit: "°C",
    formalStatement: "The highest human body core temperature ever medically recorded in a patient who survived.",
    summary: "Willie Jones (USA) was admitted to Grady Memorial Hospital, Atlanta, in July 1980 with heatstroke and a body temperature of 46.5°C (115.7°F) — the highest ever recorded in a surviving patient. He was discharged 24 days later, per the treating physicians' published case report.",
    value: "46.5",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Clinical thermometer measurement on hospital admission, documented in a published medical case report.",
    source: { title: "Guinness World Records — Highest body temperature survived", url: "https://www.guinnessworldrecords.com/world-records/highest-body-temperature", date: "1980-07-10", location: "Grady Memorial Hospital, Atlanta, Georgia, USA" },
  },

  // --- Sports Records (new category) ---
  {
    registryNumber: "LR-MOST-OLYMPIC-GOLDS", slug: "most-olympic-gold-medals", title: "Most Olympic gold medals, individual athlete",
    category: "Sports Records", subcategory: "Olympics", direction: "MAXIMIZE",
    metricName: "Career Olympic gold medals won by a single athlete", unit: "medals",
    formalStatement: "The greatest number of Olympic gold medals won across a career by a single athlete, per official International Olympic Committee records.",
    summary: "American swimmer Michael Phelps won 23 Olympic gold medals across five Olympic Games (2004–2016) — more than double the total of any other individual athlete in Olympic history — along with 3 silver and 2 bronze medals, for 28 total.",
    value: "23",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official medal-count records maintained by the International Olympic Committee.",
    source: { title: "Olympics.com — Michael Phelps", url: "https://www.olympics.com/en/athletes/michael-phelps-ii", date: "2016-08-21", location: "Multiple Olympic Games venues, 2004–2016" },
  },
  {
    registryNumber: "LR-HIGHEST-POLE-VAULT", slug: "highest-pole-vault", title: "Highest pole vault",
    category: "Sports Records", subcategory: "Athletics", direction: "MAXIMIZE",
    metricName: "Height cleared in a pole vault, record-eligible conditions", unit: "m",
    formalStatement: "The greatest height cleared in a pole vault under World Athletics record-eligible conditions.",
    summary: "Sweden's Armand 'Mondo' Duplantis cleared 6.31 m at the Mondo Classic in Uppsala, Sweden, on March 12, 2026 — the 15th time he has broken his own world record since first setting it in 2020, each time by exactly 1 centimeter.",
    value: "6.31",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Electronically measured vault height at a World Athletics-sanctioned meet, ratified as the official world record.",
    source: { title: "World Athletics — Duplantis breaks pole vault world record", url: "https://worldathletics.org/records/by-category/world-records", date: "2026-03-12", location: "Uppsala, Sweden" },
  },
  {
    registryNumber: "LR-FASTEST-TENNIS-SERVE", slug: "fastest-tennis-serve", title: "Fastest tennis serve ever recorded",
    category: "Sports Records", subcategory: "Tennis", direction: "MAXIMIZE",
    metricName: "Fastest recorded tennis serve speed", unit: "km/h",
    formalStatement: "The fastest tennis serve speed ever recorded by radar gun at a sanctioned tournament. Distinct from the ATP's own stricter tour-level record, which requires tournament-grade calibrated radar not used at every event.",
    summary: "Australia's Sam Groth served at 263.4 km/h (163.7 mph) at a Challenger-level tournament in Busan, South Korea, in May 2012 — the fastest tennis serve ever recorded. The ATP does not recognize it as the official tour record because Challenger-event radar guns are not calibrated to ATP tour standards; the ATP's own recognized record is John Isner's 253.0 km/h serve at the 2016 Davis Cup.",
    value: "263.4",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Radar gun measurement at a sanctioned tennis tournament; not ATP tour-calibrated, hence the parallel 'official' ATP figure.",
    source: { title: "Guinness World Records — Fastest tennis serve (male)", url: "https://www.guinnessworldrecords.com/world-records/fastest-tennis-serve-male", date: "2012-05-09", location: "Busan, South Korea" },
  },
  {
    registryNumber: "LR-HEAVIEST-DEADLIFT", slug: "heaviest-deadlift", title: "Heaviest deadlift",
    category: "Sports Records", subcategory: "Strength Sports", direction: "MAXIMIZE",
    metricName: "Heaviest weight deadlifted by a human", unit: "kg",
    formalStatement: "The greatest weight ever lifted by a human in a deadlift, under officially witnessed strongman competition conditions.",
    summary: "Iceland's Hafþór Júlíus Björnsson deadlifted 510 kg (1,124 lb) at the World Deadlift Championships in Birmingham, UK, on September 6, 2025 — the heaviest deadlift ever recorded, surpassing his own 505 kg lift from two months earlier and Eddie Hall's previous 500 kg record from 2016.",
    value: "510",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Officially witnessed and adjudicated lift at a sanctioned World Deadlift Championships event.",
    source: { title: "Guinness World Records — Heaviest deadlift (male)", url: "https://www.guinnessworldrecords.com/world-records/heaviest-deadlift", date: "2025-09-06", location: "Birmingham, United Kingdom" },
  },
  {
    registryNumber: "LR-LONGEST-GOLF-DRIVE", slug: "longest-golf-drive", title: "Longest golf drive",
    category: "Sports Records", subcategory: "Golf", direction: "MAXIMIZE",
    metricName: "Longest golf drive distance, officially measured", unit: "yd",
    formalStatement: "The greatest distance achieved by a golf drive under officially measured and witnessed conditions.",
    summary: "Mike Dobbyn (USA) hit a drive of 551 yards (503.8 m) at a long-drive competition in 2007 — the longest golf drive ever officially measured, aided by altitude and a favorable tailwind, conditions typical of the specialized long-drive competition format rather than standard tournament golf.",
    value: "551",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Officially measured and witnessed at a sanctioned long-drive competition.",
    source: { title: "Guinness World Records — Longest drive in golf", url: "https://www.guinnessworldrecords.com/world-records/longest-drive-in-golf", date: "2007-01-01", location: "United States" },
  },

  // --- Food & Culture (new category) ---
  {
    registryNumber: "LR-LARGEST-PIZZA", slug: "largest-pizza-ever-made", title: "Largest pizza ever made",
    category: "Food & Culture", subcategory: "Food Records", direction: "MAXIMIZE",
    metricName: "Surface area of the largest pizza ever made", unit: "m²",
    formalStatement: "The greatest surface area of any single pizza made, per Guinness World Records certification.",
    summary: "A gluten-free pizza named 'Ottavia,' made in Rome, Italy in December 2012, covered 1,261.65 m² — larger than three basketball courts — certified by Guinness World Records as the largest pizza ever made.",
    value: "1261.65",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Physical area measurement, certified by an on-site Guinness World Records adjudicator.",
    source: { title: "Guinness World Records — Largest pizza", url: "https://www.guinnessworldrecords.com/world-records/largest-pizza", date: "2012-12-11", location: "Rome, Italy" },
  },
  {
    registryNumber: "LR-SPICIEST-PEPPER", slug: "spiciest-chili-pepper", title: "Spiciest chili pepper",
    category: "Food & Culture", subcategory: "Food Records", direction: "MAXIMIZE",
    metricName: "Average Scoville Heat Units of the hottest cultivated chili pepper variety", unit: "SHU",
    formalStatement: "The highest average Scoville Heat Unit rating of any cultivated chili pepper variety, as certified by Guinness World Records.",
    summary: "The Carolina Reaper, bred by Ed Currie of the PuckerButt Pepper Company in South Carolina, USA, was certified by Guinness World Records in 2013 with an average rating of 1,641,183 Scoville Heat Units — more than 200 times hotter than a jalapeño — and remains the hottest pepper on record as of 2026.",
    value: "1641183",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "High-performance liquid chromatography (HPLC) testing at Winthrop University, South Carolina, certified by Guinness World Records.",
    source: { title: "Guinness World Records — Hottest chili pepper", url: "https://www.guinnessworldrecords.com/world-records/hottest-chili-pepper", date: "2013-08-07", location: "Fort Mill, South Carolina, USA" },
  },

  // --- Economics ---
  {
    registryNumber: "LR-LARGEST-LOTTERY-JACKPOT", slug: "largest-lottery-jackpot-won", title: "Largest lottery jackpot ever won",
    category: "Economics", subcategory: "Gaming", direction: "MAXIMIZE",
    metricName: "Largest single lottery jackpot ever paid out", unit: "USD",
    formalStatement: "The largest single lottery jackpot ever won and paid out, in nominal (not inflation-adjusted) US dollars.",
    summary: "A single Powerball ticket sold in California won a jackpot of $2.04 billion in the drawing held November 7, 2022 — the largest lottery jackpot ever won in a single drawing, still the record as of 2026. The winner, Edwin Castro, chose the lump-sum cash option of approximately $997.6 million before taxes.",
    value: "2040000000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official prize amount confirmed by the Multi-State Lottery Association and California Lottery.",
    source: { title: "California Lottery — Powerball jackpot history", url: "https://www.calottery.com/draw-games/powerball", date: "2022-11-07", location: "Altadena, California, USA" },
  },

  // --- Earth & Climate (geography, continued) ---
  {
    registryNumber: "LR-LARGEST-ISLAND", slug: "largest-island", title: "Largest island",
    category: "Earth & Climate", subcategory: "Geography", direction: "MAXIMIZE",
    metricName: "Land area of the largest island", unit: "km²",
    formalStatement: "The greatest land area of any landmass classified as an island rather than a continent — Australia (7.69 million km²) is excluded by standard geographic convention, which classifies it as a continent.",
    summary: "Greenland covers approximately 2.166 million km², over 80% of it permanently ice-covered — making it by far the largest island on Earth under the standard continent/island distinction, more than three times the size of the next-largest island, New Guinea (~786,000 km²).",
    value: "2166000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Standard geographic area measurement compiled by national and international geographic surveys.",
    source: { title: "Encyclopaedia Britannica — Greenland", url: "https://www.britannica.com/place/Greenland", date: "2022-01-01", location: "Arctic Ocean / North Atlantic" },
  },

  // --- Astrophysics, continued ---
  {
    registryNumber: "LR-BRIGHTEST-STAR-NIGHT-SKY", slug: "brightest-star-in-the-night-sky", title: "Brightest star in the night sky",
    category: "Astrophysics", subcategory: "Stellar Astronomy", direction: "MINIMIZE",
    metricName: "Apparent visual magnitude of the brightest star as seen from Earth (excluding the Sun)", unit: "mag",
    formalStatement: "The lowest (brightest) apparent visual magnitude of any star as seen from Earth, excluding the Sun. Apparent magnitude is an inverse-logarithmic scale — a lower or more negative number means a brighter object.",
    summary: "Sirius (Alpha Canis Majoris), a binary star system 8.6 light-years away, has an apparent magnitude of -1.46 — the brightest star in Earth's night sky, roughly twice as bright as the second-brightest, Canopus. Its brightness comes from a combination of its intrinsic luminosity and relative closeness to Earth, rather than being the most luminous star known.",
    value: "-1.46",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Photometric measurement of apparent visual magnitude, per standard astronomical catalogs.",
    source: { title: "Encyclopaedia Britannica — Sirius", url: "https://www.britannica.com/place/Sirius-star", date: "2022-01-01", location: "Canis Major constellation" },
  },
];
