import type { FrontierRecord } from "./frontier-records-2026";

// Tenth real-world-records batch (2026-10-05) — energy, speed, arts and culture. Extends the small
// "Energy", "Speed Records", "Arts & Entertainment" and "Food & Culture" categories with milestones
// in batteries, fuel cells, wind, solar, geothermal and nuclear power, oil and gas fields, grids and
// blackouts; vehicle, aircraft, watercraft, motorsport and human speed records; theatre, opera, music,
// film, radio, television, publishing and video games; and food, drink, festivals, languages and
// national symbols. Every topic was cross-checked against the full 2,894-record catalog (titles,
// slugs and summaries) before writing, and overlapping topics were skipped, e.g. oldest public museum
// (Ashmolean is already listed), most expensive film memorabilia (ruby slippers), first grid-connected
// nuclear plant (Obninsk), Concorde, X-15, oldest board game, largest reservoir and esports prize
// pools. Facts were checked against Wikipedia and primary sources. Topics with disputed or unverifiable
// current holders were dropped (most expensive comic book and video game, oldest pub, oldest chewing
// gum, largest phoneme inventory, country with the most official languages). Fast-moving or
// estimated figures are marked LITERATURE_ASSERTED and given with an explicit as-of date.
export const WORLD_RECORDS_BATCH10_ENERGY_CULTURE: FrontierRecord[] = [
  // --- Energy ---
  {
    registryNumber: "LR-FIRST-ELECTRIC-BATTERY-VOLTAIC-PILE", slug: "first-electric-battery-voltaic-pile", title: "First electric battery (voltaic pile)",
    category: "Energy", subcategory: "Energy History", direction: "MINIMIZE",
    metricName: "Year the first device producing a continuous electric current from chemical reactions was described", unit: "year",
    formalStatement: "The earliest year in which an electrochemical battery capable of supplying a steady electric current was built and described.",
    summary: "Alessandro Volta described his voltaic pile, a stack of alternating zinc and copper (or silver) discs separated by brine-soaked cloth or cardboard, in a letter to the Royal Society in London dated March 20, 1800. It was the first electric battery able to deliver a continuous current, and within weeks it was used to split water by electrolysis.",
    value: "1800",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Date of Volta's letter to Sir Joseph Banks, published in the Philosophical Transactions of the Royal Society in 1800.",
    source: { title: "Royal Society — Philosophical Transactions", url: "https://royalsocietypublishing.org/journal/rstl", date: "1800-03-20", location: "Como, Italy / London, England" },
  },
  {
    registryNumber: "LR-FIRST-RECHARGEABLE-BATTERY-LEAD-ACID", slug: "first-rechargeable-battery-lead-acid", title: "First rechargeable battery",
    category: "Energy", subcategory: "Energy History", direction: "MINIMIZE",
    metricName: "Year the first battery that could be recharged by reversing the current was invented", unit: "year",
    formalStatement: "The earliest year in which a secondary (rechargeable) electrochemical battery was invented.",
    summary: "French physicist Gaston Planté invented the lead-acid battery in 1859. It was the first battery that could be recharged by passing a reverse current through it, and lead-acid cells are still made in huge numbers today, mostly as starter batteries for cars.",
    value: "1859",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "History of the lead-acid cell as documented in the electrochemistry literature; Planté presented his cell to the French Academy of Sciences in 1860.",
    source: { title: "Battery Council International — lead battery history", url: "https://batterycouncil.org/", date: "1859-01-01", location: "Paris, France" },
  },
  {
    registryNumber: "LR-FIRST-FUEL-CELL", slug: "first-fuel-cell", title: "First fuel cell",
    category: "Energy", subcategory: "Energy History", direction: "MINIMIZE",
    metricName: "Year the first fuel cell (gas voltaic battery) was demonstrated", unit: "year",
    formalStatement: "The earliest year in which a device generating electricity by electrochemically combining hydrogen and oxygen was demonstrated.",
    summary: "Welsh scientist William Grove demonstrated the first fuel cell in 1838–1839, generating electricity by combining hydrogen and oxygen over platinum electrodes in dilute acid, and published his results in the Philosophical Magazine in 1839. He later called the device a 'gas voltaic battery'. Practical fuel cells came almost a century later with Francis Thomas Bacon's hydrogen–oxygen cell of 1932.",
    value: "1839",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Dating follows Grove's 1839 publication in the Philosophical Magazine; some histories date his first experiments to 1838.",
    source: { title: "Philosophical Magazine — Grove, 'On Voltaic Series and the Combination of Gases by Platinum'", url: "https://www.tandfonline.com/toc/tphm14/current", date: "1839-01-01", location: "London, England" },
  },
  {
    registryNumber: "LR-FIRST-COMMERCIAL-LITHIUM-ION-BATTERY", slug: "first-commercial-lithium-ion-battery", title: "First commercial lithium-ion battery",
    category: "Energy", subcategory: "Energy History", direction: "MINIMIZE",
    metricName: "Year lithium-ion batteries were first sold commercially", unit: "year",
    formalStatement: "The earliest year in which rechargeable lithium-ion cells went on commercial sale.",
    summary: "A Sony and Asahi Kasei team led by Yoshio Nishi commercialized the lithium-ion battery in 1991, based on Akira Yoshino's 1985 design using a carbon anode. In the three decades since, the volumetric energy density of lithium-ion cells has roughly tripled while costs have fallen about tenfold. Yoshino shared the 2019 Nobel Prize in Chemistry for the work.",
    value: "1991",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Commercial launch date recorded by Sony and the National Academy of Engineering.",
    source: { title: "Nobel Prize in Chemistry 2019 — Lithium-ion batteries", url: "https://www.nobelprize.org/prizes/chemistry/2019/summary/", date: "1991-01-01", location: "Japan" },
  },
  {
    registryNumber: "LR-FIRST-OFFSHORE-WIND-FARM", slug: "first-offshore-wind-farm", title: "First offshore wind farm",
    category: "Energy", subcategory: "Wind Power", direction: "MINIMIZE",
    metricName: "Year the first offshore wind farm began operating", unit: "year",
    formalStatement: "The earliest year in which a wind farm built at sea began supplying electricity.",
    summary: "Vindeby Offshore Wind Farm, about 2 km off the coast of Lolland in Denmark, began operating in 1991 with eleven 450 kW Bonus turbines (4.95 MW in total) in water about 4 m deep. It was the world's first offshore wind farm and ran until it was decommissioned in 2017.",
    value: "1991",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Commissioning history published by the operator (Ørsted, formerly DONG Energy).",
    source: { title: "Ørsted — Vindeby, the world's first offshore wind farm", url: "https://orsted.com/", date: "1991-01-01", location: "Lolland, Denmark" },
  },
  {
    registryNumber: "LR-FIRST-WIND-FARM", slug: "first-wind-farm", title: "First wind farm",
    category: "Energy", subcategory: "Wind Power", direction: "MINIMIZE",
    metricName: "Year the first multi-turbine wind farm was installed", unit: "year",
    formalStatement: "The earliest year in which a group of wind turbines was installed together as a wind farm to generate electricity.",
    summary: "The world's first wind farm was installed on the shoulder of Crotched Mountain in southern New Hampshire in December 1980. It had 20 turbines rated at 30 kW each, for a total capacity of 0.6 MW.",
    value: "1980",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Historical record of New England wind development compiled by the U.S. Department of Energy's Wind Powering America program.",
    source: { title: "U.S. Department of Energy — Wind Energy Technologies Office", url: "https://www.energy.gov/eere/wind/wind-energy-technologies-office", date: "1980-12-01", location: "Crotched Mountain, New Hampshire, USA" },
  },
  {
    registryNumber: "LR-FIRST-GEOTHERMAL-POWER-GENERATION", slug: "first-geothermal-power-generation", title: "First electricity generated from geothermal energy",
    category: "Energy", subcategory: "Geothermal", direction: "MINIMIZE",
    metricName: "Year electricity was first generated from geothermal steam", unit: "year",
    formalStatement: "The earliest year in which electricity was generated from geothermal heat.",
    summary: "On July 4, 1904, Prince Piero Ginori Conti tested the first geothermal power generator at Larderello in Tuscany, Italy, lighting four light bulbs with electricity made from natural steam. The world's first geothermal power plant followed at Larderello in 1911, and the field is still producing electricity today.",
    value: "1904",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Historical record of the Larderello geothermal field, operated today by Enel Green Power.",
    source: { title: "Enel Green Power — Larderello", url: "https://www.enelgreenpower.com/", date: "1904-07-04", location: "Larderello, Tuscany, Italy" },
  },
  {
    registryNumber: "LR-FIRST-ELECTRICITY-FROM-NUCLEAR-POWER", slug: "first-electricity-from-nuclear-power", title: "First electricity generated by nuclear power",
    category: "Energy", subcategory: "Nuclear Power", direction: "MINIMIZE",
    metricName: "Year a nuclear reactor first generated usable electricity", unit: "year",
    formalStatement: "The earliest year in which a nuclear reactor produced electrical power.",
    summary: "At 1:50 p.m. on December 20, 1951, Experimental Breeder Reactor I (EBR-I) in the Idaho desert produced enough electricity to light four 200-watt light bulbs, the first electricity ever generated from nuclear energy. EBR-I was also the first breeder reactor. The Soviet Obninsk plant became the first to feed a power grid in 1954.",
    value: "1951",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Argonne National Laboratory and Idaho National Laboratory reactor history; EBR-I is a U.S. National Historic Landmark.",
    source: { title: "Idaho National Laboratory — EBR-I", url: "https://inl.gov/", date: "1951-12-20", location: "Arco, Idaho, USA" },
  },
  {
    registryNumber: "LR-FIRST-HOUSE-LIT-BY-HYDROELECTRIC-POWER", slug: "first-house-lit-by-hydroelectric-power", title: "First house lit by hydroelectric power",
    category: "Energy", subcategory: "Hydropower", direction: "MINIMIZE",
    metricName: "Year a home was first lit with hydroelectricity", unit: "year",
    formalStatement: "The earliest year in which a house was lit by electricity generated from water power.",
    summary: "Cragside, the Northumberland home of industrialist William Armstrong, was the first house in the world lit by hydroelectric power. A water-driven generator powered an arc lamp in the picture gallery in 1878, and in 1880 Joseph Swan installed incandescent bulbs throughout the house.",
    value: "1878",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Historical record maintained by the National Trust, which owns Cragside.",
    source: { title: "National Trust — Cragside", url: "https://www.nationaltrust.org.uk/visit/north-east/cragside", date: "1878-01-01", location: "Rothbury, Northumberland, England" },
  },
  {
    registryNumber: "LR-FIRST-CENTRAL-HIGH-VOLTAGE-POWER-STATION", slug: "first-central-high-voltage-power-station", title: "First central high-voltage power station",
    category: "Energy", subcategory: "Power Stations", direction: "MINIMIZE",
    metricName: "Year the first central power station sending high-voltage electricity to distant consumers opened", unit: "year",
    formalStatement: "The earliest year in which a central power station was built to send high-voltage alternating current to consumers far from the plant.",
    summary: "Sebastian de Ferranti's Deptford Power Station on the River Thames opened in 1889 and is regarded as the first central high-voltage power station in the world. It sent high-voltage alternating current several miles to consumers in central London, a model for the large remote power stations that followed.",
    value: "1889",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "History of the London Electric Supply Corporation's Deptford station as recorded by the Institution of Engineering and Technology.",
    source: { title: "Institution of Engineering and Technology — archives", url: "https://www.theiet.org/", date: "1889-01-01", location: "Deptford, London, England" },
  },
  {
    registryNumber: "LR-FIRST-LONG-DISTANCE-THREE-PHASE-TRANSMISSION", slug: "first-long-distance-three-phase-transmission", title: "First long-distance three-phase power transmission",
    category: "Energy", subcategory: "Grids & Transmission", direction: "MINIMIZE",
    metricName: "Year high-power three-phase current was first transmitted over a long distance", unit: "year",
    formalStatement: "The earliest year in which high-power three-phase alternating current was sent over a long-distance line.",
    summary: "During the 1891 International Electrotechnical Exhibition in Frankfurt, three-phase alternating current generated at Lauffen am Neckar was carried 175 km to the exhibition grounds. This first long-distance transmission of high-power three-phase current established three-phase AC as the standard for power grids.",
    value: "1891",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Exhibition records and the history of the Lauffen–Frankfurt line by Michał Doliwo-Dobrowolski and Oskar von Miller.",
    source: { title: "IEEE — Milestones in electrical engineering", url: "https://ethw.org/Milestones:List_of_IEEE_Milestones", date: "1891-08-25", location: "Lauffen am Neckar – Frankfurt, Germany" },
  },
  {
    registryNumber: "LR-OLDEST-OPERATING-NUCLEAR-POWER-REACTOR", slug: "oldest-operating-nuclear-power-reactor", title: "Oldest operating nuclear power reactor",
    category: "Energy", subcategory: "Nuclear Power", direction: "MINIMIZE",
    metricName: "Year of commercial start-up of the oldest nuclear power reactor still in operation", unit: "year",
    formalStatement: "The earliest commercial operation start year of a nuclear power reactor that is still operating.",
    summary: "Unit 1 of the Beznau Nuclear Power Plant in Switzerland began commercial operation on December 24, 1969 and is still running, which makes it the oldest operating nuclear power reactor in the world. Its operator Axpo plans to keep it running until 2033.",
    value: "1969",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "IAEA PRIS reactor database start dates; standing as of October 2026.",
    source: { title: "IAEA PRIS — Power Reactor Information System", url: "https://pris.iaea.org/", date: "1969-12-24", location: "Döttingen, Aargau, Switzerland" },
  },
  {
    registryNumber: "LR-LARGEST-CONVENTIONAL-OIL-FIELD", slug: "largest-conventional-oil-field", title: "Largest conventional oil field",
    category: "Energy", subcategory: "Oil & Gas", direction: "MAXIMIZE",
    metricName: "Remaining proven crude oil reserves of a single oil field", unit: "barrels",
    formalStatement: "The greatest remaining proven oil reserves of any single conventional oil field.",
    summary: "Saudi Aramco's Ghawar field in Saudi Arabia's Eastern Province, about 280 km long and 30 km wide, is by far the largest conventional oil field in the world. Aramco's 2019 bond prospectus disclosed remaining proven reserves of about 48.25 billion barrels and a maximum sustainable output of 3.8 million barrels per day.",
    value: "48250000000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Reserve figure disclosed by Saudi Aramco in its 2019 bond prospectus; reserves estimates are company-reported and change as the field is produced.",
    source: { title: "Saudi Aramco", url: "https://www.aramco.com/", date: "2019-04-01", location: "Eastern Province, Saudi Arabia" },
  },
  {
    registryNumber: "LR-LARGEST-NATURAL-GAS-FIELD", slug: "largest-natural-gas-field", title: "Largest natural gas field",
    category: "Energy", subcategory: "Oil & Gas", direction: "MAXIMIZE",
    metricName: "Estimated natural gas in place in a single field", unit: "trillion cubic feet",
    formalStatement: "The greatest estimated volume of natural gas in place in any single gas field.",
    summary: "The South Pars/North Dome field, shared by Iran and Qatar under the Persian Gulf, is by far the world's largest natural gas field. It holds an estimated 1,800 trillion cubic feet (about 51 trillion cubic meters) of gas in place and about 50 billion barrels of natural gas condensate.",
    value: "1800",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "In-place volume estimates published by the International Energy Agency and geological studies; recoverable reserves are much smaller.",
    source: { title: "International Energy Agency", url: "https://www.iea.org/", date: "2008-01-01", location: "Persian Gulf (Iran and Qatar)" },
  },
  {
    registryNumber: "LR-LONGEST-OIL-WELL", slug: "longest-oil-well", title: "Longest oil well (measured depth)",
    category: "Energy", subcategory: "Oil & Gas", direction: "MAXIMIZE",
    metricName: "Measured length of a single drilled oil well", unit: "m",
    formalStatement: "The greatest measured length of any oil or gas well drilled, including extended-reach wells.",
    summary: "The Sakhalin-1 project off Russia's Sakhalin Island, operated by Exxon Neftegas, holds the record for the longest wells ever drilled. Its extended-reach wells from shore reach far out under the sea, and in November 2017 a record well reached 15 km long, beating the project's own earlier records such as the 12,376 m Z-44 Chayvo well of 2012.",
    value: "15000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Project-reported measured depths; the record stood at 15 km as of 2017 and project disclosures since then are limited.",
    source: { title: "Sakhalin-1 project", url: "https://www.sakhalin-1.com/", date: "2017-11-01", location: "Sakhalin Island, Russia" },
  },
  {
    registryNumber: "LR-LARGEST-POWER-OUTAGE", slug: "largest-power-outage", title: "Largest power outage by people affected",
    category: "Energy", subcategory: "Grids & Transmission", direction: "MAXIMIZE",
    metricName: "Number of people affected by a single electricity blackout", unit: "people",
    formalStatement: "The greatest number of people affected by a single power outage.",
    summary: "On July 31, 2012, a grid failure in India cut power to more than 620 million people in 22 states across northern and eastern India, about 9% of the world's population at the time. It came a day after another blackout that hit over 400 million people and remains the largest power outage in history.",
    value: "620000000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Government of India enquiry committee report and contemporary press estimates.",
    source: { title: "Ministry of Power, Government of India", url: "https://powermin.gov.in/", date: "2012-07-31", location: "Northern and eastern India" },
  },
  {
    registryNumber: "LR-FIRST-SOLAR-POWERED-SATELLITE", slug: "first-solar-powered-satellite", title: "First solar-powered satellite",
    category: "Energy", subcategory: "Solar Power", direction: "MINIMIZE",
    metricName: "Year the first satellite powered by solar cells was launched", unit: "year",
    formalStatement: "The earliest year in which a spacecraft powered by solar cells was launched.",
    summary: "Vanguard 1, launched by the United States on March 17, 1958, was the first satellite powered by solar cells. Its solar-powered transmitter kept working until 1964, and the satellite is still in orbit today as the oldest human-made object in space.",
    value: "1958",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Mission record maintained by NASA and the U.S. Naval Research Laboratory.",
    source: { title: "NASA — Vanguard 1", url: "https://nssdc.gsfc.nasa.gov/nmc/spacecraft/display.action?id=1958-002B", date: "1958-03-17", location: "Cape Canaveral, Florida, USA" },
  },
  {
    registryNumber: "LR-FIRST-MEGAWATT-SOLAR-POWER-PLANT", slug: "first-megawatt-solar-power-plant", title: "First megawatt-scale solar photovoltaic power plant",
    category: "Energy", subcategory: "Solar Power", direction: "MINIMIZE",
    metricName: "Year the first solar PV power station of at least 1 MW was completed", unit: "year",
    formalStatement: "The earliest year in which a solar photovoltaic power station with a capacity of at least one megawatt was completed.",
    summary: "The first 1 MW solar photovoltaic park was built by ARCO Solar at Lugo near Hesperia, California, at the end of 1982. It was followed in 1984 by a 5.2 MW plant at Carrizo Plain. Today's largest solar parks are thousands of times bigger.",
    value: "1982",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Installation and performance paper by Arnett et al., Proceedings of the Fifth International Photovoltaic Solar Energy Conference (1984).",
    source: { title: "U.S. National Renewable Energy Laboratory", url: "https://www.nrel.gov/", date: "1982-12-01", location: "Hesperia, California, USA" },
  },
  {
    registryNumber: "LR-LARGEST-OPERATIONAL-OFFSHORE-WIND-FARM", slug: "largest-operational-offshore-wind-farm", title: "Largest operational offshore wind farm",
    category: "Energy", subcategory: "Wind Power", direction: "MAXIMIZE",
    metricName: "Nameplate capacity of an operating offshore wind farm", unit: "MW",
    formalStatement: "The greatest nameplate capacity of an offshore wind farm that is fully operational.",
    summary: "Hornsea Project Two, about 89 km off the Yorkshire coast in the UK North Sea, became fully operational in August 2022 with 165 Siemens Gamesa 8 MW turbines and a capacity of 1,386 MW, making it the world's largest operating offshore wind farm. Even larger projects such as Dogger Bank are still being built.",
    value: "1386",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Operator-published capacity; ranking as of 2026, with larger projects under construction.",
    source: { title: "Ørsted — Hornsea Project Two", url: "https://hornseaprojects.co.uk/hornsea-project-two", date: "2022-08-31", location: "North Sea, United Kingdom" },
  },
  {
    registryNumber: "LR-HIGHEST-NUCLEAR-SHARE-OF-ELECTRICITY", slug: "highest-nuclear-share-of-electricity", title: "Highest share of electricity from nuclear power (country)",
    category: "Energy", subcategory: "Nuclear Power", direction: "MAXIMIZE",
    metricName: "Share of a country's electricity generation supplied by nuclear power", unit: "%",
    formalStatement: "The greatest share of national electricity generation supplied by nuclear power in any country.",
    summary: "France gets about 65% of its electricity from nuclear power, the highest share of any country. Of the 31 countries that operate nuclear power plants, only France, Slovakia, Belgium and Ukraine rely on them for most of their electricity as of 2026.",
    value: "65",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "IAEA PRIS nuclear share statistics; the share varies year to year with reactor availability, as of 2026.",
    source: { title: "IAEA PRIS — Nuclear share of electricity generation", url: "https://pris.iaea.org/pris/worldstatistics/nuclearshareofelectricitygeneration.aspx", date: "2026-10-05", location: "France" },
  },
  {
    registryNumber: "LR-LARGEST-URANIUM-PRODUCING-COUNTRY", slug: "largest-uranium-producing-country", title: "Largest uranium-producing country",
    category: "Energy", subcategory: "Nuclear Fuel", direction: "MAXIMIZE",
    metricName: "Annual uranium mine production of a single country", unit: "tonnes U",
    formalStatement: "The greatest annual production of uranium by a single country.",
    summary: "Kazakhstan is the world's largest uranium producer, mining 21,227 tonnes of uranium in 2022, about 43% of the world total. Canada, Namibia and Australia are the next-largest producers. Most Kazakh uranium is extracted by in-situ leaching rather than conventional mining.",
    value: "21227",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "World Nuclear Association production statistics for 2022.",
    source: { title: "World Nuclear Association — World uranium mining production", url: "https://world-nuclear.org/information-library/nuclear-fuel-cycle/mining-of-uranium/world-uranium-mining-production", date: "2022-12-31", location: "Kazakhstan" },
  },
  {
    registryNumber: "LR-LARGEST-CRUDE-OIL-PRODUCING-COUNTRY", slug: "largest-crude-oil-producing-country", title: "Largest crude oil-producing country",
    category: "Energy", subcategory: "Oil & Gas", direction: "MAXIMIZE",
    metricName: "Crude oil and lease condensate production of a single country", unit: "barrels per day",
    formalStatement: "The greatest rate of crude oil (including lease condensate) production by a single country.",
    summary: "The United States is the world's largest crude oil producer, extracting about 13.2 million barrels per day of crude oil and lease condensate in January 2026, out of a world total of about 84.5 million barrels per day. U.S. output has overtaken Saudi Arabia and Russia since the shale boom.",
    value: "13246000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "U.S. Energy Information Administration international data for January 2026; monthly figures fluctuate.",
    source: { title: "U.S. Energy Information Administration — International data", url: "https://www.eia.gov/international/data/world", date: "2026-01-31", location: "United States" },
  },
  {
    registryNumber: "LR-FIRST-NUCLEAR-POWERED-SURFACE-SHIP", slug: "first-nuclear-powered-surface-ship", title: "First nuclear-powered surface ship",
    category: "Energy", subcategory: "Nuclear Power", direction: "MINIMIZE",
    metricName: "Year the first nuclear-powered surface ship entered service", unit: "year",
    formalStatement: "The earliest year in which a nuclear-powered surface vessel entered service.",
    summary: "The Soviet icebreaker Lenin, launched in Leningrad in 1957 and in service from 1959 to 1989, was the world's first nuclear-powered surface ship and the first nuclear-powered civilian vessel. It is now a museum ship in Murmansk.",
    value: "1959",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Service history of the icebreaker as recorded by its operator Atomflot and the museum in Murmansk.",
    source: { title: "Rosatomflot", url: "https://www.rosatomflot.ru/", date: "1959-01-01", location: "Leningrad / Murmansk, Russia" },
  },
  // --- Speed Records ---
  {
    registryNumber: "LR-FASTEST-HYDROGEN-FUEL-CELL-CAR", slug: "fastest-hydrogen-fuel-cell-car", title: "Fastest hydrogen fuel-cell car",
    category: "Speed Records", subcategory: "Cars", direction: "MAXIMIZE",
    metricName: "FIA-certified flying-mile speed of a hydrogen fuel-cell vehicle", unit: "km/h",
    formalStatement: "The greatest certified land speed achieved by a vehicle powered by a hydrogen fuel cell.",
    summary: "Ohio State University's Buckeye Bullet 2 set FIA international land speed records for a hydrogen fuel-cell vehicle on September 25, 2009 at the Bonneville Salt Flats in Utah, averaging 487.4 km/h (302.877 mph) over the flying mile and 487.7 km/h (303.025 mph) over the flying kilometre.",
    value: "487.4",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "FIA-sanctioned two-way average speeds over a measured mile.",
    source: { title: "FIA — Land speed records", url: "https://www.fia.com/", date: "2009-09-25", location: "Bonneville Salt Flats, Utah, USA" },
  },
  {
    registryNumber: "LR-FASTEST-STEAM-POWERED-CAR", slug: "fastest-steam-powered-car", title: "Fastest steam-powered car",
    category: "Speed Records", subcategory: "Cars", direction: "MAXIMIZE",
    metricName: "FIA-certified two-way average speed of a steam-powered car over a measured mile", unit: "km/h",
    formalStatement: "The greatest certified land speed achieved by a steam-powered car.",
    summary: "The British Steam Car Challenge's Inspiration, driven by Charles Burnett III, averaged 225 km/h (139.843 mph) over two runs of a measured mile at Edwards Air Force Base, California, on August 25, 2009. That broke a steam car record that had stood since 1906. The next day Don Wales drove it to 238.7 km/h (148.308 mph) over a measured kilometre.",
    value: "225.05",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "FIA-sanctioned two-way average over a measured mile.",
    source: { title: "FIA — Land speed records", url: "https://www.fia.com/", date: "2009-08-25", location: "Edwards Air Force Base, California, USA" },
  },
  {
    registryNumber: "LR-FASTEST-SOLAR-POWERED-CAR", slug: "fastest-solar-powered-car", title: "Fastest solar-powered car",
    category: "Speed Records", subcategory: "Cars", direction: "MAXIMIZE",
    metricName: "Top speed of a vehicle powered only by solar panels", unit: "km/h",
    formalStatement: "The greatest speed achieved by a vehicle powered only by its own solar panels, as certified by Guinness World Records.",
    summary: "The Sky Ace TIGA, built by Ashiya University in Japan, reached 91.332 km/h (56.75 mph) at Shimojishima Airport in Miyakojima, Okinawa, on August 20, 2014, the Guinness World Record for a vehicle powered only by solar panels.",
    value: "91.332",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Guinness World Records adjudication.",
    source: { title: "Guinness World Records — Fastest solar-powered vehicle", url: "https://www.guinnessworldrecords.com/", date: "2014-08-20", location: "Miyakojima, Okinawa, Japan" },
  },
  {
    registryNumber: "LR-FASTEST-HOVERCRAFT", slug: "fastest-hovercraft", title: "Fastest hovercraft",
    category: "Speed Records", subcategory: "Watercraft", direction: "MAXIMIZE",
    metricName: "Top speed recorded by a hovercraft", unit: "km/h",
    formalStatement: "The greatest speed recorded by a hovercraft, as certified by Guinness World Records.",
    summary: "American Bob Windt drove a hovercraft at 137.4 km/h (85.38 mph) at the World Hovercraft Championships on the Douro River at Peso da Régua, Portugal, on September 18, 1995, the world hovercraft speed record recognized by Guinness World Records.",
    value: "137.4",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Guinness World Records adjudication.",
    source: { title: "Guinness World Records — Fastest hovercraft", url: "https://www.guinnessworldrecords.com/", date: "1995-09-18", location: "Peso da Régua, Portugal" },
  },
  {
    registryNumber: "LR-FASTEST-WINDSURFING-SPEED", slug: "fastest-windsurfing-speed", title: "Fastest windsurfing speed",
    category: "Speed Records", subcategory: "Sailing", direction: "MAXIMIZE",
    metricName: "Average speed of a windsurfer over a 500 m course", unit: "knots",
    formalStatement: "The greatest average speed over a 500 m course achieved by a windsurfer, as ratified by the World Sailing Speed Record Council.",
    summary: "French windsurfer Antoine Albeau averaged 53.27 knots (98.7 km/h) over 500 m at the Lüderitz speed canal in Namibia in 2015, the windsurfing speed record ratified by the World Sailing Speed Record Council. He had held the outright sailing speed record in 2008 with 49.09 knots.",
    value: "53.27",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "World Sailing Speed Record Council ratification of a timed 500 m run.",
    source: { title: "World Sailing Speed Record Council", url: "https://www.sailspeedrecords.com/", date: "2015-11-01", location: "Lüderitz, Namibia" },
  },
  {
    registryNumber: "LR-FASTEST-RUBIKS-CUBE-SOLVE", slug: "fastest-rubiks-cube-solve", title: "Fastest Rubik's Cube solve (3x3x3 single)",
    category: "Speed Records", subcategory: "Human Speed", direction: "MINIMIZE",
    metricName: "Time for a single official solve of a 3x3x3 Rubik's Cube", unit: "seconds",
    formalStatement: "The shortest time for a single solve of the standard 3x3x3 Rubik's Cube in a World Cube Association competition.",
    summary: "Teodor Zajder of Poland solved a 3x3x3 Rubik's Cube in 2.76 seconds at GLS Big Cubes Gdańsk 2026 on February 7–8, 2026, the official World Cube Association world record. The average-of-five record of 3.51 seconds belongs to China's Yiheng Wang.",
    value: "2.76",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "World Cube Association official results; speedcubing records fall often, so this is the standing as of October 2026.",
    source: { title: "World Cube Association — Records", url: "https://www.worldcubeassociation.org/results/records", date: "2026-02-08", location: "Gdańsk, Poland" },
  },
  {
    registryNumber: "LR-FASTEST-JET-SUIT-FLIGHT", slug: "fastest-jet-suit-flight", title: "Fastest flight in a jet suit",
    category: "Speed Records", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "Top speed in a body-controlled jet-engine-powered suit", unit: "km/h",
    formalStatement: "The greatest speed reached in a body-controlled, jet-engine-powered suit, as certified by Guinness World Records.",
    summary: "Richard Browning, founder of Gravity Industries, reached 136.89 km/h (85.06 mph) in his body-controlled jet suit over Brighton, England, in November 2019, the Guinness World Record for the fastest speed in a jet-engine-powered suit.",
    value: "136.89",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Guinness World Records adjudication using GPS data.",
    source: { title: "Guinness World Records — Fastest speed in a body-controlled jet engine powered suit", url: "https://www.guinnessworldrecords.com/", date: "2019-11-07", location: "Brighton, England" },
  },
  {
    registryNumber: "LR-FASTEST-PROPELLER-DRIVEN-SEAPLANE", slug: "fastest-propeller-driven-seaplane", title: "Fastest propeller-driven seaplane",
    category: "Speed Records", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "Official speed record for a piston-engined seaplane", unit: "km/h",
    formalStatement: "The greatest officially recorded speed of a propeller-driven seaplane.",
    summary: "Francesco Agello flew the Italian Macchi M.C.72 racing seaplane at an average of 709.2 km/h (440.681 mph) over Lake Garda on October 23, 1934. It was the fastest any aircraft had flown at the time, and more than 90 years later it is still the speed record for a piston-engined seaplane.",
    value: "709.2",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "FAI-ratified speed record.",
    source: { title: "FAI — World Air Sports Federation records", url: "https://www.fai.org/records", date: "1934-10-23", location: "Lake Garda, Italy" },
  },
  {
    registryNumber: "LR-FASTEST-PROPELLER-DRIVEN-AIRCRAFT", slug: "fastest-propeller-driven-aircraft", title: "Fastest propeller-driven aircraft",
    category: "Speed Records", subcategory: "Aviation", direction: "MAXIMIZE",
    metricName: "FAI speed record of a turboprop (propeller-driven) aircraft", unit: "km/h",
    formalStatement: "The greatest officially recorded speed of a propeller-driven aircraft.",
    summary: "The Soviet Tupolev Tu-114 turboprop airliner set an FAI speed record of 871.38 km/h on a 1,000 km closed circuit on March 24, 1960, and has held the official title of fastest propeller-driven aircraft ever since. It was the largest, fastest and longest-range airliner of its day.",
    value: "871.38",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "FAI-ratified closed-circuit speed record.",
    source: { title: "FAI — World Air Sports Federation records", url: "https://www.fai.org/records", date: "1960-03-24", location: "Soviet Union" },
  },
  {
    registryNumber: "LR-FASTEST-NEW-YORK-TO-LONDON-FLIGHT", slug: "fastest-new-york-to-london-flight", title: "Fastest flight from New York to London",
    category: "Speed Records", subcategory: "Aviation", direction: "MINIMIZE",
    metricName: "Elapsed time of a flight between New York and London", unit: "seconds",
    formalStatement: "The shortest officially recorded elapsed flight time between New York and London.",
    summary: "A U.S. Air Force SR-71 Blackbird flown by James Sullivan and Noel Widdifield flew from New York to London in 1 hour, 54 minutes and 56.4 seconds on September 1, 1974, averaging 2,908 km/h (1,806.964 mph) over 5,571 km. More than 50 years later the record is still unbroken.",
    value: "6896.4",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "FAI 'speed over a recognized course' record.",
    source: { title: "FAI — World Air Sports Federation records", url: "https://www.fai.org/records", date: "1974-09-01", location: "New York – London" },
  },
  {
    registryNumber: "LR-FASTEST-US-COAST-TO-COAST-FLIGHT", slug: "fastest-us-coast-to-coast-flight", title: "Fastest flight from Los Angeles to Washington, D.C.",
    category: "Speed Records", subcategory: "Aviation", direction: "MINIMIZE",
    metricName: "Elapsed time of a flight between Los Angeles and Washington, D.C.", unit: "seconds",
    formalStatement: "The shortest officially recorded elapsed flight time between Los Angeles and Washington, D.C.",
    summary: "On March 6, 1990, on its retirement flight, an SR-71 Blackbird flew from Los Angeles to Washington, D.C., 3,701 km (2,299.7 miles), in 64 minutes 20 seconds, averaging 3,452 km/h (2,144.8 mph). The aircraft was then handed over to the Smithsonian Institution.",
    value: "3860",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "FAI 'speed over a recognized course' record.",
    source: { title: "Smithsonian National Air and Space Museum — SR-71", url: "https://airandspace.si.edu/collection-objects/lockheed-sr-71-blackbird/nasm_A19920072000", date: "1990-03-06", location: "Los Angeles – Washington, D.C., USA" },
  },
  {
    registryNumber: "LR-FASTEST-PASSENGER-SHIP-IN-SERVICE", slug: "fastest-passenger-ship-in-service", title: "Fastest passenger ship in service",
    category: "Speed Records", subcategory: "Watercraft", direction: "MAXIMIZE",
    metricName: "Top speed of a passenger ship in commercial service", unit: "knots",
    formalStatement: "The greatest speed reached by a passenger ship in commercial service.",
    summary: "The Buquebus high-speed ferry Francisco, built by Incat in Tasmania and running between Buenos Aires and Montevideo, reached 58.2 knots (107.8 km/h) and is the fastest passenger ship in service. It is powered by two LNG-fuelled GE gas turbines driving waterjets.",
    value: "58.2",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Builder-reported sea-trial speed; ranking as of 2026.",
    source: { title: "Incat — Hull 069 Francisco", url: "https://www.incat.com.au/", date: "2013-01-01", location: "Río de la Plata, Argentina–Uruguay" },
  },
  {
    registryNumber: "LR-FASTEST-PIKES-PEAK-CLIMB", slug: "fastest-pikes-peak-climb", title: "Fastest Pikes Peak International Hill Climb",
    category: "Speed Records", subcategory: "Motorsport", direction: "MINIMIZE",
    metricName: "Course time on the 19.99 km Pikes Peak hill climb", unit: "seconds",
    formalStatement: "The shortest time to complete the Pikes Peak International Hill Climb course.",
    summary: "Romain Dumas drove the all-electric Volkswagen I.D. R to the summit of Pikes Peak in Colorado in 7 minutes 57.148 seconds on June 24, 2018, the course record and the first run under eight minutes. The course climbs about 1,440 m through 156 turns.",
    value: "477.148",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official timing by the Pikes Peak International Hill Climb.",
    source: { title: "Pikes Peak International Hill Climb — Records", url: "https://ppihc.org/", date: "2018-06-24", location: "Pikes Peak, Colorado, USA" },
  },
  {
    registryNumber: "LR-FASTEST-NURBURGRING-NORDSCHLEIFE-LAP", slug: "fastest-nurburgring-nordschleife-lap", title: "Fastest lap of the Nürburgring Nordschleife",
    category: "Speed Records", subcategory: "Motorsport", direction: "MINIMIZE",
    metricName: "Lap time on the 20.832 km Nürburgring Nordschleife", unit: "seconds",
    formalStatement: "The shortest lap time recorded on the full 20.832 km Nürburgring Nordschleife layout.",
    summary: "Timo Bernhard lapped the 20.832 km Nürburgring Nordschleife in Germany in 5 minutes 19.546 seconds in the Porsche 919 Hybrid Evo on June 29, 2018. It broke Stefan Bellof's 1983 record of 6:11.13 by nearly 52 seconds and is still the fastest lap of the circuit.",
    value: "319.546",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Timed lap published by Porsche and the circuit operator.",
    source: { title: "Porsche Newsroom — 919 Hybrid Evo Nordschleife record", url: "https://newsroom.porsche.com/", date: "2018-06-29", location: "Nürburg, Germany" },
  },
  {
    registryNumber: "LR-FASTEST-ISLE-OF-MAN-TT-LAP", slug: "fastest-isle-of-man-tt-lap", title: "Fastest lap of the Isle of Man TT Mountain Course",
    category: "Speed Records", subcategory: "Motorsport", direction: "MAXIMIZE",
    metricName: "Average lap speed on the 60.72 km Isle of Man TT Mountain Course", unit: "mph",
    formalStatement: "The greatest average lap speed recorded in a race on the Isle of Man TT Mountain Course.",
    summary: "Peter Hickman lapped the 37.73-mile (60.72 km) Isle of Man TT Mountain Course on public roads in 16:36.114 on a BMW M1000RR during the 2023 Superstock TT, an average of 136.358 mph (219.4 km/h). It is the outright lap record for the course.",
    value: "136.358",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Official TT race timing; standing as of 2026.",
    source: { title: "Isle of Man TT Races — Lap and race records", url: "https://www.iomttraces.com/racing/page/lap-and-race-records/", date: "2023-06-01", location: "Isle of Man" },
  },
  {
    registryNumber: "LR-FASTEST-HUMAN-POWERED-WATERCRAFT", slug: "fastest-human-powered-watercraft", title: "Fastest human-powered watercraft",
    category: "Speed Records", subcategory: "Watercraft", direction: "MAXIMIZE",
    metricName: "Top speed of a human-powered boat over a 100 m course", unit: "knots",
    formalStatement: "The greatest speed achieved by a human-powered watercraft over a timed course.",
    summary: "MIT's Decavitator, a pedal-powered hydrofoil boat, reached 18.5 knots (34.3 km/h) over a 100 m course on October 27, 1991, with aeronautical engineer Mark Drela pedaling. It remains the human-powered speed record on water.",
    value: "18.5",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Course timing reported by the MIT team and the International Human Powered Vehicle Association.",
    source: { title: "MIT — Decavitator human-powered hydrofoil", url: "https://web.mit.edu/", date: "1991-10-27", location: "Boston, Massachusetts, USA" },
  },
  // --- Arts & Entertainment ---
  {
    registryNumber: "LR-LONGEST-RUNNING-WEST-END-MUSICAL", slug: "longest-running-west-end-musical", title: "Longest-running West End musical",
    category: "Arts & Entertainment", subcategory: "Theatre", direction: "MAXIMIZE",
    metricName: "Years since opening of a musical in continuous West End production", unit: "years",
    formalStatement: "The longest continuous run of a musical in London's West End, counted in years since opening.",
    summary: "Les Misérables, the Claude-Michel Schönberg and Alain Boublil musical produced by Cameron Mackintosh, opened in London in October 1985 and has run continuously ever since, which makes it the longest-running musical in West End history. Worldwide, only the original off-Broadway run of The Fantasticks ran longer.",
    value: "41",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Production history published by the show's producers; value counts years since opening as of 2026.",
    source: { title: "Les Misérables — official site", url: "https://www.lesmis.com/", date: "1985-10-08", location: "London, England" },
  },
  {
    registryNumber: "LR-OLDEST-ACTIVE-OPERA-HOUSE", slug: "oldest-active-opera-house", title: "Oldest opera house in continuous use",
    category: "Arts & Entertainment", subcategory: "Theatre", direction: "MINIMIZE",
    metricName: "Opening year of the oldest continuously active opera venue", unit: "year",
    formalStatement: "The earliest opening year of an opera house that has been in continuous use since.",
    summary: "The Teatro di San Carlo in Naples, Italy, opened on November 4, 1737 with Domenico Sarro's Achille in Sciro. It is the oldest continuously active venue for opera in the world, opening decades before Milan's La Scala and Venice's La Fenice.",
    value: "1737",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Theatre history published by the Teatro di San Carlo.",
    source: { title: "Teatro di San Carlo — History", url: "https://www.teatrosancarlo.it/", date: "1737-11-04", location: "Naples, Italy" },
  },
  {
    registryNumber: "LR-LARGEST-OPERA-HOUSE", slug: "largest-opera-house", title: "Largest opera house",
    category: "Arts & Entertainment", subcategory: "Theatre", direction: "MAXIMIZE",
    metricName: "Total audience capacity of a repertory opera house", unit: "people",
    formalStatement: "The greatest total audience capacity of a repertory opera house.",
    summary: "The Metropolitan Opera House at Lincoln Center in New York City, opened in 1966, holds 3,975 people, including 3,800 seats and 175 standing places. Guinness World Records lists it as the largest opera house in the world.",
    value: "3975",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Seating figures published by the Metropolitan Opera and recognized by Guinness World Records.",
    source: { title: "Guinness World Records — Largest opera house", url: "https://www.guinnessworldrecords.com/", date: "1966-09-16", location: "New York City, USA" },
  },
  {
    registryNumber: "LR-BEST-SELLING-MANGA-SERIES", slug: "best-selling-manga-series", title: "Best-selling manga series",
    category: "Arts & Entertainment", subcategory: "Comics", direction: "MAXIMIZE",
    metricName: "Copies in circulation of a single manga series", unit: "copies",
    formalStatement: "The greatest number of copies in print of any manga (Japanese comic) series.",
    summary: "Eiichiro Oda's One Piece, serialized in Shueisha's Weekly Shōnen Jump since 1997, passed 600 million copies in circulation worldwide across more than 110 volumes. It is the best-selling manga ever and holds the Guinness World Record for the most copies published for the same comic book series by a single author.",
    value: "600000000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Publisher-reported circulation figures; the total grows with each new volume, as of 2026.",
    source: { title: "Shueisha — One Piece", url: "https://www.shueisha.co.jp/", date: "2026-10-05", location: "Japan / worldwide" },
  },
  {
    registryNumber: "LR-BEST-SELLING-VIDEO-GAME-FRANCHISE", slug: "best-selling-video-game-franchise", title: "Best-selling video game franchise",
    category: "Arts & Entertainment", subcategory: "Video Games", direction: "MAXIMIZE",
    metricName: "Cumulative software units sold across a video game franchise", unit: "units",
    formalStatement: "The greatest cumulative number of game units sold by any video game franchise.",
    summary: "Nintendo's Mario franchise has sold more than 907 million units since its first release in 1983, the most of any video game franchise. The core Super Mario platformers make up about 430 million of that, with the rest from Mario Kart, Mario Party and other spin-offs.",
    value: "907000000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Publisher-reported unit sales compiled from Nintendo data, as of 2026.",
    source: { title: "Nintendo — IR information", url: "https://www.nintendo.co.jp/ir/en/", date: "2026-10-05", location: "Worldwide" },
  },
  {
    registryNumber: "LR-MOST-ACADEMY-AWARDS-FOR-BEST-DIRECTOR", slug: "most-academy-awards-for-best-director", title: "Most Academy Awards for Best Director",
    category: "Arts & Entertainment", subcategory: "Film Awards", direction: "MAXIMIZE",
    metricName: "Number of Best Director Oscars won by one person", unit: "awards",
    formalStatement: "The greatest number of Academy Awards for Best Director won by a single person.",
    summary: "John Ford won the Academy Award for Best Director a record four times, for The Informer (1935), The Grapes of Wrath (1940), How Green Was My Valley (1941) and The Quiet Man (1952). Frank Capra and William Wyler won three each.",
    value: "4",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Academy of Motion Picture Arts and Sciences awards database.",
    source: { title: "Academy Awards database", url: "https://awardsdatabase.oscars.org/", date: "1953-03-19", location: "Los Angeles, California, USA" },
  },
  {
    registryNumber: "LR-OLDEST-ACADEMY-AWARD-WINNER", slug: "oldest-academy-award-winner", title: "Oldest Academy Award winner",
    category: "Arts & Entertainment", subcategory: "Film Awards", direction: "MAXIMIZE",
    metricName: "Age of the oldest person to win a competitive Academy Award", unit: "years",
    formalStatement: "The greatest age at which a person has won a competitive Academy Award.",
    summary: "James Ivory won the Academy Award for Best Adapted Screenplay for Call Me by Your Name at the 90th Academy Awards on March 4, 2018, at age 89. That made him the oldest winner of a competitive Oscar in any category.",
    value: "89",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Academy of Motion Picture Arts and Sciences awards statistics.",
    source: { title: "Academy Awards database", url: "https://awardsdatabase.oscars.org/", date: "2018-03-04", location: "Los Angeles, California, USA" },
  },
  {
    registryNumber: "LR-LARGEST-FILM-STUDIO-COMPLEX", slug: "largest-film-studio-complex", title: "Largest film studio complex",
    category: "Arts & Entertainment", subcategory: "Film", direction: "MAXIMIZE",
    metricName: "Land area of a film studio complex", unit: "acres",
    formalStatement: "The greatest land area of a film studio complex.",
    summary: "Ramoji Film City, outside Hyderabad in India, opened in 1996 and spreads over about 2,000 acres. Guinness World Records recognized it as the world's largest film studio complex in 2005. It has hosted productions in many Indian languages, including the Baahubali films.",
    value: "2000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Area as published by Ramoji Film City; Guinness World Records recognition (2005).",
    source: { title: "Ramoji Film City — About us", url: "https://www.ramojifilmcity.com/about-us", date: "2005-01-01", location: "Hyderabad, Telangana, India" },
  },
  {
    registryNumber: "LR-MOST-EUROVISION-SONG-CONTEST-WINS", slug: "most-eurovision-song-contest-wins", title: "Most Eurovision Song Contest wins by a country",
    category: "Arts & Entertainment", subcategory: "Music", direction: "MAXIMIZE",
    metricName: "Number of Eurovision Song Contest victories by one country", unit: "wins",
    formalStatement: "The greatest number of Eurovision Song Contest wins by a single country.",
    summary: "Ireland and Sweden have each won the Eurovision Song Contest seven times, more than any other country. Ireland's seventh came in 1996 after an unmatched three wins in a row from 1992 to 1994; Sweden drew level with Loreen's 'Tattoo' in 2023. Bulgaria won the 2026 contest in Vienna.",
    value: "7",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official results published by the European Broadcasting Union, as of the 2026 contest.",
    source: { title: "Eurovision Song Contest — official site", url: "https://www.eurovision.com/", date: "2023-05-13", location: "Europe" },
  },
  {
    registryNumber: "LR-MOST-EXPENSIVE-MUSICAL-INSTRUMENT-SOLD-AT-AUCTION", slug: "most-expensive-musical-instrument-sold-at-auction", title: "Most expensive musical instrument sold at auction",
    category: "Arts & Entertainment", subcategory: "Music", direction: "MAXIMIZE",
    metricName: "Auction price of a musical instrument", unit: "GBP",
    formalStatement: "The highest price paid for a musical instrument at auction.",
    summary: "The 1721 'Lady Blunt' Stradivarius violin sold for £9.8 million (about $15.9 million) in an online charity auction by Tarisio on June 20, 2011, with the proceeds going to relief efforts after the 2011 Japanese earthquake and tsunami. It is still the highest auction price for any musical instrument.",
    value: "9800000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Auction result reported by Tarisio and the BBC; standing as of 2026.",
    source: { title: "BBC News — Stradivarius violin sold for £9.8m at charity auction", url: "https://www.bbc.co.uk/news/entertainment-arts-13852872", date: "2011-06-21", location: "London, England (online auction)" },
  },
  {
    registryNumber: "LR-OLDEST-SURVIVING-PIANO", slug: "oldest-surviving-piano", title: "Oldest surviving piano",
    category: "Arts & Entertainment", subcategory: "Music", direction: "MINIMIZE",
    metricName: "Year of manufacture of the oldest surviving piano", unit: "year",
    formalStatement: "The earliest year of manufacture of a piano that still survives.",
    summary: "The oldest surviving piano was built in 1720 by Bartolomeo Cristofori, the Florentine instrument maker who invented the piano, and is now at the Metropolitan Museum of Art in New York. Only three Cristofori pianos survive, all from the 1720s.",
    value: "1720",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Instrument dating by the Metropolitan Museum of Art.",
    source: { title: "The Metropolitan Museum of Art — Cristofori piano (1720)", url: "https://www.metmuseum.org/", date: "1720-01-01", location: "Florence, Italy / New York, USA" },
  },
  {
    registryNumber: "LR-LARGEST-PIPE-ORGAN", slug: "largest-pipe-organ", title: "Largest pipe organ",
    category: "Arts & Entertainment", subcategory: "Music", direction: "MAXIMIZE",
    metricName: "Number of pipes in a single pipe organ", unit: "pipes",
    formalStatement: "The greatest number of pipes in a single pipe organ.",
    summary: "The Boardwalk Hall Auditorium Organ in Atlantic City, New Jersey, built by the Midmer-Losh company from 1929 to 1932, is the largest pipe organ in the world, with officially 33,112 pipes, though the exact count is uncertain.",
    value: "33112",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Pipe count published by the Historic Organ Restoration Committee and recognized by Guinness World Records.",
    source: { title: "Historic Organ Restoration Committee — Boardwalk Hall organs", url: "https://www.boardwalkorgans.org/", date: "1932-01-01", location: "Atlantic City, New Jersey, USA" },
  },
  {
    registryNumber: "LR-LARGEST-CINEMA-COMPLEX", slug: "largest-cinema-complex", title: "Largest cinema complex",
    category: "Arts & Entertainment", subcategory: "Film", direction: "MAXIMIZE",
    metricName: "Seating capacity of a single multiplex cinema", unit: "seats",
    formalStatement: "The greatest seating capacity of a single cinema complex.",
    summary: "Kinepolis Madrid Ciudad de la Imagen opened on September 17, 1998 with 25 screens and 9,200 seats, making it the world's largest cinema megaplex. The Belgian chain had already opened the first megaplex, Kinepolis Brussels, with 25 screens and 7,600 seats.",
    value: "9200",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Capacity as published by Kinepolis Group; ranking as of 2026.",
    source: { title: "Kinepolis Group", url: "https://corporate.kinepolis.com/", date: "1998-09-17", location: "Madrid, Spain" },
  },
  {
    registryNumber: "LR-OLDEST-OPERATING-BOOKSTORE", slug: "oldest-operating-bookstore", title: "Oldest operating bookstore",
    category: "Arts & Entertainment", subcategory: "Literature & Publishing", direction: "MINIMIZE",
    metricName: "Founding year of the oldest bookstore still operating", unit: "year",
    formalStatement: "The earliest founding year of a bookstore that is still in business.",
    summary: "Livraria Bertrand, founded in Lisbon in 1732, has its original shop on Rua Garrett in the Chiado district. Guinness World Records recognizes it as the oldest operating bookstore in the world, and the chain now has dozens of branches across Portugal.",
    value: "1732",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Guinness World Records certification (2011).",
    source: { title: "Guinness World Records — Oldest bookshop", url: "https://www.guinnessworldrecords.com/", date: "1732-01-01", location: "Lisbon, Portugal" },
  },
  {
    registryNumber: "LR-OLDEST-UNIVERSITY-PRESS", slug: "oldest-university-press", title: "Oldest university press",
    category: "Arts & Entertainment", subcategory: "Literature & Publishing", direction: "MINIMIZE",
    metricName: "Year of founding of the oldest university press", unit: "year",
    formalStatement: "The earliest founding year of a university press that is still publishing.",
    summary: "Cambridge University Press dates from letters patent that King Henry VIII granted to the University of Cambridge in 1534. It is the oldest university press in the world and has published continuously since 1584.",
    value: "1534",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Founding charter dating published by Cambridge University Press.",
    source: { title: "Cambridge University Press — Our history", url: "https://www.cambridge.org/about-us/who-we-are/history", date: "1534-07-20", location: "Cambridge, England" },
  },
  {
    registryNumber: "LR-LONGEST-RUNNING-RADIO-DRAMA", slug: "longest-running-radio-drama", title: "Longest-running radio drama",
    category: "Arts & Entertainment", subcategory: "Radio", direction: "MINIMIZE",
    metricName: "First broadcast year of the longest-running radio drama", unit: "year",
    formalStatement: "The earliest first-broadcast year of a radio drama series that is still being broadcast.",
    summary: "The BBC's rural soap opera The Archers was first broadcast nationally on January 1, 1951 and has aired ever since, first on the Light Programme and since 1967 on BBC Radio 4. With more than 20,000 episodes, it is the world's longest-running drama by both number of episodes and years on air.",
    value: "1951",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Broadcast history published by the BBC.",
    source: { title: "BBC Radio 4 — The Archers", url: "https://www.bbc.co.uk/programmes/b006qpgr", date: "1951-01-01", location: "Birmingham, England" },
  },
  {
    registryNumber: "LR-LONGEST-RUNNING-RADIO-BROADCAST-US", slug: "longest-running-radio-broadcast-us", title: "Longest-running radio broadcast in U.S. history",
    category: "Arts & Entertainment", subcategory: "Radio", direction: "MINIMIZE",
    metricName: "First broadcast year of the longest continuously running U.S. radio program", unit: "year",
    formalStatement: "The earliest first-broadcast year of a U.S. radio program that has aired continuously since.",
    summary: "The Grand Ole Opry, the Nashville country music show on WSM, first aired as the WSM Barn Dance on November 28, 1925. It has been broadcast every week since, which makes it the longest-running radio broadcast in U.S. history.",
    value: "1925",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Broadcast history published by the Grand Ole Opry and the National Radio Hall of Fame.",
    source: { title: "Grand Ole Opry — History", url: "https://www.opry.com/history", date: "1925-11-28", location: "Nashville, Tennessee, USA" },
  },
  {
    registryNumber: "LR-FIRST-NOVEL-TALE-OF-GENJI", slug: "first-novel-tale-of-genji", title: "Earliest novel (The Tale of Genji)",
    category: "Arts & Entertainment", subcategory: "Literature & Publishing", direction: "MINIMIZE",
    metricName: "Approximate year of completion of the work often called the world's first novel", unit: "year",
    formalStatement: "The earliest date of a long prose narrative widely regarded as the first novel.",
    summary: "The Tale of Genji, written by the Japanese court lady Murasaki Shikibu in the early 11th century during the Heian period, is often called the world's first novel. It follows the life and loves of the courtier Hikaru Genji over 54 chapters and holds a place in Japanese literature like Shakespeare's in English.",
    value: "1010",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Scholarly dating places completion around 1008–1010; whether it is the 'first novel' depends on definition.",
    source: { title: "Encyclopaedia Britannica — The Tale of Genji", url: "https://www.britannica.com/topic/The-Tale-of-Genji", date: "1010-01-01", location: "Kyoto, Japan" },
  },
  {
    registryNumber: "LR-FIRST-BEST-PICTURE-WINNER", slug: "first-best-picture-winner", title: "First Academy Award for Best Picture",
    category: "Arts & Entertainment", subcategory: "Film Awards", direction: "MINIMIZE",
    metricName: "Year of the first Academy Awards ceremony honoring a best picture", unit: "year",
    formalStatement: "The earliest year in which the Academy Award for Best Picture was presented.",
    summary: "The silent war film Wings, directed by William Wellman, won the first Academy Award for the year's top picture (then called Outstanding Picture) at the first Oscars ceremony, held at the Hollywood Roosevelt Hotel on May 16, 1929 to honor films of 1927–1928.",
    value: "1929",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Academy of Motion Picture Arts and Sciences awards database.",
    source: { title: "Academy Awards — 1st Academy Awards", url: "https://www.oscars.org/oscars/ceremonies/1929", date: "1929-05-16", location: "Hollywood, California, USA" },
  },
  {
    registryNumber: "LR-FIRST-FEATURE-LENGTH-FILM", slug: "first-feature-length-film", title: "First feature-length narrative film",
    category: "Arts & Entertainment", subcategory: "Film History", direction: "MINIMIZE",
    metricName: "Release year of the first full-length narrative feature film", unit: "year",
    formalStatement: "The earliest release year of a full-length narrative feature film.",
    summary: "The Story of the Kelly Gang, an Australian film about the bushranger Ned Kelly, premiered in Melbourne in December 1906 and ran about an hour. UNESCO added it to the Memory of the World Register in 2007 as the world's first full-length narrative feature film. Only about 17 minutes of it survive.",
    value: "1906",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "UNESCO Memory of the World Register inscription (2007).",
    source: { title: "UNESCO Memory of the World — The Story of the Kelly Gang", url: "https://www.unesco.org/en/memory-world", date: "1906-12-26", location: "Melbourne, Australia" },
  },
  {
    registryNumber: "LR-FIRST-MUSIC-VIDEO-ON-MTV", slug: "first-music-video-on-mtv", title: "First music video shown on MTV",
    category: "Arts & Entertainment", subcategory: "Television", direction: "MINIMIZE",
    metricName: "Year MTV first broadcast a music video", unit: "year",
    formalStatement: "The earliest year in which MTV broadcast a music video, on its launch night.",
    summary: "MTV went on air in the United States at 12:01 a.m. on August 1, 1981. Its first music video was the Buggles' 'Video Killed the Radio Star', directed by Russell Mulcahy.",
    value: "1981",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Broadcast logs from MTV's launch night.",
    source: { title: "MTV", url: "https://www.mtv.com/", date: "1981-08-01", location: "United States" },
  },
  {
    registryNumber: "LR-FIRST-ARCADE-VIDEO-GAME", slug: "first-arcade-video-game", title: "First arcade video game",
    category: "Arts & Entertainment", subcategory: "Video Games", direction: "MINIMIZE",
    metricName: "Release year of the first commercially sold video game", unit: "year",
    formalStatement: "The earliest year in which a coin-operated arcade video game was released commercially.",
    summary: "Computer Space, created by Nolan Bushnell and Ted Dabney and released by Nutting Associates in 1971, was the first arcade video game and the first commercially available video game. It was based on the 1962 computer game Spacewar!, and Bushnell and Dabney went on to found Atari.",
    value: "1971",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Video game history as documented by the Strong National Museum of Play.",
    source: { title: "The Strong National Museum of Play — Computer Space", url: "https://www.museumofplay.org/", date: "1971-11-01", location: "Mountain View, California, USA" },
  },
  {
    registryNumber: "LR-FIRST-COMMERCIAL-COMPACT-DISC", slug: "first-commercial-compact-disc", title: "First commercial compact discs",
    category: "Arts & Entertainment", subcategory: "Music", direction: "MINIMIZE",
    metricName: "Year compact discs and CD players first went on sale", unit: "year",
    formalStatement: "The earliest year in which audio compact discs were released commercially.",
    summary: "The compact disc, developed by Philips and Sony, first went on sale in Japan in October 1982 alongside the Sony CDP-101, the first consumer CD player. CDs reached North America and Europe in March 1983. Billy Joel's 52nd Street was among the first titles released.",
    value: "1982",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Product launch history published by Sony and Philips.",
    source: { title: "Sony — History of the compact disc", url: "https://www.sony.com/en/SonyInfo/CorporateInfo/History/", date: "1982-10-01", location: "Japan" },
  },
  {
    registryNumber: "LR-MOST-WATCHED-SUPER-BOWL-HALFTIME-SHOW", slug: "most-watched-super-bowl-halftime-show", title: "Most-watched Super Bowl halftime show",
    category: "Arts & Entertainment", subcategory: "Television", direction: "MAXIMIZE",
    metricName: "U.S. TV audience of a single Super Bowl halftime show", unit: "viewers",
    formalStatement: "The greatest U.S. audience recorded for a Super Bowl halftime show.",
    summary: "Kendrick Lamar's halftime show at Super Bowl LIX in New Orleans on February 9, 2025 drew more than 133.5 million viewers, the most for any Super Bowl halftime show. Bad Bunny's Super Bowl LX show in 2026 drew 128.2 million across all platforms, the fourth-highest.",
    value: "133500000",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Nielsen audience measurement reported by the NFL and Apple Music.",
    source: { title: "NFL — Super Bowl LIX halftime show", url: "https://www.nfl.com/", date: "2025-02-09", location: "New Orleans, Louisiana, USA" },
  },
  {
    registryNumber: "LR-MOST-BILLBOARD-HOT-100-ENTRIES", slug: "most-billboard-hot-100-entries", title: "Most Billboard Hot 100 entries by an artist",
    category: "Arts & Entertainment", subcategory: "Music Charts", direction: "MAXIMIZE",
    metricName: "Number of songs by one act to enter the Billboard Hot 100", unit: "entries",
    formalStatement: "The greatest number of different songs by a single artist to appear on the Billboard Hot 100.",
    summary: "Canadian rapper Drake has placed 404 songs on the Billboard Hot 100, more than any other act. They include 241 top-40 hits, 90 top-10 hits and 14 number ones. He passed the Glee cast's total of 207 entries in 2021.",
    value: "404",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Billboard chart data; the total grows with new releases, as of 2026.",
    source: { title: "Billboard — Hot 100", url: "https://www.billboard.com/charts/hot-100/", date: "2026-10-05", location: "United States" },
  },
  {
    registryNumber: "LR-FIRST-NOBEL-PRIZE-IN-LITERATURE", slug: "first-nobel-prize-in-literature", title: "First Nobel Prize in Literature",
    category: "Arts & Entertainment", subcategory: "Literature & Publishing", direction: "MINIMIZE",
    metricName: "Year the Nobel Prize in Literature was first awarded", unit: "year",
    formalStatement: "The earliest year in which the Nobel Prize in Literature was awarded.",
    summary: "French poet and essayist Sully Prudhomme received the first Nobel Prize in Literature in 1901, 'in special recognition of his poetic composition, which gives evidence of lofty idealism, artistic perfection and a rare combination of the qualities of both heart and intellect'.",
    value: "1901",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Official laureate records of the Nobel Foundation.",
    source: { title: "NobelPrize.org — Nobel Prize in Literature 1901", url: "https://www.nobelprize.org/prizes/literature/1901/summary/", date: "1901-12-10", location: "Stockholm, Sweden" },
  },
  {
    registryNumber: "LR-OLDEST-RECORDING-OF-HUMAN-VOICE", slug: "oldest-recording-of-human-voice", title: "Oldest recognizable recording of the human voice",
    category: "Arts & Entertainment", subcategory: "Music", direction: "MINIMIZE",
    metricName: "Year of the oldest recognizable recording of a human voice", unit: "year",
    formalStatement: "The earliest year in which a human voice was recorded in a form that can be played back recognizably today.",
    summary: "In April 1860, French inventor Édouard-Léon Scott de Martinville recorded someone, probably himself, singing the folk song 'Au clair de la lune' on his phonautograph, which traced sound waves onto soot-blackened paper. The recording was never meant to be played back, but researchers converted it to audio in 2008. It is the oldest recognizable recording of a human voice and the oldest recorded music.",
    value: "1860",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Recovery and playback by the First Sounds initiative and Lawrence Berkeley National Laboratory (2008).",
    source: { title: "First Sounds — Phonautograms", url: "http://www.firstsounds.org/", date: "1860-04-09", location: "Paris, France" },
  },
  // --- Food & Culture ---
  {
    registryNumber: "LR-MOST-MICHELIN-STARS-HELD-BY-A-CHEF", slug: "most-michelin-stars-held-by-a-chef", title: "Most Michelin stars held by a chef",
    category: "Food & Culture", subcategory: "Food", direction: "MAXIMIZE",
    metricName: "Total Michelin Guide stars held across one chef's restaurants", unit: "stars",
    formalStatement: "The greatest total number of Michelin Guide stars held at once across a single chef's restaurants.",
    summary: "French chef Joël Robuchon held 31 Michelin stars across his restaurants in cities including Paris, Tokyo, Las Vegas, Hong Kong and Macau by the time of his death in 2018. No other chef or restaurateur has held more.",
    value: "31",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Michelin Guide star counts reported at the time of his death in August 2018.",
    source: { title: "Michelin Guide", url: "https://guide.michelin.com/", date: "2018-08-06", location: "Worldwide" },
  },
  {
    registryNumber: "LR-OLDEST-HOTEL", slug: "oldest-hotel", title: "Oldest hotel",
    category: "Food & Culture", subcategory: "Hospitality", direction: "MINIMIZE",
    metricName: "Founding year of the oldest hotel still operating", unit: "year",
    formalStatement: "The earliest founding year of a hotel that is still in operation.",
    summary: "Nishiyama Onsen Keiunkan, a hot-spring inn in Yamanashi Prefecture, Japan, was founded in 705 by Fujiwara no Mahito. Guinness World Records recognized it in 2011 as the oldest hotel in the world, and the same family has run it for more than 50 generations.",
    value: "705",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Guinness World Records certification (2011).",
    source: { title: "Guinness World Records — Oldest hotel", url: "https://www.guinnessworldrecords.com/", date: "0705-01-01", location: "Hayakawa, Yamanashi, Japan" },
  },
  {
    registryNumber: "LR-LARGEST-BEER-FESTIVAL", slug: "largest-beer-festival", title: "Largest beer festival",
    category: "Food & Culture", subcategory: "Festivals", direction: "MAXIMIZE",
    metricName: "Total visitors to a single edition of a beer festival", unit: "visitors",
    formalStatement: "The greatest number of visitors recorded at a single edition of a beer festival.",
    summary: "Munich's Oktoberfest, held on the Theresienwiese since 1810, is the world's largest Volksfest and beer festival and draws around seven million visitors a year. The 2023 festival set a record with 7.2 million visitors.",
    value: "7200000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Visitor estimates published by the City of Munich; attendance figures are estimates, not ticket counts.",
    source: { title: "Oktoberfest.de — Final report 2023", url: "https://www.oktoberfest.de/", date: "2023-10-03", location: "Munich, Germany" },
  },
  {
    registryNumber: "LR-LARGEST-DICTIONARY-BY-PAGES", slug: "largest-dictionary-by-pages", title: "Largest dictionary by number of pages",
    category: "Food & Culture", subcategory: "Languages", direction: "MAXIMIZE",
    metricName: "Number of printed pages in a single dictionary", unit: "pages",
    formalStatement: "The greatest number of printed pages in a single dictionary.",
    summary: "The Woordenboek der Nederlandsche Taal (Dictionary of the Dutch Language), begun in 1864 and finished in 1998, covers Dutch words from 1500 to 1976 in 43 volumes (including three supplements) and 49,255 pages, with 350,000 to 400,000 entries. It is believed to be the largest dictionary in the world by number of pages.",
    value: "49255",
    claimType: "CONSTRUCTION", epistemicStatus: "SOURCE_CONFIRMED", limitStatus: "OPEN",
    methodSummary: "Edition statistics published by the Instituut voor de Nederlandse Taal.",
    source: { title: "Instituut voor de Nederlandse Taal — WNT", url: "https://ivdnt.org/", date: "1998-06-01", location: "Leiden, Netherlands" },
  },
  {
    registryNumber: "LR-OLDEST-NATIONAL-ANTHEM", slug: "oldest-national-anthem", title: "Oldest national anthem",
    category: "Food & Culture", subcategory: "Traditions", direction: "MINIMIZE",
    metricName: "Year of composition of the oldest national anthem still in use", unit: "year",
    formalStatement: "The earliest composition date of a national anthem still in use, counting only anthems whose original melody and lyrics have existed together since then.",
    summary: "Het Wilhelmus, the national anthem of the Netherlands, dates back to at least 1572, during the Dutch revolt against Spain. It is the oldest national anthem in use when counting the original melody and lyrics together, though it only became the official anthem in 1932. Japan's Kimigayo has older lyrics but its melody dates from 1880.",
    value: "1572",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Musicological dating of the song; what counts as the 'oldest anthem' depends on whether lyrics, melody or official adoption is counted.",
    source: { title: "Government of the Netherlands — National anthem", url: "https://www.government.nl/", date: "1572-01-01", location: "Netherlands" },
  },
  {
    registryNumber: "LR-OLDEST-CONTINUOUSLY-USED-NATIONAL-FLAG", slug: "oldest-continuously-used-national-flag", title: "Oldest continuously used national flag",
    category: "Food & Culture", subcategory: "Traditions", direction: "MINIMIZE",
    metricName: "Year from which the oldest national flag has been in continuous documented use", unit: "year",
    formalStatement: "The earliest year from which a national flag has been in continuous use, as recognized by Guinness World Records.",
    summary: "Denmark's Dannebrog, a white Scandinavian cross on red, holds the Guinness World Record as the oldest continuously used national flag, in use since 1625. Legend says it fell from the sky during a battle in 1219, and the design appears in sources from the 14th century.",
    value: "1625",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Guinness World Records recognition; earlier dates depend on legend and fragmentary evidence.",
    source: { title: "Guinness World Records — Oldest continuously used national flag", url: "https://www.guinnessworldrecords.com/", date: "1625-01-01", location: "Denmark" },
  },
  {
    registryNumber: "LR-HIGHEST-BEER-CONSUMPTION-PER-CAPITA", slug: "highest-beer-consumption-per-capita", title: "Highest beer consumption per capita (country)",
    category: "Food & Culture", subcategory: "Drink", direction: "MAXIMIZE",
    metricName: "Annual beer consumption per person in a country", unit: "litres per person per year",
    formalStatement: "The greatest annual per-capita beer consumption of any country.",
    summary: "The Czech Republic drinks more beer per person than any other country, about 126 litres per person in 2024 according to the Czech Beer and Malt Association. It has topped the global rankings for decades; in Kirin's 2019 survey Austria, Romania and Germany followed.",
    value: "126",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "National industry association data for 2024 and Kirin Holdings global surveys; methods differ between sources.",
    source: { title: "Czech Beer and Malt Association", url: "https://ceske-pivo.cz/", date: "2024-12-31", location: "Czech Republic" },
  },
  {
    registryNumber: "LR-MOST-PRODUCED-GRAIN-CROP", slug: "most-produced-grain-crop", title: "Most-produced grain crop",
    category: "Food & Culture", subcategory: "Food", direction: "MAXIMIZE",
    metricName: "Annual world production of a single grain crop", unit: "tonnes",
    formalStatement: "The greatest annual world production, by weight, of any grain crop.",
    summary: "More maize (corn) is produced each year than any other grain. World production reached about 1.1 billion tonnes in 2020, more than wheat or rice, although much of it is used for animal feed and ethanol rather than eaten directly.",
    value: "1100000000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "FAO production statistics for 2020; annual totals vary with harvests.",
    source: { title: "FAO — FAOSTAT crop production", url: "https://www.fao.org/faostat/en/#data/QCL", date: "2020-12-31", location: "Worldwide" },
  },
  {
    registryNumber: "LR-LARGEST-COFFEE-PRODUCING-COUNTRY", slug: "largest-coffee-producing-country", title: "Largest coffee-producing country",
    category: "Food & Culture", subcategory: "Drink", direction: "MAXIMIZE",
    metricName: "Share of world green coffee production from a single country", unit: "%",
    formalStatement: "The greatest share of world green coffee production supplied by a single country.",
    summary: "Brazil is by far the world's largest coffee producer and grew 30.8% of the world's 11.1 million tonnes of green coffee in 2023. Vietnam (17.7%) and Indonesia (6.8%) were the next-largest producers.",
    value: "30.8",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "FAO production statistics for 2023.",
    source: { title: "FAO — FAOSTAT crop production", url: "https://www.fao.org/faostat/en/#data/QCL", date: "2023-12-31", location: "Brazil" },
  },
  {
    registryNumber: "LR-LARGEST-FOOD-FIGHT", slug: "largest-food-fight", title: "Largest food fight",
    category: "Food & Culture", subcategory: "Festivals", direction: "MAXIMIZE",
    metricName: "Number of participants in an annual food fight", unit: "participants",
    formalStatement: "The greatest number of participants in a single food-fight event.",
    summary: "La Tomatina in Buñol, near Valencia in Spain, held on the last Wednesday of August since the 1940s, is the biggest food fight in the world. Participants throw more than 100 tonnes of overripe tomatoes at each other in an hour. Since 2013 it has been a ticketed event capped at 20,000 participants.",
    value: "20000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Participant cap set by the Buñol town council since 2013; earlier editions drew larger, uncounted crowds.",
    source: { title: "La Tomatina — Buñol town council", url: "https://latomatina.info/", date: "2013-08-28", location: "Buñol, Valencia, Spain" },
  },
  {
    registryNumber: "LR-MOST-SPOKEN-CONSTRUCTED-LANGUAGE", slug: "most-spoken-constructed-language", title: "Most widely spoken constructed language",
    category: "Food & Culture", subcategory: "Languages", direction: "MAXIMIZE",
    metricName: "Estimated number of speakers of a constructed language", unit: "speakers",
    formalStatement: "The greatest number of speakers of any deliberately constructed language.",
    summary: "Esperanto, created by L. L. Zamenhof and published in 1887 as an international auxiliary language, is the most widely spoken constructed language in the world, with up to two million speakers by some estimates and perhaps a thousand or so native speakers.",
    value: "2000000",
    claimType: "CONSTRUCTION", epistemicStatus: "LITERATURE_ASSERTED", limitStatus: "OPEN",
    methodSummary: "Speaker numbers are rough estimates that vary widely between sources.",
    source: { title: "Universala Esperanto-Asocio", url: "https://uea.org/", date: "2026-10-05", location: "Worldwide" },
  },
];
