import type { Metadata } from "next";
import InfoPage from "../_components/InfoPage";
import { StatusGuide } from "../../src/components/status-guide";

export const metadata: Metadata = { title: "A public record of the boundaries of what is possible. — Limits Registry", description: "Limits Registry turns scattered bounds, constructions, proofs, and open gaps into durable records that researchers can inspect and cite." };

export default function Page() { return <InfoPage kicker="About" title="A public record of the boundaries of what is possible." intro="Limits Registry turns scattered bounds, constructions, proofs, and open gaps into durable records that researchers can inspect and cite."><h2>What we are building</h2><p>The Registry records what is known, what is achievable, what is ruled out, and where the gap remains open. Every published quantitative statement should be scoped to a specification and connected to evidence.</p>
<StatusGuide />
<h2>How a record works</h2><p>A Limit defines the question and specification. Claims assert lower bounds, upper bounds, exact values, constructions, or counterexamples. Evidence establishes those Claims, while independent Registry reviews determine whether they can contribute to the public frontier.</p><h2>Publication standard</h2><p>Only accepted Claims matching the current specification contribute to a displayed frontier. Corrections, disputes, supersessions, and invalidations remain in the history rather than being silently overwritten.</p><h2>Scope</h2><p>The Registry begins with mathematics and theoretical computer science and extends carefully into physics, quantum information, computing infrastructure, and empirical AI frontiers when the quantity, assumptions, and evidence can be represented precisely.</p><h2>Governance</h2><p>Registry status is editorial, not a substitute for scientific consensus. Reviewer identity, conflicts, decisions, evidence provenance, and audit events are retained so readers can inspect how a record reached its current state.</p><h2>What we are not</h2><p>We are not a paper publisher, a replacement for peer review, or an authority that settles active disputes by itself.</p><p><a href="/editorial-policy">Read the editorial policy →</a></p><p><a href="/methodology">How to propose, review, and certify a record →</a></p>
<h2>Contact</h2><p>For general questions, contact <a href="mailto:support@limitsregistry.com">support@limitsregistry.com</a>.</p>
</InfoPage>; }
