import type { Metadata } from "next";
import InfoPage from "../_components/InfoPage";

export const metadata: Metadata = { title: "A small, deliberate data footprint. — Limits Registry", description: "Limits Registry is designed to publish research records, not to build an advertising profile of its visitors." };

export default function Page() { return <InfoPage kicker="Privacy" title="A small, deliberate data footprint." intro="Limits Registry is designed to publish research records, not to build an advertising profile of its visitors."><h2>What we collect</h2><p>The public site does not require an account. Server logs may contain ordinary technical data such as IP address, user agent, request path, and request ID for security and reliability.</p>
<h2>How we use it</h2><p>We use operational data to protect the service, diagnose failures, and understand aggregate usage. We do not sell personal information or use advertising trackers.</p>
<h2>Sponsorship enquiries</h2><p>Regular sponsorship enquiries include your name, organisation, website, preferred placement, and message. These remain in the private administrator inbox for discussing a placement. Bounty sponsorship is a separate enquiry and review process.</p><p>We store the contact email and commercial details you provide so we can review your enquiry, quote a listing fee, and maintain invoice and payment records. Contact emails, listing fees, invoice references, and refund records are private to administrators. Approved bounty details and a paid sponsor link may be published under the agreed term. Commercial records are retained as needed for administration and applicable recordkeeping requirements.</p>
<h2>API pilot requests</h2><p>We store your name, email, organisation, intended use, and data requirements in our private administrator inbox to assess and respond to your request. For issued pilot keys, we keep commercial contact details and download-start counts for administration and service operations.</p>
<h2>API operational monitoring</h2><p>We count API origin requests by endpoint, response status, hour, and resolved customer key. Aggregates expire after 48 hours. To detect repeated failures, we use daily rotating keyed hashes of client IP addresses; detection counters expire after 15 minutes, and flagged signals are retained for up to 24 hours. Raw IP addresses, API tokens, request queries, and user agents are not stored in this monitoring data. Alert summaries may be sent to the administrator by email; email retention is separate from the short-lived counters.</p>
<h2>Contact and retention</h2><p>Support messages are retained only as long as needed to respond and maintain an editorial record. For privacy requests, contact <a href="mailto:support@limitsregistry.com">support@limitsregistry.com</a>.</p>
<h2>Important note</h2><p>This is a project policy, not legal advice. Have counsel review it before production launch in each jurisdiction where the service operates.</p>
</InfoPage>; }
