import { bigint, boolean, check, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid, vector } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { customType } from "drizzle-orm/pg-core";

const bytea = customType<{ data: Buffer; driverData: Buffer }>({ dataType: () => "bytea" });

export const directionEnum = pgEnum("direction", ["MINIMIZE", "MAXIMIZE"]);
export const limitStatusEnum = pgEnum("limit_status", ["DRAFT", "OPEN", "PROVEN", "DISPUTED", "RETIRED"]);
export const claimStatusEnum = pgEnum("claim_status", ["DRAFT", "UNDER_REVIEW", "ACCEPTED", "REJECTED", "DISPUTED", "INVALIDATED"]);
export const claimRelationEnum = pgEnum("claim_relation", ["<", "<=", "=", ">=", ">"]);
export const claimTypeEnum = pgEnum("claim_type", ["UPPER_BOUND", "LOWER_BOUND", "EXACT_VALUE", "CONSTRUCTION", "COUNTEREXAMPLE", "ASYMPTOTIC_BOUND", "COMPUTATIONAL_BOUND"]);
export const epistemicStatusEnum = pgEnum("epistemic_status", ["LITERATURE_ASSERTED", "SOURCE_CONFIRMED", "REPRODUCED", "PROVEN", "FORMALLY_PROVEN", "EMPIRICALLY_SUPPORTED", "DISPUTED", "INVALIDATED"]);
export const evidenceTypeEnum = pgEnum("evidence_type", ["PAPER", "FORMAL_PROOF", "SOURCE_CODE", "DATASET", "EXHAUSTIVE_COMPUTATION", "EXPERIMENT", "REPRODUCTION", "OTHER"]);
const audit = { createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() };

export const limits = pgTable("limits", { id: uuid("id").defaultRandom().primaryKey(), registryNumber: text("registry_number").notNull().unique(), slug: text("slug").notNull().unique(), title: text("title").notNull(), summary: text("summary").notNull(), category: text("category").notNull(), subcategory: text("subcategory"), direction: directionEnum("direction").notNull(), metricName: text("metric_name").notNull(), unit: text("unit"), status: limitStatusEnum("status").default("DRAFT").notNull(), publishedAt: timestamp("published_at", { withTimezone: true }), ...audit }, (t) => [index("limits_category_idx").on(t.category), index("limits_status_idx").on(t.status)]);
export const specificationVersions = pgTable("limit_spec_versions", { id: uuid("id").defaultRandom().primaryKey(), limitId: uuid("limit_id").references(() => limits.id).notNull(), versionNumber: integer("version_number").notNull(), formalStatement: text("formal_statement").notNull(), constraints: jsonb("constraints").$type<Record<string, unknown>>().notNull(), assumptions: jsonb("assumptions").$type<Record<string, unknown>>().notNull(), asymptotic: boolean("asymptotic").default(false).notNull(), probabilistic: boolean("probabilistic").default(false).notNull(), supersedesVersionId: uuid("supersedes_version_id"), ...audit }, (t) => [uniqueIndex("limit_spec_version_unique").on(t.limitId, t.versionNumber)]);
export const claims = pgTable("claims", { id: uuid("id").defaultRandom().primaryKey(), claimNumber: text("claim_number").notNull().unique(), specificationVersionId: uuid("specification_version_id").references(() => specificationVersions.id).notNull(), claimType: claimTypeEnum("claim_type").notNull(), relation: claimRelationEnum("relation").notNull(), valueExact: text("value_exact").notNull(), valueNumeric: bigint("value_numeric", { mode: "bigint" }), valueText: text("value_text"), unit: text("unit"), scopeParameters: jsonb("scope_parameters").$type<Record<string, unknown>>().notNull(), epistemicStatus: epistemicStatusEnum("epistemic_status").notNull(), status: claimStatusEnum("status").default("DRAFT").notNull(), methodSummary: text("method_summary"), supersedesClaimId: uuid("supersedes_claim_id"), invalidatesClaimId: uuid("invalidates_claim_id"), ...audit }, (t) => [index("claims_spec_idx").on(t.specificationVersionId), index("claims_status_idx").on(t.status)]);
export const papers = pgTable("papers", { id: uuid("id").defaultRandom().primaryKey(), title: text("title").notNull(), abstract: text("abstract"), publicationDate: timestamp("publication_date", { withTimezone: true }), venue: text("venue"), doi: text("doi"), arxivId: text("arxiv_id"), publisherUrl: text("publisher_url"), ...audit }, (t) => [uniqueIndex("papers_doi_unique").on(t.doi)]);
export const people = pgTable("people", { id: uuid("id").defaultRandom().primaryKey(), displayName: text("display_name").notNull(), normalizedName: text("normalized_name").notNull(), orcid: text("orcid"), website: text("website"), profileStatus: text("profile_status").default("UNCLAIMED").notNull(), ...audit }, (t) => [index("people_name_idx").on(t.normalizedName)]);
// limitId is optional and separate from claim_evidence: it lets a Limit cite a general source (e.g.
// an OPEN record with no accepted claim yet) without inventing a claim just to anchor the citation.
export const evidence = pgTable("evidence", { id: uuid("id").defaultRandom().primaryKey(), type: evidenceTypeEnum("type").notNull(), label: text("label").notNull(), url: text("url"), location: text("location"), limitId: uuid("limit_id").references(() => limits.id), metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull(), ...audit });
export const claimEvidence = pgTable("claim_evidence", { claimId: uuid("claim_id").references(() => claims.id).notNull(), evidenceId: uuid("evidence_id").references(() => evidence.id).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex("claim_evidence_unique").on(t.claimId, t.evidenceId)]);
export const claimPapers = pgTable("claim_papers", { claimId: uuid("claim_id").references(() => claims.id).notNull(), paperId: uuid("paper_id").references(() => papers.id).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex("claim_papers_unique").on(t.claimId, t.paperId)]);
export const reviews = pgTable("reviews", { id: uuid("id").defaultRandom().primaryKey(), claimId: uuid("claim_id").references(() => claims.id).notNull(), reviewerUserId: text("reviewer_user_id").references(() => user.id).notNull(), decision: text("decision").notNull(), rationale: text("rationale").notNull(), conflictDisclosed: boolean("conflict_disclosed").notNull(), ...audit }, (t) => [index("reviews_claim_idx").on(t.claimId), uniqueIndex("reviews_claim_reviewer_unique").on(t.claimId, t.reviewerUserId)]);
export const timelineEvents = pgTable("timeline_events", { id: uuid("id").defaultRandom().primaryKey(), limitId: uuid("limit_id").references(() => limits.id).notNull(), claimId: uuid("claim_id").references(() => claims.id), eventType: text("event_type").notNull(), title: text("title").notNull(), description: text("description"), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(), metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("timeline_limit_date_idx").on(t.limitId, t.occurredAt)]);
export const auditLogs = pgTable("audit_logs", { id: uuid("id").defaultRandom().primaryKey(), actorUserId: text("actor_user_id").references(() => user.id), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id").notNull(), before: jsonb("before"), after: jsonb("after"), reason: text("reason"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("audit_entity_idx").on(t.entityType, t.entityId)]);

// --- V3: submissions, verification, reproduction, and follows ---
export const submissionTypeEnum = pgEnum("submission_type", ["BETTER_ACHIEVABLE_RESULT", "STRONGER_BOUND", "PROOF", "REPRODUCTION", "CORRECTION"]);
export const submissionStatusEnum = pgEnum("submission_status", ["SUBMITTED", "UNDER_REVIEW", "ACCEPTED", "REJECTED", "NEEDS_REVISION"]);
// Authenticated public submissions (master spec §39-40). A submission never writes to `claims`
// directly — accepting one is a manual editorial action, same draft-only posture as candidateClaims.
export const submissions = pgTable("submissions", { id: uuid("id").defaultRandom().primaryKey(), submitterUserId: text("submitter_user_id").references(() => user.id).notNull(), limitId: uuid("limit_id").references(() => limits.id).notNull(), submissionType: submissionTypeEnum("submission_type").notNull(), title: text("title").notNull(), description: text("description").notNull(), proposedRelation: claimRelationEnum("proposed_relation"), proposedValueExact: text("proposed_value_exact"), evidenceUrl: text("evidence_url"), status: submissionStatusEnum("status").default("SUBMITTED").notNull(), reviewedByUserId: text("reviewed_by_user_id").references(() => user.id), reviewerNotes: text("reviewer_notes"), ...audit }, (t) => [index("submissions_status_idx").on(t.status), index("submissions_limit_idx").on(t.limitId)]);
export const proofAttachments = pgTable("proof_attachments", { id: uuid("id").defaultRandom().primaryKey(), submissionId: uuid("submission_id").references(() => submissions.id, { onDelete: "cascade" }).notNull().unique(), filename: text("filename").notNull(), mimeType: text("mime_type").notNull(), sizeBytes: integer("size_bytes").notNull(), contents: bytea("contents").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const verifications = pgTable("verifications", { id: uuid("id").defaultRandom().primaryKey(), claimId: uuid("claim_id").references(() => claims.id).notNull(), verifierType: text("verifier_type").notNull(), input: jsonb("input").$type<Record<string, unknown>>().notNull(), result: jsonb("result").$type<Record<string, unknown>>().notNull(), status: text("status").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("verifications_claim_idx").on(t.claimId)]);
export const reproductions = pgTable("reproductions", { id: uuid("id").defaultRandom().primaryKey(), claimId: uuid("claim_id").references(() => claims.id).notNull(), evidenceId: uuid("evidence_id").references(() => evidence.id), method: text("method").notNull(), result: text("result").notNull(), artifactUrl: text("artifact_url"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("reproductions_claim_idx").on(t.claimId)]);
export const follows = pgTable("follows", { id: uuid("id").defaultRandom().primaryKey(), limitId: uuid("limit_id").references(() => limits.id).notNull(), subscriberKey: text("subscriber_key").notNull(), email: text("email").notNull(), frequency: text("frequency").default("WEEKLY").notNull(), enabled: boolean("enabled").default(true).notNull(), unsubscribedAt: timestamp("unsubscribed_at", { withTimezone: true }), ...audit }, (t) => [uniqueIndex("follows_limit_subscriber_unique").on(t.limitId, t.subscriberKey), index("follows_subscriber_idx").on(t.subscriberKey), index("follows_delivery_idx").on(t.enabled, t.frequency), check("follows_frequency_valid", sql`${t.frequency} in ('INSTANT', 'WEEKLY')`)]);
export const claimFollows = pgTable("claim_follows", { id: uuid("id").defaultRandom().primaryKey(), claimNumber: text("claim_number").references(() => claims.claimNumber).notNull(), subscriberKey: text("subscriber_key").notNull(), email: text("email").notNull(), enabled: boolean("enabled").default(true).notNull(), ...audit }, (t) => [uniqueIndex("claim_follows_claim_subscriber_unique").on(t.claimNumber, t.subscriberKey), index("claim_follows_subscriber_idx").on(t.subscriberKey)]);
export const notifications = pgTable("notifications", { id: uuid("id").defaultRandom().primaryKey(), followId: uuid("follow_id").references(() => follows.id).notNull(), watchlistEventId: uuid("watchlist_event_id"), eventType: text("event_type").notNull(), payload: jsonb("payload").$type<Record<string, unknown>>() .notNull(), status: text("status").default("PENDING").notNull(), attempts: integer("attempts").default(0).notNull(), nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true }).defaultNow().notNull(), lastError: text("last_error"), providerMessageId: text("provider_message_id"), deliveredAt: timestamp("delivered_at", { withTimezone: true }), ...audit }, (t) => [index("notifications_follow_idx").on(t.followId), index("notifications_delivery_idx").on(t.status, t.nextAttemptAt), uniqueIndex("notifications_follow_event_unique").on(t.followId, t.watchlistEventId), check("notifications_status_valid", sql`${t.status} in ('PENDING', 'SENDING', 'SENT', 'FAILED')`)]);

// --- V2: authentication (Better Auth core tables) ---
export const roleEnum = pgEnum("user_role", ["USER", "RESEARCHER", "REVIEWER", "EDITOR", "ADMIN", "SUPERADMIN"]);
export const user = pgTable("user", { id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: boolean("email_verified").default(false).notNull(), image: text("image"), role: roleEnum("role").default("USER").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const session = pgTable("session", { id: text("id").primaryKey(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), token: text("token").notNull().unique(), ipAddress: text("ip_address"), userAgent: text("user_agent"), userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("session_user_idx").on(t.userId)]);
export const account = pgTable("account", { id: text("id").primaryKey(), issuer: text("issuer").notNull(), accountId: text("account_id").notNull(), providerId: text("provider_id").notNull(), userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }), accessToken: text("access_token"), refreshToken: text("refresh_token"), idToken: text("id_token"), accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }), refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }), scope: text("scope"), password: text("password"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex("account_issuer_account_unique").on(t.issuer, t.accountId), index("account_user_idx").on(t.userId)]);
export const verification = pgTable("verification", { id: text("id").primaryKey(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow() }, (t) => [index("verification_identifier_idx").on(t.identifier)]);

// --- V2: institutions and attribution ---
export const institutions = pgTable("institutions", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), country: text("country"), website: text("website"), type: text("type"), ...audit }, (t) => [index("institutions_name_idx").on(t.name)]);
export const personInstitutions = pgTable("person_institutions", { personId: uuid("person_id").references(() => people.id).notNull(), institutionId: uuid("institution_id").references(() => institutions.id).notNull(), roleLabel: text("role_label"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex("person_institutions_unique").on(t.personId, t.institutionId)]);
export const contributorRoleEnum = pgEnum("contributor_role", ["PROBLEM_ORIGINATOR", "DISCOVERER", "RECORD_SETTER", "BOUND_AUTHOR", "PROOF_AUTHOR", "FORMALIZER", "REPRODUCER", "VERIFIER", "DATASET_AUTHOR", "IMPLEMENTER", "EDITOR"]);
export const claimPeople = pgTable("claim_people", { claimId: uuid("claim_id").references(() => claims.id).notNull(), personId: uuid("person_id").references(() => people.id).notNull(), contributorRole: contributorRoleEnum("contributor_role").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex("claim_people_unique").on(t.claimId, t.personId, t.contributorRole)]);
export const claimInstitutions = pgTable("claim_institutions", { claimId: uuid("claim_id").references(() => claims.id).notNull(), institutionId: uuid("institution_id").references(() => institutions.id).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex("claim_institutions_unique").on(t.claimId, t.institutionId)]);

// --- V2: reviewer assignments ---
export const reviewerAssignmentStatusEnum = pgEnum("reviewer_assignment_status", ["ASSIGNED", "COMPLETED", "DECLINED"]);
export const reviewerAssignments = pgTable("reviewer_assignments", { id: uuid("id").defaultRandom().primaryKey(), claimId: uuid("claim_id").references(() => claims.id).notNull(), reviewerUserId: text("reviewer_user_id").references(() => user.id).notNull(), status: reviewerAssignmentStatusEnum("status").default("ASSIGNED").notNull(), conflictDisclosed: boolean("conflict_disclosed").default(false).notNull(), assignedByUserId: text("assigned_by_user_id").references(() => user.id), ...audit }, (t) => [index("reviewer_assignments_claim_idx").on(t.claimId), uniqueIndex("reviewer_assignments_unique").on(t.claimId, t.reviewerUserId)]);

// Self-reported expertise/credentials for the REVIEWER+ role (master spec §45). Never presented
// as independently verified — see the "not verified" framing everywhere this is displayed.
export const authorProfiles = pgTable("author_profiles", { userId: text("user_id").references(() => user.id, { onDelete: "cascade" }).primaryKey(), affiliation: text("affiliation"), orcid: text("orcid"), website: text("website"), ...audit });
export const reviewerProfiles = pgTable("reviewer_profiles", { userId: text("user_id").primaryKey().references(() => user.id, { onDelete: "cascade" }), fieldsOfExpertise: jsonb("fields_of_expertise").$type<string[]>().notNull(), credentials: text("credentials"), bio: text("bio"), ...audit });

// --- V2: draft-only AI extraction output (never published directly; see AGENTS: AI may not publish) ---
export const candidateClaimStatusEnum = pgEnum("candidate_claim_status", ["PENDING_REVIEW", "PROMOTED", "DISMISSED"]);
export const candidateClaims = pgTable("candidate_claims", { id: uuid("id").defaultRandom().primaryKey(), paperId: uuid("paper_id").references(() => papers.id), limitId: uuid("limit_id").references(() => limits.id), extraction: jsonb("extraction").$type<Record<string, unknown>>().notNull(), model: text("model").notNull(), promptVersion: text("prompt_version").notNull(), confidence: text("confidence"), status: candidateClaimStatusEnum("status").default("PENDING_REVIEW").notNull(), reviewedByUserId: text("reviewed_by_user_id").references(() => user.id), promotedClaimId: uuid("promoted_claim_id").references(() => claims.id), ...audit }, (t) => [index("candidate_claims_paper_idx").on(t.paperId), index("candidate_claims_status_idx").on(t.status)]);


// V3: immutable certificates for accepted Claims and record changes
export const certificates = pgTable("certificates", { id: uuid("id").defaultRandom().primaryKey(), certificateNumber: text("certificate_number").notNull().unique(), certificateType: text("certificate_type").notNull(), claimId: uuid("claim_id").references(() => claims.id).notNull(), recordHash: text("record_hash").notNull(), signature: text("signature"), signatureAlgorithm: text("signature_algorithm").default("SHA-256").notNull(), snapshot: jsonb("snapshot").$type<Record<string, unknown>>().notNull(), status: text("status").default("ACTIVE").notNull(), issuedByUserId: text("issued_by_user_id").references(() => user.id), issuedAt: timestamp("issued_at", { withTimezone: true }).defaultNow().notNull(), supersededAt: timestamp("superseded_at", { withTimezone: true }) }, (t) => [index("certificates_claim_idx").on(t.claimId), index("certificates_hash_idx").on(t.recordHash)]);

// --- V3: admin dashboard — site controls, inbound messages, outbound admin email log ---
export const announcementLevelEnum = pgEnum("announcement_level", ["INFO", "WARNING", "CRITICAL"]);
// Singleton row (id fixed to "global") holding maintenance-mode and site-announcement state,
// read on every page via a short-lived cache (see src/db/repository.settings.ts) rather than
// once per request from proxy.ts — see AGENTS.md-linked Next docs on avoiding DB reads there.
export const siteSettings = pgTable("site_settings", { id: text("id").primaryKey(), maintenanceEnabled: boolean("maintenance_enabled").default(false).notNull(), maintenanceMessage: text("maintenance_message"), announcementEnabled: boolean("announcement_enabled").default(false).notNull(), announcementMessage: text("announcement_message"), announcementLevel: announcementLevelEnum("announcement_level").default("INFO").notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(), updatedByUserId: text("updated_by_user_id").references(() => user.id) });

export const inboxChannelEnum = pgEnum("inbox_channel", ["CONTACT", "SUPPORT"]);
export const inboxStatusEnum = pgEnum("inbox_status", ["OPEN", "RESOLVED"]);
// Inbound messages from the public /contact and /support forms. No submitter account required —
// this is the public's only way to reach the team without going through email directly.
export const inboxMessages = pgTable("inbox_messages", { id: uuid("id").defaultRandom().primaryKey(), channel: inboxChannelEnum("channel").notNull(), name: text("name").notNull(), email: text("email").notNull(), subject: text("subject"), message: text("message").notNull(), status: inboxStatusEnum("status").default("OPEN").notNull(), replyBody: text("reply_body"), repliedAt: timestamp("replied_at", { withTimezone: true }), repliedByUserId: text("replied_by_user_id").references(() => user.id), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("inbox_messages_channel_idx").on(t.channel)]);

// Audit trail for the admin "compose and send" tool — not a general outbound-email log (auth
// emails and the weekly digest aren't recorded here, only admin-initiated arbitrary sends).
export const adminSentEmails = pgTable("admin_sent_emails", { id: uuid("id").defaultRandom().primaryKey(), toEmail: text("to_email").notNull(), subject: text("subject").notNull(), heading: text("heading").notNull(), body: text("body").notNull(), footerNote: text("footer_note"), sentByUserId: text("sent_by_user_id").references(() => user.id).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });

// Research infrastructure records. All are draft/review-gated until an editor accepts them.
export const dependencyRelations = pgTable("limit_dependencies", { id: uuid("id").defaultRandom().primaryKey(), sourceLimitId: uuid("source_limit_id").references(() => limits.id).notNull(), targetLimitId: uuid("target_limit_id").references(() => limits.id).notNull(), relation: text("relation").notNull(), evidenceClaimId: uuid("evidence_claim_id").references(() => claims.id), reviewStatus: text("review_status").default("DRAFT").notNull(), ...audit }, (t) => [
  index("dependencies_source_idx").on(t.sourceLimitId), index("dependencies_target_idx").on(t.targetLimitId), index("dependencies_public_idx").on(t.reviewStatus, t.sourceLimitId, t.targetLimitId), uniqueIndex("dependencies_unique_edge_idx").on(t.sourceLimitId, t.targetLimitId, t.relation),
  check("dependencies_no_self_edge", sql`${t.sourceLimitId} <> ${t.targetLimitId}`), check("dependencies_relation_valid", sql`${t.relation} in ('REDUCES_TO', 'DEPENDS_ON', 'IMPROVES', 'GENERALIZES')`), check("dependencies_review_status_valid", sql`${t.reviewStatus} in ('DRAFT', 'ACCEPTED', 'REJECTED')`),
]);
export const verificationArtifacts = pgTable("verification_artifacts", { id: uuid("id").defaultRandom().primaryKey(), claimId: uuid("claim_id").references(() => claims.id).notNull(), verifier: text("verifier").notNull(), repositoryUrl: text("repository_url").notNull(), commitHash: text("commit_hash").notNull(), verifierVersion: text("verifier_version"), buildResult: text("build_result").default("NOT_RUN").notNull(), verificationLevel: text("verification_level").default("ARTIFACT_LINKED").notNull(), reviewStatus: text("review_status").default("DRAFT").notNull(), reviewedByUserId: text("reviewed_by_user_id"), reviewRationale: text("review_rationale"), ...audit }, (t) => [index("artifacts_claim_idx").on(t.claimId), index("artifacts_review_idx").on(t.reviewStatus), check("artifacts_verifier_valid", sql`${t.verifier} in ('LEAN4', 'COQ', 'ISABELLE', 'SAT_SOLVER')`), check("artifacts_commit_hash_valid", sql`${t.commitHash} ~ '^[0-9a-fA-F]{40}$'`), check("artifacts_review_status_valid", sql`${t.reviewStatus} in ('DRAFT', 'ACCEPTED', 'REJECTED')`), check("artifacts_level_valid", sql`${t.verificationLevel} in ('ARTIFACT_LINKED', 'REPRODUCED', 'MACHINE_CHECKED')`)]);
export const verifierExecutions = pgTable("verifier_executions", { id: uuid("id").defaultRandom().primaryKey(), artifactId: uuid("artifact_id").references(() => verificationArtifacts.id).notNull(), verifier: text("verifier").notNull(), command: text("command").notNull(), toolVersion: text("tool_version").notNull(), exitCode: integer("exit_code").notNull(), status: text("status").notNull(), reproducible: boolean("reproducible").default(false).notNull(), outputSummary: text("output_summary").notNull(), outputDigest: text("output_digest").notNull(), executedByUserId: text("executed_by_user_id").notNull(), startedAt: timestamp("started_at", { withTimezone: true }).notNull(), completedAt: timestamp("completed_at", { withTimezone: true }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("executions_artifact_idx").on(t.artifactId, t.createdAt), check("executions_status_valid", sql`${t.status} in ('PASSED', 'FAILED', 'REJECTED')`)]);
export const semanticDocuments = pgTable("semantic_documents", {
  id: uuid("id").defaultRandom().primaryKey(), entityType: text("entity_type").notNull(), entityId: text("entity_id").notNull(),
  registryNumber: text("registry_number"), title: text("title").notNull(), content: text("content").notNull(), contentHash: text("content_hash").notNull(),
  embeddingModel: text("embedding_model").notNull(), embedding: vector("embedding", { dimensions: 1536 }), embeddingStatus: text("embedding_status").default("PENDING").notNull(),
  embeddingError: text("embedding_error"), lastEmbeddedAt: timestamp("last_embedded_at", { withTimezone: true }), ...audit,
}, (t) => [uniqueIndex("semantic_entity_unique").on(t.entityType, t.entityId), index("semantic_registry_idx").on(t.registryNumber), index("semantic_status_idx").on(t.embeddingStatus), index("semantic_embedding_hnsw_idx").using("hnsw", t.embedding.op("vector_cosine_ops"))]);
export const breakthroughEvents = pgTable("breakthrough_events", { id: uuid("id").defaultRandom().primaryKey(), limitId: uuid("limit_id").references(() => limits.id).notNull(), claimId: uuid("claim_id").references(() => claims.id), eventType: text("event_type").notNull(), acceptedOnly: boolean("accepted_only").default(true).notNull(), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(), ...audit }, (t) => [index("breakthrough_limit_idx").on(t.limitId)]);
export const watchlistEvents = pgTable("watchlist_events", { id: uuid("id").defaultRandom().primaryKey(), limitId: uuid("limit_id").references(() => limits.id).notNull(), eventType: text("event_type").notNull(), sourceEntityType: text("source_entity_type").notNull(), sourceEntityId: text("source_entity_id").notNull(), payload: jsonb("payload").$type<Record<string, unknown>>() .notNull(), publishedAt: timestamp("published_at", { withTimezone: true }), ...audit }, (t) => [index("watchlist_events_limit_idx").on(t.limitId), uniqueIndex("watchlist_event_source_unique").on(t.sourceEntityType, t.sourceEntityId, t.eventType)]);
export const researchBounties = pgTable("research_bounties", { id: uuid("id").defaultRandom().primaryKey(), limitId: uuid("limit_id").references(() => limits.id), title: text("title").notNull(), sponsor: text("sponsor").notNull(), description: text("description").notNull(), sourceUrl: text("source_url").notNull(), status: text("status").default("UNVERIFIED").notNull(), amount: text("amount"), currency: text("currency"), expiresAt: timestamp("expires_at", { withTimezone: true }), submittedByUserId: text("submitted_by_user_id"), verifiedByUserId: text("verified_by_user_id"), moderationNote: text("moderation_note"), verifiedAt: timestamp("verified_at", { withTimezone: true }), ...audit }, (t) => [index("bounties_limit_idx").on(t.limitId), index("bounties_status_idx").on(t.status), index("bounties_public_idx").on(t.status, t.expiresAt), check("bounties_status_valid", sql`${t.status} in ('UNVERIFIED', 'VERIFIED', 'REJECTED', 'WITHDRAWN')`), check("bounties_currency_valid", sql`${t.currency} is null or ${t.currency} ~ '^[A-Z]{3}$'`), check("bounties_amount_valid", sql`${t.amount} is null or (${t.amount} ~ '^[0-9]+(\\.[0-9]{1,2})?$' and ${t.amount}::numeric > 0)`), check("bounties_amount_currency_paired", sql`(${t.amount} is null and ${t.currency} is null) or (${t.amount} is not null and ${t.currency} is not null)`), check("bounties_source_https_valid", sql`${t.sourceUrl} ~ '^https://[^[:space:]]+$'`)]);

// Durable source ingestion queue. Workers claim due rows with SKIP LOCKED; extracted text is not retained.
export const sourceIngestionJobs = pgTable("source_ingestion_jobs", {
  id: uuid("id").defaultRandom().primaryKey(), paperId: uuid("paper_id").references(() => papers.id, { onDelete: "cascade" }).notNull(), limitId: uuid("limit_id").references(() => limits.id), requestedByUserId: text("requested_by_user_id").notNull(), sourceType: text("source_type").notNull(), sourceUrl: text("source_url").notNull(), finalSourceUrl: text("final_source_url"), status: text("status").default("QUEUED").notNull(), attempts: integer("attempts").default(0).notNull(), maxAttempts: integer("max_attempts").default(3).notNull(), pageCount: integer("page_count"), byteSize: integer("byte_size"), extractedCharacterCount: integer("extracted_character_count"), errorCode: text("error_code"), errorMessage: text("error_message"), nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true }).defaultNow().notNull(), startedAt: timestamp("started_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), ...audit,
}, (t) => [
  index("source_jobs_due_idx").on(t.status, t.nextAttemptAt), uniqueIndex("source_jobs_active_unique").on(t.paperId).where(sql`${t.status} in ('QUEUED', 'PROCESSING', 'RETRY_WAIT')`), index("source_jobs_paper_idx").on(t.paperId, t.createdAt),
  check("source_jobs_type_valid", sql`${t.sourceType} in ('ARXIV', 'DOI_PUBLISHER')`), check("source_jobs_status_valid", sql`${t.status} in ('QUEUED', 'PROCESSING', 'RETRY_WAIT', 'SUCCEEDED', 'FAILED')`), check("source_jobs_attempts_valid", sql`${t.attempts} >= 0 and ${t.maxAttempts} between 1 and 10 and ${t.attempts} <= ${t.maxAttempts}`), check("source_jobs_counts_valid", sql`(${t.pageCount} is null or ${t.pageCount} > 0) and (${t.byteSize} is null or ${t.byteSize} > 0) and (${t.extractedCharacterCount} is null or ${t.extractedCharacterCount} > 0)`), check("source_jobs_source_https_valid", sql`${t.sourceUrl} ~ '^https://[^[:space:]]+$'`),
]);
