import { bigint, boolean, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

export const directionEnum = pgEnum("direction", ["MINIMIZE", "MAXIMIZE"]);
export const limitStatusEnum = pgEnum("limit_status", ["DRAFT", "OPEN", "PROVEN", "DISPUTED", "RETIRED"]);
export const claimStatusEnum = pgEnum("claim_status", ["DRAFT", "UNDER_REVIEW", "ACCEPTED", "REJECTED", "DISPUTED", "INVALIDATED"]);
export const claimRelationEnum = pgEnum("claim_relation", ["<", "<=", "=", ">=", ">"]);
export const claimTypeEnum = pgEnum("claim_type", ["UPPER_BOUND", "LOWER_BOUND", "EXACT_VALUE", "CONSTRUCTION", "COUNTEREXAMPLE", "ASYMPTOTIC_BOUND", "COMPUTATIONAL_BOUND"]);
export const epistemicStatusEnum = pgEnum("epistemic_status", ["LITERATURE_ASSERTED", "SOURCE_CONFIRMED", "REPRODUCED", "PROVEN", "FORMALLY_PROVEN", "EMPIRICALLY_SUPPORTED", "DISPUTED", "INVALIDATED"]);
export const evidenceTypeEnum = pgEnum("evidence_type", ["PAPER", "FORMAL_PROOF", "SOURCE_CODE", "DATASET", "EXHAUSTIVE_COMPUTATION", "EXPERIMENT", "REPRODUCTION", "OTHER"]);
const audit = { createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() };

export const limits = pgTable("limits", { id: uuid("id").defaultRandom().primaryKey(), registryNumber: text("registry_number").notNull().unique(), slug: text("slug").notNull().unique(), title: text("title").notNull(), summary: text("summary").notNull(), category: text("category").notNull(), subcategory: text("subcategory"), direction: directionEnum("direction").notNull(), metricName: text("metric_name").notNull(), unit: text("unit"), status: limitStatusEnum("status").default("DRAFT").notNull(), publishedAt: timestamp("published_at", { withTimezone: true }), ...audit }, (t) => [index("limits_category_idx").on(t.category), index("limits_status_idx").on(t.status)]);
export const specificationVersions = pgTable("limit_spec_versions", { id: uuid("id").defaultRandom().primaryKey(), limitId: uuid("limit_id").references(() => limits.id).notNull(), versionNumber: integer("version_number").notNull(), formalStatement: text("formal_statement").notNull(), constraints: jsonb("constraints").$type<Record<string, unknown>>().notNull(), assumptions: jsonb("assumptions").$type<Record<string, unknown>>().notNull(), asymptotic: boolean("asymptotic").default(false).notNull(), probabilistic: boolean("probabilistic").default(false).notNull(), supersedesVersionId: uuid("supersedes_version_id"), ...audit }, (t) => [uniqueIndex("limit_spec_version_unique").on(t.limitId, t.versionNumber)]);
export const claims = pgTable("claims", { id: uuid("id").defaultRandom().primaryKey(), claimNumber: text("claim_number").notNull().unique(), specificationVersionId: uuid("specification_version_id").references(() => specificationVersions.id).notNull(), claimType: claimTypeEnum("claim_type").notNull(), relation: claimRelationEnum("relation").notNull(), valueExact: text("value_exact").notNull(), valueNumeric: bigint("value_numeric", { mode: "bigint" }), valueText: text("value_text"), unit: text("unit"), scopeParameters: jsonb("scope_parameters").$type<Record<string, unknown>>().notNull(), epistemicStatus: epistemicStatusEnum("epistemic_status").notNull(), status: claimStatusEnum("status").default("DRAFT").notNull(), methodSummary: text("method_summary"), supersedesClaimId: uuid("supersedes_claim_id"), invalidatesClaimId: uuid("invalidates_claim_id"), ...audit }, (t) => [index("claims_spec_idx").on(t.specificationVersionId), index("claims_status_idx").on(t.status)]);
export const papers = pgTable("papers", { id: uuid("id").defaultRandom().primaryKey(), title: text("title").notNull(), abstract: text("abstract"), publicationDate: timestamp("publication_date", { withTimezone: true }), venue: text("venue"), doi: text("doi"), arxivId: text("arxiv_id"), publisherUrl: text("publisher_url"), ...audit }, (t) => [uniqueIndex("papers_doi_unique").on(t.doi)]);
export const people = pgTable("people", { id: uuid("id").defaultRandom().primaryKey(), displayName: text("display_name").notNull(), normalizedName: text("normalized_name").notNull(), orcid: text("orcid"), website: text("website"), profileStatus: text("profile_status").default("UNCLAIMED").notNull(), ...audit }, (t) => [index("people_name_idx").on(t.normalizedName)]);
export const evidence = pgTable("evidence", { id: uuid("id").defaultRandom().primaryKey(), type: evidenceTypeEnum("type").notNull(), label: text("label").notNull(), url: text("url"), location: text("location"), metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull(), ...audit });
export const claimEvidence = pgTable("claim_evidence", { claimId: uuid("claim_id").references(() => claims.id).notNull(), evidenceId: uuid("evidence_id").references(() => evidence.id).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex("claim_evidence_unique").on(t.claimId, t.evidenceId)]);
export const claimPapers = pgTable("claim_papers", { claimId: uuid("claim_id").references(() => claims.id).notNull(), paperId: uuid("paper_id").references(() => papers.id).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex("claim_papers_unique").on(t.claimId, t.paperId)]);
export const reviews = pgTable("reviews", { id: uuid("id").defaultRandom().primaryKey(), claimId: uuid("claim_id").references(() => claims.id).notNull(), reviewerUserId: uuid("reviewer_user_id").notNull(), decision: text("decision").notNull(), rationale: text("rationale").notNull(), conflictDisclosed: boolean("conflict_disclosed").notNull(), ...audit }, (t) => [index("reviews_claim_idx").on(t.claimId)]);
export const timelineEvents = pgTable("timeline_events", { id: uuid("id").defaultRandom().primaryKey(), limitId: uuid("limit_id").references(() => limits.id).notNull(), claimId: uuid("claim_id").references(() => claims.id), eventType: text("event_type").notNull(), title: text("title").notNull(), description: text("description"), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(), metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("timeline_limit_date_idx").on(t.limitId, t.occurredAt)]);
export const auditLogs = pgTable("audit_logs", { id: uuid("id").defaultRandom().primaryKey(), actorUserId: uuid("actor_user_id"), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: uuid("entity_id").notNull(), before: jsonb("before"), after: jsonb("after"), reason: text("reason"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("audit_entity_idx").on(t.entityType, t.entityId)]);


export const submissions = pgTable("submissions", { id: uuid("id").defaultRandom().primaryKey(), title: text("title").notNull(), description: text("description").notNull(), submitterEmail: text("submitter_email"), status: text("status").default("RECEIVED").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("submissions_status_idx").on(t.status)]);
export const verifications = pgTable("verifications", { id: uuid("id").defaultRandom().primaryKey(), claimId: uuid("claim_id").references(() => claims.id).notNull(), verifierType: text("verifier_type").notNull(), input: jsonb("input").$type<Record<string, unknown>>().notNull(), result: jsonb("result").$type<Record<string, unknown>>().notNull(), status: text("status").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("verifications_claim_idx").on(t.claimId)]);
export const reproductions = pgTable("reproductions", { id: uuid("id").defaultRandom().primaryKey(), claimId: uuid("claim_id").references(() => claims.id).notNull(), evidenceId: uuid("evidence_id").references(() => evidence.id), method: text("method").notNull(), result: text("result").notNull(), artifactUrl: text("artifact_url"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("reproductions_claim_idx").on(t.claimId)]);
export const follows = pgTable("follows", { id: uuid("id").defaultRandom().primaryKey(), limitId: uuid("limit_id").references(() => limits.id).notNull(), subscriberKey: text("subscriber_key").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex("follows_limit_subscriber_unique").on(t.limitId, t.subscriberKey)]);
export const notifications = pgTable("notifications", { id: uuid("id").defaultRandom().primaryKey(), followId: uuid("follow_id").references(() => follows.id).notNull(), eventType: text("event_type").notNull(), payload: jsonb("payload").$type<Record<string, unknown>>().notNull(), deliveredAt: timestamp("delivered_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("notifications_follow_idx").on(t.followId)]);
