import { NextResponse } from "next/server";
import { timingSafeEqual } from "node:crypto";
import { sql } from "drizzle-orm";
import { db } from "../../../../src/db/client";

export const runtime = "nodejs";
export const maxDuration = 60;

function authorized(request: Request) {
  const expected = process.env.CRON_SECRET;
  const header = request.headers.get("authorization") ?? "";
  const provided = header.startsWith("Bearer ") ? header.slice(7) : "";
  if (!expected || !provided || provided.length !== expected.length) return false;
  return timingSafeEqual(Buffer.from(provided), Buffer.from(expected));
}

// Verbatim published abstracts researched for the genuine academic papers cited by published
// limits (reference/database sources like Wikipedia, OEIS, MIPLIB, and TOP500 have no real
// abstract and are deliberately excluded). Matched onto evidence rows by exact source URL and
// merged into evidence.metadata rather than a schema change.
const ABSTRACTS: { url: string; abstract: string; abstractSourceUrl: string }[] = [
  { url: "https://doi.org/10.1147/RD.53.0183", abstractSourceUrl: "https://worrydream.com/refs/Landauer_1961_-_Irreversibility_and_Heat_Generation_in_the_Computing_Process.pdf", abstract: "It is argued that computing machines inevitably involve devices which perform logical functions that do not have a single-valued inverse. This logical irreversibility is associated with physical irreversibility and requires a minimal heat generation, per machine cycle, typically of the order of kT for each irreversible function. This dissipation serves the purpose of standardizing signals and making them independent of their exact logical history. Two simple, but representative, models of bistable devices are subjected to a more detailed analysis of switching kinetics to yield the relationship between speed and energy dissipation, and to estimate the effects of errors induced by thermal fluctuations." },
  { url: "https://journals.aps.org/prd/abstract/10.1103/PhysRevD.23.287", abstractSourceUrl: "https://ui.adsabs.harvard.edu/abs/1981PhRvD..23..287B/abstract", abstract: "We present evidence for the existence of a universal upper bound of magnitude 2πR/ℏc to the entropy-to-energy ratio S/E of an arbitrary system of effective radius R. For systems with negligible self-gravity, the bound follows from application of the second law of thermodynamics to a gedanken experiment involving a black hole. Direct statistical arguments are also discussed. A microcanonical approach of Gibbons illustrates for simple systems (gravitating and not) the reason behind the bound, and the connection of R with the longest dimension of the system. A more general approach establishes the bound for a relativistic field system contained in a cavity of arbitrary shape, or in a closed universe. Black holes also comply with the bound; in fact they actually attain it. Thus, as long suspected, black holes have the maximum entropy for given mass and size which is allowed by quantum theory and general relativity." },
  { url: "https://www.sciencedirect.com/science/article/pii/S0167278998000542", abstractSourceUrl: "https://arxiv.org/abs/quant-ph/9710043", abstract: "We discuss the problem of counting the maximum number of distinct states that an isolated physical system can pass through in a given period of time---its maximum speed of dynamical evolution. Previous analyses have given bounds in terms of the standard deviation of the energy of the system; here we give a strict bound that depends only on E-E0, the system's average energy minus its ground state energy. We also discuss bounds on information processing rates implied by our bound on the speed of dynamical evolution. For example, adding one Joule of energy to a given computer can never increase its processing rate by more than about 3x10^33 operations per second." },
  { url: "https://doi.org/10.1109/T-AIEE.1928.5055024", abstractSourceUrl: "https://bayes.wustl.edu/Manual/CertainTopicsInTelegraphTransmissionTheory.pdf", abstract: "The most obvious method for determining the distortion of telegraph signals is to calculate the transients of the telegraph system. This method has been treated by various writers, and solutions are available for telegraph lines with simple terminal conditions. It is well known that the extension of the same methods to more complicated terminal conditions, which represent the usual terminal apparatus, leads to great difficulties. The present paper attacks the same problem from the alternative standpoint of the steady-state characteristics of the system. This method has the advantage over the method of transients that the complication of the circuit which results from the use of terminal apparatus does not complicate the calculations materially. This method of treatment necessitates expressing the criteria of distortionless transmission in terms of the steady-state characteristics. Accordingly, a considerable portion of the paper describes and illustrates a method for making this translation. A discussion is given of the minimum frequency range required for transmission at a given speed of signaling. In the case of carrier telegraphy, this discussion includes a comparison of single-sideband and double-sideband transmission. A number of incidental topics is also discussed." },
  { url: "https://www.mathnet.ru/eng/ppi/v9/i3/p3", abstractSourceUrl: "https://www.mathnet.ru/eng/ppi/v9/i3/p3", abstract: "Certain bounds are derived for the quantity of information transmitted by a quantum channel. It is proved that if at least two of the set of density operators ρ₀,…,ρₙ do not commute, then J(π) < ℋ(∑ₐπₐρₐ) - ∑ₐπₐℋ(ρₐ), where J(π) is the upper bound of the quantity of information with respect to all generalized measurements at the channel output for a fixed distribution π=(π₀,…,πₙ) at the input. A sharper upper bound for J(π) is explicitly stated." },
  { url: "https://www.nature.com/articles/299802a0", abstractSourceUrl: "https://ui.adsabs.harvard.edu/abs/1982Natur.299..802W/abstract", abstract: "It is demonstrated that the linearity of quantum mechanics forbids the amplification of an arbitrary polarization. In particular the case of photon-atom collisions producing stimulated emission of a photon having the same polarization as that of the ingoing photon, is examined. The practical interest in replicating individual photons is stressed." },
  { url: "https://geodesic.mathdoc.fr/articles/10.4007/annals.2008.168.1/", abstractSourceUrl: "https://arxiv.org/abs/math/0309430", abstract: "The kissing number problem asks for the maximal number k(n) of equal size nonoverlapping spheres in n-dimensional space that can touch another sphere of the same size. This problem in dimension three was the subject of a famous discussion between Isaac Newton and David Gregory in 1694. In three dimensions the problem was finally solved only in 1953 by Schütte and van der Waerden. In this paper we present a solution of a long-standing problem about the kissing number in four dimensions. Namely, the equality k(4)=24 is proved. The proof is based on a modification of Delsarte's method." },
  { url: "https://annals.math.princeton.edu/2017/185-3/p07", abstractSourceUrl: "https://arxiv.org/abs/1603.04246", abstract: "In this paper we prove that no packing of unit balls in Euclidean space ℝ⁸ has density greater than that of the E₈-lattice packing." },
  { url: "https://pubsonline.informs.org/doi/10.1287/opre.2022.2338", abstractSourceUrl: "https://arxiv.org/abs/2007.01409", abstract: "For some $\\epsilon > 10^{-36}$ we give a randomized $3/2-\\epsilon$ approximation algorithm for metric TSP." },
  { url: "https://epubs.siam.org/doi/pdf/10.1137/1.9781611978322.63", abstractSourceUrl: "https://arxiv.org/abs/2307.07970", abstract: "The main contribution of this paper is a new improved variant of the laser method for designing matrix multiplication algorithms. Building upon the recent techniques of [Duan, Wu, Zhou, FOCS 2023], the new method introduces several new ingredients that not only yield an improved bound on the matrix multiplication exponent $\\omega$, but also improve the known bounds on rectangular matrix multiplication by [Le Gall and Urrutia, SODA 2018]. In particular, the new bound on $\\omega$ is $\\omega\\le 2.371552$ (improved from $\\omega\\le 2.371866$). For the dual matrix multiplication exponent $\\alpha$ defined as the largest $\\alpha$ for which $\\omega(1,\\alpha,1)=2$, we obtain the improvement $\\alpha \\ge 0.321334$ (improved from $\\alpha \\ge 0.31389$). Similar improvements are obtained for various other exponents for multiplying rectangular matrices." },
  { url: "https://arxiv.org/abs/1405.5754", abstractSourceUrl: "https://arxiv.org/abs/1405.5754", abstract: "This paper describes a computer-assisted non-existence proof of nine-input sorting networks consisting of 24 comparators, hence showing that the 25-comparator sorting network found by Floyd in 1964 is optimal. As a corollary, we obtain that the 29-comparator network found by Waksman in 1969 is optimal when sorting ten inputs.\nThis closes the two smallest open instances of the optimal size sorting network problem, which have been open since the results of Floyd and Knuth from 1966 proving optimality for sorting networks of up to eight inputs.\nThe proof involves a combination of two methodologies: one based on exploiting the abundance of symmetries in sorting networks, and the other, based on an encoding of the problem to that of satisfiability of propositional logic. We illustrate that, while each of these can single handed solve smaller instances of the problem, it is their combination which leads to an efficient solution for nine inputs." },
  { url: "https://www.combinatorics.org/ojs/index.php/eljc/article/view/DS1", abstractSourceUrl: "https://www.combinatorics.org/ojs/index.php/eljc/article/view/DS1", abstract: "We present data which, to the best of our knowledge, includes all known nontrivial values and bounds for specific graph, hypergraph and multicolor Ramsey numbers, where the avoided graphs are complete or complete without one edge. Many results pertaining to other more studied cases are also presented. We give references to all cited bounds and values, as well as to previous similar compilations. We do not attempt complete coverage of asymptotic behavior of Ramsey numbers, but concentrate on their specific values." },
  { url: "https://arxiv.org/abs/2203.15556", abstractSourceUrl: "https://arxiv.org/abs/2203.15556", abstract: "We investigate the optimal model size and number of tokens for training a transformer language model under a given compute budget. We find that current large language models are significantly undertrained, a consequence of the recent focus on scaling language models whilst keeping the amount of training data constant. By training over 400 language models ranging from 70 million to over 16 billion parameters on 5 to 500 billion tokens, we find that for compute-optimal training, the model size and the number of training tokens should be scaled equally: for every doubling of model size the number of training tokens should also be doubled. We test this hypothesis by training a predicted compute-optimal model, Chinchilla, that uses the same compute budget as Gopher but with 70B parameters and 4× more more data. Chinchilla uniformly and significantly outperforms Gopher (280B), GPT-3 (175B), Jurassic-1 (178B), and Megatron-Turing NLG (530B) on a large range of downstream evaluation tasks. This also means that Chinchilla uses substantially less compute for fine-tuning and inference, greatly facilitating downstream usage. As a highlight, Chinchilla reaches a state-of-the-art average accuracy of 67.5% on the MMLU benchmark, greater than a 7% improvement over Gopher." },
  { url: "https://arxiv.org/abs/2205.14135", abstractSourceUrl: "https://arxiv.org/abs/2205.14135", abstract: "Transformers are slow and memory-hungry on long sequences, since the time and memory complexity of self-attention are quadratic in sequence length. Approximate attention methods have attempted to address this problem by trading off model quality to reduce the compute complexity, but often do not achieve wall-clock speedup. We argue that a missing principle is making attention algorithms IO-aware -- accounting for reads and writes between levels of GPU memory. We propose FlashAttention, an IO-aware exact attention algorithm that uses tiling to reduce the number of memory reads/writes between GPU high bandwidth memory (HBM) and GPU on-chip SRAM. We analyze the IO complexity of FlashAttention, showing that it requires fewer HBM accesses than standard attention, and is optimal for a range of SRAM sizes. We also extend FlashAttention to block-sparse attention, yielding an approximate attention algorithm that is faster than any existing approximate attention method. FlashAttention trains Transformers faster than existing baselines: 15% end-to-end wall-clock speedup on BERT-large (seq. length 512) compared to the MLPerf 1.1 training speed record, 3× speedup on GPT-2 (seq. length 1K), and 2.4× speedup on long-range arena (seq. length 1K-4K). FlashAttention and block-sparse FlashAttention enable longer context in Transformers, yielding higher quality models (0.7 better perplexity on GPT-2 and 6.4 points of lift on long-document classification) and entirely new capabilities: the first Transformers to achieve better-than-chance performance on the Path-X challenge (seq. length 16K, 61.4% accuracy) and Path-256 (seq. length 64K, 63.1% accuracy)." },
  { url: "https://arxiv.org/abs/2307.03172", abstractSourceUrl: "https://arxiv.org/abs/2307.03172", abstract: "While recent language models have the ability to take long contexts as input, relatively little is known about how well they use longer context. We analyze the performance of language models on two tasks that require identifying relevant information in their input contexts: multi-document question answering and key-value retrieval. We find that performance can degrade significantly when changing the position of relevant information, indicating that current language models do not robustly make use of information in long input contexts. In particular, we observe that performance is often highest when relevant information occurs at the beginning or end of the input context, and significantly degrades when models must access relevant information in the middle of long contexts, even for explicitly long-context models. Our analysis provides a better understanding of how language models use their input context and provides new evaluation protocols for future long-context language models." },
  { url: "https://www.science.org/doi/10.1126/science.aaj2038", abstractSourceUrl: "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=DOI:10.1126/science.aaj2038&format=json&resultType=core", abstract: "DNA is an attractive medium to store digital information. Here we report a storage strategy, called DNA Fountain, that is highly robust and approaches the information capacity per nucleotide. Using our approach, we stored a full computer operating system, movie, and other files with a total of 2.14 × 10^6 bytes in DNA oligonucleotides and perfectly retrieved the information from a sequencing coverage equivalent to a single tile of Illumina sequencing. We also tested a process that can allow 2.18 × 10^15 retrievals using the original DNA sample and were able to perfectly decode the data. Finally, we explored the limit of our architecture in terms of bytes per molecule and obtained a perfect retrieval from a density of 215 petabytes per gram of DNA, orders of magnitude higher than previous reports." },
  { url: "https://pubmed.ncbi.nlm.nih.gov/18635798/", abstractSourceUrl: "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=18635798&rettype=abstract&retmode=text", abstract: "We measured the elastic properties and intrinsic breaking strength of free-standing monolayer graphene membranes by nanoindentation in an atomic force microscope. The force-displacement behavior is interpreted within a framework of nonlinear elastic stress-strain response, and yields second- and third-order elastic stiffnesses of 340 newtons per meter (N m(-1)) and -690 Nm(-1), respectively. The breaking strength is 42 N m(-1) and represents the intrinsic strength of a defect-free sheet. These quantities correspond to a Young's modulus of E = 1.0 terapascals, third-order elastic stiffness of D = -2.0 terapascals, and intrinsic strength of sigma(int) = 130 gigapascals for bulk graphite. These experiments establish graphene as the strongest material ever measured, and show that atomically perfect nanoscale materials can be mechanically tested to deformations well beyond the linear regime." },
  { url: "https://pubmed.ncbi.nlm.nih.gov/18374559/", abstractSourceUrl: "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=EXT_ID:18374559%20AND%20SRC:MED&format=json&resultType=core", abstract: "Photosynthesis is the source of our food and fiber. Increasing world population, economic development, and diminishing land resources forecast that a doubling of productivity is critical in meeting agricultural demand before the end of this century. A starting point for evaluating the global potential to meet this goal is establishing the maximum efficiency of photosynthetic solar energy conversion. The potential efficiency of each step of the photosynthetic process from light capture to carbohydrate synthesis is examined. This reveals the maximum conversion efficiency of solar energy to biomass is 4.6% for C3 photosynthesis at 30 degrees C and today's 380 ppm atmospheric [CO2], but 6% for C4 photosynthesis. This advantage over C3 will disappear as atmospheric [CO2] nears 700 ppm." },
  { url: "https://repository.ias.ac.in/70320/", abstractSourceUrl: "https://repository.ias.ac.in/70320/", abstract: "The theory of the polytropic gas spheres in conjunction with the equation of state of a relativistically degenerate electron-gas leads to a unique value for the mass of a star built on this model. This mass (=0.91 ⊚) is interpreted as representing the upper limit to the mass of an ideal white dwarf." },
];

export async function POST(request: Request) {
  if (!authorized(request)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  let updated = 0;
  const missing: string[] = [];
  for (const item of ABSTRACTS) {
    const result = await db.execute(sql`
      update evidence set metadata = metadata || ${JSON.stringify({ abstract: item.abstract, abstractSourceUrl: item.abstractSourceUrl })}::jsonb, updated_at = now()
      where url = ${item.url}
      returning id
    `);
    if (result.length) updated += result.length; else missing.push(item.url);
  }
  return NextResponse.json({ status: "ok", papersConsidered: ABSTRACTS.length, rowsUpdated: updated, urlsNotFound: missing });
}
