import Link from "next/link";
import { getCanonicalRecord } from "../../../src/domain/canonical";
import { getPublishedLimit } from "../../../src/domain/published";
import { getPublishedDomainLimit, getLimitResearchData } from "../../../src/db/repository";
import CopyCitationButton from "./CopyCitationButton";

type PageProps = { params: Promise<{ id: string }> };

const claims = [
  ["CLM-000184", "L ≥ 5", "CONSTRUCTION / LOWER BOUND", "de Grey, 2018", "SOURCE_CONFIRMED"],
  ["CLM-000208", "L ≤ 7", "UPPER BOUND", "Exoo & Ismailescu, 2019", "PROVEN"],
  ["CLM-000119", "L ≥ 4", "LOWER BOUND", "Erdős, Ko, and Rado, 1950", "PROVEN"],
];

export default async function LimitPage({ params }: PageProps) {
  const { id } = await params;
  const fallback = getPublishedLimit(id) ?? getCanonicalRecord(id);
  const databaseLimit = await getPublishedDomainLimit(id).catch(() => null);
  const record = databaseLimit ? { ...fallback, id: databaseLimit.id, title: databaseLimit.title, summary: databaseLimit.summary, category: databaseLimit.category.toUpperCase() } : fallback;
  const research = databaseLimit ? await getLimitResearchData(databaseLimit.id).catch(() => ({ specification: null, claims: [], evidence: [] })) : null;
  const citation = `Limits Registry. ${record.id}. ${record.title}. ${new Date().getUTCFullYear()}.`;
  return <main className="canonical-page">
    <header className="canonical-header"><Link className="brand" href="/"><span className="brand-mark"><i /><i /><i /></span><span>Limits Registry</span></Link><nav><Link href="/">Browse</Link><Link href="#claims">Claims</Link><Link href="#specification">Specification</Link><Link href="#evidence">Evidence</Link></nav><span className="header-tag">PUBLIC RECORD</span></header>
    <section className="canonical-intro"><div className="canonical-category">{record.category}</div><div className="canonical-id-row"><span className="canonical-id">{record.id}</span><span className="canonical-status">OPEN LIMIT</span></div><h1>{record.title}</h1><p>{record.summary}</p><div className="intro-foot"><span>Specification version 2</span><span>Last updated May 12, 2025</span><span>19 cited papers</span></div></section>
    <section className="knowledge-section"><div className="section-title"><span>01</span><h2>What we know</h2><p>Current frontiers derived from accepted Claims.</p></div><div className={`frontier ${record.gap === "Asymptotic" ? "asymptotic" : "integer"}`}><div className="frontier-labels"><span>PROVEN LOWER BOUND</span><span>BEST CONSTRUCTION</span></div><div className="frontier-values"><strong>{record.achievable}</strong><div className="frontier-line"><i /><span>UNKNOWN GAP</span><i /></div><strong>{record.bound}</strong></div><div className="frontier-foot"><span>Achievable frontier</span><span>{record.gap}</span><span>Proven bound</span></div></div></section>
    <section className="canonical-columns"><div className="canonical-main"><div className="section-title" id="claims"><span>02</span><h2>Claims</h2><p>Assertions tied to evidence, attribution, and review.</p></div><div className="claims-table">{claims.map(([claimId, relation, kind, author, status], i) => <article className="public-claim" key={claimId}><div className="claim-year">{i === 0 ? "2018" : i === 1 ? "2019" : "1950"}</div><div className="public-claim-copy"><span className="public-claim-id">{claimId}</span><strong>{relation}</strong><span>{kind}</span><small>{author}</small><small>Evidence: original paper · Review: {status === "PROVEN" ? "Proven" : "Source confirmed"}</small></div><span className={`public-status ${status.toLowerCase()}`}>{status.replaceAll("_", " ")}</span></article>)}</div><div className="section-title lower-title" id="timeline"><span>03</span><h2>Timeline</h2><p>The frontier as it changed over time.</p></div><div className="frontier-explanation" role="note"><strong>How this frontier is derived</strong><p>Only accepted Claims matching the current specification contribute to the displayed bounds. Strict inequalities remain open; contradictory Claims require editorial review.</p></div><div className="history"><div><span>1950</span><strong>First lower bound established</strong><small>Erdős, Ko, and Rado</small></div><div><span>2018</span><strong>Construction reaches 5</strong><small>de Grey · Source confirmed</small></div><div><span>2019</span><strong>Upper bound improved to 7</strong><small>Exoo &amp; Ismailescu · Proven</small></div></div></div><aside className="canonical-aside"><div className="aside-block" id="specification"><span className="aside-label">Specification</span><h3>What question is being asked?</h3><p>{record.summary}</p><p className="spec-constraints">Constraints: {research?.specification ? Object.entries(research.specification.constraints).map(([key, value]) => `${key}=${value}`).join(" · ") : "Current published scope"}</p><Link href="#claims">Read full specification <span>↗</span></Link></div><div className="aside-block" id="history"><span className="aside-label">Corrections & disputes</span><h3>Record history</h3><p>No unresolved corrections or disputes are recorded for this published version.</p><Link href="#timeline">View timeline <span>↗</span></Link></div><div className="aside-block" id="evidence"><span className="aside-label">Editorial status</span><h3>Evidence-backed record</h3><p>2 independent reviews completed. Current frontier accepted May 12, 2025.</p><div className="review-meter"><span /><span /></div><small>Human-reviewed · No AI-only claims</small></div><div className="aside-block citation"><span className="aside-label">Cite this Limit</span><code>{citation}</code><CopyCitationButton citation={citation} /></div></aside></section>
    <footer><span>LR / 2026</span><span>Evidence before assertion.</span><span className="footer-links"><Link href="/about">About</Link><Link href="/disclaimer">Disclaimer</Link><Link href="/support">Support</Link><Link href="/">Back to Browse ↗</Link></span></footer>
  </main>;
}
