/** Publishes source-backed Ramsey, kissing-number, and sphere-packing records. */
import "dotenv/config";
import postgres from "postgres";
import { mathematicsFoundationRecords } from "../src/catalog/mathematics-foundations";
const connectionString=process.env.DATABASE_URL;if(!connectionString)throw new Error("DATABASE_URL is required.");
const sql=postgres(connectionString,{prepare:false,max:2});let inserted=0,skippedExisting=0;
async function main(){try{for(const record of mathematicsFoundationRecords){
  const [sameTitle]=await sql`select id,registry_number,status from limits where lower(title)=lower(${record.title}) limit 1`;if(sameTitle){if(!["OPEN","PROVEN"].includes(sameTitle.status))throw new Error(`Existing ${record.title} is not public.`);skippedExisting++;continue;}
  if((await sql`select id from limits where registry_number=${record.registryNumber} or slug=${record.slug} limit 1`).length)throw new Error(`Catalog collision for ${record.registryNumber}/${record.slug}.`);
  let paper;if(record.source.doi){[paper]=await sql`select id from papers where doi=${record.source.doi} or title=${record.source.title} limit 1`;}else{[paper]=await sql`select id from papers where title=${record.source.title} limit 1`;}
  if(!paper)[paper]=await sql`insert into papers (title,abstract,publication_date,venue,doi,publisher_url) values (${record.source.title},${"Authoritative theorem or maintained mathematical survey supporting the registered value or bounds."},${new Date(`${record.source.date}T00:00:00Z`)},${record.source.venue},${record.source.doi??null},${record.source.url}) returning id`;
  await sql.begin(async tx=>{const publishedAt=new Date(`${record.source.date}T00:00:00Z`);const [limit]=await tx`insert into limits (registry_number,slug,title,summary,category,subcategory,direction,metric_name,unit,status,published_at) values (${record.registryNumber},${record.slug},${record.title},${record.summary},${"Mathematics"},${record.subcategory},${record.direction},${record.metricName},${record.unit},${record.status},${publishedAt}) returning id`;const [spec]=await tx`insert into limit_spec_versions (limit_id,version_number,formal_statement,constraints,assumptions) values (${limit.id},1,${record.formalStatement},${tx.json(record.constraints as postgres.JSONValue)},${tx.json({kind:"MATHEMATICAL_THEOREM_OR_OPEN_BOUND",sourceUrl:record.source.url,publicationProcess:"AUTHORITATIVE_MATHEMATICS_IMPORT"})}) returning id`;
    const claimIds:string[]=[];for(let i=0;i<record.claims.length;i++){const item=record.claims[i];const [claim]=await tx`insert into claims (claim_number,specification_version_id,claim_type,relation,value_exact,value_text,unit,scope_parameters,epistemic_status,status,method_summary) values (${`CLM-MATH-${record.registryNumber.slice(3)}-${i+1}`},${spec.id},${item.claimType},${item.relation},${item.value},${item.value},${record.unit},${tx.json({sourceLocation:record.source.location,sourceVersion:record.source.date})},${"PROVEN"},${"ACCEPTED"},${item.summary}) returning id`;claimIds.push(claim.id);const [evidence]=await tx`insert into evidence (type,label,url,location,metadata) values (${"PAPER"},${`${record.source.title} — ${record.title} ${item.relation} ${item.value}`},${record.source.url},${record.source.location},${tx.json({doi:record.source.doi??null,relation:item.relation,value:item.value,verificationLevel:"SOURCE_CONFIRMED"})}) returning id`;await tx`insert into claim_evidence (claim_id,evidence_id) values (${claim.id},${evidence.id})`;await tx`insert into claim_papers (claim_id,paper_id) values (${claim.id},${paper.id})`;await tx`insert into audit_logs (action,entity_type,entity_id,before,after,reason) values (${"AUTHORITATIVE_MATHEMATICS_CLAIM_ACCEPTED"},${"CLAIM"},${claim.id},${tx.json({status:"SOURCE_IMPORT"})},${tx.json({status:"ACCEPTED",relation:item.relation,value:item.value})},${`Verified against ${record.source.title}.`})`;}
    await tx`insert into timeline_events (limit_id,claim_id,event_type,title,description,occurred_at,metadata) values (${limit.id},${claimIds[0]},${"MATHEMATICAL_RESULT_PUBLISHED"},${record.status==="PROVEN"?"Exact result established":"Current best interval established"},${record.summary},${publishedAt},${tx.json({publicationState:"PUBLIC",source:record.source.url})})`;await tx`insert into audit_logs (action,entity_type,entity_id,before,after,reason) values (${"AUTHORITATIVE_MATHEMATICS_LIMIT_PUBLISHED"},${"LIMIT"},${limit.id},${tx.json({status:"SOURCE_IMPORT"})},${tx.json({status:record.status,publishedAt:publishedAt.toISOString()})},${`Source-backed publication from ${record.source.venue}.`})`;});inserted++;}
  const [counts]=await sql`select count(*) filter(where category='Mathematics' and status in ('OPEN','PROVEN','DISPUTED','RETIRED'))::int as "mathematicsCount",count(*) filter(where status in ('OPEN','PROVEN','DISPUTED','RETIRED'))::int as "publicCount" from limits`;console.log(JSON.stringify({inserted,skippedExisting,catalogRecords:mathematicsFoundationRecords.length,...counts}));}finally{await sql.end();}}
void main().catch(error=>{console.error(error);process.exitCode=1;});
