import type { Metadata } from "next";
import { PublicHeader } from "../../src/components/public-header";
import { SiteFooter } from "../../src/components/site-footer";
import { DependencyGraph } from "../../src/components/dependency-graph";
import { listAcceptedDependencies } from "../../src/db/repository.research";
import "./dependencies.css";
export const revalidate = 60;
export const metadata: Metadata = { title: "Dependency Graph — Limits Registry", description: "Reviewed reductions and dependencies between published Limits." };
export default async function DependenciesPage() {
  const edges = await listAcceptedDependencies();
  const nodes = [...new Map(edges.flatMap((edge) => [[edge.source.id, edge.source], [edge.target.id, edge.target]])).values()];
  return <main className="dependencies-page"><PublicHeader /><section className="dependencies-intro"><p className="section-kicker">Reviewed knowledge graph</p><h1>How Limits depend on one another.</h1><p>Directed links show accepted reductions and dependencies between published Registry records. Draft and rejected submissions are never shown here.</p></section><section className="graph-explanation" aria-labelledby="graph-explanation-title"><div><p className="section-kicker">How to read it</p><h2 id="graph-explanation-title">A map of relationships between Limits.</h2><p>Each box is a published Limit. Follow an arrow from its source to the related target to see how one result connects to another. The graph records relationships between questions, not rankings between researchers or records.</p></div><div className="graph-explanation-grid"><article><strong>Reduces to</strong><p>Solving the target would solve the source problem.</p></article><article><strong>Depends on</strong><p>The source result relies on the target result or prerequisite.</p></article><article><strong>Improves</strong><p>The source reports a stronger result or frontier than the target.</p></article><article><strong>Generalizes</strong><p>The source extends the target to a broader setting or class.</p></article></div><p className="graph-review-note">Only accepted links appear here. Draft, rejected, and unsupported relationships stay out of the public graph.</p></section><section className="dependencies-canvas"><div className="dependencies-meta">{nodes.length} Limits · {edges.length} accepted links</div><DependencyGraph nodes={nodes} edges={edges}/>{edges.length === 0 ? <div className="graph-guide"><article><strong>What belongs here?</strong><p>Accepted reductions, prerequisite relationships, and result dependencies between published Limits.</p></article><article><strong>Why is it reviewed?</strong><p>A false dependency can misrepresent an entire field, so draft links stay private until an editor accepts their evidence.</p></article><article><strong>Where are submissions made?</strong><p>Researchers submit candidate links through the Research Console. Public pages show accepted relationships only.</p></article></div> : null}</section><SiteFooter /></main>;
}
